[install]
minimumReleaseAge = 259200
minimumReleaseAgeExcludes = [
  "effect",
  "rolldown",
  "@oxc-project/types",
  "@rolldown/pluginutils",
  "@rolldown/binding-darwin-x64",
  "@rolldown/binding-darwin-arm64",
  "@rolldown/binding-linux-x64-gnu",
  "@rolldown/binding-linux-x64-musl",
  "@rolldown/binding-linux-arm64-gnu",
  "@rolldown/binding-linux-arm64-musl",
  "@rolldown/binding-linux-arm-gnueabihf",
  "@rolldown/binding-win32-x64-msvc",
  "@rolldown/binding-win32-arm64-msvc",
  "@rolldown/binding-freebsd-x64",
  "@rolldown/binding-openharmony-arm64",
  "@rolldown/binding-android-arm64",
  "@rolldown/binding-wasm32-wasi",
  "@rolldown/binding-linux-s390x-gnu",
  "@rolldown/binding-linux-ppc64-gnu",
  "fast-check",
  "@effect/platform-bun",
  "@effect/platform-node",
  "@effect/vitest",
  "@effect/platform-node-shared",
  "typescript",
  "@typescript/typescript-win32-x64",
  "@typescript/typescript-win32-arm64",
  "@typescript/typescript-linux-x64",
  "@typescript/typescript-linux-arm",
  "@typescript/typescript-linux-arm64",
  "@typescript/typescript-darwin-x64",
  "@typescript/typescript-darwin-arm64",
  "@typescript/typescript-aix-ppc64",
  "@typescript/typescript-freebsd-arm64",
  "@typescript/typescript-freebsd-x64",
  "@typescript/typescript-linux-loong64",
  "@typescript/typescript-linux-mips64el",
  "@typescript/typescript-linux-ppc64",
  "@typescript/typescript-linux-riscv64",
  "@typescript/typescript-linux-s390x",
  "@typescript/typescript-netbsd-arm64",
  "@typescript/typescript-netbsd-x64",
  "@typescript/typescript-openbsd-arm64",
  "@typescript/typescript-openbsd-x64",
  "@typescript/typescript-sunos-x64",
]
