packages:
  - packages/*

allowBuilds:
  msgpackr-extract: true

catalogs:
  aws:
    "@aws-crypto/crc32": ^5.2.0
    "@aws-crypto/util": ^5.2.0
    "@aws-sdk/credential-providers": ^3.994.0
    "@aws-sdk/types": ^3.973.1
    "@smithy/shared-ini-file-loader": ^4.4.3
    "@smithy/types": ^4.12.0
    "@smithy/util-base64": ^4.3.0
    aws4fetch: ^1.0.20
  build:
    typescript: ^7.0.2
  effect:
    "@effect/platform-bun": ">=4.0.0-rc.112 || >=4.0.0"
    effect: ">=4.0.0-rc.112 || >=4.0.0"
  shared:
    fast-xml-parser: ^5.3.4
  tooling:
    "@types/bun": latest
    "@types/node": latest
    dedent: ^1.7.0
    husky: ^9.1.7
    oxfmt: latest
    oxlint: latest
    pathe: ^2.0.3

minimumReleaseAgeExclude:
  - "@effect/platform-bun@4.0.0-rc.112"
  - "@effect/platform-node-shared@4.0.0-rc.112"
  - effect@4.0.0-rc.112
