// Auto-generated service metadata
export const serviceMetadata = {
  "lookoutmetrics": {
    sdkId: "LookoutMetrics",
    endpointPrefix: "",
    protocol: "unknown",
    targetPrefix: "",
  },
  "sso-admin": {
    sdkId: "SSO Admin",
    endpointPrefix: "sso",
    protocol: "json",
    targetPrefix: "SWBExternalService",
  },
  "frauddetector": {
    sdkId: "FraudDetector",
    endpointPrefix: "frauddetector",
    protocol: "json",
    targetPrefix: "AWSHawksNestServiceFacade",
  },
  "braket": {
    sdkId: "Braket",
    endpointPrefix: "",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "accessanalyzer": {
    sdkId: "AccessAnalyzer",
    endpointPrefix: "",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "efs": {
    sdkId: "EFS",
    endpointPrefix: "elasticfilesystem",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "kafkaconnect": {
    sdkId: "KafkaConnect",
    endpointPrefix: "kafkaconnect",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "macie2": {
    sdkId: "Macie2",
    endpointPrefix: "macie2",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "iam": {
    sdkId: "IAM",
    endpointPrefix: "iam",
    protocol: "unknown",
    targetPrefix: "",
  },
  "mediastore": {
    sdkId: "MediaStore",
    endpointPrefix: "mediastore",
    protocol: "json",
    targetPrefix: "MediaStore_20170901",
  },
  "elasticache": {
    sdkId: "ElastiCache",
    endpointPrefix: "elasticache",
    protocol: "unknown",
    targetPrefix: "",
  },
  "lex-runtime-v2": {
    sdkId: "Lex Runtime V2",
    endpointPrefix: "runtime-v2-lex",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "athena": {
    sdkId: "Athena",
    endpointPrefix: "athena",
    protocol: "json",
    targetPrefix: "AmazonAthena",
  },
  "cloud9": {
    sdkId: "Cloud9",
    endpointPrefix: "cloud9",
    protocol: "json",
    targetPrefix: "AWSCloud9WorkspaceManagementService",
  },
  "lookoutequipment": {
    sdkId: "LookoutEquipment",
    endpointPrefix: "lookoutequipment",
    protocol: "json",
    targetPrefix: "AWSLookoutEquipmentFrontendService",
  },
  "iotfleethub": {
    sdkId: "IoTFleetHub",
    endpointPrefix: "api.fleethub.iot",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "bedrock-agent-runtime": {
    sdkId: "Bedrock Agent Runtime",
    endpointPrefix: "bedrock-agent-runtime",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "guardduty": {
    sdkId: "GuardDuty",
    endpointPrefix: "guardduty",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "securitylake": {
    sdkId: "SecurityLake",
    endpointPrefix: "",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "wellarchitected": {
    sdkId: "WellArchitected",
    endpointPrefix: "wellarchitected",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "translate": {
    sdkId: "Translate",
    endpointPrefix: "translate",
    protocol: "json",
    targetPrefix: "AWSShineFrontendService_20170701",
  },
  "amp": {
    sdkId: "amp",
    endpointPrefix: "",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "transcribe-streaming": {
    sdkId: "Transcribe Streaming",
    endpointPrefix: "transcribestreaming",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "iotdeviceadvisor": {
    sdkId: "IotDeviceAdvisor",
    endpointPrefix: "api.iotdeviceadvisor",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "rum": {
    sdkId: "RUM",
    endpointPrefix: "",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "migrationhub-config": {
    sdkId: "MigrationHub Config",
    endpointPrefix: "migrationhub-config",
    protocol: "json",
    targetPrefix: "AWSMigrationHubMultiAccountService",
  },
  "dataexchange": {
    sdkId: "DataExchange",
    endpointPrefix: "",
    protocol: "unknown",
    targetPrefix: "",
  },
  "connect": {
    sdkId: "Connect",
    endpointPrefix: "",
    protocol: "unknown",
    targetPrefix: "",
  },
  "datasync": {
    sdkId: "DataSync",
    endpointPrefix: "datasync",
    protocol: "json",
    targetPrefix: "FmrsService",
  },
  "workmailmessageflow": {
    sdkId: "WorkMailMessageFlow",
    endpointPrefix: "workmailmessageflow",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "workmail": {
    sdkId: "WorkMail",
    endpointPrefix: "workmail",
    protocol: "json",
    targetPrefix: "WorkMailService",
  },
  "wisdom": {
    sdkId: "Wisdom",
    endpointPrefix: "",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "eventbridge": {
    sdkId: "EventBridge",
    endpointPrefix: "events",
    protocol: "json",
    targetPrefix: "AWSEvents",
  },
  "fis": {
    sdkId: "fis",
    endpointPrefix: "",
    protocol: "unknown",
    targetPrefix: "",
  },
  "codeguru-reviewer": {
    sdkId: "CodeGuru Reviewer",
    endpointPrefix: "codeguru-reviewer",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "secrets-manager": {
    sdkId: "Secrets Manager",
    endpointPrefix: "",
    protocol: "unknown",
    targetPrefix: "",
  },
  "cost-explorer": {
    sdkId: "Cost Explorer",
    endpointPrefix: "ce",
    protocol: "json",
    targetPrefix: "AWSInsightsIndexService",
  },
  "appstream": {
    sdkId: "AppStream",
    endpointPrefix: "appstream2",
    protocol: "json",
    targetPrefix: "PhotonAdminProxyService",
  },
  "kafka": {
    sdkId: "Kafka",
    endpointPrefix: "kafka",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "elastic-load-balancing-v2": {
    sdkId: "Elastic Load Balancing v2",
    endpointPrefix: "elasticloadbalancing",
    protocol: "unknown",
    targetPrefix: "",
  },
  "appconfig": {
    sdkId: "AppConfig",
    endpointPrefix: "",
    protocol: "unknown",
    targetPrefix: "",
  },
  "sso-oidc": {
    sdkId: "SSO OIDC",
    endpointPrefix: "oidc",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "fms": {
    sdkId: "FMS",
    endpointPrefix: "fms",
    protocol: "json",
    targetPrefix: "AWSFMS_20180101",
  },
  "panorama": {
    sdkId: "Panorama",
    endpointPrefix: "",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "glacier": {
    sdkId: "Glacier",
    endpointPrefix: "glacier",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "iotanalytics": {
    sdkId: "IoTAnalytics",
    endpointPrefix: "",
    protocol: "unknown",
    targetPrefix: "",
  },
  "mediatailor": {
    sdkId: "MediaTailor",
    endpointPrefix: "api.mediatailor",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "cloudformation": {
    sdkId: "CloudFormation",
    endpointPrefix: "cloudformation",
    protocol: "unknown",
    targetPrefix: "",
  },
  "cloudwatch-logs": {
    sdkId: "CloudWatch Logs",
    endpointPrefix: "logs",
    protocol: "json",
    targetPrefix: "Logs_20140328",
  },
  "drs": {
    sdkId: "drs",
    endpointPrefix: "",
    protocol: "unknown",
    targetPrefix: "",
  },
  "chime-sdk-messaging": {
    sdkId: "Chime SDK Messaging",
    endpointPrefix: "messaging-chime",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "omics": {
    sdkId: "Omics",
    endpointPrefix: "",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "waf": {
    sdkId: "WAF",
    endpointPrefix: "waf",
    protocol: "json",
    targetPrefix: "AWSWAF_20150824",
  },
  "dlm": {
    sdkId: "DLM",
    endpointPrefix: "dlm",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "pinpoint": {
    sdkId: "Pinpoint",
    endpointPrefix: "pinpoint",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "fsx": {
    sdkId: "FSx",
    endpointPrefix: "fsx",
    protocol: "json",
    targetPrefix: "AWSSimbaAPIService_v20180301",
  },
  "migrationhubstrategy": {
    sdkId: "MigrationHubStrategy",
    endpointPrefix: "migrationhub-strategy",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "ebs": {
    sdkId: "EBS",
    endpointPrefix: "ebs",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "personalize": {
    sdkId: "Personalize",
    endpointPrefix: "personalize",
    protocol: "json",
    targetPrefix: "AmazonPersonalize",
  },
  "mediaconvert": {
    sdkId: "MediaConvert",
    endpointPrefix: "mediaconvert",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "cloudwatch": {
    sdkId: "CloudWatch",
    endpointPrefix: "monitoring",
    protocol: "unknown",
    targetPrefix: "",
  },
  "mediaconnect": {
    sdkId: "MediaConnect",
    endpointPrefix: "",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "backup": {
    sdkId: "Backup",
    endpointPrefix: "backup",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "wafv2": {
    sdkId: "WAFV2",
    endpointPrefix: "wafv2",
    protocol: "json",
    targetPrefix: "AWSWAF_20190729",
  },
  "appsync": {
    sdkId: "AppSync",
    endpointPrefix: "appsync",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "amplifybackend": {
    sdkId: "AmplifyBackend",
    endpointPrefix: "amplifybackend",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "transfer": {
    sdkId: "Transfer",
    endpointPrefix: "transfer",
    protocol: "json",
    targetPrefix: "TransferService",
  },
  "api-gateway": {
    sdkId: "API Gateway",
    endpointPrefix: "apigateway",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "location": {
    sdkId: "Location",
    endpointPrefix: "",
    protocol: "unknown",
    targetPrefix: "",
  },
  "health": {
    sdkId: "Health",
    endpointPrefix: "health",
    protocol: "json",
    targetPrefix: "AWSHealth_20160804",
  },
  "savingsplans": {
    sdkId: "savingsplans",
    endpointPrefix: "savingsplans",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "verifiedpermissions": {
    sdkId: "VerifiedPermissions",
    endpointPrefix: "verifiedpermissions",
    protocol: "json",
    targetPrefix: "VerifiedPermissions",
  },
  "mwaa": {
    sdkId: "MWAA",
    endpointPrefix: "",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "signer": {
    sdkId: "signer",
    endpointPrefix: "signer",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "servicediscovery": {
    sdkId: "ServiceDiscovery",
    endpointPrefix: "servicediscovery",
    protocol: "json",
    targetPrefix: "Route53AutoNaming_v20170314",
  },
  "codebuild": {
    sdkId: "CodeBuild",
    endpointPrefix: "codebuild",
    protocol: "json",
    targetPrefix: "CodeBuild_20161006",
  },
  "appconfigdata": {
    sdkId: "AppConfigData",
    endpointPrefix: "appconfigdata",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "ecr": {
    sdkId: "ECR",
    endpointPrefix: "api.ecr",
    protocol: "json",
    targetPrefix: "AmazonEC2ContainerRegistry_V20150921",
  },
  "networkmanager": {
    sdkId: "NetworkManager",
    endpointPrefix: "networkmanager",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "emr-serverless": {
    sdkId: "EMR Serverless",
    endpointPrefix: "",
    protocol: "unknown",
    targetPrefix: "",
  },
  "identitystore": {
    sdkId: "identitystore",
    endpointPrefix: "identitystore",
    protocol: "json",
    targetPrefix: "AWSIdentityStore",
  },
  "grafana": {
    sdkId: "grafana",
    endpointPrefix: "",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "greengrassv2": {
    sdkId: "GreengrassV2",
    endpointPrefix: "",
    protocol: "unknown",
    targetPrefix: "",
  },
  "dynamodb-streams": {
    sdkId: "DynamoDB Streams",
    endpointPrefix: "streams.dynamodb",
    protocol: "json",
    targetPrefix: "DynamoDBStreams_20120810",
  },
  "codeguruprofiler": {
    sdkId: "CodeGuruProfiler",
    endpointPrefix: "codeguru-profiler",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "oam": {
    sdkId: "OAM",
    endpointPrefix: "",
    protocol: "unknown",
    targetPrefix: "",
  },
  "sso": {
    sdkId: "SSO",
    endpointPrefix: "portal.sso",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "comprehendmedical": {
    sdkId: "ComprehendMedical",
    endpointPrefix: "comprehendmedical",
    protocol: "json",
    targetPrefix: "ComprehendMedical_20181030",
  },
  "sagemaker": {
    sdkId: "SageMaker",
    endpointPrefix: "api.sagemaker",
    protocol: "json",
    targetPrefix: "SageMaker",
  },
  "qldb": {
    sdkId: "QLDB",
    endpointPrefix: "qldb",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "s3-control": {
    sdkId: "S3 Control",
    endpointPrefix: "",
    protocol: "unknown",
    targetPrefix: "",
  },
  "route53resolver": {
    sdkId: "Route53Resolver",
    endpointPrefix: "route53resolver",
    protocol: "json",
    targetPrefix: "Route53Resolver",
  },
  "organizations": {
    sdkId: "Organizations",
    endpointPrefix: "organizations",
    protocol: "json",
    targetPrefix: "AWSOrganizationsV20161128",
  },
  "personalize-events": {
    sdkId: "Personalize Events",
    endpointPrefix: "personalize-events",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "shield": {
    sdkId: "Shield",
    endpointPrefix: "shield",
    protocol: "json",
    targetPrefix: "AWSShield_20160616",
  },
  "cloudhsm": {
    sdkId: "CloudHSM",
    endpointPrefix: "cloudhsm",
    protocol: "json",
    targetPrefix: "CloudHsmFrontendService",
  },
  "pipes": {
    sdkId: "Pipes",
    endpointPrefix: "pipes",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "ecs": {
    sdkId: "ECS",
    endpointPrefix: "ecs",
    protocol: "json",
    targetPrefix: "AmazonEC2ContainerServiceV20141113",
  },
  "marketplace-catalog": {
    sdkId: "Marketplace Catalog",
    endpointPrefix: "catalog.marketplace",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "inspector": {
    sdkId: "Inspector",
    endpointPrefix: "inspector",
    protocol: "json",
    targetPrefix: "InspectorService",
  },
  "acm": {
    sdkId: "ACM",
    endpointPrefix: "acm",
    protocol: "json",
    targetPrefix: "CertificateManager",
  },
  "workspaces": {
    sdkId: "WorkSpaces",
    endpointPrefix: "workspaces",
    protocol: "json",
    targetPrefix: "WorkspacesService",
  },
  "polly": {
    sdkId: "Polly",
    endpointPrefix: "polly",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "greengrass": {
    sdkId: "Greengrass",
    endpointPrefix: "greengrass",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "opsworks": {
    sdkId: "OpsWorks",
    endpointPrefix: "opsworks",
    protocol: "json",
    targetPrefix: "OpsWorks_20130218",
  },
  "ses": {
    sdkId: "SES",
    endpointPrefix: "email",
    protocol: "unknown",
    targetPrefix: "",
  },
  "iotsitewise": {
    sdkId: "IoTSiteWise",
    endpointPrefix: "iotsitewise",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "lookoutvision": {
    sdkId: "LookoutVision",
    endpointPrefix: "lookoutvision",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "cognito-identity-provider": {
    sdkId: "Cognito Identity Provider",
    endpointPrefix: "",
    protocol: "unknown",
    targetPrefix: "",
  },
  "database-migration-service": {
    sdkId: "Database Migration Service",
    endpointPrefix: "dms",
    protocol: "json",
    targetPrefix: "AmazonDMSv20160101",
  },
  "clouddirectory": {
    sdkId: "CloudDirectory",
    endpointPrefix: "clouddirectory",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "glue": {
    sdkId: "Glue",
    endpointPrefix: "glue",
    protocol: "json",
    targetPrefix: "AWSGlue",
  },
  "redshift-data": {
    sdkId: "Redshift Data",
    endpointPrefix: "",
    protocol: "json",
    targetPrefix: "RedshiftData",
  },
  "serverlessapplicationrepository": {
    sdkId: "ServerlessApplicationRepository",
    endpointPrefix: "serverlessrepo",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "synthetics": {
    sdkId: "synthetics",
    endpointPrefix: "synthetics",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "ec2": {
    sdkId: "EC2",
    endpointPrefix: "ec2",
    protocol: "unknown",
    targetPrefix: "",
  },
  "device-farm": {
    sdkId: "Device Farm",
    endpointPrefix: "devicefarm",
    protocol: "json",
    targetPrefix: "DeviceFarm_20150623",
  },
  "apigatewaymanagementapi": {
    sdkId: "ApiGatewayManagementApi",
    endpointPrefix: "execute-api",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "account": {
    sdkId: "Account",
    endpointPrefix: "",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "acm-pca": {
    sdkId: "ACM PCA",
    endpointPrefix: "",
    protocol: "unknown",
    targetPrefix: "",
  },
  "service-quotas": {
    sdkId: "Service Quotas",
    endpointPrefix: "servicequotas",
    protocol: "json",
    targetPrefix: "ServiceQuotasV20190624",
  },
  "cleanrooms": {
    sdkId: "CleanRooms",
    endpointPrefix: "",
    protocol: "unknown",
    targetPrefix: "",
  },
  "cloudsearch": {
    sdkId: "CloudSearch",
    endpointPrefix: "cloudsearch",
    protocol: "unknown",
    targetPrefix: "",
  },
  "resiliencehub": {
    sdkId: "resiliencehub",
    endpointPrefix: "resiliencehub",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "opensearch": {
    sdkId: "OpenSearch",
    endpointPrefix: "es",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "finspace": {
    sdkId: "finspace",
    endpointPrefix: "finspace",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "detective": {
    sdkId: "Detective",
    endpointPrefix: "api.detective",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "iotthingsgraph": {
    sdkId: "IoTThingsGraph",
    endpointPrefix: "iotthingsgraph",
    protocol: "json",
    targetPrefix: "IotThingsGraphFrontEndService",
  },
  "s3": {
    sdkId: "S3",
    endpointPrefix: "s3",
    protocol: "unknown",
    targetPrefix: "",
  },
  "cognito-sync": {
    sdkId: "Cognito Sync",
    endpointPrefix: "cognito-sync",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "iotfleetwise": {
    sdkId: "IoTFleetWise",
    endpointPrefix: "",
    protocol: "unknown",
    targetPrefix: "",
  },
  "dax": {
    sdkId: "DAX",
    endpointPrefix: "dax",
    protocol: "json",
    targetPrefix: "AmazonDAXV3",
  },
  "xray": {
    sdkId: "XRay",
    endpointPrefix: "xray",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "auditmanager": {
    sdkId: "AuditManager",
    endpointPrefix: "auditmanager",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "lakeformation": {
    sdkId: "LakeFormation",
    endpointPrefix: "lakeformation",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "snowball": {
    sdkId: "Snowball",
    endpointPrefix: "snowball",
    protocol: "json",
    targetPrefix: "AWSIESnowballJobManagementService",
  },
  "elastic-beanstalk": {
    sdkId: "Elastic Beanstalk",
    endpointPrefix: "elasticbeanstalk",
    protocol: "unknown",
    targetPrefix: "",
  },
  "batch": {
    sdkId: "Batch",
    endpointPrefix: "batch",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "transcribe": {
    sdkId: "Transcribe",
    endpointPrefix: "transcribe",
    protocol: "json",
    targetPrefix: "Transcribe",
  },
  "elastic-transcoder": {
    sdkId: "Elastic Transcoder",
    endpointPrefix: "elastictranscoder",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "managedblockchain": {
    sdkId: "ManagedBlockchain",
    endpointPrefix: "managedblockchain",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "connectparticipant": {
    sdkId: "ConnectParticipant",
    endpointPrefix: "",
    protocol: "unknown",
    targetPrefix: "",
  },
  "databrew": {
    sdkId: "DataBrew",
    endpointPrefix: "databrew",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "simspaceweaver": {
    sdkId: "SimSpaceWeaver",
    endpointPrefix: "simspaceweaver",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "neptune": {
    sdkId: "Neptune",
    endpointPrefix: "rds",
    protocol: "unknown",
    targetPrefix: "",
  },
  "apigatewayv2": {
    sdkId: "ApiGatewayV2",
    endpointPrefix: "apigateway",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "workdocs": {
    sdkId: "WorkDocs",
    endpointPrefix: "workdocs",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "connectcases": {
    sdkId: "ConnectCases",
    endpointPrefix: "",
    protocol: "unknown",
    targetPrefix: "",
  },
  "iottwinmaker": {
    sdkId: "IoTTwinMaker",
    endpointPrefix: "iottwinmaker",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "imagebuilder": {
    sdkId: "imagebuilder",
    endpointPrefix: "imagebuilder",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "ram": {
    sdkId: "RAM",
    endpointPrefix: "ram",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "eks": {
    sdkId: "EKS",
    endpointPrefix: "eks",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "tnb": {
    sdkId: "tnb",
    endpointPrefix: "",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "scheduler": {
    sdkId: "Scheduler",
    endpointPrefix: "",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "sts": {
    sdkId: "STS",
    endpointPrefix: "sts",
    protocol: "unknown",
    targetPrefix: "",
  },
  "ssm": {
    sdkId: "SSM",
    endpointPrefix: "",
    protocol: "unknown",
    targetPrefix: "",
  },
  "emr": {
    sdkId: "EMR",
    endpointPrefix: "elasticmapreduce",
    protocol: "json",
    targetPrefix: "ElasticMapReduce",
  },
  "sms": {
    sdkId: "SMS",
    endpointPrefix: "sms",
    protocol: "json",
    targetPrefix: "AWSServerMigrationService_V2016_10_24",
  },
  "sesv2": {
    sdkId: "SESv2",
    endpointPrefix: "email",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "mediapackage": {
    sdkId: "MediaPackage",
    endpointPrefix: "mediapackage",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "appintegrations": {
    sdkId: "AppIntegrations",
    endpointPrefix: "app-integrations",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "budgets": {
    sdkId: "Budgets",
    endpointPrefix: "budgets",
    protocol: "json",
    targetPrefix: "AWSBudgetServiceGateway",
  },
  "timestream-query": {
    sdkId: "Timestream Query",
    endpointPrefix: "",
    protocol: "unknown",
    targetPrefix: "",
  },
  "rds": {
    sdkId: "RDS",
    endpointPrefix: "rds",
    protocol: "unknown",
    targetPrefix: "",
  },
  "pricing": {
    sdkId: "Pricing",
    endpointPrefix: "",
    protocol: "unknown",
    targetPrefix: "",
  },
  "rbin": {
    sdkId: "rbin",
    endpointPrefix: "rbin",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "schemas": {
    sdkId: "schemas",
    endpointPrefix: "schemas",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "sfn": {
    sdkId: "SFN",
    endpointPrefix: "",
    protocol: "unknown",
    targetPrefix: "",
  },
  "mgn": {
    sdkId: "mgn",
    endpointPrefix: "",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "chime": {
    sdkId: "Chime",
    endpointPrefix: "chime",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "support": {
    sdkId: "Support",
    endpointPrefix: "support",
    protocol: "json",
    targetPrefix: "AWSSupport_20130415",
  },
  "kms": {
    sdkId: "KMS",
    endpointPrefix: "kms",
    protocol: "json",
    targetPrefix: "TrentService",
  },
  "m2": {
    sdkId: "m2",
    endpointPrefix: "",
    protocol: "unknown",
    targetPrefix: "",
  },
  "gamelift": {
    sdkId: "GameLift",
    endpointPrefix: "gamelift",
    protocol: "json",
    targetPrefix: "GameLift",
  },
  "sagemaker-runtime": {
    sdkId: "SageMaker Runtime",
    endpointPrefix: "runtime.sagemaker",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "sqs": {
    sdkId: "SQS",
    endpointPrefix: "sqs",
    protocol: "json",
    targetPrefix: "AmazonSQS",
  },
  "connectcampaigns": {
    sdkId: "ConnectCampaigns",
    endpointPrefix: "",
    protocol: "unknown",
    targetPrefix: "",
  },
  "opensearchserverless": {
    sdkId: "OpenSearchServerless",
    endpointPrefix: "",
    protocol: "json",
    targetPrefix: "OpenSearchServerless",
  },
  "kinesis-video": {
    sdkId: "Kinesis Video",
    endpointPrefix: "kinesisvideo",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "rekognition": {
    sdkId: "Rekognition",
    endpointPrefix: "rekognition",
    protocol: "json",
    targetPrefix: "RekognitionService",
  },
  "kinesis-analytics": {
    sdkId: "Kinesis Analytics",
    endpointPrefix: "kinesisanalytics",
    protocol: "json",
    targetPrefix: "KinesisAnalytics_20150814",
  },
  "forecast": {
    sdkId: "forecast",
    endpointPrefix: "forecast",
    protocol: "json",
    targetPrefix: "AmazonForecast",
  },
  "s3outposts": {
    sdkId: "S3Outposts",
    endpointPrefix: "s3-outposts",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "groundstation": {
    sdkId: "GroundStation",
    endpointPrefix: "",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "amplify": {
    sdkId: "Amplify",
    endpointPrefix: "amplify",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "firehose": {
    sdkId: "Firehose",
    endpointPrefix: "firehose",
    protocol: "json",
    targetPrefix: "Firehose_20150804",
  },
  "service-catalog": {
    sdkId: "Service Catalog",
    endpointPrefix: "servicecatalog",
    protocol: "json",
    targetPrefix: "AWS242ServiceCatalogService",
  },
  "inspector2": {
    sdkId: "Inspector2",
    endpointPrefix: "",
    protocol: "unknown",
    targetPrefix: "",
  },
  "kendra": {
    sdkId: "kendra",
    endpointPrefix: "kendra",
    protocol: "json",
    targetPrefix: "AWSKendraFrontendService",
  },
  "appflow": {
    sdkId: "Appflow",
    endpointPrefix: "",
    protocol: "unknown",
    targetPrefix: "",
  },
  "cloudcontrol": {
    sdkId: "CloudControl",
    endpointPrefix: "cloudcontrolapi",
    protocol: "json",
    targetPrefix: "CloudApiService",
  },
  "applicationcostprofiler": {
    sdkId: "ApplicationCostProfiler",
    endpointPrefix: "application-cost-profiler",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "route-53": {
    sdkId: "Route 53",
    endpointPrefix: "route53",
    protocol: "unknown",
    targetPrefix: "",
  },
  "redshift": {
    sdkId: "Redshift",
    endpointPrefix: "redshift",
    protocol: "unknown",
    targetPrefix: "",
  },
  "elasticsearch-service": {
    sdkId: "Elasticsearch Service",
    endpointPrefix: "es",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "auto-scaling": {
    sdkId: "Auto Scaling",
    endpointPrefix: "autoscaling",
    protocol: "unknown",
    targetPrefix: "",
  },
  "timestream-write": {
    sdkId: "Timestream Write",
    endpointPrefix: "",
    protocol: "unknown",
    targetPrefix: "",
  },
  "lambda": {
    sdkId: "Lambda",
    endpointPrefix: "",
    protocol: "unknown",
    targetPrefix: "",
  },
  "quicksight": {
    sdkId: "QuickSight",
    endpointPrefix: "",
    protocol: "unknown",
    targetPrefix: "",
  },
  "codepipeline": {
    sdkId: "CodePipeline",
    endpointPrefix: "codepipeline",
    protocol: "json",
    targetPrefix: "CodePipeline_20150709",
  },
  "cloudfront": {
    sdkId: "CloudFront",
    endpointPrefix: "cloudfront",
    protocol: "unknown",
    targetPrefix: "",
  },
  "config-service": {
    sdkId: "Config Service",
    endpointPrefix: "",
    protocol: "unknown",
    targetPrefix: "",
  },
  "memorydb": {
    sdkId: "MemoryDB",
    endpointPrefix: "memory-db",
    protocol: "json",
    targetPrefix: "AmazonMemoryDB",
  },
  "lightsail": {
    sdkId: "Lightsail",
    endpointPrefix: "lightsail",
    protocol: "json",
    targetPrefix: "Lightsail_20161128",
  },
  "bedrock": {
    sdkId: "Bedrock",
    endpointPrefix: "bedrock",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "comprehend": {
    sdkId: "Comprehend",
    endpointPrefix: "comprehend",
    protocol: "json",
    targetPrefix: "Comprehend_20171127",
  },
  "robomaker": {
    sdkId: "RoboMaker",
    endpointPrefix: "robomaker",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "resource-groups": {
    sdkId: "Resource Groups",
    endpointPrefix: "resource-groups",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "evidently": {
    sdkId: "Evidently",
    endpointPrefix: "",
    protocol: "unknown",
    targetPrefix: "",
  },
  "docdb": {
    sdkId: "DocDB",
    endpointPrefix: "rds",
    protocol: "unknown",
    targetPrefix: "",
  },
  "mq": {
    sdkId: "mq",
    endpointPrefix: "mq",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "kinesis": {
    sdkId: "Kinesis",
    endpointPrefix: "kinesis",
    protocol: "json",
    targetPrefix: "Kinesis_20131202",
  },
  "pi": {
    sdkId: "PI",
    endpointPrefix: "pi",
    protocol: "json",
    targetPrefix: "PerformanceInsightsv20180227",
  },
  "customer-profiles": {
    sdkId: "Customer Profiles",
    endpointPrefix: "",
    protocol: "unknown",
    targetPrefix: "",
  },
  "marketplace-entitlement-service": {
    sdkId: "Marketplace Entitlement Service",
    endpointPrefix: "entitlement.marketplace",
    protocol: "json",
    targetPrefix: "AWSMPEntitlementService",
  },
  "lex-runtime-service": {
    sdkId: "Lex Runtime Service",
    endpointPrefix: "runtime.lex",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "swf": {
    sdkId: "SWF",
    endpointPrefix: "swf",
    protocol: "json",
    targetPrefix: "SimpleWorkflowService",
  },
  "migrationhuborchestrator": {
    sdkId: "MigrationHubOrchestrator",
    endpointPrefix: "migrationhub-orchestrator",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "keyspaces": {
    sdkId: "Keyspaces",
    endpointPrefix: "cassandra",
    protocol: "json",
    targetPrefix: "KeyspacesService",
  },
  "mturk": {
    sdkId: "MTurk",
    endpointPrefix: "mturk-requester",
    protocol: "json",
    targetPrefix: "MTurkRequesterServiceV20170117",
  },
  "outposts": {
    sdkId: "Outposts",
    endpointPrefix: "outposts",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "pinpoint-email": {
    sdkId: "Pinpoint Email",
    endpointPrefix: "email",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "ivschat": {
    sdkId: "ivschat",
    endpointPrefix: "",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "rds-data": {
    sdkId: "RDS Data",
    endpointPrefix: "",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "medialive": {
    sdkId: "MediaLive",
    endpointPrefix: "medialive",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "bedrock-agent": {
    sdkId: "Bedrock Agent",
    endpointPrefix: "",
    protocol: "unknown",
    targetPrefix: "",
  },
  "cognito-identity": {
    sdkId: "Cognito Identity",
    endpointPrefix: "",
    protocol: "unknown",
    targetPrefix: "",
  },
  "cloudtrail": {
    sdkId: "CloudTrail",
    endpointPrefix: "cloudtrail",
    protocol: "json",
    targetPrefix: "CloudTrail_20131101",
  },
  "forecastquery": {
    sdkId: "forecastquery",
    endpointPrefix: "forecastquery",
    protocol: "json",
    targetPrefix: "AmazonForecastRuntime",
  },
  "cloudwatch-events": {
    sdkId: "CloudWatch Events",
    endpointPrefix: "events",
    protocol: "json",
    targetPrefix: "AWSEvents",
  },
  "amplifyuibuilder": {
    sdkId: "AmplifyUIBuilder",
    endpointPrefix: "",
    protocol: "unknown",
    targetPrefix: "",
  },
  "apprunner": {
    sdkId: "AppRunner",
    endpointPrefix: "apprunner",
    protocol: "json",
    targetPrefix: "AppRunner",
  },
  "sns": {
    sdkId: "SNS",
    endpointPrefix: "sns",
    protocol: "unknown",
    targetPrefix: "",
  },
  "textract": {
    sdkId: "Textract",
    endpointPrefix: "textract",
    protocol: "json",
    targetPrefix: "Textract",
  },
  "healthlake": {
    sdkId: "HealthLake",
    endpointPrefix: "healthlake",
    protocol: "json",
    targetPrefix: "HealthLake",
  },
  "iotsecuretunneling": {
    sdkId: "IoTSecureTunneling",
    endpointPrefix: "",
    protocol: "unknown",
    targetPrefix: "",
  },
  "iot": {
    sdkId: "IoT",
    endpointPrefix: "",
    protocol: "unknown",
    targetPrefix: "",
  },
  "iot-data-plane": {
    sdkId: "IoT Data Plane",
    endpointPrefix: "data-ats.iot",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "billingconductor": {
    sdkId: "billingconductor",
    endpointPrefix: "",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "dynamodb": {
    sdkId: "DynamoDB",
    endpointPrefix: "dynamodb",
    protocol: "json",
    targetPrefix: "DynamoDB_20120810",
  },
  "bedrock-runtime": {
    sdkId: "Bedrock Runtime",
    endpointPrefix: "bedrock-runtime",
    protocol: "rest-json",
    targetPrefix: "",
  },
  "codecommit": {
    sdkId: "CodeCommit",
    endpointPrefix: "codecommit",
    protocol: "json",
    targetPrefix: "CodeCommit_20150413",
  },
  "rolesanywhere": {
    sdkId: "RolesAnywhere",
    endpointPrefix: "",
    protocol: "rest-json",
    targetPrefix: "",
  },
} as const;
