openapi: 3.1.0
info:
  title: Cloudflare DCV-DELEGATION API
  version: 0.0.0
servers:
  - url: https://api.cloudflare.com/client/v4
x-distilled-service: dcv-delegation
paths:
  /zones/{zone_id}/dcv_delegation/uuid:
    get:
      operationId: getDcvDelegation
      description: Retrieve the account and zone specific unique identifier used as
        part of the CNAME target for DCV Delegation.
      parameters:
        - name: zone_id
          in: path
          required: true
          description: Identifier.
          schema:
            type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  uuid:
                    type: string
                    description: The DCV Delegation unique identifier.
      x-distilled-response-path: result
