// AUTO-GENERATED by scripts/generate.ts from .generated-specs (specs/rest-api-description). Do not edit.
import * as S from "@distilled.cloud/core/schema";
import * as API from "@distilled.cloud/core/api";
import * as C from "@distilled.cloud/core/category";
import * as T from "../traits.ts";
import {
  GithubProtocol,
  type GithubOpError,
  type GithubOpContext,
} from "../protocol.ts";
import * as Retry from "../retry.ts";

export type { GithubOpError, GithubOpContext };

export class BadRequest
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<BadRequest>()("BadRequest", {
      code: S.Number,
      message: S.String,
    }).pipe(C.withBadRequestError),
    [{ status: 400 }],
  ) {}

export class Forbidden
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<Forbidden>()("Forbidden", {
      code: S.Number,
      message: S.String,
    }).pipe(C.withAuthError),
    [{ status: 403 }],
  ) {}

export class NotFound
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<NotFound>()("NotFound", {
      code: S.Number,
      message: S.String,
    }).pipe(C.withBadRequestError),
    [{ status: 404 }],
  ) {}

export class UnprocessableEntity
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<UnprocessableEntity>()("UnprocessableEntity", {
      code: S.Number,
      message: S.String,
    }).pipe(C.withBadRequestError),
    [{ status: 422 }],
  ) {}

/** Array of user login names who will receive alerts */
export type CreateOrganizationBudgetRequestBudgetAlertingAlertRecipientsList =
  Array<string>;
export const CreateOrganizationBudgetRequestBudgetAlertingAlertRecipientsList =
  /*@__PURE__*/ S.Array(
    S.String,
  ) as any as S.Schema<CreateOrganizationBudgetRequestBudgetAlertingAlertRecipientsList>;

export interface CreateOrganizationBudgetRequestBudgetAlerting {
  /** Whether alerts are enabled for this budget */
  will_alert?: boolean;
  /** Array of user login names who will receive alerts */
  alert_recipients?: CreateOrganizationBudgetRequestBudgetAlertingAlertRecipientsList;
}
export const CreateOrganizationBudgetRequestBudgetAlerting =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      will_alert: S.optional(S.Boolean),
      alert_recipients: S.optional(
        CreateOrganizationBudgetRequestBudgetAlertingAlertRecipientsList,
      ),
    }),
  ).annotate({
    identifier: "CreateOrganizationBudgetRequestBudgetAlerting",
  }) as any as S.Schema<CreateOrganizationBudgetRequestBudgetAlerting>;

/** The scope of the budget for this organization. - `organization`: Apply the budget to the organization. - `repository`: Apply the budget to a specific repository in the organization. - `multi_user_customer`: Apply a universal budget to all users in the organization. - `user`: Apply the budget to a single user in the organization. `user` and `multi_user_customer` scopes are only supported when `budget_product_sku` is `ai_credits` or `premium_requests`. */
export type CreateOrganizationBudgetRequestBudgetScope =
  | "organization"
  | "repository"
  | "multi_user_customer"
  | "user";
export const CreateOrganizationBudgetRequestBudgetScope =
  /*@__PURE__*/ S.String;

export type CreateOrganizationBudgetRequestBudgetTypeCase0 = "BundlePricing";
export const CreateOrganizationBudgetRequestBudgetTypeCase0 =
  /*@__PURE__*/ S.String;

export type CreateOrganizationBudgetRequestBudgetTypeCase1 = "ProductPricing";
export const CreateOrganizationBudgetRequestBudgetTypeCase1 =
  /*@__PURE__*/ S.String;

export type CreateOrganizationBudgetRequestBudgetTypeCase2 = "SkuPricing";
export const CreateOrganizationBudgetRequestBudgetTypeCase2 =
  /*@__PURE__*/ S.String;

/** The type of pricing model used by the budget. Determines how `budget_product_sku` is interpreted. - `BundlePricing`: Covers all AI credit SKUs. Set `budget_product_sku` to `ai_credits`. - `ProductPricing`: Covers all SKUs that belong to a product. Set `budget_product_sku` to a product such as `actions` or `packages`. - `SkuPricing`: Covers a single, specific SKU. Set `budget_product_sku` to a SKU such as `actions_linux`. */
export type CreateOrganizationBudgetRequestBudgetType =
  | CreateOrganizationBudgetRequestBudgetTypeCase0
  | CreateOrganizationBudgetRequestBudgetTypeCase1
  | CreateOrganizationBudgetRequestBudgetTypeCase2;
export const CreateOrganizationBudgetRequestBudgetType =
  /*@__PURE__*/ S.Unknown as any as S.Schema<CreateOrganizationBudgetRequestBudgetType>;

export interface CreateOrganizationBudgetRequest {
  /** The organization name. The name is not case sensitive. */
  org: string;
  /** The budget amount in whole dollars. For license-based products, this represents the number of licenses. */
  budget_amount?: number;
  /** Whether to prevent additional spending once the budget is exceeded. For `user` and `multi_user_customer` scopes, this must be `true`. */
  prevent_further_usage?: boolean;
  budget_alerting?: CreateOrganizationBudgetRequestBudgetAlerting;
  /** The scope of the budget for this organization. - `organization`: Apply the budget to the organization. - `repository`: Apply the budget to a specific repository in the organization. - `multi_user_customer`: Apply a universal budget to all users in the organization. - `user`: Apply the budget to a single user in the organization. `user` and `multi_user_customer` scopes are only supported when `budget_product_sku` is `ai_credits` or `premium_requests`. */
  budget_scope?: CreateOrganizationBudgetRequestBudgetScope | (string & {});
  /** The name of the entity to apply the budget to */
  budget_entity_name?: string;
  /** The type of pricing model used by the budget. Determines how `budget_product_sku` is interpreted. - `BundlePricing`: Covers all AI credit SKUs. Set `budget_product_sku` to `ai_credits`. - `ProductPricing`: Covers all SKUs that belong to a product. Set `budget_product_sku` to a product such as `actions` or `packages`. - `SkuPricing`: Covers a single, specific SKU. Set `budget_product_sku` to a SKU such as `actions_linux`. */
  budget_type?: CreateOrganizationBudgetRequestBudgetType;
  /** A single product or SKU that will be covered in the budget */
  budget_product_sku?: string;
  /** The username of the user for `user` scope budgets. This field is required when `budget_scope` is `user`. */
  user?: string;
}
export const CreateOrganizationBudgetRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    org: S.String.pipe(T.Label()),
    budget_amount: S.optional(S.Number),
    prevent_further_usage: S.optional(S.Boolean),
    budget_alerting: S.optional(CreateOrganizationBudgetRequestBudgetAlerting),
    budget_scope: S.optional(CreateOrganizationBudgetRequestBudgetScope),
    budget_entity_name: S.optional(S.String),
    budget_type: S.optional(CreateOrganizationBudgetRequestBudgetType),
    budget_product_sku: S.optional(S.String),
    user: S.optional(S.String),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/organizations/{org}/settings/billing/budgets",
      code: 200,
    }),
  ),
).annotate({
  identifier: "CreateOrganizationBudgetRequest",
}) as any as S.Schema<CreateOrganizationBudgetRequest>;

/** The type of scope for the budget */
export type CreateBudgetBudgetBudgetScope =
  | "enterprise"
  | "organization"
  | "repository"
  | "cost_center"
  | "multi_user_customer"
  | "multi_user_cost_center"
  | "user";
export const CreateBudgetBudgetBudgetScope = /*@__PURE__*/ S.String;

export type CreateBudgetBudgetBudgetTypeCase0 = "ProductPricing";
export const CreateBudgetBudgetBudgetTypeCase0 = /*@__PURE__*/ S.String;

export type CreateBudgetBudgetBudgetTypeCase1 = "SkuPricing";
export const CreateBudgetBudgetBudgetTypeCase1 = /*@__PURE__*/ S.String;

/** The type of pricing for the budget */
export type CreateBudgetBudgetBudgetType =
  | CreateBudgetBudgetBudgetTypeCase0
  | CreateBudgetBudgetBudgetTypeCase1;
export const CreateBudgetBudgetBudgetType =
  /*@__PURE__*/ S.Unknown as any as S.Schema<CreateBudgetBudgetBudgetType>;

/** Array of user login names who will receive alerts */
export type CreateBudgetBudgetBudgetAlertingAlertRecipientsList = Array<string>;
export const CreateBudgetBudgetBudgetAlertingAlertRecipientsList =
  /*@__PURE__*/ S.Array(
    S.String,
  ) as any as S.Schema<CreateBudgetBudgetBudgetAlertingAlertRecipientsList>;

export interface CreateBudgetBudgetBudgetAlerting {
  /** Whether alerts are enabled for this budget */
  will_alert?: boolean;
  /** Array of user login names who will receive alerts */
  alert_recipients?: CreateBudgetBudgetBudgetAlertingAlertRecipientsList;
}
export const CreateBudgetBudgetBudgetAlerting = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    will_alert: S.optional(S.Boolean),
    alert_recipients: S.optional(
      CreateBudgetBudgetBudgetAlertingAlertRecipientsList,
    ),
  }),
).annotate({
  identifier: "CreateBudgetBudgetBudgetAlerting",
}) as any as S.Schema<CreateBudgetBudgetBudgetAlerting>;

export interface CreateBudgetBudget {
  /** ID of the budget. */
  id?: string;
  /** The type of scope for the budget */
  budget_scope?: CreateBudgetBudgetBudgetScope;
  /** The name of the entity to apply the budget to */
  budget_entity_name?: string;
  /** The budget amount in whole dollars. For license-based products, this represents the number of licenses. */
  budget_amount?: number;
  /** Whether to prevent additional spending once the budget is exceeded */
  prevent_further_usage?: boolean;
  /** A single product or sku to apply the budget to. */
  budget_product_sku?: string;
  /** The type of pricing for the budget */
  budget_type?: CreateBudgetBudgetBudgetType;
  budget_alerting?: CreateBudgetBudgetBudgetAlerting;
}
export const CreateBudgetBudget = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.String),
    budget_scope: S.optional(CreateBudgetBudgetBudgetScope),
    budget_entity_name: S.optional(S.String),
    budget_amount: S.optional(S.Number),
    prevent_further_usage: S.optional(S.Boolean),
    budget_product_sku: S.optional(S.String),
    budget_type: S.optional(CreateBudgetBudgetBudgetType),
    budget_alerting: S.optional(CreateBudgetBudgetBudgetAlerting),
  }),
).annotate({
  identifier: "CreateBudgetBudget",
}) as any as S.Schema<CreateBudgetBudget>;

export interface CreateBudget {
  /** A message indicating the result of the create operation */
  message: string;
  budget: CreateBudgetBudget;
}
export const CreateBudget = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    message: S.String,
    budget: CreateBudgetBudget,
  }),
).annotate({ identifier: "CreateBudget" }) as any as S.Schema<CreateBudget>;

export interface DeleteBudgetOrgRequest {
  /** The organization name. The name is not case sensitive. */
  org: string;
  /** The ID corresponding to the budget. */
  budget_id: string;
}
export const DeleteBudgetOrgRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    org: S.String.pipe(T.Label()),
    budget_id: S.String.pipe(T.Label()),
  }).pipe(
    T.Http({
      method: "DELETE",
      uri: "/organizations/{org}/settings/billing/budgets/{budget_id}",
      code: 200,
    }),
  ),
).annotate({
  identifier: "DeleteBudgetOrgRequest",
}) as any as S.Schema<DeleteBudgetOrgRequest>;

export interface DeleteBudget {
  /** A message indicating the result of the deletion operation */
  message: string;
  /** The ID of the deleted budget */
  id: string;
}
export const DeleteBudget = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    message: S.String,
    id: S.String,
  }),
).annotate({ identifier: "DeleteBudget" }) as any as S.Schema<DeleteBudget>;

export type GetAllBudgetsOrgRequestScope =
  | "enterprise"
  | "organization"
  | "repository"
  | "cost_center"
  | "multi_user_customer"
  | "user";
export const GetAllBudgetsOrgRequestScope = /*@__PURE__*/ S.String;

export interface GetAllBudgetsOrgRequest {
  /** The organization name. The name is not case sensitive. */
  org: string;
  /** The page number of the results to fetch. */
  page?: number;
  /** The number of results per page (max 100). */
  per_page?: number;
  /** Filter budgets by scope type. - `organization`: Budgets scoped to the organization. - `repository`: Budgets scoped to a repository. - `multi_user_customer`: Universal budgets that apply to all users in the organization. - `user`: Budgets scoped to an individual user. */
  scope?: GetAllBudgetsOrgRequestScope | (string & {});
  /** Filter consumed amount details for budgets by the specified user login. */
  user?: string;
}
export const GetAllBudgetsOrgRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    org: S.String.pipe(T.Label()),
    page: S.optional(S.Number.pipe(T.Query())),
    per_page: S.optional(S.Number.pipe(T.Query())),
    scope: S.optional(GetAllBudgetsOrgRequestScope.pipe(T.Query())),
    user: S.optional(S.String.pipe(T.Query())),
  }).pipe(
    T.Http({
      method: "GET",
      uri: "/organizations/{org}/settings/billing/budgets",
      code: 200,
    }),
  ),
).annotate({
  identifier: "GetAllBudgetsOrgRequest",
}) as any as S.Schema<GetAllBudgetsOrgRequest>;

export type BudgetBudgetTypeCase0 = "SkuPricing";
export const BudgetBudgetTypeCase0 = /*@__PURE__*/ S.String;

export type BudgetBudgetTypeCase1 = "ProductPricing";
export const BudgetBudgetTypeCase1 = /*@__PURE__*/ S.String;

/** The type of pricing for the budget */
export type BudgetBudgetType = BudgetBudgetTypeCase0 | BudgetBudgetTypeCase1;
export const BudgetBudgetType =
  /*@__PURE__*/ S.Unknown as any as S.Schema<BudgetBudgetType>;

/** The scope of the budget */
export type BudgetBudgetScope =
  | "enterprise"
  | "organization"
  | "repository"
  | "cost_center"
  | "multi_user_customer"
  | "multi_user_cost_center"
  | "user";
export const BudgetBudgetScope = /*@__PURE__*/ S.String;

/** Array of user login names who will receive alerts */
export type BudgetBudgetAlertingAlertRecipientsList = Array<string>;
export const BudgetBudgetAlertingAlertRecipientsList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<BudgetBudgetAlertingAlertRecipientsList>;

export interface BudgetBudgetAlerting {
  /** Whether alerts are enabled for this budget */
  will_alert: boolean;
  /** Array of user login names who will receive alerts */
  alert_recipients: BudgetBudgetAlertingAlertRecipientsList;
}
export const BudgetBudgetAlerting = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    will_alert: S.Boolean,
    alert_recipients: BudgetBudgetAlertingAlertRecipientsList,
  }),
).annotate({
  identifier: "BudgetBudgetAlerting",
}) as any as S.Schema<BudgetBudgetAlerting>;

export interface Budget {
  /** The unique identifier for the budget */
  id: string;
  /** The type of pricing for the budget */
  budget_type: BudgetBudgetType;
  /** The budget amount limit in whole dollars. For license-based products, this represents the number of licenses. */
  budget_amount: number;
  /** The type of limit enforcement for the budget */
  prevent_further_usage: boolean;
  /** The scope of the budget */
  budget_scope: BudgetBudgetScope;
  /** The name of the entity for the budget (enterprise does not require a name). */
  budget_entity_name?: string;
  /** The user login when the budget is scoped to a single user (`user` scope). */
  user?: string;
  /** The amount consumed for a user-scoped budget, or for a multi-user budget when filtering by user. */
  consumed_amount?: number;
  /** A single product or sku to apply the budget to. */
  budget_product_sku: string;
  budget_alerting: BudgetBudgetAlerting;
}
export const Budget = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String,
    budget_type: BudgetBudgetType,
    budget_amount: S.Number,
    prevent_further_usage: S.Boolean,
    budget_scope: BudgetBudgetScope,
    budget_entity_name: S.optional(S.String),
    user: S.optional(S.String),
    consumed_amount: S.optional(S.Number),
    budget_product_sku: S.String,
    budget_alerting: BudgetBudgetAlerting,
  }),
).annotate({ identifier: "Budget" }) as any as S.Schema<Budget>;

/** Array of budget objects for the enterprise */
export type GetAllBudgetsBudgetsList = Array<Budget>;
export const GetAllBudgetsBudgetsList = /*@__PURE__*/ S.Array(
  Budget,
) as any as S.Schema<GetAllBudgetsBudgetsList>;

/** Effective user-level budget details returned when the response is scoped with the `user` query parameter. */
export interface GetAllBudgetsEffectiveBudget {
  /** The unique identifier of the effective budget. */
  id: string;
  /** The budget amount for the effective budget. */
  budget_amount: number;
  /** The consumed amount for the specified user within the effective budget. */
  consumed_amount: number;
}
export const GetAllBudgetsEffectiveBudget = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String,
    budget_amount: S.Number,
    consumed_amount: S.Number,
  }),
).annotate({
  identifier: "GetAllBudgetsEffectiveBudget",
}) as any as S.Schema<GetAllBudgetsEffectiveBudget>;

export interface GetAllBudgets {
  /** Array of budget objects for the enterprise */
  budgets: GetAllBudgetsBudgetsList;
  /** User login included when the response is scoped with the `user` query parameter. */
  user?: string;
  /** Effective user-level budget details returned when the response is scoped with the `user` query parameter. */
  effective_budget?: GetAllBudgetsEffectiveBudget;
  /** Indicates if there are more pages of results available (maps to hasNextPage from billing platform) */
  has_next_page?: boolean;
  /** Total number of budgets matching the query */
  total_count?: number;
}
export const GetAllBudgets = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    budgets: GetAllBudgetsBudgetsList,
    user: S.optional(S.String),
    effective_budget: S.optional(GetAllBudgetsEffectiveBudget),
    has_next_page: S.optional(S.Boolean),
    total_count: S.optional(S.Number),
  }),
).annotate({ identifier: "GetAllBudgets" }) as any as S.Schema<GetAllBudgets>;

export interface GetBudgetOrgRequest {
  /** The organization name. The name is not case sensitive. */
  org: string;
  /** The ID corresponding to the budget. */
  budget_id: string;
}
export const GetBudgetOrgRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    org: S.String.pipe(T.Label()),
    budget_id: S.String.pipe(T.Label()),
  }).pipe(
    T.Http({
      method: "GET",
      uri: "/organizations/{org}/settings/billing/budgets/{budget_id}",
      code: 200,
    }),
  ),
).annotate({
  identifier: "GetBudgetOrgRequest",
}) as any as S.Schema<GetBudgetOrgRequest>;

/** The type of scope for the budget */
export type GetBudgetBudgetScope =
  | "enterprise"
  | "organization"
  | "repository"
  | "cost_center"
  | "multi_user_customer"
  | "multi_user_cost_center"
  | "user";
export const GetBudgetBudgetScope = /*@__PURE__*/ S.String;

export type GetBudgetBudgetTypeCase0 = "ProductPricing";
export const GetBudgetBudgetTypeCase0 = /*@__PURE__*/ S.String;

export type GetBudgetBudgetTypeCase1 = "SkuPricing";
export const GetBudgetBudgetTypeCase1 = /*@__PURE__*/ S.String;

/** The type of pricing for the budget */
export type GetBudgetBudgetType =
  | GetBudgetBudgetTypeCase0
  | GetBudgetBudgetTypeCase1;
export const GetBudgetBudgetType =
  /*@__PURE__*/ S.Unknown as any as S.Schema<GetBudgetBudgetType>;

/** Array of user login names who will receive alerts */
export type GetBudgetBudgetAlertingAlertRecipientsList = Array<string>;
export const GetBudgetBudgetAlertingAlertRecipientsList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<GetBudgetBudgetAlertingAlertRecipientsList>;

export interface GetBudgetBudgetAlerting {
  /** Whether alerts are enabled for this budget */
  will_alert?: boolean;
  /** Array of user login names who will receive alerts */
  alert_recipients?: GetBudgetBudgetAlertingAlertRecipientsList;
}
export const GetBudgetBudgetAlerting = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    will_alert: S.optional(S.Boolean),
    alert_recipients: S.optional(GetBudgetBudgetAlertingAlertRecipientsList),
  }),
).annotate({
  identifier: "GetBudgetBudgetAlerting",
}) as any as S.Schema<GetBudgetBudgetAlerting>;

export interface GetBudget {
  /** ID of the budget. */
  id: string;
  /** The type of scope for the budget */
  budget_scope: GetBudgetBudgetScope;
  /** The name of the entity to apply the budget to */
  budget_entity_name: string;
  /** The user login when the budget is scoped to a single user (`user` scope). */
  user?: string;
  /** The budget amount in whole dollars. For license-based products, this represents the number of licenses. */
  budget_amount: number;
  /** Whether to prevent additional spending once the budget is exceeded */
  prevent_further_usage: boolean;
  /** A single product or sku to apply the budget to. */
  budget_product_sku: string;
  /** The type of pricing for the budget */
  budget_type: GetBudgetBudgetType;
  budget_alerting: GetBudgetBudgetAlerting;
}
export const GetBudget = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String,
    budget_scope: GetBudgetBudgetScope,
    budget_entity_name: S.String,
    user: S.optional(S.String),
    budget_amount: S.Number,
    prevent_further_usage: S.Boolean,
    budget_product_sku: S.String,
    budget_type: GetBudgetBudgetType,
    budget_alerting: GetBudgetBudgetAlerting,
  }),
).annotate({ identifier: "GetBudget" }) as any as S.Schema<GetBudget>;

export interface GetGithubBillingAiCreditUsageReportOrgRequest {
  /** The organization name. The name is not case sensitive. */
  org: string;
  /** If specified, only return results for a single year. The value of `year` is an integer with four digits representing a year. For example, `2025`. Default value is the current year. */
  year?: number;
  /** If specified, only return results for a single month. The value of `month` is an integer between `1` and `12`. Default value is the current month. If no year is specified the default `year` is used. */
  month?: number;
  /** If specified, only return results for a single day. The value of `day` is an integer between `1` and `31`. If no `year` or `month` is specified, the default `year` and `month` are used. */
  day?: number;
  /** The user name to query usage for. The name is not case sensitive. */
  user?: string;
  /** The model name to query usage for. The name is not case sensitive. */
  model?: string;
  /** The product name to query usage for. The name is not case sensitive. */
  product?: string;
}
export const GetGithubBillingAiCreditUsageReportOrgRequest =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      org: S.String.pipe(T.Label()),
      year: S.optional(S.Number.pipe(T.Query())),
      month: S.optional(S.Number.pipe(T.Query())),
      day: S.optional(S.Number.pipe(T.Query())),
      user: S.optional(S.String.pipe(T.Query())),
      model: S.optional(S.String.pipe(T.Query())),
      product: S.optional(S.String.pipe(T.Query())),
    }).pipe(
      T.Http({
        method: "GET",
        uri: "/organizations/{org}/settings/billing/ai_credit/usage",
        code: 200,
      }),
    ),
  ).annotate({
    identifier: "GetGithubBillingAiCreditUsageReportOrgRequest",
  }) as any as S.Schema<GetGithubBillingAiCreditUsageReportOrgRequest>;

export interface BillingAiCreditUsageReportOrgTimePeriod {
  /** The year for the usage report. */
  year: number;
  /** The month for the usage report. */
  month?: number;
  /** The day for the usage report. */
  day?: number;
}
export const BillingAiCreditUsageReportOrgTimePeriod = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      year: S.Number,
      month: S.optional(S.Number),
      day: S.optional(S.Number),
    }),
).annotate({
  identifier: "BillingAiCreditUsageReportOrgTimePeriod",
}) as any as S.Schema<BillingAiCreditUsageReportOrgTimePeriod>;

export interface BillingAiCreditUsageReportOrgUsageItemsItem {
  /** Product name. */
  product: string;
  /** SKU name. */
  sku: string;
  /** Model name. */
  model: string;
  /** Unit type of the usage line item. */
  unitType: string;
  /** Price per unit of the usage line item. */
  pricePerUnit: number;
  /** Gross quantity of the usage line item. */
  grossQuantity: number;
  /** Gross amount of the usage line item. */
  grossAmount: number;
  /** Discount quantity of the usage line item. */
  discountQuantity: number;
  /** Discount amount of the usage line item. */
  discountAmount: number;
  /** Net quantity of the usage line item. */
  netQuantity: number;
  /** Net amount of the usage line item. */
  netAmount: number;
}
export const BillingAiCreditUsageReportOrgUsageItemsItem =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      product: S.String,
      sku: S.String,
      model: S.String,
      unitType: S.String,
      pricePerUnit: S.Number,
      grossQuantity: S.Number,
      grossAmount: S.Number,
      discountQuantity: S.Number,
      discountAmount: S.Number,
      netQuantity: S.Number,
      netAmount: S.Number,
    }),
  ).annotate({
    identifier: "BillingAiCreditUsageReportOrgUsageItemsItem",
  }) as any as S.Schema<BillingAiCreditUsageReportOrgUsageItemsItem>;

export type BillingAiCreditUsageReportOrgUsageItemsList =
  Array<BillingAiCreditUsageReportOrgUsageItemsItem>;
export const BillingAiCreditUsageReportOrgUsageItemsList =
  /*@__PURE__*/ S.Array(
    BillingAiCreditUsageReportOrgUsageItemsItem,
  ) as any as S.Schema<BillingAiCreditUsageReportOrgUsageItemsList>;

export interface BillingAiCreditUsageReportOrg {
  timePeriod: BillingAiCreditUsageReportOrgTimePeriod;
  /** The unique identifier of the organization. */
  organization: string;
  /** The name of the user for the usage report. */
  user?: string;
  /** The product for the usage report. */
  product?: string;
  /** The model for the usage report. */
  model?: string;
  usageItems: BillingAiCreditUsageReportOrgUsageItemsList;
}
export const BillingAiCreditUsageReportOrg = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    timePeriod: BillingAiCreditUsageReportOrgTimePeriod,
    organization: S.String,
    user: S.optional(S.String),
    product: S.optional(S.String),
    model: S.optional(S.String),
    usageItems: BillingAiCreditUsageReportOrgUsageItemsList,
  }),
).annotate({
  identifier: "BillingAiCreditUsageReportOrg",
}) as any as S.Schema<BillingAiCreditUsageReportOrg>;

export interface GetGithubBillingAiCreditUsageReportUserRequest {
  /** The handle for the GitHub user account. */
  username: string;
  /** If specified, only return results for a single year. The value of `year` is an integer with four digits representing a year. For example, `2025`. Default value is the current year. */
  year?: number;
  /** If specified, only return results for a single month. The value of `month` is an integer between `1` and `12`. Default value is the current month. If no year is specified the default `year` is used. */
  month?: number;
  /** If specified, only return results for a single day. The value of `day` is an integer between `1` and `31`. If no `year` or `month` is specified, the default `year` and `month` are used. */
  day?: number;
  /** The model name to query usage for. The name is not case sensitive. */
  model?: string;
  /** The product name to query usage for. The name is not case sensitive. */
  product?: string;
}
export const GetGithubBillingAiCreditUsageReportUserRequest =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      username: S.String.pipe(T.Label()),
      year: S.optional(S.Number.pipe(T.Query())),
      month: S.optional(S.Number.pipe(T.Query())),
      day: S.optional(S.Number.pipe(T.Query())),
      model: S.optional(S.String.pipe(T.Query())),
      product: S.optional(S.String.pipe(T.Query())),
    }).pipe(
      T.Http({
        method: "GET",
        uri: "/users/{username}/settings/billing/ai_credit/usage",
        code: 200,
      }),
    ),
  ).annotate({
    identifier: "GetGithubBillingAiCreditUsageReportUserRequest",
  }) as any as S.Schema<GetGithubBillingAiCreditUsageReportUserRequest>;

export type BillingAiCreditUsageReportUserTimePeriod =
  BillingAiCreditUsageReportOrgTimePeriod;
export const BillingAiCreditUsageReportUserTimePeriod =
  BillingAiCreditUsageReportOrgTimePeriod;

export type BillingAiCreditUsageReportUserUsageItemsItem =
  BillingAiCreditUsageReportOrgUsageItemsItem;
export const BillingAiCreditUsageReportUserUsageItemsItem =
  BillingAiCreditUsageReportOrgUsageItemsItem;

export type BillingAiCreditUsageReportUserUsageItemsList =
  Array<BillingAiCreditUsageReportOrgUsageItemsItem>;
export const BillingAiCreditUsageReportUserUsageItemsList =
  /*@__PURE__*/ S.Array(
    BillingAiCreditUsageReportOrgUsageItemsItem,
  ) as any as S.Schema<BillingAiCreditUsageReportUserUsageItemsList>;

export interface BillingAiCreditUsageReportUser {
  timePeriod: BillingAiCreditUsageReportOrgTimePeriod;
  /** The unique identifier of the user. */
  user: string;
  /** The product for the usage report. */
  product?: string;
  /** The model for the usage report. */
  model?: string;
  usageItems: BillingAiCreditUsageReportUserUsageItemsList;
}
export const BillingAiCreditUsageReportUser = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    timePeriod: BillingAiCreditUsageReportOrgTimePeriod,
    user: S.String,
    product: S.optional(S.String),
    model: S.optional(S.String),
    usageItems: BillingAiCreditUsageReportUserUsageItemsList,
  }),
).annotate({
  identifier: "BillingAiCreditUsageReportUser",
}) as any as S.Schema<BillingAiCreditUsageReportUser>;

export interface GetGithubBillingPremiumRequestUsageReportOrgRequest {
  /** The organization name. The name is not case sensitive. */
  org: string;
  /** If specified, only return results for a single year. The value of `year` is an integer with four digits representing a year. For example, `2025`. Default value is the current year. */
  year?: number;
  /** If specified, only return results for a single month. The value of `month` is an integer between `1` and `12`. Default value is the current month. If no year is specified the default `year` is used. */
  month?: number;
  /** If specified, only return results for a single day. The value of `day` is an integer between `1` and `31`. If no `year` or `month` is specified, the default `year` and `month` are used. */
  day?: number;
  /** The user name to query usage for. The name is not case sensitive. */
  user?: string;
  /** The model name to query usage for. The name is not case sensitive. */
  model?: string;
  /** The product name to query usage for. The name is not case sensitive. */
  product?: string;
}
export const GetGithubBillingPremiumRequestUsageReportOrgRequest =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      org: S.String.pipe(T.Label()),
      year: S.optional(S.Number.pipe(T.Query())),
      month: S.optional(S.Number.pipe(T.Query())),
      day: S.optional(S.Number.pipe(T.Query())),
      user: S.optional(S.String.pipe(T.Query())),
      model: S.optional(S.String.pipe(T.Query())),
      product: S.optional(S.String.pipe(T.Query())),
    }).pipe(
      T.Http({
        method: "GET",
        uri: "/organizations/{org}/settings/billing/premium_request/usage",
        code: 200,
      }),
    ),
  ).annotate({
    identifier: "GetGithubBillingPremiumRequestUsageReportOrgRequest",
  }) as any as S.Schema<GetGithubBillingPremiumRequestUsageReportOrgRequest>;

export type BillingPremiumRequestUsageReportOrgTimePeriod =
  BillingAiCreditUsageReportOrgTimePeriod;
export const BillingPremiumRequestUsageReportOrgTimePeriod =
  BillingAiCreditUsageReportOrgTimePeriod;

export type BillingPremiumRequestUsageReportOrgUsageItemsItem =
  BillingAiCreditUsageReportOrgUsageItemsItem;
export const BillingPremiumRequestUsageReportOrgUsageItemsItem =
  BillingAiCreditUsageReportOrgUsageItemsItem;

export type BillingPremiumRequestUsageReportOrgUsageItemsList =
  Array<BillingAiCreditUsageReportOrgUsageItemsItem>;
export const BillingPremiumRequestUsageReportOrgUsageItemsList =
  /*@__PURE__*/ S.Array(
    BillingAiCreditUsageReportOrgUsageItemsItem,
  ) as any as S.Schema<BillingPremiumRequestUsageReportOrgUsageItemsList>;

export interface BillingPremiumRequestUsageReportOrg {
  timePeriod: BillingAiCreditUsageReportOrgTimePeriod;
  /** The unique identifier of the organization. */
  organization: string;
  /** The name of the user for the usage report. */
  user?: string;
  /** The product for the usage report. */
  product?: string;
  /** The model for the usage report. */
  model?: string;
  usageItems: BillingPremiumRequestUsageReportOrgUsageItemsList;
}
export const BillingPremiumRequestUsageReportOrg = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    timePeriod: BillingAiCreditUsageReportOrgTimePeriod,
    organization: S.String,
    user: S.optional(S.String),
    product: S.optional(S.String),
    model: S.optional(S.String),
    usageItems: BillingPremiumRequestUsageReportOrgUsageItemsList,
  }),
).annotate({
  identifier: "BillingPremiumRequestUsageReportOrg",
}) as any as S.Schema<BillingPremiumRequestUsageReportOrg>;

export interface GetGithubBillingPremiumRequestUsageReportUserRequest {
  /** The handle for the GitHub user account. */
  username: string;
  /** If specified, only return results for a single year. The value of `year` is an integer with four digits representing a year. For example, `2025`. Default value is the current year. */
  year?: number;
  /** If specified, only return results for a single month. The value of `month` is an integer between `1` and `12`. Default value is the current month. If no year is specified the default `year` is used. */
  month?: number;
  /** If specified, only return results for a single day. The value of `day` is an integer between `1` and `31`. If no `year` or `month` is specified, the default `year` and `month` are used. */
  day?: number;
  /** The model name to query usage for. The name is not case sensitive. */
  model?: string;
  /** The product name to query usage for. The name is not case sensitive. */
  product?: string;
}
export const GetGithubBillingPremiumRequestUsageReportUserRequest =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      username: S.String.pipe(T.Label()),
      year: S.optional(S.Number.pipe(T.Query())),
      month: S.optional(S.Number.pipe(T.Query())),
      day: S.optional(S.Number.pipe(T.Query())),
      model: S.optional(S.String.pipe(T.Query())),
      product: S.optional(S.String.pipe(T.Query())),
    }).pipe(
      T.Http({
        method: "GET",
        uri: "/users/{username}/settings/billing/premium_request/usage",
        code: 200,
      }),
    ),
  ).annotate({
    identifier: "GetGithubBillingPremiumRequestUsageReportUserRequest",
  }) as any as S.Schema<GetGithubBillingPremiumRequestUsageReportUserRequest>;

export type BillingPremiumRequestUsageReportUserTimePeriod =
  BillingAiCreditUsageReportOrgTimePeriod;
export const BillingPremiumRequestUsageReportUserTimePeriod =
  BillingAiCreditUsageReportOrgTimePeriod;

export type BillingPremiumRequestUsageReportUserUsageItemsItem =
  BillingAiCreditUsageReportOrgUsageItemsItem;
export const BillingPremiumRequestUsageReportUserUsageItemsItem =
  BillingAiCreditUsageReportOrgUsageItemsItem;

export type BillingPremiumRequestUsageReportUserUsageItemsList =
  Array<BillingAiCreditUsageReportOrgUsageItemsItem>;
export const BillingPremiumRequestUsageReportUserUsageItemsList =
  /*@__PURE__*/ S.Array(
    BillingAiCreditUsageReportOrgUsageItemsItem,
  ) as any as S.Schema<BillingPremiumRequestUsageReportUserUsageItemsList>;

export interface BillingPremiumRequestUsageReportUser {
  timePeriod: BillingAiCreditUsageReportOrgTimePeriod;
  /** The unique identifier of the user. */
  user: string;
  /** The product for the usage report. */
  product?: string;
  /** The model for the usage report. */
  model?: string;
  usageItems: BillingPremiumRequestUsageReportUserUsageItemsList;
}
export const BillingPremiumRequestUsageReportUser = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      timePeriod: BillingAiCreditUsageReportOrgTimePeriod,
      user: S.String,
      product: S.optional(S.String),
      model: S.optional(S.String),
      usageItems: BillingPremiumRequestUsageReportUserUsageItemsList,
    }),
).annotate({
  identifier: "BillingPremiumRequestUsageReportUser",
}) as any as S.Schema<BillingPremiumRequestUsageReportUser>;

export interface GetGithubBillingUsageReportOrgRequest {
  /** The organization name. The name is not case sensitive. */
  org: string;
  /** If specified, only return results for a single year. The value of `year` is an integer with four digits representing a year. For example, `2025`. Default value is the current year. */
  year?: number;
  /** If specified, only return results for a single month. The value of `month` is an integer between `1` and `12`. If no year is specified the default `year` is used. */
  month?: number;
  /** If specified, only return results for a single day. The value of `day` is an integer between `1` and `31`. If no `year` or `month` is specified, the default `year` and `month` are used. */
  day?: number;
}
export const GetGithubBillingUsageReportOrgRequest = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      org: S.String.pipe(T.Label()),
      year: S.optional(S.Number.pipe(T.Query())),
      month: S.optional(S.Number.pipe(T.Query())),
      day: S.optional(S.Number.pipe(T.Query())),
    }).pipe(
      T.Http({
        method: "GET",
        uri: "/organizations/{org}/settings/billing/usage",
        code: 200,
      }),
    ),
).annotate({
  identifier: "GetGithubBillingUsageReportOrgRequest",
}) as any as S.Schema<GetGithubBillingUsageReportOrgRequest>;

export interface BillingUsageReportUsageItemsItem {
  /** Date of the usage line item. */
  date: string;
  /** Product name. */
  product: string;
  /** SKU name. */
  sku: string;
  /** Quantity of the usage line item. */
  quantity: number;
  /** Unit type of the usage line item. */
  unitType: string;
  /** Price per unit of the usage line item. */
  pricePerUnit: number;
  /** Gross amount of the usage line item. */
  grossAmount: number;
  /** Discount amount of the usage line item. */
  discountAmount: number;
  /** Net amount of the usage line item. */
  netAmount: number;
  /** Name of the organization. */
  organizationName: string;
  /** Name of the repository. */
  repositoryName?: string;
}
export const BillingUsageReportUsageItemsItem = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    date: S.String,
    product: S.String,
    sku: S.String,
    quantity: S.Number,
    unitType: S.String,
    pricePerUnit: S.Number,
    grossAmount: S.Number,
    discountAmount: S.Number,
    netAmount: S.Number,
    organizationName: S.String,
    repositoryName: S.optional(S.String),
  }),
).annotate({
  identifier: "BillingUsageReportUsageItemsItem",
}) as any as S.Schema<BillingUsageReportUsageItemsItem>;

export type BillingUsageReportUsageItemsList =
  Array<BillingUsageReportUsageItemsItem>;
export const BillingUsageReportUsageItemsList = /*@__PURE__*/ S.Array(
  BillingUsageReportUsageItemsItem,
) as any as S.Schema<BillingUsageReportUsageItemsList>;

export interface BillingUsageReport {
  usageItems?: BillingUsageReportUsageItemsList;
}
export const BillingUsageReport = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    usageItems: S.optional(BillingUsageReportUsageItemsList),
  }),
).annotate({
  identifier: "BillingUsageReport",
}) as any as S.Schema<BillingUsageReport>;

export interface GetGithubBillingUsageReportUserRequest {
  /** The handle for the GitHub user account. */
  username: string;
  /** If specified, only return results for a single year. The value of `year` is an integer with four digits representing a year. For example, `2025`. Default value is the current year. */
  year?: number;
  /** If specified, only return results for a single month. The value of `month` is an integer between `1` and `12`. If no year is specified the default `year` is used. */
  month?: number;
  /** If specified, only return results for a single day. The value of `day` is an integer between `1` and `31`. If no `year` or `month` is specified, the default `year` and `month` are used. */
  day?: number;
}
export const GetGithubBillingUsageReportUserRequest = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      username: S.String.pipe(T.Label()),
      year: S.optional(S.Number.pipe(T.Query())),
      month: S.optional(S.Number.pipe(T.Query())),
      day: S.optional(S.Number.pipe(T.Query())),
    }).pipe(
      T.Http({
        method: "GET",
        uri: "/users/{username}/settings/billing/usage",
        code: 200,
      }),
    ),
).annotate({
  identifier: "GetGithubBillingUsageReportUserRequest",
}) as any as S.Schema<GetGithubBillingUsageReportUserRequest>;

export interface BillingUsageReportUserUsageItemsItem {
  /** Date of the usage line item. */
  date: string;
  /** Product name. */
  product: string;
  /** SKU name. */
  sku: string;
  /** Quantity of the usage line item. */
  quantity: number;
  /** Unit type of the usage line item. */
  unitType: string;
  /** Price per unit of the usage line item. */
  pricePerUnit: number;
  /** Gross amount of the usage line item. */
  grossAmount: number;
  /** Discount amount of the usage line item. */
  discountAmount: number;
  /** Net amount of the usage line item. */
  netAmount: number;
  /** Name of the repository. */
  repositoryName?: string;
}
export const BillingUsageReportUserUsageItemsItem = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      date: S.String,
      product: S.String,
      sku: S.String,
      quantity: S.Number,
      unitType: S.String,
      pricePerUnit: S.Number,
      grossAmount: S.Number,
      discountAmount: S.Number,
      netAmount: S.Number,
      repositoryName: S.optional(S.String),
    }),
).annotate({
  identifier: "BillingUsageReportUserUsageItemsItem",
}) as any as S.Schema<BillingUsageReportUserUsageItemsItem>;

export type BillingUsageReportUserUsageItemsList =
  Array<BillingUsageReportUserUsageItemsItem>;
export const BillingUsageReportUserUsageItemsList = /*@__PURE__*/ S.Array(
  BillingUsageReportUserUsageItemsItem,
) as any as S.Schema<BillingUsageReportUserUsageItemsList>;

export interface BillingUsageReportUser {
  usageItems?: BillingUsageReportUserUsageItemsList;
}
export const BillingUsageReportUser = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    usageItems: S.optional(BillingUsageReportUserUsageItemsList),
  }),
).annotate({
  identifier: "BillingUsageReportUser",
}) as any as S.Schema<BillingUsageReportUser>;

export interface GetGithubBillingUsageSummaryReportOrgRequest {
  /** The organization name. The name is not case sensitive. */
  org: string;
  /** If specified, only return results for a single year. The value of `year` is an integer with four digits representing a year. For example, `2025`. Default value is the current year. */
  year?: number;
  /** If specified, only return results for a single month. The value of `month` is an integer between `1` and `12`. Default value is the current month. If no year is specified the default `year` is used. */
  month?: number;
  /** If specified, only return results for a single day. The value of `day` is an integer between `1` and `31`. If no `year` or `month` is specified, the default `year` and `month` are used. */
  day?: number;
  /** The repository name to query for usage in the format owner/repository. */
  repository?: string;
  /** The product name to query usage for. The name is not case sensitive. */
  product?: string;
  /** The SKU to query for usage. */
  sku?: string;
}
export const GetGithubBillingUsageSummaryReportOrgRequest =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      org: S.String.pipe(T.Label()),
      year: S.optional(S.Number.pipe(T.Query())),
      month: S.optional(S.Number.pipe(T.Query())),
      day: S.optional(S.Number.pipe(T.Query())),
      repository: S.optional(S.String.pipe(T.Query())),
      product: S.optional(S.String.pipe(T.Query())),
      sku: S.optional(S.String.pipe(T.Query())),
    }).pipe(
      T.Http({
        method: "GET",
        uri: "/organizations/{org}/settings/billing/usage/summary",
        code: 200,
      }),
    ),
  ).annotate({
    identifier: "GetGithubBillingUsageSummaryReportOrgRequest",
  }) as any as S.Schema<GetGithubBillingUsageSummaryReportOrgRequest>;

export type BillingUsageSummaryReportOrgTimePeriod =
  BillingAiCreditUsageReportOrgTimePeriod;
export const BillingUsageSummaryReportOrgTimePeriod =
  BillingAiCreditUsageReportOrgTimePeriod;

export interface BillingUsageSummaryReportOrgUsageItemsItem {
  /** Product name. */
  product: string;
  /** SKU name. */
  sku: string;
  /** Unit type of the usage line item. */
  unitType: string;
  /** Price per unit of the usage line item. */
  pricePerUnit: number;
  /** Gross quantity of the usage line item. */
  grossQuantity: number;
  /** Gross amount of the usage line item. */
  grossAmount: number;
  /** Discount quantity of the usage line item. */
  discountQuantity: number;
  /** Discount amount of the usage line item. */
  discountAmount: number;
  /** Net quantity of the usage line item. */
  netQuantity: number;
  /** Net amount of the usage line item. */
  netAmount: number;
}
export const BillingUsageSummaryReportOrgUsageItemsItem =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      product: S.String,
      sku: S.String,
      unitType: S.String,
      pricePerUnit: S.Number,
      grossQuantity: S.Number,
      grossAmount: S.Number,
      discountQuantity: S.Number,
      discountAmount: S.Number,
      netQuantity: S.Number,
      netAmount: S.Number,
    }),
  ).annotate({
    identifier: "BillingUsageSummaryReportOrgUsageItemsItem",
  }) as any as S.Schema<BillingUsageSummaryReportOrgUsageItemsItem>;

export type BillingUsageSummaryReportOrgUsageItemsList =
  Array<BillingUsageSummaryReportOrgUsageItemsItem>;
export const BillingUsageSummaryReportOrgUsageItemsList = /*@__PURE__*/ S.Array(
  BillingUsageSummaryReportOrgUsageItemsItem,
) as any as S.Schema<BillingUsageSummaryReportOrgUsageItemsList>;

export interface BillingUsageSummaryReportOrg {
  timePeriod: BillingAiCreditUsageReportOrgTimePeriod;
  /** The unique identifier of the organization. */
  organization: string;
  /** The name of the repository for the usage report. */
  repository?: string;
  /** The product for the usage report. */
  product?: string;
  /** The SKU for the usage report. */
  sku?: string;
  usageItems: BillingUsageSummaryReportOrgUsageItemsList;
}
export const BillingUsageSummaryReportOrg = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    timePeriod: BillingAiCreditUsageReportOrgTimePeriod,
    organization: S.String,
    repository: S.optional(S.String),
    product: S.optional(S.String),
    sku: S.optional(S.String),
    usageItems: BillingUsageSummaryReportOrgUsageItemsList,
  }),
).annotate({
  identifier: "BillingUsageSummaryReportOrg",
}) as any as S.Schema<BillingUsageSummaryReportOrg>;

export interface GetGithubBillingUsageSummaryReportUserRequest {
  /** The handle for the GitHub user account. */
  username: string;
  /** If specified, only return results for a single year. The value of `year` is an integer with four digits representing a year. For example, `2025`. Default value is the current year. */
  year?: number;
  /** If specified, only return results for a single month. The value of `month` is an integer between `1` and `12`. Default value is the current month. If no year is specified the default `year` is used. */
  month?: number;
  /** If specified, only return results for a single day. The value of `day` is an integer between `1` and `31`. If no `year` or `month` is specified, the default `year` and `month` are used. */
  day?: number;
  /** The repository name to query for usage in the format owner/repository. */
  repository?: string;
  /** The product name to query usage for. The name is not case sensitive. */
  product?: string;
  /** The SKU to query for usage. */
  sku?: string;
}
export const GetGithubBillingUsageSummaryReportUserRequest =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      username: S.String.pipe(T.Label()),
      year: S.optional(S.Number.pipe(T.Query())),
      month: S.optional(S.Number.pipe(T.Query())),
      day: S.optional(S.Number.pipe(T.Query())),
      repository: S.optional(S.String.pipe(T.Query())),
      product: S.optional(S.String.pipe(T.Query())),
      sku: S.optional(S.String.pipe(T.Query())),
    }).pipe(
      T.Http({
        method: "GET",
        uri: "/users/{username}/settings/billing/usage/summary",
        code: 200,
      }),
    ),
  ).annotate({
    identifier: "GetGithubBillingUsageSummaryReportUserRequest",
  }) as any as S.Schema<GetGithubBillingUsageSummaryReportUserRequest>;

export type BillingUsageSummaryReportUserTimePeriod =
  BillingAiCreditUsageReportOrgTimePeriod;
export const BillingUsageSummaryReportUserTimePeriod =
  BillingAiCreditUsageReportOrgTimePeriod;

export type BillingUsageSummaryReportUserUsageItemsItem =
  BillingUsageSummaryReportOrgUsageItemsItem;
export const BillingUsageSummaryReportUserUsageItemsItem =
  BillingUsageSummaryReportOrgUsageItemsItem;

export type BillingUsageSummaryReportUserUsageItemsList =
  Array<BillingUsageSummaryReportOrgUsageItemsItem>;
export const BillingUsageSummaryReportUserUsageItemsList =
  /*@__PURE__*/ S.Array(
    BillingUsageSummaryReportOrgUsageItemsItem,
  ) as any as S.Schema<BillingUsageSummaryReportUserUsageItemsList>;

export interface BillingUsageSummaryReportUser {
  timePeriod: BillingAiCreditUsageReportOrgTimePeriod;
  /** The unique identifier of the user. */
  user: string;
  /** The name of the repository for the usage report. */
  repository?: string;
  /** The product for the usage report. */
  product?: string;
  /** The SKU for the usage report. */
  sku?: string;
  usageItems: BillingUsageSummaryReportUserUsageItemsList;
}
export const BillingUsageSummaryReportUser = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    timePeriod: BillingAiCreditUsageReportOrgTimePeriod,
    user: S.String,
    repository: S.optional(S.String),
    product: S.optional(S.String),
    sku: S.optional(S.String),
    usageItems: BillingUsageSummaryReportUserUsageItemsList,
  }),
).annotate({
  identifier: "BillingUsageSummaryReportUser",
}) as any as S.Schema<BillingUsageSummaryReportUser>;

/** Array of user login names who will receive alerts */
export type UpdateBudgetOrgRequestBudgetAlertingAlertRecipientsList =
  Array<string>;
export const UpdateBudgetOrgRequestBudgetAlertingAlertRecipientsList =
  /*@__PURE__*/ S.Array(
    S.String,
  ) as any as S.Schema<UpdateBudgetOrgRequestBudgetAlertingAlertRecipientsList>;

export interface UpdateBudgetOrgRequestBudgetAlerting {
  /** Whether alerts are enabled for this budget */
  will_alert?: boolean;
  /** Array of user login names who will receive alerts */
  alert_recipients?: UpdateBudgetOrgRequestBudgetAlertingAlertRecipientsList;
}
export const UpdateBudgetOrgRequestBudgetAlerting = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      will_alert: S.optional(S.Boolean),
      alert_recipients: S.optional(
        UpdateBudgetOrgRequestBudgetAlertingAlertRecipientsList,
      ),
    }),
).annotate({
  identifier: "UpdateBudgetOrgRequestBudgetAlerting",
}) as any as S.Schema<UpdateBudgetOrgRequestBudgetAlerting>;

/** The scope of the budget for this organization. - `organization`: Apply the budget to the organization. - `repository`: Apply the budget to a specific repository in the organization. - `multi_user_customer`: Apply a universal budget to all users in the organization. - `user`: Apply the budget to a single user in the organization. */
export type UpdateBudgetOrgRequestBudgetScope =
  | "enterprise"
  | "organization"
  | "repository"
  | "cost_center"
  | "multi_user_customer"
  | "user";
export const UpdateBudgetOrgRequestBudgetScope = /*@__PURE__*/ S.String;

export type UpdateBudgetOrgRequestBudgetTypeCase0 = "BundlePricing";
export const UpdateBudgetOrgRequestBudgetTypeCase0 = /*@__PURE__*/ S.String;

export type UpdateBudgetOrgRequestBudgetTypeCase1 = "ProductPricing";
export const UpdateBudgetOrgRequestBudgetTypeCase1 = /*@__PURE__*/ S.String;

export type UpdateBudgetOrgRequestBudgetTypeCase2 = "SkuPricing";
export const UpdateBudgetOrgRequestBudgetTypeCase2 = /*@__PURE__*/ S.String;

/** The type of pricing model used by the budget. Determines how `budget_product_sku` is interpreted. - `BundlePricing`: Covers all AI credit SKUs. Set `budget_product_sku` to `ai_credits`. - `ProductPricing`: Covers all SKUs that belong to a product. Set `budget_product_sku` to a product such as `actions` or `packages`. - `SkuPricing`: Covers a single, specific SKU. Set `budget_product_sku` to a SKU such as `actions_linux`. */
export type UpdateBudgetOrgRequestBudgetType =
  | UpdateBudgetOrgRequestBudgetTypeCase0
  | UpdateBudgetOrgRequestBudgetTypeCase1
  | UpdateBudgetOrgRequestBudgetTypeCase2;
export const UpdateBudgetOrgRequestBudgetType =
  /*@__PURE__*/ S.Unknown as any as S.Schema<UpdateBudgetOrgRequestBudgetType>;

export interface UpdateBudgetOrgRequest {
  /** The organization name. The name is not case sensitive. */
  org: string;
  /** The ID corresponding to the budget. */
  budget_id: string;
  /** The budget amount in whole dollars. For license-based products, this represents the number of licenses. */
  budget_amount?: number;
  /** Whether to prevent additional spending once the budget is exceeded. For budgets with `user` or `multi_user_customer` scope, this must remain `true`. */
  prevent_further_usage?: boolean;
  budget_alerting?: UpdateBudgetOrgRequestBudgetAlerting;
  /** The scope of the budget for this organization. - `organization`: Apply the budget to the organization. - `repository`: Apply the budget to a specific repository in the organization. - `multi_user_customer`: Apply a universal budget to all users in the organization. - `user`: Apply the budget to a single user in the organization. */
  budget_scope?: UpdateBudgetOrgRequestBudgetScope | (string & {});
  /** The name of the entity to apply the budget to */
  budget_entity_name?: string;
  /** The type of pricing model used by the budget. Determines how `budget_product_sku` is interpreted. - `BundlePricing`: Covers all AI credit SKUs. Set `budget_product_sku` to `ai_credits`. - `ProductPricing`: Covers all SKUs that belong to a product. Set `budget_product_sku` to a product such as `actions` or `packages`. - `SkuPricing`: Covers a single, specific SKU. Set `budget_product_sku` to a SKU such as `actions_linux`. */
  budget_type?: UpdateBudgetOrgRequestBudgetType;
  /** A single product or SKU that will be covered in the budget */
  budget_product_sku?: string;
  /** The username of the user for `user` scope budgets. */
  user?: string;
}
export const UpdateBudgetOrgRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    org: S.String.pipe(T.Label()),
    budget_id: S.String.pipe(T.Label()),
    budget_amount: S.optional(S.Number),
    prevent_further_usage: S.optional(S.Boolean),
    budget_alerting: S.optional(UpdateBudgetOrgRequestBudgetAlerting),
    budget_scope: S.optional(UpdateBudgetOrgRequestBudgetScope),
    budget_entity_name: S.optional(S.String),
    budget_type: S.optional(UpdateBudgetOrgRequestBudgetType),
    budget_product_sku: S.optional(S.String),
    user: S.optional(S.String),
  }).pipe(
    T.Http({
      method: "PATCH",
      uri: "/organizations/{org}/settings/billing/budgets/{budget_id}",
      code: 200,
    }),
  ),
).annotate({
  identifier: "UpdateBudgetOrgRequest",
}) as any as S.Schema<UpdateBudgetOrgRequest>;

/** The type of scope for the budget */
export type UpdateBudgetBudgetBudgetScope =
  | "enterprise"
  | "organization"
  | "repository"
  | "cost_center"
  | "multi_user_customer"
  | "multi_user_cost_center"
  | "user";
export const UpdateBudgetBudgetBudgetScope = /*@__PURE__*/ S.String;

export type UpdateBudgetBudgetBudgetTypeCase0 = "ProductPricing";
export const UpdateBudgetBudgetBudgetTypeCase0 = /*@__PURE__*/ S.String;

export type UpdateBudgetBudgetBudgetTypeCase1 = "SkuPricing";
export const UpdateBudgetBudgetBudgetTypeCase1 = /*@__PURE__*/ S.String;

/** The type of pricing for the budget */
export type UpdateBudgetBudgetBudgetType =
  | UpdateBudgetBudgetBudgetTypeCase0
  | UpdateBudgetBudgetBudgetTypeCase1;
export const UpdateBudgetBudgetBudgetType =
  /*@__PURE__*/ S.Unknown as any as S.Schema<UpdateBudgetBudgetBudgetType>;

/** Array of user login names who will receive alerts */
export type UpdateBudgetBudgetBudgetAlertingAlertRecipientsList = Array<string>;
export const UpdateBudgetBudgetBudgetAlertingAlertRecipientsList =
  /*@__PURE__*/ S.Array(
    S.String,
  ) as any as S.Schema<UpdateBudgetBudgetBudgetAlertingAlertRecipientsList>;

export interface UpdateBudgetBudgetBudgetAlerting {
  /** Whether alerts are enabled for this budget */
  will_alert?: boolean;
  /** Array of user login names who will receive alerts */
  alert_recipients?: UpdateBudgetBudgetBudgetAlertingAlertRecipientsList;
}
export const UpdateBudgetBudgetBudgetAlerting = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    will_alert: S.optional(S.Boolean),
    alert_recipients: S.optional(
      UpdateBudgetBudgetBudgetAlertingAlertRecipientsList,
    ),
  }),
).annotate({
  identifier: "UpdateBudgetBudgetBudgetAlerting",
}) as any as S.Schema<UpdateBudgetBudgetBudgetAlerting>;

export interface UpdateBudgetBudget {
  /** ID of the budget. */
  id?: string;
  /** The type of scope for the budget */
  budget_scope?: UpdateBudgetBudgetBudgetScope;
  /** The name of the entity to apply the budget to */
  budget_entity_name?: string;
  /** The user login when the budget is scoped to a single user (`user` scope). */
  user?: string;
  /** The consumed amount for the specified user within the budget. Only included for `user`-scoped budgets. */
  consumed_amount?: number;
  /** The budget amount in whole dollars. For license-based products, this represents the number of licenses. */
  budget_amount?: number;
  /** Whether to prevent additional spending once the budget is exceeded */
  prevent_further_usage?: boolean;
  /** A single product or sku to apply the budget to. */
  budget_product_sku?: string;
  /** The type of pricing for the budget */
  budget_type?: UpdateBudgetBudgetBudgetType;
  budget_alerting?: UpdateBudgetBudgetBudgetAlerting;
}
export const UpdateBudgetBudget = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.String),
    budget_scope: S.optional(UpdateBudgetBudgetBudgetScope),
    budget_entity_name: S.optional(S.String),
    user: S.optional(S.String),
    consumed_amount: S.optional(S.Number),
    budget_amount: S.optional(S.Number),
    prevent_further_usage: S.optional(S.Boolean),
    budget_product_sku: S.optional(S.String),
    budget_type: S.optional(UpdateBudgetBudgetBudgetType),
    budget_alerting: S.optional(UpdateBudgetBudgetBudgetAlerting),
  }),
).annotate({
  identifier: "UpdateBudgetBudget",
}) as any as S.Schema<UpdateBudgetBudget>;

export interface UpdateBudget {
  /** A message indicating the result of the update operation */
  message: string;
  budget: UpdateBudgetBudget;
}
export const UpdateBudget = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    message: S.String,
    budget: UpdateBudgetBudget,
  }),
).annotate({ identifier: "UpdateBudget" }) as any as S.Schema<UpdateBudget>;

export type CreateOrganizationBudgetError =
  | BadRequest
  | Forbidden
  | NotFound
  | UnprocessableEntity
  | GithubOpError;
/** Create a budget for an organization Creates a new budget for an organization. The authenticated user must be an organization admin or billing manager. */
export const createOrganizationBudget: API.OperationMethod<
  CreateOrganizationBudgetRequest,
  CreateBudget,
  CreateOrganizationBudgetError,
  GithubOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CreateOrganizationBudgetRequest,
  output: CreateBudget,
  errors: [BadRequest, Forbidden, NotFound, UnprocessableEntity],
  protocol: GithubProtocol,
  retry: Retry.Retry,
}));

export type DeleteBudgetOrgError =
  | BadRequest
  | Forbidden
  | NotFound
  | GithubOpError;
/** Delete a budget for an organization Deletes a budget by ID for an organization. The authenticated user must be an organization admin or billing manager. */
export const deleteBudgetOrg: API.OperationMethod<
  DeleteBudgetOrgRequest,
  DeleteBudget,
  DeleteBudgetOrgError,
  GithubOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: DeleteBudgetOrgRequest,
  output: DeleteBudget,
  errors: [BadRequest, Forbidden, NotFound],
  protocol: GithubProtocol,
  retry: Retry.Retry,
}));

export type GetAllBudgetsOrgError = Forbidden | NotFound | GithubOpError;
/** Get all budgets for an organization Gets all budgets for an organization. The authenticated user must be an organization admin or billing manager. Each page returns up to 100 budgets. */
export const getAllBudgetsOrg: API.OperationMethod<
  GetAllBudgetsOrgRequest,
  GetAllBudgets,
  GetAllBudgetsOrgError,
  GithubOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetAllBudgetsOrgRequest,
  output: GetAllBudgets,
  errors: [Forbidden, NotFound],
  protocol: GithubProtocol,
  retry: Retry.Retry,
}));

export type GetBudgetOrgError =
  | BadRequest
  | Forbidden
  | NotFound
  | GithubOpError;
/** Get a budget by ID for an organization Gets a budget by ID. The authenticated user must be an organization admin or billing manager. */
export const getBudgetOrg: API.OperationMethod<
  GetBudgetOrgRequest,
  GetBudget,
  GetBudgetOrgError,
  GithubOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetBudgetOrgRequest,
  output: GetBudget,
  errors: [BadRequest, Forbidden, NotFound],
  protocol: GithubProtocol,
  retry: Retry.Retry,
}));

export type GetGithubBillingAiCreditUsageReportOrgError =
  | BadRequest
  | Forbidden
  | NotFound
  | GithubOpError;
/** Get billing AI credit usage report for an organization Gets a report of AI credit usage for an organization. To use this endpoint, you must be an administrator of an organization within an enterprise or an organization account. **Note:** Only data from the past 24 months is accessible via this endpoint. */
export const getGithubBillingAiCreditUsageReportOrg: API.OperationMethod<
  GetGithubBillingAiCreditUsageReportOrgRequest,
  BillingAiCreditUsageReportOrg,
  GetGithubBillingAiCreditUsageReportOrgError,
  GithubOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetGithubBillingAiCreditUsageReportOrgRequest,
  output: BillingAiCreditUsageReportOrg,
  errors: [BadRequest, Forbidden, NotFound],
  protocol: GithubProtocol,
  retry: Retry.Retry,
}));

export type GetGithubBillingAiCreditUsageReportUserError =
  | BadRequest
  | Forbidden
  | NotFound
  | GithubOpError;
/** Get billing AI credit usage report for a user Gets a report of AI credit usage for a user. **Note:** Only data from the past 24 months is accessible via this endpoint. */
export const getGithubBillingAiCreditUsageReportUser: API.OperationMethod<
  GetGithubBillingAiCreditUsageReportUserRequest,
  BillingAiCreditUsageReportUser,
  GetGithubBillingAiCreditUsageReportUserError,
  GithubOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetGithubBillingAiCreditUsageReportUserRequest,
  output: BillingAiCreditUsageReportUser,
  errors: [BadRequest, Forbidden, NotFound],
  protocol: GithubProtocol,
  retry: Retry.Retry,
}));

export type GetGithubBillingPremiumRequestUsageReportOrgError =
  | BadRequest
  | Forbidden
  | NotFound
  | GithubOpError;
/** Get billing premium request usage report for an organization Gets a report of premium request usage for an organization. To use this endpoint, you must be an administrator of an organization within an enterprise or an organization account. **Note:** Only data from the past 24 months is accessible via this endpoint. */
export const getGithubBillingPremiumRequestUsageReportOrg: API.OperationMethod<
  GetGithubBillingPremiumRequestUsageReportOrgRequest,
  BillingPremiumRequestUsageReportOrg,
  GetGithubBillingPremiumRequestUsageReportOrgError,
  GithubOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetGithubBillingPremiumRequestUsageReportOrgRequest,
  output: BillingPremiumRequestUsageReportOrg,
  errors: [BadRequest, Forbidden, NotFound],
  protocol: GithubProtocol,
  retry: Retry.Retry,
}));

export type GetGithubBillingPremiumRequestUsageReportUserError =
  | BadRequest
  | Forbidden
  | NotFound
  | GithubOpError;
/** Get billing premium request usage report for a user Gets a report of premium request usage for a user. **Note:** Only data from the past 24 months is accessible via this endpoint. */
export const getGithubBillingPremiumRequestUsageReportUser: API.OperationMethod<
  GetGithubBillingPremiumRequestUsageReportUserRequest,
  BillingPremiumRequestUsageReportUser,
  GetGithubBillingPremiumRequestUsageReportUserError,
  GithubOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetGithubBillingPremiumRequestUsageReportUserRequest,
  output: BillingPremiumRequestUsageReportUser,
  errors: [BadRequest, Forbidden, NotFound],
  protocol: GithubProtocol,
  retry: Retry.Retry,
}));

export type GetGithubBillingUsageReportOrgError =
  | BadRequest
  | Forbidden
  | GithubOpError;
/** Get billing usage report for an organization Gets a report of the total usage for an organization. To use this endpoint, you must be an administrator of an organization within an enterprise or an organization account. **Note:** This endpoint is only available to organizations with access to the enhanced billing platform. For more information, see "[About the enhanced billing platform](https://docs.github.com/billing/using-the-new-billing-platform)." */
export const getGithubBillingUsageReportOrg: API.OperationMethod<
  GetGithubBillingUsageReportOrgRequest,
  BillingUsageReport,
  GetGithubBillingUsageReportOrgError,
  GithubOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetGithubBillingUsageReportOrgRequest,
  output: BillingUsageReport,
  errors: [BadRequest, Forbidden],
  protocol: GithubProtocol,
  retry: Retry.Retry,
}));

export type GetGithubBillingUsageReportUserError =
  | BadRequest
  | Forbidden
  | GithubOpError;
/** Get billing usage report for a user Gets a report of the total usage for a user. **Note:** This endpoint is only available to users with access to the enhanced billing platform. */
export const getGithubBillingUsageReportUser: API.OperationMethod<
  GetGithubBillingUsageReportUserRequest,
  BillingUsageReportUser,
  GetGithubBillingUsageReportUserError,
  GithubOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetGithubBillingUsageReportUserRequest,
  output: BillingUsageReportUser,
  errors: [BadRequest, Forbidden],
  protocol: GithubProtocol,
  retry: Retry.Retry,
}));

export type GetGithubBillingUsageSummaryReportOrgError =
  | BadRequest
  | Forbidden
  | GithubOpError;
/** Get billing usage summary for an organization > [!NOTE] > This endpoint is in public preview and is subject to change. Gets a summary report of usage for an organization. To use this endpoint, you must be an administrator of an organization within an enterprise or an organization account. **Note:** Only data from the past 24 months is accessible via this endpoint. */
export const getGithubBillingUsageSummaryReportOrg: API.OperationMethod<
  GetGithubBillingUsageSummaryReportOrgRequest,
  BillingUsageSummaryReportOrg,
  GetGithubBillingUsageSummaryReportOrgError,
  GithubOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetGithubBillingUsageSummaryReportOrgRequest,
  output: BillingUsageSummaryReportOrg,
  errors: [BadRequest, Forbidden],
  protocol: GithubProtocol,
  retry: Retry.Retry,
}));

export type GetGithubBillingUsageSummaryReportUserError =
  | BadRequest
  | Forbidden
  | NotFound
  | GithubOpError;
/** Get billing usage summary for a user > [!NOTE] > This endpoint is in public preview and is subject to change. Gets a summary report of usage for a user. **Note:** Only data from the past 24 months is accessible via this endpoint. */
export const getGithubBillingUsageSummaryReportUser: API.OperationMethod<
  GetGithubBillingUsageSummaryReportUserRequest,
  BillingUsageSummaryReportUser,
  GetGithubBillingUsageSummaryReportUserError,
  GithubOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetGithubBillingUsageSummaryReportUserRequest,
  output: BillingUsageSummaryReportUser,
  errors: [BadRequest, Forbidden, NotFound],
  protocol: GithubProtocol,
  retry: Retry.Retry,
}));

export type UpdateBudgetOrgError =
  | BadRequest
  | Forbidden
  | NotFound
  | UnprocessableEntity
  | GithubOpError;
/** Update a budget for an organization Updates an existing budget for an organization. The authenticated user must be an organization admin or billing manager. */
export const updateBudgetOrg: API.OperationMethod<
  UpdateBudgetOrgRequest,
  UpdateBudget,
  UpdateBudgetOrgError,
  GithubOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: UpdateBudgetOrgRequest,
  output: UpdateBudget,
  errors: [BadRequest, Forbidden, NotFound, UnprocessableEntity],
  protocol: GithubProtocol,
  retry: Retry.Retry,
}));
