import * as Schema from "effect/Schema";

export const ClusterSizeSkuSerializerSchema =
  /*@__PURE__*/ /*#__PURE__*/ Schema.Struct({
    name: Schema.String,
    display_name: Schema.String,
    cpu: Schema.String,
    storage: Schema.optional(Schema.NullOr(Schema.Number)),
    ram: Schema.Number,
    metal: Schema.Boolean,
    enabled: Schema.Boolean,
    provider: Schema.optional(Schema.NullOr(Schema.String)),
    default_vtgate: Schema.String,
    default_vtgate_rate: Schema.optional(Schema.NullOr(Schema.Number)),
    replica_rate: Schema.optional(Schema.NullOr(Schema.Number)),
    rate: Schema.optional(Schema.NullOr(Schema.Number)),
    sort_order: Schema.Number,
    architecture: Schema.optional(Schema.NullOr(Schema.String)),
    development: Schema.Boolean,
    production: Schema.Boolean,
  });
export const PostgresClusterExtensionSchema =
  /*@__PURE__*/ /*#__PURE__*/ Schema.Struct({
    id: Schema.String,
    name: Schema.String,
    description: Schema.String,
    internal: Schema.Boolean,
    shared_preload_allowed: Schema.Boolean,
    url: Schema.String,
    available: Schema.Boolean,
    unavailable_reason: Schema.String,
    parameters: Schema.Array(
      Schema.Struct({
        id: Schema.String,
        name: Schema.String,
        display_name: Schema.String,
        namespace: Schema.Literals(["patroni", "pgconf", "pgbouncer"]),
        category: Schema.String,
        description: Schema.String,
        extension: Schema.Boolean,
        immutable: Schema.Boolean,
        parameter_type: Schema.Literals([
          "array",
          "boolean",
          "bytes",
          "float",
          "integer",
          "seconds",
          "select",
          "string",
          "time",
        ]),
        default_value: Schema.String,
        value: Schema.String,
        required: Schema.Boolean,
        created_at: Schema.String,
        updated_at: Schema.String,
        restart: Schema.Boolean,
        max: Schema.Number,
        min: Schema.Number,
        step: Schema.Number,
        url: Schema.String,
        options: Schema.Array(Schema.String),
        actor: Schema.Struct({
          id: Schema.String,
          display_name: Schema.String,
          avatar_url: Schema.String,
        }),
      }),
    ),
  });
export const PostgresClusterParameterSchema =
  /*@__PURE__*/ /*#__PURE__*/ Schema.Struct({
    id: Schema.String,
    name: Schema.String,
    display_name: Schema.String,
    namespace: Schema.Literals(["patroni", "pgconf", "pgbouncer"]),
    category: Schema.String,
    description: Schema.String,
    extension: Schema.Boolean,
    immutable: Schema.Boolean,
    parameter_type: Schema.Literals([
      "array",
      "boolean",
      "bytes",
      "float",
      "integer",
      "seconds",
      "select",
      "string",
      "time",
    ]),
    default_value: Schema.String,
    value: Schema.String,
    required: Schema.Boolean,
    created_at: Schema.String,
    updated_at: Schema.String,
    restart: Schema.Boolean,
    max: Schema.Number,
    min: Schema.Number,
    step: Schema.Number,
    url: Schema.String,
    options: Schema.Array(Schema.String),
    actor: Schema.Struct({
      id: Schema.String,
      display_name: Schema.String,
      avatar_url: Schema.String,
    }),
  });
