import * as Schema from "effect/Schema";
import { API } from "../client.ts";
import * as T from "../traits.ts";

const __document =
  "mutation accountSetRequireTwoFactor($accountName: ID, $accountID: ID!, $requireTwoFactor: Boolean!) {\n  account(accountName: $accountName) {\n    setRequireTwoFactor(accountID: $accountID, requireTwoFactor: $requireTwoFactor) {\n      accessTokens {\n        createdAt\n        id\n        lastUsedAt\n        note\n        owner {\n          created\n          displayName\n          firstName\n          id\n          isExpoAdmin\n          lastDeletionAttemptTime\n        }\n        revokedAt\n        updatedAt\n        visibleTokenPrefix\n      }\n      appCount\n      appStoreConnectApiKeys {\n        appleTeam {\n          appleTeamIdentifier\n          appleTeamName\n          appleTeamType\n          id\n          lastDeletionAttemptTime\n        }\n        createdAt\n        id\n        issuerIdentifier\n        keyIdentifier\n        keyP8\n        name\n        roles\n        updatedAt\n      }\n      appleDistributionCertificates {\n        appleTeam {\n          appleTeamIdentifier\n          appleTeamName\n          appleTeamType\n          id\n          lastDeletionAttemptTime\n        }\n        certificateP12\n        certificatePassword\n        certificatePrivateSigningKey\n        createdAt\n        developerPortalIdentifier\n        id\n        iosAppBuildCredentialsList {\n          id\n          iosDistributionType\n        }\n        serialNumber\n        updatedAt\n        validityNotAfter\n        validityNotBefore\n      }\n      applePushKeys {\n        appleTeam {\n          appleTeamIdentifier\n          appleTeamName\n          appleTeamType\n          id\n          lastDeletionAttemptTime\n        }\n        createdAt\n        id\n        iosAppCredentialsList {\n          id\n        }\n        keyIdentifier\n        keyP8\n        updatedAt\n      }\n      availableBuilds\n      billing {\n        charges {\n          amount\n          createdAt\n          id\n          invoiceId\n          paid\n          receiptUrl\n          wasRefunded\n        }\n        id\n        payment {\n          id\n        }\n        subscription {\n          cancelAt\n          endedAt\n          id\n          isDowngrading\n          name\n          nextInvoice\n          nextInvoiceAmountDueCents\n          planId\n          price\n          recurringCents\n          status\n          trialEnd\n          willCancel\n        }\n      }\n      convexTeamConnections {\n        convexTeamIdentifier\n        createdAt\n        id\n        updatedAt\n      }\n      createdAt\n      displayName\n      environmentVariableEnvironments\n      githubAppInstallations {\n        actor {\n          created\n          displayName\n          firstName\n          id\n          isExpoAdmin\n          lastDeletionAttemptTime\n        }\n        id\n        installationIdentifier\n        metadata {\n          githubAccountAvatarUrl\n          githubAccountName\n          githubAccountType\n          installationStatus\n        }\n      }\n      googleServiceAccountKeys {\n        clientEmail\n        clientIdentifier\n        createdAt\n        id\n        keyJson\n        privateKeyIdentifier\n        projectIdentifier\n        updatedAt\n      }\n      hasBuilds\n      id\n      isCurrent\n      isDisabled\n      isFreeAppDevDomainTier\n      isSSOEnabled\n      lastDeletionAttemptTime\n      logRocketOrganization {\n        createdAt\n        id\n        orgName\n        orgSlug\n      }\n      memberStats {\n        allHave2FAEnabled\n        humanCount\n        ownerCount\n        robotCount\n        ssoUserCount\n        totalCount\n      }\n      name\n      offers {\n        features\n        id\n        prerequisite {\n          stripeIds\n          type\n        }\n        price\n        quantity\n        stripeId\n        trialLength\n        type\n      }\n      onboardingStats {\n        firstBuildCompletedAt\n        firstProjectCreatedAt\n        firstSubmissionCompletedAt\n        firstUpdateCreatedAt\n        hasConfiguredUpdate\n        hasConfiguredWorkflow\n        hasTeamMembers\n      }\n      owner {\n        accessTokens {\n          createdAt\n          id\n          lastUsedAt\n          note\n          revokedAt\n          updatedAt\n          visibleTokenPrefix\n        }\n        appCount\n        appetizeCode\n        bestContactEmail\n        created\n        discordUser {\n          discordIdentifier\n          id\n        }\n        displayName\n        email\n        emailVerified\n        experiments {\n          createdAt\n          enabled\n          experiment\n          id\n          updatedAt\n        }\n        firstName\n        fullName\n        githubUser {\n          githubUserIdentifier\n          id\n        }\n        githubUsername\n        hasPassword\n        hasPendingUserInvitations\n        id\n        industry\n        isExpoAdmin\n        isLegacy\n        isSecondFactorAuthenticationEnabled\n        isStaffModeEnabled\n        lastDeletionAttemptTime\n        lastName\n        location\n        newEmailPendingVerification\n        oAuthIdentities {\n          email\n          id\n          login\n          provider\n        }\n        pendingUserInvitations {\n          accountName\n          accountProfileImageUrl\n          accountProfilePhoto\n          accountRequiresTwoFactor\n          created\n          email\n          expires\n          id\n          isForOrganization\n          permissions\n          role\n        }\n        pinnedApps {\n          appStoreUrl\n          assetLimitPerUpdateGroup\n          buildProfiles\n          buildsReleaseChannels\n          description\n          environmentVariableEnvironments\n          fullName\n          githubUrl\n          iconUrl\n          id\n          internalDistributionBuildPrivacy\n          isDeleting\n          isDeprecated\n          isLikedByMe\n          lastDeletionAttemptTime\n          lastPublishedTime\n          latestActivity\n          latestReleaseId\n          likeCount\n          name\n          packageName\n          packageUsername\n          playStoreUrl\n          privacy\n          privacySetting\n          published\n          pushSecurityEnabled\n          releaseChannels\n          requiresAccessTokenForPushSecurity\n          resourceClassExperiment\n          scopeKey\n          sdkVersion\n          slug\n          suggestedDevDomainName\n          trendScore\n          updated\n          username\n        }\n        pinnedDashboardViews {\n          view\n        }\n        preferences {\n          selectedAccountName\n        }\n        primaryAccountProfileImageUrl\n        profilePhoto\n        secondFactorDevices {\n          createdAt\n          id\n          isCertified\n          isPrimary\n          method\n          name\n          smsPhoneNumber\n          updatedAt\n        }\n        twitterUsername\n        username\n      }\n      ownerUserActor {\n        accessTokens {\n          createdAt\n          id\n          lastUsedAt\n          note\n          revokedAt\n          updatedAt\n          visibleTokenPrefix\n        }\n        appCount\n        appetizeCode\n        bestContactEmail\n        created\n        discordUser {\n          discordIdentifier\n          id\n        }\n        displayName\n        experiments {\n          createdAt\n          enabled\n          experiment\n          id\n          updatedAt\n        }\n        firstName\n        fullName\n        githubUser {\n          githubUserIdentifier\n          id\n        }\n        githubUsername\n        id\n        industry\n        isExpoAdmin\n        isStaffModeEnabled\n        lastDeletionAttemptTime\n        lastName\n        location\n        pinnedApps {\n          appStoreUrl\n          assetLimitPerUpdateGroup\n          buildProfiles\n          buildsReleaseChannels\n          description\n          environmentVariableEnvironments\n          fullName\n          githubUrl\n          iconUrl\n          id\n          internalDistributionBuildPrivacy\n          isDeleting\n          isDeprecated\n          isLikedByMe\n          lastDeletionAttemptTime\n          lastPublishedTime\n          latestActivity\n          latestReleaseId\n          likeCount\n          name\n          packageName\n          packageUsername\n          playStoreUrl\n          privacy\n          privacySetting\n          published\n          pushSecurityEnabled\n          releaseChannels\n          requiresAccessTokenForPushSecurity\n          resourceClassExperiment\n          scopeKey\n          sdkVersion\n          slug\n          suggestedDevDomainName\n          trendScore\n          updated\n          username\n        }\n        preferences {\n          selectedAccountName\n        }\n        primaryAccountProfileImageUrl\n        profilePhoto\n        twitterUsername\n        username\n      }\n      pendingSentryInstallation {\n        createdAt\n        id\n        installationId\n        orgSlug\n      }\n      profileImageUrl\n      pushSecurityEnabled\n      requireTwoFactor\n      requiresAccessTokenForPushSecurity\n      sentryInstallation {\n        createdAt\n        id\n        installationId\n        orgSlug\n      }\n      ssoAllowedAuthProviders\n      ssoConfiguration {\n        authProtocol\n        authProviderIdentifier\n        clientIdentifier\n        clientSecret\n        createdAt\n        id\n        issuer\n        updatedAt\n      }\n      subscription {\n        addons {\n          id\n          name\n          nextInvoice\n          planId\n          quantity\n          willCancel\n        }\n        cancelAt\n        concurrencies {\n          android\n          ios\n          total\n        }\n        coupon {\n          amountOff\n          appliesTo\n          id\n          name\n          percentOff\n          valid\n        }\n        endedAt\n        futureSubscription {\n          createdAt\n          id\n          planId\n          recurringCents\n          startDate\n        }\n        id\n        isDowngrading\n        meteredBillingStatus {\n          EAS_BUILD\n          EAS_UPDATE\n        }\n        name\n        nextInvoice\n        nextInvoiceAmountDueCents\n        planId\n        price\n        recurringCents\n        status\n        trialEnd\n        upcomingInvoice {\n          amountDue\n          amountPaid\n          amountRemaining\n          id\n          startingBalance\n          subtotal\n          total\n          totalDiscountedAmount\n        }\n        willCancel\n      }\n      subscriptionChangesPending\n      unlimitedBuilds\n      updatedAt\n      userActorOwner {\n        accessTokens {\n          createdAt\n          id\n          lastUsedAt\n          note\n          revokedAt\n          updatedAt\n          visibleTokenPrefix\n        }\n        appCount\n        appetizeCode\n        bestContactEmail\n        created\n        discordUser {\n          discordIdentifier\n          id\n        }\n        displayName\n        experiments {\n          createdAt\n          enabled\n          experiment\n          id\n          updatedAt\n        }\n        firstName\n        fullName\n        githubUser {\n          githubUserIdentifier\n          id\n        }\n        githubUsername\n        id\n        industry\n        isExpoAdmin\n        isStaffModeEnabled\n        lastDeletionAttemptTime\n        lastName\n        location\n        pinnedApps {\n          appStoreUrl\n          assetLimitPerUpdateGroup\n          buildProfiles\n          buildsReleaseChannels\n          description\n          environmentVariableEnvironments\n          fullName\n          githubUrl\n          iconUrl\n          id\n          internalDistributionBuildPrivacy\n          isDeleting\n          isDeprecated\n          isLikedByMe\n          lastDeletionAttemptTime\n          lastPublishedTime\n          latestActivity\n          latestReleaseId\n          likeCount\n          name\n          packageName\n          packageUsername\n          playStoreUrl\n          privacy\n          privacySetting\n          published\n          pushSecurityEnabled\n          releaseChannels\n          requiresAccessTokenForPushSecurity\n          resourceClassExperiment\n          scopeKey\n          sdkVersion\n          slug\n          suggestedDevDomainName\n          trendScore\n          updated\n          username\n        }\n        preferences {\n          selectedAccountName\n        }\n        primaryAccountProfileImageUrl\n        profilePhoto\n        twitterUsername\n        username\n      }\n      userInvitations {\n        accountName\n        accountProfileImageUrl\n        accountProfilePhoto\n        accountRequiresTwoFactor\n        created\n        email\n        expires\n        id\n        isForOrganization\n        permissions\n        role\n      }\n      userSpecifiedAccountUsage\n      users {\n        actor {\n          created\n          displayName\n          firstName\n          id\n          isExpoAdmin\n          lastDeletionAttemptTime\n        }\n        id\n        permissions\n        role\n        user {\n          appCount\n          appetizeCode\n          bestContactEmail\n          created\n          displayName\n          email\n          emailVerified\n          firstName\n          fullName\n          githubUsername\n          hasPassword\n          hasPendingUserInvitations\n          id\n          industry\n          isExpoAdmin\n          isLegacy\n          isSecondFactorAuthenticationEnabled\n          isStaffModeEnabled\n          lastDeletionAttemptTime\n          lastName\n          location\n          newEmailPendingVerification\n          primaryAccountProfileImageUrl\n          profilePhoto\n          twitterUsername\n          username\n        }\n        userActor {\n          appCount\n          appetizeCode\n          bestContactEmail\n          created\n          displayName\n          firstName\n          fullName\n          githubUsername\n          id\n          industry\n          isExpoAdmin\n          isStaffModeEnabled\n          lastDeletionAttemptTime\n          lastName\n          location\n          primaryAccountProfileImageUrl\n          profilePhoto\n          twitterUsername\n          username\n        }\n      }\n      vexoAccountConnection {\n        accessToken {\n          access_token\n          expires_at\n          token_type\n        }\n        id\n      }\n      viewerUserPermission {\n        actor {\n          created\n          displayName\n          firstName\n          id\n          isExpoAdmin\n          lastDeletionAttemptTime\n        }\n        id\n        permissions\n        role\n        user {\n          appCount\n          appetizeCode\n          bestContactEmail\n          created\n          displayName\n          email\n          emailVerified\n          firstName\n          fullName\n          githubUsername\n          hasPassword\n          hasPendingUserInvitations\n          id\n          industry\n          isExpoAdmin\n          isLegacy\n          isSecondFactorAuthenticationEnabled\n          isStaffModeEnabled\n          lastDeletionAttemptTime\n          lastName\n          location\n          newEmailPendingVerification\n          primaryAccountProfileImageUrl\n          profilePhoto\n          twitterUsername\n          username\n        }\n        userActor {\n          appCount\n          appetizeCode\n          bestContactEmail\n          created\n          displayName\n          firstName\n          fullName\n          githubUsername\n          id\n          industry\n          isExpoAdmin\n          isStaffModeEnabled\n          lastDeletionAttemptTime\n          lastName\n          location\n          primaryAccountProfileImageUrl\n          profilePhoto\n          twitterUsername\n          username\n        }\n      }\n      willAutoRenewBuilds\n    }\n  }\n}";

// Input Schema (GraphQL variables)
export const AccountSetRequireTwoFactorInput = Schema.Struct({
  accountName: Schema.optional(Schema.NullOr(Schema.String)),
  accountID: Schema.String,
  requireTwoFactor: Schema.Boolean,
}).pipe(
  T.Http({ method: "POST", path: "/graphql" }),
  T.GraphQLOp({
    query: __document,
    operationName: "accountSetRequireTwoFactor",
    type: "mutation",
  }),
);
export type AccountSetRequireTwoFactorInput =
  typeof AccountSetRequireTwoFactorInput.Type;

// Output Schema (GraphQL selection set)
export const AccountSetRequireTwoFactorOutput = Schema.Struct({
  accessTokens: Schema.Array(
    Schema.NullOr(
      Schema.Struct({
        createdAt: Schema.String,
        id: Schema.String,
        lastUsedAt: Schema.NullOr(Schema.String),
        note: Schema.NullOr(Schema.String),
        owner: Schema.Struct({
          created: Schema.String,
          displayName: Schema.String,
          firstName: Schema.NullOr(Schema.String),
          id: Schema.String,
          isExpoAdmin: Schema.Boolean,
          lastDeletionAttemptTime: Schema.NullOr(Schema.String),
        }),
        revokedAt: Schema.NullOr(Schema.String),
        updatedAt: Schema.String,
        visibleTokenPrefix: Schema.String,
      }),
    ),
  ),
  appCount: Schema.Number,
  appStoreConnectApiKeys: Schema.Array(
    Schema.Struct({
      appleTeam: Schema.NullOr(
        Schema.Struct({
          appleTeamIdentifier: Schema.String,
          appleTeamName: Schema.NullOr(Schema.String),
          appleTeamType: Schema.NullOr(
            Schema.Literals([
              "COMPANY_OR_ORGANIZATION",
              "INDIVIDUAL",
              "IN_HOUSE",
            ]),
          ),
          id: Schema.String,
          lastDeletionAttemptTime: Schema.NullOr(Schema.String),
        }),
      ),
      createdAt: Schema.String,
      id: Schema.String,
      issuerIdentifier: Schema.String,
      keyIdentifier: Schema.String,
      keyP8: Schema.String,
      name: Schema.NullOr(Schema.String),
      roles: Schema.NullOr(
        Schema.Array(
          Schema.Literals([
            "ACCESS_TO_REPORTS",
            "ACCOUNT_HOLDER",
            "ADMIN",
            "APP_MANAGER",
            "CLOUD_MANAGED_APP_DISTRIBUTION",
            "CLOUD_MANAGED_DEVELOPER_ID",
            "CREATE_APPS",
            "CUSTOMER_SUPPORT",
            "DEVELOPER",
            "FINANCE",
            "IMAGE_MANAGER",
            "MARKETING",
            "READ_ONLY",
            "SALES",
            "TECHNICAL",
            "UNKNOWN",
          ]),
        ),
      ),
      updatedAt: Schema.String,
    }),
  ),
  appleDistributionCertificates: Schema.Array(
    Schema.Struct({
      appleTeam: Schema.NullOr(
        Schema.Struct({
          appleTeamIdentifier: Schema.String,
          appleTeamName: Schema.NullOr(Schema.String),
          appleTeamType: Schema.NullOr(
            Schema.Literals([
              "COMPANY_OR_ORGANIZATION",
              "INDIVIDUAL",
              "IN_HOUSE",
            ]),
          ),
          id: Schema.String,
          lastDeletionAttemptTime: Schema.NullOr(Schema.String),
        }),
      ),
      certificateP12: Schema.NullOr(Schema.String),
      certificatePassword: Schema.NullOr(Schema.String),
      certificatePrivateSigningKey: Schema.NullOr(Schema.String),
      createdAt: Schema.String,
      developerPortalIdentifier: Schema.NullOr(Schema.String),
      id: Schema.String,
      iosAppBuildCredentialsList: Schema.Array(
        Schema.Struct({
          id: Schema.String,
          iosDistributionType: Schema.Literals([
            "AD_HOC",
            "APP_STORE",
            "DEVELOPMENT",
            "ENTERPRISE",
          ]),
        }),
      ),
      serialNumber: Schema.String,
      updatedAt: Schema.String,
      validityNotAfter: Schema.String,
      validityNotBefore: Schema.String,
    }),
  ),
  applePushKeys: Schema.Array(
    Schema.Struct({
      appleTeam: Schema.NullOr(
        Schema.Struct({
          appleTeamIdentifier: Schema.String,
          appleTeamName: Schema.NullOr(Schema.String),
          appleTeamType: Schema.NullOr(
            Schema.Literals([
              "COMPANY_OR_ORGANIZATION",
              "INDIVIDUAL",
              "IN_HOUSE",
            ]),
          ),
          id: Schema.String,
          lastDeletionAttemptTime: Schema.NullOr(Schema.String),
        }),
      ),
      createdAt: Schema.String,
      id: Schema.String,
      iosAppCredentialsList: Schema.Array(
        Schema.Struct({
          id: Schema.String,
        }),
      ),
      keyIdentifier: Schema.String,
      keyP8: Schema.String,
      updatedAt: Schema.String,
    }),
  ),
  availableBuilds: Schema.NullOr(Schema.Number),
  billing: Schema.NullOr(
    Schema.Struct({
      charges: Schema.NullOr(
        Schema.Array(
          Schema.NullOr(
            Schema.Struct({
              amount: Schema.Number,
              createdAt: Schema.String,
              id: Schema.String,
              invoiceId: Schema.NullOr(Schema.String),
              paid: Schema.Boolean,
              receiptUrl: Schema.NullOr(Schema.String),
              wasRefunded: Schema.Boolean,
            }),
          ),
        ),
      ),
      id: Schema.String,
      payment: Schema.NullOr(
        Schema.Struct({
          id: Schema.String,
        }),
      ),
      subscription: Schema.NullOr(
        Schema.Struct({
          cancelAt: Schema.NullOr(Schema.String),
          endedAt: Schema.NullOr(Schema.String),
          id: Schema.String,
          isDowngrading: Schema.NullOr(Schema.Boolean),
          name: Schema.NullOr(Schema.String),
          nextInvoice: Schema.NullOr(Schema.String),
          nextInvoiceAmountDueCents: Schema.NullOr(Schema.Number),
          planId: Schema.NullOr(Schema.String),
          price: Schema.Number,
          recurringCents: Schema.NullOr(Schema.Number),
          status: Schema.NullOr(Schema.String),
          trialEnd: Schema.NullOr(Schema.String),
          willCancel: Schema.NullOr(Schema.Boolean),
        }),
      ),
    }),
  ),
  convexTeamConnections: Schema.Array(
    Schema.Struct({
      convexTeamIdentifier: Schema.String,
      createdAt: Schema.String,
      id: Schema.String,
      updatedAt: Schema.String,
    }),
  ),
  createdAt: Schema.String,
  displayName: Schema.NullOr(Schema.String),
  environmentVariableEnvironments: Schema.Array(Schema.Unknown),
  githubAppInstallations: Schema.Array(
    Schema.Struct({
      actor: Schema.NullOr(
        Schema.Struct({
          created: Schema.String,
          displayName: Schema.String,
          firstName: Schema.NullOr(Schema.String),
          id: Schema.String,
          isExpoAdmin: Schema.Boolean,
          lastDeletionAttemptTime: Schema.NullOr(Schema.String),
        }),
      ),
      id: Schema.String,
      installationIdentifier: Schema.Number,
      metadata: Schema.Struct({
        githubAccountAvatarUrl: Schema.NullOr(Schema.String),
        githubAccountName: Schema.NullOr(Schema.String),
        githubAccountType: Schema.NullOr(
          Schema.Literals(["ORGANIZATION", "USER"]),
        ),
        installationStatus: Schema.Literals([
          "ACTIVE",
          "NOT_INSTALLED",
          "SUSPENDED",
        ]),
      }),
    }),
  ),
  googleServiceAccountKeys: Schema.Array(
    Schema.Struct({
      clientEmail: Schema.String,
      clientIdentifier: Schema.String,
      createdAt: Schema.String,
      id: Schema.String,
      keyJson: Schema.String,
      privateKeyIdentifier: Schema.String,
      projectIdentifier: Schema.String,
      updatedAt: Schema.String,
    }),
  ),
  hasBuilds: Schema.Boolean,
  id: Schema.String,
  isCurrent: Schema.Boolean,
  isDisabled: Schema.Boolean,
  isFreeAppDevDomainTier: Schema.Boolean,
  isSSOEnabled: Schema.Boolean,
  lastDeletionAttemptTime: Schema.NullOr(Schema.String),
  logRocketOrganization: Schema.NullOr(
    Schema.Struct({
      createdAt: Schema.String,
      id: Schema.String,
      orgName: Schema.String,
      orgSlug: Schema.String,
    }),
  ),
  memberStats: Schema.Struct({
    allHave2FAEnabled: Schema.Boolean,
    humanCount: Schema.Number,
    ownerCount: Schema.Number,
    robotCount: Schema.Number,
    ssoUserCount: Schema.Number,
    totalCount: Schema.Number,
  }),
  name: Schema.String,
  offers: Schema.NullOr(
    Schema.Array(
      Schema.Struct({
        features: Schema.NullOr(
          Schema.Array(
            Schema.NullOr(
              Schema.Literals(["BUILDS", "OPEN_SOURCE", "SUPPORT", "TEAMS"]),
            ),
          ),
        ),
        id: Schema.String,
        prerequisite: Schema.NullOr(
          Schema.Struct({
            stripeIds: Schema.Array(Schema.String),
            type: Schema.String,
          }),
        ),
        price: Schema.Number,
        quantity: Schema.NullOr(Schema.Number),
        stripeId: Schema.String,
        trialLength: Schema.NullOr(Schema.Number),
        type: Schema.Literals(["ADDON", "PREPAID", "SUBSCRIPTION"]),
      }),
    ),
  ),
  onboardingStats: Schema.Struct({
    firstBuildCompletedAt: Schema.NullOr(Schema.String),
    firstProjectCreatedAt: Schema.NullOr(Schema.String),
    firstSubmissionCompletedAt: Schema.NullOr(Schema.String),
    firstUpdateCreatedAt: Schema.NullOr(Schema.String),
    hasConfiguredUpdate: Schema.Boolean,
    hasConfiguredWorkflow: Schema.Boolean,
    hasTeamMembers: Schema.Boolean,
  }),
  owner: Schema.NullOr(
    Schema.Struct({
      accessTokens: Schema.Array(
        Schema.Struct({
          createdAt: Schema.String,
          id: Schema.String,
          lastUsedAt: Schema.NullOr(Schema.String),
          note: Schema.NullOr(Schema.String),
          revokedAt: Schema.NullOr(Schema.String),
          updatedAt: Schema.String,
          visibleTokenPrefix: Schema.String,
        }),
      ),
      appCount: Schema.Number,
      appetizeCode: Schema.NullOr(Schema.String),
      bestContactEmail: Schema.NullOr(Schema.String),
      created: Schema.String,
      discordUser: Schema.NullOr(
        Schema.Struct({
          discordIdentifier: Schema.String,
          id: Schema.String,
        }),
      ),
      displayName: Schema.String,
      email: Schema.String,
      emailVerified: Schema.Boolean,
      experiments: Schema.Array(
        Schema.Struct({
          createdAt: Schema.String,
          enabled: Schema.Boolean,
          experiment: Schema.Literals(["ORBIT"]),
          id: Schema.String,
          updatedAt: Schema.String,
        }),
      ),
      firstName: Schema.NullOr(Schema.String),
      fullName: Schema.NullOr(Schema.String),
      githubUser: Schema.NullOr(
        Schema.Struct({
          githubUserIdentifier: Schema.String,
          id: Schema.String,
        }),
      ),
      githubUsername: Schema.NullOr(Schema.String),
      hasPassword: Schema.Boolean,
      hasPendingUserInvitations: Schema.Boolean,
      id: Schema.String,
      industry: Schema.NullOr(Schema.String),
      isExpoAdmin: Schema.Boolean,
      isLegacy: Schema.Boolean,
      isSecondFactorAuthenticationEnabled: Schema.Boolean,
      isStaffModeEnabled: Schema.Boolean,
      lastDeletionAttemptTime: Schema.NullOr(Schema.String),
      lastName: Schema.NullOr(Schema.String),
      location: Schema.NullOr(Schema.String),
      newEmailPendingVerification: Schema.NullOr(Schema.String),
      oAuthIdentities: Schema.Array(
        Schema.Struct({
          email: Schema.String,
          id: Schema.String,
          login: Schema.NullOr(Schema.String),
          provider: Schema.Literals(["apple", "github", "google"]),
        }),
      ),
      pendingUserInvitations: Schema.Array(
        Schema.Struct({
          accountName: Schema.String,
          accountProfileImageUrl: Schema.String,
          accountProfilePhoto: Schema.NullOr(Schema.String),
          accountRequiresTwoFactor: Schema.Boolean,
          created: Schema.String,
          email: Schema.String,
          expires: Schema.String,
          id: Schema.String,
          isForOrganization: Schema.Boolean,
          permissions: Schema.Array(
            Schema.Literals(["ADMIN", "OWN", "PUBLISH", "VIEW"]),
          ),
          role: Schema.Literals([
            "ADMIN",
            "CUSTOM",
            "DEVELOPER",
            "HAS_ADMIN",
            "NOT_ADMIN",
            "OWNER",
            "VIEW_ONLY",
          ]),
        }),
      ),
      pinnedApps: Schema.Array(
        Schema.Struct({
          appStoreUrl: Schema.NullOr(Schema.String),
          assetLimitPerUpdateGroup: Schema.Number,
          buildProfiles: Schema.Array(Schema.String),
          buildsReleaseChannels: Schema.Array(Schema.String),
          description: Schema.String,
          environmentVariableEnvironments: Schema.Array(Schema.Unknown),
          fullName: Schema.String,
          githubUrl: Schema.NullOr(Schema.String),
          iconUrl: Schema.NullOr(Schema.String),
          id: Schema.String,
          internalDistributionBuildPrivacy: Schema.Literals([
            "PRIVATE",
            "PUBLIC",
          ]),
          isDeleting: Schema.Boolean,
          isDeprecated: Schema.Boolean,
          isLikedByMe: Schema.Boolean,
          lastDeletionAttemptTime: Schema.NullOr(Schema.String),
          lastPublishedTime: Schema.String,
          latestActivity: Schema.String,
          latestReleaseId: Schema.String,
          likeCount: Schema.Number,
          name: Schema.String,
          packageName: Schema.String,
          packageUsername: Schema.String,
          playStoreUrl: Schema.NullOr(Schema.String),
          privacy: Schema.String,
          privacySetting: Schema.Literals(["HIDDEN", "PUBLIC", "UNLISTED"]),
          published: Schema.Boolean,
          pushSecurityEnabled: Schema.Boolean,
          releaseChannels: Schema.Array(Schema.String),
          requiresAccessTokenForPushSecurity: Schema.Boolean,
          resourceClassExperiment: Schema.NullOr(
            Schema.Literals(["C3D", "N2"]),
          ),
          scopeKey: Schema.String,
          sdkVersion: Schema.String,
          slug: Schema.String,
          suggestedDevDomainName: Schema.String,
          trendScore: Schema.Number,
          updated: Schema.String,
          username: Schema.String,
        }),
      ),
      pinnedDashboardViews: Schema.Array(
        Schema.Struct({
          view: Schema.Literals(["ACTIVITY", "OVERVIEW"]),
        }),
      ),
      preferences: Schema.Struct({
        selectedAccountName: Schema.NullOr(Schema.String),
      }),
      primaryAccountProfileImageUrl: Schema.NullOr(Schema.String),
      profilePhoto: Schema.String,
      secondFactorDevices: Schema.Array(
        Schema.Struct({
          createdAt: Schema.String,
          id: Schema.String,
          isCertified: Schema.Boolean,
          isPrimary: Schema.Boolean,
          method: Schema.Literals(["AUTHENTICATOR", "SMS"]),
          name: Schema.String,
          smsPhoneNumber: Schema.NullOr(Schema.String),
          updatedAt: Schema.String,
        }),
      ),
      twitterUsername: Schema.NullOr(Schema.String),
      username: Schema.String,
    }),
  ),
  ownerUserActor: Schema.NullOr(
    Schema.Struct({
      accessTokens: Schema.Array(
        Schema.Struct({
          createdAt: Schema.String,
          id: Schema.String,
          lastUsedAt: Schema.NullOr(Schema.String),
          note: Schema.NullOr(Schema.String),
          revokedAt: Schema.NullOr(Schema.String),
          updatedAt: Schema.String,
          visibleTokenPrefix: Schema.String,
        }),
      ),
      appCount: Schema.Number,
      appetizeCode: Schema.NullOr(Schema.String),
      bestContactEmail: Schema.NullOr(Schema.String),
      created: Schema.String,
      discordUser: Schema.NullOr(
        Schema.Struct({
          discordIdentifier: Schema.String,
          id: Schema.String,
        }),
      ),
      displayName: Schema.String,
      experiments: Schema.Array(
        Schema.Struct({
          createdAt: Schema.String,
          enabled: Schema.Boolean,
          experiment: Schema.Literals(["ORBIT"]),
          id: Schema.String,
          updatedAt: Schema.String,
        }),
      ),
      firstName: Schema.NullOr(Schema.String),
      fullName: Schema.NullOr(Schema.String),
      githubUser: Schema.NullOr(
        Schema.Struct({
          githubUserIdentifier: Schema.String,
          id: Schema.String,
        }),
      ),
      githubUsername: Schema.NullOr(Schema.String),
      id: Schema.String,
      industry: Schema.NullOr(Schema.String),
      isExpoAdmin: Schema.Boolean,
      isStaffModeEnabled: Schema.Boolean,
      lastDeletionAttemptTime: Schema.NullOr(Schema.String),
      lastName: Schema.NullOr(Schema.String),
      location: Schema.NullOr(Schema.String),
      pinnedApps: Schema.Array(
        Schema.Struct({
          appStoreUrl: Schema.NullOr(Schema.String),
          assetLimitPerUpdateGroup: Schema.Number,
          buildProfiles: Schema.Array(Schema.String),
          buildsReleaseChannels: Schema.Array(Schema.String),
          description: Schema.String,
          environmentVariableEnvironments: Schema.Array(Schema.Unknown),
          fullName: Schema.String,
          githubUrl: Schema.NullOr(Schema.String),
          iconUrl: Schema.NullOr(Schema.String),
          id: Schema.String,
          internalDistributionBuildPrivacy: Schema.Literals([
            "PRIVATE",
            "PUBLIC",
          ]),
          isDeleting: Schema.Boolean,
          isDeprecated: Schema.Boolean,
          isLikedByMe: Schema.Boolean,
          lastDeletionAttemptTime: Schema.NullOr(Schema.String),
          lastPublishedTime: Schema.String,
          latestActivity: Schema.String,
          latestReleaseId: Schema.String,
          likeCount: Schema.Number,
          name: Schema.String,
          packageName: Schema.String,
          packageUsername: Schema.String,
          playStoreUrl: Schema.NullOr(Schema.String),
          privacy: Schema.String,
          privacySetting: Schema.Literals(["HIDDEN", "PUBLIC", "UNLISTED"]),
          published: Schema.Boolean,
          pushSecurityEnabled: Schema.Boolean,
          releaseChannels: Schema.Array(Schema.String),
          requiresAccessTokenForPushSecurity: Schema.Boolean,
          resourceClassExperiment: Schema.NullOr(
            Schema.Literals(["C3D", "N2"]),
          ),
          scopeKey: Schema.String,
          sdkVersion: Schema.String,
          slug: Schema.String,
          suggestedDevDomainName: Schema.String,
          trendScore: Schema.Number,
          updated: Schema.String,
          username: Schema.String,
        }),
      ),
      preferences: Schema.Struct({
        selectedAccountName: Schema.NullOr(Schema.String),
      }),
      primaryAccountProfileImageUrl: Schema.NullOr(Schema.String),
      profilePhoto: Schema.String,
      twitterUsername: Schema.NullOr(Schema.String),
      username: Schema.String,
    }),
  ),
  pendingSentryInstallation: Schema.NullOr(
    Schema.Struct({
      createdAt: Schema.String,
      id: Schema.String,
      installationId: Schema.String,
      orgSlug: Schema.String,
    }),
  ),
  profileImageUrl: Schema.String,
  pushSecurityEnabled: Schema.Boolean,
  requireTwoFactor: Schema.Boolean,
  requiresAccessTokenForPushSecurity: Schema.Boolean,
  sentryInstallation: Schema.NullOr(
    Schema.Struct({
      createdAt: Schema.String,
      id: Schema.String,
      installationId: Schema.String,
      orgSlug: Schema.String,
    }),
  ),
  ssoAllowedAuthProviders: Schema.Array(
    Schema.Literals([
      "AMAZON_FEDERATE",
      "GENERIC",
      "GOOGLE_WS",
      "MS_ENTRA_ID",
      "OKTA",
      "ONE_LOGIN",
      "STUB_IDP",
    ]),
  ),
  ssoConfiguration: Schema.NullOr(
    Schema.Struct({
      authProtocol: Schema.Literals(["OIDC"]),
      authProviderIdentifier: Schema.Literals([
        "AMAZON_FEDERATE",
        "GENERIC",
        "GOOGLE_WS",
        "MS_ENTRA_ID",
        "OKTA",
        "ONE_LOGIN",
        "STUB_IDP",
      ]),
      clientIdentifier: Schema.String,
      clientSecret: Schema.String,
      createdAt: Schema.String,
      id: Schema.String,
      issuer: Schema.String,
      updatedAt: Schema.String,
    }),
  ),
  subscription: Schema.NullOr(
    Schema.Struct({
      addons: Schema.Array(
        Schema.Struct({
          id: Schema.String,
          name: Schema.String,
          nextInvoice: Schema.NullOr(Schema.String),
          planId: Schema.String,
          quantity: Schema.NullOr(Schema.Number),
          willCancel: Schema.NullOr(Schema.Boolean),
        }),
      ),
      cancelAt: Schema.NullOr(Schema.String),
      concurrencies: Schema.NullOr(
        Schema.Struct({
          android: Schema.Number,
          ios: Schema.Number,
          total: Schema.Number,
        }),
      ),
      coupon: Schema.NullOr(
        Schema.Struct({
          amountOff: Schema.NullOr(Schema.String),
          appliesTo: Schema.NullOr(Schema.String),
          id: Schema.String,
          name: Schema.String,
          percentOff: Schema.NullOr(Schema.Number),
          valid: Schema.Boolean,
        }),
      ),
      endedAt: Schema.NullOr(Schema.String),
      futureSubscription: Schema.NullOr(
        Schema.Struct({
          createdAt: Schema.String,
          id: Schema.String,
          planId: Schema.String,
          recurringCents: Schema.NullOr(Schema.Number),
          startDate: Schema.String,
        }),
      ),
      id: Schema.String,
      isDowngrading: Schema.NullOr(Schema.Boolean),
      meteredBillingStatus: Schema.Struct({
        EAS_BUILD: Schema.Boolean,
        EAS_UPDATE: Schema.Boolean,
      }),
      name: Schema.NullOr(Schema.String),
      nextInvoice: Schema.NullOr(Schema.String),
      nextInvoiceAmountDueCents: Schema.NullOr(Schema.Number),
      planId: Schema.NullOr(Schema.String),
      price: Schema.Number,
      recurringCents: Schema.NullOr(Schema.Number),
      status: Schema.NullOr(Schema.String),
      trialEnd: Schema.NullOr(Schema.String),
      upcomingInvoice: Schema.NullOr(
        Schema.Struct({
          amountDue: Schema.Number,
          amountPaid: Schema.Number,
          amountRemaining: Schema.Number,
          id: Schema.String,
          startingBalance: Schema.Number,
          subtotal: Schema.Number,
          total: Schema.Number,
          totalDiscountedAmount: Schema.Number,
        }),
      ),
      willCancel: Schema.NullOr(Schema.Boolean),
    }),
  ),
  subscriptionChangesPending: Schema.NullOr(Schema.Boolean),
  unlimitedBuilds: Schema.Boolean,
  updatedAt: Schema.String,
  userActorOwner: Schema.NullOr(
    Schema.Struct({
      accessTokens: Schema.Array(
        Schema.Struct({
          createdAt: Schema.String,
          id: Schema.String,
          lastUsedAt: Schema.NullOr(Schema.String),
          note: Schema.NullOr(Schema.String),
          revokedAt: Schema.NullOr(Schema.String),
          updatedAt: Schema.String,
          visibleTokenPrefix: Schema.String,
        }),
      ),
      appCount: Schema.Number,
      appetizeCode: Schema.NullOr(Schema.String),
      bestContactEmail: Schema.NullOr(Schema.String),
      created: Schema.String,
      discordUser: Schema.NullOr(
        Schema.Struct({
          discordIdentifier: Schema.String,
          id: Schema.String,
        }),
      ),
      displayName: Schema.String,
      experiments: Schema.Array(
        Schema.Struct({
          createdAt: Schema.String,
          enabled: Schema.Boolean,
          experiment: Schema.Literals(["ORBIT"]),
          id: Schema.String,
          updatedAt: Schema.String,
        }),
      ),
      firstName: Schema.NullOr(Schema.String),
      fullName: Schema.NullOr(Schema.String),
      githubUser: Schema.NullOr(
        Schema.Struct({
          githubUserIdentifier: Schema.String,
          id: Schema.String,
        }),
      ),
      githubUsername: Schema.NullOr(Schema.String),
      id: Schema.String,
      industry: Schema.NullOr(Schema.String),
      isExpoAdmin: Schema.Boolean,
      isStaffModeEnabled: Schema.Boolean,
      lastDeletionAttemptTime: Schema.NullOr(Schema.String),
      lastName: Schema.NullOr(Schema.String),
      location: Schema.NullOr(Schema.String),
      pinnedApps: Schema.Array(
        Schema.Struct({
          appStoreUrl: Schema.NullOr(Schema.String),
          assetLimitPerUpdateGroup: Schema.Number,
          buildProfiles: Schema.Array(Schema.String),
          buildsReleaseChannels: Schema.Array(Schema.String),
          description: Schema.String,
          environmentVariableEnvironments: Schema.Array(Schema.Unknown),
          fullName: Schema.String,
          githubUrl: Schema.NullOr(Schema.String),
          iconUrl: Schema.NullOr(Schema.String),
          id: Schema.String,
          internalDistributionBuildPrivacy: Schema.Literals([
            "PRIVATE",
            "PUBLIC",
          ]),
          isDeleting: Schema.Boolean,
          isDeprecated: Schema.Boolean,
          isLikedByMe: Schema.Boolean,
          lastDeletionAttemptTime: Schema.NullOr(Schema.String),
          lastPublishedTime: Schema.String,
          latestActivity: Schema.String,
          latestReleaseId: Schema.String,
          likeCount: Schema.Number,
          name: Schema.String,
          packageName: Schema.String,
          packageUsername: Schema.String,
          playStoreUrl: Schema.NullOr(Schema.String),
          privacy: Schema.String,
          privacySetting: Schema.Literals(["HIDDEN", "PUBLIC", "UNLISTED"]),
          published: Schema.Boolean,
          pushSecurityEnabled: Schema.Boolean,
          releaseChannels: Schema.Array(Schema.String),
          requiresAccessTokenForPushSecurity: Schema.Boolean,
          resourceClassExperiment: Schema.NullOr(
            Schema.Literals(["C3D", "N2"]),
          ),
          scopeKey: Schema.String,
          sdkVersion: Schema.String,
          slug: Schema.String,
          suggestedDevDomainName: Schema.String,
          trendScore: Schema.Number,
          updated: Schema.String,
          username: Schema.String,
        }),
      ),
      preferences: Schema.Struct({
        selectedAccountName: Schema.NullOr(Schema.String),
      }),
      primaryAccountProfileImageUrl: Schema.NullOr(Schema.String),
      profilePhoto: Schema.String,
      twitterUsername: Schema.NullOr(Schema.String),
      username: Schema.String,
    }),
  ),
  userInvitations: Schema.Array(
    Schema.Struct({
      accountName: Schema.String,
      accountProfileImageUrl: Schema.String,
      accountProfilePhoto: Schema.NullOr(Schema.String),
      accountRequiresTwoFactor: Schema.Boolean,
      created: Schema.String,
      email: Schema.String,
      expires: Schema.String,
      id: Schema.String,
      isForOrganization: Schema.Boolean,
      permissions: Schema.Array(
        Schema.Literals(["ADMIN", "OWN", "PUBLISH", "VIEW"]),
      ),
      role: Schema.Literals([
        "ADMIN",
        "CUSTOM",
        "DEVELOPER",
        "HAS_ADMIN",
        "NOT_ADMIN",
        "OWNER",
        "VIEW_ONLY",
      ]),
    }),
  ),
  userSpecifiedAccountUsage: Schema.NullOr(
    Schema.Literals(["COMPANY", "PERSONAL"]),
  ),
  users: Schema.Array(
    Schema.Struct({
      actor: Schema.Struct({
        created: Schema.String,
        displayName: Schema.String,
        firstName: Schema.NullOr(Schema.String),
        id: Schema.String,
        isExpoAdmin: Schema.Boolean,
        lastDeletionAttemptTime: Schema.NullOr(Schema.String),
      }),
      id: Schema.String,
      permissions: Schema.Array(
        Schema.Literals(["ADMIN", "OWN", "PUBLISH", "VIEW"]),
      ),
      role: Schema.Literals([
        "ADMIN",
        "CUSTOM",
        "DEVELOPER",
        "HAS_ADMIN",
        "NOT_ADMIN",
        "OWNER",
        "VIEW_ONLY",
      ]),
      user: Schema.NullOr(
        Schema.Struct({
          appCount: Schema.Number,
          appetizeCode: Schema.NullOr(Schema.String),
          bestContactEmail: Schema.NullOr(Schema.String),
          created: Schema.String,
          displayName: Schema.String,
          email: Schema.String,
          emailVerified: Schema.Boolean,
          firstName: Schema.NullOr(Schema.String),
          fullName: Schema.NullOr(Schema.String),
          githubUsername: Schema.NullOr(Schema.String),
          hasPassword: Schema.Boolean,
          hasPendingUserInvitations: Schema.Boolean,
          id: Schema.String,
          industry: Schema.NullOr(Schema.String),
          isExpoAdmin: Schema.Boolean,
          isLegacy: Schema.Boolean,
          isSecondFactorAuthenticationEnabled: Schema.Boolean,
          isStaffModeEnabled: Schema.Boolean,
          lastDeletionAttemptTime: Schema.NullOr(Schema.String),
          lastName: Schema.NullOr(Schema.String),
          location: Schema.NullOr(Schema.String),
          newEmailPendingVerification: Schema.NullOr(Schema.String),
          primaryAccountProfileImageUrl: Schema.NullOr(Schema.String),
          profilePhoto: Schema.String,
          twitterUsername: Schema.NullOr(Schema.String),
          username: Schema.String,
        }),
      ),
      userActor: Schema.NullOr(
        Schema.Struct({
          appCount: Schema.Number,
          appetizeCode: Schema.NullOr(Schema.String),
          bestContactEmail: Schema.NullOr(Schema.String),
          created: Schema.String,
          displayName: Schema.String,
          firstName: Schema.NullOr(Schema.String),
          fullName: Schema.NullOr(Schema.String),
          githubUsername: Schema.NullOr(Schema.String),
          id: Schema.String,
          industry: Schema.NullOr(Schema.String),
          isExpoAdmin: Schema.Boolean,
          isStaffModeEnabled: Schema.Boolean,
          lastDeletionAttemptTime: Schema.NullOr(Schema.String),
          lastName: Schema.NullOr(Schema.String),
          location: Schema.NullOr(Schema.String),
          primaryAccountProfileImageUrl: Schema.NullOr(Schema.String),
          profilePhoto: Schema.String,
          twitterUsername: Schema.NullOr(Schema.String),
          username: Schema.String,
        }),
      ),
    }),
  ),
  vexoAccountConnection: Schema.NullOr(
    Schema.Struct({
      accessToken: Schema.Struct({
        access_token: Schema.String,
        expires_at: Schema.NullOr(Schema.String),
        token_type: Schema.String,
      }),
      id: Schema.String,
    }),
  ),
  viewerUserPermission: Schema.Struct({
    actor: Schema.Struct({
      created: Schema.String,
      displayName: Schema.String,
      firstName: Schema.NullOr(Schema.String),
      id: Schema.String,
      isExpoAdmin: Schema.Boolean,
      lastDeletionAttemptTime: Schema.NullOr(Schema.String),
    }),
    id: Schema.String,
    permissions: Schema.Array(
      Schema.Literals(["ADMIN", "OWN", "PUBLISH", "VIEW"]),
    ),
    role: Schema.Literals([
      "ADMIN",
      "CUSTOM",
      "DEVELOPER",
      "HAS_ADMIN",
      "NOT_ADMIN",
      "OWNER",
      "VIEW_ONLY",
    ]),
    user: Schema.NullOr(
      Schema.Struct({
        appCount: Schema.Number,
        appetizeCode: Schema.NullOr(Schema.String),
        bestContactEmail: Schema.NullOr(Schema.String),
        created: Schema.String,
        displayName: Schema.String,
        email: Schema.String,
        emailVerified: Schema.Boolean,
        firstName: Schema.NullOr(Schema.String),
        fullName: Schema.NullOr(Schema.String),
        githubUsername: Schema.NullOr(Schema.String),
        hasPassword: Schema.Boolean,
        hasPendingUserInvitations: Schema.Boolean,
        id: Schema.String,
        industry: Schema.NullOr(Schema.String),
        isExpoAdmin: Schema.Boolean,
        isLegacy: Schema.Boolean,
        isSecondFactorAuthenticationEnabled: Schema.Boolean,
        isStaffModeEnabled: Schema.Boolean,
        lastDeletionAttemptTime: Schema.NullOr(Schema.String),
        lastName: Schema.NullOr(Schema.String),
        location: Schema.NullOr(Schema.String),
        newEmailPendingVerification: Schema.NullOr(Schema.String),
        primaryAccountProfileImageUrl: Schema.NullOr(Schema.String),
        profilePhoto: Schema.String,
        twitterUsername: Schema.NullOr(Schema.String),
        username: Schema.String,
      }),
    ),
    userActor: Schema.NullOr(
      Schema.Struct({
        appCount: Schema.Number,
        appetizeCode: Schema.NullOr(Schema.String),
        bestContactEmail: Schema.NullOr(Schema.String),
        created: Schema.String,
        displayName: Schema.String,
        firstName: Schema.NullOr(Schema.String),
        fullName: Schema.NullOr(Schema.String),
        githubUsername: Schema.NullOr(Schema.String),
        id: Schema.String,
        industry: Schema.NullOr(Schema.String),
        isExpoAdmin: Schema.Boolean,
        isStaffModeEnabled: Schema.Boolean,
        lastDeletionAttemptTime: Schema.NullOr(Schema.String),
        lastName: Schema.NullOr(Schema.String),
        location: Schema.NullOr(Schema.String),
        primaryAccountProfileImageUrl: Schema.NullOr(Schema.String),
        profilePhoto: Schema.String,
        twitterUsername: Schema.NullOr(Schema.String),
        username: Schema.String,
      }),
    ),
  }),
  willAutoRenewBuilds: Schema.NullOr(Schema.Boolean),
}).pipe(T.ResponsePath("account.setRequireTwoFactor"));
export type AccountSetRequireTwoFactorOutput =
  typeof AccountSetRequireTwoFactorOutput.Type;

export const accountSetRequireTwoFactor = API.make(() => ({
  inputSchema: AccountSetRequireTwoFactorInput,
  outputSchema: AccountSetRequireTwoFactorOutput,
}));
