import * as Schema from "effect/Schema";
import { API } from "../client.ts";
import * as T from "../traits.ts";

const __document =
  "query me {\n  me {\n    accessTokens {\n      createdAt\n      id\n      lastUsedAt\n      note\n      owner {\n        created\n        displayName\n        firstName\n        id\n        isExpoAdmin\n        lastDeletionAttemptTime\n      }\n      revokedAt\n      updatedAt\n      visibleTokenPrefix\n    }\n    accounts {\n      accessTokens {\n        createdAt\n        id\n        lastUsedAt\n        note\n        revokedAt\n        updatedAt\n        visibleTokenPrefix\n      }\n      appCount\n      appStoreConnectApiKeys {\n        createdAt\n        id\n        issuerIdentifier\n        keyIdentifier\n        keyP8\n        name\n        roles\n        updatedAt\n      }\n      appleDistributionCertificates {\n        certificateP12\n        certificatePassword\n        certificatePrivateSigningKey\n        createdAt\n        developerPortalIdentifier\n        id\n        serialNumber\n        updatedAt\n        validityNotAfter\n        validityNotBefore\n      }\n      applePushKeys {\n        createdAt\n        id\n        keyIdentifier\n        keyP8\n        updatedAt\n      }\n      availableBuilds\n      billing {\n        id\n      }\n      convexTeamConnections {\n        convexTeamIdentifier\n        createdAt\n        id\n        updatedAt\n      }\n      createdAt\n      displayName\n      environmentVariableEnvironments\n      githubAppInstallations {\n        id\n        installationIdentifier\n      }\n      googleServiceAccountKeys {\n        clientEmail\n        clientIdentifier\n        createdAt\n        id\n        keyJson\n        privateKeyIdentifier\n        projectIdentifier\n        updatedAt\n      }\n      hasBuilds\n      id\n      isCurrent\n      isDisabled\n      isFreeAppDevDomainTier\n      isSSOEnabled\n      lastDeletionAttemptTime\n      logRocketOrganization {\n        createdAt\n        id\n        orgName\n        orgSlug\n      }\n      memberStats {\n        allHave2FAEnabled\n        humanCount\n        ownerCount\n        robotCount\n        ssoUserCount\n        totalCount\n      }\n      name\n      offers {\n        features\n        id\n        price\n        quantity\n        stripeId\n        trialLength\n        type\n      }\n      onboardingStats {\n        firstBuildCompletedAt\n        firstProjectCreatedAt\n        firstSubmissionCompletedAt\n        firstUpdateCreatedAt\n        hasConfiguredUpdate\n        hasConfiguredWorkflow\n        hasTeamMembers\n      }\n      ownerUserActor {\n        appCount\n        appetizeCode\n        bestContactEmail\n        created\n        displayName\n        firstName\n        fullName\n        githubUsername\n        id\n        industry\n        isExpoAdmin\n        isStaffModeEnabled\n        lastDeletionAttemptTime\n        lastName\n        location\n        primaryAccountProfileImageUrl\n        profilePhoto\n        twitterUsername\n        username\n      }\n      pendingSentryInstallation {\n        createdAt\n        id\n        installationId\n        orgSlug\n      }\n      profileImageUrl\n      pushSecurityEnabled\n      requireTwoFactor\n      requiresAccessTokenForPushSecurity\n      sentryInstallation {\n        createdAt\n        id\n        installationId\n        orgSlug\n      }\n      ssoAllowedAuthProviders\n      ssoConfiguration {\n        authProtocol\n        authProviderIdentifier\n        clientIdentifier\n        clientSecret\n        createdAt\n        id\n        issuer\n        updatedAt\n      }\n      subscription {\n        cancelAt\n        endedAt\n        id\n        isDowngrading\n        name\n        nextInvoice\n        nextInvoiceAmountDueCents\n        planId\n        price\n        recurringCents\n        status\n        trialEnd\n        willCancel\n      }\n      subscriptionChangesPending\n      unlimitedBuilds\n      updatedAt\n      userActorOwner {\n        appCount\n        appetizeCode\n        bestContactEmail\n        created\n        displayName\n        firstName\n        fullName\n        githubUsername\n        id\n        industry\n        isExpoAdmin\n        isStaffModeEnabled\n        lastDeletionAttemptTime\n        lastName\n        location\n        primaryAccountProfileImageUrl\n        profilePhoto\n        twitterUsername\n        username\n      }\n      userInvitations {\n        accountName\n        accountProfileImageUrl\n        accountProfilePhoto\n        accountRequiresTwoFactor\n        created\n        email\n        expires\n        id\n        isForOrganization\n        permissions\n        role\n      }\n      userSpecifiedAccountUsage\n      users {\n        id\n        permissions\n        role\n      }\n      vexoAccountConnection {\n        id\n      }\n      viewerUserPermission {\n        id\n        permissions\n        role\n      }\n      willAutoRenewBuilds\n    }\n    appCount\n    appetizeCode\n    bestContactEmail\n    created\n    discordUser {\n      discordIdentifier\n      id\n      metadata {\n        discordAvatarUrl\n        discordDiscriminator\n        discordUsername\n      }\n      userActor {\n        appCount\n        appetizeCode\n        bestContactEmail\n        created\n        displayName\n        firstName\n        fullName\n        githubUsername\n        id\n        industry\n        isExpoAdmin\n        isStaffModeEnabled\n        lastDeletionAttemptTime\n        lastName\n        location\n        primaryAccountProfileImageUrl\n        profilePhoto\n        twitterUsername\n        username\n      }\n    }\n    displayName\n    email\n    emailVerified\n    experiments {\n      createdAt\n      enabled\n      experiment\n      id\n      updatedAt\n    }\n    firstName\n    fullName\n    githubUser {\n      githubUserIdentifier\n      id\n      metadata {\n        avatarUrl\n        login\n        name\n        url\n      }\n      userActor {\n        appCount\n        appetizeCode\n        bestContactEmail\n        created\n        displayName\n        firstName\n        fullName\n        githubUsername\n        id\n        industry\n        isExpoAdmin\n        isStaffModeEnabled\n        lastDeletionAttemptTime\n        lastName\n        location\n        primaryAccountProfileImageUrl\n        profilePhoto\n        twitterUsername\n        username\n      }\n    }\n    githubUsername\n    hasPassword\n    hasPendingUserInvitations\n    id\n    industry\n    isExpoAdmin\n    isLegacy\n    isSecondFactorAuthenticationEnabled\n    isStaffModeEnabled\n    lastDeletionAttemptTime\n    lastName\n    location\n    newEmailPendingVerification\n    oAuthIdentities {\n      email\n      id\n      login\n      provider\n    }\n    pendingUserInvitations {\n      accountName\n      accountProfileImageUrl\n      accountProfilePhoto\n      accountRequiresTwoFactor\n      created\n      email\n      expires\n      id\n      isForOrganization\n      permissions\n      role\n    }\n    pinnedApps {\n      accessTokens {\n        createdAt\n        id\n        lastUsedAt\n        note\n        revokedAt\n        updatedAt\n        visibleTokenPrefix\n      }\n      appStoreConnectApp {\n        ascAppIdentifier\n        createdAt\n        id\n        updatedAt\n        webhookEventTypes\n        webhookIdentifier\n      }\n      appStoreUrl\n      assetLimitPerUpdateGroup\n      buildProfiles\n      buildsReleaseChannels\n      convexProject {\n        convexProjectIdentifier\n        convexProjectName\n        convexProjectSlug\n        createdAt\n        id\n        updatedAt\n      }\n      description\n      devDomainName {\n        id\n        name\n      }\n      environmentVariableEnvironments\n      fullName\n      githubBuildTriggers {\n        autoSubmit\n        buildProfile\n        createdAt\n        environment\n        executionBehavior\n        id\n        isActive\n        lastRunAt\n        lastRunErrorCode\n        lastRunErrorMessage\n        lastRunStatus\n        platform\n        sourcePattern\n        submitProfile\n        targetPattern\n        type\n        updatedAt\n      }\n      githubJobRunTriggers {\n        createdAt\n        id\n        isActive\n        jobType\n        lastRunAt\n        lastRunErrorCode\n        lastRunErrorMessage\n        lastRunStatus\n        sourcePattern\n        targetPattern\n        triggerType\n      }\n      githubRepository {\n        createdAt\n        githubRepositoryIdentifier\n        githubRepositoryUrl\n        id\n        lastDeletionAttemptTime\n        nodeIdentifier\n      }\n      githubRepositorySettings {\n        baseDirectory\n        id\n      }\n      githubUrl\n      icon {\n        colorPalette\n        originalUrl\n        primaryColor\n        url\n      }\n      iconUrl\n      id\n      insights {\n        hasEventsFromExpoInsightsClientModule\n      }\n      internalDistributionBuildPrivacy\n      isDeleting\n      isDeprecated\n      isLikedByMe\n      lastDeletionAttemptTime\n      lastPublishedTime\n      latestActivity\n      latestReleaseId\n      likeCount\n      logRocketProject {\n        createdAt\n        id\n        logRocketOrgId\n        logRocketProjectSlug\n        updatedAt\n      }\n      name\n      observe {\n        totalEventCount\n      }\n      ownerAccount {\n        appCount\n        availableBuilds\n        createdAt\n        displayName\n        environmentVariableEnvironments\n        hasBuilds\n        id\n        isCurrent\n        isDisabled\n        isFreeAppDevDomainTier\n        isSSOEnabled\n        lastDeletionAttemptTime\n        name\n        profileImageUrl\n        pushSecurityEnabled\n        requireTwoFactor\n        requiresAccessTokenForPushSecurity\n        ssoAllowedAuthProviders\n        subscriptionChangesPending\n        unlimitedBuilds\n        updatedAt\n        userSpecifiedAccountUsage\n        willAutoRenewBuilds\n      }\n      packageName\n      packageUsername\n      playStoreUrl\n      privacy\n      privacySetting\n      published\n      pushNotifications {\n        id\n      }\n      pushSecurityEnabled\n      releaseChannels\n      requiresAccessTokenForPushSecurity\n      resourceClassExperiment\n      scopeKey\n      sdkVersion\n      sentryProject {\n        createdAt\n        id\n        sentryInstallationId\n        sentryProjectId\n        sentryProjectSlug\n        updatedAt\n      }\n      slug\n      suggestedDevDomainName\n      trendScore\n      updated\n      username\n      vexoApp {\n        domain\n        iconUrl\n        id\n        name\n        owner\n        slug\n        vexoIdentifier\n      }\n      workerCustomDomain {\n        createdAt\n        devDomainName\n        hostname\n        id\n        updatedAt\n      }\n    }\n    pinnedDashboardViews {\n      account {\n        appCount\n        availableBuilds\n        createdAt\n        displayName\n        environmentVariableEnvironments\n        hasBuilds\n        id\n        isCurrent\n        isDisabled\n        isFreeAppDevDomainTier\n        isSSOEnabled\n        lastDeletionAttemptTime\n        name\n        profileImageUrl\n        pushSecurityEnabled\n        requireTwoFactor\n        requiresAccessTokenForPushSecurity\n        ssoAllowedAuthProviders\n        subscriptionChangesPending\n        unlimitedBuilds\n        updatedAt\n        userSpecifiedAccountUsage\n        willAutoRenewBuilds\n      }\n      view\n    }\n    preferences {\n      onboarding {\n        appId\n        deviceType\n        environment\n        isCLIDone\n        lastUsed\n        platform\n      }\n      selectedAccountName\n    }\n    primaryAccount {\n      accessTokens {\n        createdAt\n        id\n        lastUsedAt\n        note\n        revokedAt\n        updatedAt\n        visibleTokenPrefix\n      }\n      appCount\n      appStoreConnectApiKeys {\n        createdAt\n        id\n        issuerIdentifier\n        keyIdentifier\n        keyP8\n        name\n        roles\n        updatedAt\n      }\n      appleDistributionCertificates {\n        certificateP12\n        certificatePassword\n        certificatePrivateSigningKey\n        createdAt\n        developerPortalIdentifier\n        id\n        serialNumber\n        updatedAt\n        validityNotAfter\n        validityNotBefore\n      }\n      applePushKeys {\n        createdAt\n        id\n        keyIdentifier\n        keyP8\n        updatedAt\n      }\n      availableBuilds\n      billing {\n        id\n      }\n      convexTeamConnections {\n        convexTeamIdentifier\n        createdAt\n        id\n        updatedAt\n      }\n      createdAt\n      displayName\n      environmentVariableEnvironments\n      githubAppInstallations {\n        id\n        installationIdentifier\n      }\n      googleServiceAccountKeys {\n        clientEmail\n        clientIdentifier\n        createdAt\n        id\n        keyJson\n        privateKeyIdentifier\n        projectIdentifier\n        updatedAt\n      }\n      hasBuilds\n      id\n      isCurrent\n      isDisabled\n      isFreeAppDevDomainTier\n      isSSOEnabled\n      lastDeletionAttemptTime\n      logRocketOrganization {\n        createdAt\n        id\n        orgName\n        orgSlug\n      }\n      memberStats {\n        allHave2FAEnabled\n        humanCount\n        ownerCount\n        robotCount\n        ssoUserCount\n        totalCount\n      }\n      name\n      offers {\n        features\n        id\n        price\n        quantity\n        stripeId\n        trialLength\n        type\n      }\n      onboardingStats {\n        firstBuildCompletedAt\n        firstProjectCreatedAt\n        firstSubmissionCompletedAt\n        firstUpdateCreatedAt\n        hasConfiguredUpdate\n        hasConfiguredWorkflow\n        hasTeamMembers\n      }\n      ownerUserActor {\n        appCount\n        appetizeCode\n        bestContactEmail\n        created\n        displayName\n        firstName\n        fullName\n        githubUsername\n        id\n        industry\n        isExpoAdmin\n        isStaffModeEnabled\n        lastDeletionAttemptTime\n        lastName\n        location\n        primaryAccountProfileImageUrl\n        profilePhoto\n        twitterUsername\n        username\n      }\n      pendingSentryInstallation {\n        createdAt\n        id\n        installationId\n        orgSlug\n      }\n      profileImageUrl\n      pushSecurityEnabled\n      requireTwoFactor\n      requiresAccessTokenForPushSecurity\n      sentryInstallation {\n        createdAt\n        id\n        installationId\n        orgSlug\n      }\n      ssoAllowedAuthProviders\n      ssoConfiguration {\n        authProtocol\n        authProviderIdentifier\n        clientIdentifier\n        clientSecret\n        createdAt\n        id\n        issuer\n        updatedAt\n      }\n      subscription {\n        cancelAt\n        endedAt\n        id\n        isDowngrading\n        name\n        nextInvoice\n        nextInvoiceAmountDueCents\n        planId\n        price\n        recurringCents\n        status\n        trialEnd\n        willCancel\n      }\n      subscriptionChangesPending\n      unlimitedBuilds\n      updatedAt\n      userActorOwner {\n        appCount\n        appetizeCode\n        bestContactEmail\n        created\n        displayName\n        firstName\n        fullName\n        githubUsername\n        id\n        industry\n        isExpoAdmin\n        isStaffModeEnabled\n        lastDeletionAttemptTime\n        lastName\n        location\n        primaryAccountProfileImageUrl\n        profilePhoto\n        twitterUsername\n        username\n      }\n      userInvitations {\n        accountName\n        accountProfileImageUrl\n        accountProfilePhoto\n        accountRequiresTwoFactor\n        created\n        email\n        expires\n        id\n        isForOrganization\n        permissions\n        role\n      }\n      userSpecifiedAccountUsage\n      users {\n        id\n        permissions\n        role\n      }\n      vexoAccountConnection {\n        id\n      }\n      viewerUserPermission {\n        id\n        permissions\n        role\n      }\n      willAutoRenewBuilds\n    }\n    primaryAccountProfileImageUrl\n    profilePhoto\n    secondFactorDevices {\n      createdAt\n      id\n      isCertified\n      isPrimary\n      method\n      name\n      smsPhoneNumber\n      updatedAt\n    }\n    twitterUsername\n    username\n  }\n}";

// Input Schema (GraphQL variables)
export const MeInput = Schema.Struct({}).pipe(
  T.Http({ method: "POST", path: "/graphql" }),
  T.GraphQLOp({
    query: __document,
    operationName: "me",
    type: "query",
  }),
);
export type MeInput = typeof MeInput.Type;

// Output Schema (GraphQL selection set)
export const MeOutput = Schema.NullOr(
  Schema.Struct({
    accessTokens: Schema.Array(
      Schema.Struct({
        createdAt: Schema.String,
        id: Schema.String,
        lastUsedAt: Schema.NullOr(Schema.String),
        note: Schema.NullOr(Schema.String),
        owner: Schema.Struct({
          created: Schema.String,
          displayName: Schema.String,
          firstName: Schema.NullOr(Schema.String),
          id: Schema.String,
          isExpoAdmin: Schema.Boolean,
          lastDeletionAttemptTime: Schema.NullOr(Schema.String),
        }),
        revokedAt: Schema.NullOr(Schema.String),
        updatedAt: Schema.String,
        visibleTokenPrefix: Schema.String,
      }),
    ),
    accounts: Schema.Array(
      Schema.Struct({
        accessTokens: Schema.Array(
          Schema.NullOr(
            Schema.Struct({
              createdAt: Schema.String,
              id: Schema.String,
              lastUsedAt: Schema.NullOr(Schema.String),
              note: Schema.NullOr(Schema.String),
              revokedAt: Schema.NullOr(Schema.String),
              updatedAt: Schema.String,
              visibleTokenPrefix: Schema.String,
            }),
          ),
        ),
        appCount: Schema.Number,
        appStoreConnectApiKeys: Schema.Array(
          Schema.Struct({
            createdAt: Schema.String,
            id: Schema.String,
            issuerIdentifier: Schema.String,
            keyIdentifier: Schema.String,
            keyP8: Schema.String,
            name: Schema.NullOr(Schema.String),
            roles: Schema.NullOr(
              Schema.Array(
                Schema.Literals([
                  "ACCESS_TO_REPORTS",
                  "ACCOUNT_HOLDER",
                  "ADMIN",
                  "APP_MANAGER",
                  "CLOUD_MANAGED_APP_DISTRIBUTION",
                  "CLOUD_MANAGED_DEVELOPER_ID",
                  "CREATE_APPS",
                  "CUSTOMER_SUPPORT",
                  "DEVELOPER",
                  "FINANCE",
                  "IMAGE_MANAGER",
                  "MARKETING",
                  "READ_ONLY",
                  "SALES",
                  "TECHNICAL",
                  "UNKNOWN",
                ]),
              ),
            ),
            updatedAt: Schema.String,
          }),
        ),
        appleDistributionCertificates: Schema.Array(
          Schema.Struct({
            certificateP12: Schema.NullOr(Schema.String),
            certificatePassword: Schema.NullOr(Schema.String),
            certificatePrivateSigningKey: Schema.NullOr(Schema.String),
            createdAt: Schema.String,
            developerPortalIdentifier: Schema.NullOr(Schema.String),
            id: Schema.String,
            serialNumber: Schema.String,
            updatedAt: Schema.String,
            validityNotAfter: Schema.String,
            validityNotBefore: Schema.String,
          }),
        ),
        applePushKeys: Schema.Array(
          Schema.Struct({
            createdAt: Schema.String,
            id: Schema.String,
            keyIdentifier: Schema.String,
            keyP8: Schema.String,
            updatedAt: Schema.String,
          }),
        ),
        availableBuilds: Schema.NullOr(Schema.Number),
        billing: Schema.NullOr(
          Schema.Struct({
            id: Schema.String,
          }),
        ),
        convexTeamConnections: Schema.Array(
          Schema.Struct({
            convexTeamIdentifier: Schema.String,
            createdAt: Schema.String,
            id: Schema.String,
            updatedAt: Schema.String,
          }),
        ),
        createdAt: Schema.String,
        displayName: Schema.NullOr(Schema.String),
        environmentVariableEnvironments: Schema.Array(Schema.Unknown),
        githubAppInstallations: Schema.Array(
          Schema.Struct({
            id: Schema.String,
            installationIdentifier: Schema.Number,
          }),
        ),
        googleServiceAccountKeys: Schema.Array(
          Schema.Struct({
            clientEmail: Schema.String,
            clientIdentifier: Schema.String,
            createdAt: Schema.String,
            id: Schema.String,
            keyJson: Schema.String,
            privateKeyIdentifier: Schema.String,
            projectIdentifier: Schema.String,
            updatedAt: Schema.String,
          }),
        ),
        hasBuilds: Schema.Boolean,
        id: Schema.String,
        isCurrent: Schema.Boolean,
        isDisabled: Schema.Boolean,
        isFreeAppDevDomainTier: Schema.Boolean,
        isSSOEnabled: Schema.Boolean,
        lastDeletionAttemptTime: Schema.NullOr(Schema.String),
        logRocketOrganization: Schema.NullOr(
          Schema.Struct({
            createdAt: Schema.String,
            id: Schema.String,
            orgName: Schema.String,
            orgSlug: Schema.String,
          }),
        ),
        memberStats: Schema.Struct({
          allHave2FAEnabled: Schema.Boolean,
          humanCount: Schema.Number,
          ownerCount: Schema.Number,
          robotCount: Schema.Number,
          ssoUserCount: Schema.Number,
          totalCount: Schema.Number,
        }),
        name: Schema.String,
        offers: Schema.NullOr(
          Schema.Array(
            Schema.Struct({
              features: Schema.NullOr(
                Schema.Array(
                  Schema.NullOr(
                    Schema.Literals([
                      "BUILDS",
                      "OPEN_SOURCE",
                      "SUPPORT",
                      "TEAMS",
                    ]),
                  ),
                ),
              ),
              id: Schema.String,
              price: Schema.Number,
              quantity: Schema.NullOr(Schema.Number),
              stripeId: Schema.String,
              trialLength: Schema.NullOr(Schema.Number),
              type: Schema.Literals(["ADDON", "PREPAID", "SUBSCRIPTION"]),
            }),
          ),
        ),
        onboardingStats: Schema.Struct({
          firstBuildCompletedAt: Schema.NullOr(Schema.String),
          firstProjectCreatedAt: Schema.NullOr(Schema.String),
          firstSubmissionCompletedAt: Schema.NullOr(Schema.String),
          firstUpdateCreatedAt: Schema.NullOr(Schema.String),
          hasConfiguredUpdate: Schema.Boolean,
          hasConfiguredWorkflow: Schema.Boolean,
          hasTeamMembers: Schema.Boolean,
        }),
        ownerUserActor: Schema.NullOr(
          Schema.Struct({
            appCount: Schema.Number,
            appetizeCode: Schema.NullOr(Schema.String),
            bestContactEmail: Schema.NullOr(Schema.String),
            created: Schema.String,
            displayName: Schema.String,
            firstName: Schema.NullOr(Schema.String),
            fullName: Schema.NullOr(Schema.String),
            githubUsername: Schema.NullOr(Schema.String),
            id: Schema.String,
            industry: Schema.NullOr(Schema.String),
            isExpoAdmin: Schema.Boolean,
            isStaffModeEnabled: Schema.Boolean,
            lastDeletionAttemptTime: Schema.NullOr(Schema.String),
            lastName: Schema.NullOr(Schema.String),
            location: Schema.NullOr(Schema.String),
            primaryAccountProfileImageUrl: Schema.NullOr(Schema.String),
            profilePhoto: Schema.String,
            twitterUsername: Schema.NullOr(Schema.String),
            username: Schema.String,
          }),
        ),
        pendingSentryInstallation: Schema.NullOr(
          Schema.Struct({
            createdAt: Schema.String,
            id: Schema.String,
            installationId: Schema.String,
            orgSlug: Schema.String,
          }),
        ),
        profileImageUrl: Schema.String,
        pushSecurityEnabled: Schema.Boolean,
        requireTwoFactor: Schema.Boolean,
        requiresAccessTokenForPushSecurity: Schema.Boolean,
        sentryInstallation: Schema.NullOr(
          Schema.Struct({
            createdAt: Schema.String,
            id: Schema.String,
            installationId: Schema.String,
            orgSlug: Schema.String,
          }),
        ),
        ssoAllowedAuthProviders: Schema.Array(
          Schema.Literals([
            "AMAZON_FEDERATE",
            "GENERIC",
            "GOOGLE_WS",
            "MS_ENTRA_ID",
            "OKTA",
            "ONE_LOGIN",
            "STUB_IDP",
          ]),
        ),
        ssoConfiguration: Schema.NullOr(
          Schema.Struct({
            authProtocol: Schema.Literals(["OIDC"]),
            authProviderIdentifier: Schema.Literals([
              "AMAZON_FEDERATE",
              "GENERIC",
              "GOOGLE_WS",
              "MS_ENTRA_ID",
              "OKTA",
              "ONE_LOGIN",
              "STUB_IDP",
            ]),
            clientIdentifier: Schema.String,
            clientSecret: Schema.String,
            createdAt: Schema.String,
            id: Schema.String,
            issuer: Schema.String,
            updatedAt: Schema.String,
          }),
        ),
        subscription: Schema.NullOr(
          Schema.Struct({
            cancelAt: Schema.NullOr(Schema.String),
            endedAt: Schema.NullOr(Schema.String),
            id: Schema.String,
            isDowngrading: Schema.NullOr(Schema.Boolean),
            name: Schema.NullOr(Schema.String),
            nextInvoice: Schema.NullOr(Schema.String),
            nextInvoiceAmountDueCents: Schema.NullOr(Schema.Number),
            planId: Schema.NullOr(Schema.String),
            price: Schema.Number,
            recurringCents: Schema.NullOr(Schema.Number),
            status: Schema.NullOr(Schema.String),
            trialEnd: Schema.NullOr(Schema.String),
            willCancel: Schema.NullOr(Schema.Boolean),
          }),
        ),
        subscriptionChangesPending: Schema.NullOr(Schema.Boolean),
        unlimitedBuilds: Schema.Boolean,
        updatedAt: Schema.String,
        userActorOwner: Schema.NullOr(
          Schema.Struct({
            appCount: Schema.Number,
            appetizeCode: Schema.NullOr(Schema.String),
            bestContactEmail: Schema.NullOr(Schema.String),
            created: Schema.String,
            displayName: Schema.String,
            firstName: Schema.NullOr(Schema.String),
            fullName: Schema.NullOr(Schema.String),
            githubUsername: Schema.NullOr(Schema.String),
            id: Schema.String,
            industry: Schema.NullOr(Schema.String),
            isExpoAdmin: Schema.Boolean,
            isStaffModeEnabled: Schema.Boolean,
            lastDeletionAttemptTime: Schema.NullOr(Schema.String),
            lastName: Schema.NullOr(Schema.String),
            location: Schema.NullOr(Schema.String),
            primaryAccountProfileImageUrl: Schema.NullOr(Schema.String),
            profilePhoto: Schema.String,
            twitterUsername: Schema.NullOr(Schema.String),
            username: Schema.String,
          }),
        ),
        userInvitations: Schema.Array(
          Schema.Struct({
            accountName: Schema.String,
            accountProfileImageUrl: Schema.String,
            accountProfilePhoto: Schema.NullOr(Schema.String),
            accountRequiresTwoFactor: Schema.Boolean,
            created: Schema.String,
            email: Schema.String,
            expires: Schema.String,
            id: Schema.String,
            isForOrganization: Schema.Boolean,
            permissions: Schema.Array(
              Schema.Literals(["ADMIN", "OWN", "PUBLISH", "VIEW"]),
            ),
            role: Schema.Literals([
              "ADMIN",
              "CUSTOM",
              "DEVELOPER",
              "HAS_ADMIN",
              "NOT_ADMIN",
              "OWNER",
              "VIEW_ONLY",
            ]),
          }),
        ),
        userSpecifiedAccountUsage: Schema.NullOr(
          Schema.Literals(["COMPANY", "PERSONAL"]),
        ),
        users: Schema.Array(
          Schema.Struct({
            id: Schema.String,
            permissions: Schema.Array(
              Schema.Literals(["ADMIN", "OWN", "PUBLISH", "VIEW"]),
            ),
            role: Schema.Literals([
              "ADMIN",
              "CUSTOM",
              "DEVELOPER",
              "HAS_ADMIN",
              "NOT_ADMIN",
              "OWNER",
              "VIEW_ONLY",
            ]),
          }),
        ),
        vexoAccountConnection: Schema.NullOr(
          Schema.Struct({
            id: Schema.String,
          }),
        ),
        viewerUserPermission: Schema.Struct({
          id: Schema.String,
          permissions: Schema.Array(
            Schema.Literals(["ADMIN", "OWN", "PUBLISH", "VIEW"]),
          ),
          role: Schema.Literals([
            "ADMIN",
            "CUSTOM",
            "DEVELOPER",
            "HAS_ADMIN",
            "NOT_ADMIN",
            "OWNER",
            "VIEW_ONLY",
          ]),
        }),
        willAutoRenewBuilds: Schema.NullOr(Schema.Boolean),
      }),
    ),
    appCount: Schema.Number,
    appetizeCode: Schema.NullOr(Schema.String),
    bestContactEmail: Schema.NullOr(Schema.String),
    created: Schema.String,
    discordUser: Schema.NullOr(
      Schema.Struct({
        discordIdentifier: Schema.String,
        id: Schema.String,
        metadata: Schema.NullOr(
          Schema.Struct({
            discordAvatarUrl: Schema.String,
            discordDiscriminator: Schema.String,
            discordUsername: Schema.String,
          }),
        ),
        userActor: Schema.Struct({
          appCount: Schema.Number,
          appetizeCode: Schema.NullOr(Schema.String),
          bestContactEmail: Schema.NullOr(Schema.String),
          created: Schema.String,
          displayName: Schema.String,
          firstName: Schema.NullOr(Schema.String),
          fullName: Schema.NullOr(Schema.String),
          githubUsername: Schema.NullOr(Schema.String),
          id: Schema.String,
          industry: Schema.NullOr(Schema.String),
          isExpoAdmin: Schema.Boolean,
          isStaffModeEnabled: Schema.Boolean,
          lastDeletionAttemptTime: Schema.NullOr(Schema.String),
          lastName: Schema.NullOr(Schema.String),
          location: Schema.NullOr(Schema.String),
          primaryAccountProfileImageUrl: Schema.NullOr(Schema.String),
          profilePhoto: Schema.String,
          twitterUsername: Schema.NullOr(Schema.String),
          username: Schema.String,
        }),
      }),
    ),
    displayName: Schema.String,
    email: Schema.String,
    emailVerified: Schema.Boolean,
    experiments: Schema.Array(
      Schema.Struct({
        createdAt: Schema.String,
        enabled: Schema.Boolean,
        experiment: Schema.Literals(["ORBIT"]),
        id: Schema.String,
        updatedAt: Schema.String,
      }),
    ),
    firstName: Schema.NullOr(Schema.String),
    fullName: Schema.NullOr(Schema.String),
    githubUser: Schema.NullOr(
      Schema.Struct({
        githubUserIdentifier: Schema.String,
        id: Schema.String,
        metadata: Schema.NullOr(
          Schema.Struct({
            avatarUrl: Schema.String,
            login: Schema.String,
            name: Schema.NullOr(Schema.String),
            url: Schema.String,
          }),
        ),
        userActor: Schema.Struct({
          appCount: Schema.Number,
          appetizeCode: Schema.NullOr(Schema.String),
          bestContactEmail: Schema.NullOr(Schema.String),
          created: Schema.String,
          displayName: Schema.String,
          firstName: Schema.NullOr(Schema.String),
          fullName: Schema.NullOr(Schema.String),
          githubUsername: Schema.NullOr(Schema.String),
          id: Schema.String,
          industry: Schema.NullOr(Schema.String),
          isExpoAdmin: Schema.Boolean,
          isStaffModeEnabled: Schema.Boolean,
          lastDeletionAttemptTime: Schema.NullOr(Schema.String),
          lastName: Schema.NullOr(Schema.String),
          location: Schema.NullOr(Schema.String),
          primaryAccountProfileImageUrl: Schema.NullOr(Schema.String),
          profilePhoto: Schema.String,
          twitterUsername: Schema.NullOr(Schema.String),
          username: Schema.String,
        }),
      }),
    ),
    githubUsername: Schema.NullOr(Schema.String),
    hasPassword: Schema.Boolean,
    hasPendingUserInvitations: Schema.Boolean,
    id: Schema.String,
    industry: Schema.NullOr(Schema.String),
    isExpoAdmin: Schema.Boolean,
    isLegacy: Schema.Boolean,
    isSecondFactorAuthenticationEnabled: Schema.Boolean,
    isStaffModeEnabled: Schema.Boolean,
    lastDeletionAttemptTime: Schema.NullOr(Schema.String),
    lastName: Schema.NullOr(Schema.String),
    location: Schema.NullOr(Schema.String),
    newEmailPendingVerification: Schema.NullOr(Schema.String),
    oAuthIdentities: Schema.Array(
      Schema.Struct({
        email: Schema.String,
        id: Schema.String,
        login: Schema.NullOr(Schema.String),
        provider: Schema.Literals(["apple", "github", "google"]),
      }),
    ),
    pendingUserInvitations: Schema.Array(
      Schema.Struct({
        accountName: Schema.String,
        accountProfileImageUrl: Schema.String,
        accountProfilePhoto: Schema.NullOr(Schema.String),
        accountRequiresTwoFactor: Schema.Boolean,
        created: Schema.String,
        email: Schema.String,
        expires: Schema.String,
        id: Schema.String,
        isForOrganization: Schema.Boolean,
        permissions: Schema.Array(
          Schema.Literals(["ADMIN", "OWN", "PUBLISH", "VIEW"]),
        ),
        role: Schema.Literals([
          "ADMIN",
          "CUSTOM",
          "DEVELOPER",
          "HAS_ADMIN",
          "NOT_ADMIN",
          "OWNER",
          "VIEW_ONLY",
        ]),
      }),
    ),
    pinnedApps: Schema.Array(
      Schema.Struct({
        accessTokens: Schema.Array(
          Schema.NullOr(
            Schema.Struct({
              createdAt: Schema.String,
              id: Schema.String,
              lastUsedAt: Schema.NullOr(Schema.String),
              note: Schema.NullOr(Schema.String),
              revokedAt: Schema.NullOr(Schema.String),
              updatedAt: Schema.String,
              visibleTokenPrefix: Schema.String,
            }),
          ),
        ),
        appStoreConnectApp: Schema.NullOr(
          Schema.Struct({
            ascAppIdentifier: Schema.String,
            createdAt: Schema.String,
            id: Schema.String,
            updatedAt: Schema.String,
            webhookEventTypes: Schema.Array(Schema.String),
            webhookIdentifier: Schema.String,
          }),
        ),
        appStoreUrl: Schema.NullOr(Schema.String),
        assetLimitPerUpdateGroup: Schema.Number,
        buildProfiles: Schema.Array(Schema.String),
        buildsReleaseChannels: Schema.Array(Schema.String),
        convexProject: Schema.NullOr(
          Schema.Struct({
            convexProjectIdentifier: Schema.String,
            convexProjectName: Schema.String,
            convexProjectSlug: Schema.String,
            createdAt: Schema.String,
            id: Schema.String,
            updatedAt: Schema.String,
          }),
        ),
        description: Schema.String,
        devDomainName: Schema.NullOr(
          Schema.Struct({
            id: Schema.String,
            name: Schema.Unknown,
          }),
        ),
        environmentVariableEnvironments: Schema.Array(Schema.Unknown),
        fullName: Schema.String,
        githubBuildTriggers: Schema.Array(
          Schema.Struct({
            autoSubmit: Schema.Boolean,
            buildProfile: Schema.String,
            createdAt: Schema.String,
            environment: Schema.NullOr(Schema.Unknown),
            executionBehavior: Schema.Literals([
              "ALWAYS",
              "BASE_DIRECTORY_CHANGED",
            ]),
            id: Schema.String,
            isActive: Schema.Boolean,
            lastRunAt: Schema.NullOr(Schema.String),
            lastRunErrorCode: Schema.NullOr(Schema.String),
            lastRunErrorMessage: Schema.NullOr(Schema.String),
            lastRunStatus: Schema.NullOr(
              Schema.Literals(["ERRORED", "SUCCESS"]),
            ),
            platform: Schema.Literals(["ANDROID", "IOS"]),
            sourcePattern: Schema.String,
            submitProfile: Schema.NullOr(Schema.String),
            targetPattern: Schema.NullOr(Schema.String),
            type: Schema.Literals([
              "PULL_REQUEST_UPDATED",
              "PUSH_TO_BRANCH",
              "TAG_UPDATED",
            ]),
            updatedAt: Schema.String,
          }),
        ),
        githubJobRunTriggers: Schema.Array(
          Schema.Struct({
            createdAt: Schema.String,
            id: Schema.String,
            isActive: Schema.Boolean,
            jobType: Schema.NullOr(Schema.Literals(["PUBLISH_UPDATE"])),
            lastRunAt: Schema.NullOr(Schema.String),
            lastRunErrorCode: Schema.NullOr(Schema.String),
            lastRunErrorMessage: Schema.NullOr(Schema.String),
            lastRunStatus: Schema.NullOr(
              Schema.Literals(["ERRORED", "SUCCESS"]),
            ),
            sourcePattern: Schema.String,
            targetPattern: Schema.NullOr(Schema.String),
            triggerType: Schema.Literals([
              "PULL_REQUEST_UPDATED",
              "PUSH_TO_BRANCH",
            ]),
          }),
        ),
        githubRepository: Schema.NullOr(
          Schema.Struct({
            createdAt: Schema.String,
            githubRepositoryIdentifier: Schema.Number,
            githubRepositoryUrl: Schema.NullOr(Schema.String),
            id: Schema.String,
            lastDeletionAttemptTime: Schema.NullOr(Schema.String),
            nodeIdentifier: Schema.String,
          }),
        ),
        githubRepositorySettings: Schema.NullOr(
          Schema.Struct({
            baseDirectory: Schema.String,
            id: Schema.String,
          }),
        ),
        githubUrl: Schema.NullOr(Schema.String),
        icon: Schema.NullOr(
          Schema.Struct({
            colorPalette: Schema.NullOr(Schema.Unknown),
            originalUrl: Schema.String,
            primaryColor: Schema.NullOr(Schema.String),
            url: Schema.String,
          }),
        ),
        iconUrl: Schema.NullOr(Schema.String),
        id: Schema.String,
        insights: Schema.Struct({
          hasEventsFromExpoInsightsClientModule: Schema.Boolean,
        }),
        internalDistributionBuildPrivacy: Schema.Literals([
          "PRIVATE",
          "PUBLIC",
        ]),
        isDeleting: Schema.Boolean,
        isDeprecated: Schema.Boolean,
        isLikedByMe: Schema.Boolean,
        lastDeletionAttemptTime: Schema.NullOr(Schema.String),
        lastPublishedTime: Schema.String,
        latestActivity: Schema.String,
        latestReleaseId: Schema.String,
        likeCount: Schema.Number,
        logRocketProject: Schema.NullOr(
          Schema.Struct({
            createdAt: Schema.String,
            id: Schema.String,
            logRocketOrgId: Schema.String,
            logRocketProjectSlug: Schema.String,
            updatedAt: Schema.String,
          }),
        ),
        name: Schema.String,
        observe: Schema.Struct({
          totalEventCount: Schema.Number,
        }),
        ownerAccount: Schema.Struct({
          appCount: Schema.Number,
          availableBuilds: Schema.NullOr(Schema.Number),
          createdAt: Schema.String,
          displayName: Schema.NullOr(Schema.String),
          environmentVariableEnvironments: Schema.Array(Schema.Unknown),
          hasBuilds: Schema.Boolean,
          id: Schema.String,
          isCurrent: Schema.Boolean,
          isDisabled: Schema.Boolean,
          isFreeAppDevDomainTier: Schema.Boolean,
          isSSOEnabled: Schema.Boolean,
          lastDeletionAttemptTime: Schema.NullOr(Schema.String),
          name: Schema.String,
          profileImageUrl: Schema.String,
          pushSecurityEnabled: Schema.Boolean,
          requireTwoFactor: Schema.Boolean,
          requiresAccessTokenForPushSecurity: Schema.Boolean,
          ssoAllowedAuthProviders: Schema.Array(
            Schema.Literals([
              "AMAZON_FEDERATE",
              "GENERIC",
              "GOOGLE_WS",
              "MS_ENTRA_ID",
              "OKTA",
              "ONE_LOGIN",
              "STUB_IDP",
            ]),
          ),
          subscriptionChangesPending: Schema.NullOr(Schema.Boolean),
          unlimitedBuilds: Schema.Boolean,
          updatedAt: Schema.String,
          userSpecifiedAccountUsage: Schema.NullOr(
            Schema.Literals(["COMPANY", "PERSONAL"]),
          ),
          willAutoRenewBuilds: Schema.NullOr(Schema.Boolean),
        }),
        packageName: Schema.String,
        packageUsername: Schema.String,
        playStoreUrl: Schema.NullOr(Schema.String),
        privacy: Schema.String,
        privacySetting: Schema.Literals(["HIDDEN", "PUBLIC", "UNLISTED"]),
        published: Schema.Boolean,
        pushNotifications: Schema.Struct({
          id: Schema.String,
        }),
        pushSecurityEnabled: Schema.Boolean,
        releaseChannels: Schema.Array(Schema.String),
        requiresAccessTokenForPushSecurity: Schema.Boolean,
        resourceClassExperiment: Schema.NullOr(Schema.Literals(["C3D", "N2"])),
        scopeKey: Schema.String,
        sdkVersion: Schema.String,
        sentryProject: Schema.NullOr(
          Schema.Struct({
            createdAt: Schema.String,
            id: Schema.String,
            sentryInstallationId: Schema.String,
            sentryProjectId: Schema.String,
            sentryProjectSlug: Schema.String,
            updatedAt: Schema.String,
          }),
        ),
        slug: Schema.String,
        suggestedDevDomainName: Schema.String,
        trendScore: Schema.Number,
        updated: Schema.String,
        username: Schema.String,
        vexoApp: Schema.NullOr(
          Schema.Struct({
            domain: Schema.NullOr(Schema.String),
            iconUrl: Schema.NullOr(Schema.String),
            id: Schema.String,
            name: Schema.String,
            owner: Schema.String,
            slug: Schema.String,
            vexoIdentifier: Schema.String,
          }),
        ),
        workerCustomDomain: Schema.NullOr(
          Schema.Struct({
            createdAt: Schema.String,
            devDomainName: Schema.Unknown,
            hostname: Schema.String,
            id: Schema.String,
            updatedAt: Schema.String,
          }),
        ),
      }),
    ),
    pinnedDashboardViews: Schema.Array(
      Schema.Struct({
        account: Schema.Struct({
          appCount: Schema.Number,
          availableBuilds: Schema.NullOr(Schema.Number),
          createdAt: Schema.String,
          displayName: Schema.NullOr(Schema.String),
          environmentVariableEnvironments: Schema.Array(Schema.Unknown),
          hasBuilds: Schema.Boolean,
          id: Schema.String,
          isCurrent: Schema.Boolean,
          isDisabled: Schema.Boolean,
          isFreeAppDevDomainTier: Schema.Boolean,
          isSSOEnabled: Schema.Boolean,
          lastDeletionAttemptTime: Schema.NullOr(Schema.String),
          name: Schema.String,
          profileImageUrl: Schema.String,
          pushSecurityEnabled: Schema.Boolean,
          requireTwoFactor: Schema.Boolean,
          requiresAccessTokenForPushSecurity: Schema.Boolean,
          ssoAllowedAuthProviders: Schema.Array(
            Schema.Literals([
              "AMAZON_FEDERATE",
              "GENERIC",
              "GOOGLE_WS",
              "MS_ENTRA_ID",
              "OKTA",
              "ONE_LOGIN",
              "STUB_IDP",
            ]),
          ),
          subscriptionChangesPending: Schema.NullOr(Schema.Boolean),
          unlimitedBuilds: Schema.Boolean,
          updatedAt: Schema.String,
          userSpecifiedAccountUsage: Schema.NullOr(
            Schema.Literals(["COMPANY", "PERSONAL"]),
          ),
          willAutoRenewBuilds: Schema.NullOr(Schema.Boolean),
        }),
        view: Schema.Literals(["ACTIVITY", "OVERVIEW"]),
      }),
    ),
    preferences: Schema.Struct({
      onboarding: Schema.NullOr(
        Schema.Struct({
          appId: Schema.String,
          deviceType: Schema.NullOr(Schema.Literals(["DEVICE", "SIMULATOR"])),
          environment: Schema.NullOr(Schema.Literals(["DEV_BUILD", "EXPO_GO"])),
          isCLIDone: Schema.NullOr(Schema.Boolean),
          lastUsed: Schema.String,
          platform: Schema.NullOr(Schema.Literals(["ANDROID", "IOS"])),
        }),
      ),
      selectedAccountName: Schema.NullOr(Schema.String),
    }),
    primaryAccount: Schema.Struct({
      accessTokens: Schema.Array(
        Schema.NullOr(
          Schema.Struct({
            createdAt: Schema.String,
            id: Schema.String,
            lastUsedAt: Schema.NullOr(Schema.String),
            note: Schema.NullOr(Schema.String),
            revokedAt: Schema.NullOr(Schema.String),
            updatedAt: Schema.String,
            visibleTokenPrefix: Schema.String,
          }),
        ),
      ),
      appCount: Schema.Number,
      appStoreConnectApiKeys: Schema.Array(
        Schema.Struct({
          createdAt: Schema.String,
          id: Schema.String,
          issuerIdentifier: Schema.String,
          keyIdentifier: Schema.String,
          keyP8: Schema.String,
          name: Schema.NullOr(Schema.String),
          roles: Schema.NullOr(
            Schema.Array(
              Schema.Literals([
                "ACCESS_TO_REPORTS",
                "ACCOUNT_HOLDER",
                "ADMIN",
                "APP_MANAGER",
                "CLOUD_MANAGED_APP_DISTRIBUTION",
                "CLOUD_MANAGED_DEVELOPER_ID",
                "CREATE_APPS",
                "CUSTOMER_SUPPORT",
                "DEVELOPER",
                "FINANCE",
                "IMAGE_MANAGER",
                "MARKETING",
                "READ_ONLY",
                "SALES",
                "TECHNICAL",
                "UNKNOWN",
              ]),
            ),
          ),
          updatedAt: Schema.String,
        }),
      ),
      appleDistributionCertificates: Schema.Array(
        Schema.Struct({
          certificateP12: Schema.NullOr(Schema.String),
          certificatePassword: Schema.NullOr(Schema.String),
          certificatePrivateSigningKey: Schema.NullOr(Schema.String),
          createdAt: Schema.String,
          developerPortalIdentifier: Schema.NullOr(Schema.String),
          id: Schema.String,
          serialNumber: Schema.String,
          updatedAt: Schema.String,
          validityNotAfter: Schema.String,
          validityNotBefore: Schema.String,
        }),
      ),
      applePushKeys: Schema.Array(
        Schema.Struct({
          createdAt: Schema.String,
          id: Schema.String,
          keyIdentifier: Schema.String,
          keyP8: Schema.String,
          updatedAt: Schema.String,
        }),
      ),
      availableBuilds: Schema.NullOr(Schema.Number),
      billing: Schema.NullOr(
        Schema.Struct({
          id: Schema.String,
        }),
      ),
      convexTeamConnections: Schema.Array(
        Schema.Struct({
          convexTeamIdentifier: Schema.String,
          createdAt: Schema.String,
          id: Schema.String,
          updatedAt: Schema.String,
        }),
      ),
      createdAt: Schema.String,
      displayName: Schema.NullOr(Schema.String),
      environmentVariableEnvironments: Schema.Array(Schema.Unknown),
      githubAppInstallations: Schema.Array(
        Schema.Struct({
          id: Schema.String,
          installationIdentifier: Schema.Number,
        }),
      ),
      googleServiceAccountKeys: Schema.Array(
        Schema.Struct({
          clientEmail: Schema.String,
          clientIdentifier: Schema.String,
          createdAt: Schema.String,
          id: Schema.String,
          keyJson: Schema.String,
          privateKeyIdentifier: Schema.String,
          projectIdentifier: Schema.String,
          updatedAt: Schema.String,
        }),
      ),
      hasBuilds: Schema.Boolean,
      id: Schema.String,
      isCurrent: Schema.Boolean,
      isDisabled: Schema.Boolean,
      isFreeAppDevDomainTier: Schema.Boolean,
      isSSOEnabled: Schema.Boolean,
      lastDeletionAttemptTime: Schema.NullOr(Schema.String),
      logRocketOrganization: Schema.NullOr(
        Schema.Struct({
          createdAt: Schema.String,
          id: Schema.String,
          orgName: Schema.String,
          orgSlug: Schema.String,
        }),
      ),
      memberStats: Schema.Struct({
        allHave2FAEnabled: Schema.Boolean,
        humanCount: Schema.Number,
        ownerCount: Schema.Number,
        robotCount: Schema.Number,
        ssoUserCount: Schema.Number,
        totalCount: Schema.Number,
      }),
      name: Schema.String,
      offers: Schema.NullOr(
        Schema.Array(
          Schema.Struct({
            features: Schema.NullOr(
              Schema.Array(
                Schema.NullOr(
                  Schema.Literals([
                    "BUILDS",
                    "OPEN_SOURCE",
                    "SUPPORT",
                    "TEAMS",
                  ]),
                ),
              ),
            ),
            id: Schema.String,
            price: Schema.Number,
            quantity: Schema.NullOr(Schema.Number),
            stripeId: Schema.String,
            trialLength: Schema.NullOr(Schema.Number),
            type: Schema.Literals(["ADDON", "PREPAID", "SUBSCRIPTION"]),
          }),
        ),
      ),
      onboardingStats: Schema.Struct({
        firstBuildCompletedAt: Schema.NullOr(Schema.String),
        firstProjectCreatedAt: Schema.NullOr(Schema.String),
        firstSubmissionCompletedAt: Schema.NullOr(Schema.String),
        firstUpdateCreatedAt: Schema.NullOr(Schema.String),
        hasConfiguredUpdate: Schema.Boolean,
        hasConfiguredWorkflow: Schema.Boolean,
        hasTeamMembers: Schema.Boolean,
      }),
      ownerUserActor: Schema.NullOr(
        Schema.Struct({
          appCount: Schema.Number,
          appetizeCode: Schema.NullOr(Schema.String),
          bestContactEmail: Schema.NullOr(Schema.String),
          created: Schema.String,
          displayName: Schema.String,
          firstName: Schema.NullOr(Schema.String),
          fullName: Schema.NullOr(Schema.String),
          githubUsername: Schema.NullOr(Schema.String),
          id: Schema.String,
          industry: Schema.NullOr(Schema.String),
          isExpoAdmin: Schema.Boolean,
          isStaffModeEnabled: Schema.Boolean,
          lastDeletionAttemptTime: Schema.NullOr(Schema.String),
          lastName: Schema.NullOr(Schema.String),
          location: Schema.NullOr(Schema.String),
          primaryAccountProfileImageUrl: Schema.NullOr(Schema.String),
          profilePhoto: Schema.String,
          twitterUsername: Schema.NullOr(Schema.String),
          username: Schema.String,
        }),
      ),
      pendingSentryInstallation: Schema.NullOr(
        Schema.Struct({
          createdAt: Schema.String,
          id: Schema.String,
          installationId: Schema.String,
          orgSlug: Schema.String,
        }),
      ),
      profileImageUrl: Schema.String,
      pushSecurityEnabled: Schema.Boolean,
      requireTwoFactor: Schema.Boolean,
      requiresAccessTokenForPushSecurity: Schema.Boolean,
      sentryInstallation: Schema.NullOr(
        Schema.Struct({
          createdAt: Schema.String,
          id: Schema.String,
          installationId: Schema.String,
          orgSlug: Schema.String,
        }),
      ),
      ssoAllowedAuthProviders: Schema.Array(
        Schema.Literals([
          "AMAZON_FEDERATE",
          "GENERIC",
          "GOOGLE_WS",
          "MS_ENTRA_ID",
          "OKTA",
          "ONE_LOGIN",
          "STUB_IDP",
        ]),
      ),
      ssoConfiguration: Schema.NullOr(
        Schema.Struct({
          authProtocol: Schema.Literals(["OIDC"]),
          authProviderIdentifier: Schema.Literals([
            "AMAZON_FEDERATE",
            "GENERIC",
            "GOOGLE_WS",
            "MS_ENTRA_ID",
            "OKTA",
            "ONE_LOGIN",
            "STUB_IDP",
          ]),
          clientIdentifier: Schema.String,
          clientSecret: Schema.String,
          createdAt: Schema.String,
          id: Schema.String,
          issuer: Schema.String,
          updatedAt: Schema.String,
        }),
      ),
      subscription: Schema.NullOr(
        Schema.Struct({
          cancelAt: Schema.NullOr(Schema.String),
          endedAt: Schema.NullOr(Schema.String),
          id: Schema.String,
          isDowngrading: Schema.NullOr(Schema.Boolean),
          name: Schema.NullOr(Schema.String),
          nextInvoice: Schema.NullOr(Schema.String),
          nextInvoiceAmountDueCents: Schema.NullOr(Schema.Number),
          planId: Schema.NullOr(Schema.String),
          price: Schema.Number,
          recurringCents: Schema.NullOr(Schema.Number),
          status: Schema.NullOr(Schema.String),
          trialEnd: Schema.NullOr(Schema.String),
          willCancel: Schema.NullOr(Schema.Boolean),
        }),
      ),
      subscriptionChangesPending: Schema.NullOr(Schema.Boolean),
      unlimitedBuilds: Schema.Boolean,
      updatedAt: Schema.String,
      userActorOwner: Schema.NullOr(
        Schema.Struct({
          appCount: Schema.Number,
          appetizeCode: Schema.NullOr(Schema.String),
          bestContactEmail: Schema.NullOr(Schema.String),
          created: Schema.String,
          displayName: Schema.String,
          firstName: Schema.NullOr(Schema.String),
          fullName: Schema.NullOr(Schema.String),
          githubUsername: Schema.NullOr(Schema.String),
          id: Schema.String,
          industry: Schema.NullOr(Schema.String),
          isExpoAdmin: Schema.Boolean,
          isStaffModeEnabled: Schema.Boolean,
          lastDeletionAttemptTime: Schema.NullOr(Schema.String),
          lastName: Schema.NullOr(Schema.String),
          location: Schema.NullOr(Schema.String),
          primaryAccountProfileImageUrl: Schema.NullOr(Schema.String),
          profilePhoto: Schema.String,
          twitterUsername: Schema.NullOr(Schema.String),
          username: Schema.String,
        }),
      ),
      userInvitations: Schema.Array(
        Schema.Struct({
          accountName: Schema.String,
          accountProfileImageUrl: Schema.String,
          accountProfilePhoto: Schema.NullOr(Schema.String),
          accountRequiresTwoFactor: Schema.Boolean,
          created: Schema.String,
          email: Schema.String,
          expires: Schema.String,
          id: Schema.String,
          isForOrganization: Schema.Boolean,
          permissions: Schema.Array(
            Schema.Literals(["ADMIN", "OWN", "PUBLISH", "VIEW"]),
          ),
          role: Schema.Literals([
            "ADMIN",
            "CUSTOM",
            "DEVELOPER",
            "HAS_ADMIN",
            "NOT_ADMIN",
            "OWNER",
            "VIEW_ONLY",
          ]),
        }),
      ),
      userSpecifiedAccountUsage: Schema.NullOr(
        Schema.Literals(["COMPANY", "PERSONAL"]),
      ),
      users: Schema.Array(
        Schema.Struct({
          id: Schema.String,
          permissions: Schema.Array(
            Schema.Literals(["ADMIN", "OWN", "PUBLISH", "VIEW"]),
          ),
          role: Schema.Literals([
            "ADMIN",
            "CUSTOM",
            "DEVELOPER",
            "HAS_ADMIN",
            "NOT_ADMIN",
            "OWNER",
            "VIEW_ONLY",
          ]),
        }),
      ),
      vexoAccountConnection: Schema.NullOr(
        Schema.Struct({
          id: Schema.String,
        }),
      ),
      viewerUserPermission: Schema.Struct({
        id: Schema.String,
        permissions: Schema.Array(
          Schema.Literals(["ADMIN", "OWN", "PUBLISH", "VIEW"]),
        ),
        role: Schema.Literals([
          "ADMIN",
          "CUSTOM",
          "DEVELOPER",
          "HAS_ADMIN",
          "NOT_ADMIN",
          "OWNER",
          "VIEW_ONLY",
        ]),
      }),
      willAutoRenewBuilds: Schema.NullOr(Schema.Boolean),
    }),
    primaryAccountProfileImageUrl: Schema.NullOr(Schema.String),
    profilePhoto: Schema.String,
    secondFactorDevices: Schema.Array(
      Schema.Struct({
        createdAt: Schema.String,
        id: Schema.String,
        isCertified: Schema.Boolean,
        isPrimary: Schema.Boolean,
        method: Schema.Literals(["AUTHENTICATOR", "SMS"]),
        name: Schema.String,
        smsPhoneNumber: Schema.NullOr(Schema.String),
        updatedAt: Schema.String,
      }),
    ),
    twitterUsername: Schema.NullOr(Schema.String),
    username: Schema.String,
  }),
).pipe(T.ResponsePath("me"));
export type MeOutput = typeof MeOutput.Type;

/**
 * If authenticated as a typical end user, this is the appropriate top-level
 * query object
 */
export const me = API.make(() => ({
  inputSchema: MeInput,
  outputSchema: MeOutput,
}));
