import * as Schema from "effect/Schema";
import { API } from "../client.ts";
import * as T from "../traits.ts";

const __document =
  "mutation submissionCreateIosSubmission($input: CreateIosSubmissionInput!) {\n  submission {\n    createIosSubmission(input: $input) {\n      submission {\n        activityTimestamp\n        actor {\n          created\n          displayName\n          firstName\n          id\n          isExpoAdmin\n          lastDeletionAttemptTime\n        }\n        androidConfig {\n          applicationIdentifier\n          archiveType\n          releaseStatus\n          rollout\n          track\n        }\n        app {\n          appStoreUrl\n          assetLimitPerUpdateGroup\n          buildProfiles\n          buildsReleaseChannels\n          description\n          environmentVariableEnvironments\n          fullName\n          githubUrl\n          iconUrl\n          id\n          internalDistributionBuildPrivacy\n          isDeleting\n          isDeprecated\n          isLikedByMe\n          lastDeletionAttemptTime\n          lastPublishedTime\n          latestActivity\n          latestReleaseId\n          likeCount\n          name\n          packageName\n          packageUsername\n          playStoreUrl\n          privacy\n          privacySetting\n          published\n          pushSecurityEnabled\n          releaseChannels\n          requiresAccessTokenForPushSecurity\n          resourceClassExperiment\n          scopeKey\n          sdkVersion\n          slug\n          suggestedDevDomainName\n          trendScore\n          updated\n          username\n        }\n        archiveUrl\n        canRetry\n        cancelingActor {\n          created\n          displayName\n          firstName\n          id\n          isExpoAdmin\n          lastDeletionAttemptTime\n        }\n        completedAt\n        createdAt\n        error {\n          errorCode\n          message\n        }\n        id\n        initiatingActor {\n          created\n          displayName\n          firstName\n          id\n          isExpoAdmin\n          lastDeletionAttemptTime\n        }\n        iosConfig {\n          appleIdUsername\n          ascApiKeyId\n          ascAppIdentifier\n        }\n        jobRun {\n          createdAt\n          displayName\n          endedAt\n          expiresAt\n          gitCommitHash\n          gitCommitMessage\n          gitRef\n          id\n          isWaived\n          logFileUrls\n          name\n          priority\n          startedAt\n          status\n          updateGroups\n        }\n        logFiles\n        logsUrl\n        maxRetryTimeMinutes\n        platform\n        priority\n        status\n        submittedBuild {\n          activityTimestamp\n          appBuildVersion\n          appIdentifier\n          appVersion\n          buildMode\n          buildProfile\n          channel\n          cliVersion\n          completedAt\n          createdAt\n          customNodeVersion\n          customWorkflowName\n          developmentClient\n          distribution\n          enqueuedAt\n          estimatedWaitTimeLeftSeconds\n          expirationDate\n          gitCommitHash\n          gitCommitMessage\n          gitRef\n          githubRepositoryOwnerAndName\n          id\n          initialQueuePosition\n          iosEnterpriseProvisioning\n          isForIosSimulator\n          isGitWorkingTreeDirty\n          isWaived\n          logFiles\n          maxBuildTimeSeconds\n          maxRetryTimeMinutes\n          message\n          platform\n          priority\n          projectMetadataFileUrl\n          projectRootDirectory\n          provisioningStartedAt\n          queuePosition\n          reactNativeVersion\n          releaseChannel\n          requiredPackageManager\n          resolvedEnvironment\n          resourceClass\n          resourceClassDisplayName\n          runFromCI\n          runtimeVersion\n          sdkVersion\n          selectedImage\n          status\n          updatedAt\n          waiverType\n          workerStartedAt\n        }\n        updatedAt\n        workflowJob {\n          createdAt\n          environment\n          id\n          key\n          name\n          outputs\n          requiredJobKeys\n          status\n          type\n          updatedAt\n        }\n      }\n    }\n  }\n}";

// Input Schema (GraphQL variables)
export const SubmissionCreateIosSubmissionInput = Schema.Struct({
  input: Schema.Struct({
    appId: Schema.String,
    archiveSource: Schema.optional(
      Schema.NullOr(
        Schema.Struct({
          bucketKey: Schema.optional(Schema.NullOr(Schema.String)),
          type: Schema.Literals([
            "GCS_BUILD_APPLICATION_ARCHIVE",
            "GCS_BUILD_APPLICATION_ARCHIVE_ORCHESTRATOR",
            "GCS_SUBMIT_ARCHIVE",
            "URL",
          ]),
          url: Schema.optional(Schema.NullOr(Schema.String)),
        }),
      ),
    ),
    config: Schema.Struct({
      appleAppSpecificPassword: Schema.optional(Schema.NullOr(Schema.String)),
      appleIdUsername: Schema.optional(Schema.NullOr(Schema.String)),
      ascApiKey: Schema.optional(
        Schema.NullOr(
          Schema.Struct({
            issuerIdentifier: Schema.String,
            keyIdentifier: Schema.String,
            keyP8: Schema.String,
          }),
        ),
      ),
      ascApiKeyId: Schema.optional(Schema.NullOr(Schema.String)),
      ascAppIdentifier: Schema.String,
      changelog: Schema.optional(Schema.NullOr(Schema.String)),
      groups: Schema.optional(Schema.NullOr(Schema.Array(Schema.String))),
      isVerboseFastlaneEnabled: Schema.optional(Schema.NullOr(Schema.Boolean)),
    }),
    submittedBuildId: Schema.optional(Schema.NullOr(Schema.String)),
  }),
}).pipe(
  T.Http({ method: "POST", path: "/graphql" }),
  T.GraphQLOp({
    query: __document,
    operationName: "submissionCreateIosSubmission",
    type: "mutation",
  }),
);
export type SubmissionCreateIosSubmissionInput =
  typeof SubmissionCreateIosSubmissionInput.Type;

// Output Schema (GraphQL selection set)
export const SubmissionCreateIosSubmissionOutput = Schema.Struct({
  submission: Schema.Struct({
    activityTimestamp: Schema.String,
    actor: Schema.NullOr(
      Schema.Struct({
        created: Schema.String,
        displayName: Schema.String,
        firstName: Schema.NullOr(Schema.String),
        id: Schema.String,
        isExpoAdmin: Schema.Boolean,
        lastDeletionAttemptTime: Schema.NullOr(Schema.String),
      }),
    ),
    androidConfig: Schema.NullOr(
      Schema.Struct({
        applicationIdentifier: Schema.NullOr(Schema.String),
        archiveType: Schema.NullOr(Schema.Literals(["AAB", "APK"])),
        releaseStatus: Schema.NullOr(
          Schema.Literals(["COMPLETED", "DRAFT", "HALTED", "IN_PROGRESS"]),
        ),
        rollout: Schema.NullOr(Schema.Number),
        track: Schema.String,
      }),
    ),
    app: Schema.Struct({
      appStoreUrl: Schema.NullOr(Schema.String),
      assetLimitPerUpdateGroup: Schema.Number,
      buildProfiles: Schema.Array(Schema.String),
      buildsReleaseChannels: Schema.Array(Schema.String),
      description: Schema.String,
      environmentVariableEnvironments: Schema.Array(Schema.Unknown),
      fullName: Schema.String,
      githubUrl: Schema.NullOr(Schema.String),
      iconUrl: Schema.NullOr(Schema.String),
      id: Schema.String,
      internalDistributionBuildPrivacy: Schema.Literals(["PRIVATE", "PUBLIC"]),
      isDeleting: Schema.Boolean,
      isDeprecated: Schema.Boolean,
      isLikedByMe: Schema.Boolean,
      lastDeletionAttemptTime: Schema.NullOr(Schema.String),
      lastPublishedTime: Schema.String,
      latestActivity: Schema.String,
      latestReleaseId: Schema.String,
      likeCount: Schema.Number,
      name: Schema.String,
      packageName: Schema.String,
      packageUsername: Schema.String,
      playStoreUrl: Schema.NullOr(Schema.String),
      privacy: Schema.String,
      privacySetting: Schema.Literals(["HIDDEN", "PUBLIC", "UNLISTED"]),
      published: Schema.Boolean,
      pushSecurityEnabled: Schema.Boolean,
      releaseChannels: Schema.Array(Schema.String),
      requiresAccessTokenForPushSecurity: Schema.Boolean,
      resourceClassExperiment: Schema.NullOr(Schema.Literals(["C3D", "N2"])),
      scopeKey: Schema.String,
      sdkVersion: Schema.String,
      slug: Schema.String,
      suggestedDevDomainName: Schema.String,
      trendScore: Schema.Number,
      updated: Schema.String,
      username: Schema.String,
    }),
    archiveUrl: Schema.NullOr(Schema.String),
    canRetry: Schema.Boolean,
    cancelingActor: Schema.NullOr(
      Schema.Struct({
        created: Schema.String,
        displayName: Schema.String,
        firstName: Schema.NullOr(Schema.String),
        id: Schema.String,
        isExpoAdmin: Schema.Boolean,
        lastDeletionAttemptTime: Schema.NullOr(Schema.String),
      }),
    ),
    completedAt: Schema.NullOr(Schema.String),
    createdAt: Schema.String,
    error: Schema.NullOr(
      Schema.Struct({
        errorCode: Schema.NullOr(Schema.String),
        message: Schema.NullOr(Schema.String),
      }),
    ),
    id: Schema.String,
    initiatingActor: Schema.NullOr(
      Schema.Struct({
        created: Schema.String,
        displayName: Schema.String,
        firstName: Schema.NullOr(Schema.String),
        id: Schema.String,
        isExpoAdmin: Schema.Boolean,
        lastDeletionAttemptTime: Schema.NullOr(Schema.String),
      }),
    ),
    iosConfig: Schema.NullOr(
      Schema.Struct({
        appleIdUsername: Schema.NullOr(Schema.String),
        ascApiKeyId: Schema.NullOr(Schema.String),
        ascAppIdentifier: Schema.String,
      }),
    ),
    jobRun: Schema.NullOr(
      Schema.Struct({
        createdAt: Schema.String,
        displayName: Schema.NullOr(Schema.String),
        endedAt: Schema.NullOr(Schema.String),
        expiresAt: Schema.String,
        gitCommitHash: Schema.NullOr(Schema.String),
        gitCommitMessage: Schema.NullOr(Schema.String),
        gitRef: Schema.NullOr(Schema.String),
        id: Schema.String,
        isWaived: Schema.Boolean,
        logFileUrls: Schema.Array(Schema.String),
        name: Schema.String,
        priority: Schema.Literals(["HIGH", "NORMAL"]),
        startedAt: Schema.NullOr(Schema.String),
        status: Schema.Literals([
          "CANCELED",
          "ERRORED",
          "FINISHED",
          "IN_PROGRESS",
          "IN_QUEUE",
          "NEW",
          "PENDING_CANCEL",
        ]),
        updateGroups: Schema.Array(Schema.Array(Schema.Unknown)),
      }),
    ),
    logFiles: Schema.Array(Schema.String),
    logsUrl: Schema.NullOr(Schema.String),
    maxRetryTimeMinutes: Schema.Number,
    platform: Schema.Literals(["ANDROID", "IOS"]),
    priority: Schema.NullOr(Schema.Literals(["HIGH", "NORMAL"])),
    status: Schema.Literals([
      "AWAITING_BUILD",
      "CANCELED",
      "ERRORED",
      "FINISHED",
      "IN_PROGRESS",
      "IN_QUEUE",
    ]),
    submittedBuild: Schema.NullOr(
      Schema.Struct({
        activityTimestamp: Schema.String,
        appBuildVersion: Schema.NullOr(Schema.String),
        appIdentifier: Schema.NullOr(Schema.String),
        appVersion: Schema.NullOr(Schema.String),
        buildMode: Schema.NullOr(
          Schema.Literals(["BUILD", "CUSTOM", "LOCAL", "REPACK", "RESIGN"]),
        ),
        buildProfile: Schema.NullOr(Schema.String),
        channel: Schema.NullOr(Schema.String),
        cliVersion: Schema.NullOr(Schema.String),
        completedAt: Schema.NullOr(Schema.String),
        createdAt: Schema.String,
        customNodeVersion: Schema.NullOr(Schema.String),
        customWorkflowName: Schema.NullOr(Schema.String),
        developmentClient: Schema.NullOr(Schema.Boolean),
        distribution: Schema.NullOr(
          Schema.Literals(["INTERNAL", "SIMULATOR", "STORE"]),
        ),
        enqueuedAt: Schema.NullOr(Schema.String),
        estimatedWaitTimeLeftSeconds: Schema.NullOr(Schema.Number),
        expirationDate: Schema.NullOr(Schema.String),
        gitCommitHash: Schema.NullOr(Schema.String),
        gitCommitMessage: Schema.NullOr(Schema.String),
        gitRef: Schema.NullOr(Schema.String),
        githubRepositoryOwnerAndName: Schema.NullOr(Schema.String),
        id: Schema.String,
        initialQueuePosition: Schema.NullOr(Schema.Number),
        iosEnterpriseProvisioning: Schema.NullOr(
          Schema.Literals(["ADHOC", "UNIVERSAL"]),
        ),
        isForIosSimulator: Schema.Boolean,
        isGitWorkingTreeDirty: Schema.NullOr(Schema.Boolean),
        isWaived: Schema.Boolean,
        logFiles: Schema.Array(Schema.String),
        maxBuildTimeSeconds: Schema.Number,
        maxRetryTimeMinutes: Schema.NullOr(Schema.Number),
        message: Schema.NullOr(Schema.String),
        platform: Schema.Literals(["ANDROID", "IOS"]),
        priority: Schema.Literals(["HIGH", "NORMAL", "NORMAL_PLUS"]),
        projectMetadataFileUrl: Schema.NullOr(Schema.String),
        projectRootDirectory: Schema.NullOr(Schema.String),
        provisioningStartedAt: Schema.NullOr(Schema.String),
        queuePosition: Schema.NullOr(Schema.Number),
        reactNativeVersion: Schema.NullOr(Schema.String),
        releaseChannel: Schema.NullOr(Schema.String),
        requiredPackageManager: Schema.NullOr(Schema.String),
        resolvedEnvironment: Schema.NullOr(Schema.Unknown),
        resourceClass: Schema.Literals([
          "ANDROID_DEFAULT",
          "ANDROID_LARGE",
          "ANDROID_MEDIUM",
          "IOS_DEFAULT",
          "IOS_INTEL_LARGE",
          "IOS_INTEL_MEDIUM",
          "IOS_LARGE",
          "IOS_M1_LARGE",
          "IOS_M1_MEDIUM",
          "IOS_MEDIUM",
          "IOS_M_LARGE",
          "IOS_M_MEDIUM",
          "LEGACY",
          "LINUX_LARGE",
          "LINUX_MEDIUM",
        ]),
        resourceClassDisplayName: Schema.String,
        runFromCI: Schema.NullOr(Schema.Boolean),
        runtimeVersion: Schema.NullOr(Schema.String),
        sdkVersion: Schema.NullOr(Schema.String),
        selectedImage: Schema.NullOr(Schema.String),
        status: Schema.Literals([
          "CANCELED",
          "ERRORED",
          "FINISHED",
          "IN_PROGRESS",
          "IN_QUEUE",
          "NEW",
          "PENDING_CANCEL",
        ]),
        updatedAt: Schema.String,
        waiverType: Schema.NullOr(
          Schema.Literals(["FAST_FAILED_BUILD", "SYSTEM_ERROR"]),
        ),
        workerStartedAt: Schema.NullOr(Schema.String),
      }),
    ),
    updatedAt: Schema.String,
    workflowJob: Schema.NullOr(
      Schema.Struct({
        createdAt: Schema.String,
        environment: Schema.NullOr(Schema.String),
        id: Schema.String,
        key: Schema.String,
        name: Schema.String,
        outputs: Schema.Unknown,
        requiredJobKeys: Schema.Array(Schema.String),
        status: Schema.Literals([
          "ACTION_REQUIRED",
          "CANCELED",
          "FAILURE",
          "IN_PROGRESS",
          "NEW",
          "PENDING_CANCEL",
          "SKIPPED",
          "SUCCESS",
        ]),
        type: Schema.Literals([
          "APPLE_DEVICE_REGISTRATION_REQUEST",
          "BUILD",
          "CUSTOM",
          "DEPLOY",
          "DOC",
          "FINGERPRINT",
          "GET_BUILD",
          "GITHUB_COMMENT",
          "MAESTRO_CLOUD",
          "MAESTRO_TEST",
          "REPACK",
          "REQUIRE_APPROVAL",
          "SLACK",
          "SUBMISSION",
          "TESTFLIGHT",
          "UPDATE",
        ]),
        updatedAt: Schema.String,
      }),
    ),
  }),
}).pipe(T.ResponsePath("submission.createIosSubmission"));
export type SubmissionCreateIosSubmissionOutput =
  typeof SubmissionCreateIosSubmissionOutput.Type;

export const submissionCreateIosSubmission = API.make(() => ({
  inputSchema: SubmissionCreateIosSubmissionInput,
  outputSchema: SubmissionCreateIosSubmissionOutput,
}));
