import * as Schema from "effect/Schema";
import { API } from "../client.ts";
import * as T from "../traits.ts";

const __document =
  "mutation updateBranchPublishUpdateGroups($publishUpdateGroupsInput: [PublishUpdateGroupInput!]!) {\n  updateBranch {\n    publishUpdateGroups(publishUpdateGroupsInput: $publishUpdateGroupsInput) {\n      activityTimestamp\n      actor {\n        accessTokens {\n          createdAt\n          id\n          lastUsedAt\n          note\n          revokedAt\n          updatedAt\n          visibleTokenPrefix\n        }\n        accounts {\n          appCount\n          availableBuilds\n          createdAt\n          displayName\n          environmentVariableEnvironments\n          hasBuilds\n          id\n          isCurrent\n          isDisabled\n          isFreeAppDevDomainTier\n          isSSOEnabled\n          lastDeletionAttemptTime\n          name\n          profileImageUrl\n          pushSecurityEnabled\n          requireTwoFactor\n          requiresAccessTokenForPushSecurity\n          ssoAllowedAuthProviders\n          subscriptionChangesPending\n          unlimitedBuilds\n          updatedAt\n          userSpecifiedAccountUsage\n          willAutoRenewBuilds\n        }\n        created\n        displayName\n        experiments {\n          createdAt\n          enabled\n          experiment\n          id\n          updatedAt\n        }\n        firstName\n        id\n        isExpoAdmin\n        lastDeletionAttemptTime\n      }\n      app {\n        accessTokens {\n          createdAt\n          id\n          lastUsedAt\n          note\n          revokedAt\n          updatedAt\n          visibleTokenPrefix\n        }\n        appStoreConnectApp {\n          ascAppIdentifier\n          createdAt\n          id\n          updatedAt\n          webhookEventTypes\n          webhookIdentifier\n        }\n        appStoreUrl\n        assetLimitPerUpdateGroup\n        buildProfiles\n        buildsReleaseChannels\n        convexProject {\n          convexProjectIdentifier\n          convexProjectName\n          convexProjectSlug\n          createdAt\n          id\n          updatedAt\n        }\n        description\n        devDomainName {\n          id\n          name\n        }\n        environmentVariableEnvironments\n        fullName\n        githubBuildTriggers {\n          autoSubmit\n          buildProfile\n          createdAt\n          environment\n          executionBehavior\n          id\n          isActive\n          lastRunAt\n          lastRunErrorCode\n          lastRunErrorMessage\n          lastRunStatus\n          platform\n          sourcePattern\n          submitProfile\n          targetPattern\n          type\n          updatedAt\n        }\n        githubJobRunTriggers {\n          createdAt\n          id\n          isActive\n          jobType\n          lastRunAt\n          lastRunErrorCode\n          lastRunErrorMessage\n          lastRunStatus\n          sourcePattern\n          targetPattern\n          triggerType\n        }\n        githubRepository {\n          createdAt\n          githubRepositoryIdentifier\n          githubRepositoryUrl\n          id\n          lastDeletionAttemptTime\n          nodeIdentifier\n        }\n        githubRepositorySettings {\n          baseDirectory\n          id\n        }\n        githubUrl\n        icon {\n          colorPalette\n          originalUrl\n          primaryColor\n          url\n        }\n        iconUrl\n        id\n        insights {\n          hasEventsFromExpoInsightsClientModule\n        }\n        internalDistributionBuildPrivacy\n        isDeleting\n        isDeprecated\n        isLikedByMe\n        lastDeletionAttemptTime\n        lastPublishedTime\n        latestActivity\n        latestReleaseId\n        likeCount\n        logRocketProject {\n          createdAt\n          id\n          logRocketOrgId\n          logRocketProjectSlug\n          updatedAt\n        }\n        name\n        observe {\n          totalEventCount\n        }\n        ownerAccount {\n          appCount\n          availableBuilds\n          createdAt\n          displayName\n          environmentVariableEnvironments\n          hasBuilds\n          id\n          isCurrent\n          isDisabled\n          isFreeAppDevDomainTier\n          isSSOEnabled\n          lastDeletionAttemptTime\n          name\n          profileImageUrl\n          pushSecurityEnabled\n          requireTwoFactor\n          requiresAccessTokenForPushSecurity\n          ssoAllowedAuthProviders\n          subscriptionChangesPending\n          unlimitedBuilds\n          updatedAt\n          userSpecifiedAccountUsage\n          willAutoRenewBuilds\n        }\n        packageName\n        packageUsername\n        playStoreUrl\n        privacy\n        privacySetting\n        published\n        pushNotifications {\n          id\n        }\n        pushSecurityEnabled\n        releaseChannels\n        requiresAccessTokenForPushSecurity\n        resourceClassExperiment\n        scopeKey\n        sdkVersion\n        sentryProject {\n          createdAt\n          id\n          sentryInstallationId\n          sentryProjectId\n          sentryProjectSlug\n          updatedAt\n        }\n        slug\n        suggestedDevDomainName\n        trendScore\n        updated\n        username\n        users {\n          appCount\n          appetizeCode\n          bestContactEmail\n          created\n          displayName\n          email\n          emailVerified\n          firstName\n          fullName\n          githubUsername\n          hasPassword\n          hasPendingUserInvitations\n          id\n          industry\n          isExpoAdmin\n          isLegacy\n          isSecondFactorAuthenticationEnabled\n          isStaffModeEnabled\n          lastDeletionAttemptTime\n          lastName\n          location\n          newEmailPendingVerification\n          primaryAccountProfileImageUrl\n          profilePhoto\n          twitterUsername\n          username\n        }\n        vexoApp {\n          domain\n          iconUrl\n          id\n          name\n          owner\n          slug\n          vexoIdentifier\n        }\n        workerCustomDomain {\n          createdAt\n          devDomainName\n          hostname\n          id\n          updatedAt\n        }\n      }\n      assetHostOverride\n      assetMapUrl\n      awaitingCodeSigningInfo\n      branch {\n        app {\n          appStoreUrl\n          assetLimitPerUpdateGroup\n          buildProfiles\n          buildsReleaseChannels\n          description\n          environmentVariableEnvironments\n          fullName\n          githubUrl\n          iconUrl\n          id\n          internalDistributionBuildPrivacy\n          isDeleting\n          isDeprecated\n          isLikedByMe\n          lastDeletionAttemptTime\n          lastPublishedTime\n          latestActivity\n          latestReleaseId\n          likeCount\n          name\n          packageName\n          packageUsername\n          playStoreUrl\n          privacy\n          privacySetting\n          published\n          pushSecurityEnabled\n          releaseChannels\n          requiresAccessTokenForPushSecurity\n          resourceClassExperiment\n          scopeKey\n          sdkVersion\n          slug\n          suggestedDevDomainName\n          trendScore\n          updated\n          username\n        }\n        appId\n        createdAt\n        id\n        lastDeletionAttemptTime\n        latestActivity\n        name\n        updatedAt\n      }\n      branchId\n      codeSigningInfo {\n        alg\n        keyid\n        sig\n      }\n      createdAt\n      environment\n      expoGoSDKVersion\n      fingerprint {\n        app {\n          appStoreUrl\n          assetLimitPerUpdateGroup\n          buildProfiles\n          buildsReleaseChannels\n          description\n          environmentVariableEnvironments\n          fullName\n          githubUrl\n          iconUrl\n          id\n          internalDistributionBuildPrivacy\n          isDeleting\n          isDeprecated\n          isLikedByMe\n          lastDeletionAttemptTime\n          lastPublishedTime\n          latestActivity\n          latestReleaseId\n          likeCount\n          name\n          packageName\n          packageUsername\n          playStoreUrl\n          privacy\n          privacySetting\n          published\n          pushSecurityEnabled\n          releaseChannels\n          requiresAccessTokenForPushSecurity\n          resourceClassExperiment\n          scopeKey\n          sdkVersion\n          slug\n          suggestedDevDomainName\n          trendScore\n          updated\n          username\n        }\n        buildCount\n        createdAt\n        debugInfoUrl\n        hash\n        id\n        source {\n          bucketKey\n          isDebugFingerprint\n          type\n        }\n        updateCount\n        updatedAt\n      }\n      gitCommitHash\n      group\n      id\n      insights {\n        averageAssetMetrics {\n          averageDownloadSizeBytes\n          baseUpdateDownloadUrl\n          baseUpdateId\n          count\n          storageKey\n        }\n        cumulativeAverageMetrics {\n          averageUpdatePayloadBytes\n          launchAssetCount\n        }\n        id\n        sizeBreakdownByCategory {\n          assetCount\n          category\n          totalBytes\n        }\n      }\n      isGitWorkingTreeDirty\n      isRollBackToEmbedded\n      jobRun {\n        app {\n          appStoreUrl\n          assetLimitPerUpdateGroup\n          buildProfiles\n          buildsReleaseChannels\n          description\n          environmentVariableEnvironments\n          fullName\n          githubUrl\n          iconUrl\n          id\n          internalDistributionBuildPrivacy\n          isDeleting\n          isDeprecated\n          isLikedByMe\n          lastDeletionAttemptTime\n          lastPublishedTime\n          latestActivity\n          latestReleaseId\n          likeCount\n          name\n          packageName\n          packageUsername\n          playStoreUrl\n          privacy\n          privacySetting\n          published\n          pushSecurityEnabled\n          releaseChannels\n          requiresAccessTokenForPushSecurity\n          resourceClassExperiment\n          scopeKey\n          sdkVersion\n          slug\n          suggestedDevDomainName\n          trendScore\n          updated\n          username\n        }\n        artifacts {\n          contentType\n          createdAt\n          downloadUrl\n          fileSizeBytes\n          filename\n          id\n          name\n          storageType\n          updatedAt\n        }\n        createdAt\n        displayName\n        endedAt\n        errors {\n          buildPhase\n          docsUrl\n          errorCode\n          message\n        }\n        expiresAt\n        gitCommitHash\n        gitCommitMessage\n        gitRef\n        id\n        initiatingActor {\n          created\n          displayName\n          firstName\n          id\n          isExpoAdmin\n          lastDeletionAttemptTime\n        }\n        isWaived\n        logFileUrls\n        name\n        priority\n        startedAt\n        status\n        updateGroups\n      }\n      manifestFragment\n      manifestHostOverride\n      manifestPermalink\n      message\n      platform\n      rolloutPercentage\n      runtime {\n        app {\n          appStoreUrl\n          assetLimitPerUpdateGroup\n          buildProfiles\n          buildsReleaseChannels\n          description\n          environmentVariableEnvironments\n          fullName\n          githubUrl\n          iconUrl\n          id\n          internalDistributionBuildPrivacy\n          isDeleting\n          isDeprecated\n          isLikedByMe\n          lastDeletionAttemptTime\n          lastPublishedTime\n          latestActivity\n          latestReleaseId\n          likeCount\n          name\n          packageName\n          packageUsername\n          playStoreUrl\n          privacy\n          privacySetting\n          published\n          pushSecurityEnabled\n          releaseChannels\n          requiresAccessTokenForPushSecurity\n          resourceClassExperiment\n          scopeKey\n          sdkVersion\n          slug\n          suggestedDevDomainName\n          trendScore\n          updated\n          username\n        }\n        createdAt\n        fingerprint {\n          buildCount\n          createdAt\n          debugInfoUrl\n          hash\n          id\n          updateCount\n          updatedAt\n        }\n        firstBuildCreatedAt\n        id\n        isFingerprint\n        updatedAt\n        version\n      }\n      runtimeVersion\n      updatedAt\n      workflowJob {\n        allDeviceTestCaseResults {\n          createdAt\n          duration\n          errorMessage\n          id\n          name\n          path\n          properties\n          retryCount\n          status\n          tags\n          updatedAt\n        }\n        approvals {\n          createdAt\n          decision\n          id\n          updatedAt\n        }\n        createdAt\n        credentialsAppleDeviceRegistrationRequest {\n          id\n        }\n        deviceTestCaseResults {\n          createdAt\n          duration\n          errorMessage\n          id\n          name\n          path\n          properties\n          retryCount\n          status\n          tags\n          updatedAt\n        }\n        environment\n        errors {\n          message\n          title\n        }\n        id\n        key\n        name\n        outputs\n        requiredJobKeys\n        status\n        turtleBuild {\n          activityTimestamp\n          appBuildVersion\n          appIdentifier\n          appVersion\n          buildMode\n          buildProfile\n          channel\n          cliVersion\n          completedAt\n          createdAt\n          customNodeVersion\n          customWorkflowName\n          developmentClient\n          distribution\n          enqueuedAt\n          estimatedWaitTimeLeftSeconds\n          expirationDate\n          gitCommitHash\n          gitCommitMessage\n          gitRef\n          githubRepositoryOwnerAndName\n          id\n          initialQueuePosition\n          iosEnterpriseProvisioning\n          isForIosSimulator\n          isGitWorkingTreeDirty\n          isWaived\n          logFiles\n          maxBuildTimeSeconds\n          maxRetryTimeMinutes\n          message\n          platform\n          priority\n          projectMetadataFileUrl\n          projectRootDirectory\n          provisioningStartedAt\n          queuePosition\n          reactNativeVersion\n          releaseChannel\n          requiredPackageManager\n          resolvedEnvironment\n          resourceClass\n          resourceClassDisplayName\n          runFromCI\n          runtimeVersion\n          sdkVersion\n          selectedImage\n          status\n          updatedAt\n          waiverType\n          workerStartedAt\n        }\n        turtleJobRun {\n          createdAt\n          displayName\n          endedAt\n          expiresAt\n          gitCommitHash\n          gitCommitMessage\n          gitRef\n          id\n          isWaived\n          logFileUrls\n          name\n          priority\n          startedAt\n          status\n          updateGroups\n        }\n        turtleSubmission {\n          activityTimestamp\n          archiveUrl\n          canRetry\n          completedAt\n          createdAt\n          id\n          logFiles\n          logsUrl\n          maxRetryTimeMinutes\n          platform\n          priority\n          status\n          updatedAt\n        }\n        type\n        updatedAt\n        workflowRun {\n          activityTimestamp\n          createdAt\n          durationSeconds\n          finalizedAt\n          gitCommitHash\n          gitCommitMessage\n          id\n          inputs\n          name\n          pullRequestNumber\n          requestedGitRef\n          sourceExpiresAt\n          status\n          triggerEventType\n          triggeringLabelName\n          triggeringSchedule\n          updatedAt\n        }\n      }\n    }\n  }\n}";

// Input Schema (GraphQL variables)
export const UpdateBranchPublishUpdateGroupsInput = Schema.Struct({
  publishUpdateGroupsInput: Schema.Array(
    Schema.Struct({
      assetHostOverride: Schema.optional(Schema.NullOr(Schema.String)),
      assetMapGroup: Schema.optional(
        Schema.NullOr(
          Schema.Struct({
            android: Schema.optional(
              Schema.NullOr(
                Schema.Struct({
                  bucketKey: Schema.optional(Schema.NullOr(Schema.String)),
                  type: Schema.optional(
                    Schema.NullOr(Schema.Literals(["GCS"])),
                  ),
                }),
              ),
            ),
            ios: Schema.optional(
              Schema.NullOr(
                Schema.Struct({
                  bucketKey: Schema.optional(Schema.NullOr(Schema.String)),
                  type: Schema.optional(
                    Schema.NullOr(Schema.Literals(["GCS"])),
                  ),
                }),
              ),
            ),
            web: Schema.optional(
              Schema.NullOr(
                Schema.Struct({
                  bucketKey: Schema.optional(Schema.NullOr(Schema.String)),
                  type: Schema.optional(
                    Schema.NullOr(Schema.Literals(["GCS"])),
                  ),
                }),
              ),
            ),
          }),
        ),
      ),
      awaitingCodeSigningInfo: Schema.optional(Schema.NullOr(Schema.Boolean)),
      branchId: Schema.String,
      environment: Schema.optional(Schema.NullOr(Schema.Unknown)),
      excludedAssets: Schema.optional(
        Schema.NullOr(
          Schema.Array(
            Schema.Struct({
              bundleKey: Schema.String,
              contentType: Schema.String,
              fileExtension: Schema.optional(Schema.NullOr(Schema.String)),
              fileSHA256: Schema.String,
              storageKey: Schema.String,
            }),
          ),
        ),
      ),
      fingerprintInfoGroup: Schema.optional(
        Schema.NullOr(
          Schema.Struct({
            android: Schema.optional(
              Schema.NullOr(
                Schema.Struct({
                  fingerprintHash: Schema.String,
                  fingerprintSource: Schema.Struct({
                    bucketKey: Schema.optional(Schema.NullOr(Schema.String)),
                    isDebugFingerprint: Schema.optional(
                      Schema.NullOr(Schema.Boolean),
                    ),
                    type: Schema.optional(
                      Schema.NullOr(Schema.Literals(["GCS"])),
                    ),
                  }),
                }),
              ),
            ),
            ios: Schema.optional(
              Schema.NullOr(
                Schema.Struct({
                  fingerprintHash: Schema.String,
                  fingerprintSource: Schema.Struct({
                    bucketKey: Schema.optional(Schema.NullOr(Schema.String)),
                    isDebugFingerprint: Schema.optional(
                      Schema.NullOr(Schema.Boolean),
                    ),
                    type: Schema.optional(
                      Schema.NullOr(Schema.Literals(["GCS"])),
                    ),
                  }),
                }),
              ),
            ),
            web: Schema.optional(
              Schema.NullOr(
                Schema.Struct({
                  fingerprintHash: Schema.String,
                  fingerprintSource: Schema.Struct({
                    bucketKey: Schema.optional(Schema.NullOr(Schema.String)),
                    isDebugFingerprint: Schema.optional(
                      Schema.NullOr(Schema.Boolean),
                    ),
                    type: Schema.optional(
                      Schema.NullOr(Schema.Literals(["GCS"])),
                    ),
                  }),
                }),
              ),
            ),
          }),
        ),
      ),
      gitCommitHash: Schema.optional(Schema.NullOr(Schema.String)),
      isGitWorkingTreeDirty: Schema.optional(Schema.NullOr(Schema.Boolean)),
      manifestHostOverride: Schema.optional(Schema.NullOr(Schema.String)),
      message: Schema.optional(Schema.NullOr(Schema.String)),
      rollBackToEmbeddedInfoGroup: Schema.optional(
        Schema.NullOr(
          Schema.Struct({
            android: Schema.optional(Schema.NullOr(Schema.Boolean)),
            ios: Schema.optional(Schema.NullOr(Schema.Boolean)),
            web: Schema.optional(Schema.NullOr(Schema.Boolean)),
          }),
        ),
      ),
      rolloutInfoGroup: Schema.optional(
        Schema.NullOr(
          Schema.Struct({
            android: Schema.optional(
              Schema.NullOr(
                Schema.Struct({
                  rolloutControlUpdateId: Schema.optional(
                    Schema.NullOr(Schema.String),
                  ),
                  rolloutPercentage: Schema.Number,
                }),
              ),
            ),
            ios: Schema.optional(
              Schema.NullOr(
                Schema.Struct({
                  rolloutControlUpdateId: Schema.optional(
                    Schema.NullOr(Schema.String),
                  ),
                  rolloutPercentage: Schema.Number,
                }),
              ),
            ),
            web: Schema.optional(
              Schema.NullOr(
                Schema.Struct({
                  rolloutControlUpdateId: Schema.optional(
                    Schema.NullOr(Schema.String),
                  ),
                  rolloutPercentage: Schema.Number,
                }),
              ),
            ),
          }),
        ),
      ),
      runtimeVersion: Schema.String,
      turtleJobRunId: Schema.optional(Schema.NullOr(Schema.String)),
      updateInfoGroup: Schema.optional(
        Schema.NullOr(
          Schema.Struct({
            android: Schema.optional(
              Schema.NullOr(
                Schema.Struct({
                  assets: Schema.Array(
                    Schema.NullOr(
                      Schema.Struct({
                        bundleKey: Schema.String,
                        contentType: Schema.String,
                        fileExtension: Schema.optional(
                          Schema.NullOr(Schema.String),
                        ),
                        fileSHA256: Schema.String,
                        storageKey: Schema.String,
                      }),
                    ),
                  ),
                  extra: Schema.optional(Schema.NullOr(Schema.Unknown)),
                  launchAsset: Schema.Struct({
                    bundleKey: Schema.String,
                    contentType: Schema.String,
                    fileExtension: Schema.optional(
                      Schema.NullOr(Schema.String),
                    ),
                    fileSHA256: Schema.String,
                    storageKey: Schema.String,
                  }),
                }),
              ),
            ),
            ios: Schema.optional(
              Schema.NullOr(
                Schema.Struct({
                  assets: Schema.Array(
                    Schema.NullOr(
                      Schema.Struct({
                        bundleKey: Schema.String,
                        contentType: Schema.String,
                        fileExtension: Schema.optional(
                          Schema.NullOr(Schema.String),
                        ),
                        fileSHA256: Schema.String,
                        storageKey: Schema.String,
                      }),
                    ),
                  ),
                  extra: Schema.optional(Schema.NullOr(Schema.Unknown)),
                  launchAsset: Schema.Struct({
                    bundleKey: Schema.String,
                    contentType: Schema.String,
                    fileExtension: Schema.optional(
                      Schema.NullOr(Schema.String),
                    ),
                    fileSHA256: Schema.String,
                    storageKey: Schema.String,
                  }),
                }),
              ),
            ),
            web: Schema.optional(
              Schema.NullOr(
                Schema.Struct({
                  assets: Schema.Array(
                    Schema.NullOr(
                      Schema.Struct({
                        bundleKey: Schema.String,
                        contentType: Schema.String,
                        fileExtension: Schema.optional(
                          Schema.NullOr(Schema.String),
                        ),
                        fileSHA256: Schema.String,
                        storageKey: Schema.String,
                      }),
                    ),
                  ),
                  extra: Schema.optional(Schema.NullOr(Schema.Unknown)),
                  launchAsset: Schema.Struct({
                    bundleKey: Schema.String,
                    contentType: Schema.String,
                    fileExtension: Schema.optional(
                      Schema.NullOr(Schema.String),
                    ),
                    fileSHA256: Schema.String,
                    storageKey: Schema.String,
                  }),
                }),
              ),
            ),
          }),
        ),
      ),
    }),
  ),
}).pipe(
  T.Http({ method: "POST", path: "/graphql" }),
  T.GraphQLOp({
    query: __document,
    operationName: "updateBranchPublishUpdateGroups",
    type: "mutation",
  }),
);
export type UpdateBranchPublishUpdateGroupsInput =
  typeof UpdateBranchPublishUpdateGroupsInput.Type;

// Output Schema (GraphQL selection set)
export const UpdateBranchPublishUpdateGroupsOutput = Schema.Array(
  Schema.Struct({
    activityTimestamp: Schema.String,
    actor: Schema.NullOr(
      Schema.Struct({
        accessTokens: Schema.Array(
          Schema.Struct({
            createdAt: Schema.String,
            id: Schema.String,
            lastUsedAt: Schema.NullOr(Schema.String),
            note: Schema.NullOr(Schema.String),
            revokedAt: Schema.NullOr(Schema.String),
            updatedAt: Schema.String,
            visibleTokenPrefix: Schema.String,
          }),
        ),
        accounts: Schema.Array(
          Schema.Struct({
            appCount: Schema.Number,
            availableBuilds: Schema.NullOr(Schema.Number),
            createdAt: Schema.String,
            displayName: Schema.NullOr(Schema.String),
            environmentVariableEnvironments: Schema.Array(Schema.Unknown),
            hasBuilds: Schema.Boolean,
            id: Schema.String,
            isCurrent: Schema.Boolean,
            isDisabled: Schema.Boolean,
            isFreeAppDevDomainTier: Schema.Boolean,
            isSSOEnabled: Schema.Boolean,
            lastDeletionAttemptTime: Schema.NullOr(Schema.String),
            name: Schema.String,
            profileImageUrl: Schema.String,
            pushSecurityEnabled: Schema.Boolean,
            requireTwoFactor: Schema.Boolean,
            requiresAccessTokenForPushSecurity: Schema.Boolean,
            ssoAllowedAuthProviders: Schema.Array(
              Schema.Literals([
                "AMAZON_FEDERATE",
                "GENERIC",
                "GOOGLE_WS",
                "MS_ENTRA_ID",
                "OKTA",
                "ONE_LOGIN",
                "STUB_IDP",
              ]),
            ),
            subscriptionChangesPending: Schema.NullOr(Schema.Boolean),
            unlimitedBuilds: Schema.Boolean,
            updatedAt: Schema.String,
            userSpecifiedAccountUsage: Schema.NullOr(
              Schema.Literals(["COMPANY", "PERSONAL"]),
            ),
            willAutoRenewBuilds: Schema.NullOr(Schema.Boolean),
          }),
        ),
        created: Schema.String,
        displayName: Schema.String,
        experiments: Schema.Array(
          Schema.Struct({
            createdAt: Schema.String,
            enabled: Schema.Boolean,
            experiment: Schema.Literals(["ORBIT"]),
            id: Schema.String,
            updatedAt: Schema.String,
          }),
        ),
        firstName: Schema.NullOr(Schema.String),
        id: Schema.String,
        isExpoAdmin: Schema.Boolean,
        lastDeletionAttemptTime: Schema.NullOr(Schema.String),
      }),
    ),
    app: Schema.Struct({
      accessTokens: Schema.Array(
        Schema.NullOr(
          Schema.Struct({
            createdAt: Schema.String,
            id: Schema.String,
            lastUsedAt: Schema.NullOr(Schema.String),
            note: Schema.NullOr(Schema.String),
            revokedAt: Schema.NullOr(Schema.String),
            updatedAt: Schema.String,
            visibleTokenPrefix: Schema.String,
          }),
        ),
      ),
      appStoreConnectApp: Schema.NullOr(
        Schema.Struct({
          ascAppIdentifier: Schema.String,
          createdAt: Schema.String,
          id: Schema.String,
          updatedAt: Schema.String,
          webhookEventTypes: Schema.Array(Schema.String),
          webhookIdentifier: Schema.String,
        }),
      ),
      appStoreUrl: Schema.NullOr(Schema.String),
      assetLimitPerUpdateGroup: Schema.Number,
      buildProfiles: Schema.Array(Schema.String),
      buildsReleaseChannels: Schema.Array(Schema.String),
      convexProject: Schema.NullOr(
        Schema.Struct({
          convexProjectIdentifier: Schema.String,
          convexProjectName: Schema.String,
          convexProjectSlug: Schema.String,
          createdAt: Schema.String,
          id: Schema.String,
          updatedAt: Schema.String,
        }),
      ),
      description: Schema.String,
      devDomainName: Schema.NullOr(
        Schema.Struct({
          id: Schema.String,
          name: Schema.Unknown,
        }),
      ),
      environmentVariableEnvironments: Schema.Array(Schema.Unknown),
      fullName: Schema.String,
      githubBuildTriggers: Schema.Array(
        Schema.Struct({
          autoSubmit: Schema.Boolean,
          buildProfile: Schema.String,
          createdAt: Schema.String,
          environment: Schema.NullOr(Schema.Unknown),
          executionBehavior: Schema.Literals([
            "ALWAYS",
            "BASE_DIRECTORY_CHANGED",
          ]),
          id: Schema.String,
          isActive: Schema.Boolean,
          lastRunAt: Schema.NullOr(Schema.String),
          lastRunErrorCode: Schema.NullOr(Schema.String),
          lastRunErrorMessage: Schema.NullOr(Schema.String),
          lastRunStatus: Schema.NullOr(Schema.Literals(["ERRORED", "SUCCESS"])),
          platform: Schema.Literals(["ANDROID", "IOS"]),
          sourcePattern: Schema.String,
          submitProfile: Schema.NullOr(Schema.String),
          targetPattern: Schema.NullOr(Schema.String),
          type: Schema.Literals([
            "PULL_REQUEST_UPDATED",
            "PUSH_TO_BRANCH",
            "TAG_UPDATED",
          ]),
          updatedAt: Schema.String,
        }),
      ),
      githubJobRunTriggers: Schema.Array(
        Schema.Struct({
          createdAt: Schema.String,
          id: Schema.String,
          isActive: Schema.Boolean,
          jobType: Schema.NullOr(Schema.Literals(["PUBLISH_UPDATE"])),
          lastRunAt: Schema.NullOr(Schema.String),
          lastRunErrorCode: Schema.NullOr(Schema.String),
          lastRunErrorMessage: Schema.NullOr(Schema.String),
          lastRunStatus: Schema.NullOr(Schema.Literals(["ERRORED", "SUCCESS"])),
          sourcePattern: Schema.String,
          targetPattern: Schema.NullOr(Schema.String),
          triggerType: Schema.Literals([
            "PULL_REQUEST_UPDATED",
            "PUSH_TO_BRANCH",
          ]),
        }),
      ),
      githubRepository: Schema.NullOr(
        Schema.Struct({
          createdAt: Schema.String,
          githubRepositoryIdentifier: Schema.Number,
          githubRepositoryUrl: Schema.NullOr(Schema.String),
          id: Schema.String,
          lastDeletionAttemptTime: Schema.NullOr(Schema.String),
          nodeIdentifier: Schema.String,
        }),
      ),
      githubRepositorySettings: Schema.NullOr(
        Schema.Struct({
          baseDirectory: Schema.String,
          id: Schema.String,
        }),
      ),
      githubUrl: Schema.NullOr(Schema.String),
      icon: Schema.NullOr(
        Schema.Struct({
          colorPalette: Schema.NullOr(Schema.Unknown),
          originalUrl: Schema.String,
          primaryColor: Schema.NullOr(Schema.String),
          url: Schema.String,
        }),
      ),
      iconUrl: Schema.NullOr(Schema.String),
      id: Schema.String,
      insights: Schema.Struct({
        hasEventsFromExpoInsightsClientModule: Schema.Boolean,
      }),
      internalDistributionBuildPrivacy: Schema.Literals(["PRIVATE", "PUBLIC"]),
      isDeleting: Schema.Boolean,
      isDeprecated: Schema.Boolean,
      isLikedByMe: Schema.Boolean,
      lastDeletionAttemptTime: Schema.NullOr(Schema.String),
      lastPublishedTime: Schema.String,
      latestActivity: Schema.String,
      latestReleaseId: Schema.String,
      likeCount: Schema.Number,
      logRocketProject: Schema.NullOr(
        Schema.Struct({
          createdAt: Schema.String,
          id: Schema.String,
          logRocketOrgId: Schema.String,
          logRocketProjectSlug: Schema.String,
          updatedAt: Schema.String,
        }),
      ),
      name: Schema.String,
      observe: Schema.Struct({
        totalEventCount: Schema.Number,
      }),
      ownerAccount: Schema.Struct({
        appCount: Schema.Number,
        availableBuilds: Schema.NullOr(Schema.Number),
        createdAt: Schema.String,
        displayName: Schema.NullOr(Schema.String),
        environmentVariableEnvironments: Schema.Array(Schema.Unknown),
        hasBuilds: Schema.Boolean,
        id: Schema.String,
        isCurrent: Schema.Boolean,
        isDisabled: Schema.Boolean,
        isFreeAppDevDomainTier: Schema.Boolean,
        isSSOEnabled: Schema.Boolean,
        lastDeletionAttemptTime: Schema.NullOr(Schema.String),
        name: Schema.String,
        profileImageUrl: Schema.String,
        pushSecurityEnabled: Schema.Boolean,
        requireTwoFactor: Schema.Boolean,
        requiresAccessTokenForPushSecurity: Schema.Boolean,
        ssoAllowedAuthProviders: Schema.Array(
          Schema.Literals([
            "AMAZON_FEDERATE",
            "GENERIC",
            "GOOGLE_WS",
            "MS_ENTRA_ID",
            "OKTA",
            "ONE_LOGIN",
            "STUB_IDP",
          ]),
        ),
        subscriptionChangesPending: Schema.NullOr(Schema.Boolean),
        unlimitedBuilds: Schema.Boolean,
        updatedAt: Schema.String,
        userSpecifiedAccountUsage: Schema.NullOr(
          Schema.Literals(["COMPANY", "PERSONAL"]),
        ),
        willAutoRenewBuilds: Schema.NullOr(Schema.Boolean),
      }),
      packageName: Schema.String,
      packageUsername: Schema.String,
      playStoreUrl: Schema.NullOr(Schema.String),
      privacy: Schema.String,
      privacySetting: Schema.Literals(["HIDDEN", "PUBLIC", "UNLISTED"]),
      published: Schema.Boolean,
      pushNotifications: Schema.Struct({
        id: Schema.String,
      }),
      pushSecurityEnabled: Schema.Boolean,
      releaseChannels: Schema.Array(Schema.String),
      requiresAccessTokenForPushSecurity: Schema.Boolean,
      resourceClassExperiment: Schema.NullOr(Schema.Literals(["C3D", "N2"])),
      scopeKey: Schema.String,
      sdkVersion: Schema.String,
      sentryProject: Schema.NullOr(
        Schema.Struct({
          createdAt: Schema.String,
          id: Schema.String,
          sentryInstallationId: Schema.String,
          sentryProjectId: Schema.String,
          sentryProjectSlug: Schema.String,
          updatedAt: Schema.String,
        }),
      ),
      slug: Schema.String,
      suggestedDevDomainName: Schema.String,
      trendScore: Schema.Number,
      updated: Schema.String,
      username: Schema.String,
      users: Schema.NullOr(
        Schema.Array(
          Schema.NullOr(
            Schema.Struct({
              appCount: Schema.Number,
              appetizeCode: Schema.NullOr(Schema.String),
              bestContactEmail: Schema.NullOr(Schema.String),
              created: Schema.String,
              displayName: Schema.String,
              email: Schema.String,
              emailVerified: Schema.Boolean,
              firstName: Schema.NullOr(Schema.String),
              fullName: Schema.NullOr(Schema.String),
              githubUsername: Schema.NullOr(Schema.String),
              hasPassword: Schema.Boolean,
              hasPendingUserInvitations: Schema.Boolean,
              id: Schema.String,
              industry: Schema.NullOr(Schema.String),
              isExpoAdmin: Schema.Boolean,
              isLegacy: Schema.Boolean,
              isSecondFactorAuthenticationEnabled: Schema.Boolean,
              isStaffModeEnabled: Schema.Boolean,
              lastDeletionAttemptTime: Schema.NullOr(Schema.String),
              lastName: Schema.NullOr(Schema.String),
              location: Schema.NullOr(Schema.String),
              newEmailPendingVerification: Schema.NullOr(Schema.String),
              primaryAccountProfileImageUrl: Schema.NullOr(Schema.String),
              profilePhoto: Schema.String,
              twitterUsername: Schema.NullOr(Schema.String),
              username: Schema.String,
            }),
          ),
        ),
      ),
      vexoApp: Schema.NullOr(
        Schema.Struct({
          domain: Schema.NullOr(Schema.String),
          iconUrl: Schema.NullOr(Schema.String),
          id: Schema.String,
          name: Schema.String,
          owner: Schema.String,
          slug: Schema.String,
          vexoIdentifier: Schema.String,
        }),
      ),
      workerCustomDomain: Schema.NullOr(
        Schema.Struct({
          createdAt: Schema.String,
          devDomainName: Schema.Unknown,
          hostname: Schema.String,
          id: Schema.String,
          updatedAt: Schema.String,
        }),
      ),
    }),
    assetHostOverride: Schema.NullOr(Schema.String),
    assetMapUrl: Schema.NullOr(Schema.String),
    awaitingCodeSigningInfo: Schema.Boolean,
    branch: Schema.Struct({
      app: Schema.Struct({
        appStoreUrl: Schema.NullOr(Schema.String),
        assetLimitPerUpdateGroup: Schema.Number,
        buildProfiles: Schema.Array(Schema.String),
        buildsReleaseChannels: Schema.Array(Schema.String),
        description: Schema.String,
        environmentVariableEnvironments: Schema.Array(Schema.Unknown),
        fullName: Schema.String,
        githubUrl: Schema.NullOr(Schema.String),
        iconUrl: Schema.NullOr(Schema.String),
        id: Schema.String,
        internalDistributionBuildPrivacy: Schema.Literals([
          "PRIVATE",
          "PUBLIC",
        ]),
        isDeleting: Schema.Boolean,
        isDeprecated: Schema.Boolean,
        isLikedByMe: Schema.Boolean,
        lastDeletionAttemptTime: Schema.NullOr(Schema.String),
        lastPublishedTime: Schema.String,
        latestActivity: Schema.String,
        latestReleaseId: Schema.String,
        likeCount: Schema.Number,
        name: Schema.String,
        packageName: Schema.String,
        packageUsername: Schema.String,
        playStoreUrl: Schema.NullOr(Schema.String),
        privacy: Schema.String,
        privacySetting: Schema.Literals(["HIDDEN", "PUBLIC", "UNLISTED"]),
        published: Schema.Boolean,
        pushSecurityEnabled: Schema.Boolean,
        releaseChannels: Schema.Array(Schema.String),
        requiresAccessTokenForPushSecurity: Schema.Boolean,
        resourceClassExperiment: Schema.NullOr(Schema.Literals(["C3D", "N2"])),
        scopeKey: Schema.String,
        sdkVersion: Schema.String,
        slug: Schema.String,
        suggestedDevDomainName: Schema.String,
        trendScore: Schema.Number,
        updated: Schema.String,
        username: Schema.String,
      }),
      appId: Schema.String,
      createdAt: Schema.String,
      id: Schema.String,
      lastDeletionAttemptTime: Schema.NullOr(Schema.String),
      latestActivity: Schema.String,
      name: Schema.String,
      updatedAt: Schema.String,
    }),
    branchId: Schema.String,
    codeSigningInfo: Schema.NullOr(
      Schema.Struct({
        alg: Schema.String,
        keyid: Schema.String,
        sig: Schema.String,
      }),
    ),
    createdAt: Schema.String,
    environment: Schema.NullOr(Schema.Unknown),
    expoGoSDKVersion: Schema.NullOr(Schema.String),
    fingerprint: Schema.NullOr(
      Schema.Struct({
        app: Schema.Struct({
          appStoreUrl: Schema.NullOr(Schema.String),
          assetLimitPerUpdateGroup: Schema.Number,
          buildProfiles: Schema.Array(Schema.String),
          buildsReleaseChannels: Schema.Array(Schema.String),
          description: Schema.String,
          environmentVariableEnvironments: Schema.Array(Schema.Unknown),
          fullName: Schema.String,
          githubUrl: Schema.NullOr(Schema.String),
          iconUrl: Schema.NullOr(Schema.String),
          id: Schema.String,
          internalDistributionBuildPrivacy: Schema.Literals([
            "PRIVATE",
            "PUBLIC",
          ]),
          isDeleting: Schema.Boolean,
          isDeprecated: Schema.Boolean,
          isLikedByMe: Schema.Boolean,
          lastDeletionAttemptTime: Schema.NullOr(Schema.String),
          lastPublishedTime: Schema.String,
          latestActivity: Schema.String,
          latestReleaseId: Schema.String,
          likeCount: Schema.Number,
          name: Schema.String,
          packageName: Schema.String,
          packageUsername: Schema.String,
          playStoreUrl: Schema.NullOr(Schema.String),
          privacy: Schema.String,
          privacySetting: Schema.Literals(["HIDDEN", "PUBLIC", "UNLISTED"]),
          published: Schema.Boolean,
          pushSecurityEnabled: Schema.Boolean,
          releaseChannels: Schema.Array(Schema.String),
          requiresAccessTokenForPushSecurity: Schema.Boolean,
          resourceClassExperiment: Schema.NullOr(
            Schema.Literals(["C3D", "N2"]),
          ),
          scopeKey: Schema.String,
          sdkVersion: Schema.String,
          slug: Schema.String,
          suggestedDevDomainName: Schema.String,
          trendScore: Schema.Number,
          updated: Schema.String,
          username: Schema.String,
        }),
        buildCount: Schema.Number,
        createdAt: Schema.String,
        debugInfoUrl: Schema.NullOr(Schema.String),
        hash: Schema.String,
        id: Schema.String,
        source: Schema.NullOr(
          Schema.Struct({
            bucketKey: Schema.String,
            isDebugFingerprint: Schema.NullOr(Schema.Boolean),
            type: Schema.Literals(["GCS"]),
          }),
        ),
        updateCount: Schema.Number,
        updatedAt: Schema.String,
      }),
    ),
    gitCommitHash: Schema.NullOr(Schema.String),
    group: Schema.String,
    id: Schema.String,
    insights: Schema.Struct({
      averageAssetMetrics: Schema.Array(
        Schema.Struct({
          averageDownloadSizeBytes: Schema.Number,
          baseUpdateDownloadUrl: Schema.NullOr(Schema.String),
          baseUpdateId: Schema.NullOr(Schema.String),
          count: Schema.Number,
          storageKey: Schema.String,
        }),
      ),
      cumulativeAverageMetrics: Schema.Struct({
        averageUpdatePayloadBytes: Schema.Number,
        launchAssetCount: Schema.Number,
      }),
      id: Schema.String,
      sizeBreakdownByCategory: Schema.Array(
        Schema.Struct({
          assetCount: Schema.Number,
          category: Schema.String,
          totalBytes: Schema.Number,
        }),
      ),
    }),
    isGitWorkingTreeDirty: Schema.Boolean,
    isRollBackToEmbedded: Schema.Boolean,
    jobRun: Schema.NullOr(
      Schema.Struct({
        app: Schema.Struct({
          appStoreUrl: Schema.NullOr(Schema.String),
          assetLimitPerUpdateGroup: Schema.Number,
          buildProfiles: Schema.Array(Schema.String),
          buildsReleaseChannels: Schema.Array(Schema.String),
          description: Schema.String,
          environmentVariableEnvironments: Schema.Array(Schema.Unknown),
          fullName: Schema.String,
          githubUrl: Schema.NullOr(Schema.String),
          iconUrl: Schema.NullOr(Schema.String),
          id: Schema.String,
          internalDistributionBuildPrivacy: Schema.Literals([
            "PRIVATE",
            "PUBLIC",
          ]),
          isDeleting: Schema.Boolean,
          isDeprecated: Schema.Boolean,
          isLikedByMe: Schema.Boolean,
          lastDeletionAttemptTime: Schema.NullOr(Schema.String),
          lastPublishedTime: Schema.String,
          latestActivity: Schema.String,
          latestReleaseId: Schema.String,
          likeCount: Schema.Number,
          name: Schema.String,
          packageName: Schema.String,
          packageUsername: Schema.String,
          playStoreUrl: Schema.NullOr(Schema.String),
          privacy: Schema.String,
          privacySetting: Schema.Literals(["HIDDEN", "PUBLIC", "UNLISTED"]),
          published: Schema.Boolean,
          pushSecurityEnabled: Schema.Boolean,
          releaseChannels: Schema.Array(Schema.String),
          requiresAccessTokenForPushSecurity: Schema.Boolean,
          resourceClassExperiment: Schema.NullOr(
            Schema.Literals(["C3D", "N2"]),
          ),
          scopeKey: Schema.String,
          sdkVersion: Schema.String,
          slug: Schema.String,
          suggestedDevDomainName: Schema.String,
          trendScore: Schema.Number,
          updated: Schema.String,
          username: Schema.String,
        }),
        artifacts: Schema.Array(
          Schema.Struct({
            contentType: Schema.NullOr(Schema.String),
            createdAt: Schema.String,
            downloadUrl: Schema.NullOr(Schema.String),
            fileSizeBytes: Schema.NullOr(Schema.Number),
            filename: Schema.String,
            id: Schema.String,
            name: Schema.String,
            storageType: Schema.Literals(["GCS", "R2"]),
            updatedAt: Schema.String,
          }),
        ),
        createdAt: Schema.String,
        displayName: Schema.NullOr(Schema.String),
        endedAt: Schema.NullOr(Schema.String),
        errors: Schema.Array(
          Schema.Struct({
            buildPhase: Schema.NullOr(Schema.String),
            docsUrl: Schema.NullOr(Schema.String),
            errorCode: Schema.String,
            message: Schema.String,
          }),
        ),
        expiresAt: Schema.String,
        gitCommitHash: Schema.NullOr(Schema.String),
        gitCommitMessage: Schema.NullOr(Schema.String),
        gitRef: Schema.NullOr(Schema.String),
        id: Schema.String,
        initiatingActor: Schema.NullOr(
          Schema.Struct({
            created: Schema.String,
            displayName: Schema.String,
            firstName: Schema.NullOr(Schema.String),
            id: Schema.String,
            isExpoAdmin: Schema.Boolean,
            lastDeletionAttemptTime: Schema.NullOr(Schema.String),
          }),
        ),
        isWaived: Schema.Boolean,
        logFileUrls: Schema.Array(Schema.String),
        name: Schema.String,
        priority: Schema.Literals(["HIGH", "NORMAL"]),
        startedAt: Schema.NullOr(Schema.String),
        status: Schema.Literals([
          "CANCELED",
          "ERRORED",
          "FINISHED",
          "IN_PROGRESS",
          "IN_QUEUE",
          "NEW",
          "PENDING_CANCEL",
        ]),
        updateGroups: Schema.Array(Schema.Array(Schema.Unknown)),
      }),
    ),
    manifestFragment: Schema.String,
    manifestHostOverride: Schema.NullOr(Schema.String),
    manifestPermalink: Schema.String,
    message: Schema.NullOr(Schema.String),
    platform: Schema.String,
    rolloutPercentage: Schema.NullOr(Schema.Number),
    runtime: Schema.Struct({
      app: Schema.Struct({
        appStoreUrl: Schema.NullOr(Schema.String),
        assetLimitPerUpdateGroup: Schema.Number,
        buildProfiles: Schema.Array(Schema.String),
        buildsReleaseChannels: Schema.Array(Schema.String),
        description: Schema.String,
        environmentVariableEnvironments: Schema.Array(Schema.Unknown),
        fullName: Schema.String,
        githubUrl: Schema.NullOr(Schema.String),
        iconUrl: Schema.NullOr(Schema.String),
        id: Schema.String,
        internalDistributionBuildPrivacy: Schema.Literals([
          "PRIVATE",
          "PUBLIC",
        ]),
        isDeleting: Schema.Boolean,
        isDeprecated: Schema.Boolean,
        isLikedByMe: Schema.Boolean,
        lastDeletionAttemptTime: Schema.NullOr(Schema.String),
        lastPublishedTime: Schema.String,
        latestActivity: Schema.String,
        latestReleaseId: Schema.String,
        likeCount: Schema.Number,
        name: Schema.String,
        packageName: Schema.String,
        packageUsername: Schema.String,
        playStoreUrl: Schema.NullOr(Schema.String),
        privacy: Schema.String,
        privacySetting: Schema.Literals(["HIDDEN", "PUBLIC", "UNLISTED"]),
        published: Schema.Boolean,
        pushSecurityEnabled: Schema.Boolean,
        releaseChannels: Schema.Array(Schema.String),
        requiresAccessTokenForPushSecurity: Schema.Boolean,
        resourceClassExperiment: Schema.NullOr(Schema.Literals(["C3D", "N2"])),
        scopeKey: Schema.String,
        sdkVersion: Schema.String,
        slug: Schema.String,
        suggestedDevDomainName: Schema.String,
        trendScore: Schema.Number,
        updated: Schema.String,
        username: Schema.String,
      }),
      createdAt: Schema.String,
      fingerprint: Schema.NullOr(
        Schema.Struct({
          buildCount: Schema.Number,
          createdAt: Schema.String,
          debugInfoUrl: Schema.NullOr(Schema.String),
          hash: Schema.String,
          id: Schema.String,
          updateCount: Schema.Number,
          updatedAt: Schema.String,
        }),
      ),
      firstBuildCreatedAt: Schema.NullOr(Schema.String),
      id: Schema.String,
      isFingerprint: Schema.Boolean,
      updatedAt: Schema.String,
      version: Schema.String,
    }),
    runtimeVersion: Schema.String,
    updatedAt: Schema.String,
    workflowJob: Schema.NullOr(
      Schema.Struct({
        allDeviceTestCaseResults: Schema.Array(
          Schema.Struct({
            createdAt: Schema.String,
            duration: Schema.NullOr(Schema.Number),
            errorMessage: Schema.NullOr(Schema.String),
            id: Schema.String,
            name: Schema.String,
            path: Schema.String,
            properties: Schema.NullOr(Schema.Unknown),
            retryCount: Schema.NullOr(Schema.Number),
            status: Schema.Literals(["FAILED", "PASSED"]),
            tags: Schema.NullOr(Schema.Array(Schema.String)),
            updatedAt: Schema.String,
          }),
        ),
        approvals: Schema.Array(
          Schema.Struct({
            createdAt: Schema.String,
            decision: Schema.Literals(["APPROVED", "REJECTED"]),
            id: Schema.String,
            updatedAt: Schema.String,
          }),
        ),
        createdAt: Schema.String,
        credentialsAppleDeviceRegistrationRequest: Schema.NullOr(
          Schema.Struct({
            id: Schema.String,
          }),
        ),
        deviceTestCaseResults: Schema.Array(
          Schema.Struct({
            createdAt: Schema.String,
            duration: Schema.NullOr(Schema.Number),
            errorMessage: Schema.NullOr(Schema.String),
            id: Schema.String,
            name: Schema.String,
            path: Schema.String,
            properties: Schema.NullOr(Schema.Unknown),
            retryCount: Schema.NullOr(Schema.Number),
            status: Schema.Literals(["FAILED", "PASSED"]),
            tags: Schema.NullOr(Schema.Array(Schema.String)),
            updatedAt: Schema.String,
          }),
        ),
        environment: Schema.NullOr(Schema.String),
        errors: Schema.Array(
          Schema.Struct({
            message: Schema.String,
            title: Schema.String,
          }),
        ),
        id: Schema.String,
        key: Schema.String,
        name: Schema.String,
        outputs: Schema.Unknown,
        requiredJobKeys: Schema.Array(Schema.String),
        status: Schema.Literals([
          "ACTION_REQUIRED",
          "CANCELED",
          "FAILURE",
          "IN_PROGRESS",
          "NEW",
          "PENDING_CANCEL",
          "SKIPPED",
          "SUCCESS",
        ]),
        turtleBuild: Schema.NullOr(
          Schema.Struct({
            activityTimestamp: Schema.String,
            appBuildVersion: Schema.NullOr(Schema.String),
            appIdentifier: Schema.NullOr(Schema.String),
            appVersion: Schema.NullOr(Schema.String),
            buildMode: Schema.NullOr(
              Schema.Literals(["BUILD", "CUSTOM", "LOCAL", "REPACK", "RESIGN"]),
            ),
            buildProfile: Schema.NullOr(Schema.String),
            channel: Schema.NullOr(Schema.String),
            cliVersion: Schema.NullOr(Schema.String),
            completedAt: Schema.NullOr(Schema.String),
            createdAt: Schema.String,
            customNodeVersion: Schema.NullOr(Schema.String),
            customWorkflowName: Schema.NullOr(Schema.String),
            developmentClient: Schema.NullOr(Schema.Boolean),
            distribution: Schema.NullOr(
              Schema.Literals(["INTERNAL", "SIMULATOR", "STORE"]),
            ),
            enqueuedAt: Schema.NullOr(Schema.String),
            estimatedWaitTimeLeftSeconds: Schema.NullOr(Schema.Number),
            expirationDate: Schema.NullOr(Schema.String),
            gitCommitHash: Schema.NullOr(Schema.String),
            gitCommitMessage: Schema.NullOr(Schema.String),
            gitRef: Schema.NullOr(Schema.String),
            githubRepositoryOwnerAndName: Schema.NullOr(Schema.String),
            id: Schema.String,
            initialQueuePosition: Schema.NullOr(Schema.Number),
            iosEnterpriseProvisioning: Schema.NullOr(
              Schema.Literals(["ADHOC", "UNIVERSAL"]),
            ),
            isForIosSimulator: Schema.Boolean,
            isGitWorkingTreeDirty: Schema.NullOr(Schema.Boolean),
            isWaived: Schema.Boolean,
            logFiles: Schema.Array(Schema.String),
            maxBuildTimeSeconds: Schema.Number,
            maxRetryTimeMinutes: Schema.NullOr(Schema.Number),
            message: Schema.NullOr(Schema.String),
            platform: Schema.Literals(["ANDROID", "IOS"]),
            priority: Schema.Literals(["HIGH", "NORMAL", "NORMAL_PLUS"]),
            projectMetadataFileUrl: Schema.NullOr(Schema.String),
            projectRootDirectory: Schema.NullOr(Schema.String),
            provisioningStartedAt: Schema.NullOr(Schema.String),
            queuePosition: Schema.NullOr(Schema.Number),
            reactNativeVersion: Schema.NullOr(Schema.String),
            releaseChannel: Schema.NullOr(Schema.String),
            requiredPackageManager: Schema.NullOr(Schema.String),
            resolvedEnvironment: Schema.NullOr(Schema.Unknown),
            resourceClass: Schema.Literals([
              "ANDROID_DEFAULT",
              "ANDROID_LARGE",
              "ANDROID_MEDIUM",
              "IOS_DEFAULT",
              "IOS_INTEL_LARGE",
              "IOS_INTEL_MEDIUM",
              "IOS_LARGE",
              "IOS_M1_LARGE",
              "IOS_M1_MEDIUM",
              "IOS_MEDIUM",
              "IOS_M_LARGE",
              "IOS_M_MEDIUM",
              "LEGACY",
              "LINUX_LARGE",
              "LINUX_MEDIUM",
            ]),
            resourceClassDisplayName: Schema.String,
            runFromCI: Schema.NullOr(Schema.Boolean),
            runtimeVersion: Schema.NullOr(Schema.String),
            sdkVersion: Schema.NullOr(Schema.String),
            selectedImage: Schema.NullOr(Schema.String),
            status: Schema.Literals([
              "CANCELED",
              "ERRORED",
              "FINISHED",
              "IN_PROGRESS",
              "IN_QUEUE",
              "NEW",
              "PENDING_CANCEL",
            ]),
            updatedAt: Schema.String,
            waiverType: Schema.NullOr(
              Schema.Literals(["FAST_FAILED_BUILD", "SYSTEM_ERROR"]),
            ),
            workerStartedAt: Schema.NullOr(Schema.String),
          }),
        ),
        turtleJobRun: Schema.NullOr(
          Schema.Struct({
            createdAt: Schema.String,
            displayName: Schema.NullOr(Schema.String),
            endedAt: Schema.NullOr(Schema.String),
            expiresAt: Schema.String,
            gitCommitHash: Schema.NullOr(Schema.String),
            gitCommitMessage: Schema.NullOr(Schema.String),
            gitRef: Schema.NullOr(Schema.String),
            id: Schema.String,
            isWaived: Schema.Boolean,
            logFileUrls: Schema.Array(Schema.String),
            name: Schema.String,
            priority: Schema.Literals(["HIGH", "NORMAL"]),
            startedAt: Schema.NullOr(Schema.String),
            status: Schema.Literals([
              "CANCELED",
              "ERRORED",
              "FINISHED",
              "IN_PROGRESS",
              "IN_QUEUE",
              "NEW",
              "PENDING_CANCEL",
            ]),
            updateGroups: Schema.Array(Schema.Array(Schema.Unknown)),
          }),
        ),
        turtleSubmission: Schema.NullOr(
          Schema.Struct({
            activityTimestamp: Schema.String,
            archiveUrl: Schema.NullOr(Schema.String),
            canRetry: Schema.Boolean,
            completedAt: Schema.NullOr(Schema.String),
            createdAt: Schema.String,
            id: Schema.String,
            logFiles: Schema.Array(Schema.String),
            logsUrl: Schema.NullOr(Schema.String),
            maxRetryTimeMinutes: Schema.Number,
            platform: Schema.Literals(["ANDROID", "IOS"]),
            priority: Schema.NullOr(Schema.Literals(["HIGH", "NORMAL"])),
            status: Schema.Literals([
              "AWAITING_BUILD",
              "CANCELED",
              "ERRORED",
              "FINISHED",
              "IN_PROGRESS",
              "IN_QUEUE",
            ]),
            updatedAt: Schema.String,
          }),
        ),
        type: Schema.Literals([
          "APPLE_DEVICE_REGISTRATION_REQUEST",
          "BUILD",
          "CUSTOM",
          "DEPLOY",
          "DOC",
          "FINGERPRINT",
          "GET_BUILD",
          "GITHUB_COMMENT",
          "MAESTRO_CLOUD",
          "MAESTRO_TEST",
          "REPACK",
          "REQUIRE_APPROVAL",
          "SLACK",
          "SUBMISSION",
          "TESTFLIGHT",
          "UPDATE",
        ]),
        updatedAt: Schema.String,
        workflowRun: Schema.Struct({
          activityTimestamp: Schema.String,
          createdAt: Schema.String,
          durationSeconds: Schema.NullOr(Schema.Number),
          finalizedAt: Schema.NullOr(Schema.String),
          gitCommitHash: Schema.NullOr(Schema.String),
          gitCommitMessage: Schema.NullOr(Schema.String),
          id: Schema.String,
          inputs: Schema.NullOr(Schema.Unknown),
          name: Schema.String,
          pullRequestNumber: Schema.NullOr(Schema.Number),
          requestedGitRef: Schema.NullOr(Schema.String),
          sourceExpiresAt: Schema.NullOr(Schema.String),
          status: Schema.Literals([
            "ACTION_REQUIRED",
            "CANCELED",
            "FAILURE",
            "IN_PROGRESS",
            "NEW",
            "SUCCESS",
          ]),
          triggerEventType: Schema.Literals([
            "APP_STORE_CONNECT_APP_VERSION_STATE_CHANGED",
            "APP_STORE_CONNECT_BETA_FEEDBACK_SUBMITTED",
            "APP_STORE_CONNECT_BUILD_UPLOAD_STATE_CHANGED",
            "APP_STORE_CONNECT_EXTERNAL_BETA_STATE_CHANGED",
            "EAS_SUBMIT",
            "EXPO_LAUNCH",
            "GITHUB_PULL_REQUEST_LABELED",
            "GITHUB_PULL_REQUEST_OPENED",
            "GITHUB_PULL_REQUEST_READY_FOR_REVIEW",
            "GITHUB_PULL_REQUEST_REOPENED",
            "GITHUB_PULL_REQUEST_SYNCHRONIZE",
            "GITHUB_PUSH",
            "MANUAL",
            "REPACK_EXPO_GO",
            "SCHEDULE",
          ]),
          triggeringLabelName: Schema.NullOr(Schema.String),
          triggeringSchedule: Schema.NullOr(Schema.String),
          updatedAt: Schema.String,
        }),
      }),
    ),
  }),
).pipe(T.ResponsePath("updateBranch.publishUpdateGroups"));
export type UpdateBranchPublishUpdateGroupsOutput =
  typeof UpdateBranchPublishUpdateGroupsOutput.Type;

export const updateBranchPublishUpdateGroups = API.make(() => ({
  inputSchema: UpdateBranchPublishUpdateGroupsInput,
  outputSchema: UpdateBranchPublishUpdateGroupsOutput,
}));
