import * as Schema from "effect/Schema";
import { API } from "../client";
import * as T from "../traits";
import { SensitiveNullableString } from "../sensitive";

// Input Schema
export const V1UpdateAuthServiceConfigInput =
  /*@__PURE__*/ /*#__PURE__*/ Schema.Struct({
    ref: Schema.String.pipe(T.PathParam()),
    site_url: Schema.optional(Schema.NullOr(Schema.String)),
    disable_signup: Schema.optional(Schema.NullOr(Schema.Boolean)),
    jwt_exp: Schema.optional(Schema.NullOr(Schema.Number)),
    smtp_admin_email: Schema.optional(Schema.NullOr(Schema.String)),
    smtp_host: Schema.optional(Schema.NullOr(Schema.String)),
    smtp_port: Schema.optional(Schema.NullOr(Schema.String)),
    smtp_user: Schema.optional(Schema.NullOr(Schema.String)),
    smtp_pass: Schema.optional(Schema.NullOr(Schema.String)),
    smtp_max_frequency: Schema.optional(Schema.NullOr(Schema.Number)),
    smtp_sender_name: Schema.optional(Schema.NullOr(Schema.String)),
    mailer_allow_unverified_email_sign_ins: Schema.optional(
      Schema.NullOr(Schema.Boolean),
    ),
    mailer_autoconfirm: Schema.optional(Schema.NullOr(Schema.Boolean)),
    mailer_subjects_invite: Schema.optional(Schema.NullOr(Schema.String)),
    mailer_subjects_confirmation: Schema.optional(Schema.NullOr(Schema.String)),
    mailer_subjects_recovery: Schema.optional(Schema.NullOr(Schema.String)),
    mailer_subjects_email_change: Schema.optional(Schema.NullOr(Schema.String)),
    mailer_subjects_magic_link: Schema.optional(Schema.NullOr(Schema.String)),
    mailer_subjects_reauthentication: Schema.optional(
      Schema.NullOr(Schema.String),
    ),
    mailer_subjects_password_changed_notification: Schema.optional(
      SensitiveNullableString,
    ),
    mailer_subjects_email_changed_notification: Schema.optional(
      Schema.NullOr(Schema.String),
    ),
    mailer_subjects_phone_changed_notification: Schema.optional(
      Schema.NullOr(Schema.String),
    ),
    mailer_subjects_mfa_factor_enrolled_notification: Schema.optional(
      Schema.NullOr(Schema.String),
    ),
    mailer_subjects_mfa_factor_unenrolled_notification: Schema.optional(
      Schema.NullOr(Schema.String),
    ),
    mailer_subjects_identity_linked_notification: Schema.optional(
      Schema.NullOr(Schema.String),
    ),
    mailer_subjects_identity_unlinked_notification: Schema.optional(
      Schema.NullOr(Schema.String),
    ),
    mailer_templates_invite_content: Schema.optional(
      Schema.NullOr(Schema.String),
    ),
    mailer_templates_confirmation_content: Schema.optional(
      Schema.NullOr(Schema.String),
    ),
    mailer_templates_recovery_content: Schema.optional(
      Schema.NullOr(Schema.String),
    ),
    mailer_templates_email_change_content: Schema.optional(
      Schema.NullOr(Schema.String),
    ),
    mailer_templates_magic_link_content: Schema.optional(
      Schema.NullOr(Schema.String),
    ),
    mailer_templates_reauthentication_content: Schema.optional(
      Schema.NullOr(Schema.String),
    ),
    mailer_templates_password_changed_notification_content: Schema.optional(
      SensitiveNullableString,
    ),
    mailer_templates_email_changed_notification_content: Schema.optional(
      Schema.NullOr(Schema.String),
    ),
    mailer_templates_phone_changed_notification_content: Schema.optional(
      Schema.NullOr(Schema.String),
    ),
    mailer_templates_mfa_factor_enrolled_notification_content: Schema.optional(
      Schema.NullOr(Schema.String),
    ),
    mailer_templates_mfa_factor_unenrolled_notification_content:
      Schema.optional(Schema.NullOr(Schema.String)),
    mailer_templates_identity_linked_notification_content: Schema.optional(
      Schema.NullOr(Schema.String),
    ),
    mailer_templates_identity_unlinked_notification_content: Schema.optional(
      Schema.NullOr(Schema.String),
    ),
    mailer_notifications_password_changed_enabled: Schema.optional(
      Schema.NullOr(Schema.Boolean),
    ),
    mailer_notifications_email_changed_enabled: Schema.optional(
      Schema.NullOr(Schema.Boolean),
    ),
    mailer_notifications_phone_changed_enabled: Schema.optional(
      Schema.NullOr(Schema.Boolean),
    ),
    mailer_notifications_mfa_factor_enrolled_enabled: Schema.optional(
      Schema.NullOr(Schema.Boolean),
    ),
    mailer_notifications_mfa_factor_unenrolled_enabled: Schema.optional(
      Schema.NullOr(Schema.Boolean),
    ),
    mailer_notifications_identity_linked_enabled: Schema.optional(
      Schema.NullOr(Schema.Boolean),
    ),
    mailer_notifications_identity_unlinked_enabled: Schema.optional(
      Schema.NullOr(Schema.Boolean),
    ),
    mfa_max_enrolled_factors: Schema.optional(Schema.NullOr(Schema.Number)),
    uri_allow_list: Schema.optional(Schema.NullOr(Schema.String)),
    external_anonymous_users_enabled: Schema.optional(
      Schema.NullOr(Schema.Boolean),
    ),
    external_email_enabled: Schema.optional(Schema.NullOr(Schema.Boolean)),
    external_phone_enabled: Schema.optional(Schema.NullOr(Schema.Boolean)),
    saml_enabled: Schema.optional(Schema.NullOr(Schema.Boolean)),
    saml_external_url: Schema.optional(Schema.NullOr(Schema.String)),
    security_sb_forwarded_for_enabled: Schema.optional(
      Schema.NullOr(Schema.Boolean),
    ),
    security_captcha_enabled: Schema.optional(Schema.NullOr(Schema.Boolean)),
    security_captcha_provider: Schema.optional(
      Schema.NullOr(Schema.Literals(["turnstile", "hcaptcha"])),
    ),
    security_captcha_secret: Schema.optional(SensitiveNullableString),
    sessions_timebox: Schema.optional(Schema.NullOr(Schema.Number)),
    sessions_inactivity_timeout: Schema.optional(Schema.NullOr(Schema.Number)),
    sessions_single_per_user: Schema.optional(Schema.NullOr(Schema.Boolean)),
    sessions_tags: Schema.optional(Schema.NullOr(Schema.String)),
    rate_limit_anonymous_users: Schema.optional(Schema.NullOr(Schema.Number)),
    rate_limit_email_sent: Schema.optional(Schema.NullOr(Schema.Number)),
    rate_limit_sms_sent: Schema.optional(Schema.NullOr(Schema.Number)),
    rate_limit_verify: Schema.optional(Schema.NullOr(Schema.Number)),
    rate_limit_token_refresh: Schema.optional(Schema.NullOr(Schema.Number)),
    rate_limit_otp: Schema.optional(Schema.NullOr(Schema.Number)),
    rate_limit_web3: Schema.optional(Schema.NullOr(Schema.Number)),
    mailer_secure_email_change_enabled: Schema.optional(
      Schema.NullOr(Schema.Boolean),
    ),
    refresh_token_rotation_enabled: Schema.optional(
      Schema.NullOr(Schema.Boolean),
    ),
    password_hibp_enabled: Schema.optional(Schema.NullOr(Schema.Boolean)),
    password_min_length: Schema.optional(Schema.NullOr(Schema.Number)),
    password_required_characters: Schema.optional(
      Schema.NullOr(
        Schema.Literals([
          "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ:0123456789",
          "abcdefghijklmnopqrstuvwxyz:ABCDEFGHIJKLMNOPQRSTUVWXYZ:0123456789",
          "abcdefghijklmnopqrstuvwxyz:ABCDEFGHIJKLMNOPQRSTUVWXYZ:0123456789:!@#$%^&*()_+-=[]{};'\\\\:\"|<>?,./`~",
          "",
        ]),
      ),
    ),
    security_manual_linking_enabled: Schema.optional(
      Schema.NullOr(Schema.Boolean),
    ),
    security_update_password_require_reauthentication: Schema.optional(
      Schema.NullOr(Schema.Boolean),
    ),
    security_refresh_token_reuse_interval: Schema.optional(
      Schema.NullOr(Schema.Number),
    ),
    mailer_otp_exp: Schema.optional(Schema.Number),
    mailer_otp_length: Schema.optional(Schema.NullOr(Schema.Number)),
    sms_autoconfirm: Schema.optional(Schema.NullOr(Schema.Boolean)),
    sms_max_frequency: Schema.optional(Schema.NullOr(Schema.Number)),
    sms_otp_exp: Schema.optional(Schema.NullOr(Schema.Number)),
    sms_otp_length: Schema.optional(Schema.Number),
    sms_provider: Schema.optional(
      Schema.NullOr(
        Schema.Literals([
          "messagebird",
          "textlocal",
          "twilio",
          "twilio_verify",
          "vonage",
        ]),
      ),
    ),
    sms_messagebird_access_key: Schema.optional(Schema.NullOr(Schema.String)),
    sms_messagebird_originator: Schema.optional(Schema.NullOr(Schema.String)),
    sms_test_otp: Schema.optional(Schema.NullOr(Schema.String)),
    sms_test_otp_valid_until: Schema.optional(Schema.NullOr(Schema.String)),
    sms_textlocal_api_key: Schema.optional(Schema.NullOr(Schema.String)),
    sms_textlocal_sender: Schema.optional(Schema.NullOr(Schema.String)),
    sms_twilio_account_sid: Schema.optional(Schema.NullOr(Schema.String)),
    sms_twilio_auth_token: Schema.optional(Schema.NullOr(Schema.String)),
    sms_twilio_content_sid: Schema.optional(Schema.NullOr(Schema.String)),
    sms_twilio_message_service_sid: Schema.optional(
      Schema.NullOr(Schema.String),
    ),
    sms_twilio_verify_account_sid: Schema.optional(
      Schema.NullOr(Schema.String),
    ),
    sms_twilio_verify_auth_token: Schema.optional(Schema.NullOr(Schema.String)),
    sms_twilio_verify_message_service_sid: Schema.optional(
      Schema.NullOr(Schema.String),
    ),
    sms_vonage_api_key: Schema.optional(Schema.NullOr(Schema.String)),
    sms_vonage_api_secret: Schema.optional(SensitiveNullableString),
    sms_vonage_from: Schema.optional(Schema.NullOr(Schema.String)),
    sms_template: Schema.optional(Schema.NullOr(Schema.String)),
    hook_mfa_verification_attempt_enabled: Schema.optional(
      Schema.NullOr(Schema.Boolean),
    ),
    hook_mfa_verification_attempt_uri: Schema.optional(
      Schema.NullOr(Schema.String),
    ),
    hook_mfa_verification_attempt_secrets: Schema.optional(
      Schema.NullOr(Schema.String),
    ),
    hook_password_verification_attempt_enabled: Schema.optional(
      Schema.NullOr(Schema.Boolean),
    ),
    hook_password_verification_attempt_uri: Schema.optional(
      SensitiveNullableString,
    ),
    hook_password_verification_attempt_secrets: Schema.optional(
      SensitiveNullableString,
    ),
    hook_custom_access_token_enabled: Schema.optional(
      Schema.NullOr(Schema.Boolean),
    ),
    hook_custom_access_token_uri: Schema.optional(Schema.NullOr(Schema.String)),
    hook_custom_access_token_secrets: Schema.optional(
      Schema.NullOr(Schema.String),
    ),
    hook_send_sms_enabled: Schema.optional(Schema.NullOr(Schema.Boolean)),
    hook_send_sms_uri: Schema.optional(Schema.NullOr(Schema.String)),
    hook_send_sms_secrets: Schema.optional(Schema.NullOr(Schema.String)),
    hook_send_email_enabled: Schema.optional(Schema.NullOr(Schema.Boolean)),
    hook_send_email_uri: Schema.optional(Schema.NullOr(Schema.String)),
    hook_send_email_secrets: Schema.optional(Schema.NullOr(Schema.String)),
    hook_before_user_created_enabled: Schema.optional(
      Schema.NullOr(Schema.Boolean),
    ),
    hook_before_user_created_uri: Schema.optional(Schema.NullOr(Schema.String)),
    hook_before_user_created_secrets: Schema.optional(
      Schema.NullOr(Schema.String),
    ),
    hook_after_user_created_enabled: Schema.optional(
      Schema.NullOr(Schema.Boolean),
    ),
    hook_after_user_created_uri: Schema.optional(Schema.NullOr(Schema.String)),
    hook_after_user_created_secrets: Schema.optional(
      Schema.NullOr(Schema.String),
    ),
    external_apple_enabled: Schema.optional(Schema.NullOr(Schema.Boolean)),
    external_apple_client_id: Schema.optional(Schema.NullOr(Schema.String)),
    external_apple_email_optional: Schema.optional(
      Schema.NullOr(Schema.Boolean),
    ),
    external_apple_secret: Schema.optional(SensitiveNullableString),
    external_apple_additional_client_ids: Schema.optional(
      Schema.NullOr(Schema.String),
    ),
    external_azure_enabled: Schema.optional(Schema.NullOr(Schema.Boolean)),
    external_azure_client_id: Schema.optional(Schema.NullOr(Schema.String)),
    external_azure_email_optional: Schema.optional(
      Schema.NullOr(Schema.Boolean),
    ),
    external_azure_secret: Schema.optional(SensitiveNullableString),
    external_azure_url: Schema.optional(Schema.NullOr(Schema.String)),
    external_bitbucket_enabled: Schema.optional(Schema.NullOr(Schema.Boolean)),
    external_bitbucket_client_id: Schema.optional(Schema.NullOr(Schema.String)),
    external_bitbucket_email_optional: Schema.optional(
      Schema.NullOr(Schema.Boolean),
    ),
    external_bitbucket_secret: Schema.optional(SensitiveNullableString),
    external_discord_enabled: Schema.optional(Schema.NullOr(Schema.Boolean)),
    external_discord_client_id: Schema.optional(Schema.NullOr(Schema.String)),
    external_discord_email_optional: Schema.optional(
      Schema.NullOr(Schema.Boolean),
    ),
    external_discord_secret: Schema.optional(SensitiveNullableString),
    external_facebook_enabled: Schema.optional(Schema.NullOr(Schema.Boolean)),
    external_facebook_client_id: Schema.optional(Schema.NullOr(Schema.String)),
    external_facebook_email_optional: Schema.optional(
      Schema.NullOr(Schema.Boolean),
    ),
    external_facebook_secret: Schema.optional(SensitiveNullableString),
    external_figma_enabled: Schema.optional(Schema.NullOr(Schema.Boolean)),
    external_figma_client_id: Schema.optional(Schema.NullOr(Schema.String)),
    external_figma_email_optional: Schema.optional(
      Schema.NullOr(Schema.Boolean),
    ),
    external_figma_secret: Schema.optional(SensitiveNullableString),
    external_github_enabled: Schema.optional(Schema.NullOr(Schema.Boolean)),
    external_github_client_id: Schema.optional(Schema.NullOr(Schema.String)),
    external_github_email_optional: Schema.optional(
      Schema.NullOr(Schema.Boolean),
    ),
    external_github_secret: Schema.optional(SensitiveNullableString),
    external_gitlab_enabled: Schema.optional(Schema.NullOr(Schema.Boolean)),
    external_gitlab_client_id: Schema.optional(Schema.NullOr(Schema.String)),
    external_gitlab_email_optional: Schema.optional(
      Schema.NullOr(Schema.Boolean),
    ),
    external_gitlab_secret: Schema.optional(SensitiveNullableString),
    external_gitlab_url: Schema.optional(Schema.NullOr(Schema.String)),
    external_google_enabled: Schema.optional(Schema.NullOr(Schema.Boolean)),
    external_google_client_id: Schema.optional(Schema.NullOr(Schema.String)),
    external_google_email_optional: Schema.optional(
      Schema.NullOr(Schema.Boolean),
    ),
    external_google_secret: Schema.optional(SensitiveNullableString),
    external_google_additional_client_ids: Schema.optional(
      Schema.NullOr(Schema.String),
    ),
    external_google_skip_nonce_check: Schema.optional(
      Schema.NullOr(Schema.Boolean),
    ),
    external_kakao_enabled: Schema.optional(Schema.NullOr(Schema.Boolean)),
    external_kakao_client_id: Schema.optional(Schema.NullOr(Schema.String)),
    external_kakao_email_optional: Schema.optional(
      Schema.NullOr(Schema.Boolean),
    ),
    external_kakao_secret: Schema.optional(SensitiveNullableString),
    external_keycloak_enabled: Schema.optional(Schema.NullOr(Schema.Boolean)),
    external_keycloak_client_id: Schema.optional(Schema.NullOr(Schema.String)),
    external_keycloak_email_optional: Schema.optional(
      Schema.NullOr(Schema.Boolean),
    ),
    external_keycloak_secret: Schema.optional(SensitiveNullableString),
    external_keycloak_url: Schema.optional(Schema.NullOr(Schema.String)),
    external_linkedin_oidc_enabled: Schema.optional(
      Schema.NullOr(Schema.Boolean),
    ),
    external_linkedin_oidc_client_id: Schema.optional(
      Schema.NullOr(Schema.String),
    ),
    external_linkedin_oidc_email_optional: Schema.optional(
      Schema.NullOr(Schema.Boolean),
    ),
    external_linkedin_oidc_secret: Schema.optional(SensitiveNullableString),
    external_slack_oidc_enabled: Schema.optional(Schema.NullOr(Schema.Boolean)),
    external_slack_oidc_client_id: Schema.optional(
      Schema.NullOr(Schema.String),
    ),
    external_slack_oidc_email_optional: Schema.optional(
      Schema.NullOr(Schema.Boolean),
    ),
    external_slack_oidc_secret: Schema.optional(SensitiveNullableString),
    external_notion_enabled: Schema.optional(Schema.NullOr(Schema.Boolean)),
    external_notion_client_id: Schema.optional(Schema.NullOr(Schema.String)),
    external_notion_email_optional: Schema.optional(
      Schema.NullOr(Schema.Boolean),
    ),
    external_notion_secret: Schema.optional(SensitiveNullableString),
    external_slack_enabled: Schema.optional(Schema.NullOr(Schema.Boolean)),
    external_slack_client_id: Schema.optional(Schema.NullOr(Schema.String)),
    external_slack_email_optional: Schema.optional(
      Schema.NullOr(Schema.Boolean),
    ),
    external_slack_secret: Schema.optional(SensitiveNullableString),
    external_spotify_enabled: Schema.optional(Schema.NullOr(Schema.Boolean)),
    external_spotify_client_id: Schema.optional(Schema.NullOr(Schema.String)),
    external_spotify_email_optional: Schema.optional(
      Schema.NullOr(Schema.Boolean),
    ),
    external_spotify_secret: Schema.optional(SensitiveNullableString),
    external_twitch_enabled: Schema.optional(Schema.NullOr(Schema.Boolean)),
    external_twitch_client_id: Schema.optional(Schema.NullOr(Schema.String)),
    external_twitch_email_optional: Schema.optional(
      Schema.NullOr(Schema.Boolean),
    ),
    external_twitch_secret: Schema.optional(SensitiveNullableString),
    external_twitter_enabled: Schema.optional(Schema.NullOr(Schema.Boolean)),
    external_twitter_client_id: Schema.optional(Schema.NullOr(Schema.String)),
    external_twitter_email_optional: Schema.optional(
      Schema.NullOr(Schema.Boolean),
    ),
    external_twitter_secret: Schema.optional(SensitiveNullableString),
    external_x_enabled: Schema.optional(Schema.NullOr(Schema.Boolean)),
    external_x_client_id: Schema.optional(Schema.NullOr(Schema.String)),
    external_x_email_optional: Schema.optional(Schema.NullOr(Schema.Boolean)),
    external_x_secret: Schema.optional(SensitiveNullableString),
    external_workos_enabled: Schema.optional(Schema.NullOr(Schema.Boolean)),
    external_workos_client_id: Schema.optional(Schema.NullOr(Schema.String)),
    external_workos_secret: Schema.optional(SensitiveNullableString),
    external_workos_url: Schema.optional(Schema.NullOr(Schema.String)),
    external_web3_solana_enabled: Schema.optional(
      Schema.NullOr(Schema.Boolean),
    ),
    external_web3_ethereum_enabled: Schema.optional(
      Schema.NullOr(Schema.Boolean),
    ),
    external_zoom_enabled: Schema.optional(Schema.NullOr(Schema.Boolean)),
    external_zoom_client_id: Schema.optional(Schema.NullOr(Schema.String)),
    external_zoom_email_optional: Schema.optional(
      Schema.NullOr(Schema.Boolean),
    ),
    external_zoom_secret: Schema.optional(SensitiveNullableString),
    db_max_pool_size: Schema.optional(Schema.NullOr(Schema.Number)),
    db_max_pool_size_unit: Schema.optional(
      Schema.NullOr(Schema.Literals(["connections", "percent"])),
    ),
    api_max_request_duration: Schema.optional(Schema.NullOr(Schema.Number)),
    mfa_totp_enroll_enabled: Schema.optional(Schema.NullOr(Schema.Boolean)),
    mfa_totp_verify_enabled: Schema.optional(Schema.NullOr(Schema.Boolean)),
    mfa_web_authn_enroll_enabled: Schema.optional(
      Schema.NullOr(Schema.Boolean),
    ),
    mfa_web_authn_verify_enabled: Schema.optional(
      Schema.NullOr(Schema.Boolean),
    ),
    mfa_phone_enroll_enabled: Schema.optional(Schema.NullOr(Schema.Boolean)),
    mfa_phone_verify_enabled: Schema.optional(Schema.NullOr(Schema.Boolean)),
    mfa_phone_max_frequency: Schema.optional(Schema.NullOr(Schema.Number)),
    mfa_phone_otp_length: Schema.optional(Schema.NullOr(Schema.Number)),
    mfa_phone_template: Schema.optional(Schema.NullOr(Schema.String)),
    nimbus_oauth_client_id: Schema.optional(Schema.NullOr(Schema.String)),
    nimbus_oauth_client_secret: Schema.optional(SensitiveNullableString),
    oauth_server_enabled: Schema.optional(Schema.NullOr(Schema.Boolean)),
    oauth_server_allow_dynamic_registration: Schema.optional(
      Schema.NullOr(Schema.Boolean),
    ),
    oauth_server_authorization_path: Schema.optional(
      Schema.NullOr(Schema.String),
    ),
    custom_oauth_enabled: Schema.optional(Schema.Boolean),
  }).pipe(T.Http({ method: "PATCH", path: "/v1/projects/{ref}/config/auth" }));
export type V1UpdateAuthServiceConfigInput =
  typeof V1UpdateAuthServiceConfigInput.Type;

// Output Schema
export const V1UpdateAuthServiceConfigOutput =
  /*@__PURE__*/ /*#__PURE__*/ Schema.Struct({
    api_max_request_duration: Schema.NullOr(Schema.Number),
    db_max_pool_size: Schema.NullOr(Schema.Number),
    db_max_pool_size_unit: Schema.NullOr(
      Schema.Literals(["connections", "percent"]),
    ),
    disable_signup: Schema.NullOr(Schema.Boolean),
    external_anonymous_users_enabled: Schema.NullOr(Schema.Boolean),
    external_apple_additional_client_ids: Schema.NullOr(Schema.String),
    external_apple_client_id: Schema.NullOr(Schema.String),
    external_apple_email_optional: Schema.NullOr(Schema.Boolean),
    external_apple_enabled: Schema.NullOr(Schema.Boolean),
    external_apple_secret: SensitiveNullableString,
    external_azure_client_id: Schema.NullOr(Schema.String),
    external_azure_email_optional: Schema.NullOr(Schema.Boolean),
    external_azure_enabled: Schema.NullOr(Schema.Boolean),
    external_azure_secret: SensitiveNullableString,
    external_azure_url: Schema.NullOr(Schema.String),
    external_bitbucket_client_id: Schema.NullOr(Schema.String),
    external_bitbucket_email_optional: Schema.NullOr(Schema.Boolean),
    external_bitbucket_enabled: Schema.NullOr(Schema.Boolean),
    external_bitbucket_secret: SensitiveNullableString,
    external_discord_client_id: Schema.NullOr(Schema.String),
    external_discord_email_optional: Schema.NullOr(Schema.Boolean),
    external_discord_enabled: Schema.NullOr(Schema.Boolean),
    external_discord_secret: SensitiveNullableString,
    external_email_enabled: Schema.NullOr(Schema.Boolean),
    external_facebook_client_id: Schema.NullOr(Schema.String),
    external_facebook_email_optional: Schema.NullOr(Schema.Boolean),
    external_facebook_enabled: Schema.NullOr(Schema.Boolean),
    external_facebook_secret: SensitiveNullableString,
    external_figma_client_id: Schema.NullOr(Schema.String),
    external_figma_email_optional: Schema.NullOr(Schema.Boolean),
    external_figma_enabled: Schema.NullOr(Schema.Boolean),
    external_figma_secret: SensitiveNullableString,
    external_github_client_id: Schema.NullOr(Schema.String),
    external_github_email_optional: Schema.NullOr(Schema.Boolean),
    external_github_enabled: Schema.NullOr(Schema.Boolean),
    external_github_secret: SensitiveNullableString,
    external_gitlab_client_id: Schema.NullOr(Schema.String),
    external_gitlab_email_optional: Schema.NullOr(Schema.Boolean),
    external_gitlab_enabled: Schema.NullOr(Schema.Boolean),
    external_gitlab_secret: SensitiveNullableString,
    external_gitlab_url: Schema.NullOr(Schema.String),
    external_google_additional_client_ids: Schema.NullOr(Schema.String),
    external_google_client_id: Schema.NullOr(Schema.String),
    external_google_email_optional: Schema.NullOr(Schema.Boolean),
    external_google_enabled: Schema.NullOr(Schema.Boolean),
    external_google_secret: SensitiveNullableString,
    external_google_skip_nonce_check: Schema.NullOr(Schema.Boolean),
    external_kakao_client_id: Schema.NullOr(Schema.String),
    external_kakao_email_optional: Schema.NullOr(Schema.Boolean),
    external_kakao_enabled: Schema.NullOr(Schema.Boolean),
    external_kakao_secret: SensitiveNullableString,
    external_keycloak_client_id: Schema.NullOr(Schema.String),
    external_keycloak_email_optional: Schema.NullOr(Schema.Boolean),
    external_keycloak_enabled: Schema.NullOr(Schema.Boolean),
    external_keycloak_secret: SensitiveNullableString,
    external_keycloak_url: Schema.NullOr(Schema.String),
    external_linkedin_oidc_client_id: Schema.NullOr(Schema.String),
    external_linkedin_oidc_email_optional: Schema.NullOr(Schema.Boolean),
    external_linkedin_oidc_enabled: Schema.NullOr(Schema.Boolean),
    external_linkedin_oidc_secret: SensitiveNullableString,
    external_slack_oidc_client_id: Schema.NullOr(Schema.String),
    external_slack_oidc_email_optional: Schema.NullOr(Schema.Boolean),
    external_slack_oidc_enabled: Schema.NullOr(Schema.Boolean),
    external_slack_oidc_secret: SensitiveNullableString,
    external_notion_client_id: Schema.NullOr(Schema.String),
    external_notion_email_optional: Schema.NullOr(Schema.Boolean),
    external_notion_enabled: Schema.NullOr(Schema.Boolean),
    external_notion_secret: SensitiveNullableString,
    external_phone_enabled: Schema.NullOr(Schema.Boolean),
    external_slack_client_id: Schema.NullOr(Schema.String),
    external_slack_email_optional: Schema.NullOr(Schema.Boolean),
    external_slack_enabled: Schema.NullOr(Schema.Boolean),
    external_slack_secret: SensitiveNullableString,
    external_spotify_client_id: Schema.NullOr(Schema.String),
    external_spotify_email_optional: Schema.NullOr(Schema.Boolean),
    external_spotify_enabled: Schema.NullOr(Schema.Boolean),
    external_spotify_secret: SensitiveNullableString,
    external_twitch_client_id: Schema.NullOr(Schema.String),
    external_twitch_email_optional: Schema.NullOr(Schema.Boolean),
    external_twitch_enabled: Schema.NullOr(Schema.Boolean),
    external_twitch_secret: SensitiveNullableString,
    external_twitter_client_id: Schema.NullOr(Schema.String),
    external_twitter_email_optional: Schema.NullOr(Schema.Boolean),
    external_twitter_enabled: Schema.NullOr(Schema.Boolean),
    external_twitter_secret: SensitiveNullableString,
    external_x_client_id: Schema.NullOr(Schema.String),
    external_x_email_optional: Schema.NullOr(Schema.Boolean),
    external_x_enabled: Schema.NullOr(Schema.Boolean),
    external_x_secret: SensitiveNullableString,
    external_workos_client_id: Schema.NullOr(Schema.String),
    external_workos_enabled: Schema.NullOr(Schema.Boolean),
    external_workos_secret: SensitiveNullableString,
    external_workos_url: Schema.NullOr(Schema.String),
    external_web3_solana_enabled: Schema.NullOr(Schema.Boolean),
    external_web3_ethereum_enabled: Schema.NullOr(Schema.Boolean),
    external_zoom_client_id: Schema.NullOr(Schema.String),
    external_zoom_email_optional: Schema.NullOr(Schema.Boolean),
    external_zoom_enabled: Schema.NullOr(Schema.Boolean),
    external_zoom_secret: SensitiveNullableString,
    hook_custom_access_token_enabled: Schema.NullOr(Schema.Boolean),
    hook_custom_access_token_uri: Schema.NullOr(Schema.String),
    hook_custom_access_token_secrets: Schema.NullOr(Schema.String),
    hook_mfa_verification_attempt_enabled: Schema.NullOr(Schema.Boolean),
    hook_mfa_verification_attempt_uri: Schema.NullOr(Schema.String),
    hook_mfa_verification_attempt_secrets: Schema.NullOr(Schema.String),
    hook_password_verification_attempt_enabled: Schema.NullOr(Schema.Boolean),
    hook_password_verification_attempt_uri: SensitiveNullableString,
    hook_password_verification_attempt_secrets: SensitiveNullableString,
    hook_send_sms_enabled: Schema.NullOr(Schema.Boolean),
    hook_send_sms_uri: Schema.NullOr(Schema.String),
    hook_send_sms_secrets: Schema.NullOr(Schema.String),
    hook_send_email_enabled: Schema.NullOr(Schema.Boolean),
    hook_send_email_uri: Schema.NullOr(Schema.String),
    hook_send_email_secrets: Schema.NullOr(Schema.String),
    hook_before_user_created_enabled: Schema.NullOr(Schema.Boolean),
    hook_before_user_created_uri: Schema.NullOr(Schema.String),
    hook_before_user_created_secrets: Schema.NullOr(Schema.String),
    hook_after_user_created_enabled: Schema.NullOr(Schema.Boolean),
    hook_after_user_created_uri: Schema.NullOr(Schema.String),
    hook_after_user_created_secrets: Schema.NullOr(Schema.String),
    jwt_exp: Schema.NullOr(Schema.Number),
    mailer_allow_unverified_email_sign_ins: Schema.NullOr(Schema.Boolean),
    mailer_autoconfirm: Schema.NullOr(Schema.Boolean),
    mailer_otp_exp: Schema.Number,
    mailer_otp_length: Schema.NullOr(Schema.Number),
    mailer_secure_email_change_enabled: Schema.NullOr(Schema.Boolean),
    mailer_subjects_confirmation: Schema.NullOr(Schema.String),
    mailer_subjects_email_change: Schema.NullOr(Schema.String),
    mailer_subjects_invite: Schema.NullOr(Schema.String),
    mailer_subjects_magic_link: Schema.NullOr(Schema.String),
    mailer_subjects_reauthentication: Schema.NullOr(Schema.String),
    mailer_subjects_recovery: Schema.NullOr(Schema.String),
    mailer_subjects_password_changed_notification: SensitiveNullableString,
    mailer_subjects_email_changed_notification: Schema.NullOr(Schema.String),
    mailer_subjects_phone_changed_notification: Schema.NullOr(Schema.String),
    mailer_subjects_mfa_factor_enrolled_notification: Schema.NullOr(
      Schema.String,
    ),
    mailer_subjects_mfa_factor_unenrolled_notification: Schema.NullOr(
      Schema.String,
    ),
    mailer_subjects_identity_linked_notification: Schema.NullOr(Schema.String),
    mailer_subjects_identity_unlinked_notification: Schema.NullOr(
      Schema.String,
    ),
    mailer_templates_confirmation_content: Schema.NullOr(Schema.String),
    mailer_templates_email_change_content: Schema.NullOr(Schema.String),
    mailer_templates_invite_content: Schema.NullOr(Schema.String),
    mailer_templates_magic_link_content: Schema.NullOr(Schema.String),
    mailer_templates_reauthentication_content: Schema.NullOr(Schema.String),
    mailer_templates_recovery_content: Schema.NullOr(Schema.String),
    mailer_templates_password_changed_notification_content:
      SensitiveNullableString,
    mailer_templates_email_changed_notification_content: Schema.NullOr(
      Schema.String,
    ),
    mailer_templates_phone_changed_notification_content: Schema.NullOr(
      Schema.String,
    ),
    mailer_templates_mfa_factor_enrolled_notification_content: Schema.NullOr(
      Schema.String,
    ),
    mailer_templates_mfa_factor_unenrolled_notification_content: Schema.NullOr(
      Schema.String,
    ),
    mailer_templates_identity_linked_notification_content: Schema.NullOr(
      Schema.String,
    ),
    mailer_templates_identity_unlinked_notification_content: Schema.NullOr(
      Schema.String,
    ),
    mailer_notifications_password_changed_enabled: Schema.NullOr(
      Schema.Boolean,
    ),
    mailer_notifications_email_changed_enabled: Schema.NullOr(Schema.Boolean),
    mailer_notifications_phone_changed_enabled: Schema.NullOr(Schema.Boolean),
    mailer_notifications_mfa_factor_enrolled_enabled: Schema.NullOr(
      Schema.Boolean,
    ),
    mailer_notifications_mfa_factor_unenrolled_enabled: Schema.NullOr(
      Schema.Boolean,
    ),
    mailer_notifications_identity_linked_enabled: Schema.NullOr(Schema.Boolean),
    mailer_notifications_identity_unlinked_enabled: Schema.NullOr(
      Schema.Boolean,
    ),
    mfa_max_enrolled_factors: Schema.NullOr(Schema.Number),
    mfa_totp_enroll_enabled: Schema.NullOr(Schema.Boolean),
    mfa_totp_verify_enabled: Schema.NullOr(Schema.Boolean),
    mfa_phone_enroll_enabled: Schema.NullOr(Schema.Boolean),
    mfa_phone_verify_enabled: Schema.NullOr(Schema.Boolean),
    mfa_web_authn_enroll_enabled: Schema.NullOr(Schema.Boolean),
    mfa_web_authn_verify_enabled: Schema.NullOr(Schema.Boolean),
    mfa_phone_otp_length: Schema.Number,
    mfa_phone_template: Schema.NullOr(Schema.String),
    mfa_phone_max_frequency: Schema.NullOr(Schema.Number),
    nimbus_oauth_client_id: Schema.NullOr(Schema.String),
    nimbus_oauth_email_optional: Schema.NullOr(Schema.Boolean),
    nimbus_oauth_client_secret: SensitiveNullableString,
    password_hibp_enabled: Schema.NullOr(Schema.Boolean),
    password_min_length: Schema.NullOr(Schema.Number),
    password_required_characters: Schema.NullOr(
      Schema.Literals([
        "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ:0123456789",
        "abcdefghijklmnopqrstuvwxyz:ABCDEFGHIJKLMNOPQRSTUVWXYZ:0123456789",
        "abcdefghijklmnopqrstuvwxyz:ABCDEFGHIJKLMNOPQRSTUVWXYZ:0123456789:!@#$%^&*()_+-=[]{};'\\\\:\"|<>?,./`~",
        "",
      ]),
    ),
    rate_limit_anonymous_users: Schema.NullOr(Schema.Number),
    rate_limit_email_sent: Schema.NullOr(Schema.Number),
    rate_limit_sms_sent: Schema.NullOr(Schema.Number),
    rate_limit_token_refresh: Schema.NullOr(Schema.Number),
    rate_limit_verify: Schema.NullOr(Schema.Number),
    rate_limit_otp: Schema.NullOr(Schema.Number),
    rate_limit_web3: Schema.NullOr(Schema.Number),
    refresh_token_rotation_enabled: Schema.NullOr(Schema.Boolean),
    saml_enabled: Schema.NullOr(Schema.Boolean),
    saml_external_url: Schema.NullOr(Schema.String),
    saml_allow_encrypted_assertions: Schema.NullOr(Schema.Boolean),
    security_sb_forwarded_for_enabled: Schema.NullOr(Schema.Boolean),
    security_captcha_enabled: Schema.NullOr(Schema.Boolean),
    security_captcha_provider: Schema.NullOr(
      Schema.Literals(["turnstile", "hcaptcha"]),
    ),
    security_captcha_secret: SensitiveNullableString,
    security_manual_linking_enabled: Schema.NullOr(Schema.Boolean),
    security_refresh_token_reuse_interval: Schema.NullOr(Schema.Number),
    security_update_password_require_reauthentication: Schema.NullOr(
      Schema.Boolean,
    ),
    sessions_inactivity_timeout: Schema.NullOr(Schema.Number),
    sessions_single_per_user: Schema.NullOr(Schema.Boolean),
    sessions_tags: Schema.NullOr(Schema.String),
    sessions_timebox: Schema.NullOr(Schema.Number),
    site_url: Schema.NullOr(Schema.String),
    sms_autoconfirm: Schema.NullOr(Schema.Boolean),
    sms_max_frequency: Schema.NullOr(Schema.Number),
    sms_messagebird_access_key: Schema.NullOr(Schema.String),
    sms_messagebird_originator: Schema.NullOr(Schema.String),
    sms_otp_exp: Schema.NullOr(Schema.Number),
    sms_otp_length: Schema.Number,
    sms_provider: Schema.NullOr(
      Schema.Literals([
        "messagebird",
        "textlocal",
        "twilio",
        "twilio_verify",
        "vonage",
      ]),
    ),
    sms_template: Schema.NullOr(Schema.String),
    sms_test_otp: Schema.NullOr(Schema.String),
    sms_test_otp_valid_until: Schema.NullOr(Schema.String),
    sms_textlocal_api_key: Schema.NullOr(Schema.String),
    sms_textlocal_sender: Schema.NullOr(Schema.String),
    sms_twilio_account_sid: Schema.NullOr(Schema.String),
    sms_twilio_auth_token: Schema.NullOr(Schema.String),
    sms_twilio_content_sid: Schema.NullOr(Schema.String),
    sms_twilio_message_service_sid: Schema.NullOr(Schema.String),
    sms_twilio_verify_account_sid: Schema.NullOr(Schema.String),
    sms_twilio_verify_auth_token: Schema.NullOr(Schema.String),
    sms_twilio_verify_message_service_sid: Schema.NullOr(Schema.String),
    sms_vonage_api_key: Schema.NullOr(Schema.String),
    sms_vonage_api_secret: SensitiveNullableString,
    sms_vonage_from: Schema.NullOr(Schema.String),
    smtp_admin_email: Schema.NullOr(Schema.String),
    smtp_host: Schema.NullOr(Schema.String),
    smtp_max_frequency: Schema.NullOr(Schema.Number),
    smtp_pass: Schema.NullOr(Schema.String),
    smtp_port: Schema.NullOr(Schema.String),
    smtp_sender_name: Schema.NullOr(Schema.String),
    smtp_user: Schema.NullOr(Schema.String),
    uri_allow_list: Schema.NullOr(Schema.String),
    oauth_server_enabled: Schema.Boolean,
    oauth_server_allow_dynamic_registration: Schema.Boolean,
    oauth_server_authorization_path: Schema.NullOr(Schema.String),
    custom_oauth_enabled: Schema.Boolean,
    custom_oauth_max_providers: Schema.Number,
  });
export type V1UpdateAuthServiceConfigOutput =
  typeof V1UpdateAuthServiceConfigOutput.Type;

// The operation
/**
 * Updates a project's auth config
 *
 * @param ref - Project ref
 */
export const v1UpdateAuthServiceConfig = /*@__PURE__*/ /*#__PURE__*/ API.make(
  () => ({
    inputSchema: V1UpdateAuthServiceConfigInput,
    outputSchema: V1UpdateAuthServiceConfigOutput,
  }),
);
