// AUTO-GENERATED by scripts/generate.ts from .generated-specs. Do not edit.
import * as S from "@distilled.cloud/core/schema";
import * as API from "@distilled.cloud/core/api";
import * as T from "../traits.ts";
import {
  CloudflareProtocol,
  type CloudflareOpError,
  type CloudflareOpContext,
} from "../protocol.ts";
import { CloudflareError, CloudflareRateLimited } from "../errors.ts";
import * as Retry from "../retry.ts";

export type { CloudflareOpError, CloudflareOpContext };

/** Fallback camelCase→wire mapping for opaque content (mined from the distilled SDK). */
const KEY_DICTIONARY: Record<string, string> = {
  actionParameters: "action_parameters",
  botScore: "bot_score",
  isEuCountry: "is_eu_country",
  isoCode: "iso_code",
  plainText: "plain_text",
  postalCode: "postal_code",
  regionCode: "region_code",
  skipChallenge: "skip_challenge",
  skipResponse: "skip_response",
  statusCode: "status_code",
  stepName: "step_name",
  subdivision_2IsoCode: "subdivision_2_iso_code",
  threatScore: "threat_score",
};

export interface TracesCreateRequestBody {
  /** Base64 encoded request body */
  base64?: string | null;
  /** Arbitrary json as request body */
  json?: unknown | null;
  /** Request body as plain text */
  plainText?: string | null;
}
export const TracesCreateRequestBody = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    base64: S.optional(S.NullOr(S.String)),
    json: S.optional(S.NullOr(S.Unknown)),
    plainText: S.optional(S.NullOr(S.String).pipe(T.Body("plain_text"))),
  }),
).annotate({
  identifier: "TracesCreateRequestBody",
}) as any as S.Schema<TracesCreateRequestBody>;

export interface TracesCreateRequestContextGeoloc {
  city?: string | null;
  continent?: string | null;
  isEuCountry?: boolean | null;
  isoCode?: string | null;
  latitude?: number | null;
  longitude?: number | null;
  postalCode?: string | null;
  regionCode?: string | null;
  subdivision_2_iso_code?: string | null;
  timezone?: string | null;
}
export const TracesCreateRequestContextGeoloc = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    city: S.optional(S.NullOr(S.String)),
    continent: S.optional(S.NullOr(S.String)),
    isEuCountry: S.optional(S.NullOr(S.Boolean).pipe(T.Body("is_eu_country"))),
    isoCode: S.optional(S.NullOr(S.String).pipe(T.Body("iso_code"))),
    latitude: S.optional(S.NullOr(S.Number)),
    longitude: S.optional(S.NullOr(S.Number)),
    postalCode: S.optional(S.NullOr(S.String).pipe(T.Body("postal_code"))),
    regionCode: S.optional(S.NullOr(S.String).pipe(T.Body("region_code"))),
    subdivision_2_iso_code: S.optional(S.NullOr(S.String)),
    timezone: S.optional(S.NullOr(S.String)),
  }),
).annotate({
  identifier: "TracesCreateRequestContextGeoloc",
}) as any as S.Schema<TracesCreateRequestContextGeoloc>;

export interface TracesCreateRequestContext {
  /** Bot score used for evaluating tracing request processing */
  botScore?: number | null;
  /** Geodata for tracing request */
  geoloc?: TracesCreateRequestContextGeoloc | null;
  /** Whether to skip any challenges for tracing request (e.g.: captcha) */
  skipChallenge?: boolean | null;
  /** Threat score used for evaluating tracing request processing */
  threatScore?: number | null;
}
export const TracesCreateRequestContext = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    botScore: S.optional(S.NullOr(S.Number).pipe(T.Body("bot_score"))),
    geoloc: S.optional(S.NullOr(TracesCreateRequestContextGeoloc)),
    skipChallenge: S.optional(
      S.NullOr(S.Boolean).pipe(T.Body("skip_challenge")),
    ),
    threatScore: S.optional(S.NullOr(S.Number).pipe(T.Body("threat_score"))),
  }),
).annotate({
  identifier: "TracesCreateRequestContext",
}) as any as S.Schema<TracesCreateRequestContext>;

export type TracesCreateRequestCookiesMap = {
  [key: string]: string | undefined;
};
export const TracesCreateRequestCookiesMap = /*@__PURE__*/ S.Record(
  S.String,
  S.String,
) as any as S.Schema<TracesCreateRequestCookiesMap>;

export type TracesCreateRequestHeadersMap = {
  [key: string]: string | undefined;
};
export const TracesCreateRequestHeadersMap = /*@__PURE__*/ S.Record(
  S.String,
  S.String,
) as any as S.Schema<TracesCreateRequestHeadersMap>;

export interface CreateTraceRequest {
  /** Identifier. */
  accountId: string;
  /** HTTP Method of tracing request */
  method: string;
  /** URL to which perform tracing request */
  url: string;
  body?: TracesCreateRequestBody | null;
  /** Additional request parameters */
  context?: TracesCreateRequestContext | null;
  /** Cookies added to tracing request */
  cookies?: TracesCreateRequestCookiesMap | null;
  /** Headers added to tracing request */
  headers?: TracesCreateRequestHeadersMap | null;
  /** HTTP Protocol of tracing request */
  protocol?: string | null;
  /** Skip sending the request to the Origin server after all rules evaluation */
  skipResponse?: boolean | null;
}
export const CreateTraceRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    accountId: S.String.pipe(T.Label("account_id")),
    method: S.String,
    url: S.String,
    body: S.optional(S.NullOr(TracesCreateRequestBody)),
    context: S.optional(S.NullOr(TracesCreateRequestContext)),
    cookies: S.optional(S.NullOr(TracesCreateRequestCookiesMap)),
    headers: S.optional(S.NullOr(TracesCreateRequestHeadersMap)),
    protocol: S.optional(S.NullOr(S.String)),
    skipResponse: S.optional(S.NullOr(S.Boolean).pipe(T.Body("skip_response"))),
  })
    .pipe(
      T.Http({
        method: "POST",
        uri: "/accounts/{account_id}/request-tracer/trace",
        code: 200,
      }),
    )
    .pipe(T.KeyDictionary(KEY_DICTIONARY)),
).annotate({
  identifier: "CreateTraceRequest",
}) as any as S.Schema<CreateTraceRequest>;

/** Unwrapped `result` payload of the Cloudflare v4 response envelope. */
export interface CreateTraceResponse {
  /** HTTP Status code of zone response */
  statusCode?: number | null;
  trace?: unknown | null;
}
export const CreateTraceResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    statusCode: S.optional(S.NullOr(S.Number).pipe(T.Body("status_code"))),
    trace: S.optional(S.NullOr(S.Unknown)),
  }).pipe(T.KeyDictionary(KEY_DICTIONARY)),
).annotate({
  identifier: "CreateTraceResponse",
}) as any as S.Schema<CreateTraceResponse>;

export type CreateTraceError = CloudflareOpError;
/** Request Trace */
export const createTrace: API.OperationMethod<
  CreateTraceRequest,
  CreateTraceResponse,
  CreateTraceError,
  CloudflareOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CreateTraceRequest,
  output: CreateTraceResponse,
  errors: [CloudflareRateLimited, CloudflareError],
  protocol: CloudflareProtocol,
  retry: Retry.Retry,
}));
