import * as Schema from "effect/Schema";
import {
  AvailableSetupTaskIdsEnumSchema,
  SessionRecordingRetentionPeriodEnumSchema,
  TeamCustomerAnalyticsConfigSchema,
  TeamMarketingAnalyticsConfigSchema,
  TeamRevenueAnalyticsConfigSchema,
  TimezoneEnumSchema,
} from "./_schemas.ts";
import { API } from "../../client.ts";
import * as T from "../../traits.ts";
import { BadRequest, Forbidden, NotFound } from "../../errors.ts";
import { SensitiveString } from "../../sensitive.ts";

// Input Schema
export const EnvironmentsRotateSecretTokenPartialUpdateInput =
  /*@__PURE__*/ /*#__PURE__*/ Schema.Struct({
    id: Schema.Number.pipe(T.PathParam()),
    project_id: Schema.String.pipe(T.PathParam()),
    uuid: Schema.optional(Schema.String),
    name: Schema.optional(Schema.String),
    access_control: Schema.optional(Schema.Boolean),
    organization: Schema.optional(Schema.String),
    api_token: Schema.optional(SensitiveString),
    secret_api_token: Schema.optional(Schema.NullOr(Schema.String)),
    secret_api_token_backup: Schema.optional(Schema.NullOr(Schema.String)),
    created_at: Schema.optional(Schema.String),
    updated_at: Schema.optional(Schema.String),
    ingested_event: Schema.optional(Schema.Boolean),
    default_modifiers: Schema.optional(
      Schema.Record(Schema.String, Schema.Unknown),
    ),
    person_on_events_querying_enabled: Schema.optional(Schema.Boolean),
    user_access_level: Schema.optional(Schema.NullOr(Schema.String)),
    app_urls: Schema.optional(Schema.Array(Schema.NullOr(Schema.String))),
    anonymize_ips: Schema.optional(Schema.Boolean),
    completed_snippet_onboarding: Schema.optional(Schema.Boolean),
    test_account_filters: Schema.optional(Schema.Unknown),
    test_account_filters_default_checked: Schema.optional(
      Schema.NullOr(Schema.Boolean),
    ),
    path_cleaning_filters: Schema.optional(Schema.NullOr(Schema.Unknown)),
    is_demo: Schema.optional(Schema.Boolean),
    timezone: Schema.optional(Schema.suspend(() => TimezoneEnumSchema)),
    data_attributes: Schema.optional(Schema.Unknown),
    person_display_name_properties: Schema.optional(
      Schema.NullOr(Schema.Array(Schema.String)),
    ),
    correlation_config: Schema.optional(Schema.NullOr(Schema.Unknown)),
    autocapture_opt_out: Schema.optional(Schema.NullOr(Schema.Boolean)),
    autocapture_exceptions_opt_in: Schema.optional(
      Schema.NullOr(Schema.Boolean),
    ),
    autocapture_web_vitals_opt_in: Schema.optional(
      Schema.NullOr(Schema.Boolean),
    ),
    autocapture_web_vitals_allowed_metrics: Schema.optional(
      Schema.NullOr(Schema.Unknown),
    ),
    autocapture_exceptions_errors_to_ignore: Schema.optional(
      Schema.NullOr(Schema.Unknown),
    ),
    capture_console_log_opt_in: Schema.optional(Schema.NullOr(Schema.Boolean)),
    logs_settings: Schema.optional(Schema.NullOr(Schema.Unknown)),
    capture_performance_opt_in: Schema.optional(Schema.NullOr(Schema.Boolean)),
    session_recording_opt_in: Schema.optional(Schema.Boolean),
    session_recording_sample_rate: Schema.optional(
      Schema.NullOr(Schema.String),
    ),
    session_recording_minimum_duration_milliseconds: Schema.optional(
      Schema.NullOr(Schema.Number),
    ),
    session_recording_linked_flag: Schema.optional(
      Schema.NullOr(Schema.Unknown),
    ),
    session_recording_network_payload_capture_config: Schema.optional(
      Schema.NullOr(Schema.Unknown),
    ),
    session_recording_masking_config: Schema.optional(
      Schema.NullOr(Schema.Unknown),
    ),
    session_recording_url_trigger_config: Schema.optional(
      Schema.NullOr(Schema.Array(Schema.NullOr(Schema.Unknown))),
    ),
    session_recording_url_blocklist_config: Schema.optional(
      Schema.NullOr(Schema.Array(Schema.NullOr(Schema.Unknown))),
    ),
    session_recording_event_trigger_config: Schema.optional(
      Schema.NullOr(Schema.Array(Schema.NullOr(Schema.String))),
    ),
    session_recording_trigger_match_type_config: Schema.optional(
      Schema.NullOr(Schema.String),
    ),
    session_recording_trigger_groups: Schema.optional(
      Schema.NullOr(Schema.Unknown),
    ),
    session_recording_retention_period: Schema.optional(
      Schema.suspend(() => SessionRecordingRetentionPeriodEnumSchema),
    ),
    session_replay_config: Schema.optional(Schema.NullOr(Schema.Unknown)),
    survey_config: Schema.optional(Schema.NullOr(Schema.Unknown)),
    week_start_day: Schema.optional(Schema.Unknown),
    primary_dashboard: Schema.optional(Schema.NullOr(Schema.Number)),
    live_events_columns: Schema.optional(
      Schema.NullOr(Schema.Array(Schema.String)),
    ),
    recording_domains: Schema.optional(
      Schema.NullOr(Schema.Array(Schema.NullOr(Schema.String))),
    ),
    cookieless_server_hash_mode: Schema.optional(Schema.Unknown),
    human_friendly_comparison_periods: Schema.optional(
      Schema.NullOr(Schema.Boolean),
    ),
    inject_web_apps: Schema.optional(Schema.NullOr(Schema.Boolean)),
    extra_settings: Schema.optional(Schema.NullOr(Schema.Unknown)),
    modifiers: Schema.optional(Schema.NullOr(Schema.Unknown)),
    has_completed_onboarding_for: Schema.optional(
      Schema.NullOr(Schema.Unknown),
    ),
    surveys_opt_in: Schema.optional(Schema.NullOr(Schema.Boolean)),
    heatmaps_opt_in: Schema.optional(Schema.NullOr(Schema.Boolean)),
    flags_persistence_default: Schema.optional(Schema.NullOr(Schema.Boolean)),
    feature_flag_confirmation_enabled: Schema.optional(
      Schema.NullOr(Schema.Boolean),
    ),
    feature_flag_confirmation_message: Schema.optional(
      Schema.NullOr(Schema.String),
    ),
    default_evaluation_contexts_enabled: Schema.optional(
      Schema.NullOr(Schema.Boolean),
    ),
    require_evaluation_contexts: Schema.optional(Schema.NullOr(Schema.Boolean)),
    capture_dead_clicks: Schema.optional(Schema.NullOr(Schema.Boolean)),
    default_data_theme: Schema.optional(Schema.NullOr(Schema.Number)),
    revenue_analytics_config: Schema.optional(
      Schema.suspend(() => TeamRevenueAnalyticsConfigSchema),
    ),
    marketing_analytics_config: Schema.optional(
      Schema.suspend(() => TeamMarketingAnalyticsConfigSchema),
    ),
    customer_analytics_config: Schema.optional(
      Schema.suspend(() => TeamCustomerAnalyticsConfigSchema),
    ),
    onboarding_tasks: Schema.optional(Schema.NullOr(Schema.Unknown)),
    base_currency: Schema.optional(
      Schema.Literals([
        "AED",
        "AFN",
        "ALL",
        "AMD",
        "ANG",
        "AOA",
        "ARS",
        "AUD",
        "AWG",
        "AZN",
        "BAM",
        "BBD",
        "BDT",
        "BGN",
        "BHD",
        "BIF",
        "BMD",
        "BND",
        "BOB",
        "BRL",
        "BSD",
        "BTC",
        "BTN",
        "BWP",
        "BYN",
        "BZD",
        "CAD",
        "CDF",
        "CHF",
        "CLP",
        "CNY",
        "COP",
        "CRC",
        "CVE",
        "CZK",
        "DJF",
        "DKK",
        "DOP",
        "DZD",
        "EGP",
        "ERN",
        "ETB",
        "EUR",
        "FJD",
        "GBP",
        "GEL",
        "GHS",
        "GIP",
        "GMD",
        "GNF",
        "GTQ",
        "GYD",
        "HKD",
        "HNL",
        "HRK",
        "HTG",
        "HUF",
        "IDR",
        "ILS",
        "INR",
        "IQD",
        "IRR",
        "ISK",
        "JMD",
        "JOD",
        "JPY",
        "KES",
        "KGS",
        "KHR",
        "KMF",
        "KRW",
        "KWD",
        "KYD",
        "KZT",
        "LAK",
        "LBP",
        "LKR",
        "LRD",
        "LTL",
        "LVL",
        "LSL",
        "LYD",
        "MAD",
        "MDL",
        "MGA",
        "MKD",
        "MMK",
        "MNT",
        "MOP",
        "MRU",
        "MTL",
        "MUR",
        "MVR",
        "MWK",
        "MXN",
        "MYR",
        "MZN",
        "NAD",
        "NGN",
        "NIO",
        "NOK",
        "NPR",
        "NZD",
        "OMR",
        "PAB",
        "PEN",
        "PGK",
        "PHP",
        "PKR",
        "PLN",
        "PYG",
        "QAR",
        "RON",
        "RSD",
        "RUB",
        "RWF",
        "SAR",
        "SBD",
        "SCR",
        "SDG",
        "SEK",
        "SGD",
        "SRD",
        "SSP",
        "STN",
        "SYP",
        "SZL",
        "THB",
        "TJS",
        "TMT",
        "TND",
        "TOP",
        "TRY",
        "TTD",
        "TWD",
        "TZS",
        "UAH",
        "UGX",
        "USD",
        "UYU",
        "UZS",
        "VES",
        "VND",
        "VUV",
        "WST",
        "XAF",
        "XCD",
        "XOF",
        "XPF",
        "YER",
        "ZAR",
        "ZMW",
      ]),
    ),
    web_analytics_pre_aggregated_tables_enabled: Schema.optional(
      Schema.NullOr(Schema.Boolean),
    ),
    receive_org_level_activity_logs: Schema.optional(
      Schema.NullOr(Schema.Boolean),
    ),
    business_model: Schema.optional(Schema.Unknown),
    conversations_enabled: Schema.optional(Schema.NullOr(Schema.Boolean)),
    conversations_settings: Schema.optional(Schema.NullOr(Schema.Unknown)),
    proactive_tasks_enabled: Schema.optional(Schema.NullOr(Schema.Boolean)),
    effective_membership_level: Schema.optional(
      Schema.NullOr(Schema.Literals([1, 8, 15])),
    ),
    has_group_types: Schema.optional(Schema.Boolean),
    group_types: Schema.optional(
      Schema.Array(Schema.Record(Schema.String, Schema.Unknown)),
    ),
    live_events_token: Schema.optional(Schema.NullOr(Schema.String)),
    product_intents: Schema.optional(
      Schema.Array(Schema.Record(Schema.String, Schema.Unknown)),
    ),
    managed_viewsets: Schema.optional(
      Schema.Record(Schema.String, Schema.Boolean),
    ),
    available_setup_task_ids: Schema.optional(
      Schema.Array(Schema.suspend(() => AvailableSetupTaskIdsEnumSchema)),
    ),
  }).pipe(
    T.Http({
      method: "PATCH",
      path: "/api/projects/{project_id}/environments/{id}/rotate_secret_token/",
    }),
  );
export type EnvironmentsRotateSecretTokenPartialUpdateInput =
  typeof EnvironmentsRotateSecretTokenPartialUpdateInput.Type;

// Output Schema
export const EnvironmentsRotateSecretTokenPartialUpdateOutput =
  /*@__PURE__*/ /*#__PURE__*/ Schema.Void;
export type EnvironmentsRotateSecretTokenPartialUpdateOutput =
  typeof EnvironmentsRotateSecretTokenPartialUpdateOutput.Type;

// The operation
/**
 * Deprecated: use /api/environments/{id}/ instead.
 *
 * @param id - A unique integer value identifying this environment (aka team).
 * @param project_id - Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/.
 */
export const environmentsRotateSecretTokenPartialUpdate =
  /*@__PURE__*/ /*#__PURE__*/ API.make(() => ({
    inputSchema: EnvironmentsRotateSecretTokenPartialUpdateInput,
    outputSchema: EnvironmentsRotateSecretTokenPartialUpdateOutput,
    errors: [BadRequest, Forbidden, NotFound] as const,
  }));
