import * as Schema from "effect/Schema";
import { API } from "../client.ts";
import * as T from "../traits.ts";

// Input Schema
export const GetAccountsAccountCapabilitiesCapabilityInput =
  /*@__PURE__*/ /*#__PURE__*/ Schema.Struct({
    account: Schema.String.pipe(T.PathParam()),
    capability: Schema.String.pipe(T.PathParam()),
    expand: Schema.optional(Schema.String),
  }).pipe(
    T.Http({
      method: "GET",
      path: "/v1/accounts/{account}/capabilities/{capability}",
      contentType: "form-urlencoded",
    }),
  );
export type GetAccountsAccountCapabilitiesCapabilityInput =
  typeof GetAccountsAccountCapabilitiesCapabilityInput.Type;

// Output Schema
export const GetAccountsAccountCapabilitiesCapabilityOutput =
  /*@__PURE__*/ /*#__PURE__*/ Schema.Struct({
    account: Schema.Unknown,
    future_requirements: Schema.optional(
      Schema.Struct({
        alternatives: Schema.NullOr(
          Schema.Array(
            Schema.Struct({
              alternative_fields_due: Schema.Array(Schema.String),
              original_fields_due: Schema.Array(Schema.String),
            }),
          ),
        ),
        current_deadline: Schema.NullOr(Schema.Number),
        currently_due: Schema.Array(Schema.String),
        disabled_reason: Schema.NullOr(
          Schema.Literals([
            "other",
            "paused.inactivity",
            "pending.onboarding",
            "pending.review",
            "platform_disabled",
            "platform_paused",
            "rejected.inactivity",
            "rejected.other",
            "rejected.unsupported_business",
            "requirements.fields_needed",
          ]),
        ),
        errors: Schema.Array(
          Schema.Struct({
            code: Schema.Literals([
              "external_request",
              "information_missing",
              "invalid_address_city_state_postal_code",
              "invalid_address_highway_contract_box",
              "invalid_address_private_mailbox",
              "invalid_business_profile_name",
              "invalid_business_profile_name_denylisted",
              "invalid_company_name_denylisted",
              "invalid_dob_age_over_maximum",
              "invalid_dob_age_under_18",
              "invalid_dob_age_under_minimum",
              "invalid_product_description_length",
              "invalid_product_description_url_match",
              "invalid_representative_country",
              "invalid_signator",
              "invalid_statement_descriptor_business_mismatch",
              "invalid_statement_descriptor_denylisted",
              "invalid_statement_descriptor_length",
              "invalid_statement_descriptor_prefix_denylisted",
              "invalid_statement_descriptor_prefix_mismatch",
              "invalid_street_address",
              "invalid_tax_id",
              "invalid_tax_id_format",
              "invalid_tos_acceptance",
              "invalid_url_denylisted",
              "invalid_url_format",
              "invalid_url_length",
              "invalid_url_web_presence_detected",
              "invalid_url_website_business_information_mismatch",
              "invalid_url_website_empty",
              "invalid_url_website_inaccessible",
              "invalid_url_website_inaccessible_geoblocked",
              "invalid_url_website_inaccessible_password_protected",
              "invalid_url_website_incomplete",
              "invalid_url_website_incomplete_cancellation_policy",
              "invalid_url_website_incomplete_customer_service_details",
              "invalid_url_website_incomplete_legal_restrictions",
              "invalid_url_website_incomplete_refund_policy",
              "invalid_url_website_incomplete_return_policy",
              "invalid_url_website_incomplete_terms_and_conditions",
              "invalid_url_website_incomplete_under_construction",
              "invalid_url_website_other",
              "invalid_value_other",
              "unsupported_business_type",
              "verification_directors_mismatch",
              "verification_document_address_mismatch",
              "verification_document_address_missing",
              "verification_document_corrupt",
              "verification_document_country_not_supported",
              "verification_document_directors_mismatch",
              "verification_document_dob_mismatch",
              "verification_document_duplicate_type",
              "verification_document_expired",
              "verification_document_failed_copy",
              "verification_document_failed_greyscale",
              "verification_document_failed_other",
              "verification_document_failed_test_mode",
              "verification_document_fraudulent",
              "verification_document_id_number_mismatch",
              "verification_document_id_number_missing",
              "verification_document_incomplete",
              "verification_document_invalid",
              "verification_document_issue_or_expiry_date_missing",
              "verification_document_manipulated",
              "verification_document_missing_back",
              "verification_document_missing_front",
              "verification_document_name_mismatch",
              "verification_document_name_missing",
              "verification_document_nationality_mismatch",
              "verification_document_not_readable",
              "verification_document_not_signed",
              "verification_document_not_uploaded",
              "verification_document_photo_mismatch",
              "verification_document_too_large",
              "verification_document_type_not_supported",
              "verification_extraneous_directors",
              "verification_failed_address_match",
              "verification_failed_authorizer_authority",
              "verification_failed_business_iec_number",
              "verification_failed_document_match",
              "verification_failed_id_number_match",
              "verification_failed_keyed_identity",
              "verification_failed_keyed_match",
              "verification_failed_name_match",
              "verification_failed_other",
              "verification_failed_representative_authority",
              "verification_failed_residential_address",
              "verification_failed_tax_id_match",
              "verification_failed_tax_id_not_issued",
              "verification_legal_entity_structure_mismatch",
              "verification_missing_directors",
              "verification_missing_executives",
              "verification_missing_owners",
              "verification_rejected_ownership_exemption_reason",
              "verification_requires_additional_memorandum_of_associations",
              "verification_requires_additional_proof_of_registration",
              "verification_supportability",
            ]),
            reason: Schema.String,
            requirement: Schema.String,
          }),
        ),
        eventually_due: Schema.Array(Schema.String),
        past_due: Schema.Array(Schema.String),
        pending_verification: Schema.Array(Schema.String),
      }),
    ),
    id: Schema.String,
    object: Schema.Literals(["capability"]),
    requested: Schema.Boolean,
    requested_at: Schema.NullOr(Schema.Number),
    requirements: Schema.optional(
      Schema.Struct({
        alternatives: Schema.NullOr(
          Schema.Array(
            Schema.Struct({
              alternative_fields_due: Schema.Array(Schema.String),
              original_fields_due: Schema.Array(Schema.String),
            }),
          ),
        ),
        current_deadline: Schema.NullOr(Schema.Number),
        currently_due: Schema.Array(Schema.String),
        disabled_reason: Schema.NullOr(
          Schema.Literals([
            "other",
            "paused.inactivity",
            "pending.onboarding",
            "pending.review",
            "platform_disabled",
            "platform_paused",
            "rejected.inactivity",
            "rejected.other",
            "rejected.unsupported_business",
            "requirements.fields_needed",
          ]),
        ),
        errors: Schema.Array(
          Schema.Struct({
            code: Schema.Literals([
              "external_request",
              "information_missing",
              "invalid_address_city_state_postal_code",
              "invalid_address_highway_contract_box",
              "invalid_address_private_mailbox",
              "invalid_business_profile_name",
              "invalid_business_profile_name_denylisted",
              "invalid_company_name_denylisted",
              "invalid_dob_age_over_maximum",
              "invalid_dob_age_under_18",
              "invalid_dob_age_under_minimum",
              "invalid_product_description_length",
              "invalid_product_description_url_match",
              "invalid_representative_country",
              "invalid_signator",
              "invalid_statement_descriptor_business_mismatch",
              "invalid_statement_descriptor_denylisted",
              "invalid_statement_descriptor_length",
              "invalid_statement_descriptor_prefix_denylisted",
              "invalid_statement_descriptor_prefix_mismatch",
              "invalid_street_address",
              "invalid_tax_id",
              "invalid_tax_id_format",
              "invalid_tos_acceptance",
              "invalid_url_denylisted",
              "invalid_url_format",
              "invalid_url_length",
              "invalid_url_web_presence_detected",
              "invalid_url_website_business_information_mismatch",
              "invalid_url_website_empty",
              "invalid_url_website_inaccessible",
              "invalid_url_website_inaccessible_geoblocked",
              "invalid_url_website_inaccessible_password_protected",
              "invalid_url_website_incomplete",
              "invalid_url_website_incomplete_cancellation_policy",
              "invalid_url_website_incomplete_customer_service_details",
              "invalid_url_website_incomplete_legal_restrictions",
              "invalid_url_website_incomplete_refund_policy",
              "invalid_url_website_incomplete_return_policy",
              "invalid_url_website_incomplete_terms_and_conditions",
              "invalid_url_website_incomplete_under_construction",
              "invalid_url_website_other",
              "invalid_value_other",
              "unsupported_business_type",
              "verification_directors_mismatch",
              "verification_document_address_mismatch",
              "verification_document_address_missing",
              "verification_document_corrupt",
              "verification_document_country_not_supported",
              "verification_document_directors_mismatch",
              "verification_document_dob_mismatch",
              "verification_document_duplicate_type",
              "verification_document_expired",
              "verification_document_failed_copy",
              "verification_document_failed_greyscale",
              "verification_document_failed_other",
              "verification_document_failed_test_mode",
              "verification_document_fraudulent",
              "verification_document_id_number_mismatch",
              "verification_document_id_number_missing",
              "verification_document_incomplete",
              "verification_document_invalid",
              "verification_document_issue_or_expiry_date_missing",
              "verification_document_manipulated",
              "verification_document_missing_back",
              "verification_document_missing_front",
              "verification_document_name_mismatch",
              "verification_document_name_missing",
              "verification_document_nationality_mismatch",
              "verification_document_not_readable",
              "verification_document_not_signed",
              "verification_document_not_uploaded",
              "verification_document_photo_mismatch",
              "verification_document_too_large",
              "verification_document_type_not_supported",
              "verification_extraneous_directors",
              "verification_failed_address_match",
              "verification_failed_authorizer_authority",
              "verification_failed_business_iec_number",
              "verification_failed_document_match",
              "verification_failed_id_number_match",
              "verification_failed_keyed_identity",
              "verification_failed_keyed_match",
              "verification_failed_name_match",
              "verification_failed_other",
              "verification_failed_representative_authority",
              "verification_failed_residential_address",
              "verification_failed_tax_id_match",
              "verification_failed_tax_id_not_issued",
              "verification_legal_entity_structure_mismatch",
              "verification_missing_directors",
              "verification_missing_executives",
              "verification_missing_owners",
              "verification_rejected_ownership_exemption_reason",
              "verification_requires_additional_memorandum_of_associations",
              "verification_requires_additional_proof_of_registration",
              "verification_supportability",
            ]),
            reason: Schema.String,
            requirement: Schema.String,
          }),
        ),
        eventually_due: Schema.Array(Schema.String),
        past_due: Schema.Array(Schema.String),
        pending_verification: Schema.Array(Schema.String),
      }),
    ),
    status: Schema.Literals(["active", "inactive", "pending", "unrequested"]),
  });
export type GetAccountsAccountCapabilitiesCapabilityOutput =
  typeof GetAccountsAccountCapabilitiesCapabilityOutput.Type;

// The operation
/**
 * Retrieve an Account Capability
 *
 * <p>Retrieves information about the specified Account Capability.</p>
 *
 * @param expand - Specifies which fields in the response should be expanded.
 */
export const GetAccountsAccountCapabilitiesCapability =
  /*@__PURE__*/ /*#__PURE__*/ API.make(() => ({
    inputSchema: GetAccountsAccountCapabilitiesCapabilityInput,
    outputSchema: GetAccountsAccountCapabilitiesCapabilityOutput,
  }));
