import * as Schema from "effect/Schema";
import {
  billing_detailsSchema,
  payment_flows_private_payment_methods_alipaySchema,
  payment_method_acss_debitSchema,
  payment_method_affirmSchema,
  payment_method_afterpay_clearpaySchema,
  payment_method_almaSchema,
  payment_method_amazon_paySchema,
  payment_method_au_becs_debitSchema,
  payment_method_bacs_debitSchema,
  payment_method_bancontactSchema,
  payment_method_billieSchema,
  payment_method_blikSchema,
  payment_method_boletoSchema,
  payment_method_cardSchema,
  payment_method_card_presentSchema,
  payment_method_cashappSchema,
  payment_method_cryptoSchema,
  payment_method_customSchema,
  payment_method_customer_balanceSchema,
  payment_method_epsSchema,
  payment_method_fpxSchema,
  payment_method_giropaySchema,
  payment_method_grabpaySchema,
  payment_method_idealSchema,
  payment_method_interac_presentSchema,
  payment_method_kakao_paySchema,
  payment_method_klarnaSchema,
  payment_method_konbiniSchema,
  payment_method_kr_cardSchema,
  payment_method_linkSchema,
  payment_method_mb_waySchema,
  payment_method_mobilepaySchema,
  payment_method_multibancoSchema,
  payment_method_naver_paySchema,
  payment_method_nz_bank_accountSchema,
  payment_method_oxxoSchema,
  payment_method_p24Schema,
  payment_method_pay_by_bankSchema,
  payment_method_paycoSchema,
  payment_method_paynowSchema,
  payment_method_paypalSchema,
  payment_method_paytoSchema,
  payment_method_pixSchema,
  payment_method_promptpaySchema,
  payment_method_revolut_paySchema,
  payment_method_samsung_paySchema,
  payment_method_satispaySchema,
  payment_method_sepa_debitSchema,
  payment_method_sofortSchema,
  payment_method_swishSchema,
  payment_method_twintSchema,
  payment_method_upiSchema,
  payment_method_us_bank_accountSchema,
  payment_method_wechat_paySchema,
  payment_method_zipSchema,
  radar_radar_optionsSchema,
} from "./_schemas.ts";
import { API } from "../client.ts";
import * as T from "../traits.ts";

// Input Schema
export const PostPaymentMethodsInput =
  /*@__PURE__*/ /*#__PURE__*/ Schema.Struct({
    acss_debit: Schema.optional(
      Schema.Struct({
        account_number: Schema.String,
        institution_number: Schema.String,
        transit_number: Schema.String,
      }),
    ),
    affirm: Schema.optional(Schema.Struct({})),
    afterpay_clearpay: Schema.optional(Schema.Struct({})),
    alipay: Schema.optional(Schema.Struct({})),
    allow_redisplay: Schema.optional(
      Schema.Literals(["always", "limited", "unspecified"]),
    ),
    alma: Schema.optional(Schema.Struct({})),
    amazon_pay: Schema.optional(Schema.Struct({})),
    au_becs_debit: Schema.optional(
      Schema.Struct({
        account_number: Schema.String,
        bsb_number: Schema.String,
      }),
    ),
    bacs_debit: Schema.optional(
      Schema.Struct({
        account_number: Schema.optional(Schema.String),
        sort_code: Schema.optional(Schema.String),
      }),
    ),
    bancontact: Schema.optional(Schema.Struct({})),
    billie: Schema.optional(Schema.Struct({})),
    billing_details: Schema.optional(
      Schema.Struct({
        address: Schema.optional(Schema.Unknown),
        email: Schema.optional(Schema.Unknown),
        name: Schema.optional(Schema.Unknown),
        phone: Schema.optional(Schema.Unknown),
        tax_id: Schema.optional(Schema.String),
      }),
    ),
    blik: Schema.optional(Schema.Struct({})),
    boleto: Schema.optional(
      Schema.Struct({
        tax_id: Schema.String,
      }),
    ),
    card: Schema.optional(Schema.Unknown),
    cashapp: Schema.optional(Schema.Struct({})),
    crypto: Schema.optional(Schema.Struct({})),
    custom: Schema.optional(
      Schema.Struct({
        type: Schema.String,
      }),
    ),
    customer: Schema.optional(Schema.String),
    customer_balance: Schema.optional(Schema.Struct({})),
    eps: Schema.optional(
      Schema.Struct({
        bank: Schema.optional(
          Schema.Literals([
            "arzte_und_apotheker_bank",
            "austrian_anadi_bank_ag",
            "bank_austria",
            "bankhaus_carl_spangler",
            "bankhaus_schelhammer_und_schattera_ag",
            "bawag_psk_ag",
            "bks_bank_ag",
            "brull_kallmus_bank_ag",
            "btv_vier_lander_bank",
            "capital_bank_grawe_gruppe_ag",
            "deutsche_bank_ag",
            "dolomitenbank",
            "easybank_ag",
            "erste_bank_und_sparkassen",
            "hypo_alpeadriabank_international_ag",
            "hypo_bank_burgenland_aktiengesellschaft",
            "hypo_noe_lb_fur_niederosterreich_u_wien",
            "hypo_oberosterreich_salzburg_steiermark",
            "hypo_tirol_bank_ag",
            "hypo_vorarlberg_bank_ag",
            "marchfelder_bank",
            "oberbank_ag",
            "raiffeisen_bankengruppe_osterreich",
            "schoellerbank_ag",
            "sparda_bank_wien",
            "volksbank_gruppe",
            "volkskreditbank_ag",
            "vr_bank_braunau",
          ]),
        ),
      }),
    ),
    expand: Schema.optional(Schema.Array(Schema.String)),
    fpx: Schema.optional(
      Schema.Struct({
        account_holder_type: Schema.optional(
          Schema.Literals(["company", "individual"]),
        ),
        bank: Schema.Literals([
          "affin_bank",
          "agrobank",
          "alliance_bank",
          "ambank",
          "bank_islam",
          "bank_muamalat",
          "bank_of_china",
          "bank_rakyat",
          "bsn",
          "cimb",
          "deutsche_bank",
          "hong_leong_bank",
          "hsbc",
          "kfh",
          "maybank2e",
          "maybank2u",
          "ocbc",
          "pb_enterprise",
          "public_bank",
          "rhb",
          "standard_chartered",
          "uob",
        ]),
      }),
    ),
    giropay: Schema.optional(Schema.Struct({})),
    grabpay: Schema.optional(Schema.Struct({})),
    ideal: Schema.optional(
      Schema.Struct({
        bank: Schema.optional(
          Schema.Literals([
            "abn_amro",
            "adyen",
            "asn_bank",
            "bunq",
            "buut",
            "finom",
            "handelsbanken",
            "ing",
            "knab",
            "mollie",
            "moneyou",
            "n26",
            "nn",
            "rabobank",
            "regiobank",
            "revolut",
            "sns_bank",
            "triodos_bank",
            "van_lanschot",
            "yoursafe",
          ]),
        ),
      }),
    ),
    interac_present: Schema.optional(Schema.Struct({})),
    kakao_pay: Schema.optional(Schema.Struct({})),
    klarna: Schema.optional(
      Schema.Struct({
        dob: Schema.optional(
          Schema.Struct({
            day: Schema.Number,
            month: Schema.Number,
            year: Schema.Number,
          }),
        ),
      }),
    ),
    konbini: Schema.optional(Schema.Struct({})),
    kr_card: Schema.optional(Schema.Struct({})),
    link: Schema.optional(Schema.Struct({})),
    mb_way: Schema.optional(Schema.Struct({})),
    metadata: Schema.optional(Schema.Record(Schema.String, Schema.String)),
    mobilepay: Schema.optional(Schema.Struct({})),
    multibanco: Schema.optional(Schema.Struct({})),
    naver_pay: Schema.optional(
      Schema.Struct({
        funding: Schema.optional(Schema.Literals(["card", "points"])),
      }),
    ),
    nz_bank_account: Schema.optional(
      Schema.Struct({
        account_holder_name: Schema.optional(Schema.String),
        account_number: Schema.String,
        bank_code: Schema.String,
        branch_code: Schema.String,
        reference: Schema.optional(Schema.String),
        suffix: Schema.String,
      }),
    ),
    oxxo: Schema.optional(Schema.Struct({})),
    p24: Schema.optional(
      Schema.Struct({
        bank: Schema.optional(
          Schema.Literals([
            "alior_bank",
            "bank_millennium",
            "bank_nowy_bfg_sa",
            "bank_pekao_sa",
            "banki_spbdzielcze",
            "blik",
            "bnp_paribas",
            "boz",
            "citi_handlowy",
            "credit_agricole",
            "envelobank",
            "etransfer_pocztowy24",
            "getin_bank",
            "ideabank",
            "ing",
            "inteligo",
            "mbank_mtransfer",
            "nest_przelew",
            "noble_pay",
            "pbac_z_ipko",
            "plus_bank",
            "santander_przelew24",
            "tmobile_usbugi_bankowe",
            "toyota_bank",
            "velobank",
            "volkswagen_bank",
          ]),
        ),
      }),
    ),
    pay_by_bank: Schema.optional(Schema.Struct({})),
    payco: Schema.optional(Schema.Struct({})),
    payment_method: Schema.optional(Schema.String),
    paynow: Schema.optional(Schema.Struct({})),
    paypal: Schema.optional(Schema.Struct({})),
    payto: Schema.optional(
      Schema.Struct({
        account_number: Schema.optional(Schema.String),
        bsb_number: Schema.optional(Schema.String),
        pay_id: Schema.optional(Schema.String),
      }),
    ),
    pix: Schema.optional(Schema.Struct({})),
    promptpay: Schema.optional(Schema.Struct({})),
    radar_options: Schema.optional(
      Schema.Struct({
        session: Schema.optional(Schema.String),
      }),
    ),
    revolut_pay: Schema.optional(Schema.Struct({})),
    samsung_pay: Schema.optional(Schema.Struct({})),
    satispay: Schema.optional(Schema.Struct({})),
    sepa_debit: Schema.optional(
      Schema.Struct({
        iban: Schema.String,
      }),
    ),
    sofort: Schema.optional(
      Schema.Struct({
        country: Schema.Literals(["AT", "BE", "DE", "ES", "IT", "NL"]),
      }),
    ),
    swish: Schema.optional(Schema.Struct({})),
    twint: Schema.optional(Schema.Struct({})),
    type: Schema.optional(
      Schema.Literals([
        "acss_debit",
        "affirm",
        "afterpay_clearpay",
        "alipay",
        "alma",
        "amazon_pay",
        "au_becs_debit",
        "bacs_debit",
        "bancontact",
        "billie",
        "blik",
        "boleto",
        "card",
        "cashapp",
        "crypto",
        "custom",
        "customer_balance",
        "eps",
        "fpx",
        "giropay",
        "grabpay",
        "ideal",
        "kakao_pay",
        "klarna",
        "konbini",
        "kr_card",
        "link",
        "mb_way",
        "mobilepay",
        "multibanco",
        "naver_pay",
        "nz_bank_account",
        "oxxo",
        "p24",
        "pay_by_bank",
        "payco",
        "paynow",
        "paypal",
        "payto",
        "pix",
        "promptpay",
        "revolut_pay",
        "samsung_pay",
        "satispay",
        "sepa_debit",
        "sofort",
        "swish",
        "twint",
        "upi",
        "us_bank_account",
        "wechat_pay",
        "zip",
      ]),
    ),
    upi: Schema.optional(
      Schema.Struct({
        mandate_options: Schema.optional(
          Schema.Struct({
            amount: Schema.optional(Schema.Number),
            amount_type: Schema.optional(Schema.Literals(["fixed", "maximum"])),
            description: Schema.optional(Schema.String),
            end_date: Schema.optional(Schema.Number),
          }),
        ),
      }),
    ),
    us_bank_account: Schema.optional(
      Schema.Struct({
        account_holder_type: Schema.optional(
          Schema.Literals(["company", "individual"]),
        ),
        account_number: Schema.optional(Schema.String),
        account_type: Schema.optional(Schema.Literals(["checking", "savings"])),
        financial_connections_account: Schema.optional(Schema.String),
        routing_number: Schema.optional(Schema.String),
      }),
    ),
    wechat_pay: Schema.optional(Schema.Struct({})),
    zip: Schema.optional(Schema.Struct({})),
  }).pipe(
    T.Http({
      method: "POST",
      path: "/v1/payment_methods",
      contentType: "form-urlencoded",
    }),
  );
export type PostPaymentMethodsInput = typeof PostPaymentMethodsInput.Type;

// Output Schema
export const PostPaymentMethodsOutput =
  /*@__PURE__*/ /*#__PURE__*/ Schema.Struct({
    acss_debit: Schema.optional(
      Schema.suspend(() => payment_method_acss_debitSchema),
    ),
    affirm: Schema.optional(Schema.suspend(() => payment_method_affirmSchema)),
    afterpay_clearpay: Schema.optional(
      Schema.suspend(() => payment_method_afterpay_clearpaySchema),
    ),
    alipay: Schema.optional(
      Schema.suspend(() => payment_flows_private_payment_methods_alipaySchema),
    ),
    allow_redisplay: Schema.optional(
      Schema.Literals(["always", "limited", "unspecified"]),
    ),
    alma: Schema.optional(Schema.suspend(() => payment_method_almaSchema)),
    amazon_pay: Schema.optional(
      Schema.suspend(() => payment_method_amazon_paySchema),
    ),
    au_becs_debit: Schema.optional(
      Schema.suspend(() => payment_method_au_becs_debitSchema),
    ),
    bacs_debit: Schema.optional(
      Schema.suspend(() => payment_method_bacs_debitSchema),
    ),
    bancontact: Schema.optional(
      Schema.suspend(() => payment_method_bancontactSchema),
    ),
    billie: Schema.optional(Schema.suspend(() => payment_method_billieSchema)),
    billing_details: Schema.suspend(() => billing_detailsSchema),
    blik: Schema.optional(Schema.suspend(() => payment_method_blikSchema)),
    boleto: Schema.optional(Schema.suspend(() => payment_method_boletoSchema)),
    card: Schema.optional(Schema.suspend(() => payment_method_cardSchema)),
    card_present: Schema.optional(
      Schema.suspend(() => payment_method_card_presentSchema),
    ),
    cashapp: Schema.optional(
      Schema.suspend(() => payment_method_cashappSchema),
    ),
    created: Schema.Number,
    crypto: Schema.optional(Schema.suspend(() => payment_method_cryptoSchema)),
    custom: Schema.optional(Schema.suspend(() => payment_method_customSchema)),
    customer: Schema.Unknown,
    customer_account: Schema.NullOr(Schema.String),
    customer_balance: Schema.optional(
      Schema.suspend(() => payment_method_customer_balanceSchema),
    ),
    eps: Schema.optional(Schema.suspend(() => payment_method_epsSchema)),
    fpx: Schema.optional(Schema.suspend(() => payment_method_fpxSchema)),
    giropay: Schema.optional(
      Schema.suspend(() => payment_method_giropaySchema),
    ),
    grabpay: Schema.optional(
      Schema.suspend(() => payment_method_grabpaySchema),
    ),
    id: Schema.String,
    ideal: Schema.optional(Schema.suspend(() => payment_method_idealSchema)),
    interac_present: Schema.optional(
      Schema.suspend(() => payment_method_interac_presentSchema),
    ),
    kakao_pay: Schema.optional(
      Schema.suspend(() => payment_method_kakao_paySchema),
    ),
    klarna: Schema.optional(Schema.suspend(() => payment_method_klarnaSchema)),
    konbini: Schema.optional(
      Schema.suspend(() => payment_method_konbiniSchema),
    ),
    kr_card: Schema.optional(
      Schema.suspend(() => payment_method_kr_cardSchema),
    ),
    link: Schema.optional(Schema.suspend(() => payment_method_linkSchema)),
    livemode: Schema.Boolean,
    mb_way: Schema.optional(Schema.suspend(() => payment_method_mb_waySchema)),
    metadata: Schema.NullOr(Schema.Record(Schema.String, Schema.String)),
    mobilepay: Schema.optional(
      Schema.suspend(() => payment_method_mobilepaySchema),
    ),
    multibanco: Schema.optional(
      Schema.suspend(() => payment_method_multibancoSchema),
    ),
    naver_pay: Schema.optional(
      Schema.suspend(() => payment_method_naver_paySchema),
    ),
    nz_bank_account: Schema.optional(
      Schema.suspend(() => payment_method_nz_bank_accountSchema),
    ),
    object: Schema.Literals(["payment_method"]),
    oxxo: Schema.optional(Schema.suspend(() => payment_method_oxxoSchema)),
    p24: Schema.optional(Schema.suspend(() => payment_method_p24Schema)),
    pay_by_bank: Schema.optional(
      Schema.suspend(() => payment_method_pay_by_bankSchema),
    ),
    payco: Schema.optional(Schema.suspend(() => payment_method_paycoSchema)),
    paynow: Schema.optional(Schema.suspend(() => payment_method_paynowSchema)),
    paypal: Schema.optional(Schema.suspend(() => payment_method_paypalSchema)),
    payto: Schema.optional(Schema.suspend(() => payment_method_paytoSchema)),
    pix: Schema.optional(Schema.suspend(() => payment_method_pixSchema)),
    promptpay: Schema.optional(
      Schema.suspend(() => payment_method_promptpaySchema),
    ),
    radar_options: Schema.optional(
      Schema.suspend(() => radar_radar_optionsSchema),
    ),
    revolut_pay: Schema.optional(
      Schema.suspend(() => payment_method_revolut_paySchema),
    ),
    samsung_pay: Schema.optional(
      Schema.suspend(() => payment_method_samsung_paySchema),
    ),
    satispay: Schema.optional(
      Schema.suspend(() => payment_method_satispaySchema),
    ),
    sepa_debit: Schema.optional(
      Schema.suspend(() => payment_method_sepa_debitSchema),
    ),
    sofort: Schema.optional(Schema.suspend(() => payment_method_sofortSchema)),
    swish: Schema.optional(Schema.suspend(() => payment_method_swishSchema)),
    twint: Schema.optional(Schema.suspend(() => payment_method_twintSchema)),
    type: Schema.Literals([
      "acss_debit",
      "affirm",
      "afterpay_clearpay",
      "alipay",
      "alma",
      "amazon_pay",
      "au_becs_debit",
      "bacs_debit",
      "bancontact",
      "billie",
      "blik",
      "boleto",
      "card",
      "card_present",
      "cashapp",
      "crypto",
      "custom",
      "customer_balance",
      "eps",
      "fpx",
      "giropay",
      "grabpay",
      "ideal",
      "interac_present",
      "kakao_pay",
      "klarna",
      "konbini",
      "kr_card",
      "link",
      "mb_way",
      "mobilepay",
      "multibanco",
      "naver_pay",
      "nz_bank_account",
      "oxxo",
      "p24",
      "pay_by_bank",
      "payco",
      "paynow",
      "paypal",
      "payto",
      "pix",
      "promptpay",
      "revolut_pay",
      "samsung_pay",
      "satispay",
      "sepa_debit",
      "sofort",
      "swish",
      "twint",
      "upi",
      "us_bank_account",
      "wechat_pay",
      "zip",
    ]),
    upi: Schema.optional(Schema.suspend(() => payment_method_upiSchema)),
    us_bank_account: Schema.optional(
      Schema.suspend(() => payment_method_us_bank_accountSchema),
    ),
    wechat_pay: Schema.optional(
      Schema.suspend(() => payment_method_wechat_paySchema),
    ),
    zip: Schema.optional(Schema.suspend(() => payment_method_zipSchema)),
  });
export type PostPaymentMethodsOutput = typeof PostPaymentMethodsOutput.Type;

// The operation
/**
 * Shares a PaymentMethod
 *
 * <p>Creates a PaymentMethod object. Read the <a href="/docs/stripe-js/reference#stripe-create-payment-method">Stripe.js reference</a> to learn how to create PaymentMethods via Stripe.js.</p>
 * <p>Instead of creating a PaymentMethod directly, we recommend using the <a href="/docs/payments/accept-a-payment">PaymentIntents</a> API to accept a payment immediately or the <a href="/docs/payments/save-and-reuse">SetupIntent</a> API to collect payment method details ahead of a future payment.</p>
 */
export const PostPaymentMethods = /*@__PURE__*/ /*#__PURE__*/ API.make(() => ({
  inputSchema: PostPaymentMethodsInput,
  outputSchema: PostPaymentMethodsOutput,
}));
