import * as Schema from "effect/Schema";
import {
  customer_taxSchema,
  invoice_setting_customer_settingSchema,
  payment_sourceSchema,
  subscriptionSchema,
  tax_idSchema,
} from "./_schemas.ts";
import { API } from "../client.ts";
import * as T from "../traits.ts";

// Input Schema
export const PostCustomersInput = /*@__PURE__*/ /*#__PURE__*/ Schema.Struct({
  address: Schema.optional(Schema.Unknown),
  balance: Schema.optional(Schema.Number),
  business_name: Schema.optional(Schema.Unknown),
  cash_balance: Schema.optional(
    Schema.Struct({
      settings: Schema.optional(
        Schema.Struct({
          reconciliation_mode: Schema.optional(
            Schema.Literals(["automatic", "manual", "merchant_default"]),
          ),
        }),
      ),
    }),
  ),
  description: Schema.optional(Schema.String),
  email: Schema.optional(Schema.String),
  expand: Schema.optional(Schema.Array(Schema.String)),
  individual_name: Schema.optional(Schema.Unknown),
  invoice_prefix: Schema.optional(Schema.String),
  invoice_settings: Schema.optional(
    Schema.Struct({
      custom_fields: Schema.optional(Schema.Unknown),
      default_payment_method: Schema.optional(Schema.String),
      footer: Schema.optional(Schema.String),
      rendering_options: Schema.optional(Schema.Unknown),
    }),
  ),
  metadata: Schema.optional(Schema.Unknown),
  name: Schema.optional(Schema.String),
  next_invoice_sequence: Schema.optional(Schema.Number),
  payment_method: Schema.optional(Schema.String),
  phone: Schema.optional(Schema.String),
  preferred_locales: Schema.optional(Schema.Array(Schema.String)),
  shipping: Schema.optional(Schema.Unknown),
  source: Schema.optional(Schema.String),
  tax: Schema.optional(
    Schema.Struct({
      ip_address: Schema.optional(Schema.Unknown),
      validate_location: Schema.optional(
        Schema.Literals(["deferred", "immediately"]),
      ),
    }),
  ),
  tax_exempt: Schema.optional(
    Schema.Literals(["", "exempt", "none", "reverse"]),
  ),
  tax_id_data: Schema.optional(
    Schema.Array(
      Schema.Struct({
        type: Schema.Literals([
          "ad_nrt",
          "ae_trn",
          "al_tin",
          "am_tin",
          "ao_tin",
          "ar_cuit",
          "au_abn",
          "au_arn",
          "aw_tin",
          "az_tin",
          "ba_tin",
          "bb_tin",
          "bd_bin",
          "bf_ifu",
          "bg_uic",
          "bh_vat",
          "bj_ifu",
          "bo_tin",
          "br_cnpj",
          "br_cpf",
          "bs_tin",
          "by_tin",
          "ca_bn",
          "ca_gst_hst",
          "ca_pst_bc",
          "ca_pst_mb",
          "ca_pst_sk",
          "ca_qst",
          "cd_nif",
          "ch_uid",
          "ch_vat",
          "cl_tin",
          "cm_niu",
          "cn_tin",
          "co_nit",
          "cr_tin",
          "cv_nif",
          "de_stn",
          "do_rcn",
          "ec_ruc",
          "eg_tin",
          "es_cif",
          "et_tin",
          "eu_oss_vat",
          "eu_vat",
          "gb_vat",
          "ge_vat",
          "gn_nif",
          "hk_br",
          "hr_oib",
          "hu_tin",
          "id_npwp",
          "il_vat",
          "in_gst",
          "is_vat",
          "jp_cn",
          "jp_rn",
          "jp_trn",
          "ke_pin",
          "kg_tin",
          "kh_tin",
          "kr_brn",
          "kz_bin",
          "la_tin",
          "li_uid",
          "li_vat",
          "lk_vat",
          "ma_vat",
          "md_vat",
          "me_pib",
          "mk_vat",
          "mr_nif",
          "mx_rfc",
          "my_frp",
          "my_itn",
          "my_sst",
          "ng_tin",
          "no_vat",
          "no_voec",
          "np_pan",
          "nz_gst",
          "om_vat",
          "pe_ruc",
          "ph_tin",
          "pl_nip",
          "ro_tin",
          "rs_pib",
          "ru_inn",
          "ru_kpp",
          "sa_vat",
          "sg_gst",
          "sg_uen",
          "si_tin",
          "sn_ninea",
          "sr_fin",
          "sv_nit",
          "th_vat",
          "tj_tin",
          "tr_tin",
          "tw_vat",
          "tz_vat",
          "ua_vat",
          "ug_tin",
          "us_ein",
          "uy_ruc",
          "uz_tin",
          "uz_vat",
          "ve_rif",
          "vn_tin",
          "za_vat",
          "zm_tin",
          "zw_tin",
        ]),
        value: Schema.String,
      }),
    ),
  ),
  test_clock: Schema.optional(Schema.String),
  validate: Schema.optional(Schema.Boolean),
}).pipe(
  T.Http({
    method: "POST",
    path: "/v1/customers",
    contentType: "form-urlencoded",
  }),
);
export type PostCustomersInput = typeof PostCustomersInput.Type;

// Output Schema
export const PostCustomersOutput = /*@__PURE__*/ /*#__PURE__*/ Schema.Struct({
  address: Schema.optional(Schema.Unknown),
  balance: Schema.optional(Schema.Number),
  business_name: Schema.optional(Schema.String),
  cash_balance: Schema.optional(Schema.Unknown),
  created: Schema.Number,
  currency: Schema.optional(Schema.NullOr(Schema.String)),
  customer_account: Schema.optional(Schema.NullOr(Schema.String)),
  default_source: Schema.Unknown,
  delinquent: Schema.optional(Schema.NullOr(Schema.Boolean)),
  description: Schema.NullOr(Schema.String),
  discount: Schema.optional(Schema.Unknown),
  email: Schema.NullOr(Schema.String),
  id: Schema.String,
  individual_name: Schema.optional(Schema.String),
  invoice_credit_balance: Schema.optional(
    Schema.Record(Schema.String, Schema.Number),
  ),
  invoice_prefix: Schema.optional(Schema.NullOr(Schema.String)),
  invoice_settings: Schema.optional(
    Schema.suspend(() => invoice_setting_customer_settingSchema),
  ),
  livemode: Schema.Boolean,
  metadata: Schema.optional(Schema.Record(Schema.String, Schema.String)),
  name: Schema.optional(Schema.NullOr(Schema.String)),
  next_invoice_sequence: Schema.optional(Schema.Number),
  object: Schema.Literals(["customer"]),
  phone: Schema.optional(Schema.NullOr(Schema.String)),
  preferred_locales: Schema.optional(
    Schema.NullOr(Schema.Array(Schema.String)),
  ),
  shipping: Schema.Unknown,
  sources: Schema.optional(
    Schema.Struct({
      data: Schema.Array(Schema.suspend(() => payment_sourceSchema)),
      has_more: Schema.Boolean,
      object: Schema.Literals(["list"]),
      url: Schema.String,
    }),
  ),
  subscriptions: Schema.optional(
    Schema.Struct({
      data: Schema.Array(Schema.suspend(() => subscriptionSchema)),
      has_more: Schema.Boolean,
      object: Schema.Literals(["list"]),
      url: Schema.String,
    }),
  ),
  tax: Schema.optional(Schema.suspend(() => customer_taxSchema)),
  tax_exempt: Schema.optional(
    Schema.NullOr(Schema.Literals(["exempt", "none", "reverse"])),
  ),
  tax_ids: Schema.optional(
    Schema.Struct({
      data: Schema.Array(Schema.suspend(() => tax_idSchema)),
      has_more: Schema.Boolean,
      object: Schema.Literals(["list"]),
      url: Schema.String,
    }),
  ),
  test_clock: Schema.optional(Schema.Unknown),
});
export type PostCustomersOutput = typeof PostCustomersOutput.Type;

// The operation
/**
 * Create a customer
 *
 * <p>Creates a new customer object.</p>
 */
export const PostCustomers = /*@__PURE__*/ /*#__PURE__*/ API.make(() => ({
  inputSchema: PostCustomersInput,
  outputSchema: PostCustomersOutput,
}));
