import * as Schema from "effect/Schema";
import { SensitiveOutputString } from "../../sensitive.ts";

export const ExternalDataSchemaSchema =
  /*@__PURE__*/ /*#__PURE__*/ Schema.Struct({
    id: Schema.optional(Schema.String),
    name: Schema.optional(Schema.String),
    label: Schema.optional(Schema.NullOr(Schema.String)),
    table: Schema.optional(
      Schema.NullOr(Schema.Record(Schema.String, Schema.Unknown)),
    ),
    should_sync: Schema.optional(Schema.Boolean),
    last_synced_at: Schema.optional(Schema.NullOr(Schema.String)),
    latest_error: Schema.optional(Schema.NullOr(Schema.String)),
    incremental: Schema.optional(Schema.Boolean),
    status: Schema.optional(Schema.NullOr(Schema.String)),
    sync_type: Schema.optional(Schema.Unknown),
    incremental_field: Schema.optional(Schema.NullOr(Schema.String)),
    incremental_field_type: Schema.optional(Schema.Unknown),
    sync_frequency: Schema.optional(Schema.Unknown),
    sync_time_of_day: Schema.optional(Schema.NullOr(Schema.String)),
    description: Schema.optional(Schema.NullOr(Schema.String)),
    primary_key_columns: Schema.optional(
      Schema.NullOr(Schema.Array(Schema.String)),
    ),
    cdc_table_mode: Schema.optional(Schema.Unknown),
  });
export const ExternalDataSourceSerializersSchema =
  /*@__PURE__*/ /*#__PURE__*/ Schema.Struct({
    id: Schema.optional(Schema.String),
    created_at: Schema.optional(Schema.String),
    created_by: Schema.optional(Schema.NullOr(Schema.String)),
    status: Schema.optional(Schema.String),
    client_secret: Schema.optional(SensitiveOutputString),
    account_id: Schema.optional(Schema.String),
    source_type: Schema.optional(
      Schema.Literals([
        "Ashby",
        "Supabase",
        "CustomerIO",
        "Github",
        "Stripe",
        "Hubspot",
        "Postgres",
        "Zendesk",
        "Snowflake",
        "Salesforce",
        "MySQL",
        "MongoDB",
        "MSSQL",
        "Vitally",
        "BigQuery",
        "Chargebee",
        "Clerk",
        "GoogleAds",
        "TemporalIO",
        "DoIt",
        "GoogleSheets",
        "MetaAds",
        "Klaviyo",
        "Mailchimp",
        "Braze",
        "Mailjet",
        "Redshift",
        "Polar",
        "RevenueCat",
        "LinkedinAds",
        "RedditAds",
        "TikTokAds",
        "BingAds",
        "Shopify",
        "Attio",
        "SnapchatAds",
        "Linear",
        "Intercom",
        "Amplitude",
        "Mixpanel",
        "Jira",
        "ActiveCampaign",
        "Marketo",
        "Adjust",
        "AppsFlyer",
        "Freshdesk",
        "GoogleAnalytics",
        "Pipedrive",
        "SendGrid",
        "Slack",
        "PagerDuty",
        "Asana",
        "Notion",
        "Airtable",
        "Greenhouse",
        "BambooHR",
        "Lever",
        "GitLab",
        "Datadog",
        "Sentry",
        "Pendo",
        "FullStory",
        "AmazonAds",
        "PinterestAds",
        "AppleSearchAds",
        "QuickBooks",
        "Xero",
        "NetSuite",
        "WooCommerce",
        "BigCommerce",
        "PayPal",
        "Square",
        "Zoom",
        "Trello",
        "Monday",
        "ClickUp",
        "Confluence",
        "Recurly",
        "SalesLoft",
        "Outreach",
        "Gong",
        "Calendly",
        "Typeform",
        "Iterable",
        "ZohoCRM",
        "Close",
        "Oracle",
        "DynamoDB",
        "Elasticsearch",
        "Kafka",
        "LaunchDarkly",
        "Braintree",
        "Recharge",
        "HelpScout",
        "Gorgias",
        "Instagram",
        "YouTubeAnalytics",
        "FacebookPages",
        "TwitterAds",
        "Workday",
        "ServiceNow",
        "Pardot",
        "Copper",
        "Front",
        "ChartMogul",
        "Zuora",
        "Paddle",
        "CircleCI",
        "CockroachDB",
        "Firebase",
        "AzureBlob",
        "GoogleDrive",
        "OneDrive",
        "SharePoint",
        "Box",
        "SFTP",
        "MicrosoftTeams",
        "Aircall",
        "Webflow",
        "Okta",
        "Auth0",
        "Productboard",
        "Smartsheet",
        "Wrike",
        "Plaid",
        "SurveyMonkey",
        "Eventbrite",
        "RingCentral",
        "Twilio",
        "Freshsales",
        "Shortcut",
        "ConvertKit",
        "Drip",
        "CampaignMonitor",
        "MailerLite",
        "Omnisend",
        "Brevo",
        "Postmark",
        "Granola",
        "BuildBetter",
        "Convex",
        "ClickHouse",
        "Plain",
      ]),
    ),
    latest_error: Schema.optional(Schema.NullOr(Schema.String)),
    prefix: Schema.optional(Schema.NullOr(Schema.String)),
    description: Schema.optional(Schema.NullOr(Schema.String)),
    access_method: Schema.optional(Schema.Literals(["warehouse", "direct"])),
    engine: Schema.optional(Schema.Unknown),
    last_run_at: Schema.optional(Schema.NullOr(Schema.String)),
    schemas: Schema.optional(
      Schema.Array(Schema.Record(Schema.String, Schema.Unknown)),
    ),
    job_inputs: Schema.optional(Schema.NullOr(Schema.Unknown)),
    revenue_analytics_config: Schema.optional(
      Schema.Struct({
        enabled: Schema.optional(Schema.Boolean),
        include_invoiceless_charges: Schema.optional(Schema.Boolean),
      }),
    ),
    user_access_level: Schema.optional(Schema.NullOr(Schema.String)),
    supports_webhooks: Schema.optional(Schema.Boolean),
  });
export const ExternalDataSourceBulkUpdateSchemaSchema =
  /*@__PURE__*/ /*#__PURE__*/ Schema.Struct({
    id: Schema.optional(Schema.String),
    should_sync: Schema.optional(Schema.Boolean),
    sync_type: Schema.optional(Schema.Unknown),
    incremental_field: Schema.optional(Schema.NullOr(Schema.String)),
    incremental_field_type: Schema.optional(Schema.NullOr(Schema.String)),
    sync_frequency: Schema.optional(Schema.NullOr(Schema.String)),
    sync_time_of_day: Schema.optional(Schema.NullOr(Schema.String)),
    cdc_table_mode: Schema.optional(Schema.Unknown),
  });
export const ExternalDataSourceConnectionOptionSchema =
  /*@__PURE__*/ /*#__PURE__*/ Schema.Struct({
    id: Schema.optional(Schema.String),
    prefix: Schema.optional(Schema.NullOr(Schema.String)),
    engine: Schema.optional(Schema.Unknown),
  });
export const InsightVariableSchema = /*@__PURE__*/ /*#__PURE__*/ Schema.Struct({
  id: Schema.optional(Schema.String),
  name: Schema.optional(Schema.String),
  type: Schema.optional(
    Schema.Literals(["String", "Number", "Boolean", "List", "Date"]),
  ),
  default_value: Schema.optional(Schema.NullOr(Schema.Unknown)),
  created_by: Schema.optional(Schema.NullOr(Schema.Number)),
  created_at: Schema.optional(Schema.String),
  code_name: Schema.optional(Schema.NullOr(Schema.String)),
  values: Schema.optional(Schema.NullOr(Schema.Unknown)),
});
export const DataWarehouseSavedQueryMinimalSchema =
  /*@__PURE__*/ /*#__PURE__*/ Schema.Struct({
    id: Schema.optional(Schema.String),
    deleted: Schema.optional(Schema.NullOr(Schema.Boolean)),
    name: Schema.optional(Schema.String),
    created_by: Schema.optional(
      Schema.NullOr(
        Schema.Struct({
          id: Schema.optional(Schema.Number),
          uuid: Schema.optional(Schema.String),
          distinct_id: Schema.optional(Schema.NullOr(Schema.String)),
          first_name: Schema.optional(Schema.String),
          last_name: Schema.optional(Schema.String),
          email: Schema.optional(Schema.String),
          is_email_verified: Schema.optional(Schema.NullOr(Schema.Boolean)),
          hedgehog_config: Schema.optional(
            Schema.NullOr(Schema.Record(Schema.String, Schema.Unknown)),
          ),
          role_at_organization: Schema.optional(Schema.Unknown),
        }),
      ),
    ),
    created_at: Schema.optional(Schema.String),
    sync_frequency: Schema.optional(Schema.NullOr(Schema.String)),
    columns: Schema.optional(
      Schema.Array(Schema.Record(Schema.String, Schema.Unknown)),
    ),
    status: Schema.optional(Schema.Unknown),
    last_run_at: Schema.optional(Schema.NullOr(Schema.String)),
    managed_viewset_kind: Schema.optional(Schema.NullOr(Schema.String)),
    folder_id: Schema.optional(Schema.NullOr(Schema.String)),
    folder_name: Schema.optional(Schema.NullOr(Schema.String)),
    latest_error: Schema.optional(Schema.NullOr(Schema.String)),
    is_materialized: Schema.optional(Schema.NullOr(Schema.Boolean)),
    origin: Schema.optional(Schema.Unknown),
    is_test: Schema.optional(Schema.Boolean),
    expires_at: Schema.optional(Schema.NullOr(Schema.String)),
  });
export const DataWarehouseSavedQueryFolderSchema =
  /*@__PURE__*/ /*#__PURE__*/ Schema.Struct({
    id: Schema.optional(Schema.String),
    name: Schema.optional(Schema.String),
    created_at: Schema.optional(Schema.String),
    created_by: Schema.optional(
      Schema.NullOr(
        Schema.Struct({
          id: Schema.optional(Schema.Number),
          uuid: Schema.optional(Schema.String),
          distinct_id: Schema.optional(Schema.NullOr(Schema.String)),
          first_name: Schema.optional(Schema.String),
          last_name: Schema.optional(Schema.String),
          email: Schema.optional(Schema.String),
          is_email_verified: Schema.optional(Schema.NullOr(Schema.Boolean)),
          hedgehog_config: Schema.optional(
            Schema.NullOr(Schema.Record(Schema.String, Schema.Unknown)),
          ),
          role_at_organization: Schema.optional(Schema.Unknown),
        }),
      ),
    ),
    view_count: Schema.optional(Schema.Number),
  });
