import * as Schema from "effect/Schema";
import { API } from "../../client.ts";
import * as T from "../../traits.ts";
import { BadRequest, Forbidden, NotFound } from "../../errors.ts";

// Input Schema
export const ExternalDataSourcesDatabaseSchemaCreateInput =
  /*@__PURE__*/ /*#__PURE__*/ Schema.Struct({
    project_id: Schema.String.pipe(T.PathParam()),
    source_type: Schema.Literals([
      "Ashby",
      "Supabase",
      "CustomerIO",
      "Github",
      "Stripe",
      "Hubspot",
      "Postgres",
      "Zendesk",
      "Snowflake",
      "Salesforce",
      "MySQL",
      "MongoDB",
      "MSSQL",
      "Vitally",
      "BigQuery",
      "Chargebee",
      "Clerk",
      "GoogleAds",
      "TemporalIO",
      "DoIt",
      "GoogleSheets",
      "MetaAds",
      "Klaviyo",
      "Mailchimp",
      "Braze",
      "Mailjet",
      "Redshift",
      "Polar",
      "RevenueCat",
      "LinkedinAds",
      "RedditAds",
      "TikTokAds",
      "BingAds",
      "Shopify",
      "Attio",
      "SnapchatAds",
      "Linear",
      "Intercom",
      "Amplitude",
      "Mixpanel",
      "Jira",
      "ActiveCampaign",
      "Marketo",
      "Adjust",
      "AppsFlyer",
      "Freshdesk",
      "GoogleAnalytics",
      "Pipedrive",
      "SendGrid",
      "Slack",
      "PagerDuty",
      "Asana",
      "Notion",
      "Airtable",
      "Greenhouse",
      "BambooHR",
      "Lever",
      "GitLab",
      "Datadog",
      "Sentry",
      "Pendo",
      "FullStory",
      "AmazonAds",
      "PinterestAds",
      "AppleSearchAds",
      "QuickBooks",
      "Xero",
      "NetSuite",
      "WooCommerce",
      "BigCommerce",
      "PayPal",
      "Square",
      "Zoom",
      "Trello",
      "Monday",
      "ClickUp",
      "Confluence",
      "Recurly",
      "SalesLoft",
      "Outreach",
      "Gong",
      "Calendly",
      "Typeform",
      "Iterable",
      "ZohoCRM",
      "Close",
      "Oracle",
      "DynamoDB",
      "Elasticsearch",
      "Kafka",
      "LaunchDarkly",
      "Braintree",
      "Recharge",
      "HelpScout",
      "Gorgias",
      "Instagram",
      "YouTubeAnalytics",
      "FacebookPages",
      "TwitterAds",
      "Workday",
      "ServiceNow",
      "Pardot",
      "Copper",
      "Front",
      "ChartMogul",
      "Zuora",
      "Paddle",
      "CircleCI",
      "CockroachDB",
      "Firebase",
      "AzureBlob",
      "GoogleDrive",
      "OneDrive",
      "SharePoint",
      "Box",
      "SFTP",
      "MicrosoftTeams",
      "Aircall",
      "Webflow",
      "Okta",
      "Auth0",
      "Productboard",
      "Smartsheet",
      "Wrike",
      "Plaid",
      "SurveyMonkey",
      "Eventbrite",
      "RingCentral",
      "Twilio",
      "Freshsales",
      "Shortcut",
      "ConvertKit",
      "Drip",
      "CampaignMonitor",
      "MailerLite",
      "Omnisend",
      "Brevo",
      "Postmark",
      "Granola",
      "BuildBetter",
      "Convex",
      "ClickHouse",
      "Plain",
    ]),
  }).pipe(
    T.Http({
      method: "POST",
      path: "/api/projects/{project_id}/external_data_sources/database_schema/",
    }),
  );
export type ExternalDataSourcesDatabaseSchemaCreateInput =
  typeof ExternalDataSourcesDatabaseSchemaCreateInput.Type;

// Output Schema
export const ExternalDataSourcesDatabaseSchemaCreateOutput =
  /*@__PURE__*/ /*#__PURE__*/ Schema.Void;
export type ExternalDataSourcesDatabaseSchemaCreateOutput =
  typeof ExternalDataSourcesDatabaseSchemaCreateOutput.Type;

// The operation
/**
 * Create, Read, Update and Delete External data Sources.
 *
 * @param project_id - Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/.
 */
export const externalDataSourcesDatabaseSchemaCreate =
  /*@__PURE__*/ /*#__PURE__*/ API.make(() => ({
    inputSchema: ExternalDataSourcesDatabaseSchemaCreateInput,
    outputSchema: ExternalDataSourcesDatabaseSchemaCreateOutput,
    errors: [BadRequest, Forbidden, NotFound] as const,
  }));
