// AUTO-GENERATED by scripts/generate.ts from .generated-specs (specs/api-v1-native.json + api-v1-stable.json). Do not edit.
import * as S from "@distilled.cloud/core/schema";
import * as API from "@distilled.cloud/core/api";
import * as C from "@distilled.cloud/core/category";
import * as T from "../traits.ts";
import {
  WhopProtocol,
  type WhopOpError,
  type WhopOpContext,
} from "../protocol.ts";
import { paginateRelay } from "../pagination.ts";
import * as Retry from "../retry.ts";

export type { WhopOpError, WhopOpContext };

export class BadRequest
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<BadRequest>()("BadRequest", {
      code: S.Number,
      message: S.String,
    }).pipe(C.withBadRequestError),
    [{ status: 400 }],
  ) {}

export class NotFound
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<NotFound>()("NotFound", {
      code: S.Number,
      message: S.String,
    }).pipe(C.withBadRequestError),
    [{ status: 404 }],
  ) {}

export type ListPeopleRequestSourceList = Array<string>;
export const ListPeopleRequestSourceList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<ListPeopleRequestSourceList>;

export type ListPeopleRequestAttributionModel = "last_touch" | "first_touch";
export const ListPeopleRequestAttributionModel = /*@__PURE__*/ S.String;

export type ListPeopleRequestEventNameList = Array<string>;
export const ListPeopleRequestEventNameList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<ListPeopleRequestEventNameList>;

export type ListPeopleRequestOrder =
  | "first_seen_at"
  | "last_seen_at"
  | "first_purchase_at"
  | "last_purchase_at"
  | "purchase_count"
  | "event_count"
  | "ltv"
  | "aov"
  | "name"
  | "email";
export const ListPeopleRequestOrder = /*@__PURE__*/ S.String;

export type ListPeopleRequestDirection = "asc" | "desc";
export const ListPeopleRequestDirection = /*@__PURE__*/ S.String;

export interface ListPeopleRequest {
  /** Account ID, prefixed `biz_`. Optional for account API keys; required for credentials that can access multiple accounts. */
  account_id?: string;
  /** Search people by name, email, phone, or whop user ID (case-insensitive substring match). */
  query?: string;
  /** Only include people acquired from any of these sources — canonical paths (whop:<campaign>:<group>:<ad>, ext:<platform>:..., referrer:<domain>, direct, other), exact or with a trailing :* prefix. The same vocabulary the events / people metrics use. */
  source?: ListPeopleRequestSourceList;
  /** Attribution model the source filter matches against (defaults to last_touch). */
  attribution_model?: ListPeopleRequestAttributionModel | (string & {});
  /** Only include people who fired any of these events, e.g. payment.completed or page.checkout.view. */
  event_name?: ListPeopleRequestEventNameList;
  /** Only include people who fired this custom pixel event. */
  custom_event?: string;
  /** With event_to plus an event or source filter, switches to exact-population mode: person ids are resolved and paginated on the events side within this window (the same query the people metric counts), then hydrated per page. */
  event_from?: string;
  /** The inclusive end of the event window for exact-population mode. */
  event_to?: string;
  /** Only include people in this audience. An audience that keeps itself up to date resolves to the People filters that define it, so this always reflects who matches now; uploaded lists and point-in-time snapshots match their recorded members. */
  audience_id?: string;
  /** Only include the person linked to this whop user ID. */
  user_id?: string;
  /** Only include the person linked to this email address. */
  email?: string;
  /** Only include the person linked to this phone number. */
  phone?: string;
  /** Only include people whose most recent visit came from this ISO 3166-1 alpha-2 country code. */
  country?: string;
  /** true for customers only, false for people who have never purchased. */
  has_purchased?: boolean;
  /** true for people who have an email address or phone number — the ones an ad platform can match. */
  contactable?: boolean;
  /** Only include people first seen within this many days, as a rolling window. */
  first_seen_within_days?: number;
  /** Only include people last seen within this many days, as a rolling window. */
  last_seen_within_days?: number;
  /** Only include people first seen at or after this ISO 8601 timestamp. */
  first_seen_after?: string;
  /** Only include people first seen before this ISO 8601 timestamp. */
  first_seen_before?: string;
  /** Only include people last seen at or after this ISO 8601 timestamp. */
  last_seen_after?: string;
  /** Only include people last seen before this ISO 8601 timestamp. */
  last_seen_before?: string;
  /** The number of people to return (default 100, max 100). */
  first?: number;
  /** A cursor for fetching people after a previous page. */
  after?: string;
  /** A cursor for fetching people before a later page. */
  before?: string;
  /** Column to sort by. Defaults to last_seen_at. */
  order?: ListPeopleRequestOrder | (string & {});
  /** Sort direction. Defaults to desc. */
  direction?: ListPeopleRequestDirection | (string & {});
}
export const ListPeopleRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    account_id: S.optional(S.String.pipe(T.Query())),
    query: S.optional(S.String.pipe(T.Query())),
    source: S.optional(ListPeopleRequestSourceList.pipe(T.Query())),
    attribution_model: S.optional(
      ListPeopleRequestAttributionModel.pipe(T.Query()),
    ),
    event_name: S.optional(ListPeopleRequestEventNameList.pipe(T.Query())),
    custom_event: S.optional(S.String.pipe(T.Query())),
    event_from: S.optional(S.String.pipe(T.Query())),
    event_to: S.optional(S.String.pipe(T.Query())),
    audience_id: S.optional(S.String.pipe(T.Query())),
    user_id: S.optional(S.String.pipe(T.Query())),
    email: S.optional(S.String.pipe(T.Query())),
    phone: S.optional(S.String.pipe(T.Query())),
    country: S.optional(S.String.pipe(T.Query())),
    has_purchased: S.optional(S.Boolean.pipe(T.Query())),
    contactable: S.optional(S.Boolean.pipe(T.Query())),
    first_seen_within_days: S.optional(S.Number.pipe(T.Query())),
    last_seen_within_days: S.optional(S.Number.pipe(T.Query())),
    first_seen_after: S.optional(S.String.pipe(T.Query())),
    first_seen_before: S.optional(S.String.pipe(T.Query())),
    last_seen_after: S.optional(S.String.pipe(T.Query())),
    last_seen_before: S.optional(S.String.pipe(T.Query())),
    first: S.optional(S.Number.pipe(T.Query())),
    after: S.optional(S.String.pipe(T.Query())),
    before: S.optional(S.String.pipe(T.Query())),
    order: S.optional(ListPeopleRequestOrder.pipe(T.Query())),
    direction: S.optional(ListPeopleRequestDirection.pipe(T.Query())),
  }).pipe(T.Http({ method: "GET", uri: "/people", code: 200 })),
).annotate({
  identifier: "ListPeopleRequest",
}) as any as S.Schema<ListPeopleRequest>;

export interface ListPeopleResponseDataItemDevice {
  browser?: string | null;
  device?: string | null;
  os?: string | null;
}
export const ListPeopleResponseDataItemDevice = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    browser: S.optional(S.NullOr(S.String)),
    device: S.optional(S.NullOr(S.String)),
    os: S.optional(S.NullOr(S.String)),
  }),
).annotate({
  identifier: "ListPeopleResponseDataItemDevice",
}) as any as S.Schema<ListPeopleResponseDataItemDevice>;

export interface ListPeopleResponseDataItemFirstSourceAd {
  id: string;
  name?: string | null;
  thumbnail_url?: string | null;
}
export const ListPeopleResponseDataItemFirstSourceAd = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      id: S.String,
      name: S.optional(S.NullOr(S.String)),
      thumbnail_url: S.optional(S.NullOr(S.String)),
    }),
).annotate({
  identifier: "ListPeopleResponseDataItemFirstSourceAd",
}) as any as S.Schema<ListPeopleResponseDataItemFirstSourceAd>;

export type ListPeopleResponseDataItemFirstSourceAdGroup =
  ListPeopleResponseDataItemFirstSourceAd;
export const ListPeopleResponseDataItemFirstSourceAdGroup =
  ListPeopleResponseDataItemFirstSourceAd;

export type ListPeopleResponseDataItemFirstSourceCampaign =
  ListPeopleResponseDataItemFirstSourceAd;
export const ListPeopleResponseDataItemFirstSourceCampaign =
  ListPeopleResponseDataItemFirstSourceAd;

export type ListPeopleResponseDataItemFirstSourceType =
  | "ad_click"
  | "lead_form"
  | "external_ad_click"
  | "referrer"
  | "utm";
export const ListPeopleResponseDataItemFirstSourceType = /*@__PURE__*/ S.String;

/** Where a visit came from: a whop ad click, a lead form, an external ad, or a referring site. */
export interface ListPeopleResponseDataItemFirstSource {
  ad?: ListPeopleResponseDataItemFirstSourceAd | null;
  ad_group?: ListPeopleResponseDataItemFirstSourceAd | null;
  campaign?: ListPeopleResponseDataItemFirstSourceAd | null;
  domain?: string | null;
  occurred_at?: string | null;
  platform?: string | null;
  type: ListPeopleResponseDataItemFirstSourceType;
  utm_source?: string | null;
}
export const ListPeopleResponseDataItemFirstSource = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      ad: S.optional(S.NullOr(ListPeopleResponseDataItemFirstSourceAd)),
      ad_group: S.optional(S.NullOr(ListPeopleResponseDataItemFirstSourceAd)),
      campaign: S.optional(S.NullOr(ListPeopleResponseDataItemFirstSourceAd)),
      domain: S.optional(S.NullOr(S.String)),
      occurred_at: S.optional(S.NullOr(S.String)),
      platform: S.optional(S.NullOr(S.String)),
      type: ListPeopleResponseDataItemFirstSourceType,
      utm_source: S.optional(S.NullOr(S.String)),
    }),
).annotate({
  identifier: "ListPeopleResponseDataItemFirstSource",
}) as any as S.Schema<ListPeopleResponseDataItemFirstSource>;

export type ListPeopleResponseDataItemLastSourceAd =
  ListPeopleResponseDataItemFirstSourceAd;
export const ListPeopleResponseDataItemLastSourceAd =
  ListPeopleResponseDataItemFirstSourceAd;

export type ListPeopleResponseDataItemLastSourceAdGroup =
  ListPeopleResponseDataItemFirstSourceAd;
export const ListPeopleResponseDataItemLastSourceAdGroup =
  ListPeopleResponseDataItemFirstSourceAd;

export type ListPeopleResponseDataItemLastSourceCampaign =
  ListPeopleResponseDataItemFirstSourceAd;
export const ListPeopleResponseDataItemLastSourceCampaign =
  ListPeopleResponseDataItemFirstSourceAd;

export type ListPeopleResponseDataItemLastSourceType =
  | "ad_click"
  | "lead_form"
  | "external_ad_click"
  | "referrer"
  | "utm";
export const ListPeopleResponseDataItemLastSourceType = /*@__PURE__*/ S.String;

/** Where a visit came from: a whop ad click, a lead form, an external ad, or a referring site. */
export interface ListPeopleResponseDataItemLastSource {
  ad?: ListPeopleResponseDataItemFirstSourceAd | null;
  ad_group?: ListPeopleResponseDataItemFirstSourceAd | null;
  campaign?: ListPeopleResponseDataItemFirstSourceAd | null;
  domain?: string | null;
  occurred_at?: string | null;
  platform?: string | null;
  type: ListPeopleResponseDataItemLastSourceType;
  utm_source?: string | null;
}
export const ListPeopleResponseDataItemLastSource = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      ad: S.optional(S.NullOr(ListPeopleResponseDataItemFirstSourceAd)),
      ad_group: S.optional(S.NullOr(ListPeopleResponseDataItemFirstSourceAd)),
      campaign: S.optional(S.NullOr(ListPeopleResponseDataItemFirstSourceAd)),
      domain: S.optional(S.NullOr(S.String)),
      occurred_at: S.optional(S.NullOr(S.String)),
      platform: S.optional(S.NullOr(S.String)),
      type: ListPeopleResponseDataItemLastSourceType,
      utm_source: S.optional(S.NullOr(S.String)),
    }),
).annotate({
  identifier: "ListPeopleResponseDataItemLastSource",
}) as any as S.Schema<ListPeopleResponseDataItemLastSource>;

export interface ListPeopleResponseDataItemLocation {
  city?: string | null;
  continent?: string | null;
  country?: string | null;
}
export const ListPeopleResponseDataItemLocation = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    city: S.optional(S.NullOr(S.String)),
    continent: S.optional(S.NullOr(S.String)),
    country: S.optional(S.NullOr(S.String)),
  }),
).annotate({
  identifier: "ListPeopleResponseDataItemLocation",
}) as any as S.Schema<ListPeopleResponseDataItemLocation>;

/** The user's member record at this account, when they are a member of it. */
export interface ListPeopleResponseDataItemMember {
  id: string;
  joined_at?: string | null;
  status?: string | null;
  usd_total_spend?: number;
}
export const ListPeopleResponseDataItemMember = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String,
    joined_at: S.optional(S.NullOr(S.String)),
    status: S.optional(S.NullOr(S.String)),
    usd_total_spend: S.optional(S.Number),
  }),
).annotate({
  identifier: "ListPeopleResponseDataItemMember",
}) as any as S.Schema<ListPeopleResponseDataItemMember>;

/** The person's primary whop user, when one of their identities is a whop account. */
export interface ListPeopleResponseDataItemUser {
  id: string;
  name?: string | null;
  profile_pic_url?: string | null;
  username: string;
}
export const ListPeopleResponseDataItemUser = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String,
    name: S.optional(S.NullOr(S.String)),
    profile_pic_url: S.optional(S.NullOr(S.String)),
    username: S.String,
  }),
).annotate({
  identifier: "ListPeopleResponseDataItemUser",
}) as any as S.Schema<ListPeopleResponseDataItemUser>;

export interface ListPeopleResponseDataItem {
  account_id: string;
  aov?: number;
  device?: ListPeopleResponseDataItemDevice;
  /** The email from the person's most recent event that carried one. */
  email?: string | null;
  event_count: number;
  first_purchase_at?: string | null;
  first_seen_at: string;
  /** Where a visit came from: a whop ad click, a lead form, an external ad, or a referring site. */
  first_source?: ListPeopleResponseDataItemFirstSource | null;
  id: string;
  last_ip?: string | null;
  last_purchase_at?: string | null;
  last_seen_at: string;
  /** Where a visit came from: a whop ad click, a lead form, an external ad, or a referring site. */
  last_source?: ListPeopleResponseDataItemLastSource | null;
  location?: ListPeopleResponseDataItemLocation;
  ltv?: number;
  /** The user's member record at this account, when they are a member of it. */
  member?: ListPeopleResponseDataItemMember | null;
  /** The name from the person's most recent event that carried one. */
  name?: string | null;
  /** The phone from the person's most recent event that carried one. */
  phone?: string | null;
  purchase_count: number;
  timezone?: string | null;
  /** The person's primary whop user, when one of their identities is a whop account. */
  user?: ListPeopleResponseDataItemUser | null;
}
export const ListPeopleResponseDataItem = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    account_id: S.String,
    aov: S.optional(S.Number),
    device: S.optional(ListPeopleResponseDataItemDevice),
    email: S.optional(S.NullOr(S.String)),
    event_count: S.Number,
    first_purchase_at: S.optional(S.NullOr(S.String)),
    first_seen_at: S.String,
    first_source: S.optional(S.NullOr(ListPeopleResponseDataItemFirstSource)),
    id: S.String,
    last_ip: S.optional(S.NullOr(S.String)),
    last_purchase_at: S.optional(S.NullOr(S.String)),
    last_seen_at: S.String,
    last_source: S.optional(S.NullOr(ListPeopleResponseDataItemLastSource)),
    location: S.optional(ListPeopleResponseDataItemLocation),
    ltv: S.optional(S.Number),
    member: S.optional(S.NullOr(ListPeopleResponseDataItemMember)),
    name: S.optional(S.NullOr(S.String)),
    phone: S.optional(S.NullOr(S.String)),
    purchase_count: S.Number,
    timezone: S.optional(S.NullOr(S.String)),
    user: S.optional(S.NullOr(ListPeopleResponseDataItemUser)),
  }),
).annotate({
  identifier: "ListPeopleResponseDataItem",
}) as any as S.Schema<ListPeopleResponseDataItem>;

export type ListPeopleResponseDataList = Array<ListPeopleResponseDataItem>;
export const ListPeopleResponseDataList = /*@__PURE__*/ S.Array(
  ListPeopleResponseDataItem,
) as any as S.Schema<ListPeopleResponseDataList>;

export interface ListPeopleResponsePageInfo {
  end_cursor?: string | null;
  has_next_page: boolean;
  has_previous_page: boolean;
  start_cursor?: string | null;
}
export const ListPeopleResponsePageInfo = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    end_cursor: S.optional(S.NullOr(S.String)),
    has_next_page: S.Boolean,
    has_previous_page: S.Boolean,
    start_cursor: S.optional(S.NullOr(S.String)),
  }),
).annotate({
  identifier: "ListPeopleResponsePageInfo",
}) as any as S.Schema<ListPeopleResponsePageInfo>;

export interface ListPeopleResponse {
  data: ListPeopleResponseDataList;
  page_info: ListPeopleResponsePageInfo;
  total_count?: number;
}
export const ListPeopleResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    data: ListPeopleResponseDataList,
    page_info: ListPeopleResponsePageInfo,
    total_count: S.optional(S.Number),
  }),
).annotate({
  identifier: "ListPeopleResponse",
}) as any as S.Schema<ListPeopleResponse>;

export interface RetrievePersonRequest {
  /** The person ID, user ID, email address, or phone number to look up. */
  id: string;
  /** Account ID, prefixed `biz_`. Optional for account API keys; required for credentials that can access multiple accounts. */
  account_id?: string;
}
export const RetrievePersonRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String.pipe(T.Label()),
    account_id: S.optional(S.String.pipe(T.Query())),
  }).pipe(T.Http({ method: "GET", uri: "/people/{id}", code: 200 })),
).annotate({
  identifier: "RetrievePersonRequest",
}) as any as S.Schema<RetrievePersonRequest>;

export type RetrievePersonResponseAudienceIdsList = Array<string>;
export const RetrievePersonResponseAudienceIdsList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<RetrievePersonResponseAudienceIdsList>;

export type RetrievePersonResponseCustomEventNamesList = Array<string>;
export const RetrievePersonResponseCustomEventNamesList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<RetrievePersonResponseCustomEventNamesList>;

export type RetrievePersonResponseDevice = ListPeopleResponseDataItemDevice;
export const RetrievePersonResponseDevice = ListPeopleResponseDataItemDevice;

/** Every linked email, primary first. */
export type RetrievePersonResponseEmailsList = Array<string>;
export const RetrievePersonResponseEmailsList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<RetrievePersonResponseEmailsList>;

export type RetrievePersonResponseEventNamesList = Array<string>;
export const RetrievePersonResponseEventNamesList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<RetrievePersonResponseEventNamesList>;

export type RetrievePersonResponseFirstSourceAd =
  ListPeopleResponseDataItemFirstSourceAd;
export const RetrievePersonResponseFirstSourceAd =
  ListPeopleResponseDataItemFirstSourceAd;

export type RetrievePersonResponseFirstSourceAdGroup =
  ListPeopleResponseDataItemFirstSourceAd;
export const RetrievePersonResponseFirstSourceAdGroup =
  ListPeopleResponseDataItemFirstSourceAd;

export type RetrievePersonResponseFirstSourceCampaign =
  ListPeopleResponseDataItemFirstSourceAd;
export const RetrievePersonResponseFirstSourceCampaign =
  ListPeopleResponseDataItemFirstSourceAd;

export type RetrievePersonResponseFirstSourceType =
  | "ad_click"
  | "lead_form"
  | "external_ad_click"
  | "referrer"
  | "utm";
export const RetrievePersonResponseFirstSourceType = /*@__PURE__*/ S.String;

/** Where a visit came from: a whop ad click, a lead form, an external ad, or a referring site. */
export interface RetrievePersonResponseFirstSource {
  ad?: ListPeopleResponseDataItemFirstSourceAd | null;
  ad_group?: ListPeopleResponseDataItemFirstSourceAd | null;
  campaign?: ListPeopleResponseDataItemFirstSourceAd | null;
  domain?: string | null;
  occurred_at?: string | null;
  platform?: string | null;
  type: RetrievePersonResponseFirstSourceType;
  utm_source?: string | null;
}
export const RetrievePersonResponseFirstSource = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    ad: S.optional(S.NullOr(ListPeopleResponseDataItemFirstSourceAd)),
    ad_group: S.optional(S.NullOr(ListPeopleResponseDataItemFirstSourceAd)),
    campaign: S.optional(S.NullOr(ListPeopleResponseDataItemFirstSourceAd)),
    domain: S.optional(S.NullOr(S.String)),
    occurred_at: S.optional(S.NullOr(S.String)),
    platform: S.optional(S.NullOr(S.String)),
    type: RetrievePersonResponseFirstSourceType,
    utm_source: S.optional(S.NullOr(S.String)),
  }),
).annotate({
  identifier: "RetrievePersonResponseFirstSource",
}) as any as S.Schema<RetrievePersonResponseFirstSource>;

export type RetrievePersonResponseLastSourceAd =
  ListPeopleResponseDataItemFirstSourceAd;
export const RetrievePersonResponseLastSourceAd =
  ListPeopleResponseDataItemFirstSourceAd;

export type RetrievePersonResponseLastSourceAdGroup =
  ListPeopleResponseDataItemFirstSourceAd;
export const RetrievePersonResponseLastSourceAdGroup =
  ListPeopleResponseDataItemFirstSourceAd;

export type RetrievePersonResponseLastSourceCampaign =
  ListPeopleResponseDataItemFirstSourceAd;
export const RetrievePersonResponseLastSourceCampaign =
  ListPeopleResponseDataItemFirstSourceAd;

export type RetrievePersonResponseLastSourceType =
  | "ad_click"
  | "lead_form"
  | "external_ad_click"
  | "referrer"
  | "utm";
export const RetrievePersonResponseLastSourceType = /*@__PURE__*/ S.String;

/** Where a visit came from: a whop ad click, a lead form, an external ad, or a referring site. */
export interface RetrievePersonResponseLastSource {
  ad?: ListPeopleResponseDataItemFirstSourceAd | null;
  ad_group?: ListPeopleResponseDataItemFirstSourceAd | null;
  campaign?: ListPeopleResponseDataItemFirstSourceAd | null;
  domain?: string | null;
  occurred_at?: string | null;
  platform?: string | null;
  type: RetrievePersonResponseLastSourceType;
  utm_source?: string | null;
}
export const RetrievePersonResponseLastSource = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    ad: S.optional(S.NullOr(ListPeopleResponseDataItemFirstSourceAd)),
    ad_group: S.optional(S.NullOr(ListPeopleResponseDataItemFirstSourceAd)),
    campaign: S.optional(S.NullOr(ListPeopleResponseDataItemFirstSourceAd)),
    domain: S.optional(S.NullOr(S.String)),
    occurred_at: S.optional(S.NullOr(S.String)),
    platform: S.optional(S.NullOr(S.String)),
    type: RetrievePersonResponseLastSourceType,
    utm_source: S.optional(S.NullOr(S.String)),
  }),
).annotate({
  identifier: "RetrievePersonResponseLastSource",
}) as any as S.Schema<RetrievePersonResponseLastSource>;

export type RetrievePersonResponseLocation = ListPeopleResponseDataItemLocation;
export const RetrievePersonResponseLocation =
  ListPeopleResponseDataItemLocation;

/** The user's member record at this account, when they are a member of it. */
export type RetrievePersonResponseMember = ListPeopleResponseDataItemMember;
export const RetrievePersonResponseMember = ListPeopleResponseDataItemMember;

/** Every name the person's linked identities carried, primary first. */
export type RetrievePersonResponseNamesList = Array<string>;
export const RetrievePersonResponseNamesList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<RetrievePersonResponseNamesList>;

/** Every linked phone, primary first. */
export type RetrievePersonResponsePhonesList = Array<string>;
export const RetrievePersonResponsePhonesList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<RetrievePersonResponsePhonesList>;

export interface RetrievePersonResponsePurchasesItem {
  event_id: string;
  occurred_at: string;
  usd_value: number;
}
export const RetrievePersonResponsePurchasesItem = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    event_id: S.String,
    occurred_at: S.String,
    usd_value: S.Number,
  }),
).annotate({
  identifier: "RetrievePersonResponsePurchasesItem",
}) as any as S.Schema<RetrievePersonResponsePurchasesItem>;

export type RetrievePersonResponsePurchasesList =
  Array<RetrievePersonResponsePurchasesItem>;
export const RetrievePersonResponsePurchasesList = /*@__PURE__*/ S.Array(
  RetrievePersonResponsePurchasesItem,
) as any as S.Schema<RetrievePersonResponsePurchasesList>;

export type RetrievePersonResponseRolesList = Array<string>;
export const RetrievePersonResponseRolesList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<RetrievePersonResponseRolesList>;

export type RetrievePersonResponseSourcesItemAd =
  ListPeopleResponseDataItemFirstSourceAd;
export const RetrievePersonResponseSourcesItemAd =
  ListPeopleResponseDataItemFirstSourceAd;

export type RetrievePersonResponseSourcesItemAdGroup =
  ListPeopleResponseDataItemFirstSourceAd;
export const RetrievePersonResponseSourcesItemAdGroup =
  ListPeopleResponseDataItemFirstSourceAd;

export type RetrievePersonResponseSourcesItemCampaign =
  ListPeopleResponseDataItemFirstSourceAd;
export const RetrievePersonResponseSourcesItemCampaign =
  ListPeopleResponseDataItemFirstSourceAd;

export type RetrievePersonResponseSourcesItemType =
  | "ad_click"
  | "lead_form"
  | "external_ad_click"
  | "referrer"
  | "utm";
export const RetrievePersonResponseSourcesItemType = /*@__PURE__*/ S.String;

/** Where a visit came from: a whop ad click, a lead form, an external ad, or a referring site. */
export interface RetrievePersonResponseSourcesItem {
  ad?: ListPeopleResponseDataItemFirstSourceAd | null;
  ad_group?: ListPeopleResponseDataItemFirstSourceAd | null;
  campaign?: ListPeopleResponseDataItemFirstSourceAd | null;
  domain?: string | null;
  occurred_at?: string | null;
  platform?: string | null;
  type: RetrievePersonResponseSourcesItemType;
  utm_source?: string | null;
}
export const RetrievePersonResponseSourcesItem = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    ad: S.optional(S.NullOr(ListPeopleResponseDataItemFirstSourceAd)),
    ad_group: S.optional(S.NullOr(ListPeopleResponseDataItemFirstSourceAd)),
    campaign: S.optional(S.NullOr(ListPeopleResponseDataItemFirstSourceAd)),
    domain: S.optional(S.NullOr(S.String)),
    occurred_at: S.optional(S.NullOr(S.String)),
    platform: S.optional(S.NullOr(S.String)),
    type: RetrievePersonResponseSourcesItemType,
    utm_source: S.optional(S.NullOr(S.String)),
  }),
).annotate({
  identifier: "RetrievePersonResponseSourcesItem",
}) as any as S.Schema<RetrievePersonResponseSourcesItem>;

/** Every distinct acquisition signal the person ever carried, ad entities hydrated. */
export type RetrievePersonResponseSourcesList =
  Array<RetrievePersonResponseSourcesItem>;
export const RetrievePersonResponseSourcesList = /*@__PURE__*/ S.Array(
  RetrievePersonResponseSourcesItem,
) as any as S.Schema<RetrievePersonResponseSourcesList>;

export interface RetrievePersonResponseUsageBrowserItem {
  events: number;
  value: string;
}
export const RetrievePersonResponseUsageBrowserItem = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      events: S.Number,
      value: S.String,
    }),
).annotate({
  identifier: "RetrievePersonResponseUsageBrowserItem",
}) as any as S.Schema<RetrievePersonResponseUsageBrowserItem>;

export type RetrievePersonResponseUsageBrowserList =
  Array<RetrievePersonResponseUsageBrowserItem>;
export const RetrievePersonResponseUsageBrowserList = /*@__PURE__*/ S.Array(
  RetrievePersonResponseUsageBrowserItem,
) as any as S.Schema<RetrievePersonResponseUsageBrowserList>;

export type RetrievePersonResponseUsageCityItem =
  RetrievePersonResponseUsageBrowserItem;
export const RetrievePersonResponseUsageCityItem =
  RetrievePersonResponseUsageBrowserItem;

export type RetrievePersonResponseUsageCityList =
  Array<RetrievePersonResponseUsageBrowserItem>;
export const RetrievePersonResponseUsageCityList = /*@__PURE__*/ S.Array(
  RetrievePersonResponseUsageBrowserItem,
) as any as S.Schema<RetrievePersonResponseUsageCityList>;

export type RetrievePersonResponseUsageCountryItem =
  RetrievePersonResponseUsageBrowserItem;
export const RetrievePersonResponseUsageCountryItem =
  RetrievePersonResponseUsageBrowserItem;

export type RetrievePersonResponseUsageCountryList =
  Array<RetrievePersonResponseUsageBrowserItem>;
export const RetrievePersonResponseUsageCountryList = /*@__PURE__*/ S.Array(
  RetrievePersonResponseUsageBrowserItem,
) as any as S.Schema<RetrievePersonResponseUsageCountryList>;

export type RetrievePersonResponseUsageDeviceItem =
  RetrievePersonResponseUsageBrowserItem;
export const RetrievePersonResponseUsageDeviceItem =
  RetrievePersonResponseUsageBrowserItem;

export type RetrievePersonResponseUsageDeviceList =
  Array<RetrievePersonResponseUsageBrowserItem>;
export const RetrievePersonResponseUsageDeviceList = /*@__PURE__*/ S.Array(
  RetrievePersonResponseUsageBrowserItem,
) as any as S.Schema<RetrievePersonResponseUsageDeviceList>;

export type RetrievePersonResponseUsageIpItem =
  RetrievePersonResponseUsageBrowserItem;
export const RetrievePersonResponseUsageIpItem =
  RetrievePersonResponseUsageBrowserItem;

export type RetrievePersonResponseUsageIpList =
  Array<RetrievePersonResponseUsageBrowserItem>;
export const RetrievePersonResponseUsageIpList = /*@__PURE__*/ S.Array(
  RetrievePersonResponseUsageBrowserItem,
) as any as S.Schema<RetrievePersonResponseUsageIpList>;

export type RetrievePersonResponseUsageOsItem =
  RetrievePersonResponseUsageBrowserItem;
export const RetrievePersonResponseUsageOsItem =
  RetrievePersonResponseUsageBrowserItem;

export type RetrievePersonResponseUsageOsList =
  Array<RetrievePersonResponseUsageBrowserItem>;
export const RetrievePersonResponseUsageOsList = /*@__PURE__*/ S.Array(
  RetrievePersonResponseUsageBrowserItem,
) as any as S.Schema<RetrievePersonResponseUsageOsList>;

export type RetrievePersonResponseUsageReferrerItem =
  RetrievePersonResponseUsageBrowserItem;
export const RetrievePersonResponseUsageReferrerItem =
  RetrievePersonResponseUsageBrowserItem;

export type RetrievePersonResponseUsageReferrerList =
  Array<RetrievePersonResponseUsageBrowserItem>;
export const RetrievePersonResponseUsageReferrerList = /*@__PURE__*/ S.Array(
  RetrievePersonResponseUsageBrowserItem,
) as any as S.Schema<RetrievePersonResponseUsageReferrerList>;

export type RetrievePersonResponseUsageTimezoneItem =
  RetrievePersonResponseUsageBrowserItem;
export const RetrievePersonResponseUsageTimezoneItem =
  RetrievePersonResponseUsageBrowserItem;

export type RetrievePersonResponseUsageTimezoneList =
  Array<RetrievePersonResponseUsageBrowserItem>;
export const RetrievePersonResponseUsageTimezoneList = /*@__PURE__*/ S.Array(
  RetrievePersonResponseUsageBrowserItem,
) as any as S.Schema<RetrievePersonResponseUsageTimezoneList>;

/** Exact usage breakdowns for the person's browser traffic (distinct events per value). */
export interface RetrievePersonResponseUsage {
  browser?: RetrievePersonResponseUsageBrowserList;
  city?: RetrievePersonResponseUsageCityList;
  country?: RetrievePersonResponseUsageCountryList;
  device?: RetrievePersonResponseUsageDeviceList;
  ip?: RetrievePersonResponseUsageIpList;
  os?: RetrievePersonResponseUsageOsList;
  referrer?: RetrievePersonResponseUsageReferrerList;
  timezone?: RetrievePersonResponseUsageTimezoneList;
}
export const RetrievePersonResponseUsage = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    browser: S.optional(RetrievePersonResponseUsageBrowserList),
    city: S.optional(RetrievePersonResponseUsageCityList),
    country: S.optional(RetrievePersonResponseUsageCountryList),
    device: S.optional(RetrievePersonResponseUsageDeviceList),
    ip: S.optional(RetrievePersonResponseUsageIpList),
    os: S.optional(RetrievePersonResponseUsageOsList),
    referrer: S.optional(RetrievePersonResponseUsageReferrerList),
    timezone: S.optional(RetrievePersonResponseUsageTimezoneList),
  }),
).annotate({
  identifier: "RetrievePersonResponseUsage",
}) as any as S.Schema<RetrievePersonResponseUsage>;

/** The person's primary whop user, when one of their identities is a whop account. */
export type RetrievePersonResponseUser = ListPeopleResponseDataItemUser;
export const RetrievePersonResponseUser = ListPeopleResponseDataItemUser;

/** Every linked whop account, the most used one first. */
export type RetrievePersonResponseUserIdsList = Array<string>;
export const RetrievePersonResponseUserIdsList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<RetrievePersonResponseUserIdsList>;

export interface RetrievePersonResponse {
  account_id: string;
  aov?: number;
  audience_ids?: RetrievePersonResponseAudienceIdsList;
  custom_event_names?: RetrievePersonResponseCustomEventNamesList;
  device?: ListPeopleResponseDataItemDevice;
  /** The email from the person's most recent event that carried one. */
  email?: string | null;
  /** Every linked email, primary first. */
  emails?: RetrievePersonResponseEmailsList;
  event_count: number;
  event_names?: RetrievePersonResponseEventNamesList;
  first_purchase_at?: string | null;
  first_seen_at: string;
  /** Where a visit came from: a whop ad click, a lead form, an external ad, or a referring site. */
  first_source?: RetrievePersonResponseFirstSource | null;
  id: string;
  last_ip?: string | null;
  last_purchase_at?: string | null;
  last_seen_at: string;
  /** Where a visit came from: a whop ad click, a lead form, an external ad, or a referring site. */
  last_source?: RetrievePersonResponseLastSource | null;
  location?: ListPeopleResponseDataItemLocation;
  ltv?: number;
  /** The user's member record at this account, when they are a member of it. */
  member?: ListPeopleResponseDataItemMember | null;
  /** The name from the person's most recent event that carried one. */
  name?: string | null;
  /** Every name the person's linked identities carried, primary first. */
  names?: RetrievePersonResponseNamesList;
  /** The phone from the person's most recent event that carried one. */
  phone?: string | null;
  /** Every linked phone, primary first. */
  phones?: RetrievePersonResponsePhonesList;
  purchase_count: number;
  purchases?: RetrievePersonResponsePurchasesList;
  roles?: RetrievePersonResponseRolesList;
  /** Every distinct acquisition signal the person ever carried, ad entities hydrated. */
  sources?: RetrievePersonResponseSourcesList;
  timezone?: string | null;
  /** Exact usage breakdowns for the person's browser traffic (distinct events per value). */
  usage?: RetrievePersonResponseUsage;
  /** The person's primary whop user, when one of their identities is a whop account. */
  user?: ListPeopleResponseDataItemUser | null;
  /** Every linked whop account, the most used one first. */
  user_ids?: RetrievePersonResponseUserIdsList;
}
export const RetrievePersonResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    account_id: S.String,
    aov: S.optional(S.Number),
    audience_ids: S.optional(RetrievePersonResponseAudienceIdsList),
    custom_event_names: S.optional(RetrievePersonResponseCustomEventNamesList),
    device: S.optional(ListPeopleResponseDataItemDevice),
    email: S.optional(S.NullOr(S.String)),
    emails: S.optional(RetrievePersonResponseEmailsList),
    event_count: S.Number,
    event_names: S.optional(RetrievePersonResponseEventNamesList),
    first_purchase_at: S.optional(S.NullOr(S.String)),
    first_seen_at: S.String,
    first_source: S.optional(S.NullOr(RetrievePersonResponseFirstSource)),
    id: S.String,
    last_ip: S.optional(S.NullOr(S.String)),
    last_purchase_at: S.optional(S.NullOr(S.String)),
    last_seen_at: S.String,
    last_source: S.optional(S.NullOr(RetrievePersonResponseLastSource)),
    location: S.optional(ListPeopleResponseDataItemLocation),
    ltv: S.optional(S.Number),
    member: S.optional(S.NullOr(ListPeopleResponseDataItemMember)),
    name: S.optional(S.NullOr(S.String)),
    names: S.optional(RetrievePersonResponseNamesList),
    phone: S.optional(S.NullOr(S.String)),
    phones: S.optional(RetrievePersonResponsePhonesList),
    purchase_count: S.Number,
    purchases: S.optional(RetrievePersonResponsePurchasesList),
    roles: S.optional(RetrievePersonResponseRolesList),
    sources: S.optional(RetrievePersonResponseSourcesList),
    timezone: S.optional(S.NullOr(S.String)),
    usage: S.optional(RetrievePersonResponseUsage),
    user: S.optional(S.NullOr(ListPeopleResponseDataItemUser)),
    user_ids: S.optional(RetrievePersonResponseUserIdsList),
  }),
).annotate({
  identifier: "RetrievePersonResponse",
}) as any as S.Schema<RetrievePersonResponse>;

export type ListPeopleError = BadRequest | WhopOpError;
/** List People Lists the people (visitors and customers) of an account: the identity-linked person profiles aggregated from every pixel, payment, and platform event — identities, purchases and LTV, geo/device profile, traffic sources, and first/last marketing touches. */
export const listPeople: API.PaginatedOperationMethod<
  ListPeopleRequest,
  ListPeopleResponse,
  ListPeopleError,
  WhopOpContext,
  ListPeopleResponseDataItem
> = /*@__PURE__*/ API.makePaginated(
  () => ({
    input: ListPeopleRequest,
    output: ListPeopleResponse,
    errors: [BadRequest],
    protocol: WhopProtocol,
    retry: Retry.Retry,
    pagination: {
      mode: "relay",
      inputToken: "after",
      outputToken: "page_info.end_cursor",
      hasNextPage: "page_info.has_next_page",
      items: "data",
      pageSize: "first",
    } as const,
  }),
  paginateRelay,
) as any;

export type RetrievePersonError = NotFound | WhopOpError;
/** Retrieve Person Retrieves one person for an account. The identifier can be a person ID (prefixed `prsn_`), a user ID (prefixed `user_`), an email address, or a phone number — merged people resolve to the surviving profile. */
export const retrievePerson: API.OperationMethod<
  RetrievePersonRequest,
  RetrievePersonResponse,
  RetrievePersonError,
  WhopOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: RetrievePersonRequest,
  output: RetrievePersonResponse,
  errors: [NotFound],
  protocol: WhopProtocol,
  retry: Retry.Retry,
}));
