// AUTO-GENERATED by scripts/generate.ts from .generated-specs (see scripts/convert.ts). Do not edit.
import * as S from "@distilled.cloud/core/schema";
import * as API from "@distilled.cloud/core/api";
import * as T from "../traits.ts";
import {
  PosthogProtocol,
  type PosthogOpError,
  type PosthogOpContext,
} from "../protocol.ts";
import * as Retry from "../retry.ts";

export type { PosthogOpError, PosthogOpContext };

/** * `text` - text * `number` - number * `currency` - currency * `percent` - percent * `date` - date * `datetime` - datetime * `boolean` - boolean * `select` - select */
export type CustomPropertyDisplayTypeEnum =
  | "text"
  | "number"
  | "currency"
  | "percent"
  | "date"
  | "datetime"
  | "boolean"
  | "select";
export const CustomPropertyDisplayTypeEnum = /*@__PURE__*/ S.String;

/** * `account` - account * `person` - person * `group` - group */
export type CustomPropertyDefinitionTargetTypeEnum =
  | "account"
  | "person"
  | "group";
export const CustomPropertyDefinitionTargetTypeEnum = /*@__PURE__*/ S.String;

/** * `preset-1` - preset-1 * `preset-2` - preset-2 * `preset-3` - preset-3 * `preset-4` - preset-4 * `preset-5` - preset-5 * `preset-6` - preset-6 * `preset-7` - preset-7 * `preset-8` - preset-8 * `preset-9` - preset-9 * `preset-10` - preset-10 */
export type CustomPropertyOptionColorEnum =
  | "preset-1"
  | "preset-2"
  | "preset-3"
  | "preset-4"
  | "preset-5"
  | "preset-6"
  | "preset-7"
  | "preset-8"
  | "preset-9"
  | "preset-10";
export const CustomPropertyOptionColorEnum = /*@__PURE__*/ S.String;

/** An allowed value of a select custom property. */
export interface CustomPropertyOption {
  /** Server-assigned stable id of the option. Omit for new options; send it back unchanged when editing so renames and removals can be told apart. */
  id?: string | null;
  /** Display label of the option. Stored as the account's value when picked. */
  label: string;
  /** Preset color token used to render the option ('preset-1' through 'preset-10'). * `preset-1` - preset-1 * `preset-2` - preset-2 * `preset-3` - preset-3 * `preset-4` - preset-4 * `preset-5` - preset-5 * `preset-6` - preset-6 * `preset-7` - preset-7 * `preset-8` - preset-8 * `preset-9` - preset-9 * `preset-10` - preset-10 */
  color: CustomPropertyOptionColorEnum;
}
export const CustomPropertyOption = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.NullOr(S.String)),
    label: S.String,
    color: CustomPropertyOptionColorEnum,
  }),
).annotate({
  identifier: "CustomPropertyOption",
}) as any as S.Schema<CustomPropertyOption>;

/** For select properties: the allowed options. Required (non-empty) when display_type is 'select'; cleared server-side for other types. */
export type CustomPropertyDefinitionsCreateRequestOptionsList =
  ReadonlyArray<CustomPropertyOption>;
export const CustomPropertyDefinitionsCreateRequestOptionsList =
  /*@__PURE__*/ S.Array(
    CustomPropertyOption,
  ) as any as S.Schema<CustomPropertyDefinitionsCreateRequestOptionsList>;

export interface CustomPropertyDefinitionsCreateRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  /** Human-readable name of the custom property. Unique within the team. */
  name: string;
  /** Optional description of what the property represents. */
  description?: string | null;
  /** How the property is interpreted and rendered: 'text', 'number', 'currency', 'percent', 'date', 'datetime', 'boolean', or 'select'. * `text` - text * `number` - number * `currency` - currency * `percent` - percent * `date` - date * `datetime` - datetime * `boolean` - boolean * `select` - select */
  display_type: CustomPropertyDisplayTypeEnum;
  /** What entity this property is attached to: 'account' (default), 'person', or 'group'. Person and group properties are populated from a warehouse schema and become usable like any other person/group property (feature flags, cohorts, insights). * `account` - account * `person` - person * `group` - group */
  target_type?: CustomPropertyDefinitionTargetTypeEnum;
  /** For 'group' targets only: which group type (0-4) the property attaches to. Required when target_type is 'group'; must be omitted otherwise. Create-only. */
  group_type_index?: number | null;
  /** Abbreviate large numbers (e.g. 10,000 → 10K). Only applies to numeric properties. */
  is_big_number?: boolean;
  /** For select properties: the allowed options. Required (non-empty) when display_type is 'select'; cleared server-side for other types. */
  options?: CustomPropertyDefinitionsCreateRequestOptionsList | null;
}
export const CustomPropertyDefinitionsCreateRequest = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      project_id: S.String.pipe(T.Label()),
      name: S.String,
      description: S.optional(S.NullOr(S.String)),
      display_type: CustomPropertyDisplayTypeEnum,
      target_type: S.optional(CustomPropertyDefinitionTargetTypeEnum),
      group_type_index: S.optional(S.NullOr(S.Number)),
      is_big_number: S.optional(S.Boolean),
      options: S.optional(
        S.NullOr(CustomPropertyDefinitionsCreateRequestOptionsList),
      ),
    }).pipe(
      T.Http({
        method: "POST",
        uri: "/api/projects/{project_id}/custom_property_definitions/",
        code: 200,
      }),
    ),
).annotate({
  identifier: "CustomPropertyDefinitionsCreateRequest",
}) as any as S.Schema<CustomPropertyDefinitionsCreateRequest>;

/** For select properties: the allowed options. Required (non-empty) when display_type is 'select'; cleared server-side for other types. */
export type CustomPropertyDefinitionOptionsList =
  ReadonlyArray<CustomPropertyOption>;
export const CustomPropertyDefinitionOptionsList = /*@__PURE__*/ S.Array(
  CustomPropertyOption,
) as any as S.Schema<CustomPropertyDefinitionOptionsList>;

/** One person- or group-property sync or backfill run. Read-only: runs are created by the sync/backfill pipeline, never through the API. */
export interface CustomPropertySyncRun {
  id: string;
  /** What started the run: 'scheduled' (rode a warehouse sync), 'manual', or 'backfill'. */
  trigger: string;
  /** Run status: 'running', 'completed', or 'failed'. */
  status: string;
  /** When the run began. */
  started_at: string | null;
  /** When the run ended, or null while running. */
  finished_at: string | null;
  /** Warehouse rows scanned this run. */
  rows_read: number;
  /** Rows whose mapped values changed since the last run. */
  changed: number;
  /** Person or group profiles updated (changed rows that matched an existing person/group). */
  existing: number;
  /** Property-update intents produced to the ingestion pipeline. */
  produced: number;
  /** Changed rows dropped because no existing person/group matched the key column value. */
  skipped_missing_person: number;
  /** Error summary if the run failed, else null. */
  error: string | null;
  /** When the run row was recorded. */
  created_at: string;
}
export const CustomPropertySyncRun = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String,
    trigger: S.String,
    status: S.String,
    started_at: S.NullOr(S.String),
    finished_at: S.NullOr(S.String),
    rows_read: S.Number,
    changed: S.Number,
    existing: S.Number,
    produced: S.Number,
    skipped_missing_person: S.Number,
    error: S.NullOr(S.String),
    created_at: S.String,
  }),
).annotate({
  identifier: "CustomPropertySyncRun",
}) as any as S.Schema<CustomPropertySyncRun>;

/** Binds a data-warehouse source to a custom property definition. Account sources read a materialized view column and sync onto matching accounts; person and group sources read a warehouse schema and sync onto matching persons or groups on each warehouse sync. */
export interface CustomPropertySource {
  id: string;
  /** UUID of the custom property definition this source feeds. One source per definition. */
  definition: string;
  /** Account sources only: UUID of the data-warehouse saved query (materialized view) to read values from. Mutually exclusive with external_data_schema. */
  saved_query?: string | null;
  /** Person and group sources only: UUID of the warehouse schema (raw incremental table) to read from. Mutually exclusive with saved_query. */
  external_data_schema?: string | null;
  /** Account sources only: column in the view whose value is written to the property. */
  source_column?: string | null;
  /** Person and group sources only: {warehouse_column: property_name} mapping the columns this source writes onto the person or group. */
  column_property_map?: unknown;
  /** Column whose value identifies the target: an account's external_id for account sources, the person's distinct_id for person sources, or the group key for group sources. */
  key_column: string;
  /** Whether the source syncs. Auto-disabled after repeated failures or a missing view; re-enabling resets the failure count. */
  is_enabled?: boolean;
  /** Consecutive failed sync runs; the source auto-disables at the cap. */
  consecutive_failures: number;
  /** When the most recent sync run finished. */
  last_synced_at: string | null;
  /** Error summary from the last run, or null if it succeeded. */
  last_sync_error: string | null;
  created_at: string;
  created_by: number | null;
  updated_at: string | null;
  /** Person and group sources only: how often the underlying warehouse schema syncs, in seconds. Null for account sources or when unavailable. */
  sync_frequency_interval_seconds: number | null;
  /** Person and group sources only: approximate time of the next scheduled sync (last synced + interval). Approximate — drifts if the schedule was paused. Null for account sources or if never synced. */
  next_sync_at: string | null;
  /** Person and group sources only: the most recent sync/backfill run, or null if none yet. */
  latest_run: CustomPropertySyncRun | null;
}
export const CustomPropertySource = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String,
    definition: S.String,
    saved_query: S.optional(S.NullOr(S.String)),
    external_data_schema: S.optional(S.NullOr(S.String)),
    source_column: S.optional(S.NullOr(S.String)),
    column_property_map: S.optional(S.Unknown),
    key_column: S.String,
    is_enabled: S.optional(S.Boolean),
    consecutive_failures: S.Number,
    last_synced_at: S.NullOr(S.String),
    last_sync_error: S.NullOr(S.String),
    created_at: S.String,
    created_by: S.NullOr(S.Number),
    updated_at: S.NullOr(S.String),
    sync_frequency_interval_seconds: S.NullOr(S.Number),
    next_sync_at: S.NullOr(S.String),
    latest_run: S.NullOr(CustomPropertySyncRun),
  }),
).annotate({
  identifier: "CustomPropertySource",
}) as any as S.Schema<CustomPropertySource>;

/** A place that uses a custom property definition (read-only). */
export interface CustomPropertyReference {
  /** Id of the referring entity (e.g. the workflow id). */
  id: string;
  /** Display name of the referring entity. */
  name: string;
  /** Status of the referring entity (e.g. workflow status). */
  status: string;
  /** Kind of reference. Currently always 'workflow'. */
  type: string;
}
export const CustomPropertyReference = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String,
    name: S.String,
    status: S.String,
    type: S.String,
  }),
).annotate({
  identifier: "CustomPropertyReference",
}) as any as S.Schema<CustomPropertyReference>;

/** Workflows that use this property, resolved by definition id. */
export type CustomPropertyDefinitionReferencesList =
  ReadonlyArray<CustomPropertyReference>;
export const CustomPropertyDefinitionReferencesList = /*@__PURE__*/ S.Array(
  CustomPropertyReference,
) as any as S.Schema<CustomPropertyDefinitionReferencesList>;

/** A team-scoped definition of a custom account property — the attribute side of the model. Holds only the property's shape (name, display type, big-number flag). Per-account values are stored separately, so this serializer never reads or writes account values. */
export interface CustomPropertyDefinition {
  id: string;
  /** Human-readable name of the custom property. Unique within the team. */
  name: string;
  /** Optional description of what the property represents. */
  description?: string | null;
  /** How the property is interpreted and rendered: 'text', 'number', 'currency', 'percent', 'date', 'datetime', 'boolean', or 'select'. * `text` - text * `number` - number * `currency` - currency * `percent` - percent * `date` - date * `datetime` - datetime * `boolean` - boolean * `select` - select */
  display_type: CustomPropertyDisplayTypeEnum;
  /** What entity this property is attached to: 'account' (default), 'person', or 'group'. Person and group properties are populated from a warehouse schema and become usable like any other person/group property (feature flags, cohorts, insights). * `account` - account * `person` - person * `group` - group */
  target_type?: CustomPropertyDefinitionTargetTypeEnum;
  /** For 'group' targets only: which group type (0-4) the property attaches to. Required when target_type is 'group'; must be omitted otherwise. Create-only. */
  group_type_index?: number | null;
  /** Abbreviate large numbers (e.g. 10,000 → 10K). Only applies to numeric properties. */
  is_big_number?: boolean;
  /** For select properties: the allowed options. Required (non-empty) when display_type is 'select'; cleared server-side for other types. */
  options?: CustomPropertyDefinitionOptionsList | null;
  /** The data-warehouse view-sync binding feeding this property, or null when values are set manually. */
  source: CustomPropertySource | null;
  created_at: string;
  created_by: number | null;
  updated_at: string | null;
  /** Workflows that use this property, resolved by definition id. */
  references: CustomPropertyDefinitionReferencesList;
}
export const CustomPropertyDefinition = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String,
    name: S.String,
    description: S.optional(S.NullOr(S.String)),
    display_type: CustomPropertyDisplayTypeEnum,
    target_type: S.optional(CustomPropertyDefinitionTargetTypeEnum),
    group_type_index: S.optional(S.NullOr(S.Number)),
    is_big_number: S.optional(S.Boolean),
    options: S.optional(S.NullOr(CustomPropertyDefinitionOptionsList)),
    source: S.NullOr(CustomPropertySource),
    created_at: S.String,
    created_by: S.NullOr(S.Number),
    updated_at: S.NullOr(S.String),
    references: CustomPropertyDefinitionReferencesList,
  }),
).annotate({
  identifier: "CustomPropertyDefinition",
}) as any as S.Schema<CustomPropertyDefinition>;

export interface CustomPropertyDefinitionsDestroyRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  id: string;
}
export const CustomPropertyDefinitionsDestroyRequest = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      project_id: S.String.pipe(T.Label()),
      id: S.String.pipe(T.Label()),
    }).pipe(
      T.Http({
        method: "DELETE",
        uri: "/api/projects/{project_id}/custom_property_definitions/{id}/",
        code: 200,
      }),
    ),
).annotate({
  identifier: "CustomPropertyDefinitionsDestroyRequest",
}) as any as S.Schema<CustomPropertyDefinitionsDestroyRequest>;

export interface CustomPropertyDefinitionsDestroyResponse {}
export const CustomPropertyDefinitionsDestroyResponse = /*@__PURE__*/ S.suspend(
  () => S.Struct({}),
).annotate({
  identifier: "CustomPropertyDefinitionsDestroyResponse",
}) as any as S.Schema<CustomPropertyDefinitionsDestroyResponse>;

export interface CustomPropertyDefinitionsListRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  /** Number of results to return per page. */
  limit?: number;
  /** The initial index from which to return the results. */
  offset?: number;
}
export const CustomPropertyDefinitionsListRequest = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      project_id: S.String.pipe(T.Label()),
      limit: S.optional(S.Number.pipe(T.Query())),
      offset: S.optional(S.Number.pipe(T.Query())),
    }).pipe(
      T.Http({
        method: "GET",
        uri: "/api/projects/{project_id}/custom_property_definitions/",
        code: 200,
      }),
    ),
).annotate({
  identifier: "CustomPropertyDefinitionsListRequest",
}) as any as S.Schema<CustomPropertyDefinitionsListRequest>;

export type PaginatedCustomPropertyDefinitionListResultsList =
  ReadonlyArray<CustomPropertyDefinition>;
export const PaginatedCustomPropertyDefinitionListResultsList =
  /*@__PURE__*/ S.Array(
    CustomPropertyDefinition,
  ) as any as S.Schema<PaginatedCustomPropertyDefinitionListResultsList>;

export interface PaginatedCustomPropertyDefinitionList {
  count: number;
  next?: string | null;
  previous?: string | null;
  results: PaginatedCustomPropertyDefinitionListResultsList;
}
export const PaginatedCustomPropertyDefinitionList = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      count: S.Number,
      next: S.optional(S.NullOr(S.String)),
      previous: S.optional(S.NullOr(S.String)),
      results: PaginatedCustomPropertyDefinitionListResultsList,
    }),
).annotate({
  identifier: "PaginatedCustomPropertyDefinitionList",
}) as any as S.Schema<PaginatedCustomPropertyDefinitionList>;

/** For select properties: the allowed options. Required (non-empty) when display_type is 'select'; cleared server-side for other types. */
export type CustomPropertyDefinitionsPartialUpdateRequestOptionsList =
  ReadonlyArray<CustomPropertyOption>;
export const CustomPropertyDefinitionsPartialUpdateRequestOptionsList =
  /*@__PURE__*/ S.Array(
    CustomPropertyOption,
  ) as any as S.Schema<CustomPropertyDefinitionsPartialUpdateRequestOptionsList>;

export interface CustomPropertyDefinitionsPartialUpdateRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  id: string;
  /** Human-readable name of the custom property. Unique within the team. */
  name?: string;
  /** Optional description of what the property represents. */
  description?: string | null;
  /** How the property is interpreted and rendered: 'text', 'number', 'currency', 'percent', 'date', 'datetime', 'boolean', or 'select'. * `text` - text * `number` - number * `currency` - currency * `percent` - percent * `date` - date * `datetime` - datetime * `boolean` - boolean * `select` - select */
  display_type?: CustomPropertyDisplayTypeEnum;
  /** What entity this property is attached to: 'account' (default), 'person', or 'group'. Person and group properties are populated from a warehouse schema and become usable like any other person/group property (feature flags, cohorts, insights). * `account` - account * `person` - person * `group` - group */
  target_type?: CustomPropertyDefinitionTargetTypeEnum;
  /** For 'group' targets only: which group type (0-4) the property attaches to. Required when target_type is 'group'; must be omitted otherwise. Create-only. */
  group_type_index?: number | null;
  /** Abbreviate large numbers (e.g. 10,000 → 10K). Only applies to numeric properties. */
  is_big_number?: boolean;
  /** For select properties: the allowed options. Required (non-empty) when display_type is 'select'; cleared server-side for other types. */
  options?: CustomPropertyDefinitionsPartialUpdateRequestOptionsList | null;
}
export const CustomPropertyDefinitionsPartialUpdateRequest =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      project_id: S.String.pipe(T.Label()),
      id: S.String.pipe(T.Label()),
      name: S.optional(S.String),
      description: S.optional(S.NullOr(S.String)),
      display_type: S.optional(CustomPropertyDisplayTypeEnum),
      target_type: S.optional(CustomPropertyDefinitionTargetTypeEnum),
      group_type_index: S.optional(S.NullOr(S.Number)),
      is_big_number: S.optional(S.Boolean),
      options: S.optional(
        S.NullOr(CustomPropertyDefinitionsPartialUpdateRequestOptionsList),
      ),
    }).pipe(
      T.Http({
        method: "PATCH",
        uri: "/api/projects/{project_id}/custom_property_definitions/{id}/",
        code: 200,
      }),
    ),
  ).annotate({
    identifier: "CustomPropertyDefinitionsPartialUpdateRequest",
  }) as any as S.Schema<CustomPropertyDefinitionsPartialUpdateRequest>;

export interface CustomPropertyDefinitionsRetrieveRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  id: string;
}
export const CustomPropertyDefinitionsRetrieveRequest = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      project_id: S.String.pipe(T.Label()),
      id: S.String.pipe(T.Label()),
    }).pipe(
      T.Http({
        method: "GET",
        uri: "/api/projects/{project_id}/custom_property_definitions/{id}/",
        code: 200,
      }),
    ),
).annotate({
  identifier: "CustomPropertyDefinitionsRetrieveRequest",
}) as any as S.Schema<CustomPropertyDefinitionsRetrieveRequest>;

/** For select properties: the allowed options. Required (non-empty) when display_type is 'select'; cleared server-side for other types. */
export type CustomPropertyDefinitionsUpdateRequestOptionsList =
  ReadonlyArray<CustomPropertyOption>;
export const CustomPropertyDefinitionsUpdateRequestOptionsList =
  /*@__PURE__*/ S.Array(
    CustomPropertyOption,
  ) as any as S.Schema<CustomPropertyDefinitionsUpdateRequestOptionsList>;

export interface CustomPropertyDefinitionsUpdateRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  id: string;
  /** Human-readable name of the custom property. Unique within the team. */
  name: string;
  /** Optional description of what the property represents. */
  description?: string | null;
  /** How the property is interpreted and rendered: 'text', 'number', 'currency', 'percent', 'date', 'datetime', 'boolean', or 'select'. * `text` - text * `number` - number * `currency` - currency * `percent` - percent * `date` - date * `datetime` - datetime * `boolean` - boolean * `select` - select */
  display_type: CustomPropertyDisplayTypeEnum;
  /** What entity this property is attached to: 'account' (default), 'person', or 'group'. Person and group properties are populated from a warehouse schema and become usable like any other person/group property (feature flags, cohorts, insights). * `account` - account * `person` - person * `group` - group */
  target_type?: CustomPropertyDefinitionTargetTypeEnum;
  /** For 'group' targets only: which group type (0-4) the property attaches to. Required when target_type is 'group'; must be omitted otherwise. Create-only. */
  group_type_index?: number | null;
  /** Abbreviate large numbers (e.g. 10,000 → 10K). Only applies to numeric properties. */
  is_big_number?: boolean;
  /** For select properties: the allowed options. Required (non-empty) when display_type is 'select'; cleared server-side for other types. */
  options?: CustomPropertyDefinitionsUpdateRequestOptionsList | null;
}
export const CustomPropertyDefinitionsUpdateRequest = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      project_id: S.String.pipe(T.Label()),
      id: S.String.pipe(T.Label()),
      name: S.String,
      description: S.optional(S.NullOr(S.String)),
      display_type: CustomPropertyDisplayTypeEnum,
      target_type: S.optional(CustomPropertyDefinitionTargetTypeEnum),
      group_type_index: S.optional(S.NullOr(S.Number)),
      is_big_number: S.optional(S.Boolean),
      options: S.optional(
        S.NullOr(CustomPropertyDefinitionsUpdateRequestOptionsList),
      ),
    }).pipe(
      T.Http({
        method: "PUT",
        uri: "/api/projects/{project_id}/custom_property_definitions/{id}/",
        code: 200,
      }),
    ),
).annotate({
  identifier: "CustomPropertyDefinitionsUpdateRequest",
}) as any as S.Schema<CustomPropertyDefinitionsUpdateRequest>;

export interface CustomPropertyDefinitionsValuesRetrieveRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  /** Id of the custom property definition to suggest values for. */
  key: string;
  /** Case-insensitive substring to narrow the suggestions. */
  value?: string;
}
export const CustomPropertyDefinitionsValuesRetrieveRequest =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      project_id: S.String.pipe(T.Label()),
      key: S.String.pipe(T.Query()),
      value: S.optional(S.String.pipe(T.Query())),
    }).pipe(
      T.Http({
        method: "GET",
        uri: "/api/projects/{project_id}/custom_property_definitions/values/",
        code: 200,
      }),
    ),
  ).annotate({
    identifier: "CustomPropertyDefinitionsValuesRetrieveRequest",
  }) as any as S.Schema<CustomPropertyDefinitionsValuesRetrieveRequest>;

/** One suggested filter value for a custom property. */
export interface CustomPropertyValueSuggestion {
  /** A suggested value for the custom property. */
  name: string;
}
export const CustomPropertyValueSuggestion = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    name: S.String,
  }),
).annotate({
  identifier: "CustomPropertyValueSuggestion",
}) as any as S.Schema<CustomPropertyValueSuggestion>;

/** Suggested values matching the search input. */
export type CustomPropertyValueSuggestionsResponseResultsList =
  ReadonlyArray<CustomPropertyValueSuggestion>;
export const CustomPropertyValueSuggestionsResponseResultsList =
  /*@__PURE__*/ S.Array(
    CustomPropertyValueSuggestion,
  ) as any as S.Schema<CustomPropertyValueSuggestionsResponseResultsList>;

/** Response shape of the custom property value-suggestions endpoint. Matches the contract of the shared property-values picker (``propertyDefinitionsModel`` on the frontend), which expects ``{results: [{name}], refreshing}``. */
export interface CustomPropertyValueSuggestionsResponse {
  /** Suggested values matching the search input. */
  results: CustomPropertyValueSuggestionsResponseResultsList;
  /** Always false — present for compatibility with the property-values consumer. */
  refreshing: boolean;
}
export const CustomPropertyValueSuggestionsResponse = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      results: CustomPropertyValueSuggestionsResponseResultsList,
      refreshing: S.Boolean,
    }),
).annotate({
  identifier: "CustomPropertyValueSuggestionsResponse",
}) as any as S.Schema<CustomPropertyValueSuggestionsResponse>;

export type CustomPropertyDefinitionsCreateError = PosthogOpError;
export const customPropertyDefinitionsCreate: API.OperationMethod<
  CustomPropertyDefinitionsCreateRequest,
  CustomPropertyDefinition,
  CustomPropertyDefinitionsCreateError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CustomPropertyDefinitionsCreateRequest,
  output: CustomPropertyDefinition,
  errors: [],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type CustomPropertyDefinitionsDestroyError = PosthogOpError;
export const customPropertyDefinitionsDestroy: API.OperationMethod<
  CustomPropertyDefinitionsDestroyRequest,
  CustomPropertyDefinitionsDestroyResponse,
  CustomPropertyDefinitionsDestroyError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CustomPropertyDefinitionsDestroyRequest,
  output: CustomPropertyDefinitionsDestroyResponse,
  errors: [],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type CustomPropertyDefinitionsListError = PosthogOpError;
export const customPropertyDefinitionsList: API.OperationMethod<
  CustomPropertyDefinitionsListRequest,
  PaginatedCustomPropertyDefinitionList,
  CustomPropertyDefinitionsListError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CustomPropertyDefinitionsListRequest,
  output: PaginatedCustomPropertyDefinitionList,
  errors: [],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type CustomPropertyDefinitionsPartialUpdateError = PosthogOpError;
export const customPropertyDefinitionsPartialUpdate: API.OperationMethod<
  CustomPropertyDefinitionsPartialUpdateRequest,
  CustomPropertyDefinition,
  CustomPropertyDefinitionsPartialUpdateError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CustomPropertyDefinitionsPartialUpdateRequest,
  output: CustomPropertyDefinition,
  errors: [],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type CustomPropertyDefinitionsRetrieveError = PosthogOpError;
export const customPropertyDefinitionsRetrieve: API.OperationMethod<
  CustomPropertyDefinitionsRetrieveRequest,
  CustomPropertyDefinition,
  CustomPropertyDefinitionsRetrieveError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CustomPropertyDefinitionsRetrieveRequest,
  output: CustomPropertyDefinition,
  errors: [],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type CustomPropertyDefinitionsUpdateError = PosthogOpError;
export const customPropertyDefinitionsUpdate: API.OperationMethod<
  CustomPropertyDefinitionsUpdateRequest,
  CustomPropertyDefinition,
  CustomPropertyDefinitionsUpdateError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CustomPropertyDefinitionsUpdateRequest,
  output: CustomPropertyDefinition,
  errors: [],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type CustomPropertyDefinitionsValuesRetrieveError = PosthogOpError;
export const customPropertyDefinitionsValuesRetrieve: API.OperationMethod<
  CustomPropertyDefinitionsValuesRetrieveRequest,
  CustomPropertyValueSuggestionsResponse,
  CustomPropertyDefinitionsValuesRetrieveError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CustomPropertyDefinitionsValuesRetrieveRequest,
  output: CustomPropertyValueSuggestionsResponse,
  errors: [],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));
