// AUTO-GENERATED by scripts/generate.ts from .generated-specs (see scripts/convert.ts). Do not edit.
import * as S from "@distilled.cloud/core/schema";
import * as API from "@distilled.cloud/core/api";
import * as T from "../traits.ts";
import {
  PosthogProtocol,
  type PosthogOpError,
  type PosthogOpContext,
} from "../protocol.ts";
import * as Retry from "../retry.ts";

export type { PosthogOpError, PosthogOpContext };

export interface QuotaLimitsListRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
}
export const QuotaLimitsListRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
  }).pipe(
    T.Http({
      method: "GET",
      uri: "/api/projects/{project_id}/quota_limits/",
      code: 200,
    }),
  ),
).annotate({
  identifier: "QuotaLimitsListRequest",
}) as any as S.Schema<QuotaLimitsListRequest>;

export interface QuotaResourceLimit {
  /** True when the team is currently over its quota for this resource and limits are in effect. A deactivated organization additionally reads as limited on the two credit buckets `ai_credits` and `posthog_code_credits`, regardless of usage. */
  limited: boolean;
  /** Units of this resource the organization has used so far this billing period, in the resource's native unit (credits for credit buckets). Null when billing hasn't synced usage for the resource. */
  usage: number | null;
  /** The organization's limit for this resource in the same unit. Null when unlimited or unknown. */
  limit: number | null;
}
export const QuotaResourceLimit = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    limited: S.Boolean,
    usage: S.NullOr(S.Number),
    limit: S.NullOr(S.Number),
  }),
).annotate({
  identifier: "QuotaResourceLimit",
}) as any as S.Schema<QuotaResourceLimit>;

/** Per-resource limit state for every `QuotaResource` value, e.g. `ai_credits`, `posthog_code_credits`. Also carries the informational Desktop component resources (`posthog_code_token_credits`, `sandbox_compute_credits`, `sandbox_compute_cpu_millicore_seconds`, `sandbox_compute_memory_mib_seconds`) with usage in their native units, a null limit, and `limited` always false — they are never quota-enforced; only the combined `posthog_code_credits` is. */
export type QuotaLimitsResponseLimitedMap = {
  [key: string]: QuotaResourceLimit | undefined;
};
export const QuotaLimitsResponseLimitedMap = /*@__PURE__*/ S.Record(
  S.String,
  QuotaResourceLimit,
) as any as S.Schema<QuotaLimitsResponseLimitedMap>;

export interface QuotaLimitsResponse {
  /** Per-resource limit state for every `QuotaResource` value, e.g. `ai_credits`, `posthog_code_credits`. Also carries the informational Desktop component resources (`posthog_code_token_credits`, `sandbox_compute_credits`, `sandbox_compute_cpu_millicore_seconds`, `sandbox_compute_memory_mib_seconds`) with usage in their native units, a null limit, and `limited` always false — they are never quota-enforced; only the combined `posthog_code_credits` is. */
  limited: QuotaLimitsResponseLimitedMap;
  /** Whether the team's organization pays for PostHog Desktop usage: billing grants the `posthog_code_usage` product feature only on the Desktop usage product's paid plan, synced into the organization's available features. Consumers gate paid-tier Desktop behavior on this; an org unknown to billing reads as not paying. Always false for deactivated organizations. */
  code_usage_billing_active: boolean;
}
export const QuotaLimitsResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    limited: QuotaLimitsResponseLimitedMap,
    code_usage_billing_active: S.Boolean,
  }),
).annotate({
  identifier: "QuotaLimitsResponse",
}) as any as S.Schema<QuotaLimitsResponse>;

export type QuotaLimitsListResponseBodyList = Array<QuotaLimitsResponse>;
export const QuotaLimitsListResponseBodyList = /*@__PURE__*/ S.Array(
  QuotaLimitsResponse,
) as any as S.Schema<QuotaLimitsListResponseBodyList>;

export type QuotaLimitsListResponse = QuotaLimitsListResponseBodyList;
export const QuotaLimitsListResponse = /*@__PURE__*/ S.suspend(() =>
  QuotaLimitsListResponseBodyList.pipe(T.RawResponseRoot()),
).annotate({
  identifier: "QuotaLimitsListResponse",
}) as any as S.Schema<QuotaLimitsListResponse>;

export type QuotaLimitsListError = PosthogOpError;
/** Get a team's quota-limit state Return the current quota-limit state for the team identified in the URL, keyed by `QuotaResource` value. Used by the LLM gateway to gate billable products on AI credits exhaustion. */
export const quotaLimitsList: API.OperationMethod<
  QuotaLimitsListRequest,
  QuotaLimitsListResponse,
  QuotaLimitsListError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: QuotaLimitsListRequest,
  output: QuotaLimitsListResponse,
  errors: [],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));
