// AUTO-GENERATED by scripts/generate.ts from .generated-specs (see scripts/convert.ts). Do not edit.
import * as S from "@distilled.cloud/core/schema";
import * as API from "@distilled.cloud/core/api";
import * as T from "../traits.ts";
import {
  PosthogProtocol,
  type PosthogOpError,
  type PosthogOpContext,
} from "../protocol.ts";
import * as Retry from "../retry.ts";

export type { PosthogOpError, PosthogOpContext };

export class BadRequest extends T.applyErrorMatchers(
  S.TaggedErrorClass<BadRequest>()("BadRequest", {
    code: S.Number,
    message: S.String,
  }),
  [{ status: 400 }],
) {}

export class Forbidden extends T.applyErrorMatchers(
  S.TaggedErrorClass<Forbidden>()("Forbidden", {
    code: S.Number,
    message: S.String,
  }),
  [{ status: 403 }],
) {}

export class NotFound extends T.applyErrorMatchers(
  S.TaggedErrorClass<NotFound>()("NotFound", {
    code: S.Number,
    message: S.String,
  }),
  [{ status: 404 }],
) {}

/** List of insight IDs from the dashboard to include. Required for dashboard subscriptions, max 6. */
export type SubscriptionsCreateRequestDashboardExportInsightsList =
  Array<number>;
export const SubscriptionsCreateRequestDashboardExportInsightsList =
  /*@__PURE__*/ S.Array(
    S.Number,
  ) as any as S.Schema<SubscriptionsCreateRequestDashboardExportInsightsList>;

/** * `since_last_sent` - Since last report * `last_n_days` - Last N days * `days_ago_range` - Between X and Y days ago */
export type AIWindowConfigModeEnum =
  | "since_last_sent"
  | "last_n_days"
  | "days_ago_range";
export const AIWindowConfigModeEnum = /*@__PURE__*/ S.String;

export interface AIWindowConfig {
  /** What the report analyzes each run: * `since_last_sent` (default) — everything since the previous successful scheduled delivery (gap-free; test/manual sends don't move the anchor) * `last_n_days` — a fixed trailing window of start_days_ago days * `days_ago_range` — the explicit range from start_days_ago to end_days_ago days ago * `since_last_sent` - Since last report * `last_n_days` - Last N days * `days_ago_range` - Between X and Y days ago */
  mode?: AIWindowConfigModeEnum | (string & {});
  /** Lower bound of the analysis window, in days before the run. Required for 'last_n_days' (the N) and 'days_ago_range'; ignored for 'since_last_sent'. 1-365. */
  start_days_ago?: number | null;
  /** Upper bound of the analysis window, in days before the run (0 = now). Required for 'days_ago_range' and must be less than start_days_ago; ignored for other modes. 0-365. */
  end_days_ago?: number | null;
}
export const AIWindowConfig = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    mode: S.optional(AIWindowConfigModeEnum),
    start_days_ago: S.optional(S.NullOr(S.Number)),
    end_days_ago: S.optional(S.NullOr(S.Number)),
  }),
).annotate({ identifier: "AIWindowConfig" }) as any as S.Schema<AIWindowConfig>;

export interface AIPromptConfig {
  /** Analysis window for the report. Omitted = 'since_last_sent' (everything since the previous scheduled delivery). */
  window?: AIWindowConfig;
}
export const AIPromptConfig = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    window: S.optional(AIWindowConfig),
  }),
).annotate({ identifier: "AIPromptConfig" }) as any as S.Schema<AIPromptConfig>;

/** * `email` - Email * `slack` - Slack */
export type TargetTypeEnum = "email" | "slack";
export const TargetTypeEnum = /*@__PURE__*/ S.String;

/** * `daily` - Daily * `weekly` - Weekly * `monthly` - Monthly * `yearly` - Yearly */
export type RecurrenceIntervalEnum = "daily" | "weekly" | "monthly" | "yearly";
export const RecurrenceIntervalEnum = /*@__PURE__*/ S.String;

/** * `monday` - Monday * `tuesday` - Tuesday * `wednesday` - Wednesday * `thursday` - Thursday * `friday` - Friday * `saturday` - Saturday * `sunday` - Sunday */
export type SubscriptionsCreateRequestByweekdayItem =
  | "monday"
  | "tuesday"
  | "wednesday"
  | "thursday"
  | "friday"
  | "saturday"
  | "sunday";
export const SubscriptionsCreateRequestByweekdayItem = /*@__PURE__*/ S.String;

/** Days of week for weekly subscriptions: monday, tuesday, wednesday, thursday, friday, saturday, sunday. */
export type SubscriptionsCreateRequestByweekdayList = Array<
  SubscriptionsCreateRequestByweekdayItem | (string & {})
>;
export const SubscriptionsCreateRequestByweekdayList = /*@__PURE__*/ S.Array(
  SubscriptionsCreateRequestByweekdayItem,
) as any as S.Schema<SubscriptionsCreateRequestByweekdayList>;

export interface SubscriptionsCreateRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  /** Dashboard ID to subscribe to (mutually exclusive with insight on create). */
  dashboard?: number | null;
  /** Insight ID to subscribe to (mutually exclusive with dashboard on create). */
  insight?: number | null;
  /** List of insight IDs from the dashboard to include. Required for dashboard subscriptions, max 6. */
  dashboard_export_insights?: SubscriptionsCreateRequestDashboardExportInsightsList;
  /** Free-text prompt that drives the AI-generated report. Required when resource_type is 'ai_prompt'. Max 4000 characters. */
  prompt?: string | null;
  /** Configuration for AI report subscriptions (analysis window, future knobs). Only valid when resource_type is 'ai_prompt'. Replaced wholesale on writes. */
  ai_prompt_config?: AIPromptConfig;
  /** Delivery channel: email or slack. * `email` - Email * `slack` - Slack */
  target_type?: TargetTypeEnum | (string & {});
  /** Recipient(s): comma-separated email addresses for email, or Slack channel name/ID for slack. */
  target_value?: string;
  /** How often to deliver: daily, weekly, monthly, or yearly. * `daily` - Daily * `weekly` - Weekly * `monthly` - Monthly * `yearly` - Yearly */
  frequency?: RecurrenceIntervalEnum | (string & {});
  /** Interval multiplier (e.g. 2 with weekly frequency means every 2 weeks). Required on create; must be 1 or greater. */
  interval?: number;
  /** Days of week for weekly subscriptions: monday, tuesday, wednesday, thursday, friday, saturday, sunday. */
  byweekday?: SubscriptionsCreateRequestByweekdayList | null;
  /** Position within byweekday set for monthly frequency (e.g. 1 for first, -1 for last). */
  bysetpos?: number | null;
  /** Total number of deliveries before the subscription stops. Null for unlimited. */
  count?: number | null;
  /** When to start delivering (ISO 8601 datetime). */
  start_date?: string;
  /** When to stop delivering (ISO 8601 datetime). Null for indefinite. */
  until_date?: string | null;
  /** Set to true to soft-delete. Subscriptions cannot be hard-deleted. */
  deleted?: boolean;
  /** Whether the subscription is active. Set to false to pause delivery without deleting. Auto-set to false when the delivery integration becomes invalid. */
  enabled?: boolean;
  /** Human-readable name for this subscription. */
  title?: string | null;
  /** ID of a connected Slack integration. Required when target_type is slack. */
  integration_id?: number | null;
  /** Optional message included in the invitation email when adding new recipients. */
  invite_message?: string | null;
  /** Whether to immediately deliver the subscription once on save so the editor can confirm it looks right. Defaults to true on create. When omitted on update, a delivery is sent only if the edit changed what gets delivered (recipient, channel, source) or re-enabled the subscription. The recurring schedule is unaffected. */
  send_test_now?: boolean;
  /** Whether to attach an AI-generated summary to each delivery (insight and dashboard subscriptions only). Requires the organization to have approved AI data processing, and is subject to the org's active-summary cap and AI credit budget; otherwise the write is rejected. Not applicable to prompt subscriptions, which are themselves AI-generated. */
  summary_enabled?: boolean;
  /** Optional free-text guidance (max 500 chars) steering the AI summary, e.g. which metrics to emphasize. Only settable when AI summary context is enabled for the organization; clearing it (empty string) is always allowed. */
  summary_prompt_guide?: string;
}
export const SubscriptionsCreateRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
    dashboard: S.optional(S.NullOr(S.Number)),
    insight: S.optional(S.NullOr(S.Number)),
    dashboard_export_insights: S.optional(
      SubscriptionsCreateRequestDashboardExportInsightsList,
    ),
    prompt: S.optional(S.NullOr(S.String)),
    ai_prompt_config: S.optional(AIPromptConfig),
    target_type: S.optional(TargetTypeEnum),
    target_value: S.optional(S.String),
    frequency: S.optional(RecurrenceIntervalEnum),
    interval: S.optional(S.Number),
    byweekday: S.optional(S.NullOr(SubscriptionsCreateRequestByweekdayList)),
    bysetpos: S.optional(S.NullOr(S.Number)),
    count: S.optional(S.NullOr(S.Number)),
    start_date: S.optional(S.String),
    until_date: S.optional(S.NullOr(S.String)),
    deleted: S.optional(S.Boolean),
    enabled: S.optional(S.Boolean),
    title: S.optional(S.NullOr(S.String)),
    integration_id: S.optional(S.NullOr(S.Number)),
    invite_message: S.optional(S.NullOr(S.String)),
    send_test_now: S.optional(S.Boolean),
    summary_enabled: S.optional(S.Boolean),
    summary_prompt_guide: S.optional(S.String),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/api/projects/{project_id}/subscriptions/",
      code: 200,
    }),
  ),
).annotate({
  identifier: "SubscriptionsCreateRequest",
}) as any as S.Schema<SubscriptionsCreateRequest>;

/** * `insight` - Insight * `dashboard` - Dashboard * `ai_prompt` - AI prompt */
export type ResourceTypeEnum = "insight" | "dashboard" | "ai_prompt";
export const ResourceTypeEnum = /*@__PURE__*/ S.String;

/** List of insight IDs from the dashboard to include. Required for dashboard subscriptions, max 6. */
export type SubscriptionOutputDashboardExportInsightsList = Array<number>;
export const SubscriptionOutputDashboardExportInsightsList =
  /*@__PURE__*/ S.Array(
    S.Number,
  ) as any as S.Schema<SubscriptionOutputDashboardExportInsightsList>;

/** * `monday` - Monday * `tuesday` - Tuesday * `wednesday` - Wednesday * `thursday` - Thursday * `friday` - Friday * `saturday` - Saturday * `sunday` - Sunday */
export type SubscriptionOutputByweekdayItem =
  | "monday"
  | "tuesday"
  | "wednesday"
  | "thursday"
  | "friday"
  | "saturday"
  | "sunday";
export const SubscriptionOutputByweekdayItem = /*@__PURE__*/ S.String;

/** Days of week for weekly subscriptions: monday, tuesday, wednesday, thursday, friday, saturday, sunday. */
export type SubscriptionOutputByweekdayList =
  Array<SubscriptionOutputByweekdayItem>;
export const SubscriptionOutputByweekdayList = /*@__PURE__*/ S.Array(
  SubscriptionOutputByweekdayItem,
) as any as S.Schema<SubscriptionOutputByweekdayList>;

export type UserBasicHedgehogConfigMap = { [key: string]: unknown | undefined };
export const UserBasicHedgehogConfigMap = /*@__PURE__*/ S.Record(
  S.String,
  S.Unknown,
) as any as S.Schema<UserBasicHedgehogConfigMap>;

/** * `engineering` - Engineering * `data` - Data * `product` - Product Management * `founder` - Founder * `leadership` - Leadership * `marketing` - Marketing * `sales` - Sales / Success * `other` - Other */
export type RoleAtOrganizationEnum =
  | "engineering"
  | "data"
  | "product"
  | "founder"
  | "leadership"
  | "marketing"
  | "sales"
  | "other";
export const RoleAtOrganizationEnum = /*@__PURE__*/ S.String;

export type BlankEnum = "";
export const BlankEnum = /*@__PURE__*/ S.String;

export type UserBasicRoleAtOrganization = RoleAtOrganizationEnum | BlankEnum;
export const UserBasicRoleAtOrganization =
  /*@__PURE__*/ S.Unknown as any as S.Schema<UserBasicRoleAtOrganization>;

export interface UserBasic {
  id?: number;
  uuid?: string;
  distinct_id?: string | null;
  first_name?: string;
  last_name?: string;
  email?: string;
  is_email_verified?: boolean | null;
  hedgehog_config?: UserBasicHedgehogConfigMap | null;
  role_at_organization?: UserBasicRoleAtOrganization | null;
}
export const UserBasic = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.Number),
    uuid: S.optional(S.String),
    distinct_id: S.optional(S.NullOr(S.String)),
    first_name: S.optional(S.String),
    last_name: S.optional(S.String),
    email: S.optional(S.String),
    is_email_verified: S.optional(S.NullOr(S.Boolean)),
    hedgehog_config: S.optional(S.NullOr(UserBasicHedgehogConfigMap)),
    role_at_organization: S.optional(S.NullOr(UserBasicRoleAtOrganization)),
  }),
).annotate({ identifier: "UserBasic" }) as any as S.Schema<UserBasic>;

/** Standard Subscription serializer. */
export interface SubscriptionOutput {
  id?: number;
  /** What the subscription delivers: 'insight' (snapshot of one insight), 'dashboard' (snapshot of one dashboard), or 'ai_prompt' (LLM-generated report). Read-only — derived from the populated target (insight → insight, dashboard → dashboard, prompt → ai_prompt). * `insight` - Insight * `dashboard` - Dashboard * `ai_prompt` - AI prompt */
  resource_type?: ResourceTypeEnum;
  /** Dashboard ID to subscribe to (mutually exclusive with insight on create). */
  dashboard?: number | null;
  /** Insight ID to subscribe to (mutually exclusive with dashboard on create). */
  insight?: number | null;
  insight_short_id?: string | null;
  resource_name?: string | null;
  /** List of insight IDs from the dashboard to include. Required for dashboard subscriptions, max 6. */
  dashboard_export_insights?: SubscriptionOutputDashboardExportInsightsList;
  /** Free-text prompt that drives the AI-generated report. Required when resource_type is 'ai_prompt'. Max 4000 characters. */
  prompt?: string | null;
  /** Configuration for AI report subscriptions (analysis window, future knobs). Only valid when resource_type is 'ai_prompt'. Replaced wholesale on writes. */
  ai_prompt_config?: AIPromptConfig;
  /** Delivery channel: email or slack. * `email` - Email * `slack` - Slack */
  target_type?: TargetTypeEnum;
  /** Recipient(s): comma-separated email addresses for email, or Slack channel name/ID for slack. */
  target_value?: string;
  /** How often to deliver: daily, weekly, monthly, or yearly. * `daily` - Daily * `weekly` - Weekly * `monthly` - Monthly * `yearly` - Yearly */
  frequency?: RecurrenceIntervalEnum;
  /** Interval multiplier (e.g. 2 with weekly frequency means every 2 weeks). Required on create; must be 1 or greater. */
  interval?: number;
  /** Days of week for weekly subscriptions: monday, tuesday, wednesday, thursday, friday, saturday, sunday. */
  byweekday?: SubscriptionOutputByweekdayList | null;
  /** Position within byweekday set for monthly frequency (e.g. 1 for first, -1 for last). */
  bysetpos?: number | null;
  /** Total number of deliveries before the subscription stops. Null for unlimited. */
  count?: number | null;
  /** When to start delivering (ISO 8601 datetime). */
  start_date?: string;
  /** When to stop delivering (ISO 8601 datetime). Null for indefinite. */
  until_date?: string | null;
  created_at?: string;
  created_by?: UserBasic | null;
  /** Set to true to soft-delete. Subscriptions cannot be hard-deleted. */
  deleted?: boolean;
  /** Whether the subscription is active. Set to false to pause delivery without deleting. Auto-set to false when the delivery integration becomes invalid. */
  enabled?: boolean;
  /** Human-readable name for this subscription. */
  title?: string | null;
  /** Human-readable schedule summary, e.g. 'sent daily'. */
  summary?: string;
  next_delivery_date?: string | null;
  /** ID of a connected Slack integration. Required when target_type is slack. */
  integration_id?: number | null;
  /** Optional message included in the invitation email when adding new recipients. */
  invite_message?: string | null;
  /** Whether to attach an AI-generated summary to each delivery (insight and dashboard subscriptions only). Requires the organization to have approved AI data processing, and is subject to the org's active-summary cap and AI credit budget; otherwise the write is rejected. Not applicable to prompt subscriptions, which are themselves AI-generated. */
  summary_enabled?: boolean;
  /** Optional free-text guidance (max 500 chars) steering the AI summary, e.g. which metrics to emphasize. Only settable when AI summary context is enabled for the organization; clearing it (empty string) is always allowed. */
  summary_prompt_guide?: string;
}
export const SubscriptionOutput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.Number),
    resource_type: S.optional(ResourceTypeEnum),
    dashboard: S.optional(S.NullOr(S.Number)),
    insight: S.optional(S.NullOr(S.Number)),
    insight_short_id: S.optional(S.NullOr(S.String)),
    resource_name: S.optional(S.NullOr(S.String)),
    dashboard_export_insights: S.optional(
      SubscriptionOutputDashboardExportInsightsList,
    ),
    prompt: S.optional(S.NullOr(S.String)),
    ai_prompt_config: S.optional(AIPromptConfig),
    target_type: S.optional(TargetTypeEnum),
    target_value: S.optional(S.String),
    frequency: S.optional(RecurrenceIntervalEnum),
    interval: S.optional(S.Number),
    byweekday: S.optional(S.NullOr(SubscriptionOutputByweekdayList)),
    bysetpos: S.optional(S.NullOr(S.Number)),
    count: S.optional(S.NullOr(S.Number)),
    start_date: S.optional(S.String),
    until_date: S.optional(S.NullOr(S.String)),
    created_at: S.optional(S.String),
    created_by: S.optional(S.NullOr(UserBasic)),
    deleted: S.optional(S.Boolean),
    enabled: S.optional(S.Boolean),
    title: S.optional(S.NullOr(S.String)),
    summary: S.optional(S.String),
    next_delivery_date: S.optional(S.NullOr(S.String)),
    integration_id: S.optional(S.NullOr(S.Number)),
    invite_message: S.optional(S.NullOr(S.String)),
    summary_enabled: S.optional(S.Boolean),
    summary_prompt_guide: S.optional(S.String),
  }),
).annotate({
  identifier: "SubscriptionOutput",
}) as any as S.Schema<SubscriptionOutput>;

export type SubscriptionsDeliveriesListRequestStatus =
  | "completed"
  | "failed"
  | "skipped"
  | "starting";
export const SubscriptionsDeliveriesListRequestStatus = /*@__PURE__*/ S.String;

export interface SubscriptionsDeliveriesListRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  subscription_id: number;
  /** The pagination cursor value. */
  cursor?: string;
  /** Return only deliveries in this run status (starting, completed, failed, or skipped). */
  status?: SubscriptionsDeliveriesListRequestStatus | (string & {});
}
export const SubscriptionsDeliveriesListRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
    subscription_id: S.Number.pipe(T.Label()),
    cursor: S.optional(S.String.pipe(T.Query())),
    status: S.optional(
      SubscriptionsDeliveriesListRequestStatus.pipe(T.Query()),
    ),
  }).pipe(
    T.Http({
      method: "GET",
      uri: "/api/projects/{project_id}/subscriptions/{subscription_id}/deliveries/",
      code: 200,
    }),
  ),
).annotate({
  identifier: "SubscriptionsDeliveriesListRequest",
}) as any as S.Schema<SubscriptionsDeliveriesListRequest>;

/** ExportedAsset ids generated for this send. */
export type SubscriptionDeliveryExportedAssetIdsList = Array<number>;
export const SubscriptionDeliveryExportedAssetIdsList = /*@__PURE__*/ S.Array(
  S.Number,
) as any as S.Schema<SubscriptionDeliveryExportedAssetIdsList>;

/** * `starting` - Starting * `completed` - Completed * `failed` - Failed * `skipped` - Skipped */
export type SubscriptionDeliveryStatusEnum =
  | "starting"
  | "completed"
  | "failed"
  | "skipped";
export const SubscriptionDeliveryStatusEnum = /*@__PURE__*/ S.String;

export interface AIReportQueryDiagnostic {
  /** What this query step was meant to compute. */
  description: string;
  /** The HogQL the assistant generated for this step. */
  hogql: string;
  /** Whether the query ran successfully. */
  ok: boolean;
  /** Exception class name when the query failed; null on success. */
  error_type: string | null;
  /** Human-readable failure reason, present only for query errors safe to surface to the subscription owner (e.g. an unresolved field name); null on success and for internal errors, which expose error_type only. */
  human_readable_error?: string | null;
}
export const AIReportQueryDiagnostic = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    description: S.String,
    hogql: S.String,
    ok: S.Boolean,
    error_type: S.NullOr(S.String),
    human_readable_error: S.optional(S.NullOr(S.String)),
  }),
).annotate({
  identifier: "AIReportQueryDiagnostic",
}) as any as S.Schema<AIReportQueryDiagnostic>;

/** Per-step query diagnostics (generated HogQL + failure type) for this report. Null for non-AI deliveries or runs without persisted diagnostics. */
export type SubscriptionDeliveryAiReportDiagnosticsList =
  Array<AIReportQueryDiagnostic>;
export const SubscriptionDeliveryAiReportDiagnosticsList =
  /*@__PURE__*/ S.Array(
    AIReportQueryDiagnostic,
  ) as any as S.Schema<SubscriptionDeliveryAiReportDiagnosticsList>;

export interface SubscriptionDelivery {
  /** Primary key for this delivery row. */
  id?: string;
  /** Parent subscription id. */
  subscription?: number;
  /** Temporal workflow id for this delivery run. */
  temporal_workflow_id?: string;
  /** Dedupes activity retries for the same logical run. */
  idempotency_key?: string;
  /** Why the run started (e.g. scheduled, manual, target_change). */
  trigger_type?: string;
  /** Planned send time when applicable. */
  scheduled_at?: string | null;
  /** Channel snapshot at send time (email or slack). */
  target_type?: string;
  /** Destination snapshot at send time (emails, channel id, URL). */
  target_value?: string;
  /** ExportedAsset ids generated for this send. */
  exported_asset_ids?: SubscriptionDeliveryExportedAssetIdsList;
  /** Snapshot at send time: dashboard metadata, total_insight_count, and per-exported-insight entries (id, short_id, name, query_hash, cache_key, query_results, optional query_error). */
  content_snapshot?: unknown;
  /** Per-destination outcomes; items use status success, failed, or partial. */
  recipient_results?: unknown;
  /** Overall run status: starting, completed, failed, or skipped. * `starting` - Starting * `completed` - Completed * `failed` - Failed * `skipped` - Skipped */
  status?: SubscriptionDeliveryStatusEnum;
  /** Top-level failure payload when status is failed, if any. */
  error?: unknown;
  /** When the delivery row was created. */
  created_at?: string;
  /** Last ORM update to this row. */
  last_updated_at?: string;
  /** When the run finished, if applicable. */
  finished_at?: string | null;
  /** AI-generated summary included in this delivery, when one was produced. */
  change_summary?: string | null;
  /** AI-generated report markdown delivered by this run. Null for non-AI deliveries or runs without a persisted report. */
  ai_report?: string | null;
  /** Per-step query diagnostics (generated HogQL + failure type) for this report. Null for non-AI deliveries or runs without persisted diagnostics. */
  ai_report_diagnostics?: SubscriptionDeliveryAiReportDiagnosticsList | null;
  /** The subscription's prompt as it was when this report was generated. Null for older deliveries and non-AI deliveries. */
  ai_report_prompt?: string | null;
}
export const SubscriptionDelivery = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.String),
    subscription: S.optional(S.Number),
    temporal_workflow_id: S.optional(S.String),
    idempotency_key: S.optional(S.String),
    trigger_type: S.optional(S.String),
    scheduled_at: S.optional(S.NullOr(S.String)),
    target_type: S.optional(S.String),
    target_value: S.optional(S.String),
    exported_asset_ids: S.optional(SubscriptionDeliveryExportedAssetIdsList),
    content_snapshot: S.optional(S.Unknown),
    recipient_results: S.optional(S.Unknown),
    status: S.optional(SubscriptionDeliveryStatusEnum),
    error: S.optional(S.Unknown),
    created_at: S.optional(S.String),
    last_updated_at: S.optional(S.String),
    finished_at: S.optional(S.NullOr(S.String)),
    change_summary: S.optional(S.NullOr(S.String)),
    ai_report: S.optional(S.NullOr(S.String)),
    ai_report_diagnostics: S.optional(
      S.NullOr(SubscriptionDeliveryAiReportDiagnosticsList),
    ),
    ai_report_prompt: S.optional(S.NullOr(S.String)),
  }),
).annotate({
  identifier: "SubscriptionDelivery",
}) as any as S.Schema<SubscriptionDelivery>;

export type PaginatedSubscriptionDeliveryListResultsList =
  Array<SubscriptionDelivery>;
export const PaginatedSubscriptionDeliveryListResultsList =
  /*@__PURE__*/ S.Array(
    SubscriptionDelivery,
  ) as any as S.Schema<PaginatedSubscriptionDeliveryListResultsList>;

export interface PaginatedSubscriptionDeliveryList {
  next?: string | null;
  previous?: string | null;
  results?: PaginatedSubscriptionDeliveryListResultsList;
}
export const PaginatedSubscriptionDeliveryList = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    next: S.optional(S.NullOr(S.String)),
    previous: S.optional(S.NullOr(S.String)),
    results: S.optional(PaginatedSubscriptionDeliveryListResultsList),
  }),
).annotate({
  identifier: "PaginatedSubscriptionDeliveryList",
}) as any as S.Schema<PaginatedSubscriptionDeliveryList>;

export interface SubscriptionsDeliveriesRetrieveRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  subscription_id: number;
  /** A UUID string identifying this subscription delivery. */
  id: string;
}
export const SubscriptionsDeliveriesRetrieveRequest = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      project_id: S.String.pipe(T.Label()),
      subscription_id: S.Number.pipe(T.Label()),
      id: S.String.pipe(T.Label()),
    }).pipe(
      T.Http({
        method: "GET",
        uri: "/api/projects/{project_id}/subscriptions/{subscription_id}/deliveries/{id}/",
        code: 200,
      }),
    ),
).annotate({
  identifier: "SubscriptionsDeliveriesRetrieveRequest",
}) as any as S.Schema<SubscriptionsDeliveriesRetrieveRequest>;

export interface SubscriptionsDestroyRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  /** A unique integer value identifying this subscription. */
  id: number;
}
export const SubscriptionsDestroyRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
    id: S.Number.pipe(T.Label()),
  }).pipe(
    T.Http({
      method: "DELETE",
      uri: "/api/projects/{project_id}/subscriptions/{id}/",
      code: 200,
    }),
  ),
).annotate({
  identifier: "SubscriptionsDestroyRequest",
}) as any as S.Schema<SubscriptionsDestroyRequest>;

export interface SubscriptionsDestroyResponse {}
export const SubscriptionsDestroyResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}),
).annotate({
  identifier: "SubscriptionsDestroyResponse",
}) as any as S.Schema<SubscriptionsDestroyResponse>;

export type SubscriptionsListRequestResourceType =
  | "ai_prompt"
  | "dashboard"
  | "insight";
export const SubscriptionsListRequestResourceType = /*@__PURE__*/ S.String;

export type SubscriptionsListRequestTargetType = "email" | "slack";
export const SubscriptionsListRequestTargetType = /*@__PURE__*/ S.String;

export interface SubscriptionsListRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  /** Filter by creator user UUID. */
  created_by?: string;
  /** Filter by dashboard ID. */
  dashboard?: number;
  /** Filter to subscriptions on insights that are tiles of the given dashboard ID. */
  dashboard_tiles?: number;
  /** Filter by insight ID. */
  insight?: number;
  /** Filter by a comma-separated list of insight IDs. */
  insights?: string;
  /** Number of results to return per page. */
  limit?: number;
  /** The initial index from which to return the results. */
  offset?: number;
  /** Which field to use when ordering the results. */
  ordering?: string;
  /** Filter by subscription resource: insight, dashboard export, or AI report. */
  resource_type?: SubscriptionsListRequestResourceType | (string & {});
  /** A search term. */
  search?: string;
  /** Filter by delivery channel (email or Slack). */
  target_type?: SubscriptionsListRequestTargetType | (string & {});
}
export const SubscriptionsListRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
    created_by: S.optional(S.String.pipe(T.Query())),
    dashboard: S.optional(S.Number.pipe(T.Query())),
    dashboard_tiles: S.optional(S.Number.pipe(T.Query())),
    insight: S.optional(S.Number.pipe(T.Query())),
    insights: S.optional(S.String.pipe(T.Query())),
    limit: S.optional(S.Number.pipe(T.Query())),
    offset: S.optional(S.Number.pipe(T.Query())),
    ordering: S.optional(S.String.pipe(T.Query())),
    resource_type: S.optional(
      SubscriptionsListRequestResourceType.pipe(T.Query()),
    ),
    search: S.optional(S.String.pipe(T.Query())),
    target_type: S.optional(SubscriptionsListRequestTargetType.pipe(T.Query())),
  }).pipe(
    T.Http({
      method: "GET",
      uri: "/api/projects/{project_id}/subscriptions/",
      code: 200,
    }),
  ),
).annotate({
  identifier: "SubscriptionsListRequest",
}) as any as S.Schema<SubscriptionsListRequest>;

export type PaginatedSubscriptionListOutputResultsList =
  Array<SubscriptionOutput>;
export const PaginatedSubscriptionListOutputResultsList = /*@__PURE__*/ S.Array(
  SubscriptionOutput,
) as any as S.Schema<PaginatedSubscriptionListOutputResultsList>;

export interface PaginatedSubscriptionListOutput {
  count?: number;
  next?: string | null;
  previous?: string | null;
  results?: PaginatedSubscriptionListOutputResultsList;
}
export const PaginatedSubscriptionListOutput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    count: S.optional(S.Number),
    next: S.optional(S.NullOr(S.String)),
    previous: S.optional(S.NullOr(S.String)),
    results: S.optional(PaginatedSubscriptionListOutputResultsList),
  }),
).annotate({
  identifier: "PaginatedSubscriptionListOutput",
}) as any as S.Schema<PaginatedSubscriptionListOutput>;

/** List of insight IDs from the dashboard to include. Required for dashboard subscriptions, max 6. */
export type SubscriptionsPartialUpdateRequestDashboardExportInsightsList =
  Array<number>;
export const SubscriptionsPartialUpdateRequestDashboardExportInsightsList =
  /*@__PURE__*/ S.Array(
    S.Number,
  ) as any as S.Schema<SubscriptionsPartialUpdateRequestDashboardExportInsightsList>;

/** * `monday` - Monday * `tuesday` - Tuesday * `wednesday` - Wednesday * `thursday` - Thursday * `friday` - Friday * `saturday` - Saturday * `sunday` - Sunday */
export type SubscriptionsPartialUpdateRequestByweekdayItem =
  | "monday"
  | "tuesday"
  | "wednesday"
  | "thursday"
  | "friday"
  | "saturday"
  | "sunday";
export const SubscriptionsPartialUpdateRequestByweekdayItem =
  /*@__PURE__*/ S.String;

/** Days of week for weekly subscriptions: monday, tuesday, wednesday, thursday, friday, saturday, sunday. */
export type SubscriptionsPartialUpdateRequestByweekdayList = Array<
  SubscriptionsPartialUpdateRequestByweekdayItem | (string & {})
>;
export const SubscriptionsPartialUpdateRequestByweekdayList =
  /*@__PURE__*/ S.Array(
    SubscriptionsPartialUpdateRequestByweekdayItem,
  ) as any as S.Schema<SubscriptionsPartialUpdateRequestByweekdayList>;

export interface SubscriptionsPartialUpdateRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  /** A unique integer value identifying this subscription. */
  id: number;
  /** Dashboard ID to subscribe to (mutually exclusive with insight on create). */
  dashboard?: number | null;
  /** Insight ID to subscribe to (mutually exclusive with dashboard on create). */
  insight?: number | null;
  /** List of insight IDs from the dashboard to include. Required for dashboard subscriptions, max 6. */
  dashboard_export_insights?: SubscriptionsPartialUpdateRequestDashboardExportInsightsList;
  /** Free-text prompt that drives the AI-generated report. Required when resource_type is 'ai_prompt'. Max 4000 characters. */
  prompt?: string | null;
  /** Configuration for AI report subscriptions (analysis window, future knobs). Only valid when resource_type is 'ai_prompt'. Replaced wholesale on writes. */
  ai_prompt_config?: AIPromptConfig;
  /** Delivery channel: email or slack. * `email` - Email * `slack` - Slack */
  target_type?: TargetTypeEnum | (string & {});
  /** Recipient(s): comma-separated email addresses for email, or Slack channel name/ID for slack. */
  target_value?: string;
  /** How often to deliver: daily, weekly, monthly, or yearly. * `daily` - Daily * `weekly` - Weekly * `monthly` - Monthly * `yearly` - Yearly */
  frequency?: RecurrenceIntervalEnum | (string & {});
  /** Interval multiplier (e.g. 2 with weekly frequency means every 2 weeks). Required on create; must be 1 or greater. */
  interval?: number;
  /** Days of week for weekly subscriptions: monday, tuesday, wednesday, thursday, friday, saturday, sunday. */
  byweekday?: SubscriptionsPartialUpdateRequestByweekdayList | null;
  /** Position within byweekday set for monthly frequency (e.g. 1 for first, -1 for last). */
  bysetpos?: number | null;
  /** Total number of deliveries before the subscription stops. Null for unlimited. */
  count?: number | null;
  /** When to start delivering (ISO 8601 datetime). */
  start_date?: string;
  /** When to stop delivering (ISO 8601 datetime). Null for indefinite. */
  until_date?: string | null;
  /** Set to true to soft-delete. Subscriptions cannot be hard-deleted. */
  deleted?: boolean;
  /** Whether the subscription is active. Set to false to pause delivery without deleting. Auto-set to false when the delivery integration becomes invalid. */
  enabled?: boolean;
  /** Human-readable name for this subscription. */
  title?: string | null;
  /** ID of a connected Slack integration. Required when target_type is slack. */
  integration_id?: number | null;
  /** Optional message included in the invitation email when adding new recipients. */
  invite_message?: string | null;
  /** Whether to immediately deliver the subscription once on save so the editor can confirm it looks right. Defaults to true on create. When omitted on update, a delivery is sent only if the edit changed what gets delivered (recipient, channel, source) or re-enabled the subscription. The recurring schedule is unaffected. */
  send_test_now?: boolean;
  /** Whether to attach an AI-generated summary to each delivery (insight and dashboard subscriptions only). Requires the organization to have approved AI data processing, and is subject to the org's active-summary cap and AI credit budget; otherwise the write is rejected. Not applicable to prompt subscriptions, which are themselves AI-generated. */
  summary_enabled?: boolean;
  /** Optional free-text guidance (max 500 chars) steering the AI summary, e.g. which metrics to emphasize. Only settable when AI summary context is enabled for the organization; clearing it (empty string) is always allowed. */
  summary_prompt_guide?: string;
}
export const SubscriptionsPartialUpdateRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
    id: S.Number.pipe(T.Label()),
    dashboard: S.optional(S.NullOr(S.Number)),
    insight: S.optional(S.NullOr(S.Number)),
    dashboard_export_insights: S.optional(
      SubscriptionsPartialUpdateRequestDashboardExportInsightsList,
    ),
    prompt: S.optional(S.NullOr(S.String)),
    ai_prompt_config: S.optional(AIPromptConfig),
    target_type: S.optional(TargetTypeEnum),
    target_value: S.optional(S.String),
    frequency: S.optional(RecurrenceIntervalEnum),
    interval: S.optional(S.Number),
    byweekday: S.optional(
      S.NullOr(SubscriptionsPartialUpdateRequestByweekdayList),
    ),
    bysetpos: S.optional(S.NullOr(S.Number)),
    count: S.optional(S.NullOr(S.Number)),
    start_date: S.optional(S.String),
    until_date: S.optional(S.NullOr(S.String)),
    deleted: S.optional(S.Boolean),
    enabled: S.optional(S.Boolean),
    title: S.optional(S.NullOr(S.String)),
    integration_id: S.optional(S.NullOr(S.Number)),
    invite_message: S.optional(S.NullOr(S.String)),
    send_test_now: S.optional(S.Boolean),
    summary_enabled: S.optional(S.Boolean),
    summary_prompt_guide: S.optional(S.String),
  }).pipe(
    T.Http({
      method: "PATCH",
      uri: "/api/projects/{project_id}/subscriptions/{id}/",
      code: 200,
    }),
  ),
).annotate({
  identifier: "SubscriptionsPartialUpdateRequest",
}) as any as S.Schema<SubscriptionsPartialUpdateRequest>;

export interface SubscriptionsRetrieveRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  /** A unique integer value identifying this subscription. */
  id: number;
}
export const SubscriptionsRetrieveRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
    id: S.Number.pipe(T.Label()),
  }).pipe(
    T.Http({
      method: "GET",
      uri: "/api/projects/{project_id}/subscriptions/{id}/",
      code: 200,
    }),
  ),
).annotate({
  identifier: "SubscriptionsRetrieveRequest",
}) as any as S.Schema<SubscriptionsRetrieveRequest>;

export interface SubscriptionsSummaryQuotaRetrieveRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
}
export const SubscriptionsSummaryQuotaRetrieveRequest = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      project_id: S.String.pipe(T.Label()),
    }).pipe(
      T.Http({
        method: "GET",
        uri: "/api/projects/{project_id}/subscriptions/summary_quota/",
        code: 200,
      }),
    ),
).annotate({
  identifier: "SubscriptionsSummaryQuotaRetrieveRequest",
}) as any as S.Schema<SubscriptionsSummaryQuotaRetrieveRequest>;

export interface SubscriptionsSummaryQuotaRetrieveResponse {
  active_count: number;
  limit: number | null;
  at_limit: boolean;
}
export const SubscriptionsSummaryQuotaRetrieveResponse =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      active_count: S.Number,
      limit: S.NullOr(S.Number),
      at_limit: S.Boolean,
    }),
  ).annotate({
    identifier: "SubscriptionsSummaryQuotaRetrieveResponse",
  }) as any as S.Schema<SubscriptionsSummaryQuotaRetrieveResponse>;

export interface SubscriptionsTestDeliveryCreateRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  /** A unique integer value identifying this subscription. */
  id: number;
}
export const SubscriptionsTestDeliveryCreateRequest = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      project_id: S.String.pipe(T.Label()),
      id: S.Number.pipe(T.Label()),
    }).pipe(
      T.Http({
        method: "POST",
        uri: "/api/projects/{project_id}/subscriptions/{id}/test-delivery/",
        code: 200,
      }),
    ),
).annotate({
  identifier: "SubscriptionsTestDeliveryCreateRequest",
}) as any as S.Schema<SubscriptionsTestDeliveryCreateRequest>;

export interface SubscriptionsTestDeliveryCreateResponse {}
export const SubscriptionsTestDeliveryCreateResponse = /*@__PURE__*/ S.suspend(
  () => S.Struct({}),
).annotate({
  identifier: "SubscriptionsTestDeliveryCreateResponse",
}) as any as S.Schema<SubscriptionsTestDeliveryCreateResponse>;

/** List of insight IDs from the dashboard to include. Required for dashboard subscriptions, max 6. */
export type SubscriptionsUpdateRequestDashboardExportInsightsList =
  Array<number>;
export const SubscriptionsUpdateRequestDashboardExportInsightsList =
  /*@__PURE__*/ S.Array(
    S.Number,
  ) as any as S.Schema<SubscriptionsUpdateRequestDashboardExportInsightsList>;

/** * `monday` - Monday * `tuesday` - Tuesday * `wednesday` - Wednesday * `thursday` - Thursday * `friday` - Friday * `saturday` - Saturday * `sunday` - Sunday */
export type SubscriptionsUpdateRequestByweekdayItem =
  | "monday"
  | "tuesday"
  | "wednesday"
  | "thursday"
  | "friday"
  | "saturday"
  | "sunday";
export const SubscriptionsUpdateRequestByweekdayItem = /*@__PURE__*/ S.String;

/** Days of week for weekly subscriptions: monday, tuesday, wednesday, thursday, friday, saturday, sunday. */
export type SubscriptionsUpdateRequestByweekdayList = Array<
  SubscriptionsUpdateRequestByweekdayItem | (string & {})
>;
export const SubscriptionsUpdateRequestByweekdayList = /*@__PURE__*/ S.Array(
  SubscriptionsUpdateRequestByweekdayItem,
) as any as S.Schema<SubscriptionsUpdateRequestByweekdayList>;

export interface SubscriptionsUpdateRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  /** A unique integer value identifying this subscription. */
  id: number;
  /** Dashboard ID to subscribe to (mutually exclusive with insight on create). */
  dashboard?: number | null;
  /** Insight ID to subscribe to (mutually exclusive with dashboard on create). */
  insight?: number | null;
  /** List of insight IDs from the dashboard to include. Required for dashboard subscriptions, max 6. */
  dashboard_export_insights?: SubscriptionsUpdateRequestDashboardExportInsightsList;
  /** Free-text prompt that drives the AI-generated report. Required when resource_type is 'ai_prompt'. Max 4000 characters. */
  prompt?: string | null;
  /** Configuration for AI report subscriptions (analysis window, future knobs). Only valid when resource_type is 'ai_prompt'. Replaced wholesale on writes. */
  ai_prompt_config?: AIPromptConfig;
  /** Delivery channel: email or slack. * `email` - Email * `slack` - Slack */
  target_type?: TargetTypeEnum | (string & {});
  /** Recipient(s): comma-separated email addresses for email, or Slack channel name/ID for slack. */
  target_value?: string;
  /** How often to deliver: daily, weekly, monthly, or yearly. * `daily` - Daily * `weekly` - Weekly * `monthly` - Monthly * `yearly` - Yearly */
  frequency?: RecurrenceIntervalEnum | (string & {});
  /** Interval multiplier (e.g. 2 with weekly frequency means every 2 weeks). Required on create; must be 1 or greater. */
  interval?: number;
  /** Days of week for weekly subscriptions: monday, tuesday, wednesday, thursday, friday, saturday, sunday. */
  byweekday?: SubscriptionsUpdateRequestByweekdayList | null;
  /** Position within byweekday set for monthly frequency (e.g. 1 for first, -1 for last). */
  bysetpos?: number | null;
  /** Total number of deliveries before the subscription stops. Null for unlimited. */
  count?: number | null;
  /** When to start delivering (ISO 8601 datetime). */
  start_date?: string;
  /** When to stop delivering (ISO 8601 datetime). Null for indefinite. */
  until_date?: string | null;
  /** Set to true to soft-delete. Subscriptions cannot be hard-deleted. */
  deleted?: boolean;
  /** Whether the subscription is active. Set to false to pause delivery without deleting. Auto-set to false when the delivery integration becomes invalid. */
  enabled?: boolean;
  /** Human-readable name for this subscription. */
  title?: string | null;
  /** ID of a connected Slack integration. Required when target_type is slack. */
  integration_id?: number | null;
  /** Optional message included in the invitation email when adding new recipients. */
  invite_message?: string | null;
  /** Whether to immediately deliver the subscription once on save so the editor can confirm it looks right. Defaults to true on create. When omitted on update, a delivery is sent only if the edit changed what gets delivered (recipient, channel, source) or re-enabled the subscription. The recurring schedule is unaffected. */
  send_test_now?: boolean;
  /** Whether to attach an AI-generated summary to each delivery (insight and dashboard subscriptions only). Requires the organization to have approved AI data processing, and is subject to the org's active-summary cap and AI credit budget; otherwise the write is rejected. Not applicable to prompt subscriptions, which are themselves AI-generated. */
  summary_enabled?: boolean;
  /** Optional free-text guidance (max 500 chars) steering the AI summary, e.g. which metrics to emphasize. Only settable when AI summary context is enabled for the organization; clearing it (empty string) is always allowed. */
  summary_prompt_guide?: string;
}
export const SubscriptionsUpdateRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
    id: S.Number.pipe(T.Label()),
    dashboard: S.optional(S.NullOr(S.Number)),
    insight: S.optional(S.NullOr(S.Number)),
    dashboard_export_insights: S.optional(
      SubscriptionsUpdateRequestDashboardExportInsightsList,
    ),
    prompt: S.optional(S.NullOr(S.String)),
    ai_prompt_config: S.optional(AIPromptConfig),
    target_type: S.optional(TargetTypeEnum),
    target_value: S.optional(S.String),
    frequency: S.optional(RecurrenceIntervalEnum),
    interval: S.optional(S.Number),
    byweekday: S.optional(S.NullOr(SubscriptionsUpdateRequestByweekdayList)),
    bysetpos: S.optional(S.NullOr(S.Number)),
    count: S.optional(S.NullOr(S.Number)),
    start_date: S.optional(S.String),
    until_date: S.optional(S.NullOr(S.String)),
    deleted: S.optional(S.Boolean),
    enabled: S.optional(S.Boolean),
    title: S.optional(S.NullOr(S.String)),
    integration_id: S.optional(S.NullOr(S.Number)),
    invite_message: S.optional(S.NullOr(S.String)),
    send_test_now: S.optional(S.Boolean),
    summary_enabled: S.optional(S.Boolean),
    summary_prompt_guide: S.optional(S.String),
  }).pipe(
    T.Http({
      method: "PUT",
      uri: "/api/projects/{project_id}/subscriptions/{id}/",
      code: 200,
    }),
  ),
).annotate({
  identifier: "SubscriptionsUpdateRequest",
}) as any as S.Schema<SubscriptionsUpdateRequest>;

export type SubscriptionsCreateError =
  | BadRequest
  | Forbidden
  | NotFound
  | PosthogOpError;
export const subscriptionsCreate: API.OperationMethod<
  SubscriptionsCreateRequest,
  SubscriptionOutput,
  SubscriptionsCreateError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: SubscriptionsCreateRequest,
  output: SubscriptionOutput,
  errors: [BadRequest, Forbidden, NotFound],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type SubscriptionsDeliveriesListError = PosthogOpError;
/** List subscription deliveries Paginated delivery history for a subscription. Requires premium subscriptions. */
export const subscriptionsDeliveriesList: API.OperationMethod<
  SubscriptionsDeliveriesListRequest,
  PaginatedSubscriptionDeliveryList,
  SubscriptionsDeliveriesListError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: SubscriptionsDeliveriesListRequest,
  output: PaginatedSubscriptionDeliveryList,
  errors: [],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type SubscriptionsDeliveriesRetrieveError = PosthogOpError;
/** Retrieve subscription delivery Fetch one delivery row by id. */
export const subscriptionsDeliveriesRetrieve: API.OperationMethod<
  SubscriptionsDeliveriesRetrieveRequest,
  SubscriptionDelivery,
  SubscriptionsDeliveriesRetrieveError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: SubscriptionsDeliveriesRetrieveRequest,
  output: SubscriptionDelivery,
  errors: [],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type SubscriptionsDestroyError = Forbidden | NotFound | PosthogOpError;
/** Hard delete of this model is not allowed. Use a patch API call to set "deleted" to true */
export const subscriptionsDestroy: API.OperationMethod<
  SubscriptionsDestroyRequest,
  SubscriptionsDestroyResponse,
  SubscriptionsDestroyError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: SubscriptionsDestroyRequest,
  output: SubscriptionsDestroyResponse,
  errors: [Forbidden, NotFound],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type SubscriptionsListError =
  | BadRequest
  | Forbidden
  | NotFound
  | PosthogOpError;
export const subscriptionsList: API.OperationMethod<
  SubscriptionsListRequest,
  PaginatedSubscriptionListOutput,
  SubscriptionsListError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: SubscriptionsListRequest,
  output: PaginatedSubscriptionListOutput,
  errors: [BadRequest, Forbidden, NotFound],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type SubscriptionsPartialUpdateError =
  | BadRequest
  | Forbidden
  | NotFound
  | PosthogOpError;
export const subscriptionsPartialUpdate: API.OperationMethod<
  SubscriptionsPartialUpdateRequest,
  SubscriptionOutput,
  SubscriptionsPartialUpdateError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: SubscriptionsPartialUpdateRequest,
  output: SubscriptionOutput,
  errors: [BadRequest, Forbidden, NotFound],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type SubscriptionsRetrieveError = Forbidden | NotFound | PosthogOpError;
export const subscriptionsRetrieve: API.OperationMethod<
  SubscriptionsRetrieveRequest,
  SubscriptionOutput,
  SubscriptionsRetrieveError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: SubscriptionsRetrieveRequest,
  output: SubscriptionOutput,
  errors: [Forbidden, NotFound],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type SubscriptionsSummaryQuotaRetrieveError = PosthogOpError;
export const subscriptionsSummaryQuotaRetrieve: API.OperationMethod<
  SubscriptionsSummaryQuotaRetrieveRequest,
  SubscriptionsSummaryQuotaRetrieveResponse,
  SubscriptionsSummaryQuotaRetrieveError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: SubscriptionsSummaryQuotaRetrieveRequest,
  output: SubscriptionsSummaryQuotaRetrieveResponse,
  errors: [],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type SubscriptionsTestDeliveryCreateError =
  | Forbidden
  | NotFound
  | PosthogOpError;
export const subscriptionsTestDeliveryCreate: API.OperationMethod<
  SubscriptionsTestDeliveryCreateRequest,
  SubscriptionsTestDeliveryCreateResponse,
  SubscriptionsTestDeliveryCreateError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: SubscriptionsTestDeliveryCreateRequest,
  output: SubscriptionsTestDeliveryCreateResponse,
  errors: [Forbidden, NotFound],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type SubscriptionsUpdateError =
  | BadRequest
  | Forbidden
  | NotFound
  | PosthogOpError;
export const subscriptionsUpdate: API.OperationMethod<
  SubscriptionsUpdateRequest,
  SubscriptionOutput,
  SubscriptionsUpdateError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: SubscriptionsUpdateRequest,
  output: SubscriptionOutput,
  errors: [BadRequest, Forbidden, NotFound],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));
