// AUTO-GENERATED by scripts/generate.ts from .generated-specs (see scripts/convert.ts). Do not edit.
import * as S from "@distilled.cloud/core/schema";
import * as API from "@distilled.cloud/core/api";
import * as C from "@distilled.cloud/core/category";
import * as T from "../traits.ts";
import {
  PosthogProtocol,
  type PosthogOpError,
  type PosthogOpContext,
} from "../protocol.ts";
import * as Retry from "../retry.ts";

export type { PosthogOpError, PosthogOpContext };

export class BadRequest
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<BadRequest>()("BadRequest", {
      code: S.Number,
      message: S.String,
    }).pipe(C.withBadRequestError),
    [{ status: 400 }],
  ) {}

export class Forbidden
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<Forbidden>()("Forbidden", {
      code: S.Number,
      message: S.String,
    }).pipe(C.withAuthError),
    [{ status: 403 }],
  ) {}

export class NotFound
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<NotFound>()("NotFound", {
      code: S.Number,
      message: S.String,
    }).pipe(C.withBadRequestError),
    [{ status: 404 }],
  ) {}

export interface VisualReviewReposBaselinesRetrieveRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  id: string;
}
export const VisualReviewReposBaselinesRetrieveRequest =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      project_id: S.String.pipe(T.Label()),
      id: S.String.pipe(T.Label()),
    }).pipe(
      T.Http({
        method: "GET",
        uri: "/api/projects/{project_id}/visual_review/repos/{id}/baselines/",
        code: 200,
      }),
    ),
  ).annotate({
    identifier: "VisualReviewReposBaselinesRetrieveRequest",
  }) as any as S.Schema<VisualReviewReposBaselinesRetrieveRequest>;

export interface UserBasicInfo {
  id?: number;
  first_name?: string;
  email?: string;
}
export const UserBasicInfo = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.Number),
    first_name: S.optional(S.String),
    email: S.optional(S.String),
  }),
).annotate({ identifier: "UserBasicInfo" }) as any as S.Schema<UserBasicInfo>;

export interface QuarantineSourceRun {
  id: string;
  branch: string;
  commit_sha: string;
  created_at: string;
  pr_number?: number | null;
}
export const QuarantineSourceRun = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String,
    branch: S.String,
    commit_sha: S.String,
    created_at: S.String,
    pr_number: S.optional(S.NullOr(S.Number)),
  }),
).annotate({
  identifier: "QuarantineSourceRun",
}) as any as S.Schema<QuarantineSourceRun>;

export interface BaselineQuarantineSummary {
  created_by?: UserBasicInfo | null;
  source_run?: QuarantineSourceRun | null;
  id: string;
  reason: string;
  expires_at: string | null;
  created_at: string;
}
export const BaselineQuarantineSummary = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    created_by: S.optional(S.NullOr(UserBasicInfo)),
    source_run: S.optional(S.NullOr(QuarantineSourceRun)),
    id: S.String,
    reason: S.String,
    expires_at: S.NullOr(S.String),
    created_at: S.String,
  }),
).annotate({
  identifier: "BaselineQuarantineSummary",
}) as any as S.Schema<BaselineQuarantineSummary>;

export interface BaselineEntry {
  /** Active quarantine details when `is_quarantined` is true. Null otherwise. */
  quarantine?: BaselineQuarantineSummary | null;
  identifier: string;
  run_type: string;
  browser: string | null;
  thumbnail_hash: string | null;
  width: number | null;
  height: number | null;
  tolerate_count_30d: number;
  tolerate_count_90d: number;
  is_quarantined: boolean;
  last_run_at: string;
  baseline_change_count: number;
  recent_drift_avg: number | null;
}
export const BaselineEntry = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    quarantine: S.optional(S.NullOr(BaselineQuarantineSummary)),
    identifier: S.String,
    run_type: S.String,
    browser: S.NullOr(S.String),
    thumbnail_hash: S.NullOr(S.String),
    width: S.NullOr(S.Number),
    height: S.NullOr(S.Number),
    tolerate_count_30d: S.Number,
    tolerate_count_90d: S.Number,
    is_quarantined: S.Boolean,
    last_run_at: S.String,
    baseline_change_count: S.Number,
    recent_drift_avg: S.NullOr(S.Number),
  }),
).annotate({ identifier: "BaselineEntry" }) as any as S.Schema<BaselineEntry>;

export type BaselineOverviewEntriesList = Array<BaselineEntry>;
export const BaselineOverviewEntriesList = /*@__PURE__*/ S.Array(
  BaselineEntry,
) as any as S.Schema<BaselineOverviewEntriesList>;

export type BaselineTotalsByRunTypeMap = { [key: string]: number | undefined };
export const BaselineTotalsByRunTypeMap = /*@__PURE__*/ S.Record(
  S.String,
  S.Number,
) as any as S.Schema<BaselineTotalsByRunTypeMap>;

export interface BaselineTotals {
  by_run_type: BaselineTotalsByRunTypeMap;
  all_snapshots: number;
  recently_tolerated: number;
  frequently_tolerated: number;
  currently_quarantined: number;
}
export const BaselineTotals = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    by_run_type: BaselineTotalsByRunTypeMap,
    all_snapshots: S.Number,
    recently_tolerated: S.Number,
    frequently_tolerated: S.Number,
    currently_quarantined: S.Number,
  }),
).annotate({ identifier: "BaselineTotals" }) as any as S.Schema<BaselineTotals>;

export interface BaselineOverview {
  entries: BaselineOverviewEntriesList;
  totals: BaselineTotals;
  truncated: boolean;
  generated_at: string;
}
export const BaselineOverview = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    entries: BaselineOverviewEntriesList,
    totals: BaselineTotals,
    truncated: S.Boolean,
    generated_at: S.String,
  }),
).annotate({
  identifier: "BaselineOverview",
}) as any as S.Schema<BaselineOverview>;

export interface VisualReviewReposCreateRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  repo_full_name?: string;
  repo_external_id?: number | null;
}
export const VisualReviewReposCreateRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
    repo_full_name: S.optional(S.String),
    repo_external_id: S.optional(S.NullOr(S.Number)),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/api/projects/{project_id}/visual_review/repos/",
      code: 200,
    }),
  ),
).annotate({
  identifier: "VisualReviewReposCreateRequest",
}) as any as S.Schema<VisualReviewReposCreateRequest>;

export type RepoBaselineFilePathsMap = { [key: string]: string | undefined };
export const RepoBaselineFilePathsMap = /*@__PURE__*/ S.Record(
  S.String,
  S.String,
) as any as S.Schema<RepoBaselineFilePathsMap>;

export interface Repo {
  id?: string;
  team_id?: number;
  repo_external_id?: number;
  repo_full_name?: string;
  baseline_file_paths?: RepoBaselineFilePathsMap;
  enable_pr_comments?: boolean;
  created_at?: string;
}
export const Repo = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.String),
    team_id: S.optional(S.Number),
    repo_external_id: S.optional(S.Number),
    repo_full_name: S.optional(S.String),
    baseline_file_paths: S.optional(RepoBaselineFilePathsMap),
    enable_pr_comments: S.optional(S.Boolean),
    created_at: S.optional(S.String),
  }),
).annotate({ identifier: "Repo" }) as any as S.Schema<Repo>;

export interface VisualReviewReposListRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  /** Number of results to return per page. */
  limit?: number;
  /** The initial index from which to return the results. */
  offset?: number;
}
export const VisualReviewReposListRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
    limit: S.optional(S.Number.pipe(T.Query())),
    offset: S.optional(S.Number.pipe(T.Query())),
  }).pipe(
    T.Http({
      method: "GET",
      uri: "/api/projects/{project_id}/visual_review/repos/",
      code: 200,
    }),
  ),
).annotate({
  identifier: "VisualReviewReposListRequest",
}) as any as S.Schema<VisualReviewReposListRequest>;

export type PaginatedRepoListResultsList = Array<Repo>;
export const PaginatedRepoListResultsList = /*@__PURE__*/ S.Array(
  Repo,
) as any as S.Schema<PaginatedRepoListResultsList>;

export interface PaginatedRepoList {
  count?: number;
  next?: string | null;
  previous?: string | null;
  results?: PaginatedRepoListResultsList;
}
export const PaginatedRepoList = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    count: S.optional(S.Number),
    next: S.optional(S.NullOr(S.String)),
    previous: S.optional(S.NullOr(S.String)),
    results: S.optional(PaginatedRepoListResultsList),
  }),
).annotate({
  identifier: "PaginatedRepoList",
}) as any as S.Schema<PaginatedRepoList>;

export type VisualReviewReposPartialUpdateRequestBaselineFilePathsMap = {
  [key: string]: string | undefined;
};
export const VisualReviewReposPartialUpdateRequestBaselineFilePathsMap =
  /*@__PURE__*/ S.Record(
    S.String,
    S.String,
  ) as any as S.Schema<VisualReviewReposPartialUpdateRequestBaselineFilePathsMap>;

export interface VisualReviewReposPartialUpdateRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  id: string;
  baseline_file_paths?: VisualReviewReposPartialUpdateRequestBaselineFilePathsMap | null;
  enable_pr_comments?: boolean | null;
}
export const VisualReviewReposPartialUpdateRequest = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      project_id: S.String.pipe(T.Label()),
      id: S.String.pipe(T.Label()),
      baseline_file_paths: S.optional(
        S.NullOr(VisualReviewReposPartialUpdateRequestBaselineFilePathsMap),
      ),
      enable_pr_comments: S.optional(S.NullOr(S.Boolean)),
    }).pipe(
      T.Http({
        method: "PATCH",
        uri: "/api/projects/{project_id}/visual_review/repos/{id}/",
        code: 200,
      }),
    ),
).annotate({
  identifier: "VisualReviewReposPartialUpdateRequest",
}) as any as S.Schema<VisualReviewReposPartialUpdateRequest>;

export interface VisualReviewReposQuarantineCreateRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  id: string;
  run_type: string;
  /** Snapshot identifier to quarantine. */
  identifier?: string;
  /** Why this snapshot is being quarantined. */
  reason?: string;
  /** Optional pointer to the run whose failing snapshot prompted this quarantine — used to surface a 'view the failing run' link later. */
  source_run_id?: string | null;
  expires_at?: string | null;
}
export const VisualReviewReposQuarantineCreateRequest = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      project_id: S.String.pipe(T.Label()),
      id: S.String.pipe(T.Label()),
      run_type: S.String.pipe(T.Label()),
      identifier: S.optional(S.String),
      reason: S.optional(S.String),
      source_run_id: S.optional(S.NullOr(S.String)),
      expires_at: S.optional(S.NullOr(S.String)),
    }).pipe(
      T.Http({
        method: "POST",
        uri: "/api/projects/{project_id}/visual_review/repos/{id}/quarantine/{run_type}/",
        code: 200,
      }),
    ),
).annotate({
  identifier: "VisualReviewReposQuarantineCreateRequest",
}) as any as S.Schema<VisualReviewReposQuarantineCreateRequest>;

export interface QuarantinedIdentifierEntry {
  created_by?: UserBasicInfo | null;
  /** Run whose failing snapshot prompted this quarantine. Null when quarantine was created without run context. */
  source_run?: QuarantineSourceRun | null;
  id?: string;
  identifier?: string;
  run_type?: string;
  reason?: string;
  expires_at?: string | null;
  created_at?: string;
  updated_at?: string;
}
export const QuarantinedIdentifierEntry = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    created_by: S.optional(S.NullOr(UserBasicInfo)),
    source_run: S.optional(S.NullOr(QuarantineSourceRun)),
    id: S.optional(S.String),
    identifier: S.optional(S.String),
    run_type: S.optional(S.String),
    reason: S.optional(S.String),
    expires_at: S.optional(S.NullOr(S.String)),
    created_at: S.optional(S.String),
    updated_at: S.optional(S.String),
  }),
).annotate({
  identifier: "QuarantinedIdentifierEntry",
}) as any as S.Schema<QuarantinedIdentifierEntry>;

export interface VisualReviewReposQuarantineExpireCreateRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  id: string;
  run_type: string;
  /** Snapshot identifier to quarantine. */
  identifier?: string;
  /** Why this snapshot is being quarantined. */
  reason?: string;
  /** Optional pointer to the run whose failing snapshot prompted this quarantine — used to surface a 'view the failing run' link later. */
  source_run_id?: string | null;
  expires_at?: string | null;
}
export const VisualReviewReposQuarantineExpireCreateRequest =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      project_id: S.String.pipe(T.Label()),
      id: S.String.pipe(T.Label()),
      run_type: S.String.pipe(T.Label()),
      identifier: S.optional(S.String),
      reason: S.optional(S.String),
      source_run_id: S.optional(S.NullOr(S.String)),
      expires_at: S.optional(S.NullOr(S.String)),
    }).pipe(
      T.Http({
        method: "POST",
        uri: "/api/projects/{project_id}/visual_review/repos/{id}/quarantine/{run_type}/expire/",
        code: 200,
      }),
    ),
  ).annotate({
    identifier: "VisualReviewReposQuarantineExpireCreateRequest",
  }) as any as S.Schema<VisualReviewReposQuarantineExpireCreateRequest>;

export interface VisualReviewReposQuarantineExpireCreateResponse {}
export const VisualReviewReposQuarantineExpireCreateResponse =
  /*@__PURE__*/ S.suspend(() => S.Struct({})).annotate({
    identifier: "VisualReviewReposQuarantineExpireCreateResponse",
  }) as any as S.Schema<VisualReviewReposQuarantineExpireCreateResponse>;

export interface VisualReviewReposQuarantineListRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  id: string;
  /** Filter by identifier (returns full history) */
  identifier?: string;
  /** Number of results to return per page. */
  limit?: number;
  /** The initial index from which to return the results. */
  offset?: number;
  /** Filter by run type */
  run_type?: string;
}
export const VisualReviewReposQuarantineListRequest = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      project_id: S.String.pipe(T.Label()),
      id: S.String.pipe(T.Label()),
      identifier: S.optional(S.String.pipe(T.Query())),
      limit: S.optional(S.Number.pipe(T.Query())),
      offset: S.optional(S.Number.pipe(T.Query())),
      run_type: S.optional(S.String.pipe(T.Query())),
    }).pipe(
      T.Http({
        method: "GET",
        uri: "/api/projects/{project_id}/visual_review/repos/{id}/quarantine/",
        code: 200,
      }),
    ),
).annotate({
  identifier: "VisualReviewReposQuarantineListRequest",
}) as any as S.Schema<VisualReviewReposQuarantineListRequest>;

export type PaginatedQuarantinedIdentifierEntryListResultsList =
  Array<QuarantinedIdentifierEntry>;
export const PaginatedQuarantinedIdentifierEntryListResultsList =
  /*@__PURE__*/ S.Array(
    QuarantinedIdentifierEntry,
  ) as any as S.Schema<PaginatedQuarantinedIdentifierEntryListResultsList>;

export interface PaginatedQuarantinedIdentifierEntryList {
  count?: number;
  next?: string | null;
  previous?: string | null;
  results?: PaginatedQuarantinedIdentifierEntryListResultsList;
}
export const PaginatedQuarantinedIdentifierEntryList = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      count: S.optional(S.Number),
      next: S.optional(S.NullOr(S.String)),
      previous: S.optional(S.NullOr(S.String)),
      results: S.optional(PaginatedQuarantinedIdentifierEntryListResultsList),
    }),
).annotate({
  identifier: "PaginatedQuarantinedIdentifierEntryList",
}) as any as S.Schema<PaginatedQuarantinedIdentifierEntryList>;

export interface VisualReviewReposRetrieveRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  id: string;
}
export const VisualReviewReposRetrieveRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
    id: S.String.pipe(T.Label()),
  }).pipe(
    T.Http({
      method: "GET",
      uri: "/api/projects/{project_id}/visual_review/repos/{id}/",
      code: 200,
    }),
  ),
).annotate({
  identifier: "VisualReviewReposRetrieveRequest",
}) as any as S.Schema<VisualReviewReposRetrieveRequest>;

export interface VisualReviewReposRunsCountsRetrieveRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  repo_id: string;
}
export const VisualReviewReposRunsCountsRetrieveRequest =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      project_id: S.String.pipe(T.Label()),
      repo_id: S.String.pipe(T.Label()),
    }).pipe(
      T.Http({
        method: "GET",
        uri: "/api/projects/{project_id}/visual_review/repos/{repo_id}/runs/counts/",
        code: 200,
      }),
    ),
  ).annotate({
    identifier: "VisualReviewReposRunsCountsRetrieveRequest",
  }) as any as S.Schema<VisualReviewReposRunsCountsRetrieveRequest>;

export interface ReviewStateCounts {
  needs_review?: number;
  clean?: number;
  processing?: number;
  stale?: number;
}
export const ReviewStateCounts = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    needs_review: S.optional(S.Number),
    clean: S.optional(S.Number),
    processing: S.optional(S.Number),
    stale: S.optional(S.Number),
  }),
).annotate({
  identifier: "ReviewStateCounts",
}) as any as S.Schema<ReviewStateCounts>;

export interface VisualReviewReposRunsListRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  repo_id: string;
  /** Number of results to return per page. */
  limit?: number;
  /** The initial index from which to return the results. */
  offset?: number;
  /** Filter by review state */
  review_state?: string;
  /** Free-text search over branch, commit SHA, run type, and PR number */
  search?: string;
}
export const VisualReviewReposRunsListRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
    repo_id: S.String.pipe(T.Label()),
    limit: S.optional(S.Number.pipe(T.Query())),
    offset: S.optional(S.Number.pipe(T.Query())),
    review_state: S.optional(S.String.pipe(T.Query())),
    search: S.optional(S.String.pipe(T.Query())),
  }).pipe(
    T.Http({
      method: "GET",
      uri: "/api/projects/{project_id}/visual_review/repos/{repo_id}/runs/",
      code: 200,
    }),
  ),
).annotate({
  identifier: "VisualReviewReposRunsListRequest",
}) as any as S.Schema<VisualReviewReposRunsListRequest>;

export type SearchMatchTypeEnum = "exact" | "similar";
export const SearchMatchTypeEnum = /*@__PURE__*/ S.String;

export interface RunSummary {
  total?: number;
  changed?: number;
  new?: number;
  removed?: number;
  unchanged?: number;
  unresolved?: number;
  tolerated_matched?: number;
}
export const RunSummary = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    total: S.optional(S.Number),
    changed: S.optional(S.Number),
    new: S.optional(S.Number),
    removed: S.optional(S.Number),
    unchanged: S.optional(S.Number),
    unresolved: S.optional(S.Number),
    tolerated_matched: S.optional(S.Number),
  }),
).annotate({ identifier: "RunSummary" }) as any as S.Schema<RunSummary>;

export type RunMetadataMap = { [key: string]: unknown | undefined };
export const RunMetadataMap = /*@__PURE__*/ S.Record(
  S.String,
  S.Unknown,
) as any as S.Schema<RunMetadataMap>;

export interface Run {
  approved_by?: UserBasicInfo | null;
  /** How this row matched the `search` query parameter: `exact` (the term is a case-insensitive substring of branch/run type, a commit SHA prefix, or an exact PR number) or `similar` (a fuzzy trigram match only). Results are ordered exact-first. Null when the list is not filtered by `search`. * `exact` - exact * `similar` - similar */
  search_match_type?: SearchMatchTypeEnum | null;
  id?: string;
  repo_id?: string;
  status?: string;
  run_type?: string;
  commit_sha?: string;
  branch?: string;
  pr_number?: number | null;
  approved?: boolean;
  approved_at?: string | null;
  summary?: RunSummary;
  error_message?: string | null;
  created_at?: string;
  completed_at?: string | null;
  is_stale?: boolean;
  superseded_by_id?: string | null;
  metadata?: RunMetadataMap;
}
export const Run = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    approved_by: S.optional(S.NullOr(UserBasicInfo)),
    search_match_type: S.optional(S.NullOr(SearchMatchTypeEnum)),
    id: S.optional(S.String),
    repo_id: S.optional(S.String),
    status: S.optional(S.String),
    run_type: S.optional(S.String),
    commit_sha: S.optional(S.String),
    branch: S.optional(S.String),
    pr_number: S.optional(S.NullOr(S.Number)),
    approved: S.optional(S.Boolean),
    approved_at: S.optional(S.NullOr(S.String)),
    summary: S.optional(RunSummary),
    error_message: S.optional(S.NullOr(S.String)),
    created_at: S.optional(S.String),
    completed_at: S.optional(S.NullOr(S.String)),
    is_stale: S.optional(S.Boolean),
    superseded_by_id: S.optional(S.NullOr(S.String)),
    metadata: S.optional(RunMetadataMap),
  }),
).annotate({ identifier: "Run" }) as any as S.Schema<Run>;

export type PaginatedRunListResultsList = Array<Run>;
export const PaginatedRunListResultsList = /*@__PURE__*/ S.Array(
  Run,
) as any as S.Schema<PaginatedRunListResultsList>;

export interface PaginatedRunList {
  count?: number;
  next?: string | null;
  previous?: string | null;
  results?: PaginatedRunListResultsList;
}
export const PaginatedRunList = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    count: S.optional(S.Number),
    next: S.optional(S.NullOr(S.String)),
    previous: S.optional(S.NullOr(S.String)),
    results: S.optional(PaginatedRunListResultsList),
  }),
).annotate({
  identifier: "PaginatedRunList",
}) as any as S.Schema<PaginatedRunList>;

export interface VisualReviewReposSnapshotsListRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  repo_id: string;
  /** Run type (storybook, playwright) */
  run_type: string;
  /** Snapshot identifier; clients must percent-encode before sending */
  identifier: string;
  /** Number of results to return per page. */
  limit?: number;
  /** The initial index from which to return the results. */
  offset?: number;
}
export const VisualReviewReposSnapshotsListRequest = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      project_id: S.String.pipe(T.Label()),
      repo_id: S.String.pipe(T.Label()),
      run_type: S.String.pipe(T.Label()),
      identifier: S.String.pipe(T.Label()),
      limit: S.optional(S.Number.pipe(T.Query())),
      offset: S.optional(S.Number.pipe(T.Query())),
    }).pipe(
      T.Http({
        method: "GET",
        uri: "/api/projects/{project_id}/visual_review/repos/{repo_id}/snapshots/{run_type}/{identifier}/",
        code: 200,
      }),
    ),
).annotate({
  identifier: "VisualReviewReposSnapshotsListRequest",
}) as any as S.Schema<VisualReviewReposSnapshotsListRequest>;

export interface Artifact {
  id?: string;
  content_hash?: string;
  width?: number | null;
  height?: number | null;
  download_url?: string | null;
}
export const Artifact = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.String),
    content_hash: S.optional(S.String),
    width: S.optional(S.NullOr(S.Number)),
    height: S.optional(S.NullOr(S.Number)),
    download_url: S.optional(S.NullOr(S.String)),
  }),
).annotate({ identifier: "Artifact" }) as any as S.Schema<Artifact>;

export interface SnapshotHistoryEntry {
  current_artifact?: Artifact | null;
  run_id?: string;
  snapshot_id?: string;
  result?: string;
  branch?: string;
  commit_sha?: string;
  created_at?: string;
  pr_number?: number | null;
  diff_percentage?: number | null;
  review_state?: string;
  ssim_score?: number | null;
  change_kind?: string;
  size_mismatch?: boolean;
}
export const SnapshotHistoryEntry = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    current_artifact: S.optional(S.NullOr(Artifact)),
    run_id: S.optional(S.String),
    snapshot_id: S.optional(S.String),
    result: S.optional(S.String),
    branch: S.optional(S.String),
    commit_sha: S.optional(S.String),
    created_at: S.optional(S.String),
    pr_number: S.optional(S.NullOr(S.Number)),
    diff_percentage: S.optional(S.NullOr(S.Number)),
    review_state: S.optional(S.String),
    ssim_score: S.optional(S.NullOr(S.Number)),
    change_kind: S.optional(S.String),
    size_mismatch: S.optional(S.Boolean),
  }),
).annotate({
  identifier: "SnapshotHistoryEntry",
}) as any as S.Schema<SnapshotHistoryEntry>;

export type PaginatedSnapshotHistoryEntryListResultsList =
  Array<SnapshotHistoryEntry>;
export const PaginatedSnapshotHistoryEntryListResultsList =
  /*@__PURE__*/ S.Array(
    SnapshotHistoryEntry,
  ) as any as S.Schema<PaginatedSnapshotHistoryEntryListResultsList>;

export interface PaginatedSnapshotHistoryEntryList {
  count?: number;
  next?: string | null;
  previous?: string | null;
  results?: PaginatedSnapshotHistoryEntryListResultsList;
}
export const PaginatedSnapshotHistoryEntryList = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    count: S.optional(S.Number),
    next: S.optional(S.NullOr(S.String)),
    previous: S.optional(S.NullOr(S.String)),
    results: S.optional(PaginatedSnapshotHistoryEntryListResultsList),
  }),
).annotate({
  identifier: "PaginatedSnapshotHistoryEntryList",
}) as any as S.Schema<PaginatedSnapshotHistoryEntryList>;

export interface VisualReviewReposThumbnailsRetrieveRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  id: string;
  identifier: string;
}
export const VisualReviewReposThumbnailsRetrieveRequest =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      project_id: S.String.pipe(T.Label()),
      id: S.String.pipe(T.Label()),
      identifier: S.String.pipe(T.Label()),
    }).pipe(
      T.Http({
        method: "GET",
        uri: "/api/projects/{project_id}/visual_review/repos/{id}/thumbnails/{identifier}/",
        code: 200,
      }),
    ),
  ).annotate({
    identifier: "VisualReviewReposThumbnailsRetrieveRequest",
  }) as any as S.Schema<VisualReviewReposThumbnailsRetrieveRequest>;

export interface VisualReviewReposThumbnailsRetrieveResponse {}
export const VisualReviewReposThumbnailsRetrieveResponse =
  /*@__PURE__*/ S.suspend(() => S.Struct({})).annotate({
    identifier: "VisualReviewReposThumbnailsRetrieveResponse",
  }) as any as S.Schema<VisualReviewReposThumbnailsRetrieveResponse>;

export type SnapshotManifestItemMetadataMap = {
  [key: string]: unknown | undefined;
};
export const SnapshotManifestItemMetadataMap = /*@__PURE__*/ S.Record(
  S.String,
  S.Unknown,
) as any as S.Schema<SnapshotManifestItemMetadataMap>;

export interface SnapshotManifestItem {
  identifier?: string;
  content_hash?: string;
  width?: number | null;
  height?: number | null;
  metadata?: SnapshotManifestItemMetadataMap;
}
export const SnapshotManifestItem = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    identifier: S.optional(S.String),
    content_hash: S.optional(S.String),
    width: S.optional(S.NullOr(S.Number)),
    height: S.optional(S.NullOr(S.Number)),
    metadata: S.optional(SnapshotManifestItemMetadataMap),
  }),
).annotate({
  identifier: "SnapshotManifestItem",
}) as any as S.Schema<SnapshotManifestItem>;

export type VisualReviewRunsAddSnapshotsCreateRequestSnapshotsList =
  Array<SnapshotManifestItem>;
export const VisualReviewRunsAddSnapshotsCreateRequestSnapshotsList =
  /*@__PURE__*/ S.Array(
    SnapshotManifestItem,
  ) as any as S.Schema<VisualReviewRunsAddSnapshotsCreateRequestSnapshotsList>;

export type VisualReviewRunsAddSnapshotsCreateRequestBaselineHashesMap = {
  [key: string]: string | undefined;
};
export const VisualReviewRunsAddSnapshotsCreateRequestBaselineHashesMap =
  /*@__PURE__*/ S.Record(
    S.String,
    S.String,
  ) as any as S.Schema<VisualReviewRunsAddSnapshotsCreateRequestBaselineHashesMap>;

export interface VisualReviewRunsAddSnapshotsCreateRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  id: string;
  snapshots?: VisualReviewRunsAddSnapshotsCreateRequestSnapshotsList;
  baseline_hashes?: VisualReviewRunsAddSnapshotsCreateRequestBaselineHashesMap;
}
export const VisualReviewRunsAddSnapshotsCreateRequest =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      project_id: S.String.pipe(T.Label()),
      id: S.String.pipe(T.Label()),
      snapshots: S.optional(
        VisualReviewRunsAddSnapshotsCreateRequestSnapshotsList,
      ),
      baseline_hashes: S.optional(
        VisualReviewRunsAddSnapshotsCreateRequestBaselineHashesMap,
      ),
    }).pipe(
      T.Http({
        method: "POST",
        uri: "/api/projects/{project_id}/visual_review/runs/{id}/add-snapshots/",
        code: 200,
      }),
    ),
  ).annotate({
    identifier: "VisualReviewRunsAddSnapshotsCreateRequest",
  }) as any as S.Schema<VisualReviewRunsAddSnapshotsCreateRequest>;

export type UploadTargetFieldsMap = { [key: string]: string | undefined };
export const UploadTargetFieldsMap = /*@__PURE__*/ S.Record(
  S.String,
  S.String,
) as any as S.Schema<UploadTargetFieldsMap>;

export interface UploadTarget {
  content_hash?: string;
  url?: string;
  fields?: UploadTargetFieldsMap;
}
export const UploadTarget = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    content_hash: S.optional(S.String),
    url: S.optional(S.String),
    fields: S.optional(UploadTargetFieldsMap),
  }),
).annotate({ identifier: "UploadTarget" }) as any as S.Schema<UploadTarget>;

export type AddSnapshotsResultUploadsList = Array<UploadTarget>;
export const AddSnapshotsResultUploadsList = /*@__PURE__*/ S.Array(
  UploadTarget,
) as any as S.Schema<AddSnapshotsResultUploadsList>;

export interface AddSnapshotsResult {
  added?: number;
  uploads?: AddSnapshotsResultUploadsList;
}
export const AddSnapshotsResult = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    added: S.optional(S.Number),
    uploads: S.optional(AddSnapshotsResultUploadsList),
  }),
).annotate({
  identifier: "AddSnapshotsResult",
}) as any as S.Schema<AddSnapshotsResult>;

export interface ApproveSnapshotInput {
  /** The snapshot identifier to approve (e.g. Storybook story id plus theme). */
  identifier?: string;
  /** The content hash of the new baseline image to record for this identifier. */
  new_hash?: string;
}
export const ApproveSnapshotInput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    identifier: S.optional(S.String),
    new_hash: S.optional(S.String),
  }),
).annotate({
  identifier: "ApproveSnapshotInput",
}) as any as S.Schema<ApproveSnapshotInput>;

/** Snapshots to mark reviewed, each with `identifier` and `new_hash`. This only records the review in the database (the per-snapshot "Accept change" action) — it does not change the baseline or the GitHub gate. Commit the baseline and green the gate with the finalize endpoint. */
export type VisualReviewRunsApproveCreateRequestSnapshotsList =
  Array<ApproveSnapshotInput>;
export const VisualReviewRunsApproveCreateRequestSnapshotsList =
  /*@__PURE__*/ S.Array(
    ApproveSnapshotInput,
  ) as any as S.Schema<VisualReviewRunsApproveCreateRequestSnapshotsList>;

export interface VisualReviewRunsApproveCreateRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  id: string;
  /** Snapshots to mark reviewed, each with `identifier` and `new_hash`. This only records the review in the database (the per-snapshot "Accept change" action) — it does not change the baseline or the GitHub gate. Commit the baseline and green the gate with the finalize endpoint. */
  snapshots: VisualReviewRunsApproveCreateRequestSnapshotsList;
}
export const VisualReviewRunsApproveCreateRequest = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      project_id: S.String.pipe(T.Label()),
      id: S.String.pipe(T.Label()),
      snapshots: VisualReviewRunsApproveCreateRequestSnapshotsList,
    }).pipe(
      T.Http({
        method: "POST",
        uri: "/api/projects/{project_id}/visual_review/runs/{id}/approve/",
        code: 200,
      }),
    ),
).annotate({
  identifier: "VisualReviewRunsApproveCreateRequest",
}) as any as S.Schema<VisualReviewRunsApproveCreateRequest>;

export interface VisualReviewRunsCompleteCreateRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  id: string;
}
export const VisualReviewRunsCompleteCreateRequest = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      project_id: S.String.pipe(T.Label()),
      id: S.String.pipe(T.Label()),
    }).pipe(
      T.Http({
        method: "POST",
        uri: "/api/projects/{project_id}/visual_review/runs/{id}/complete/",
        code: 200,
      }),
    ),
).annotate({
  identifier: "VisualReviewRunsCompleteCreateRequest",
}) as any as S.Schema<VisualReviewRunsCompleteCreateRequest>;

export interface VisualReviewRunsCountsRetrieveRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
}
export const VisualReviewRunsCountsRetrieveRequest = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      project_id: S.String.pipe(T.Label()),
    }).pipe(
      T.Http({
        method: "GET",
        uri: "/api/projects/{project_id}/visual_review/runs/counts/",
        code: 200,
      }),
    ),
).annotate({
  identifier: "VisualReviewRunsCountsRetrieveRequest",
}) as any as S.Schema<VisualReviewRunsCountsRetrieveRequest>;

export type VisualReviewRunsCreateRequestSnapshotsList =
  Array<SnapshotManifestItem>;
export const VisualReviewRunsCreateRequestSnapshotsList = /*@__PURE__*/ S.Array(
  SnapshotManifestItem,
) as any as S.Schema<VisualReviewRunsCreateRequestSnapshotsList>;

export type VisualReviewRunsCreateRequestBaselineHashesMap = {
  [key: string]: string | undefined;
};
export const VisualReviewRunsCreateRequestBaselineHashesMap =
  /*@__PURE__*/ S.Record(
    S.String,
    S.String,
  ) as any as S.Schema<VisualReviewRunsCreateRequestBaselineHashesMap>;

export type VisualReviewRunsCreateRequestRemovedIdentifiersList = Array<string>;
export const VisualReviewRunsCreateRequestRemovedIdentifiersList =
  /*@__PURE__*/ S.Array(
    S.String,
  ) as any as S.Schema<VisualReviewRunsCreateRequestRemovedIdentifiersList>;

export type VisualReviewRunsCreateRequestMetadataMap = {
  [key: string]: unknown | undefined;
};
export const VisualReviewRunsCreateRequestMetadataMap = /*@__PURE__*/ S.Record(
  S.String,
  S.Unknown,
) as any as S.Schema<VisualReviewRunsCreateRequestMetadataMap>;

export interface VisualReviewRunsCreateRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  repo_id?: string;
  run_type?: string;
  commit_sha?: string;
  branch?: string;
  snapshots?: VisualReviewRunsCreateRequestSnapshotsList;
  pr_number?: number | null;
  baseline_hashes?: VisualReviewRunsCreateRequestBaselineHashesMap;
  unchanged_count?: number;
  removed_identifiers?: VisualReviewRunsCreateRequestRemovedIdentifiersList;
  purpose?: string;
  metadata?: VisualReviewRunsCreateRequestMetadataMap;
  is_partial?: boolean;
}
export const VisualReviewRunsCreateRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
    repo_id: S.optional(S.String),
    run_type: S.optional(S.String),
    commit_sha: S.optional(S.String),
    branch: S.optional(S.String),
    snapshots: S.optional(VisualReviewRunsCreateRequestSnapshotsList),
    pr_number: S.optional(S.NullOr(S.Number)),
    baseline_hashes: S.optional(VisualReviewRunsCreateRequestBaselineHashesMap),
    unchanged_count: S.optional(S.Number),
    removed_identifiers: S.optional(
      VisualReviewRunsCreateRequestRemovedIdentifiersList,
    ),
    purpose: S.optional(S.String),
    metadata: S.optional(VisualReviewRunsCreateRequestMetadataMap),
    is_partial: S.optional(S.Boolean),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/api/projects/{project_id}/visual_review/runs/",
      code: 200,
    }),
  ),
).annotate({
  identifier: "VisualReviewRunsCreateRequest",
}) as any as S.Schema<VisualReviewRunsCreateRequest>;

export type CreateRunResultUploadsList = Array<UploadTarget>;
export const CreateRunResultUploadsList = /*@__PURE__*/ S.Array(
  UploadTarget,
) as any as S.Schema<CreateRunResultUploadsList>;

export interface CreateRunResult {
  run_id?: string;
  uploads?: CreateRunResultUploadsList;
}
export const CreateRunResult = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    run_id: S.optional(S.String),
    uploads: S.optional(CreateRunResultUploadsList),
  }),
).annotate({
  identifier: "CreateRunResult",
}) as any as S.Schema<CreateRunResult>;

export interface VisualReviewRunsFinalizeCreateRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  id: string;
  /** Approve every still-pending changed and new snapshot before finalizing (tolerated snapshots are left untouched). Leave false to finalize a run you've already reviewed — finalizing fails if any changed/new snapshot is still unreviewed. */
  approve_all?: boolean;
  /** Whether the server commits the approved baseline to the PR branch and greens the gate (the normal path — leave true). Set false only for tooling that commits the baseline itself: the server skips the commit and returns the signed YAML in `baseline_content` instead. With false, the gate is NOT greened and `metadata.baseline_commit_sha` is absent. */
  commit_to_github?: boolean;
  /** Whether to embed the before/after snapshot images in the post-approval PR comment. The comment itself is always posted (when the run was initiated from a GitHub review prompt and the repo has PR comments enabled); this flag only controls the images. Defaults false — the comment stays a text summary unless the reviewer opts in to attach the snapshots. */
  add_images_to_comment_on_pr?: boolean;
}
export const VisualReviewRunsFinalizeCreateRequest = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      project_id: S.String.pipe(T.Label()),
      id: S.String.pipe(T.Label()),
      approve_all: S.optional(S.Boolean),
      commit_to_github: S.optional(S.Boolean),
      add_images_to_comment_on_pr: S.optional(S.Boolean),
    }).pipe(
      T.Http({
        method: "POST",
        uri: "/api/projects/{project_id}/visual_review/runs/{id}/finalize/",
        code: 200,
      }),
    ),
).annotate({
  identifier: "VisualReviewRunsFinalizeCreateRequest",
}) as any as S.Schema<VisualReviewRunsFinalizeCreateRequest>;

export interface FinalizeResult {
  run: Run;
  baseline_content: string;
}
export const FinalizeResult = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    run: Run,
    baseline_content: S.String,
  }),
).annotate({ identifier: "FinalizeResult" }) as any as S.Schema<FinalizeResult>;

export interface VisualReviewRunsListRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  /** Filter by branch name */
  branch?: string;
  /** Filter by full commit SHA */
  commit_sha?: string;
  /** Number of results to return per page. */
  limit?: number;
  /** The initial index from which to return the results. */
  offset?: number;
  /** Filter by GitHub PR number */
  pr_number?: number;
  /** Filter by review state */
  review_state?: string;
  /** Free-text search over branch, commit SHA, run type, and PR number */
  search?: string;
}
export const VisualReviewRunsListRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
    branch: S.optional(S.String.pipe(T.Query())),
    commit_sha: S.optional(S.String.pipe(T.Query())),
    limit: S.optional(S.Number.pipe(T.Query())),
    offset: S.optional(S.Number.pipe(T.Query())),
    pr_number: S.optional(S.Number.pipe(T.Query())),
    review_state: S.optional(S.String.pipe(T.Query())),
    search: S.optional(S.String.pipe(T.Query())),
  }).pipe(
    T.Http({
      method: "GET",
      uri: "/api/projects/{project_id}/visual_review/runs/",
      code: 200,
    }),
  ),
).annotate({
  identifier: "VisualReviewRunsListRequest",
}) as any as S.Schema<VisualReviewRunsListRequest>;

export interface VisualReviewRunsRecomputeCreateRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  id: string;
}
export const VisualReviewRunsRecomputeCreateRequest = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      project_id: S.String.pipe(T.Label()),
      id: S.String.pipe(T.Label()),
    }).pipe(
      T.Http({
        method: "POST",
        uri: "/api/projects/{project_id}/visual_review/runs/{id}/recompute/",
        code: 200,
      }),
    ),
).annotate({
  identifier: "VisualReviewRunsRecomputeCreateRequest",
}) as any as S.Schema<VisualReviewRunsRecomputeCreateRequest>;

export interface RecomputeResult {
  run?: Run;
  counts_changed?: boolean;
  unresolved?: number;
  ci_rerun_triggered?: boolean;
  ci_rerun_error?: string | null;
}
export const RecomputeResult = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    run: S.optional(Run),
    counts_changed: S.optional(S.Boolean),
    unresolved: S.optional(S.Number),
    ci_rerun_triggered: S.optional(S.Boolean),
    ci_rerun_error: S.optional(S.NullOr(S.String)),
  }),
).annotate({
  identifier: "RecomputeResult",
}) as any as S.Schema<RecomputeResult>;

export interface VisualReviewRunsRetrieveRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  id: string;
}
export const VisualReviewRunsRetrieveRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
    id: S.String.pipe(T.Label()),
  }).pipe(
    T.Http({
      method: "GET",
      uri: "/api/projects/{project_id}/visual_review/runs/{id}/",
      code: 200,
    }),
  ),
).annotate({
  identifier: "VisualReviewRunsRetrieveRequest",
}) as any as S.Schema<VisualReviewRunsRetrieveRequest>;

export interface VisualReviewRunsSnapshotHistoryListRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  id: string;
  /** Snapshot identifier */
  identifier: string;
  /** Number of results to return per page. */
  limit?: number;
  /** The initial index from which to return the results. */
  offset?: number;
}
export const VisualReviewRunsSnapshotHistoryListRequest =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      project_id: S.String.pipe(T.Label()),
      id: S.String.pipe(T.Label()),
      identifier: S.String.pipe(T.Query()),
      limit: S.optional(S.Number.pipe(T.Query())),
      offset: S.optional(S.Number.pipe(T.Query())),
    }).pipe(
      T.Http({
        method: "GET",
        uri: "/api/projects/{project_id}/visual_review/runs/{id}/snapshot-history/",
        code: 200,
      }),
    ),
  ).annotate({
    identifier: "VisualReviewRunsSnapshotHistoryListRequest",
  }) as any as S.Schema<VisualReviewRunsSnapshotHistoryListRequest>;

export interface VisualReviewRunsSnapshotsListRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  id: string;
  /** Whether to include snapshots whose identifier is currently quarantined. Defaults to false: quarantined snapshots are excluded from results and reported in quarantined_count instead, since they are noise when reviewing real changes. */
  include_quarantined?: boolean;
  /** Number of results to return per page. */
  limit?: number;
  /** The initial index from which to return the results. */
  offset?: number;
}
export const VisualReviewRunsSnapshotsListRequest = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      project_id: S.String.pipe(T.Label()),
      id: S.String.pipe(T.Label()),
      include_quarantined: S.optional(S.Boolean.pipe(T.Query())),
      limit: S.optional(S.Number.pipe(T.Query())),
      offset: S.optional(S.Number.pipe(T.Query())),
    }).pipe(
      T.Http({
        method: "GET",
        uri: "/api/projects/{project_id}/visual_review/runs/{id}/snapshots/",
        code: 200,
      }),
    ),
).annotate({
  identifier: "VisualReviewRunsSnapshotsListRequest",
}) as any as S.Schema<VisualReviewRunsSnapshotsListRequest>;

export interface DiffCluster {
  x: number;
  y: number;
  width: number;
  height: number;
  pixel_count: number;
  centroid_x: number;
  centroid_y: number;
}
export const DiffCluster = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    x: S.Number,
    y: S.Number,
    width: S.Number,
    height: S.Number,
    pixel_count: S.Number,
    centroid_x: S.Number,
    centroid_y: S.Number,
  }),
).annotate({ identifier: "DiffCluster" }) as any as S.Schema<DiffCluster>;

export type ClusterSummaryItemsList = Array<DiffCluster>;
export const ClusterSummaryItemsList = /*@__PURE__*/ S.Array(
  DiffCluster,
) as any as S.Schema<ClusterSummaryItemsList>;

export interface ClusterSummary {
  items: ClusterSummaryItemsList;
  total: number;
  truncated: boolean;
}
export const ClusterSummary = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    items: ClusterSummaryItemsList,
    total: S.Number,
    truncated: S.Boolean,
  }),
).annotate({ identifier: "ClusterSummary" }) as any as S.Schema<ClusterSummary>;

export type SnapshotMetadataMap = { [key: string]: unknown | undefined };
export const SnapshotMetadataMap = /*@__PURE__*/ S.Record(
  S.String,
  S.Unknown,
) as any as S.Schema<SnapshotMetadataMap>;

export interface Snapshot {
  current_artifact?: Artifact | null;
  baseline_artifact?: Artifact | null;
  diff_artifact?: Artifact | null;
  reviewed_by?: UserBasicInfo | null;
  cluster_summary?: ClusterSummary | null;
  id?: string;
  run_id?: string;
  identifier?: string;
  result?: string;
  classification_reason?: string;
  diff_percentage?: number | null;
  diff_pixel_count?: number | null;
  review_state?: string;
  reviewed_at?: string | null;
  approved_hash?: string;
  tolerated_hash_id?: string | null;
  is_quarantined?: boolean;
  metadata?: SnapshotMetadataMap;
  ssim_score?: number | null;
  change_kind?: string;
  size_mismatch?: boolean;
}
export const Snapshot = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    current_artifact: S.optional(S.NullOr(Artifact)),
    baseline_artifact: S.optional(S.NullOr(Artifact)),
    diff_artifact: S.optional(S.NullOr(Artifact)),
    reviewed_by: S.optional(S.NullOr(UserBasicInfo)),
    cluster_summary: S.optional(S.NullOr(ClusterSummary)),
    id: S.optional(S.String),
    run_id: S.optional(S.String),
    identifier: S.optional(S.String),
    result: S.optional(S.String),
    classification_reason: S.optional(S.String),
    diff_percentage: S.optional(S.NullOr(S.Number)),
    diff_pixel_count: S.optional(S.NullOr(S.Number)),
    review_state: S.optional(S.String),
    reviewed_at: S.optional(S.NullOr(S.String)),
    approved_hash: S.optional(S.String),
    tolerated_hash_id: S.optional(S.NullOr(S.String)),
    is_quarantined: S.optional(S.Boolean),
    metadata: S.optional(SnapshotMetadataMap),
    ssim_score: S.optional(S.NullOr(S.Number)),
    change_kind: S.optional(S.String),
    size_mismatch: S.optional(S.Boolean),
  }),
).annotate({ identifier: "Snapshot" }) as any as S.Schema<Snapshot>;

export type PaginatedSnapshotListResultsList = Array<Snapshot>;
export const PaginatedSnapshotListResultsList = /*@__PURE__*/ S.Array(
  Snapshot,
) as any as S.Schema<PaginatedSnapshotListResultsList>;

export interface PaginatedSnapshotList {
  count?: number;
  next?: string | null;
  previous?: string | null;
  results?: PaginatedSnapshotListResultsList;
  /** Count of this run's snapshots whose identifier is currently quarantined. Excluded from results unless include_quarantined=true is passed. */
  quarantined_count?: number;
}
export const PaginatedSnapshotList = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    count: S.optional(S.Number),
    next: S.optional(S.NullOr(S.String)),
    previous: S.optional(S.NullOr(S.String)),
    results: S.optional(PaginatedSnapshotListResultsList),
    quarantined_count: S.optional(S.Number),
  }),
).annotate({
  identifier: "PaginatedSnapshotList",
}) as any as S.Schema<PaginatedSnapshotList>;

export interface VisualReviewRunsTolerateCreateRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  id: string;
  /** UUID of the changed snapshot to mark as a known tolerated alternate. Future runs that produce the same alternate hash for this identifier will not be flagged as changes. */
  snapshot_id?: string;
}
export const VisualReviewRunsTolerateCreateRequest = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      project_id: S.String.pipe(T.Label()),
      id: S.String.pipe(T.Label()),
      snapshot_id: S.optional(S.String),
    }).pipe(
      T.Http({
        method: "POST",
        uri: "/api/projects/{project_id}/visual_review/runs/{id}/tolerate/",
        code: 200,
      }),
    ),
).annotate({
  identifier: "VisualReviewRunsTolerateCreateRequest",
}) as any as S.Schema<VisualReviewRunsTolerateCreateRequest>;

export interface VisualReviewRunsToleratedHashesListRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  id: string;
  /** Snapshot identifier */
  identifier: string;
  /** Number of results to return per page. */
  limit?: number;
  /** The initial index from which to return the results. */
  offset?: number;
}
export const VisualReviewRunsToleratedHashesListRequest =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      project_id: S.String.pipe(T.Label()),
      id: S.String.pipe(T.Label()),
      identifier: S.String.pipe(T.Query()),
      limit: S.optional(S.Number.pipe(T.Query())),
      offset: S.optional(S.Number.pipe(T.Query())),
    }).pipe(
      T.Http({
        method: "GET",
        uri: "/api/projects/{project_id}/visual_review/runs/{id}/tolerated-hashes/",
        code: 200,
      }),
    ),
  ).annotate({
    identifier: "VisualReviewRunsToleratedHashesListRequest",
  }) as any as S.Schema<VisualReviewRunsToleratedHashesListRequest>;

export interface ToleratedHashEntry {
  id?: string;
  alternate_hash?: string;
  baseline_hash?: string;
  reason?: string;
  diff_percentage?: number | null;
  created_at?: string;
  source_run_id?: string | null;
}
export const ToleratedHashEntry = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.String),
    alternate_hash: S.optional(S.String),
    baseline_hash: S.optional(S.String),
    reason: S.optional(S.String),
    diff_percentage: S.optional(S.NullOr(S.Number)),
    created_at: S.optional(S.String),
    source_run_id: S.optional(S.NullOr(S.String)),
  }),
).annotate({
  identifier: "ToleratedHashEntry",
}) as any as S.Schema<ToleratedHashEntry>;

export type PaginatedToleratedHashEntryListResultsList =
  Array<ToleratedHashEntry>;
export const PaginatedToleratedHashEntryListResultsList = /*@__PURE__*/ S.Array(
  ToleratedHashEntry,
) as any as S.Schema<PaginatedToleratedHashEntryListResultsList>;

export interface PaginatedToleratedHashEntryList {
  count?: number;
  next?: string | null;
  previous?: string | null;
  results?: PaginatedToleratedHashEntryListResultsList;
}
export const PaginatedToleratedHashEntryList = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    count: S.optional(S.Number),
    next: S.optional(S.NullOr(S.String)),
    previous: S.optional(S.NullOr(S.String)),
    results: S.optional(PaginatedToleratedHashEntryListResultsList),
  }),
).annotate({
  identifier: "PaginatedToleratedHashEntryList",
}) as any as S.Schema<PaginatedToleratedHashEntryList>;

export type VisualReviewReposBaselinesRetrieveError = PosthogOpError;
/** Snapshots overview for a repo: every identifier with a current baseline (latest non-superseded master/main run per run_type), plus tolerate counts, active quarantine state, and a 30-day stability sparkline. Capped at 5000 entries — sets `truncated` and returns the most recently active when exceeded. Filtering / faceting / search are all done client-side; this endpoint takes no filter query params. */
export const visualReviewReposBaselinesRetrieve: API.OperationMethod<
  VisualReviewReposBaselinesRetrieveRequest,
  BaselineOverview,
  VisualReviewReposBaselinesRetrieveError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: VisualReviewReposBaselinesRetrieveRequest,
  output: BaselineOverview,
  errors: [],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type VisualReviewReposCreateError =
  | BadRequest
  | Forbidden
  | NotFound
  | PosthogOpError;
/** Create a new repo. */
export const visualReviewReposCreate: API.OperationMethod<
  VisualReviewReposCreateRequest,
  Repo,
  VisualReviewReposCreateError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: VisualReviewReposCreateRequest,
  output: Repo,
  errors: [BadRequest, Forbidden, NotFound],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type VisualReviewReposListError =
  | BadRequest
  | Forbidden
  | NotFound
  | PosthogOpError;
/** List all projects for the team. */
export const visualReviewReposList: API.OperationMethod<
  VisualReviewReposListRequest,
  PaginatedRepoList,
  VisualReviewReposListError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: VisualReviewReposListRequest,
  output: PaginatedRepoList,
  errors: [BadRequest, Forbidden, NotFound],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type VisualReviewReposPartialUpdateError =
  | BadRequest
  | Forbidden
  | NotFound
  | PosthogOpError;
/** Update a repo's settings. */
export const visualReviewReposPartialUpdate: API.OperationMethod<
  VisualReviewReposPartialUpdateRequest,
  Repo,
  VisualReviewReposPartialUpdateError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: VisualReviewReposPartialUpdateRequest,
  output: Repo,
  errors: [BadRequest, Forbidden, NotFound],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type VisualReviewReposQuarantineCreateError =
  | BadRequest
  | Forbidden
  | NotFound
  | PosthogOpError;
/** Quarantine a snapshot identifier for a specific run type. */
export const visualReviewReposQuarantineCreate: API.OperationMethod<
  VisualReviewReposQuarantineCreateRequest,
  QuarantinedIdentifierEntry,
  VisualReviewReposQuarantineCreateError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: VisualReviewReposQuarantineCreateRequest,
  output: QuarantinedIdentifierEntry,
  errors: [BadRequest, Forbidden, NotFound],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type VisualReviewReposQuarantineExpireCreateError =
  | BadRequest
  | Forbidden
  | NotFound
  | PosthogOpError;
/** Expire all active quarantine entries for an identifier. */
export const visualReviewReposQuarantineExpireCreate: API.OperationMethod<
  VisualReviewReposQuarantineExpireCreateRequest,
  VisualReviewReposQuarantineExpireCreateResponse,
  VisualReviewReposQuarantineExpireCreateError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: VisualReviewReposQuarantineExpireCreateRequest,
  output: VisualReviewReposQuarantineExpireCreateResponse,
  errors: [BadRequest, Forbidden, NotFound],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type VisualReviewReposQuarantineListError =
  | BadRequest
  | Forbidden
  | NotFound
  | PosthogOpError;
/** List quarantined identifiers. Without filter: active only. With identifier: full history. */
export const visualReviewReposQuarantineList: API.OperationMethod<
  VisualReviewReposQuarantineListRequest,
  PaginatedQuarantinedIdentifierEntryList,
  VisualReviewReposQuarantineListError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: VisualReviewReposQuarantineListRequest,
  output: PaginatedQuarantinedIdentifierEntryList,
  errors: [BadRequest, Forbidden, NotFound],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type VisualReviewReposRetrieveError =
  | Forbidden
  | NotFound
  | PosthogOpError;
/** Get a repo by ID. */
export const visualReviewReposRetrieve: API.OperationMethod<
  VisualReviewReposRetrieveRequest,
  Repo,
  VisualReviewReposRetrieveError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: VisualReviewReposRetrieveRequest,
  output: Repo,
  errors: [Forbidden, NotFound],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type VisualReviewReposRunsCountsRetrieveError = PosthogOpError;
/** Review state counts for runs in this repo. */
export const visualReviewReposRunsCountsRetrieve: API.OperationMethod<
  VisualReviewReposRunsCountsRetrieveRequest,
  ReviewStateCounts,
  VisualReviewReposRunsCountsRetrieveError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: VisualReviewReposRunsCountsRetrieveRequest,
  output: ReviewStateCounts,
  errors: [],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type VisualReviewReposRunsListError = PosthogOpError;
/** List runs in this repo, optionally filtered by review state and free-text search. */
export const visualReviewReposRunsList: API.OperationMethod<
  VisualReviewReposRunsListRequest,
  PaginatedRunList,
  VisualReviewReposRunsListError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: VisualReviewReposRunsListRequest,
  output: PaginatedRunList,
  errors: [],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type VisualReviewReposSnapshotsListError = PosthogOpError;
/** Deduped baseline timeline for a snapshot identity. Newest first. */
export const visualReviewReposSnapshotsList: API.OperationMethod<
  VisualReviewReposSnapshotsListRequest,
  PaginatedSnapshotHistoryEntryList,
  VisualReviewReposSnapshotsListError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: VisualReviewReposSnapshotsListRequest,
  output: PaginatedSnapshotHistoryEntryList,
  errors: [],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type VisualReviewReposThumbnailsRetrieveError = PosthogOpError;
/** Serve a snapshot thumbnail by identifier. Returns WebP with ETag caching. */
export const visualReviewReposThumbnailsRetrieve: API.OperationMethod<
  VisualReviewReposThumbnailsRetrieveRequest,
  VisualReviewReposThumbnailsRetrieveResponse,
  VisualReviewReposThumbnailsRetrieveError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: VisualReviewReposThumbnailsRetrieveRequest,
  output: VisualReviewReposThumbnailsRetrieveResponse,
  errors: [],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type VisualReviewRunsAddSnapshotsCreateError =
  | BadRequest
  | Forbidden
  | NotFound
  | PosthogOpError;
/** Add a batch of snapshots to a pending run (shard-based flow). */
export const visualReviewRunsAddSnapshotsCreate: API.OperationMethod<
  VisualReviewRunsAddSnapshotsCreateRequest,
  AddSnapshotsResult,
  VisualReviewRunsAddSnapshotsCreateError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: VisualReviewRunsAddSnapshotsCreateRequest,
  output: AddSnapshotsResult,
  errors: [BadRequest, Forbidden, NotFound],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type VisualReviewRunsApproveCreateError =
  | BadRequest
  | Forbidden
  | NotFound
  | PosthogOpError;
/** Mark snapshots reviewed (DB only). Records the per-snapshot "Accept change" decision. Does not commit the baseline or change the GitHub gate — call finalize to ship the run. */
export const visualReviewRunsApproveCreate: API.OperationMethod<
  VisualReviewRunsApproveCreateRequest,
  Run,
  VisualReviewRunsApproveCreateError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: VisualReviewRunsApproveCreateRequest,
  output: Run,
  errors: [BadRequest, Forbidden, NotFound],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type VisualReviewRunsCompleteCreateError =
  | Forbidden
  | NotFound
  | PosthogOpError;
/** Complete a run: detect removals, verify uploads, trigger diff processing. */
export const visualReviewRunsCompleteCreate: API.OperationMethod<
  VisualReviewRunsCompleteCreateRequest,
  Run,
  VisualReviewRunsCompleteCreateError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: VisualReviewRunsCompleteCreateRequest,
  output: Run,
  errors: [Forbidden, NotFound],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type VisualReviewRunsCountsRetrieveError =
  | Forbidden
  | NotFound
  | PosthogOpError;
/** Review state counts for the runs list. */
export const visualReviewRunsCountsRetrieve: API.OperationMethod<
  VisualReviewRunsCountsRetrieveRequest,
  ReviewStateCounts,
  VisualReviewRunsCountsRetrieveError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: VisualReviewRunsCountsRetrieveRequest,
  output: ReviewStateCounts,
  errors: [Forbidden, NotFound],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type VisualReviewRunsCreateError =
  | BadRequest
  | Forbidden
  | NotFound
  | PosthogOpError;
/** Create a new run from a CI manifest. */
export const visualReviewRunsCreate: API.OperationMethod<
  VisualReviewRunsCreateRequest,
  CreateRunResult,
  VisualReviewRunsCreateError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: VisualReviewRunsCreateRequest,
  output: CreateRunResult,
  errors: [BadRequest, Forbidden, NotFound],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type VisualReviewRunsFinalizeCreateError = PosthogOpError;
/** Finalize a fully-reviewed run: commit the approved baseline and green the gate. Commits exactly the snapshots approved in the DB (tolerated ones keep their baseline) and only succeeds once every changed/new snapshot is resolved. With approve_all=true, any still-pending changed/new snapshot is approved first. With commit_to_github=false the server returns the signed baseline YAML instead of committing it. */
export const visualReviewRunsFinalizeCreate: API.OperationMethod<
  VisualReviewRunsFinalizeCreateRequest,
  FinalizeResult,
  VisualReviewRunsFinalizeCreateError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: VisualReviewRunsFinalizeCreateRequest,
  output: FinalizeResult,
  errors: [],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type VisualReviewRunsListError =
  | BadRequest
  | Forbidden
  | NotFound
  | PosthogOpError;
/** List runs for the team, optionally filtered by review state, PR number, commit SHA, branch, or free-text search. */
export const visualReviewRunsList: API.OperationMethod<
  VisualReviewRunsListRequest,
  PaginatedRunList,
  VisualReviewRunsListError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: VisualReviewRunsListRequest,
  output: PaginatedRunList,
  errors: [BadRequest, Forbidden, NotFound],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type VisualReviewRunsRecomputeCreateError =
  | Forbidden
  | NotFound
  | PosthogOpError;
/** Re-evaluate quarantine and counts, update commit status, and optionally rerun the CI job. */
export const visualReviewRunsRecomputeCreate: API.OperationMethod<
  VisualReviewRunsRecomputeCreateRequest,
  RecomputeResult,
  VisualReviewRunsRecomputeCreateError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: VisualReviewRunsRecomputeCreateRequest,
  output: RecomputeResult,
  errors: [Forbidden, NotFound],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type VisualReviewRunsRetrieveError =
  | Forbidden
  | NotFound
  | PosthogOpError;
/** Get run status and summary. */
export const visualReviewRunsRetrieve: API.OperationMethod<
  VisualReviewRunsRetrieveRequest,
  Run,
  VisualReviewRunsRetrieveError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: VisualReviewRunsRetrieveRequest,
  output: Run,
  errors: [Forbidden, NotFound],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type VisualReviewRunsSnapshotHistoryListError =
  | BadRequest
  | Forbidden
  | NotFound
  | PosthogOpError;
/** Recent change history for a snapshot identifier across runs. */
export const visualReviewRunsSnapshotHistoryList: API.OperationMethod<
  VisualReviewRunsSnapshotHistoryListRequest,
  PaginatedSnapshotHistoryEntryList,
  VisualReviewRunsSnapshotHistoryListError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: VisualReviewRunsSnapshotHistoryListRequest,
  output: PaginatedSnapshotHistoryEntryList,
  errors: [BadRequest, Forbidden, NotFound],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type VisualReviewRunsSnapshotsListError =
  | BadRequest
  | Forbidden
  | NotFound
  | PosthogOpError;
/** Get a run's snapshots with diff results, excluding quarantined ones by default. */
export const visualReviewRunsSnapshotsList: API.OperationMethod<
  VisualReviewRunsSnapshotsListRequest,
  PaginatedSnapshotList,
  VisualReviewRunsSnapshotsListError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: VisualReviewRunsSnapshotsListRequest,
  output: PaginatedSnapshotList,
  errors: [BadRequest, Forbidden, NotFound],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type VisualReviewRunsTolerateCreateError =
  | BadRequest
  | Forbidden
  | NotFound
  | PosthogOpError;
/** Mark a changed snapshot as a known tolerated alternate. */
export const visualReviewRunsTolerateCreate: API.OperationMethod<
  VisualReviewRunsTolerateCreateRequest,
  Snapshot,
  VisualReviewRunsTolerateCreateError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: VisualReviewRunsTolerateCreateRequest,
  output: Snapshot,
  errors: [BadRequest, Forbidden, NotFound],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type VisualReviewRunsToleratedHashesListError =
  | BadRequest
  | Forbidden
  | NotFound
  | PosthogOpError;
/** List known tolerated hashes for a snapshot identifier. */
export const visualReviewRunsToleratedHashesList: API.OperationMethod<
  VisualReviewRunsToleratedHashesListRequest,
  PaginatedToleratedHashEntryList,
  VisualReviewRunsToleratedHashesListError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: VisualReviewRunsToleratedHashesListRequest,
  output: PaginatedToleratedHashEntryList,
  errors: [BadRequest, Forbidden, NotFound],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));
