import * as Schema from "effect/Schema";
import { API } from "../client.ts";
import * as T from "../traits.ts";

const __document =
  "mutation appCreateApp($appId: ID, $appInput: AppInput!) {\n  app(appId: $appId) {\n    createApp(appInput: $appInput) {\n      accessTokens {\n        createdAt\n        id\n        lastUsedAt\n        note\n        owner {\n          created\n          displayName\n          firstName\n          id\n          isExpoAdmin\n          lastDeletionAttemptTime\n        }\n        revokedAt\n        updatedAt\n        visibleTokenPrefix\n      }\n      appStoreConnectApp {\n        appStoreConnectApiKey {\n          createdAt\n          id\n          issuerIdentifier\n          keyIdentifier\n          keyP8\n          name\n          roles\n          updatedAt\n        }\n        ascAppIdentifier\n        createdAt\n        id\n        remoteAppStoreConnectApp {\n          appStoreIconUrl\n          ascAppIdentifier\n          bundleIdentifier\n          name\n        }\n        updatedAt\n        webhookEventTypes\n        webhookIdentifier\n      }\n      appStoreUrl\n      assetLimitPerUpdateGroup\n      buildProfiles\n      buildsReleaseChannels\n      convexProject {\n        convexProjectIdentifier\n        convexProjectName\n        convexProjectSlug\n        convexTeamConnection {\n          convexTeamIdentifier\n          createdAt\n          id\n          updatedAt\n        }\n        createdAt\n        id\n        updatedAt\n      }\n      description\n      devDomainName {\n        id\n        name\n      }\n      environmentVariableEnvironments\n      fullName\n      githubBuildTriggers {\n        autoSubmit\n        buildProfile\n        createdAt\n        environment\n        executionBehavior\n        id\n        isActive\n        lastRunAt\n        lastRunBuild {\n          activityTimestamp\n          appBuildVersion\n          appIdentifier\n          appVersion\n          buildMode\n          buildProfile\n          channel\n          cliVersion\n          completedAt\n          createdAt\n          customNodeVersion\n          customWorkflowName\n          developmentClient\n          distribution\n          enqueuedAt\n          estimatedWaitTimeLeftSeconds\n          expirationDate\n          gitCommitHash\n          gitCommitMessage\n          gitRef\n          githubRepositoryOwnerAndName\n          id\n          initialQueuePosition\n          iosEnterpriseProvisioning\n          isForIosSimulator\n          isGitWorkingTreeDirty\n          isWaived\n          logFiles\n          maxBuildTimeSeconds\n          maxRetryTimeMinutes\n          message\n          platform\n          priority\n          projectMetadataFileUrl\n          projectRootDirectory\n          provisioningStartedAt\n          queuePosition\n          reactNativeVersion\n          releaseChannel\n          requiredPackageManager\n          resolvedEnvironment\n          resourceClass\n          resourceClassDisplayName\n          runFromCI\n          runtimeVersion\n          sdkVersion\n          selectedImage\n          status\n          updatedAt\n          waiverType\n          workerStartedAt\n        }\n        lastRunErrorCode\n        lastRunErrorMessage\n        lastRunStatus\n        platform\n        sourcePattern\n        submitProfile\n        targetPattern\n        type\n        updatedAt\n      }\n      githubJobRunTriggers {\n        createdAt\n        id\n        isActive\n        jobType\n        lastRunAt\n        lastRunErrorCode\n        lastRunErrorMessage\n        lastRunStatus\n        sourcePattern\n        targetPattern\n        triggerType\n      }\n      githubRepository {\n        createdAt\n        githubAppInstallation {\n          id\n          installationIdentifier\n        }\n        githubRepositoryIdentifier\n        githubRepositoryUrl\n        id\n        lastDeletionAttemptTime\n        metadata {\n          defaultBranch\n          githubRepoDescription\n          githubRepoName\n          githubRepoOwnerName\n          githubRepoUrl\n          lastPushed\n          lastUpdated\n          private\n        }\n        nodeIdentifier\n      }\n      githubRepositorySettings {\n        baseDirectory\n        id\n      }\n      githubUrl\n      icon {\n        colorPalette\n        originalUrl\n        primaryColor\n        url\n      }\n      iconUrl\n      id\n      insights {\n        hasEventsFromExpoInsightsClientModule\n      }\n      internalDistributionBuildPrivacy\n      isDeleting\n      isDeprecated\n      isLikedByMe\n      lastDeletionAttemptTime\n      lastPublishedTime\n      latestActivity\n      latestReleaseId\n      likeCount\n      logRocketProject {\n        createdAt\n        id\n        logRocketOrgId\n        logRocketProjectSlug\n        updatedAt\n      }\n      name\n      observe {\n        totalEventCount\n      }\n      ownerAccount {\n        accessTokens {\n          createdAt\n          id\n          lastUsedAt\n          note\n          revokedAt\n          updatedAt\n          visibleTokenPrefix\n        }\n        appCount\n        appStoreConnectApiKeys {\n          createdAt\n          id\n          issuerIdentifier\n          keyIdentifier\n          keyP8\n          name\n          roles\n          updatedAt\n        }\n        appleDistributionCertificates {\n          certificateP12\n          certificatePassword\n          certificatePrivateSigningKey\n          createdAt\n          developerPortalIdentifier\n          id\n          serialNumber\n          updatedAt\n          validityNotAfter\n          validityNotBefore\n        }\n        applePushKeys {\n          createdAt\n          id\n          keyIdentifier\n          keyP8\n          updatedAt\n        }\n        availableBuilds\n        billing {\n          id\n        }\n        convexTeamConnections {\n          convexTeamIdentifier\n          createdAt\n          id\n          updatedAt\n        }\n        createdAt\n        displayName\n        environmentVariableEnvironments\n        githubAppInstallations {\n          id\n          installationIdentifier\n        }\n        googleServiceAccountKeys {\n          clientEmail\n          clientIdentifier\n          createdAt\n          id\n          keyJson\n          privateKeyIdentifier\n          projectIdentifier\n          updatedAt\n        }\n        hasBuilds\n        id\n        isCurrent\n        isDisabled\n        isFreeAppDevDomainTier\n        isSSOEnabled\n        lastDeletionAttemptTime\n        logRocketOrganization {\n          createdAt\n          id\n          orgName\n          orgSlug\n        }\n        memberStats {\n          allHave2FAEnabled\n          humanCount\n          ownerCount\n          robotCount\n          ssoUserCount\n          totalCount\n        }\n        name\n        offers {\n          features\n          id\n          price\n          quantity\n          stripeId\n          trialLength\n          type\n        }\n        onboardingStats {\n          firstBuildCompletedAt\n          firstProjectCreatedAt\n          firstSubmissionCompletedAt\n          firstUpdateCreatedAt\n          hasConfiguredUpdate\n          hasConfiguredWorkflow\n          hasTeamMembers\n        }\n        owner {\n          appCount\n          appetizeCode\n          bestContactEmail\n          created\n          displayName\n          email\n          emailVerified\n          firstName\n          fullName\n          githubUsername\n          hasPassword\n          hasPendingUserInvitations\n          id\n          industry\n          isExpoAdmin\n          isLegacy\n          isSecondFactorAuthenticationEnabled\n          isStaffModeEnabled\n          lastDeletionAttemptTime\n          lastName\n          location\n          newEmailPendingVerification\n          primaryAccountProfileImageUrl\n          profilePhoto\n          twitterUsername\n          username\n        }\n        ownerUserActor {\n          appCount\n          appetizeCode\n          bestContactEmail\n          created\n          displayName\n          firstName\n          fullName\n          githubUsername\n          id\n          industry\n          isExpoAdmin\n          isStaffModeEnabled\n          lastDeletionAttemptTime\n          lastName\n          location\n          primaryAccountProfileImageUrl\n          profilePhoto\n          twitterUsername\n          username\n        }\n        pendingSentryInstallation {\n          createdAt\n          id\n          installationId\n          orgSlug\n        }\n        profileImageUrl\n        pushSecurityEnabled\n        requireTwoFactor\n        requiresAccessTokenForPushSecurity\n        sentryInstallation {\n          createdAt\n          id\n          installationId\n          orgSlug\n        }\n        ssoAllowedAuthProviders\n        ssoConfiguration {\n          authProtocol\n          authProviderIdentifier\n          clientIdentifier\n          clientSecret\n          createdAt\n          id\n          issuer\n          updatedAt\n        }\n        subscription {\n          cancelAt\n          endedAt\n          id\n          isDowngrading\n          name\n          nextInvoice\n          nextInvoiceAmountDueCents\n          planId\n          price\n          recurringCents\n          status\n          trialEnd\n          willCancel\n        }\n        subscriptionChangesPending\n        unlimitedBuilds\n        updatedAt\n        userActorOwner {\n          appCount\n          appetizeCode\n          bestContactEmail\n          created\n          displayName\n          firstName\n          fullName\n          githubUsername\n          id\n          industry\n          isExpoAdmin\n          isStaffModeEnabled\n          lastDeletionAttemptTime\n          lastName\n          location\n          primaryAccountProfileImageUrl\n          profilePhoto\n          twitterUsername\n          username\n        }\n        userInvitations {\n          accountName\n          accountProfileImageUrl\n          accountProfilePhoto\n          accountRequiresTwoFactor\n          created\n          email\n          expires\n          id\n          isForOrganization\n          permissions\n          role\n        }\n        userSpecifiedAccountUsage\n        users {\n          id\n          permissions\n          role\n        }\n        vexoAccountConnection {\n          id\n        }\n        viewerUserPermission {\n          id\n          permissions\n          role\n        }\n        willAutoRenewBuilds\n      }\n      packageName\n      packageUsername\n      playStoreUrl\n      privacy\n      privacySetting\n      published\n      pushNotifications {\n        id\n        insights {\n          id\n        }\n      }\n      pushSecurityEnabled\n      releaseChannels\n      requiresAccessTokenForPushSecurity\n      resourceClassExperiment\n      scopeKey\n      sdkVersion\n      sentryProject {\n        createdAt\n        id\n        sentryInstallationId\n        sentryProjectId\n        sentryProjectSlug\n        updatedAt\n      }\n      slug\n      suggestedDevDomainName\n      trendScore\n      updated\n      username\n      users {\n        accessTokens {\n          createdAt\n          id\n          lastUsedAt\n          note\n          revokedAt\n          updatedAt\n          visibleTokenPrefix\n        }\n        accounts {\n          appCount\n          availableBuilds\n          createdAt\n          displayName\n          environmentVariableEnvironments\n          hasBuilds\n          id\n          isCurrent\n          isDisabled\n          isFreeAppDevDomainTier\n          isSSOEnabled\n          lastDeletionAttemptTime\n          name\n          profileImageUrl\n          pushSecurityEnabled\n          requireTwoFactor\n          requiresAccessTokenForPushSecurity\n          ssoAllowedAuthProviders\n          subscriptionChangesPending\n          unlimitedBuilds\n          updatedAt\n          userSpecifiedAccountUsage\n          willAutoRenewBuilds\n        }\n        appCount\n        appetizeCode\n        bestContactEmail\n        created\n        discordUser {\n          discordIdentifier\n          id\n        }\n        displayName\n        email\n        emailVerified\n        experiments {\n          createdAt\n          enabled\n          experiment\n          id\n          updatedAt\n        }\n        firstName\n        fullName\n        githubUser {\n          githubUserIdentifier\n          id\n        }\n        githubUsername\n        hasPassword\n        hasPendingUserInvitations\n        id\n        industry\n        isExpoAdmin\n        isLegacy\n        isSecondFactorAuthenticationEnabled\n        isStaffModeEnabled\n        lastDeletionAttemptTime\n        lastName\n        location\n        newEmailPendingVerification\n        oAuthIdentities {\n          email\n          id\n          login\n          provider\n        }\n        pendingUserInvitations {\n          accountName\n          accountProfileImageUrl\n          accountProfilePhoto\n          accountRequiresTwoFactor\n          created\n          email\n          expires\n          id\n          isForOrganization\n          permissions\n          role\n        }\n        pinnedDashboardViews {\n          view\n        }\n        preferences {\n          selectedAccountName\n        }\n        primaryAccount {\n          appCount\n          availableBuilds\n          createdAt\n          displayName\n          environmentVariableEnvironments\n          hasBuilds\n          id\n          isCurrent\n          isDisabled\n          isFreeAppDevDomainTier\n          isSSOEnabled\n          lastDeletionAttemptTime\n          name\n          profileImageUrl\n          pushSecurityEnabled\n          requireTwoFactor\n          requiresAccessTokenForPushSecurity\n          ssoAllowedAuthProviders\n          subscriptionChangesPending\n          unlimitedBuilds\n          updatedAt\n          userSpecifiedAccountUsage\n          willAutoRenewBuilds\n        }\n        primaryAccountProfileImageUrl\n        profilePhoto\n        secondFactorDevices {\n          createdAt\n          id\n          isCertified\n          isPrimary\n          method\n          name\n          smsPhoneNumber\n          updatedAt\n        }\n        twitterUsername\n        username\n      }\n      vexoApp {\n        domain\n        iconUrl\n        id\n        name\n        owner\n        slug\n        vexoIdentifier\n      }\n      workerCustomDomain {\n        alias {\n          aliasName\n          createdAt\n          deploymentDomain\n          devDomainName\n          id\n          subdomain\n          updatedAt\n          url\n        }\n        createdAt\n        dcvDelegationRecord {\n          dnsContent\n          dnsName\n          dnsType\n          isConfigured\n        }\n        devDomainName\n        dnsRecord {\n          dnsContent\n          dnsName\n          dnsType\n          isConfigured\n        }\n        hostname\n        id\n        setup {\n          sslErrors\n          sslStatus\n          status\n          verificationErrors\n          verificationStatus\n        }\n        updatedAt\n        verificationRecord {\n          dnsContent\n          dnsName\n          dnsType\n          isConfigured\n        }\n      }\n    }\n  }\n}";

// Input Schema (GraphQL variables)
export const AppCreateAppInput = Schema.Struct({
  appId: Schema.optional(Schema.NullOr(Schema.String)),
  appInput: Schema.Struct({
    accountId: Schema.String,
    appInfo: Schema.optional(
      Schema.NullOr(
        Schema.Struct({
          displayName: Schema.optional(Schema.NullOr(Schema.String)),
        }),
      ),
    ),
    projectName: Schema.String,
  }),
}).pipe(
  T.Http({ method: "POST", path: "/graphql" }),
  T.GraphQLOp({
    query: __document,
    operationName: "appCreateApp",
    type: "mutation",
  }),
);
export type AppCreateAppInput = typeof AppCreateAppInput.Type;

// Output Schema (GraphQL selection set)
export const AppCreateAppOutput = Schema.Struct({
  accessTokens: Schema.Array(
    Schema.NullOr(
      Schema.Struct({
        createdAt: Schema.String,
        id: Schema.String,
        lastUsedAt: Schema.NullOr(Schema.String),
        note: Schema.NullOr(Schema.String),
        owner: Schema.Struct({
          created: Schema.String,
          displayName: Schema.String,
          firstName: Schema.NullOr(Schema.String),
          id: Schema.String,
          isExpoAdmin: Schema.Boolean,
          lastDeletionAttemptTime: Schema.NullOr(Schema.String),
        }),
        revokedAt: Schema.NullOr(Schema.String),
        updatedAt: Schema.String,
        visibleTokenPrefix: Schema.String,
      }),
    ),
  ),
  appStoreConnectApp: Schema.NullOr(
    Schema.Struct({
      appStoreConnectApiKey: Schema.Struct({
        createdAt: Schema.String,
        id: Schema.String,
        issuerIdentifier: Schema.String,
        keyIdentifier: Schema.String,
        keyP8: Schema.String,
        name: Schema.NullOr(Schema.String),
        roles: Schema.NullOr(
          Schema.Array(
            Schema.Literals([
              "ACCESS_TO_REPORTS",
              "ACCOUNT_HOLDER",
              "ADMIN",
              "APP_MANAGER",
              "CLOUD_MANAGED_APP_DISTRIBUTION",
              "CLOUD_MANAGED_DEVELOPER_ID",
              "CREATE_APPS",
              "CUSTOMER_SUPPORT",
              "DEVELOPER",
              "FINANCE",
              "IMAGE_MANAGER",
              "MARKETING",
              "READ_ONLY",
              "SALES",
              "TECHNICAL",
              "UNKNOWN",
            ]),
          ),
        ),
        updatedAt: Schema.String,
      }),
      ascAppIdentifier: Schema.String,
      createdAt: Schema.String,
      id: Schema.String,
      remoteAppStoreConnectApp: Schema.Struct({
        appStoreIconUrl: Schema.NullOr(Schema.String),
        ascAppIdentifier: Schema.String,
        bundleIdentifier: Schema.String,
        name: Schema.NullOr(Schema.String),
      }),
      updatedAt: Schema.String,
      webhookEventTypes: Schema.Array(Schema.String),
      webhookIdentifier: Schema.String,
    }),
  ),
  appStoreUrl: Schema.NullOr(Schema.String),
  assetLimitPerUpdateGroup: Schema.Number,
  buildProfiles: Schema.Array(Schema.String),
  buildsReleaseChannels: Schema.Array(Schema.String),
  convexProject: Schema.NullOr(
    Schema.Struct({
      convexProjectIdentifier: Schema.String,
      convexProjectName: Schema.String,
      convexProjectSlug: Schema.String,
      convexTeamConnection: Schema.Struct({
        convexTeamIdentifier: Schema.String,
        createdAt: Schema.String,
        id: Schema.String,
        updatedAt: Schema.String,
      }),
      createdAt: Schema.String,
      id: Schema.String,
      updatedAt: Schema.String,
    }),
  ),
  description: Schema.String,
  devDomainName: Schema.NullOr(
    Schema.Struct({
      id: Schema.String,
      name: Schema.Unknown,
    }),
  ),
  environmentVariableEnvironments: Schema.Array(Schema.Unknown),
  fullName: Schema.String,
  githubBuildTriggers: Schema.Array(
    Schema.Struct({
      autoSubmit: Schema.Boolean,
      buildProfile: Schema.String,
      createdAt: Schema.String,
      environment: Schema.NullOr(Schema.Unknown),
      executionBehavior: Schema.Literals(["ALWAYS", "BASE_DIRECTORY_CHANGED"]),
      id: Schema.String,
      isActive: Schema.Boolean,
      lastRunAt: Schema.NullOr(Schema.String),
      lastRunBuild: Schema.NullOr(
        Schema.Struct({
          activityTimestamp: Schema.String,
          appBuildVersion: Schema.NullOr(Schema.String),
          appIdentifier: Schema.NullOr(Schema.String),
          appVersion: Schema.NullOr(Schema.String),
          buildMode: Schema.NullOr(
            Schema.Literals(["BUILD", "CUSTOM", "LOCAL", "REPACK", "RESIGN"]),
          ),
          buildProfile: Schema.NullOr(Schema.String),
          channel: Schema.NullOr(Schema.String),
          cliVersion: Schema.NullOr(Schema.String),
          completedAt: Schema.NullOr(Schema.String),
          createdAt: Schema.String,
          customNodeVersion: Schema.NullOr(Schema.String),
          customWorkflowName: Schema.NullOr(Schema.String),
          developmentClient: Schema.NullOr(Schema.Boolean),
          distribution: Schema.NullOr(
            Schema.Literals(["INTERNAL", "SIMULATOR", "STORE"]),
          ),
          enqueuedAt: Schema.NullOr(Schema.String),
          estimatedWaitTimeLeftSeconds: Schema.NullOr(Schema.Number),
          expirationDate: Schema.NullOr(Schema.String),
          gitCommitHash: Schema.NullOr(Schema.String),
          gitCommitMessage: Schema.NullOr(Schema.String),
          gitRef: Schema.NullOr(Schema.String),
          githubRepositoryOwnerAndName: Schema.NullOr(Schema.String),
          id: Schema.String,
          initialQueuePosition: Schema.NullOr(Schema.Number),
          iosEnterpriseProvisioning: Schema.NullOr(
            Schema.Literals(["ADHOC", "UNIVERSAL"]),
          ),
          isForIosSimulator: Schema.Boolean,
          isGitWorkingTreeDirty: Schema.NullOr(Schema.Boolean),
          isWaived: Schema.Boolean,
          logFiles: Schema.Array(Schema.String),
          maxBuildTimeSeconds: Schema.Number,
          maxRetryTimeMinutes: Schema.NullOr(Schema.Number),
          message: Schema.NullOr(Schema.String),
          platform: Schema.Literals(["ANDROID", "IOS"]),
          priority: Schema.Literals(["HIGH", "NORMAL", "NORMAL_PLUS"]),
          projectMetadataFileUrl: Schema.NullOr(Schema.String),
          projectRootDirectory: Schema.NullOr(Schema.String),
          provisioningStartedAt: Schema.NullOr(Schema.String),
          queuePosition: Schema.NullOr(Schema.Number),
          reactNativeVersion: Schema.NullOr(Schema.String),
          releaseChannel: Schema.NullOr(Schema.String),
          requiredPackageManager: Schema.NullOr(Schema.String),
          resolvedEnvironment: Schema.NullOr(Schema.Unknown),
          resourceClass: Schema.Literals([
            "ANDROID_DEFAULT",
            "ANDROID_LARGE",
            "ANDROID_MEDIUM",
            "IOS_DEFAULT",
            "IOS_INTEL_LARGE",
            "IOS_INTEL_MEDIUM",
            "IOS_LARGE",
            "IOS_M1_LARGE",
            "IOS_M1_MEDIUM",
            "IOS_MEDIUM",
            "IOS_M_LARGE",
            "IOS_M_MEDIUM",
            "LEGACY",
            "LINUX_LARGE",
            "LINUX_MEDIUM",
          ]),
          resourceClassDisplayName: Schema.String,
          runFromCI: Schema.NullOr(Schema.Boolean),
          runtimeVersion: Schema.NullOr(Schema.String),
          sdkVersion: Schema.NullOr(Schema.String),
          selectedImage: Schema.NullOr(Schema.String),
          status: Schema.Literals([
            "CANCELED",
            "ERRORED",
            "FINISHED",
            "IN_PROGRESS",
            "IN_QUEUE",
            "NEW",
            "PENDING_CANCEL",
          ]),
          updatedAt: Schema.String,
          waiverType: Schema.NullOr(
            Schema.Literals(["FAST_FAILED_BUILD", "SYSTEM_ERROR"]),
          ),
          workerStartedAt: Schema.NullOr(Schema.String),
        }),
      ),
      lastRunErrorCode: Schema.NullOr(Schema.String),
      lastRunErrorMessage: Schema.NullOr(Schema.String),
      lastRunStatus: Schema.NullOr(Schema.Literals(["ERRORED", "SUCCESS"])),
      platform: Schema.Literals(["ANDROID", "IOS"]),
      sourcePattern: Schema.String,
      submitProfile: Schema.NullOr(Schema.String),
      targetPattern: Schema.NullOr(Schema.String),
      type: Schema.Literals([
        "PULL_REQUEST_UPDATED",
        "PUSH_TO_BRANCH",
        "TAG_UPDATED",
      ]),
      updatedAt: Schema.String,
    }),
  ),
  githubJobRunTriggers: Schema.Array(
    Schema.Struct({
      createdAt: Schema.String,
      id: Schema.String,
      isActive: Schema.Boolean,
      jobType: Schema.NullOr(Schema.Literals(["PUBLISH_UPDATE"])),
      lastRunAt: Schema.NullOr(Schema.String),
      lastRunErrorCode: Schema.NullOr(Schema.String),
      lastRunErrorMessage: Schema.NullOr(Schema.String),
      lastRunStatus: Schema.NullOr(Schema.Literals(["ERRORED", "SUCCESS"])),
      sourcePattern: Schema.String,
      targetPattern: Schema.NullOr(Schema.String),
      triggerType: Schema.Literals(["PULL_REQUEST_UPDATED", "PUSH_TO_BRANCH"]),
    }),
  ),
  githubRepository: Schema.NullOr(
    Schema.Struct({
      createdAt: Schema.String,
      githubAppInstallation: Schema.Struct({
        id: Schema.String,
        installationIdentifier: Schema.Number,
      }),
      githubRepositoryIdentifier: Schema.Number,
      githubRepositoryUrl: Schema.NullOr(Schema.String),
      id: Schema.String,
      lastDeletionAttemptTime: Schema.NullOr(Schema.String),
      metadata: Schema.Struct({
        defaultBranch: Schema.NullOr(Schema.String),
        githubRepoDescription: Schema.NullOr(Schema.String),
        githubRepoName: Schema.String,
        githubRepoOwnerName: Schema.String,
        githubRepoUrl: Schema.String,
        lastPushed: Schema.String,
        lastUpdated: Schema.String,
        private: Schema.Boolean,
      }),
      nodeIdentifier: Schema.String,
    }),
  ),
  githubRepositorySettings: Schema.NullOr(
    Schema.Struct({
      baseDirectory: Schema.String,
      id: Schema.String,
    }),
  ),
  githubUrl: Schema.NullOr(Schema.String),
  icon: Schema.NullOr(
    Schema.Struct({
      colorPalette: Schema.NullOr(Schema.Unknown),
      originalUrl: Schema.String,
      primaryColor: Schema.NullOr(Schema.String),
      url: Schema.String,
    }),
  ),
  iconUrl: Schema.NullOr(Schema.String),
  id: Schema.String,
  insights: Schema.Struct({
    hasEventsFromExpoInsightsClientModule: Schema.Boolean,
  }),
  internalDistributionBuildPrivacy: Schema.Literals(["PRIVATE", "PUBLIC"]),
  isDeleting: Schema.Boolean,
  isDeprecated: Schema.Boolean,
  isLikedByMe: Schema.Boolean,
  lastDeletionAttemptTime: Schema.NullOr(Schema.String),
  lastPublishedTime: Schema.String,
  latestActivity: Schema.String,
  latestReleaseId: Schema.String,
  likeCount: Schema.Number,
  logRocketProject: Schema.NullOr(
    Schema.Struct({
      createdAt: Schema.String,
      id: Schema.String,
      logRocketOrgId: Schema.String,
      logRocketProjectSlug: Schema.String,
      updatedAt: Schema.String,
    }),
  ),
  name: Schema.String,
  observe: Schema.Struct({
    totalEventCount: Schema.Number,
  }),
  ownerAccount: Schema.Struct({
    accessTokens: Schema.Array(
      Schema.NullOr(
        Schema.Struct({
          createdAt: Schema.String,
          id: Schema.String,
          lastUsedAt: Schema.NullOr(Schema.String),
          note: Schema.NullOr(Schema.String),
          revokedAt: Schema.NullOr(Schema.String),
          updatedAt: Schema.String,
          visibleTokenPrefix: Schema.String,
        }),
      ),
    ),
    appCount: Schema.Number,
    appStoreConnectApiKeys: Schema.Array(
      Schema.Struct({
        createdAt: Schema.String,
        id: Schema.String,
        issuerIdentifier: Schema.String,
        keyIdentifier: Schema.String,
        keyP8: Schema.String,
        name: Schema.NullOr(Schema.String),
        roles: Schema.NullOr(
          Schema.Array(
            Schema.Literals([
              "ACCESS_TO_REPORTS",
              "ACCOUNT_HOLDER",
              "ADMIN",
              "APP_MANAGER",
              "CLOUD_MANAGED_APP_DISTRIBUTION",
              "CLOUD_MANAGED_DEVELOPER_ID",
              "CREATE_APPS",
              "CUSTOMER_SUPPORT",
              "DEVELOPER",
              "FINANCE",
              "IMAGE_MANAGER",
              "MARKETING",
              "READ_ONLY",
              "SALES",
              "TECHNICAL",
              "UNKNOWN",
            ]),
          ),
        ),
        updatedAt: Schema.String,
      }),
    ),
    appleDistributionCertificates: Schema.Array(
      Schema.Struct({
        certificateP12: Schema.NullOr(Schema.String),
        certificatePassword: Schema.NullOr(Schema.String),
        certificatePrivateSigningKey: Schema.NullOr(Schema.String),
        createdAt: Schema.String,
        developerPortalIdentifier: Schema.NullOr(Schema.String),
        id: Schema.String,
        serialNumber: Schema.String,
        updatedAt: Schema.String,
        validityNotAfter: Schema.String,
        validityNotBefore: Schema.String,
      }),
    ),
    applePushKeys: Schema.Array(
      Schema.Struct({
        createdAt: Schema.String,
        id: Schema.String,
        keyIdentifier: Schema.String,
        keyP8: Schema.String,
        updatedAt: Schema.String,
      }),
    ),
    availableBuilds: Schema.NullOr(Schema.Number),
    billing: Schema.NullOr(
      Schema.Struct({
        id: Schema.String,
      }),
    ),
    convexTeamConnections: Schema.Array(
      Schema.Struct({
        convexTeamIdentifier: Schema.String,
        createdAt: Schema.String,
        id: Schema.String,
        updatedAt: Schema.String,
      }),
    ),
    createdAt: Schema.String,
    displayName: Schema.NullOr(Schema.String),
    environmentVariableEnvironments: Schema.Array(Schema.Unknown),
    githubAppInstallations: Schema.Array(
      Schema.Struct({
        id: Schema.String,
        installationIdentifier: Schema.Number,
      }),
    ),
    googleServiceAccountKeys: Schema.Array(
      Schema.Struct({
        clientEmail: Schema.String,
        clientIdentifier: Schema.String,
        createdAt: Schema.String,
        id: Schema.String,
        keyJson: Schema.String,
        privateKeyIdentifier: Schema.String,
        projectIdentifier: Schema.String,
        updatedAt: Schema.String,
      }),
    ),
    hasBuilds: Schema.Boolean,
    id: Schema.String,
    isCurrent: Schema.Boolean,
    isDisabled: Schema.Boolean,
    isFreeAppDevDomainTier: Schema.Boolean,
    isSSOEnabled: Schema.Boolean,
    lastDeletionAttemptTime: Schema.NullOr(Schema.String),
    logRocketOrganization: Schema.NullOr(
      Schema.Struct({
        createdAt: Schema.String,
        id: Schema.String,
        orgName: Schema.String,
        orgSlug: Schema.String,
      }),
    ),
    memberStats: Schema.Struct({
      allHave2FAEnabled: Schema.Boolean,
      humanCount: Schema.Number,
      ownerCount: Schema.Number,
      robotCount: Schema.Number,
      ssoUserCount: Schema.Number,
      totalCount: Schema.Number,
    }),
    name: Schema.String,
    offers: Schema.NullOr(
      Schema.Array(
        Schema.Struct({
          features: Schema.NullOr(
            Schema.Array(
              Schema.NullOr(
                Schema.Literals(["BUILDS", "OPEN_SOURCE", "SUPPORT", "TEAMS"]),
              ),
            ),
          ),
          id: Schema.String,
          price: Schema.Number,
          quantity: Schema.NullOr(Schema.Number),
          stripeId: Schema.String,
          trialLength: Schema.NullOr(Schema.Number),
          type: Schema.Literals(["ADDON", "PREPAID", "SUBSCRIPTION"]),
        }),
      ),
    ),
    onboardingStats: Schema.Struct({
      firstBuildCompletedAt: Schema.NullOr(Schema.String),
      firstProjectCreatedAt: Schema.NullOr(Schema.String),
      firstSubmissionCompletedAt: Schema.NullOr(Schema.String),
      firstUpdateCreatedAt: Schema.NullOr(Schema.String),
      hasConfiguredUpdate: Schema.Boolean,
      hasConfiguredWorkflow: Schema.Boolean,
      hasTeamMembers: Schema.Boolean,
    }),
    owner: Schema.NullOr(
      Schema.Struct({
        appCount: Schema.Number,
        appetizeCode: Schema.NullOr(Schema.String),
        bestContactEmail: Schema.NullOr(Schema.String),
        created: Schema.String,
        displayName: Schema.String,
        email: Schema.String,
        emailVerified: Schema.Boolean,
        firstName: Schema.NullOr(Schema.String),
        fullName: Schema.NullOr(Schema.String),
        githubUsername: Schema.NullOr(Schema.String),
        hasPassword: Schema.Boolean,
        hasPendingUserInvitations: Schema.Boolean,
        id: Schema.String,
        industry: Schema.NullOr(Schema.String),
        isExpoAdmin: Schema.Boolean,
        isLegacy: Schema.Boolean,
        isSecondFactorAuthenticationEnabled: Schema.Boolean,
        isStaffModeEnabled: Schema.Boolean,
        lastDeletionAttemptTime: Schema.NullOr(Schema.String),
        lastName: Schema.NullOr(Schema.String),
        location: Schema.NullOr(Schema.String),
        newEmailPendingVerification: Schema.NullOr(Schema.String),
        primaryAccountProfileImageUrl: Schema.NullOr(Schema.String),
        profilePhoto: Schema.String,
        twitterUsername: Schema.NullOr(Schema.String),
        username: Schema.String,
      }),
    ),
    ownerUserActor: Schema.NullOr(
      Schema.Struct({
        appCount: Schema.Number,
        appetizeCode: Schema.NullOr(Schema.String),
        bestContactEmail: Schema.NullOr(Schema.String),
        created: Schema.String,
        displayName: Schema.String,
        firstName: Schema.NullOr(Schema.String),
        fullName: Schema.NullOr(Schema.String),
        githubUsername: Schema.NullOr(Schema.String),
        id: Schema.String,
        industry: Schema.NullOr(Schema.String),
        isExpoAdmin: Schema.Boolean,
        isStaffModeEnabled: Schema.Boolean,
        lastDeletionAttemptTime: Schema.NullOr(Schema.String),
        lastName: Schema.NullOr(Schema.String),
        location: Schema.NullOr(Schema.String),
        primaryAccountProfileImageUrl: Schema.NullOr(Schema.String),
        profilePhoto: Schema.String,
        twitterUsername: Schema.NullOr(Schema.String),
        username: Schema.String,
      }),
    ),
    pendingSentryInstallation: Schema.NullOr(
      Schema.Struct({
        createdAt: Schema.String,
        id: Schema.String,
        installationId: Schema.String,
        orgSlug: Schema.String,
      }),
    ),
    profileImageUrl: Schema.String,
    pushSecurityEnabled: Schema.Boolean,
    requireTwoFactor: Schema.Boolean,
    requiresAccessTokenForPushSecurity: Schema.Boolean,
    sentryInstallation: Schema.NullOr(
      Schema.Struct({
        createdAt: Schema.String,
        id: Schema.String,
        installationId: Schema.String,
        orgSlug: Schema.String,
      }),
    ),
    ssoAllowedAuthProviders: Schema.Array(
      Schema.Literals([
        "AMAZON_FEDERATE",
        "GENERIC",
        "GOOGLE_WS",
        "MS_ENTRA_ID",
        "OKTA",
        "ONE_LOGIN",
        "STUB_IDP",
      ]),
    ),
    ssoConfiguration: Schema.NullOr(
      Schema.Struct({
        authProtocol: Schema.Literals(["OIDC"]),
        authProviderIdentifier: Schema.Literals([
          "AMAZON_FEDERATE",
          "GENERIC",
          "GOOGLE_WS",
          "MS_ENTRA_ID",
          "OKTA",
          "ONE_LOGIN",
          "STUB_IDP",
        ]),
        clientIdentifier: Schema.String,
        clientSecret: Schema.String,
        createdAt: Schema.String,
        id: Schema.String,
        issuer: Schema.String,
        updatedAt: Schema.String,
      }),
    ),
    subscription: Schema.NullOr(
      Schema.Struct({
        cancelAt: Schema.NullOr(Schema.String),
        endedAt: Schema.NullOr(Schema.String),
        id: Schema.String,
        isDowngrading: Schema.NullOr(Schema.Boolean),
        name: Schema.NullOr(Schema.String),
        nextInvoice: Schema.NullOr(Schema.String),
        nextInvoiceAmountDueCents: Schema.NullOr(Schema.Number),
        planId: Schema.NullOr(Schema.String),
        price: Schema.Number,
        recurringCents: Schema.NullOr(Schema.Number),
        status: Schema.NullOr(Schema.String),
        trialEnd: Schema.NullOr(Schema.String),
        willCancel: Schema.NullOr(Schema.Boolean),
      }),
    ),
    subscriptionChangesPending: Schema.NullOr(Schema.Boolean),
    unlimitedBuilds: Schema.Boolean,
    updatedAt: Schema.String,
    userActorOwner: Schema.NullOr(
      Schema.Struct({
        appCount: Schema.Number,
        appetizeCode: Schema.NullOr(Schema.String),
        bestContactEmail: Schema.NullOr(Schema.String),
        created: Schema.String,
        displayName: Schema.String,
        firstName: Schema.NullOr(Schema.String),
        fullName: Schema.NullOr(Schema.String),
        githubUsername: Schema.NullOr(Schema.String),
        id: Schema.String,
        industry: Schema.NullOr(Schema.String),
        isExpoAdmin: Schema.Boolean,
        isStaffModeEnabled: Schema.Boolean,
        lastDeletionAttemptTime: Schema.NullOr(Schema.String),
        lastName: Schema.NullOr(Schema.String),
        location: Schema.NullOr(Schema.String),
        primaryAccountProfileImageUrl: Schema.NullOr(Schema.String),
        profilePhoto: Schema.String,
        twitterUsername: Schema.NullOr(Schema.String),
        username: Schema.String,
      }),
    ),
    userInvitations: Schema.Array(
      Schema.Struct({
        accountName: Schema.String,
        accountProfileImageUrl: Schema.String,
        accountProfilePhoto: Schema.NullOr(Schema.String),
        accountRequiresTwoFactor: Schema.Boolean,
        created: Schema.String,
        email: Schema.String,
        expires: Schema.String,
        id: Schema.String,
        isForOrganization: Schema.Boolean,
        permissions: Schema.Array(
          Schema.Literals(["ADMIN", "OWN", "PUBLISH", "VIEW"]),
        ),
        role: Schema.Literals([
          "ADMIN",
          "CUSTOM",
          "DEVELOPER",
          "HAS_ADMIN",
          "NOT_ADMIN",
          "OWNER",
          "VIEW_ONLY",
        ]),
      }),
    ),
    userSpecifiedAccountUsage: Schema.NullOr(
      Schema.Literals(["COMPANY", "PERSONAL"]),
    ),
    users: Schema.Array(
      Schema.Struct({
        id: Schema.String,
        permissions: Schema.Array(
          Schema.Literals(["ADMIN", "OWN", "PUBLISH", "VIEW"]),
        ),
        role: Schema.Literals([
          "ADMIN",
          "CUSTOM",
          "DEVELOPER",
          "HAS_ADMIN",
          "NOT_ADMIN",
          "OWNER",
          "VIEW_ONLY",
        ]),
      }),
    ),
    vexoAccountConnection: Schema.NullOr(
      Schema.Struct({
        id: Schema.String,
      }),
    ),
    viewerUserPermission: Schema.Struct({
      id: Schema.String,
      permissions: Schema.Array(
        Schema.Literals(["ADMIN", "OWN", "PUBLISH", "VIEW"]),
      ),
      role: Schema.Literals([
        "ADMIN",
        "CUSTOM",
        "DEVELOPER",
        "HAS_ADMIN",
        "NOT_ADMIN",
        "OWNER",
        "VIEW_ONLY",
      ]),
    }),
    willAutoRenewBuilds: Schema.NullOr(Schema.Boolean),
  }),
  packageName: Schema.String,
  packageUsername: Schema.String,
  playStoreUrl: Schema.NullOr(Schema.String),
  privacy: Schema.String,
  privacySetting: Schema.Literals(["HIDDEN", "PUBLIC", "UNLISTED"]),
  published: Schema.Boolean,
  pushNotifications: Schema.Struct({
    id: Schema.String,
    insights: Schema.Struct({
      id: Schema.String,
    }),
  }),
  pushSecurityEnabled: Schema.Boolean,
  releaseChannels: Schema.Array(Schema.String),
  requiresAccessTokenForPushSecurity: Schema.Boolean,
  resourceClassExperiment: Schema.NullOr(Schema.Literals(["C3D", "N2"])),
  scopeKey: Schema.String,
  sdkVersion: Schema.String,
  sentryProject: Schema.NullOr(
    Schema.Struct({
      createdAt: Schema.String,
      id: Schema.String,
      sentryInstallationId: Schema.String,
      sentryProjectId: Schema.String,
      sentryProjectSlug: Schema.String,
      updatedAt: Schema.String,
    }),
  ),
  slug: Schema.String,
  suggestedDevDomainName: Schema.String,
  trendScore: Schema.Number,
  updated: Schema.String,
  username: Schema.String,
  users: Schema.NullOr(
    Schema.Array(
      Schema.NullOr(
        Schema.Struct({
          accessTokens: Schema.Array(
            Schema.Struct({
              createdAt: Schema.String,
              id: Schema.String,
              lastUsedAt: Schema.NullOr(Schema.String),
              note: Schema.NullOr(Schema.String),
              revokedAt: Schema.NullOr(Schema.String),
              updatedAt: Schema.String,
              visibleTokenPrefix: Schema.String,
            }),
          ),
          accounts: Schema.Array(
            Schema.Struct({
              appCount: Schema.Number,
              availableBuilds: Schema.NullOr(Schema.Number),
              createdAt: Schema.String,
              displayName: Schema.NullOr(Schema.String),
              environmentVariableEnvironments: Schema.Array(Schema.Unknown),
              hasBuilds: Schema.Boolean,
              id: Schema.String,
              isCurrent: Schema.Boolean,
              isDisabled: Schema.Boolean,
              isFreeAppDevDomainTier: Schema.Boolean,
              isSSOEnabled: Schema.Boolean,
              lastDeletionAttemptTime: Schema.NullOr(Schema.String),
              name: Schema.String,
              profileImageUrl: Schema.String,
              pushSecurityEnabled: Schema.Boolean,
              requireTwoFactor: Schema.Boolean,
              requiresAccessTokenForPushSecurity: Schema.Boolean,
              ssoAllowedAuthProviders: Schema.Array(
                Schema.Literals([
                  "AMAZON_FEDERATE",
                  "GENERIC",
                  "GOOGLE_WS",
                  "MS_ENTRA_ID",
                  "OKTA",
                  "ONE_LOGIN",
                  "STUB_IDP",
                ]),
              ),
              subscriptionChangesPending: Schema.NullOr(Schema.Boolean),
              unlimitedBuilds: Schema.Boolean,
              updatedAt: Schema.String,
              userSpecifiedAccountUsage: Schema.NullOr(
                Schema.Literals(["COMPANY", "PERSONAL"]),
              ),
              willAutoRenewBuilds: Schema.NullOr(Schema.Boolean),
            }),
          ),
          appCount: Schema.Number,
          appetizeCode: Schema.NullOr(Schema.String),
          bestContactEmail: Schema.NullOr(Schema.String),
          created: Schema.String,
          discordUser: Schema.NullOr(
            Schema.Struct({
              discordIdentifier: Schema.String,
              id: Schema.String,
            }),
          ),
          displayName: Schema.String,
          email: Schema.String,
          emailVerified: Schema.Boolean,
          experiments: Schema.Array(
            Schema.Struct({
              createdAt: Schema.String,
              enabled: Schema.Boolean,
              experiment: Schema.Literals(["ORBIT"]),
              id: Schema.String,
              updatedAt: Schema.String,
            }),
          ),
          firstName: Schema.NullOr(Schema.String),
          fullName: Schema.NullOr(Schema.String),
          githubUser: Schema.NullOr(
            Schema.Struct({
              githubUserIdentifier: Schema.String,
              id: Schema.String,
            }),
          ),
          githubUsername: Schema.NullOr(Schema.String),
          hasPassword: Schema.Boolean,
          hasPendingUserInvitations: Schema.Boolean,
          id: Schema.String,
          industry: Schema.NullOr(Schema.String),
          isExpoAdmin: Schema.Boolean,
          isLegacy: Schema.Boolean,
          isSecondFactorAuthenticationEnabled: Schema.Boolean,
          isStaffModeEnabled: Schema.Boolean,
          lastDeletionAttemptTime: Schema.NullOr(Schema.String),
          lastName: Schema.NullOr(Schema.String),
          location: Schema.NullOr(Schema.String),
          newEmailPendingVerification: Schema.NullOr(Schema.String),
          oAuthIdentities: Schema.Array(
            Schema.Struct({
              email: Schema.String,
              id: Schema.String,
              login: Schema.NullOr(Schema.String),
              provider: Schema.Literals(["apple", "github", "google"]),
            }),
          ),
          pendingUserInvitations: Schema.Array(
            Schema.Struct({
              accountName: Schema.String,
              accountProfileImageUrl: Schema.String,
              accountProfilePhoto: Schema.NullOr(Schema.String),
              accountRequiresTwoFactor: Schema.Boolean,
              created: Schema.String,
              email: Schema.String,
              expires: Schema.String,
              id: Schema.String,
              isForOrganization: Schema.Boolean,
              permissions: Schema.Array(
                Schema.Literals(["ADMIN", "OWN", "PUBLISH", "VIEW"]),
              ),
              role: Schema.Literals([
                "ADMIN",
                "CUSTOM",
                "DEVELOPER",
                "HAS_ADMIN",
                "NOT_ADMIN",
                "OWNER",
                "VIEW_ONLY",
              ]),
            }),
          ),
          pinnedDashboardViews: Schema.Array(
            Schema.Struct({
              view: Schema.Literals(["ACTIVITY", "OVERVIEW"]),
            }),
          ),
          preferences: Schema.Struct({
            selectedAccountName: Schema.NullOr(Schema.String),
          }),
          primaryAccount: Schema.Struct({
            appCount: Schema.Number,
            availableBuilds: Schema.NullOr(Schema.Number),
            createdAt: Schema.String,
            displayName: Schema.NullOr(Schema.String),
            environmentVariableEnvironments: Schema.Array(Schema.Unknown),
            hasBuilds: Schema.Boolean,
            id: Schema.String,
            isCurrent: Schema.Boolean,
            isDisabled: Schema.Boolean,
            isFreeAppDevDomainTier: Schema.Boolean,
            isSSOEnabled: Schema.Boolean,
            lastDeletionAttemptTime: Schema.NullOr(Schema.String),
            name: Schema.String,
            profileImageUrl: Schema.String,
            pushSecurityEnabled: Schema.Boolean,
            requireTwoFactor: Schema.Boolean,
            requiresAccessTokenForPushSecurity: Schema.Boolean,
            ssoAllowedAuthProviders: Schema.Array(
              Schema.Literals([
                "AMAZON_FEDERATE",
                "GENERIC",
                "GOOGLE_WS",
                "MS_ENTRA_ID",
                "OKTA",
                "ONE_LOGIN",
                "STUB_IDP",
              ]),
            ),
            subscriptionChangesPending: Schema.NullOr(Schema.Boolean),
            unlimitedBuilds: Schema.Boolean,
            updatedAt: Schema.String,
            userSpecifiedAccountUsage: Schema.NullOr(
              Schema.Literals(["COMPANY", "PERSONAL"]),
            ),
            willAutoRenewBuilds: Schema.NullOr(Schema.Boolean),
          }),
          primaryAccountProfileImageUrl: Schema.NullOr(Schema.String),
          profilePhoto: Schema.String,
          secondFactorDevices: Schema.Array(
            Schema.Struct({
              createdAt: Schema.String,
              id: Schema.String,
              isCertified: Schema.Boolean,
              isPrimary: Schema.Boolean,
              method: Schema.Literals(["AUTHENTICATOR", "SMS"]),
              name: Schema.String,
              smsPhoneNumber: Schema.NullOr(Schema.String),
              updatedAt: Schema.String,
            }),
          ),
          twitterUsername: Schema.NullOr(Schema.String),
          username: Schema.String,
        }),
      ),
    ),
  ),
  vexoApp: Schema.NullOr(
    Schema.Struct({
      domain: Schema.NullOr(Schema.String),
      iconUrl: Schema.NullOr(Schema.String),
      id: Schema.String,
      name: Schema.String,
      owner: Schema.String,
      slug: Schema.String,
      vexoIdentifier: Schema.String,
    }),
  ),
  workerCustomDomain: Schema.NullOr(
    Schema.Struct({
      alias: Schema.Struct({
        aliasName: Schema.NullOr(Schema.Unknown),
        createdAt: Schema.String,
        deploymentDomain: Schema.String,
        devDomainName: Schema.Unknown,
        id: Schema.String,
        subdomain: Schema.String,
        updatedAt: Schema.String,
        url: Schema.String,
      }),
      createdAt: Schema.String,
      dcvDelegationRecord: Schema.NullOr(
        Schema.Struct({
          dnsContent: Schema.String,
          dnsName: Schema.String,
          dnsType: Schema.Literals(["A", "CNAME", "TXT"]),
          isConfigured: Schema.Boolean,
        }),
      ),
      devDomainName: Schema.Unknown,
      dnsRecord: Schema.Struct({
        dnsContent: Schema.String,
        dnsName: Schema.String,
        dnsType: Schema.Literals(["A", "CNAME", "TXT"]),
        isConfigured: Schema.Boolean,
      }),
      hostname: Schema.String,
      id: Schema.String,
      setup: Schema.NullOr(
        Schema.Struct({
          sslErrors: Schema.NullOr(Schema.Array(Schema.String)),
          sslStatus: Schema.NullOr(
            Schema.Literals(["ACTIVE", "ERROR", "PENDING", "TIMED_OUT"]),
          ),
          status: Schema.Literals(["ACTIVE", "ERROR", "PENDING", "TIMED_OUT"]),
          verificationErrors: Schema.NullOr(Schema.Array(Schema.String)),
          verificationStatus: Schema.NullOr(
            Schema.Literals(["ACTIVE", "ERROR", "PENDING", "TIMED_OUT"]),
          ),
        }),
      ),
      updatedAt: Schema.String,
      verificationRecord: Schema.NullOr(
        Schema.Struct({
          dnsContent: Schema.String,
          dnsName: Schema.String,
          dnsType: Schema.Literals(["A", "CNAME", "TXT"]),
          isConfigured: Schema.Boolean,
        }),
      ),
    }),
  ),
}).pipe(T.ResponsePath("app.createApp"));
export type AppCreateAppOutput = typeof AppCreateAppOutput.Type;

export const appCreateApp = API.make(() => ({
  inputSchema: AppCreateAppInput,
  outputSchema: AppCreateAppOutput,
}));
