import * as Schema from "effect/Schema";
import { API } from "../client.ts";
import * as T from "../traits.ts";

const __document =
  "query appleDeviceRegistrationRequestById($id: ID!) {\n  appleDeviceRegistrationRequest {\n    byId(id: $id) {\n      account {\n        accessTokens {\n          createdAt\n          id\n          lastUsedAt\n          note\n          revokedAt\n          updatedAt\n          visibleTokenPrefix\n        }\n        appCount\n        appStoreConnectApiKeys {\n          createdAt\n          id\n          issuerIdentifier\n          keyIdentifier\n          keyP8\n          name\n          roles\n          updatedAt\n        }\n        appleDistributionCertificates {\n          certificateP12\n          certificatePassword\n          certificatePrivateSigningKey\n          createdAt\n          developerPortalIdentifier\n          id\n          serialNumber\n          updatedAt\n          validityNotAfter\n          validityNotBefore\n        }\n        applePushKeys {\n          createdAt\n          id\n          keyIdentifier\n          keyP8\n          updatedAt\n        }\n        availableBuilds\n        billing {\n          id\n        }\n        convexTeamConnections {\n          convexTeamIdentifier\n          convexTeamName\n          convexTeamSlug\n          createdAt\n          hasBeenClaimed\n          id\n          invitedAt\n          invitedEmail\n          updatedAt\n        }\n        createdAt\n        displayName\n        environmentVariableEnvironments\n        githubAppInstallations {\n          id\n          installationIdentifier\n        }\n        googleServiceAccountKeys {\n          clientEmail\n          clientIdentifier\n          createdAt\n          id\n          keyJson\n          privateKeyIdentifier\n          projectIdentifier\n          updatedAt\n        }\n        hasBuilds\n        id\n        isCurrent\n        isDisabled\n        isFreeAppDevDomainTier\n        isSSOEnabled\n        lastDeletionAttemptTime\n        logRocketOrganization {\n          createdAt\n          id\n          orgName\n          orgSlug\n        }\n        memberStats {\n          allHave2FAEnabled\n          humanCount\n          ownerCount\n          robotCount\n          ssoUserCount\n          totalCount\n        }\n        name\n        offers {\n          features\n          id\n          price\n          quantity\n          stripeId\n          trialLength\n          type\n        }\n        onboardingStats {\n          firstBuildCompletedAt\n          firstProjectCreatedAt\n          firstSubmissionCompletedAt\n          firstUpdateCreatedAt\n          hasConfiguredUpdate\n          hasConfiguredWorkflow\n          hasTeamMembers\n        }\n        owner {\n          appCount\n          appetizeCode\n          bestContactEmail\n          created\n          displayName\n          email\n          emailVerified\n          firstName\n          fullName\n          githubUsername\n          hasPassword\n          hasPendingUserInvitations\n          id\n          industry\n          isExpoAdmin\n          isLegacy\n          isSecondFactorAuthenticationEnabled\n          isStaffModeEnabled\n          lastDeletionAttemptTime\n          lastName\n          location\n          newEmailPendingVerification\n          primaryAccountProfileImageUrl\n          profilePhoto\n          twitterUsername\n          username\n        }\n        ownerUserActor {\n          appCount\n          appetizeCode\n          bestContactEmail\n          created\n          displayName\n          firstName\n          fullName\n          githubUsername\n          id\n          industry\n          isExpoAdmin\n          isStaffModeEnabled\n          lastDeletionAttemptTime\n          lastName\n          location\n          primaryAccountProfileImageUrl\n          profilePhoto\n          twitterUsername\n          username\n        }\n        pendingSentryInstallation {\n          createdAt\n          id\n          installationId\n          orgSlug\n        }\n        posthogOrganizationConnection {\n          createdAt\n          id\n          posthogOrganizationIdentifier\n          posthogOrganizationName\n          posthogRegion\n          updatedAt\n        }\n        profileImageUrl\n        pushSecurityEnabled\n        requireTwoFactor\n        requiresAccessTokenForPushSecurity\n        sentryInstallation {\n          createdAt\n          id\n          installationId\n          orgSlug\n        }\n        ssoAllowedAuthProviders\n        ssoConfiguration {\n          authProtocol\n          authProviderIdentifier\n          clientIdentifier\n          clientSecret\n          createdAt\n          id\n          issuer\n          updatedAt\n        }\n        subscription {\n          cancelAt\n          endedAt\n          id\n          includedAgentCreditsInCents\n          isDowngrading\n          name\n          nextInvoice\n          nextInvoiceAmountDueCents\n          planId\n          price\n          recurringCents\n          status\n          trialEnd\n          willCancel\n        }\n        subscriptionChangesPending\n        unlimitedBuilds\n        updatedAt\n        userActorOwner {\n          appCount\n          appetizeCode\n          bestContactEmail\n          created\n          displayName\n          firstName\n          fullName\n          githubUsername\n          id\n          industry\n          isExpoAdmin\n          isStaffModeEnabled\n          lastDeletionAttemptTime\n          lastName\n          location\n          primaryAccountProfileImageUrl\n          profilePhoto\n          twitterUsername\n          username\n        }\n        userInvitations {\n          accountName\n          accountProfileImageUrl\n          accountProfilePhoto\n          accountRequiresTwoFactor\n          created\n          email\n          expires\n          id\n          isForOrganization\n          permissions\n          role\n        }\n        userSpecifiedAccountUsage\n        users {\n          id\n          permissions\n          role\n        }\n        vexoAccountConnection {\n          id\n        }\n        viewerUserPermission {\n          id\n          permissions\n          role\n        }\n        willAutoRenewBuilds\n      }\n      appleTeam {\n        account {\n          appCount\n          availableBuilds\n          createdAt\n          displayName\n          environmentVariableEnvironments\n          hasBuilds\n          id\n          isCurrent\n          isDisabled\n          isFreeAppDevDomainTier\n          isSSOEnabled\n          lastDeletionAttemptTime\n          name\n          profileImageUrl\n          pushSecurityEnabled\n          requireTwoFactor\n          requiresAccessTokenForPushSecurity\n          ssoAllowedAuthProviders\n          subscriptionChangesPending\n          unlimitedBuilds\n          updatedAt\n          userSpecifiedAccountUsage\n          willAutoRenewBuilds\n        }\n        appleDistributionCertificates {\n          certificateP12\n          certificatePassword\n          certificatePrivateSigningKey\n          createdAt\n          developerPortalIdentifier\n          id\n          serialNumber\n          updatedAt\n          validityNotAfter\n          validityNotBefore\n        }\n        applePushKeys {\n          createdAt\n          id\n          keyIdentifier\n          keyP8\n          updatedAt\n        }\n        appleTeamIdentifier\n        appleTeamName\n        appleTeamType\n        id\n        lastDeletionAttemptTime\n      }\n      closedAt\n      id\n      resolvedAppleDevice {\n        account {\n          appCount\n          availableBuilds\n          createdAt\n          displayName\n          environmentVariableEnvironments\n          hasBuilds\n          id\n          isCurrent\n          isDisabled\n          isFreeAppDevDomainTier\n          isSSOEnabled\n          lastDeletionAttemptTime\n          name\n          profileImageUrl\n          pushSecurityEnabled\n          requireTwoFactor\n          requiresAccessTokenForPushSecurity\n          ssoAllowedAuthProviders\n          subscriptionChangesPending\n          unlimitedBuilds\n          updatedAt\n          userSpecifiedAccountUsage\n          willAutoRenewBuilds\n        }\n        appleTeam {\n          appleTeamIdentifier\n          appleTeamName\n          appleTeamType\n          id\n          lastDeletionAttemptTime\n        }\n        createdAt\n        deviceClass\n        enabled\n        id\n        identifier\n        model\n        name\n        softwareVersion\n      }\n      workflowJob {\n        allDeviceTestCaseResults {\n          createdAt\n          duration\n          errorMessage\n          id\n          name\n          path\n          properties\n          retryCount\n          status\n          tags\n          updatedAt\n        }\n        approvals {\n          createdAt\n          decision\n          id\n          updatedAt\n        }\n        createdAt\n        deviceTestCaseResultAttempts {\n          createdAt\n          duration\n          errorMessage\n          id\n          name\n          path\n          properties\n          retryCount\n          status\n          tags\n          updatedAt\n        }\n        deviceTestCaseResults {\n          createdAt\n          duration\n          errorMessage\n          id\n          name\n          path\n          properties\n          retryCount\n          status\n          tags\n          updatedAt\n        }\n        environment\n        errors {\n          message\n          title\n        }\n        id\n        key\n        name\n        outputs\n        requiredJobKeys\n        status\n        turtleBuild {\n          activityTimestamp\n          appBuildVersion\n          appIdentifier\n          appVersion\n          buildMode\n          buildProfile\n          channel\n          cliVersion\n          completedAt\n          createdAt\n          customNodeVersion\n          customWorkflowName\n          developmentClient\n          distribution\n          enqueuedAt\n          estimatedWaitTimeLeftSeconds\n          expirationDate\n          gitCommitHash\n          gitCommitMessage\n          gitRef\n          githubRepositoryOwnerAndName\n          id\n          initialQueuePosition\n          iosEnterpriseProvisioning\n          isForIosSimulator\n          isGitWorkingTreeDirty\n          isWaived\n          logFiles\n          maxBuildTimeSeconds\n          maxRetryTimeMinutes\n          message\n          platform\n          priority\n          projectMetadataFileUrl\n          projectRootDirectory\n          provisioningStartedAt\n          queuePosition\n          reactNativeVersion\n          releaseChannel\n          requiredPackageManager\n          resolvedEnvironment\n          resolvedImage\n          resourceClass\n          resourceClassDisplayName\n          runFromCI\n          runtimeVersion\n          sdkVersion\n          selectedImage\n          status\n          updatedAt\n          waiverType\n          workerStartedAt\n        }\n        turtleJobRun {\n          createdAt\n          displayName\n          endedAt\n          enqueuedAt\n          expiresAt\n          gitCommitHash\n          gitCommitMessage\n          gitRef\n          id\n          isWaived\n          logFileUrls\n          maxRunTimeSeconds\n          name\n          priority\n          resourceClassDisplayName\n          startedAt\n          status\n          updateGroups\n        }\n        turtleSubmission {\n          activityTimestamp\n          archiveUrl\n          canRetry\n          completedAt\n          createdAt\n          id\n          logFiles\n          logsUrl\n          maxRetryTimeMinutes\n          platform\n          priority\n          status\n          updatedAt\n        }\n        type\n        updatedAt\n        workflowRun {\n          activityTimestamp\n          createdAt\n          durationSeconds\n          finalizedAt\n          gitCommitHash\n          gitCommitMessage\n          id\n          inputs\n          name\n          pullRequestNumber\n          requestedGitRef\n          sourceExpiresAt\n          status\n          triggerEventType\n          triggeringLabelName\n          triggeringSchedule\n          updatedAt\n        }\n      }\n    }\n  }\n}";

// Input Schema (GraphQL variables)
export const AppleDeviceRegistrationRequestByIdInput = Schema.Struct({
  id: Schema.String,
}).pipe(
  T.Http({ method: "POST", path: "/graphql" }),
  T.GraphQLOp({
    query: __document,
    operationName: "appleDeviceRegistrationRequestById",
    type: "query",
  }),
);
export type AppleDeviceRegistrationRequestByIdInput =
  typeof AppleDeviceRegistrationRequestByIdInput.Type;

// Output Schema (GraphQL selection set)
export const AppleDeviceRegistrationRequestByIdOutput = Schema.Struct({
  account: Schema.Struct({
    accessTokens: Schema.Array(
      Schema.NullOr(
        Schema.Struct({
          createdAt: Schema.String,
          id: Schema.String,
          lastUsedAt: Schema.NullOr(Schema.String),
          note: Schema.NullOr(Schema.String),
          revokedAt: Schema.NullOr(Schema.String),
          updatedAt: Schema.String,
          visibleTokenPrefix: Schema.String,
        }),
      ),
    ),
    appCount: Schema.Number,
    appStoreConnectApiKeys: Schema.Array(
      Schema.Struct({
        createdAt: Schema.String,
        id: Schema.String,
        issuerIdentifier: Schema.String,
        keyIdentifier: Schema.String,
        keyP8: Schema.String,
        name: Schema.NullOr(Schema.String),
        roles: Schema.NullOr(
          Schema.Array(
            Schema.Literals([
              "ACCESS_TO_REPORTS",
              "ACCOUNT_HOLDER",
              "ADMIN",
              "APP_MANAGER",
              "CLOUD_MANAGED_APP_DISTRIBUTION",
              "CLOUD_MANAGED_DEVELOPER_ID",
              "CREATE_APPS",
              "CUSTOMER_SUPPORT",
              "DEVELOPER",
              "FINANCE",
              "IMAGE_MANAGER",
              "MARKETING",
              "READ_ONLY",
              "SALES",
              "TECHNICAL",
              "UNKNOWN",
            ]),
          ),
        ),
        updatedAt: Schema.String,
      }),
    ),
    appleDistributionCertificates: Schema.Array(
      Schema.Struct({
        certificateP12: Schema.NullOr(Schema.String),
        certificatePassword: Schema.NullOr(Schema.String),
        certificatePrivateSigningKey: Schema.NullOr(Schema.String),
        createdAt: Schema.String,
        developerPortalIdentifier: Schema.NullOr(Schema.String),
        id: Schema.String,
        serialNumber: Schema.String,
        updatedAt: Schema.String,
        validityNotAfter: Schema.String,
        validityNotBefore: Schema.String,
      }),
    ),
    applePushKeys: Schema.Array(
      Schema.Struct({
        createdAt: Schema.String,
        id: Schema.String,
        keyIdentifier: Schema.String,
        keyP8: Schema.String,
        updatedAt: Schema.String,
      }),
    ),
    availableBuilds: Schema.NullOr(Schema.Number),
    billing: Schema.NullOr(
      Schema.Struct({
        id: Schema.String,
      }),
    ),
    convexTeamConnections: Schema.Array(
      Schema.Struct({
        convexTeamIdentifier: Schema.String,
        convexTeamName: Schema.String,
        convexTeamSlug: Schema.String,
        createdAt: Schema.String,
        hasBeenClaimed: Schema.Boolean,
        id: Schema.String,
        invitedAt: Schema.NullOr(Schema.String),
        invitedEmail: Schema.NullOr(Schema.String),
        updatedAt: Schema.String,
      }),
    ),
    createdAt: Schema.String,
    displayName: Schema.NullOr(Schema.String),
    environmentVariableEnvironments: Schema.Array(Schema.Unknown),
    githubAppInstallations: Schema.Array(
      Schema.Struct({
        id: Schema.String,
        installationIdentifier: Schema.Number,
      }),
    ),
    googleServiceAccountKeys: Schema.Array(
      Schema.Struct({
        clientEmail: Schema.String,
        clientIdentifier: Schema.String,
        createdAt: Schema.String,
        id: Schema.String,
        keyJson: Schema.String,
        privateKeyIdentifier: Schema.String,
        projectIdentifier: Schema.String,
        updatedAt: Schema.String,
      }),
    ),
    hasBuilds: Schema.Boolean,
    id: Schema.String,
    isCurrent: Schema.Boolean,
    isDisabled: Schema.Boolean,
    isFreeAppDevDomainTier: Schema.Boolean,
    isSSOEnabled: Schema.Boolean,
    lastDeletionAttemptTime: Schema.NullOr(Schema.String),
    logRocketOrganization: Schema.NullOr(
      Schema.Struct({
        createdAt: Schema.String,
        id: Schema.String,
        orgName: Schema.String,
        orgSlug: Schema.String,
      }),
    ),
    memberStats: Schema.Struct({
      allHave2FAEnabled: Schema.Boolean,
      humanCount: Schema.Number,
      ownerCount: Schema.Number,
      robotCount: Schema.Number,
      ssoUserCount: Schema.Number,
      totalCount: Schema.Number,
    }),
    name: Schema.String,
    offers: Schema.NullOr(
      Schema.Array(
        Schema.Struct({
          features: Schema.NullOr(
            Schema.Array(
              Schema.NullOr(
                Schema.Literals(["BUILDS", "OPEN_SOURCE", "SUPPORT", "TEAMS"]),
              ),
            ),
          ),
          id: Schema.String,
          price: Schema.Number,
          quantity: Schema.NullOr(Schema.Number),
          stripeId: Schema.String,
          trialLength: Schema.NullOr(Schema.Number),
          type: Schema.Literals(["ADDON", "PREPAID", "SUBSCRIPTION"]),
        }),
      ),
    ),
    onboardingStats: Schema.Struct({
      firstBuildCompletedAt: Schema.NullOr(Schema.String),
      firstProjectCreatedAt: Schema.NullOr(Schema.String),
      firstSubmissionCompletedAt: Schema.NullOr(Schema.String),
      firstUpdateCreatedAt: Schema.NullOr(Schema.String),
      hasConfiguredUpdate: Schema.Boolean,
      hasConfiguredWorkflow: Schema.Boolean,
      hasTeamMembers: Schema.Boolean,
    }),
    owner: Schema.NullOr(
      Schema.Struct({
        appCount: Schema.Number,
        appetizeCode: Schema.NullOr(Schema.String),
        bestContactEmail: Schema.NullOr(Schema.String),
        created: Schema.String,
        displayName: Schema.String,
        email: Schema.String,
        emailVerified: Schema.Boolean,
        firstName: Schema.NullOr(Schema.String),
        fullName: Schema.NullOr(Schema.String),
        githubUsername: Schema.NullOr(Schema.String),
        hasPassword: Schema.Boolean,
        hasPendingUserInvitations: Schema.Boolean,
        id: Schema.String,
        industry: Schema.NullOr(Schema.String),
        isExpoAdmin: Schema.Boolean,
        isLegacy: Schema.Boolean,
        isSecondFactorAuthenticationEnabled: Schema.Boolean,
        isStaffModeEnabled: Schema.Boolean,
        lastDeletionAttemptTime: Schema.NullOr(Schema.String),
        lastName: Schema.NullOr(Schema.String),
        location: Schema.NullOr(Schema.String),
        newEmailPendingVerification: Schema.NullOr(Schema.String),
        primaryAccountProfileImageUrl: Schema.String,
        profilePhoto: Schema.String,
        twitterUsername: Schema.NullOr(Schema.String),
        username: Schema.String,
      }),
    ),
    ownerUserActor: Schema.NullOr(
      Schema.Struct({
        appCount: Schema.Number,
        appetizeCode: Schema.NullOr(Schema.String),
        bestContactEmail: Schema.NullOr(Schema.String),
        created: Schema.String,
        displayName: Schema.String,
        firstName: Schema.NullOr(Schema.String),
        fullName: Schema.NullOr(Schema.String),
        githubUsername: Schema.NullOr(Schema.String),
        id: Schema.String,
        industry: Schema.NullOr(Schema.String),
        isExpoAdmin: Schema.Boolean,
        isStaffModeEnabled: Schema.Boolean,
        lastDeletionAttemptTime: Schema.NullOr(Schema.String),
        lastName: Schema.NullOr(Schema.String),
        location: Schema.NullOr(Schema.String),
        primaryAccountProfileImageUrl: Schema.String,
        profilePhoto: Schema.String,
        twitterUsername: Schema.NullOr(Schema.String),
        username: Schema.String,
      }),
    ),
    pendingSentryInstallation: Schema.NullOr(
      Schema.Struct({
        createdAt: Schema.String,
        id: Schema.String,
        installationId: Schema.String,
        orgSlug: Schema.String,
      }),
    ),
    posthogOrganizationConnection: Schema.NullOr(
      Schema.Struct({
        createdAt: Schema.String,
        id: Schema.String,
        posthogOrganizationIdentifier: Schema.String,
        posthogOrganizationName: Schema.String,
        posthogRegion: Schema.Literals(["EU", "US"]),
        updatedAt: Schema.String,
      }),
    ),
    profileImageUrl: Schema.String,
    pushSecurityEnabled: Schema.Boolean,
    requireTwoFactor: Schema.Boolean,
    requiresAccessTokenForPushSecurity: Schema.Boolean,
    sentryInstallation: Schema.NullOr(
      Schema.Struct({
        createdAt: Schema.String,
        id: Schema.String,
        installationId: Schema.String,
        orgSlug: Schema.String,
      }),
    ),
    ssoAllowedAuthProviders: Schema.Array(
      Schema.Literals([
        "AMAZON_FEDERATE",
        "GENERIC",
        "GOOGLE_WS",
        "MS_ENTRA_ID",
        "OKTA",
        "ONE_LOGIN",
        "STUB_IDP",
      ]),
    ),
    ssoConfiguration: Schema.NullOr(
      Schema.Struct({
        authProtocol: Schema.Literals(["OIDC"]),
        authProviderIdentifier: Schema.Literals([
          "AMAZON_FEDERATE",
          "GENERIC",
          "GOOGLE_WS",
          "MS_ENTRA_ID",
          "OKTA",
          "ONE_LOGIN",
          "STUB_IDP",
        ]),
        clientIdentifier: Schema.String,
        clientSecret: Schema.String,
        createdAt: Schema.String,
        id: Schema.String,
        issuer: Schema.String,
        updatedAt: Schema.String,
      }),
    ),
    subscription: Schema.NullOr(
      Schema.Struct({
        cancelAt: Schema.NullOr(Schema.String),
        endedAt: Schema.NullOr(Schema.String),
        id: Schema.String,
        includedAgentCreditsInCents: Schema.Number,
        isDowngrading: Schema.NullOr(Schema.Boolean),
        name: Schema.NullOr(Schema.String),
        nextInvoice: Schema.NullOr(Schema.String),
        nextInvoiceAmountDueCents: Schema.NullOr(Schema.Number),
        planId: Schema.NullOr(Schema.String),
        price: Schema.Number,
        recurringCents: Schema.NullOr(Schema.Number),
        status: Schema.NullOr(Schema.String),
        trialEnd: Schema.NullOr(Schema.String),
        willCancel: Schema.NullOr(Schema.Boolean),
      }),
    ),
    subscriptionChangesPending: Schema.NullOr(Schema.Boolean),
    unlimitedBuilds: Schema.Boolean,
    updatedAt: Schema.String,
    userActorOwner: Schema.NullOr(
      Schema.Struct({
        appCount: Schema.Number,
        appetizeCode: Schema.NullOr(Schema.String),
        bestContactEmail: Schema.NullOr(Schema.String),
        created: Schema.String,
        displayName: Schema.String,
        firstName: Schema.NullOr(Schema.String),
        fullName: Schema.NullOr(Schema.String),
        githubUsername: Schema.NullOr(Schema.String),
        id: Schema.String,
        industry: Schema.NullOr(Schema.String),
        isExpoAdmin: Schema.Boolean,
        isStaffModeEnabled: Schema.Boolean,
        lastDeletionAttemptTime: Schema.NullOr(Schema.String),
        lastName: Schema.NullOr(Schema.String),
        location: Schema.NullOr(Schema.String),
        primaryAccountProfileImageUrl: Schema.String,
        profilePhoto: Schema.String,
        twitterUsername: Schema.NullOr(Schema.String),
        username: Schema.String,
      }),
    ),
    userInvitations: Schema.Array(
      Schema.Struct({
        accountName: Schema.String,
        accountProfileImageUrl: Schema.String,
        accountProfilePhoto: Schema.NullOr(Schema.String),
        accountRequiresTwoFactor: Schema.Boolean,
        created: Schema.String,
        email: Schema.String,
        expires: Schema.String,
        id: Schema.String,
        isForOrganization: Schema.Boolean,
        permissions: Schema.Array(
          Schema.Literals(["ADMIN", "OWN", "PUBLISH", "VIEW"]),
        ),
        role: Schema.Literals([
          "ADMIN",
          "CUSTOM",
          "DEVELOPER",
          "HAS_ADMIN",
          "NOT_ADMIN",
          "OWNER",
          "VIEW_ONLY",
        ]),
      }),
    ),
    userSpecifiedAccountUsage: Schema.NullOr(
      Schema.Literals(["COMPANY", "PERSONAL"]),
    ),
    users: Schema.Array(
      Schema.Struct({
        id: Schema.String,
        permissions: Schema.Array(
          Schema.Literals(["ADMIN", "OWN", "PUBLISH", "VIEW"]),
        ),
        role: Schema.Literals([
          "ADMIN",
          "CUSTOM",
          "DEVELOPER",
          "HAS_ADMIN",
          "NOT_ADMIN",
          "OWNER",
          "VIEW_ONLY",
        ]),
      }),
    ),
    vexoAccountConnection: Schema.NullOr(
      Schema.Struct({
        id: Schema.String,
      }),
    ),
    viewerUserPermission: Schema.Struct({
      id: Schema.String,
      permissions: Schema.Array(
        Schema.Literals(["ADMIN", "OWN", "PUBLISH", "VIEW"]),
      ),
      role: Schema.Literals([
        "ADMIN",
        "CUSTOM",
        "DEVELOPER",
        "HAS_ADMIN",
        "NOT_ADMIN",
        "OWNER",
        "VIEW_ONLY",
      ]),
    }),
    willAutoRenewBuilds: Schema.NullOr(Schema.Boolean),
  }),
  appleTeam: Schema.Struct({
    account: Schema.Struct({
      appCount: Schema.Number,
      availableBuilds: Schema.NullOr(Schema.Number),
      createdAt: Schema.String,
      displayName: Schema.NullOr(Schema.String),
      environmentVariableEnvironments: Schema.Array(Schema.Unknown),
      hasBuilds: Schema.Boolean,
      id: Schema.String,
      isCurrent: Schema.Boolean,
      isDisabled: Schema.Boolean,
      isFreeAppDevDomainTier: Schema.Boolean,
      isSSOEnabled: Schema.Boolean,
      lastDeletionAttemptTime: Schema.NullOr(Schema.String),
      name: Schema.String,
      profileImageUrl: Schema.String,
      pushSecurityEnabled: Schema.Boolean,
      requireTwoFactor: Schema.Boolean,
      requiresAccessTokenForPushSecurity: Schema.Boolean,
      ssoAllowedAuthProviders: Schema.Array(
        Schema.Literals([
          "AMAZON_FEDERATE",
          "GENERIC",
          "GOOGLE_WS",
          "MS_ENTRA_ID",
          "OKTA",
          "ONE_LOGIN",
          "STUB_IDP",
        ]),
      ),
      subscriptionChangesPending: Schema.NullOr(Schema.Boolean),
      unlimitedBuilds: Schema.Boolean,
      updatedAt: Schema.String,
      userSpecifiedAccountUsage: Schema.NullOr(
        Schema.Literals(["COMPANY", "PERSONAL"]),
      ),
      willAutoRenewBuilds: Schema.NullOr(Schema.Boolean),
    }),
    appleDistributionCertificates: Schema.Array(
      Schema.Struct({
        certificateP12: Schema.NullOr(Schema.String),
        certificatePassword: Schema.NullOr(Schema.String),
        certificatePrivateSigningKey: Schema.NullOr(Schema.String),
        createdAt: Schema.String,
        developerPortalIdentifier: Schema.NullOr(Schema.String),
        id: Schema.String,
        serialNumber: Schema.String,
        updatedAt: Schema.String,
        validityNotAfter: Schema.String,
        validityNotBefore: Schema.String,
      }),
    ),
    applePushKeys: Schema.Array(
      Schema.Struct({
        createdAt: Schema.String,
        id: Schema.String,
        keyIdentifier: Schema.String,
        keyP8: Schema.String,
        updatedAt: Schema.String,
      }),
    ),
    appleTeamIdentifier: Schema.String,
    appleTeamName: Schema.NullOr(Schema.String),
    appleTeamType: Schema.NullOr(
      Schema.Literals(["COMPANY_OR_ORGANIZATION", "INDIVIDUAL", "IN_HOUSE"]),
    ),
    id: Schema.String,
    lastDeletionAttemptTime: Schema.NullOr(Schema.String),
  }),
  closedAt: Schema.NullOr(Schema.String),
  id: Schema.String,
  resolvedAppleDevice: Schema.NullOr(
    Schema.Struct({
      account: Schema.Struct({
        appCount: Schema.Number,
        availableBuilds: Schema.NullOr(Schema.Number),
        createdAt: Schema.String,
        displayName: Schema.NullOr(Schema.String),
        environmentVariableEnvironments: Schema.Array(Schema.Unknown),
        hasBuilds: Schema.Boolean,
        id: Schema.String,
        isCurrent: Schema.Boolean,
        isDisabled: Schema.Boolean,
        isFreeAppDevDomainTier: Schema.Boolean,
        isSSOEnabled: Schema.Boolean,
        lastDeletionAttemptTime: Schema.NullOr(Schema.String),
        name: Schema.String,
        profileImageUrl: Schema.String,
        pushSecurityEnabled: Schema.Boolean,
        requireTwoFactor: Schema.Boolean,
        requiresAccessTokenForPushSecurity: Schema.Boolean,
        ssoAllowedAuthProviders: Schema.Array(
          Schema.Literals([
            "AMAZON_FEDERATE",
            "GENERIC",
            "GOOGLE_WS",
            "MS_ENTRA_ID",
            "OKTA",
            "ONE_LOGIN",
            "STUB_IDP",
          ]),
        ),
        subscriptionChangesPending: Schema.NullOr(Schema.Boolean),
        unlimitedBuilds: Schema.Boolean,
        updatedAt: Schema.String,
        userSpecifiedAccountUsage: Schema.NullOr(
          Schema.Literals(["COMPANY", "PERSONAL"]),
        ),
        willAutoRenewBuilds: Schema.NullOr(Schema.Boolean),
      }),
      appleTeam: Schema.Struct({
        appleTeamIdentifier: Schema.String,
        appleTeamName: Schema.NullOr(Schema.String),
        appleTeamType: Schema.NullOr(
          Schema.Literals([
            "COMPANY_OR_ORGANIZATION",
            "INDIVIDUAL",
            "IN_HOUSE",
          ]),
        ),
        id: Schema.String,
        lastDeletionAttemptTime: Schema.NullOr(Schema.String),
      }),
      createdAt: Schema.String,
      deviceClass: Schema.NullOr(
        Schema.Literals(["IPAD", "IPHONE", "MAC", "UNKNOWN"]),
      ),
      enabled: Schema.NullOr(Schema.Boolean),
      id: Schema.String,
      identifier: Schema.String,
      model: Schema.NullOr(Schema.String),
      name: Schema.NullOr(Schema.String),
      softwareVersion: Schema.NullOr(Schema.String),
    }),
  ),
  workflowJob: Schema.NullOr(
    Schema.Struct({
      allDeviceTestCaseResults: Schema.Array(
        Schema.Struct({
          createdAt: Schema.String,
          duration: Schema.NullOr(Schema.Number),
          errorMessage: Schema.NullOr(Schema.String),
          id: Schema.String,
          name: Schema.String,
          path: Schema.String,
          properties: Schema.NullOr(Schema.Unknown),
          retryCount: Schema.NullOr(Schema.Number),
          status: Schema.Literals(["FAILED", "PASSED"]),
          tags: Schema.NullOr(Schema.Array(Schema.String)),
          updatedAt: Schema.String,
        }),
      ),
      approvals: Schema.Array(
        Schema.Struct({
          createdAt: Schema.String,
          decision: Schema.Literals(["APPROVED", "REJECTED"]),
          id: Schema.String,
          updatedAt: Schema.String,
        }),
      ),
      createdAt: Schema.String,
      deviceTestCaseResultAttempts: Schema.Array(
        Schema.Struct({
          createdAt: Schema.String,
          duration: Schema.NullOr(Schema.Number),
          errorMessage: Schema.NullOr(Schema.String),
          id: Schema.String,
          name: Schema.String,
          path: Schema.String,
          properties: Schema.NullOr(Schema.Unknown),
          retryCount: Schema.NullOr(Schema.Number),
          status: Schema.Literals(["FAILED", "PASSED"]),
          tags: Schema.NullOr(Schema.Array(Schema.String)),
          updatedAt: Schema.String,
        }),
      ),
      deviceTestCaseResults: Schema.Array(
        Schema.Struct({
          createdAt: Schema.String,
          duration: Schema.NullOr(Schema.Number),
          errorMessage: Schema.NullOr(Schema.String),
          id: Schema.String,
          name: Schema.String,
          path: Schema.String,
          properties: Schema.NullOr(Schema.Unknown),
          retryCount: Schema.NullOr(Schema.Number),
          status: Schema.Literals(["FAILED", "PASSED"]),
          tags: Schema.NullOr(Schema.Array(Schema.String)),
          updatedAt: Schema.String,
        }),
      ),
      environment: Schema.NullOr(Schema.String),
      errors: Schema.Array(
        Schema.Struct({
          message: Schema.String,
          title: Schema.String,
        }),
      ),
      id: Schema.String,
      key: Schema.String,
      name: Schema.String,
      outputs: Schema.Unknown,
      requiredJobKeys: Schema.Array(Schema.String),
      status: Schema.Literals([
        "ACTION_REQUIRED",
        "CANCELED",
        "FAILURE",
        "IN_PROGRESS",
        "NEW",
        "PENDING_CANCEL",
        "SKIPPED",
        "SUCCESS",
      ]),
      turtleBuild: Schema.NullOr(
        Schema.Struct({
          activityTimestamp: Schema.String,
          appBuildVersion: Schema.NullOr(Schema.String),
          appIdentifier: Schema.NullOr(Schema.String),
          appVersion: Schema.NullOr(Schema.String),
          buildMode: Schema.NullOr(
            Schema.Literals(["BUILD", "CUSTOM", "LOCAL", "REPACK", "RESIGN"]),
          ),
          buildProfile: Schema.NullOr(Schema.String),
          channel: Schema.NullOr(Schema.String),
          cliVersion: Schema.NullOr(Schema.String),
          completedAt: Schema.NullOr(Schema.String),
          createdAt: Schema.String,
          customNodeVersion: Schema.NullOr(Schema.String),
          customWorkflowName: Schema.NullOr(Schema.String),
          developmentClient: Schema.NullOr(Schema.Boolean),
          distribution: Schema.NullOr(
            Schema.Literals(["INTERNAL", "SIMULATOR", "STORE"]),
          ),
          enqueuedAt: Schema.NullOr(Schema.String),
          estimatedWaitTimeLeftSeconds: Schema.NullOr(Schema.Number),
          expirationDate: Schema.NullOr(Schema.String),
          gitCommitHash: Schema.NullOr(Schema.String),
          gitCommitMessage: Schema.NullOr(Schema.String),
          gitRef: Schema.NullOr(Schema.String),
          githubRepositoryOwnerAndName: Schema.NullOr(Schema.String),
          id: Schema.String,
          initialQueuePosition: Schema.NullOr(Schema.Number),
          iosEnterpriseProvisioning: Schema.NullOr(
            Schema.Literals(["ADHOC", "UNIVERSAL"]),
          ),
          isForIosSimulator: Schema.Boolean,
          isGitWorkingTreeDirty: Schema.NullOr(Schema.Boolean),
          isWaived: Schema.Boolean,
          logFiles: Schema.Array(Schema.String),
          maxBuildTimeSeconds: Schema.Number,
          maxRetryTimeMinutes: Schema.NullOr(Schema.Number),
          message: Schema.NullOr(Schema.String),
          platform: Schema.Literals(["ANDROID", "IOS"]),
          priority: Schema.Literals(["HIGH", "NORMAL", "NORMAL_PLUS"]),
          projectMetadataFileUrl: Schema.NullOr(Schema.String),
          projectRootDirectory: Schema.NullOr(Schema.String),
          provisioningStartedAt: Schema.NullOr(Schema.String),
          queuePosition: Schema.NullOr(Schema.Number),
          reactNativeVersion: Schema.NullOr(Schema.String),
          releaseChannel: Schema.NullOr(Schema.String),
          requiredPackageManager: Schema.NullOr(Schema.String),
          resolvedEnvironment: Schema.NullOr(Schema.Unknown),
          resolvedImage: Schema.NullOr(Schema.String),
          resourceClass: Schema.Literals([
            "ANDROID_DEFAULT",
            "ANDROID_LARGE",
            "ANDROID_MEDIUM",
            "IOS_DEFAULT",
            "IOS_INTEL_LARGE",
            "IOS_INTEL_MEDIUM",
            "IOS_LARGE",
            "IOS_M1_LARGE",
            "IOS_M1_MEDIUM",
            "IOS_MEDIUM",
            "IOS_M_LARGE",
            "IOS_M_MEDIUM",
            "LEGACY",
            "LINUX_LARGE",
            "LINUX_MEDIUM",
          ]),
          resourceClassDisplayName: Schema.String,
          runFromCI: Schema.NullOr(Schema.Boolean),
          runtimeVersion: Schema.NullOr(Schema.String),
          sdkVersion: Schema.NullOr(Schema.String),
          selectedImage: Schema.NullOr(Schema.String),
          status: Schema.Literals([
            "CANCELED",
            "ERRORED",
            "FINISHED",
            "IN_PROGRESS",
            "IN_QUEUE",
            "NEW",
            "PENDING_CANCEL",
          ]),
          updatedAt: Schema.String,
          waiverType: Schema.NullOr(
            Schema.Literals(["FAST_FAILED_BUILD", "SYSTEM_ERROR"]),
          ),
          workerStartedAt: Schema.NullOr(Schema.String),
        }),
      ),
      turtleJobRun: Schema.NullOr(
        Schema.Struct({
          createdAt: Schema.String,
          displayName: Schema.NullOr(Schema.String),
          endedAt: Schema.NullOr(Schema.String),
          enqueuedAt: Schema.NullOr(Schema.String),
          expiresAt: Schema.String,
          gitCommitHash: Schema.NullOr(Schema.String),
          gitCommitMessage: Schema.NullOr(Schema.String),
          gitRef: Schema.NullOr(Schema.String),
          id: Schema.String,
          isWaived: Schema.Boolean,
          logFileUrls: Schema.Array(Schema.String),
          maxRunTimeSeconds: Schema.Number,
          name: Schema.String,
          priority: Schema.Literals(["HIGH", "NORMAL"]),
          resourceClassDisplayName: Schema.String,
          startedAt: Schema.NullOr(Schema.String),
          status: Schema.Literals([
            "CANCELED",
            "ERRORED",
            "FINISHED",
            "IN_PROGRESS",
            "IN_QUEUE",
            "NEW",
            "PENDING_CANCEL",
          ]),
          updateGroups: Schema.Array(Schema.Array(Schema.Unknown)),
        }),
      ),
      turtleSubmission: Schema.NullOr(
        Schema.Struct({
          activityTimestamp: Schema.String,
          archiveUrl: Schema.NullOr(Schema.String),
          canRetry: Schema.Boolean,
          completedAt: Schema.NullOr(Schema.String),
          createdAt: Schema.String,
          id: Schema.String,
          logFiles: Schema.Array(Schema.String),
          logsUrl: Schema.NullOr(Schema.String),
          maxRetryTimeMinutes: Schema.Number,
          platform: Schema.Literals(["ANDROID", "IOS"]),
          priority: Schema.NullOr(Schema.Literals(["HIGH", "NORMAL"])),
          status: Schema.Literals([
            "AWAITING_BUILD",
            "CANCELED",
            "ERRORED",
            "FINISHED",
            "IN_PROGRESS",
            "IN_QUEUE",
          ]),
          updatedAt: Schema.String,
        }),
      ),
      type: Schema.Literals([
        "APPLE_DEVICE_REGISTRATION_REQUEST",
        "BRANCH_DELETE",
        "BUILD",
        "CUSTOM",
        "DEPLOY",
        "DOC",
        "FINGERPRINT",
        "GET_BUILD",
        "GITHUB_COMMENT",
        "MAESTRO_CLOUD",
        "MAESTRO_TEST",
        "REPACK",
        "REQUIRE_APPROVAL",
        "SLACK",
        "SUBMISSION",
        "TESTFLIGHT",
        "UPDATE",
      ]),
      updatedAt: Schema.String,
      workflowRun: Schema.Struct({
        activityTimestamp: Schema.String,
        createdAt: Schema.String,
        durationSeconds: Schema.NullOr(Schema.Number),
        finalizedAt: Schema.NullOr(Schema.String),
        gitCommitHash: Schema.NullOr(Schema.String),
        gitCommitMessage: Schema.NullOr(Schema.String),
        id: Schema.String,
        inputs: Schema.NullOr(Schema.Unknown),
        name: Schema.String,
        pullRequestNumber: Schema.NullOr(Schema.Number),
        requestedGitRef: Schema.NullOr(Schema.String),
        sourceExpiresAt: Schema.NullOr(Schema.String),
        status: Schema.Literals([
          "ACTION_REQUIRED",
          "CANCELED",
          "FAILURE",
          "IN_PROGRESS",
          "NEW",
          "SUCCESS",
        ]),
        triggerEventType: Schema.Literals([
          "APP_STORE_CONNECT_APP_VERSION_STATE_CHANGED",
          "APP_STORE_CONNECT_BETA_FEEDBACK_SUBMITTED",
          "APP_STORE_CONNECT_BUILD_UPLOAD_STATE_CHANGED",
          "APP_STORE_CONNECT_EXTERNAL_BETA_STATE_CHANGED",
          "EAS_SUBMIT",
          "EXPO_LAUNCH",
          "GITHUB_PULL_REQUEST_BASE_REF_CHANGED",
          "GITHUB_PULL_REQUEST_EDITED",
          "GITHUB_PULL_REQUEST_LABELED",
          "GITHUB_PULL_REQUEST_OPENED",
          "GITHUB_PULL_REQUEST_READY_FOR_REVIEW",
          "GITHUB_PULL_REQUEST_REOPENED",
          "GITHUB_PULL_REQUEST_SYNCHRONIZE",
          "GITHUB_PUSH",
          "GITHUB_REF_DELETE",
          "MANUAL",
          "REPACK_EXPO_GO",
          "SCHEDULE",
        ]),
        triggeringLabelName: Schema.NullOr(Schema.String),
        triggeringSchedule: Schema.NullOr(Schema.String),
        updatedAt: Schema.String,
      }),
    }),
  ),
}).pipe(T.ResponsePath("appleDeviceRegistrationRequest.byId"));
export type AppleDeviceRegistrationRequestByIdOutput =
  typeof AppleDeviceRegistrationRequestByIdOutput.Type;

export const appleDeviceRegistrationRequestById = API.make(() => ({
  inputSchema: AppleDeviceRegistrationRequestByIdInput,
  outputSchema: AppleDeviceRegistrationRequestByIdOutput,
}));
