import * as Schema from "effect/Schema";
import { API } from "../client.ts";
import * as T from "../traits.ts";

const __document =
  "mutation githubBuildTriggerUpdateGitHubBuildTrigger($githubBuildTriggerData: UpdateGitHubBuildTriggerInput!, $githubBuildTriggerId: ID!) {\n  githubBuildTrigger {\n    updateGitHubBuildTrigger(githubBuildTriggerData: $githubBuildTriggerData, githubBuildTriggerId: $githubBuildTriggerId) {\n      app {\n        accessTokens {\n          createdAt\n          id\n          lastUsedAt\n          note\n          revokedAt\n          updatedAt\n          visibleTokenPrefix\n        }\n        appStoreConnectApp {\n          ascAppIdentifier\n          createdAt\n          id\n          updatedAt\n          webhookEventTypes\n          webhookIdentifier\n        }\n        appStoreUrl\n        assetLimitPerUpdateGroup\n        buildProfiles\n        buildsReleaseChannels\n        convexProject {\n          convexProjectIdentifier\n          convexProjectName\n          convexProjectSlug\n          createdAt\n          id\n          updatedAt\n        }\n        description\n        devDomainName {\n          id\n          name\n        }\n        environmentVariableEnvironments\n        fullName\n        githubJobRunTriggers {\n          createdAt\n          id\n          isActive\n          jobType\n          lastRunAt\n          lastRunErrorCode\n          lastRunErrorMessage\n          lastRunStatus\n          sourcePattern\n          targetPattern\n          triggerType\n        }\n        githubRepository {\n          createdAt\n          githubRepositoryIdentifier\n          githubRepositoryUrl\n          id\n          lastDeletionAttemptTime\n          nodeIdentifier\n        }\n        githubRepositorySettings {\n          baseDirectory\n          id\n        }\n        githubUrl\n        icon {\n          colorPalette\n          originalUrl\n          primaryColor\n          url\n        }\n        iconUrl\n        id\n        insights {\n          hasEventsFromExpoInsightsClientModule\n        }\n        internalDistributionBuildPrivacy\n        isDeleting\n        isDeprecated\n        isLikedByMe\n        lastDeletionAttemptTime\n        lastPublishedTime\n        latestActivity\n        latestReleaseId\n        likeCount\n        logRocketProject {\n          createdAt\n          id\n          logRocketOrgId\n          logRocketProjectSlug\n          updatedAt\n        }\n        name\n        observe {\n          totalEventCount\n        }\n        ownerAccount {\n          appCount\n          availableBuilds\n          createdAt\n          displayName\n          environmentVariableEnvironments\n          hasBuilds\n          id\n          isCurrent\n          isDisabled\n          isFreeAppDevDomainTier\n          isSSOEnabled\n          lastDeletionAttemptTime\n          name\n          profileImageUrl\n          pushSecurityEnabled\n          requireTwoFactor\n          requiresAccessTokenForPushSecurity\n          ssoAllowedAuthProviders\n          subscriptionChangesPending\n          unlimitedBuilds\n          updatedAt\n          userSpecifiedAccountUsage\n          willAutoRenewBuilds\n        }\n        packageName\n        packageUsername\n        playStoreUrl\n        privacy\n        privacySetting\n        published\n        pushNotifications {\n          id\n        }\n        pushSecurityEnabled\n        releaseChannels\n        requiresAccessTokenForPushSecurity\n        resourceClassExperiment\n        scopeKey\n        sdkVersion\n        sentryProject {\n          createdAt\n          id\n          sentryInstallationId\n          sentryProjectId\n          sentryProjectSlug\n          updatedAt\n        }\n        slug\n        suggestedDevDomainName\n        trendScore\n        updated\n        username\n        users {\n          appCount\n          appetizeCode\n          bestContactEmail\n          created\n          displayName\n          email\n          emailVerified\n          firstName\n          fullName\n          githubUsername\n          hasPassword\n          hasPendingUserInvitations\n          id\n          industry\n          isExpoAdmin\n          isLegacy\n          isSecondFactorAuthenticationEnabled\n          isStaffModeEnabled\n          lastDeletionAttemptTime\n          lastName\n          location\n          newEmailPendingVerification\n          primaryAccountProfileImageUrl\n          profilePhoto\n          twitterUsername\n          username\n        }\n        vexoApp {\n          domain\n          iconUrl\n          id\n          name\n          owner\n          slug\n          vexoIdentifier\n        }\n        workerCustomDomain {\n          createdAt\n          devDomainName\n          hostname\n          id\n          updatedAt\n        }\n      }\n      autoSubmit\n      buildProfile\n      createdAt\n      environment\n      executionBehavior\n      id\n      isActive\n      lastRunAt\n      lastRunBuild {\n        activityTimestamp\n        actor {\n          created\n          displayName\n          firstName\n          id\n          isExpoAdmin\n          lastDeletionAttemptTime\n        }\n        app {\n          appStoreUrl\n          assetLimitPerUpdateGroup\n          buildProfiles\n          buildsReleaseChannels\n          description\n          environmentVariableEnvironments\n          fullName\n          githubUrl\n          iconUrl\n          id\n          internalDistributionBuildPrivacy\n          isDeleting\n          isDeprecated\n          isLikedByMe\n          lastDeletionAttemptTime\n          lastPublishedTime\n          latestActivity\n          latestReleaseId\n          likeCount\n          name\n          packageName\n          packageUsername\n          playStoreUrl\n          privacy\n          privacySetting\n          published\n          pushSecurityEnabled\n          releaseChannels\n          requiresAccessTokenForPushSecurity\n          resourceClassExperiment\n          scopeKey\n          sdkVersion\n          slug\n          suggestedDevDomainName\n          trendScore\n          updated\n          username\n        }\n        appBuildVersion\n        appIdentifier\n        appVersion\n        artifacts {\n          applicationArchiveUrl\n          buildArtifactsUrl\n          buildUrl\n          fingerprintUrl\n          xcodeBuildLogsUrl\n        }\n        buildMode\n        buildProfile\n        cancelingActor {\n          created\n          displayName\n          firstName\n          id\n          isExpoAdmin\n          lastDeletionAttemptTime\n        }\n        channel\n        cliVersion\n        completedAt\n        createdAt\n        customNodeVersion\n        customWorkflowName\n        deployment {\n          id\n        }\n        developmentClient\n        distribution\n        enqueuedAt\n        error {\n          buildPhase\n          docsUrl\n          errorCode\n          message\n        }\n        estimatedWaitTimeLeftSeconds\n        expirationDate\n        fingerprint {\n          buildCount\n          createdAt\n          debugInfoUrl\n          hash\n          id\n          updateCount\n          updatedAt\n        }\n        gitCommitHash\n        gitCommitMessage\n        gitRef\n        githubRepositoryOwnerAndName\n        id\n        initialQueuePosition\n        initiatingActor {\n          created\n          displayName\n          firstName\n          id\n          isExpoAdmin\n          lastDeletionAttemptTime\n        }\n        iosEnterpriseProvisioning\n        isForIosSimulator\n        isGitWorkingTreeDirty\n        isWaived\n        logFiles\n        maxBuildTimeSeconds\n        maxRetryTimeMinutes\n        message\n        metrics {\n          buildDuration\n          buildQueueTime\n          buildWaitTime\n        }\n        platform\n        priority\n        project {\n          description\n          fullName\n          iconUrl\n          id\n          name\n          published\n          slug\n          updated\n          username\n        }\n        projectMetadataFileUrl\n        projectRootDirectory\n        provisioningStartedAt\n        queuePosition\n        reactNativeVersion\n        releaseChannel\n        requiredPackageManager\n        resolvedEnvironment\n        resourceClass\n        resourceClassDisplayName\n        runFromCI\n        runtime {\n          createdAt\n          firstBuildCreatedAt\n          id\n          isFingerprint\n          updatedAt\n          version\n        }\n        runtimeVersion\n        sdkVersion\n        selectedImage\n        status\n        submissions {\n          activityTimestamp\n          archiveUrl\n          canRetry\n          completedAt\n          createdAt\n          id\n          logFiles\n          logsUrl\n          maxRetryTimeMinutes\n          platform\n          priority\n          status\n          updatedAt\n        }\n        updateChannel {\n          appId\n          branchMapping\n          createdAt\n          id\n          isPaused\n          lastDeletionAttemptTime\n          name\n          updatedAt\n        }\n        updatedAt\n        waiverType\n        workerStartedAt\n        workflowJob {\n          createdAt\n          environment\n          id\n          key\n          name\n          outputs\n          requiredJobKeys\n          status\n          type\n          updatedAt\n        }\n      }\n      lastRunErrorCode\n      lastRunErrorMessage\n      lastRunStatus\n      platform\n      sourcePattern\n      submitProfile\n      targetPattern\n      type\n      updatedAt\n    }\n  }\n}";

// Input Schema (GraphQL variables)
export const GithubBuildTriggerUpdateGitHubBuildTriggerInput = Schema.Struct({
  githubBuildTriggerData: Schema.Struct({
    autoSubmit: Schema.Boolean,
    buildProfile: Schema.String,
    environment: Schema.optional(Schema.NullOr(Schema.Unknown)),
    executionBehavior: Schema.Literals(["ALWAYS", "BASE_DIRECTORY_CHANGED"]),
    isActive: Schema.Boolean,
    platform: Schema.Literals(["ANDROID", "IOS"]),
    sourcePattern: Schema.String,
    submitProfile: Schema.optional(Schema.NullOr(Schema.String)),
    targetPattern: Schema.optional(Schema.NullOr(Schema.String)),
    type: Schema.Literals([
      "PULL_REQUEST_UPDATED",
      "PUSH_TO_BRANCH",
      "TAG_UPDATED",
    ]),
  }),
  githubBuildTriggerId: Schema.String,
}).pipe(
  T.Http({ method: "POST", path: "/graphql" }),
  T.GraphQLOp({
    query: __document,
    operationName: "githubBuildTriggerUpdateGitHubBuildTrigger",
    type: "mutation",
  }),
);
export type GithubBuildTriggerUpdateGitHubBuildTriggerInput =
  typeof GithubBuildTriggerUpdateGitHubBuildTriggerInput.Type;

// Output Schema (GraphQL selection set)
export const GithubBuildTriggerUpdateGitHubBuildTriggerOutput = Schema.Struct({
  app: Schema.Struct({
    accessTokens: Schema.Array(
      Schema.NullOr(
        Schema.Struct({
          createdAt: Schema.String,
          id: Schema.String,
          lastUsedAt: Schema.NullOr(Schema.String),
          note: Schema.NullOr(Schema.String),
          revokedAt: Schema.NullOr(Schema.String),
          updatedAt: Schema.String,
          visibleTokenPrefix: Schema.String,
        }),
      ),
    ),
    appStoreConnectApp: Schema.NullOr(
      Schema.Struct({
        ascAppIdentifier: Schema.String,
        createdAt: Schema.String,
        id: Schema.String,
        updatedAt: Schema.String,
        webhookEventTypes: Schema.Array(Schema.String),
        webhookIdentifier: Schema.String,
      }),
    ),
    appStoreUrl: Schema.NullOr(Schema.String),
    assetLimitPerUpdateGroup: Schema.Number,
    buildProfiles: Schema.Array(Schema.String),
    buildsReleaseChannels: Schema.Array(Schema.String),
    convexProject: Schema.NullOr(
      Schema.Struct({
        convexProjectIdentifier: Schema.String,
        convexProjectName: Schema.String,
        convexProjectSlug: Schema.String,
        createdAt: Schema.String,
        id: Schema.String,
        updatedAt: Schema.String,
      }),
    ),
    description: Schema.String,
    devDomainName: Schema.NullOr(
      Schema.Struct({
        id: Schema.String,
        name: Schema.Unknown,
      }),
    ),
    environmentVariableEnvironments: Schema.Array(Schema.Unknown),
    fullName: Schema.String,
    githubJobRunTriggers: Schema.Array(
      Schema.Struct({
        createdAt: Schema.String,
        id: Schema.String,
        isActive: Schema.Boolean,
        jobType: Schema.NullOr(Schema.Literals(["PUBLISH_UPDATE"])),
        lastRunAt: Schema.NullOr(Schema.String),
        lastRunErrorCode: Schema.NullOr(Schema.String),
        lastRunErrorMessage: Schema.NullOr(Schema.String),
        lastRunStatus: Schema.NullOr(Schema.Literals(["ERRORED", "SUCCESS"])),
        sourcePattern: Schema.String,
        targetPattern: Schema.NullOr(Schema.String),
        triggerType: Schema.Literals([
          "PULL_REQUEST_UPDATED",
          "PUSH_TO_BRANCH",
        ]),
      }),
    ),
    githubRepository: Schema.NullOr(
      Schema.Struct({
        createdAt: Schema.String,
        githubRepositoryIdentifier: Schema.Number,
        githubRepositoryUrl: Schema.NullOr(Schema.String),
        id: Schema.String,
        lastDeletionAttemptTime: Schema.NullOr(Schema.String),
        nodeIdentifier: Schema.String,
      }),
    ),
    githubRepositorySettings: Schema.NullOr(
      Schema.Struct({
        baseDirectory: Schema.String,
        id: Schema.String,
      }),
    ),
    githubUrl: Schema.NullOr(Schema.String),
    icon: Schema.NullOr(
      Schema.Struct({
        colorPalette: Schema.NullOr(Schema.Unknown),
        originalUrl: Schema.String,
        primaryColor: Schema.NullOr(Schema.String),
        url: Schema.String,
      }),
    ),
    iconUrl: Schema.NullOr(Schema.String),
    id: Schema.String,
    insights: Schema.Struct({
      hasEventsFromExpoInsightsClientModule: Schema.Boolean,
    }),
    internalDistributionBuildPrivacy: Schema.Literals(["PRIVATE", "PUBLIC"]),
    isDeleting: Schema.Boolean,
    isDeprecated: Schema.Boolean,
    isLikedByMe: Schema.Boolean,
    lastDeletionAttemptTime: Schema.NullOr(Schema.String),
    lastPublishedTime: Schema.String,
    latestActivity: Schema.String,
    latestReleaseId: Schema.String,
    likeCount: Schema.Number,
    logRocketProject: Schema.NullOr(
      Schema.Struct({
        createdAt: Schema.String,
        id: Schema.String,
        logRocketOrgId: Schema.String,
        logRocketProjectSlug: Schema.String,
        updatedAt: Schema.String,
      }),
    ),
    name: Schema.String,
    observe: Schema.Struct({
      totalEventCount: Schema.Number,
    }),
    ownerAccount: Schema.Struct({
      appCount: Schema.Number,
      availableBuilds: Schema.NullOr(Schema.Number),
      createdAt: Schema.String,
      displayName: Schema.NullOr(Schema.String),
      environmentVariableEnvironments: Schema.Array(Schema.Unknown),
      hasBuilds: Schema.Boolean,
      id: Schema.String,
      isCurrent: Schema.Boolean,
      isDisabled: Schema.Boolean,
      isFreeAppDevDomainTier: Schema.Boolean,
      isSSOEnabled: Schema.Boolean,
      lastDeletionAttemptTime: Schema.NullOr(Schema.String),
      name: Schema.String,
      profileImageUrl: Schema.String,
      pushSecurityEnabled: Schema.Boolean,
      requireTwoFactor: Schema.Boolean,
      requiresAccessTokenForPushSecurity: Schema.Boolean,
      ssoAllowedAuthProviders: Schema.Array(
        Schema.Literals([
          "AMAZON_FEDERATE",
          "GENERIC",
          "GOOGLE_WS",
          "MS_ENTRA_ID",
          "OKTA",
          "ONE_LOGIN",
          "STUB_IDP",
        ]),
      ),
      subscriptionChangesPending: Schema.NullOr(Schema.Boolean),
      unlimitedBuilds: Schema.Boolean,
      updatedAt: Schema.String,
      userSpecifiedAccountUsage: Schema.NullOr(
        Schema.Literals(["COMPANY", "PERSONAL"]),
      ),
      willAutoRenewBuilds: Schema.NullOr(Schema.Boolean),
    }),
    packageName: Schema.String,
    packageUsername: Schema.String,
    playStoreUrl: Schema.NullOr(Schema.String),
    privacy: Schema.String,
    privacySetting: Schema.Literals(["HIDDEN", "PUBLIC", "UNLISTED"]),
    published: Schema.Boolean,
    pushNotifications: Schema.Struct({
      id: Schema.String,
    }),
    pushSecurityEnabled: Schema.Boolean,
    releaseChannels: Schema.Array(Schema.String),
    requiresAccessTokenForPushSecurity: Schema.Boolean,
    resourceClassExperiment: Schema.NullOr(Schema.Literals(["C3D", "N2"])),
    scopeKey: Schema.String,
    sdkVersion: Schema.String,
    sentryProject: Schema.NullOr(
      Schema.Struct({
        createdAt: Schema.String,
        id: Schema.String,
        sentryInstallationId: Schema.String,
        sentryProjectId: Schema.String,
        sentryProjectSlug: Schema.String,
        updatedAt: Schema.String,
      }),
    ),
    slug: Schema.String,
    suggestedDevDomainName: Schema.String,
    trendScore: Schema.Number,
    updated: Schema.String,
    username: Schema.String,
    users: Schema.NullOr(
      Schema.Array(
        Schema.NullOr(
          Schema.Struct({
            appCount: Schema.Number,
            appetizeCode: Schema.NullOr(Schema.String),
            bestContactEmail: Schema.NullOr(Schema.String),
            created: Schema.String,
            displayName: Schema.String,
            email: Schema.String,
            emailVerified: Schema.Boolean,
            firstName: Schema.NullOr(Schema.String),
            fullName: Schema.NullOr(Schema.String),
            githubUsername: Schema.NullOr(Schema.String),
            hasPassword: Schema.Boolean,
            hasPendingUserInvitations: Schema.Boolean,
            id: Schema.String,
            industry: Schema.NullOr(Schema.String),
            isExpoAdmin: Schema.Boolean,
            isLegacy: Schema.Boolean,
            isSecondFactorAuthenticationEnabled: Schema.Boolean,
            isStaffModeEnabled: Schema.Boolean,
            lastDeletionAttemptTime: Schema.NullOr(Schema.String),
            lastName: Schema.NullOr(Schema.String),
            location: Schema.NullOr(Schema.String),
            newEmailPendingVerification: Schema.NullOr(Schema.String),
            primaryAccountProfileImageUrl: Schema.NullOr(Schema.String),
            profilePhoto: Schema.String,
            twitterUsername: Schema.NullOr(Schema.String),
            username: Schema.String,
          }),
        ),
      ),
    ),
    vexoApp: Schema.NullOr(
      Schema.Struct({
        domain: Schema.NullOr(Schema.String),
        iconUrl: Schema.NullOr(Schema.String),
        id: Schema.String,
        name: Schema.String,
        owner: Schema.String,
        slug: Schema.String,
        vexoIdentifier: Schema.String,
      }),
    ),
    workerCustomDomain: Schema.NullOr(
      Schema.Struct({
        createdAt: Schema.String,
        devDomainName: Schema.Unknown,
        hostname: Schema.String,
        id: Schema.String,
        updatedAt: Schema.String,
      }),
    ),
  }),
  autoSubmit: Schema.Boolean,
  buildProfile: Schema.String,
  createdAt: Schema.String,
  environment: Schema.NullOr(Schema.Unknown),
  executionBehavior: Schema.Literals(["ALWAYS", "BASE_DIRECTORY_CHANGED"]),
  id: Schema.String,
  isActive: Schema.Boolean,
  lastRunAt: Schema.NullOr(Schema.String),
  lastRunBuild: Schema.NullOr(
    Schema.Struct({
      activityTimestamp: Schema.String,
      actor: Schema.NullOr(
        Schema.Struct({
          created: Schema.String,
          displayName: Schema.String,
          firstName: Schema.NullOr(Schema.String),
          id: Schema.String,
          isExpoAdmin: Schema.Boolean,
          lastDeletionAttemptTime: Schema.NullOr(Schema.String),
        }),
      ),
      app: Schema.Struct({
        appStoreUrl: Schema.NullOr(Schema.String),
        assetLimitPerUpdateGroup: Schema.Number,
        buildProfiles: Schema.Array(Schema.String),
        buildsReleaseChannels: Schema.Array(Schema.String),
        description: Schema.String,
        environmentVariableEnvironments: Schema.Array(Schema.Unknown),
        fullName: Schema.String,
        githubUrl: Schema.NullOr(Schema.String),
        iconUrl: Schema.NullOr(Schema.String),
        id: Schema.String,
        internalDistributionBuildPrivacy: Schema.Literals([
          "PRIVATE",
          "PUBLIC",
        ]),
        isDeleting: Schema.Boolean,
        isDeprecated: Schema.Boolean,
        isLikedByMe: Schema.Boolean,
        lastDeletionAttemptTime: Schema.NullOr(Schema.String),
        lastPublishedTime: Schema.String,
        latestActivity: Schema.String,
        latestReleaseId: Schema.String,
        likeCount: Schema.Number,
        name: Schema.String,
        packageName: Schema.String,
        packageUsername: Schema.String,
        playStoreUrl: Schema.NullOr(Schema.String),
        privacy: Schema.String,
        privacySetting: Schema.Literals(["HIDDEN", "PUBLIC", "UNLISTED"]),
        published: Schema.Boolean,
        pushSecurityEnabled: Schema.Boolean,
        releaseChannels: Schema.Array(Schema.String),
        requiresAccessTokenForPushSecurity: Schema.Boolean,
        resourceClassExperiment: Schema.NullOr(Schema.Literals(["C3D", "N2"])),
        scopeKey: Schema.String,
        sdkVersion: Schema.String,
        slug: Schema.String,
        suggestedDevDomainName: Schema.String,
        trendScore: Schema.Number,
        updated: Schema.String,
        username: Schema.String,
      }),
      appBuildVersion: Schema.NullOr(Schema.String),
      appIdentifier: Schema.NullOr(Schema.String),
      appVersion: Schema.NullOr(Schema.String),
      artifacts: Schema.NullOr(
        Schema.Struct({
          applicationArchiveUrl: Schema.NullOr(Schema.String),
          buildArtifactsUrl: Schema.NullOr(Schema.String),
          buildUrl: Schema.NullOr(Schema.String),
          fingerprintUrl: Schema.NullOr(Schema.String),
          xcodeBuildLogsUrl: Schema.NullOr(Schema.String),
        }),
      ),
      buildMode: Schema.NullOr(
        Schema.Literals(["BUILD", "CUSTOM", "LOCAL", "REPACK", "RESIGN"]),
      ),
      buildProfile: Schema.NullOr(Schema.String),
      cancelingActor: Schema.NullOr(
        Schema.Struct({
          created: Schema.String,
          displayName: Schema.String,
          firstName: Schema.NullOr(Schema.String),
          id: Schema.String,
          isExpoAdmin: Schema.Boolean,
          lastDeletionAttemptTime: Schema.NullOr(Schema.String),
        }),
      ),
      channel: Schema.NullOr(Schema.String),
      cliVersion: Schema.NullOr(Schema.String),
      completedAt: Schema.NullOr(Schema.String),
      createdAt: Schema.String,
      customNodeVersion: Schema.NullOr(Schema.String),
      customWorkflowName: Schema.NullOr(Schema.String),
      deployment: Schema.NullOr(
        Schema.Struct({
          id: Schema.String,
        }),
      ),
      developmentClient: Schema.NullOr(Schema.Boolean),
      distribution: Schema.NullOr(
        Schema.Literals(["INTERNAL", "SIMULATOR", "STORE"]),
      ),
      enqueuedAt: Schema.NullOr(Schema.String),
      error: Schema.NullOr(
        Schema.Struct({
          buildPhase: Schema.NullOr(
            Schema.Literals([
              "BUILDER_INFO",
              "CACHE_STATS",
              "CALCULATE_EXPO_UPDATES_RUNTIME_VERSION",
              "CLEAN_UP_CREDENTIALS",
              "COMPLETE_BUILD",
              "COMPLETE_JOB",
              "CONFIGURE_ANDROID_VERSION",
              "CONFIGURE_EXPO_UPDATES",
              "CONFIGURE_XCODE_PROJECT",
              "CUSTOM",
              "DOWNLOAD_APPLICATION_ARCHIVE",
              "EAGER_BUNDLE",
              "EAS_BUILD_INTERNAL",
              "FAIL_BUILD",
              "FIX_GRADLEW",
              "INSTALL_CUSTOM_TOOLS",
              "INSTALL_DEPENDENCIES",
              "INSTALL_PODS",
              "ON_BUILD_CANCEL_HOOK",
              "ON_BUILD_COMPLETE_HOOK",
              "ON_BUILD_ERROR_HOOK",
              "ON_BUILD_SUCCESS_HOOK",
              "PARSE_CUSTOM_WORKFLOW_CONFIG",
              "POST_INSTALL_HOOK",
              "PREBUILD",
              "PREPARE_ARTIFACTS",
              "PREPARE_CREDENTIALS",
              "PREPARE_PROJECT",
              "PRE_INSTALL_HOOK",
              "PRE_UPLOAD_ARTIFACTS_HOOK",
              "QUEUE",
              "READ_APP_CONFIG",
              "READ_EAS_JSON",
              "READ_PACKAGE_JSON",
              "RESTORE_CACHE",
              "RUN_EXPO_DOCTOR",
              "RUN_FASTLANE",
              "RUN_GRADLEW",
              "SAVE_CACHE",
              "SET_UP_BUILD_ENVIRONMENT",
              "SPIN_UP_BUILDER",
              "START_BUILD",
              "UNKNOWN",
              "UPLOAD_APPLICATION_ARCHIVE",
              "UPLOAD_ARTIFACTS",
              "UPLOAD_BUILD_ARTIFACTS",
            ]),
          ),
          docsUrl: Schema.NullOr(Schema.String),
          errorCode: Schema.String,
          message: Schema.String,
        }),
      ),
      estimatedWaitTimeLeftSeconds: Schema.NullOr(Schema.Number),
      expirationDate: Schema.NullOr(Schema.String),
      fingerprint: Schema.NullOr(
        Schema.Struct({
          buildCount: Schema.Number,
          createdAt: Schema.String,
          debugInfoUrl: Schema.NullOr(Schema.String),
          hash: Schema.String,
          id: Schema.String,
          updateCount: Schema.Number,
          updatedAt: Schema.String,
        }),
      ),
      gitCommitHash: Schema.NullOr(Schema.String),
      gitCommitMessage: Schema.NullOr(Schema.String),
      gitRef: Schema.NullOr(Schema.String),
      githubRepositoryOwnerAndName: Schema.NullOr(Schema.String),
      id: Schema.String,
      initialQueuePosition: Schema.NullOr(Schema.Number),
      initiatingActor: Schema.NullOr(
        Schema.Struct({
          created: Schema.String,
          displayName: Schema.String,
          firstName: Schema.NullOr(Schema.String),
          id: Schema.String,
          isExpoAdmin: Schema.Boolean,
          lastDeletionAttemptTime: Schema.NullOr(Schema.String),
        }),
      ),
      iosEnterpriseProvisioning: Schema.NullOr(
        Schema.Literals(["ADHOC", "UNIVERSAL"]),
      ),
      isForIosSimulator: Schema.Boolean,
      isGitWorkingTreeDirty: Schema.NullOr(Schema.Boolean),
      isWaived: Schema.Boolean,
      logFiles: Schema.Array(Schema.String),
      maxBuildTimeSeconds: Schema.Number,
      maxRetryTimeMinutes: Schema.NullOr(Schema.Number),
      message: Schema.NullOr(Schema.String),
      metrics: Schema.NullOr(
        Schema.Struct({
          buildDuration: Schema.NullOr(Schema.Number),
          buildQueueTime: Schema.NullOr(Schema.Number),
          buildWaitTime: Schema.NullOr(Schema.Number),
        }),
      ),
      platform: Schema.Literals(["ANDROID", "IOS"]),
      priority: Schema.Literals(["HIGH", "NORMAL", "NORMAL_PLUS"]),
      project: Schema.Struct({
        description: Schema.String,
        fullName: Schema.String,
        iconUrl: Schema.NullOr(Schema.String),
        id: Schema.String,
        name: Schema.String,
        published: Schema.Boolean,
        slug: Schema.String,
        updated: Schema.String,
        username: Schema.String,
      }),
      projectMetadataFileUrl: Schema.NullOr(Schema.String),
      projectRootDirectory: Schema.NullOr(Schema.String),
      provisioningStartedAt: Schema.NullOr(Schema.String),
      queuePosition: Schema.NullOr(Schema.Number),
      reactNativeVersion: Schema.NullOr(Schema.String),
      releaseChannel: Schema.NullOr(Schema.String),
      requiredPackageManager: Schema.NullOr(Schema.String),
      resolvedEnvironment: Schema.NullOr(Schema.Unknown),
      resourceClass: Schema.Literals([
        "ANDROID_DEFAULT",
        "ANDROID_LARGE",
        "ANDROID_MEDIUM",
        "IOS_DEFAULT",
        "IOS_INTEL_LARGE",
        "IOS_INTEL_MEDIUM",
        "IOS_LARGE",
        "IOS_M1_LARGE",
        "IOS_M1_MEDIUM",
        "IOS_MEDIUM",
        "IOS_M_LARGE",
        "IOS_M_MEDIUM",
        "LEGACY",
        "LINUX_LARGE",
        "LINUX_MEDIUM",
      ]),
      resourceClassDisplayName: Schema.String,
      runFromCI: Schema.NullOr(Schema.Boolean),
      runtime: Schema.NullOr(
        Schema.Struct({
          createdAt: Schema.String,
          firstBuildCreatedAt: Schema.NullOr(Schema.String),
          id: Schema.String,
          isFingerprint: Schema.Boolean,
          updatedAt: Schema.String,
          version: Schema.String,
        }),
      ),
      runtimeVersion: Schema.NullOr(Schema.String),
      sdkVersion: Schema.NullOr(Schema.String),
      selectedImage: Schema.NullOr(Schema.String),
      status: Schema.Literals([
        "CANCELED",
        "ERRORED",
        "FINISHED",
        "IN_PROGRESS",
        "IN_QUEUE",
        "NEW",
        "PENDING_CANCEL",
      ]),
      submissions: Schema.Array(
        Schema.Struct({
          activityTimestamp: Schema.String,
          archiveUrl: Schema.NullOr(Schema.String),
          canRetry: Schema.Boolean,
          completedAt: Schema.NullOr(Schema.String),
          createdAt: Schema.String,
          id: Schema.String,
          logFiles: Schema.Array(Schema.String),
          logsUrl: Schema.NullOr(Schema.String),
          maxRetryTimeMinutes: Schema.Number,
          platform: Schema.Literals(["ANDROID", "IOS"]),
          priority: Schema.NullOr(Schema.Literals(["HIGH", "NORMAL"])),
          status: Schema.Literals([
            "AWAITING_BUILD",
            "CANCELED",
            "ERRORED",
            "FINISHED",
            "IN_PROGRESS",
            "IN_QUEUE",
          ]),
          updatedAt: Schema.String,
        }),
      ),
      updateChannel: Schema.NullOr(
        Schema.Struct({
          appId: Schema.String,
          branchMapping: Schema.String,
          createdAt: Schema.String,
          id: Schema.String,
          isPaused: Schema.Boolean,
          lastDeletionAttemptTime: Schema.NullOr(Schema.String),
          name: Schema.String,
          updatedAt: Schema.String,
        }),
      ),
      updatedAt: Schema.String,
      waiverType: Schema.NullOr(
        Schema.Literals(["FAST_FAILED_BUILD", "SYSTEM_ERROR"]),
      ),
      workerStartedAt: Schema.NullOr(Schema.String),
      workflowJob: Schema.NullOr(
        Schema.Struct({
          createdAt: Schema.String,
          environment: Schema.NullOr(Schema.String),
          id: Schema.String,
          key: Schema.String,
          name: Schema.String,
          outputs: Schema.Unknown,
          requiredJobKeys: Schema.Array(Schema.String),
          status: Schema.Literals([
            "ACTION_REQUIRED",
            "CANCELED",
            "FAILURE",
            "IN_PROGRESS",
            "NEW",
            "PENDING_CANCEL",
            "SKIPPED",
            "SUCCESS",
          ]),
          type: Schema.Literals([
            "APPLE_DEVICE_REGISTRATION_REQUEST",
            "BUILD",
            "CUSTOM",
            "DEPLOY",
            "DOC",
            "FINGERPRINT",
            "GET_BUILD",
            "GITHUB_COMMENT",
            "MAESTRO_CLOUD",
            "MAESTRO_TEST",
            "REPACK",
            "REQUIRE_APPROVAL",
            "SLACK",
            "SUBMISSION",
            "TESTFLIGHT",
            "UPDATE",
          ]),
          updatedAt: Schema.String,
        }),
      ),
    }),
  ),
  lastRunErrorCode: Schema.NullOr(Schema.String),
  lastRunErrorMessage: Schema.NullOr(Schema.String),
  lastRunStatus: Schema.NullOr(Schema.Literals(["ERRORED", "SUCCESS"])),
  platform: Schema.Literals(["ANDROID", "IOS"]),
  sourcePattern: Schema.String,
  submitProfile: Schema.NullOr(Schema.String),
  targetPattern: Schema.NullOr(Schema.String),
  type: Schema.Literals([
    "PULL_REQUEST_UPDATED",
    "PUSH_TO_BRANCH",
    "TAG_UPDATED",
  ]),
  updatedAt: Schema.String,
}).pipe(T.ResponsePath("githubBuildTrigger.updateGitHubBuildTrigger"));
export type GithubBuildTriggerUpdateGitHubBuildTriggerOutput =
  typeof GithubBuildTriggerUpdateGitHubBuildTriggerOutput.Type;

export const githubBuildTriggerUpdateGitHubBuildTrigger = API.make(() => ({
  inputSchema: GithubBuildTriggerUpdateGitHubBuildTriggerInput,
  outputSchema: GithubBuildTriggerUpdateGitHubBuildTriggerOutput,
}));
