import * as Schema from "effect/Schema";
import { API } from "../client.ts";
import * as T from "../traits.ts";

const __document =
  "mutation workflowRunCancelWorkflowRun($workflowRunId: ID!) {\n  workflowRun {\n    cancelWorkflowRun(workflowRunId: $workflowRunId) {\n      activityTimestamp\n      actor {\n        accessTokens {\n          createdAt\n          id\n          lastUsedAt\n          note\n          revokedAt\n          updatedAt\n          visibleTokenPrefix\n        }\n        accounts {\n          appCount\n          availableBuilds\n          createdAt\n          displayName\n          environmentVariableEnvironments\n          hasBuilds\n          id\n          isCurrent\n          isDisabled\n          isFreeAppDevDomainTier\n          isSSOEnabled\n          lastDeletionAttemptTime\n          name\n          profileImageUrl\n          pushSecurityEnabled\n          requireTwoFactor\n          requiresAccessTokenForPushSecurity\n          ssoAllowedAuthProviders\n          subscriptionChangesPending\n          unlimitedBuilds\n          updatedAt\n          userSpecifiedAccountUsage\n          willAutoRenewBuilds\n        }\n        created\n        displayName\n        experiments {\n          createdAt\n          enabled\n          experiment\n          id\n          updatedAt\n        }\n        firstName\n        id\n        isExpoAdmin\n        lastDeletionAttemptTime\n      }\n      createdAt\n      durationSeconds\n      errors {\n        message\n        title\n      }\n      finalizedAt\n      gitCommitHash\n      gitCommitMessage\n      githubRepository {\n        app {\n          appStoreUrl\n          assetLimitPerUpdateGroup\n          buildProfiles\n          buildsReleaseChannels\n          description\n          environmentVariableEnvironments\n          fullName\n          githubUrl\n          iconUrl\n          id\n          internalDistributionBuildPrivacy\n          isDeleting\n          isDeprecated\n          isLikedByMe\n          lastDeletionAttemptTime\n          lastPublishedTime\n          latestActivity\n          latestReleaseId\n          likeCount\n          name\n          packageName\n          packageUsername\n          playStoreUrl\n          privacy\n          privacySetting\n          published\n          pushSecurityEnabled\n          releaseChannels\n          requiresAccessTokenForPushSecurity\n          resourceClassExperiment\n          scopeKey\n          sdkVersion\n          slug\n          suggestedDevDomainName\n          trendScore\n          updated\n          username\n        }\n        createdAt\n        githubAppInstallation {\n          id\n          installationIdentifier\n        }\n        githubRepositoryIdentifier\n        githubRepositoryUrl\n        id\n        lastDeletionAttemptTime\n        metadata {\n          defaultBranch\n          githubRepoDescription\n          githubRepoName\n          githubRepoOwnerName\n          githubRepoUrl\n          lastPushed\n          lastUpdated\n          private\n        }\n        nodeIdentifier\n      }\n      id\n      inputs\n      jobs {\n        allDeviceTestCaseResults {\n          createdAt\n          duration\n          errorMessage\n          id\n          name\n          path\n          properties\n          retryCount\n          status\n          tags\n          updatedAt\n        }\n        approvals {\n          createdAt\n          decision\n          id\n          updatedAt\n        }\n        createdAt\n        credentialsAppleDeviceRegistrationRequest {\n          id\n        }\n        deviceTestCaseResults {\n          createdAt\n          duration\n          errorMessage\n          id\n          name\n          path\n          properties\n          retryCount\n          status\n          tags\n          updatedAt\n        }\n        environment\n        errors {\n          message\n          title\n        }\n        id\n        key\n        name\n        outputs\n        requiredJobKeys\n        status\n        turtleBuild {\n          activityTimestamp\n          appBuildVersion\n          appIdentifier\n          appVersion\n          buildMode\n          buildProfile\n          channel\n          cliVersion\n          completedAt\n          createdAt\n          customNodeVersion\n          customWorkflowName\n          developmentClient\n          distribution\n          enqueuedAt\n          estimatedWaitTimeLeftSeconds\n          expirationDate\n          gitCommitHash\n          gitCommitMessage\n          gitRef\n          githubRepositoryOwnerAndName\n          id\n          initialQueuePosition\n          iosEnterpriseProvisioning\n          isForIosSimulator\n          isGitWorkingTreeDirty\n          isWaived\n          logFiles\n          maxBuildTimeSeconds\n          maxRetryTimeMinutes\n          message\n          platform\n          priority\n          projectMetadataFileUrl\n          projectRootDirectory\n          provisioningStartedAt\n          queuePosition\n          reactNativeVersion\n          releaseChannel\n          requiredPackageManager\n          resolvedEnvironment\n          resourceClass\n          resourceClassDisplayName\n          runFromCI\n          runtimeVersion\n          sdkVersion\n          selectedImage\n          status\n          updatedAt\n          waiverType\n          workerStartedAt\n        }\n        turtleJobRun {\n          createdAt\n          displayName\n          endedAt\n          expiresAt\n          gitCommitHash\n          gitCommitMessage\n          gitRef\n          id\n          isWaived\n          logFileUrls\n          name\n          priority\n          startedAt\n          status\n          updateGroups\n        }\n        turtleSubmission {\n          activityTimestamp\n          archiveUrl\n          canRetry\n          completedAt\n          createdAt\n          id\n          logFiles\n          logsUrl\n          maxRetryTimeMinutes\n          platform\n          priority\n          status\n          updatedAt\n        }\n        type\n        updatedAt\n      }\n      name\n      pullRequestNumber\n      requestedGitRef\n      sourceExpiresAt\n      status\n      triggerEventType\n      triggeringLabelName\n      triggeringSchedule\n      updatedAt\n      workflow {\n        app {\n          appStoreUrl\n          assetLimitPerUpdateGroup\n          buildProfiles\n          buildsReleaseChannels\n          description\n          environmentVariableEnvironments\n          fullName\n          githubUrl\n          iconUrl\n          id\n          internalDistributionBuildPrivacy\n          isDeleting\n          isDeprecated\n          isLikedByMe\n          lastDeletionAttemptTime\n          lastPublishedTime\n          latestActivity\n          latestReleaseId\n          likeCount\n          name\n          packageName\n          packageUsername\n          playStoreUrl\n          privacy\n          privacySetting\n          published\n          pushSecurityEnabled\n          releaseChannels\n          requiresAccessTokenForPushSecurity\n          resourceClassExperiment\n          scopeKey\n          sdkVersion\n          slug\n          suggestedDevDomainName\n          trendScore\n          updated\n          username\n        }\n        createdAt\n        fileName\n        id\n        name\n        updatedAt\n      }\n      workflowRevision {\n        blobSha\n        commitSha\n        createdAt\n        id\n        workflow {\n          createdAt\n          fileName\n          id\n          name\n          updatedAt\n        }\n        yamlConfig\n      }\n    }\n  }\n}";

// Input Schema (GraphQL variables)
export const WorkflowRunCancelWorkflowRunInput = Schema.Struct({
  workflowRunId: Schema.String,
}).pipe(
  T.Http({ method: "POST", path: "/graphql" }),
  T.GraphQLOp({
    query: __document,
    operationName: "workflowRunCancelWorkflowRun",
    type: "mutation",
  }),
);
export type WorkflowRunCancelWorkflowRunInput =
  typeof WorkflowRunCancelWorkflowRunInput.Type;

// Output Schema (GraphQL selection set)
export const WorkflowRunCancelWorkflowRunOutput = Schema.Struct({
  activityTimestamp: Schema.String,
  actor: Schema.NullOr(
    Schema.Struct({
      accessTokens: Schema.Array(
        Schema.Struct({
          createdAt: Schema.String,
          id: Schema.String,
          lastUsedAt: Schema.NullOr(Schema.String),
          note: Schema.NullOr(Schema.String),
          revokedAt: Schema.NullOr(Schema.String),
          updatedAt: Schema.String,
          visibleTokenPrefix: Schema.String,
        }),
      ),
      accounts: Schema.Array(
        Schema.Struct({
          appCount: Schema.Number,
          availableBuilds: Schema.NullOr(Schema.Number),
          createdAt: Schema.String,
          displayName: Schema.NullOr(Schema.String),
          environmentVariableEnvironments: Schema.Array(Schema.Unknown),
          hasBuilds: Schema.Boolean,
          id: Schema.String,
          isCurrent: Schema.Boolean,
          isDisabled: Schema.Boolean,
          isFreeAppDevDomainTier: Schema.Boolean,
          isSSOEnabled: Schema.Boolean,
          lastDeletionAttemptTime: Schema.NullOr(Schema.String),
          name: Schema.String,
          profileImageUrl: Schema.String,
          pushSecurityEnabled: Schema.Boolean,
          requireTwoFactor: Schema.Boolean,
          requiresAccessTokenForPushSecurity: Schema.Boolean,
          ssoAllowedAuthProviders: Schema.Array(
            Schema.Literals([
              "AMAZON_FEDERATE",
              "GENERIC",
              "GOOGLE_WS",
              "MS_ENTRA_ID",
              "OKTA",
              "ONE_LOGIN",
              "STUB_IDP",
            ]),
          ),
          subscriptionChangesPending: Schema.NullOr(Schema.Boolean),
          unlimitedBuilds: Schema.Boolean,
          updatedAt: Schema.String,
          userSpecifiedAccountUsage: Schema.NullOr(
            Schema.Literals(["COMPANY", "PERSONAL"]),
          ),
          willAutoRenewBuilds: Schema.NullOr(Schema.Boolean),
        }),
      ),
      created: Schema.String,
      displayName: Schema.String,
      experiments: Schema.Array(
        Schema.Struct({
          createdAt: Schema.String,
          enabled: Schema.Boolean,
          experiment: Schema.Literals(["ORBIT"]),
          id: Schema.String,
          updatedAt: Schema.String,
        }),
      ),
      firstName: Schema.NullOr(Schema.String),
      id: Schema.String,
      isExpoAdmin: Schema.Boolean,
      lastDeletionAttemptTime: Schema.NullOr(Schema.String),
    }),
  ),
  createdAt: Schema.String,
  durationSeconds: Schema.NullOr(Schema.Number),
  errors: Schema.Array(
    Schema.Struct({
      message: Schema.String,
      title: Schema.NullOr(Schema.String),
    }),
  ),
  finalizedAt: Schema.NullOr(Schema.String),
  gitCommitHash: Schema.NullOr(Schema.String),
  gitCommitMessage: Schema.NullOr(Schema.String),
  githubRepository: Schema.NullOr(
    Schema.Struct({
      app: Schema.Struct({
        appStoreUrl: Schema.NullOr(Schema.String),
        assetLimitPerUpdateGroup: Schema.Number,
        buildProfiles: Schema.Array(Schema.String),
        buildsReleaseChannels: Schema.Array(Schema.String),
        description: Schema.String,
        environmentVariableEnvironments: Schema.Array(Schema.Unknown),
        fullName: Schema.String,
        githubUrl: Schema.NullOr(Schema.String),
        iconUrl: Schema.NullOr(Schema.String),
        id: Schema.String,
        internalDistributionBuildPrivacy: Schema.Literals([
          "PRIVATE",
          "PUBLIC",
        ]),
        isDeleting: Schema.Boolean,
        isDeprecated: Schema.Boolean,
        isLikedByMe: Schema.Boolean,
        lastDeletionAttemptTime: Schema.NullOr(Schema.String),
        lastPublishedTime: Schema.String,
        latestActivity: Schema.String,
        latestReleaseId: Schema.String,
        likeCount: Schema.Number,
        name: Schema.String,
        packageName: Schema.String,
        packageUsername: Schema.String,
        playStoreUrl: Schema.NullOr(Schema.String),
        privacy: Schema.String,
        privacySetting: Schema.Literals(["HIDDEN", "PUBLIC", "UNLISTED"]),
        published: Schema.Boolean,
        pushSecurityEnabled: Schema.Boolean,
        releaseChannels: Schema.Array(Schema.String),
        requiresAccessTokenForPushSecurity: Schema.Boolean,
        resourceClassExperiment: Schema.NullOr(Schema.Literals(["C3D", "N2"])),
        scopeKey: Schema.String,
        sdkVersion: Schema.String,
        slug: Schema.String,
        suggestedDevDomainName: Schema.String,
        trendScore: Schema.Number,
        updated: Schema.String,
        username: Schema.String,
      }),
      createdAt: Schema.String,
      githubAppInstallation: Schema.Struct({
        id: Schema.String,
        installationIdentifier: Schema.Number,
      }),
      githubRepositoryIdentifier: Schema.Number,
      githubRepositoryUrl: Schema.NullOr(Schema.String),
      id: Schema.String,
      lastDeletionAttemptTime: Schema.NullOr(Schema.String),
      metadata: Schema.Struct({
        defaultBranch: Schema.NullOr(Schema.String),
        githubRepoDescription: Schema.NullOr(Schema.String),
        githubRepoName: Schema.String,
        githubRepoOwnerName: Schema.String,
        githubRepoUrl: Schema.String,
        lastPushed: Schema.String,
        lastUpdated: Schema.String,
        private: Schema.Boolean,
      }),
      nodeIdentifier: Schema.String,
    }),
  ),
  id: Schema.String,
  inputs: Schema.NullOr(Schema.Unknown),
  jobs: Schema.Array(
    Schema.Struct({
      allDeviceTestCaseResults: Schema.Array(
        Schema.Struct({
          createdAt: Schema.String,
          duration: Schema.NullOr(Schema.Number),
          errorMessage: Schema.NullOr(Schema.String),
          id: Schema.String,
          name: Schema.String,
          path: Schema.String,
          properties: Schema.NullOr(Schema.Unknown),
          retryCount: Schema.NullOr(Schema.Number),
          status: Schema.Literals(["FAILED", "PASSED"]),
          tags: Schema.NullOr(Schema.Array(Schema.String)),
          updatedAt: Schema.String,
        }),
      ),
      approvals: Schema.Array(
        Schema.Struct({
          createdAt: Schema.String,
          decision: Schema.Literals(["APPROVED", "REJECTED"]),
          id: Schema.String,
          updatedAt: Schema.String,
        }),
      ),
      createdAt: Schema.String,
      credentialsAppleDeviceRegistrationRequest: Schema.NullOr(
        Schema.Struct({
          id: Schema.String,
        }),
      ),
      deviceTestCaseResults: Schema.Array(
        Schema.Struct({
          createdAt: Schema.String,
          duration: Schema.NullOr(Schema.Number),
          errorMessage: Schema.NullOr(Schema.String),
          id: Schema.String,
          name: Schema.String,
          path: Schema.String,
          properties: Schema.NullOr(Schema.Unknown),
          retryCount: Schema.NullOr(Schema.Number),
          status: Schema.Literals(["FAILED", "PASSED"]),
          tags: Schema.NullOr(Schema.Array(Schema.String)),
          updatedAt: Schema.String,
        }),
      ),
      environment: Schema.NullOr(Schema.String),
      errors: Schema.Array(
        Schema.Struct({
          message: Schema.String,
          title: Schema.String,
        }),
      ),
      id: Schema.String,
      key: Schema.String,
      name: Schema.String,
      outputs: Schema.Unknown,
      requiredJobKeys: Schema.Array(Schema.String),
      status: Schema.Literals([
        "ACTION_REQUIRED",
        "CANCELED",
        "FAILURE",
        "IN_PROGRESS",
        "NEW",
        "PENDING_CANCEL",
        "SKIPPED",
        "SUCCESS",
      ]),
      turtleBuild: Schema.NullOr(
        Schema.Struct({
          activityTimestamp: Schema.String,
          appBuildVersion: Schema.NullOr(Schema.String),
          appIdentifier: Schema.NullOr(Schema.String),
          appVersion: Schema.NullOr(Schema.String),
          buildMode: Schema.NullOr(
            Schema.Literals(["BUILD", "CUSTOM", "LOCAL", "REPACK", "RESIGN"]),
          ),
          buildProfile: Schema.NullOr(Schema.String),
          channel: Schema.NullOr(Schema.String),
          cliVersion: Schema.NullOr(Schema.String),
          completedAt: Schema.NullOr(Schema.String),
          createdAt: Schema.String,
          customNodeVersion: Schema.NullOr(Schema.String),
          customWorkflowName: Schema.NullOr(Schema.String),
          developmentClient: Schema.NullOr(Schema.Boolean),
          distribution: Schema.NullOr(
            Schema.Literals(["INTERNAL", "SIMULATOR", "STORE"]),
          ),
          enqueuedAt: Schema.NullOr(Schema.String),
          estimatedWaitTimeLeftSeconds: Schema.NullOr(Schema.Number),
          expirationDate: Schema.NullOr(Schema.String),
          gitCommitHash: Schema.NullOr(Schema.String),
          gitCommitMessage: Schema.NullOr(Schema.String),
          gitRef: Schema.NullOr(Schema.String),
          githubRepositoryOwnerAndName: Schema.NullOr(Schema.String),
          id: Schema.String,
          initialQueuePosition: Schema.NullOr(Schema.Number),
          iosEnterpriseProvisioning: Schema.NullOr(
            Schema.Literals(["ADHOC", "UNIVERSAL"]),
          ),
          isForIosSimulator: Schema.Boolean,
          isGitWorkingTreeDirty: Schema.NullOr(Schema.Boolean),
          isWaived: Schema.Boolean,
          logFiles: Schema.Array(Schema.String),
          maxBuildTimeSeconds: Schema.Number,
          maxRetryTimeMinutes: Schema.NullOr(Schema.Number),
          message: Schema.NullOr(Schema.String),
          platform: Schema.Literals(["ANDROID", "IOS"]),
          priority: Schema.Literals(["HIGH", "NORMAL", "NORMAL_PLUS"]),
          projectMetadataFileUrl: Schema.NullOr(Schema.String),
          projectRootDirectory: Schema.NullOr(Schema.String),
          provisioningStartedAt: Schema.NullOr(Schema.String),
          queuePosition: Schema.NullOr(Schema.Number),
          reactNativeVersion: Schema.NullOr(Schema.String),
          releaseChannel: Schema.NullOr(Schema.String),
          requiredPackageManager: Schema.NullOr(Schema.String),
          resolvedEnvironment: Schema.NullOr(Schema.Unknown),
          resourceClass: Schema.Literals([
            "ANDROID_DEFAULT",
            "ANDROID_LARGE",
            "ANDROID_MEDIUM",
            "IOS_DEFAULT",
            "IOS_INTEL_LARGE",
            "IOS_INTEL_MEDIUM",
            "IOS_LARGE",
            "IOS_M1_LARGE",
            "IOS_M1_MEDIUM",
            "IOS_MEDIUM",
            "IOS_M_LARGE",
            "IOS_M_MEDIUM",
            "LEGACY",
            "LINUX_LARGE",
            "LINUX_MEDIUM",
          ]),
          resourceClassDisplayName: Schema.String,
          runFromCI: Schema.NullOr(Schema.Boolean),
          runtimeVersion: Schema.NullOr(Schema.String),
          sdkVersion: Schema.NullOr(Schema.String),
          selectedImage: Schema.NullOr(Schema.String),
          status: Schema.Literals([
            "CANCELED",
            "ERRORED",
            "FINISHED",
            "IN_PROGRESS",
            "IN_QUEUE",
            "NEW",
            "PENDING_CANCEL",
          ]),
          updatedAt: Schema.String,
          waiverType: Schema.NullOr(
            Schema.Literals(["FAST_FAILED_BUILD", "SYSTEM_ERROR"]),
          ),
          workerStartedAt: Schema.NullOr(Schema.String),
        }),
      ),
      turtleJobRun: Schema.NullOr(
        Schema.Struct({
          createdAt: Schema.String,
          displayName: Schema.NullOr(Schema.String),
          endedAt: Schema.NullOr(Schema.String),
          expiresAt: Schema.String,
          gitCommitHash: Schema.NullOr(Schema.String),
          gitCommitMessage: Schema.NullOr(Schema.String),
          gitRef: Schema.NullOr(Schema.String),
          id: Schema.String,
          isWaived: Schema.Boolean,
          logFileUrls: Schema.Array(Schema.String),
          name: Schema.String,
          priority: Schema.Literals(["HIGH", "NORMAL"]),
          startedAt: Schema.NullOr(Schema.String),
          status: Schema.Literals([
            "CANCELED",
            "ERRORED",
            "FINISHED",
            "IN_PROGRESS",
            "IN_QUEUE",
            "NEW",
            "PENDING_CANCEL",
          ]),
          updateGroups: Schema.Array(Schema.Array(Schema.Unknown)),
        }),
      ),
      turtleSubmission: Schema.NullOr(
        Schema.Struct({
          activityTimestamp: Schema.String,
          archiveUrl: Schema.NullOr(Schema.String),
          canRetry: Schema.Boolean,
          completedAt: Schema.NullOr(Schema.String),
          createdAt: Schema.String,
          id: Schema.String,
          logFiles: Schema.Array(Schema.String),
          logsUrl: Schema.NullOr(Schema.String),
          maxRetryTimeMinutes: Schema.Number,
          platform: Schema.Literals(["ANDROID", "IOS"]),
          priority: Schema.NullOr(Schema.Literals(["HIGH", "NORMAL"])),
          status: Schema.Literals([
            "AWAITING_BUILD",
            "CANCELED",
            "ERRORED",
            "FINISHED",
            "IN_PROGRESS",
            "IN_QUEUE",
          ]),
          updatedAt: Schema.String,
        }),
      ),
      type: Schema.Literals([
        "APPLE_DEVICE_REGISTRATION_REQUEST",
        "BUILD",
        "CUSTOM",
        "DEPLOY",
        "DOC",
        "FINGERPRINT",
        "GET_BUILD",
        "GITHUB_COMMENT",
        "MAESTRO_CLOUD",
        "MAESTRO_TEST",
        "REPACK",
        "REQUIRE_APPROVAL",
        "SLACK",
        "SUBMISSION",
        "TESTFLIGHT",
        "UPDATE",
      ]),
      updatedAt: Schema.String,
    }),
  ),
  name: Schema.String,
  pullRequestNumber: Schema.NullOr(Schema.Number),
  requestedGitRef: Schema.NullOr(Schema.String),
  sourceExpiresAt: Schema.NullOr(Schema.String),
  status: Schema.Literals([
    "ACTION_REQUIRED",
    "CANCELED",
    "FAILURE",
    "IN_PROGRESS",
    "NEW",
    "SUCCESS",
  ]),
  triggerEventType: Schema.Literals([
    "APP_STORE_CONNECT_APP_VERSION_STATE_CHANGED",
    "APP_STORE_CONNECT_BETA_FEEDBACK_SUBMITTED",
    "APP_STORE_CONNECT_BUILD_UPLOAD_STATE_CHANGED",
    "APP_STORE_CONNECT_EXTERNAL_BETA_STATE_CHANGED",
    "EAS_SUBMIT",
    "EXPO_LAUNCH",
    "GITHUB_PULL_REQUEST_LABELED",
    "GITHUB_PULL_REQUEST_OPENED",
    "GITHUB_PULL_REQUEST_READY_FOR_REVIEW",
    "GITHUB_PULL_REQUEST_REOPENED",
    "GITHUB_PULL_REQUEST_SYNCHRONIZE",
    "GITHUB_PUSH",
    "MANUAL",
    "REPACK_EXPO_GO",
    "SCHEDULE",
  ]),
  triggeringLabelName: Schema.NullOr(Schema.String),
  triggeringSchedule: Schema.NullOr(Schema.String),
  updatedAt: Schema.String,
  workflow: Schema.Struct({
    app: Schema.Struct({
      appStoreUrl: Schema.NullOr(Schema.String),
      assetLimitPerUpdateGroup: Schema.Number,
      buildProfiles: Schema.Array(Schema.String),
      buildsReleaseChannels: Schema.Array(Schema.String),
      description: Schema.String,
      environmentVariableEnvironments: Schema.Array(Schema.Unknown),
      fullName: Schema.String,
      githubUrl: Schema.NullOr(Schema.String),
      iconUrl: Schema.NullOr(Schema.String),
      id: Schema.String,
      internalDistributionBuildPrivacy: Schema.Literals(["PRIVATE", "PUBLIC"]),
      isDeleting: Schema.Boolean,
      isDeprecated: Schema.Boolean,
      isLikedByMe: Schema.Boolean,
      lastDeletionAttemptTime: Schema.NullOr(Schema.String),
      lastPublishedTime: Schema.String,
      latestActivity: Schema.String,
      latestReleaseId: Schema.String,
      likeCount: Schema.Number,
      name: Schema.String,
      packageName: Schema.String,
      packageUsername: Schema.String,
      playStoreUrl: Schema.NullOr(Schema.String),
      privacy: Schema.String,
      privacySetting: Schema.Literals(["HIDDEN", "PUBLIC", "UNLISTED"]),
      published: Schema.Boolean,
      pushSecurityEnabled: Schema.Boolean,
      releaseChannels: Schema.Array(Schema.String),
      requiresAccessTokenForPushSecurity: Schema.Boolean,
      resourceClassExperiment: Schema.NullOr(Schema.Literals(["C3D", "N2"])),
      scopeKey: Schema.String,
      sdkVersion: Schema.String,
      slug: Schema.String,
      suggestedDevDomainName: Schema.String,
      trendScore: Schema.Number,
      updated: Schema.String,
      username: Schema.String,
    }),
    createdAt: Schema.String,
    fileName: Schema.String,
    id: Schema.String,
    name: Schema.NullOr(Schema.String),
    updatedAt: Schema.String,
  }),
  workflowRevision: Schema.NullOr(
    Schema.Struct({
      blobSha: Schema.String,
      commitSha: Schema.NullOr(Schema.String),
      createdAt: Schema.String,
      id: Schema.String,
      workflow: Schema.Struct({
        createdAt: Schema.String,
        fileName: Schema.String,
        id: Schema.String,
        name: Schema.NullOr(Schema.String),
        updatedAt: Schema.String,
      }),
      yamlConfig: Schema.String,
    }),
  ),
}).pipe(T.ResponsePath("workflowRun.cancelWorkflowRun"));
export type WorkflowRunCancelWorkflowRunOutput =
  typeof WorkflowRunCancelWorkflowRunOutput.Type;

export const workflowRunCancelWorkflowRun = API.make(() => ({
  inputSchema: WorkflowRunCancelWorkflowRunInput,
  outputSchema: WorkflowRunCancelWorkflowRunOutput,
}));
