import * as Schema from "effect/Schema";
import { API } from "../client.ts";
import * as T from "../traits.ts";

const __document =
  "query serviceInstance($environmentId: String!, $serviceId: String!) {\n  serviceInstance(environmentId: $environmentId, serviceId: $serviceId) {\n    activeDeployments {\n      canRedeploy\n      canRollback\n      createdAt\n      creator {\n        avatar\n        email\n        id\n        name\n      }\n      deploymentStopped\n      diagnosis\n      environment {\n        canAccess\n        createdAt\n        deletedAt\n        id\n        isEphemeral\n        name\n        projectId\n        unmergedChangesCount\n        updatedAt\n      }\n      environmentId\n      id\n      instances {\n        id\n        status\n      }\n      meta\n      projectId\n      service {\n        createdAt\n        deletedAt\n        featureFlags\n        hasHiddenRegistryCredentialsFromTemplate\n        icon\n        id\n        name\n        projectId\n        templateId\n        templateServiceId\n        templateThreadSlug\n        updatedAt\n      }\n      serviceId\n      snapshotId\n      sockets {\n        ipv6\n        port\n        processName\n        updatedAt\n      }\n      staticUrl\n      status\n      statusUpdatedAt\n      suggestAddServiceDomain\n      updatedAt\n      url\n    }\n    buildCommand\n    builder\n    createdAt\n    cronSchedule\n    deletedAt\n    dockerfilePath\n    domains {\n      customDomains {\n        cdnMode\n        createdAt\n        deletedAt\n        domain\n        edgeId\n        environmentId\n        id\n        projectId\n        serviceId\n        syncStatus\n        targetPort\n        updatedAt\n      }\n      serviceDomains {\n        cdnMode\n        createdAt\n        deletedAt\n        domain\n        edgeId\n        environmentId\n        id\n        newDomainName\n        newHostLabel\n        projectId\n        serviceId\n        suffix\n        syncStatus\n        targetPort\n        updatedAt\n      }\n    }\n    drainingSeconds\n    edgeConfig {\n      caching {\n        defaultTtlSeconds\n        htmlCaching\n        mode\n        purgeOnDeploy\n      }\n      enabled\n      id\n      purgeEpoch\n      purgeEpochByKind\n    }\n    environmentId\n    healthcheckPath\n    healthcheckTimeout\n    id\n    ipv6EgressEnabled\n    isUpdatable\n    latestDeployment {\n      canRedeploy\n      canRollback\n      createdAt\n      creator {\n        avatar\n        email\n        id\n        name\n      }\n      deploymentStopped\n      diagnosis\n      environment {\n        canAccess\n        createdAt\n        deletedAt\n        id\n        isEphemeral\n        name\n        projectId\n        unmergedChangesCount\n        updatedAt\n      }\n      environmentId\n      id\n      instances {\n        id\n        status\n      }\n      meta\n      projectId\n      service {\n        createdAt\n        deletedAt\n        featureFlags\n        hasHiddenRegistryCredentialsFromTemplate\n        icon\n        id\n        name\n        projectId\n        templateId\n        templateServiceId\n        templateThreadSlug\n        updatedAt\n      }\n      serviceId\n      snapshotId\n      sockets {\n        ipv6\n        port\n        processName\n        updatedAt\n      }\n      staticUrl\n      status\n      statusUpdatedAt\n      suggestAddServiceDomain\n      updatedAt\n      url\n    }\n    nextCronRunAt\n    nixpacksPlan\n    numReplicas\n    overlapSeconds\n    preDeployCommand\n    railpackInfo\n    railwayConfigFile\n    region\n    restartPolicyMaxRetries\n    restartPolicyType\n    rootDirectory\n    service {\n      createdAt\n      deletedAt\n      featureFlags\n      hasHiddenRegistryCredentialsFromTemplate\n      icon\n      id\n      name\n      project {\n        baseEnvironmentId\n        botPrEnvironments\n        createdAt\n        deletedAt\n        description\n        expiredAt\n        featureFlags\n        focusedPrEnvironments\n        id\n        isPublic\n        isTempProject\n        name\n        prDeploys\n        primaryEnvironmentId\n        subscriptionPlanLimit\n        subscriptionType\n        teamId\n        updatedAt\n        workspaceId\n      }\n      projectId\n      templateId\n      templateServiceId\n      templateThreadSlug\n      updatedAt\n    }\n    serviceId\n    serviceName\n    sleepApplication\n    source {\n      image\n      repo\n    }\n    startCommand\n    updatedAt\n    upstreamUrl\n    watchPatterns\n  }\n}";

// Input Schema (GraphQL variables)
export const GetServiceInstanceInput = Schema.Struct({
  environmentId: Schema.String,
  serviceId: Schema.String,
}).pipe(
  T.Http({ method: "POST", path: "/graphql/v2" }),
  T.GraphQLOp({
    query: __document,
    operationName: "serviceInstance",
    type: "query",
  }),
);
export type GetServiceInstanceInput = typeof GetServiceInstanceInput.Type;

// Output Schema (GraphQL selection set)
export const GetServiceInstanceOutput = Schema.Struct({
  activeDeployments: Schema.Array(
    Schema.Struct({
      canRedeploy: Schema.Boolean,
      canRollback: Schema.Boolean,
      createdAt: Schema.String,
      creator: Schema.NullOr(
        Schema.Struct({
          avatar: Schema.NullOr(Schema.String),
          email: Schema.String,
          id: Schema.String,
          name: Schema.NullOr(Schema.String),
        }),
      ),
      deploymentStopped: Schema.Boolean,
      diagnosis: Schema.NullOr(Schema.Unknown),
      environment: Schema.Struct({
        canAccess: Schema.Boolean,
        createdAt: Schema.String,
        deletedAt: Schema.NullOr(Schema.String),
        id: Schema.String,
        isEphemeral: Schema.Boolean,
        name: Schema.String,
        projectId: Schema.String,
        unmergedChangesCount: Schema.NullOr(Schema.Number),
        updatedAt: Schema.String,
      }),
      environmentId: Schema.String,
      id: Schema.String,
      instances: Schema.Array(
        Schema.Struct({
          id: Schema.String,
          status: Schema.Literals([
            "CRASHED",
            "CREATED",
            "EXITED",
            "INITIALIZING",
            "REMOVED",
            "REMOVING",
            "RESTARTING",
            "RUNNING",
            "SKIPPED",
            "STOPPED",
          ]),
        }),
      ),
      meta: Schema.NullOr(Schema.Unknown),
      projectId: Schema.String,
      service: Schema.Struct({
        createdAt: Schema.String,
        deletedAt: Schema.NullOr(Schema.String),
        featureFlags: Schema.Array(
          Schema.Literals([
            "COPY_VOLUME_TO_ENVIRONMENT",
            "ENABLE_DOCKER_EXTENSION",
            "PLACEHOLDER",
            "SKIPPED_BUILDS",
            "USE_EXPRESS_DEPLOY",
            "USE_HA_STATIC_EGRESS",
            "USE_VM_RUNTIME",
          ]),
        ),
        hasHiddenRegistryCredentialsFromTemplate: Schema.Boolean,
        icon: Schema.NullOr(Schema.String),
        id: Schema.String,
        name: Schema.String,
        projectId: Schema.String,
        templateId: Schema.NullOr(Schema.String),
        templateServiceId: Schema.NullOr(Schema.String),
        templateThreadSlug: Schema.NullOr(Schema.String),
        updatedAt: Schema.String,
      }),
      serviceId: Schema.NullOr(Schema.String),
      snapshotId: Schema.NullOr(Schema.String),
      sockets: Schema.Array(
        Schema.Struct({
          ipv6: Schema.Boolean,
          port: Schema.Number,
          processName: Schema.String,
          updatedAt: Schema.Number,
        }),
      ),
      staticUrl: Schema.NullOr(Schema.String),
      status: Schema.Literals([
        "BUILDING",
        "CRASHED",
        "DEPLOYING",
        "FAILED",
        "INITIALIZING",
        "NEEDS_APPROVAL",
        "QUEUED",
        "REMOVED",
        "REMOVING",
        "SKIPPED",
        "SLEEPING",
        "SUCCESS",
        "WAITING",
      ]),
      statusUpdatedAt: Schema.NullOr(Schema.String),
      suggestAddServiceDomain: Schema.Boolean,
      updatedAt: Schema.String,
      url: Schema.NullOr(Schema.String),
    }),
  ),
  buildCommand: Schema.NullOr(Schema.String),
  builder: Schema.Literals(["HEROKU", "NIXPACKS", "PAKETO", "RAILPACK"]),
  createdAt: Schema.String,
  cronSchedule: Schema.NullOr(Schema.String),
  deletedAt: Schema.NullOr(Schema.String),
  dockerfilePath: Schema.NullOr(Schema.String),
  domains: Schema.Struct({
    customDomains: Schema.Array(
      Schema.Struct({
        cdnMode: Schema.NullOr(Schema.String),
        createdAt: Schema.NullOr(Schema.String),
        deletedAt: Schema.NullOr(Schema.String),
        domain: Schema.String,
        edgeId: Schema.NullOr(Schema.String),
        environmentId: Schema.String,
        id: Schema.String,
        projectId: Schema.NullOr(Schema.String),
        serviceId: Schema.String,
        syncStatus: Schema.Literals([
          "ACTIVE",
          "CREATING",
          "DELETED",
          "DELETING",
          "UNSPECIFIED",
          "UPDATING",
        ]),
        targetPort: Schema.NullOr(Schema.Number),
        updatedAt: Schema.NullOr(Schema.String),
      }),
    ),
    serviceDomains: Schema.Array(
      Schema.Struct({
        cdnMode: Schema.NullOr(Schema.String),
        createdAt: Schema.NullOr(Schema.String),
        deletedAt: Schema.NullOr(Schema.String),
        domain: Schema.String,
        edgeId: Schema.NullOr(Schema.String),
        environmentId: Schema.String,
        id: Schema.String,
        newDomainName: Schema.NullOr(Schema.String),
        newHostLabel: Schema.NullOr(Schema.String),
        projectId: Schema.NullOr(Schema.String),
        serviceId: Schema.String,
        suffix: Schema.NullOr(Schema.String),
        syncStatus: Schema.Literals([
          "ACTIVE",
          "CREATING",
          "DELETED",
          "DELETING",
          "UNSPECIFIED",
          "UPDATING",
        ]),
        targetPort: Schema.NullOr(Schema.Number),
        updatedAt: Schema.NullOr(Schema.String),
      }),
    ),
  }),
  drainingSeconds: Schema.NullOr(Schema.Number),
  edgeConfig: Schema.NullOr(
    Schema.Struct({
      caching: Schema.NullOr(
        Schema.Struct({
          defaultTtlSeconds: Schema.Number,
          htmlCaching: Schema.String,
          mode: Schema.String,
          purgeOnDeploy: Schema.Literals(["ALL", "HTML", "OFF"]),
        }),
      ),
      enabled: Schema.Boolean,
      id: Schema.String,
      purgeEpoch: Schema.Number,
      purgeEpochByKind: Schema.Unknown,
    }),
  ),
  environmentId: Schema.String,
  healthcheckPath: Schema.NullOr(Schema.String),
  healthcheckTimeout: Schema.NullOr(Schema.Number),
  id: Schema.String,
  ipv6EgressEnabled: Schema.NullOr(Schema.Boolean),
  isUpdatable: Schema.Boolean,
  latestDeployment: Schema.NullOr(
    Schema.Struct({
      canRedeploy: Schema.Boolean,
      canRollback: Schema.Boolean,
      createdAt: Schema.String,
      creator: Schema.NullOr(
        Schema.Struct({
          avatar: Schema.NullOr(Schema.String),
          email: Schema.String,
          id: Schema.String,
          name: Schema.NullOr(Schema.String),
        }),
      ),
      deploymentStopped: Schema.Boolean,
      diagnosis: Schema.NullOr(Schema.Unknown),
      environment: Schema.Struct({
        canAccess: Schema.Boolean,
        createdAt: Schema.String,
        deletedAt: Schema.NullOr(Schema.String),
        id: Schema.String,
        isEphemeral: Schema.Boolean,
        name: Schema.String,
        projectId: Schema.String,
        unmergedChangesCount: Schema.NullOr(Schema.Number),
        updatedAt: Schema.String,
      }),
      environmentId: Schema.String,
      id: Schema.String,
      instances: Schema.Array(
        Schema.Struct({
          id: Schema.String,
          status: Schema.Literals([
            "CRASHED",
            "CREATED",
            "EXITED",
            "INITIALIZING",
            "REMOVED",
            "REMOVING",
            "RESTARTING",
            "RUNNING",
            "SKIPPED",
            "STOPPED",
          ]),
        }),
      ),
      meta: Schema.NullOr(Schema.Unknown),
      projectId: Schema.String,
      service: Schema.Struct({
        createdAt: Schema.String,
        deletedAt: Schema.NullOr(Schema.String),
        featureFlags: Schema.Array(
          Schema.Literals([
            "COPY_VOLUME_TO_ENVIRONMENT",
            "ENABLE_DOCKER_EXTENSION",
            "PLACEHOLDER",
            "SKIPPED_BUILDS",
            "USE_EXPRESS_DEPLOY",
            "USE_HA_STATIC_EGRESS",
            "USE_VM_RUNTIME",
          ]),
        ),
        hasHiddenRegistryCredentialsFromTemplate: Schema.Boolean,
        icon: Schema.NullOr(Schema.String),
        id: Schema.String,
        name: Schema.String,
        projectId: Schema.String,
        templateId: Schema.NullOr(Schema.String),
        templateServiceId: Schema.NullOr(Schema.String),
        templateThreadSlug: Schema.NullOr(Schema.String),
        updatedAt: Schema.String,
      }),
      serviceId: Schema.NullOr(Schema.String),
      snapshotId: Schema.NullOr(Schema.String),
      sockets: Schema.Array(
        Schema.Struct({
          ipv6: Schema.Boolean,
          port: Schema.Number,
          processName: Schema.String,
          updatedAt: Schema.Number,
        }),
      ),
      staticUrl: Schema.NullOr(Schema.String),
      status: Schema.Literals([
        "BUILDING",
        "CRASHED",
        "DEPLOYING",
        "FAILED",
        "INITIALIZING",
        "NEEDS_APPROVAL",
        "QUEUED",
        "REMOVED",
        "REMOVING",
        "SKIPPED",
        "SLEEPING",
        "SUCCESS",
        "WAITING",
      ]),
      statusUpdatedAt: Schema.NullOr(Schema.String),
      suggestAddServiceDomain: Schema.Boolean,
      updatedAt: Schema.String,
      url: Schema.NullOr(Schema.String),
    }),
  ),
  nextCronRunAt: Schema.NullOr(Schema.String),
  nixpacksPlan: Schema.NullOr(Schema.Unknown),
  numReplicas: Schema.NullOr(Schema.Number),
  overlapSeconds: Schema.NullOr(Schema.Number),
  preDeployCommand: Schema.NullOr(Schema.Unknown),
  railpackInfo: Schema.NullOr(Schema.Unknown),
  railwayConfigFile: Schema.NullOr(Schema.String),
  region: Schema.NullOr(Schema.String),
  restartPolicyMaxRetries: Schema.Number,
  restartPolicyType: Schema.Literals(["ALWAYS", "NEVER", "ON_FAILURE"]),
  rootDirectory: Schema.NullOr(Schema.String),
  service: Schema.Struct({
    createdAt: Schema.String,
    deletedAt: Schema.NullOr(Schema.String),
    featureFlags: Schema.Array(
      Schema.Literals([
        "COPY_VOLUME_TO_ENVIRONMENT",
        "ENABLE_DOCKER_EXTENSION",
        "PLACEHOLDER",
        "SKIPPED_BUILDS",
        "USE_EXPRESS_DEPLOY",
        "USE_HA_STATIC_EGRESS",
        "USE_VM_RUNTIME",
      ]),
    ),
    hasHiddenRegistryCredentialsFromTemplate: Schema.Boolean,
    icon: Schema.NullOr(Schema.String),
    id: Schema.String,
    name: Schema.String,
    project: Schema.Struct({
      baseEnvironmentId: Schema.NullOr(Schema.String),
      botPrEnvironments: Schema.Boolean,
      createdAt: Schema.String,
      deletedAt: Schema.NullOr(Schema.String),
      description: Schema.NullOr(Schema.String),
      expiredAt: Schema.NullOr(Schema.String),
      featureFlags: Schema.Array(Schema.Literals(["PLACEHOLDER"])),
      focusedPrEnvironments: Schema.Boolean,
      id: Schema.String,
      isPublic: Schema.Boolean,
      isTempProject: Schema.Boolean,
      name: Schema.String,
      prDeploys: Schema.Boolean,
      primaryEnvironmentId: Schema.NullOr(Schema.String),
      subscriptionPlanLimit: Schema.Unknown,
      subscriptionType: Schema.Literals(["free", "hobby", "pro", "trial"]),
      teamId: Schema.NullOr(Schema.String),
      updatedAt: Schema.String,
      workspaceId: Schema.NullOr(Schema.String),
    }),
    projectId: Schema.String,
    templateId: Schema.NullOr(Schema.String),
    templateServiceId: Schema.NullOr(Schema.String),
    templateThreadSlug: Schema.NullOr(Schema.String),
    updatedAt: Schema.String,
  }),
  serviceId: Schema.String,
  serviceName: Schema.String,
  sleepApplication: Schema.NullOr(Schema.Boolean),
  source: Schema.NullOr(
    Schema.Struct({
      image: Schema.NullOr(Schema.String),
      repo: Schema.NullOr(Schema.String),
    }),
  ),
  startCommand: Schema.NullOr(Schema.String),
  updatedAt: Schema.String,
  upstreamUrl: Schema.NullOr(Schema.String),
  watchPatterns: Schema.Array(Schema.String),
}).pipe(T.ResponsePath("serviceInstance"));
export type GetServiceInstanceOutput = typeof GetServiceInstanceOutput.Type;

/**
 * Get a service instance belonging to a service and environment
 */
export const getServiceInstance = API.make(() => ({
  inputSchema: GetServiceInstanceInput,
  outputSchema: GetServiceInstanceOutput,
}));
