import * as Schema from "effect/Schema";
import { API } from "../client.ts";
import * as T from "../traits.ts";

const __document =
  "mutation userTermsUpdate {\n  userTermsUpdate {\n    agreedFairUse\n    apiTokenRateLimit {\n      remainingPoints\n      resetsAt\n    }\n    avatar\n    banReason\n    createdAt\n    email\n    featureFlags\n    flags\n    githubProviderId\n    githubUsername\n    has2FA\n    hasPasskeys\n    id\n    isAdmin\n    isConductor\n    isVerified\n    lastLogin\n    name\n    platformFeatureFlags\n    profile {\n      bio\n      isPublic\n      website\n    }\n    registrationStatus\n    riskLevel\n    termsAgreedOn\n    username\n    workspace {\n      adoptionHistory {\n        adoptionLevel\n        createdAt\n        deltaLevel\n        id\n        matchedIcpEmail\n        monthlyEstimatedUsage\n        numConfigFile\n        numCronSchedule\n        numDeploys\n        numEnvs\n        numFailedDeploys\n        numHealthcheck\n        numIconConfig\n        numRegion\n        numReplicas\n        numRootDirectory\n        numSeats\n        numServices\n        numVariables\n        numWatchPatterns\n        totalCores\n        totalDisk\n        totalNetwork\n        updatedAt\n      }\n      adoptionLevel\n      allowDeprecatedRegions\n      apiTokenRateLimit {\n        remainingPoints\n        resetsAt\n      }\n      avatar\n      banReason\n      createdAt\n      customer {\n        appliedCredits\n        billingEmail\n        creditBalance\n        currentUsage\n        defaultPaymentMethodId\n        hasExhaustedFreePlan\n        id\n        isPrepaying\n        isTrialing\n        isUsageSubscriber\n        isWithdrawingToCredits\n        remainingUsageCreditBalance\n        state\n        stripeCustomerId\n        supportedWithdrawalPlatforms\n        trialDaysRemaining\n      }\n      discordRole\n      has2FAEnforcement\n      hasAutomaticDiagnosis\n      hasGuardrailsAccess\n      hasSAML\n      id\n      members {\n        avatar\n        email\n        featureFlags\n        id\n        name\n        role\n        twoFactorAuthEnabled\n      }\n      name\n      partnerProfile {\n        category\n        description\n        slug\n        type\n        website\n      }\n      plan\n      preferredRegion\n      redactedDueTo2FAPending\n      referredUsers {\n        code\n        id\n        status\n      }\n      slackChannelId\n      subscriptionModel\n      subscriptionPlanLimit\n      supportTierOverride\n      team {\n        adoptionLevel\n        avatar\n        createdAt\n        id\n        name\n        preferredRegion\n        slackChannelId\n        supportTierOverride\n        updatedAt\n      }\n      updatedAt\n      usersWithout2FA\n    }\n    workspaces {\n      adoptionHistory {\n        adoptionLevel\n        createdAt\n        deltaLevel\n        id\n        matchedIcpEmail\n        monthlyEstimatedUsage\n        numConfigFile\n        numCronSchedule\n        numDeploys\n        numEnvs\n        numFailedDeploys\n        numHealthcheck\n        numIconConfig\n        numRegion\n        numReplicas\n        numRootDirectory\n        numSeats\n        numServices\n        numVariables\n        numWatchPatterns\n        totalCores\n        totalDisk\n        totalNetwork\n        updatedAt\n      }\n      adoptionLevel\n      allowDeprecatedRegions\n      apiTokenRateLimit {\n        remainingPoints\n        resetsAt\n      }\n      avatar\n      banReason\n      createdAt\n      customer {\n        appliedCredits\n        billingEmail\n        creditBalance\n        currentUsage\n        defaultPaymentMethodId\n        hasExhaustedFreePlan\n        id\n        isPrepaying\n        isTrialing\n        isUsageSubscriber\n        isWithdrawingToCredits\n        remainingUsageCreditBalance\n        state\n        stripeCustomerId\n        supportedWithdrawalPlatforms\n        trialDaysRemaining\n      }\n      discordRole\n      has2FAEnforcement\n      hasAutomaticDiagnosis\n      hasGuardrailsAccess\n      hasSAML\n      id\n      members {\n        avatar\n        email\n        featureFlags\n        id\n        name\n        role\n        twoFactorAuthEnabled\n      }\n      name\n      partnerProfile {\n        category\n        description\n        slug\n        type\n        website\n      }\n      plan\n      preferredRegion\n      redactedDueTo2FAPending\n      referredUsers {\n        code\n        id\n        status\n      }\n      slackChannelId\n      subscriptionModel\n      subscriptionPlanLimit\n      supportTierOverride\n      team {\n        adoptionLevel\n        avatar\n        createdAt\n        id\n        name\n        preferredRegion\n        slackChannelId\n        supportTierOverride\n        updatedAt\n      }\n      updatedAt\n      usersWithout2FA\n    }\n  }\n}";

// Input Schema (GraphQL variables)
export const UserTermsUpdateInput = Schema.Struct({}).pipe(
  T.Http({ method: "POST", path: "/graphql/v2" }),
  T.GraphQLOp({
    query: __document,
    operationName: "userTermsUpdate",
    type: "mutation",
  }),
);
export type UserTermsUpdateInput = typeof UserTermsUpdateInput.Type;

// Output Schema (GraphQL selection set)
export const UserTermsUpdateOutput = Schema.NullOr(
  Schema.Struct({
    agreedFairUse: Schema.Boolean,
    apiTokenRateLimit: Schema.NullOr(
      Schema.Struct({
        remainingPoints: Schema.Number,
        resetsAt: Schema.String,
      }),
    ),
    avatar: Schema.NullOr(Schema.String),
    banReason: Schema.NullOr(Schema.String),
    createdAt: Schema.String,
    email: Schema.String,
    featureFlags: Schema.Array(
      Schema.Literals([
        "AUDIT_LOGS",
        "BUCKET_FILE_BROWSER",
        "DEBUG_SMART_DIAGNOSIS",
        "IN_DASHBOARD_SUPPORT",
        "MAGIC_CONFIG",
        "POSTGRES_PGBOUNCER",
        "PRIORITY_BOARDING",
      ]),
    ),
    flags: Schema.Array(Schema.Literals(["BETA"])),
    githubProviderId: Schema.NullOr(Schema.String),
    githubUsername: Schema.NullOr(Schema.String),
    has2FA: Schema.Boolean,
    hasPasskeys: Schema.Boolean,
    id: Schema.String,
    isAdmin: Schema.Boolean,
    isConductor: Schema.Boolean,
    isVerified: Schema.Boolean,
    lastLogin: Schema.String,
    name: Schema.NullOr(Schema.String),
    platformFeatureFlags: Schema.Array(
      Schema.Literals([
        "AGENT_USAGE_BILLING",
        "ALLOW_REPLICA_METRICS",
        "ARCHIVER_V2_ROLLOUT",
        "BUILDER_V3_FOR_CLI_DEPLOYS",
        "BUILDER_V3_ROLLOUT_EXISTING_SERVICES",
        "BUILDER_V3_ROLLOUT_EXISTING_SERVICES_PRO",
        "BUILDER_V3_ROLLOUT_EXISTING_SERVICES_TRIAL",
        "BUILDER_V3_ROLLOUT_NEW_SERVICES",
        "BUILDER_V3_ROLLOUT_NEW_SERVICES_PRO",
        "BUILDER_V3_ROLLOUT_NEW_SERVICES_TRIAL",
        "COMPARE_CLICKHOUSE_METRICS",
        "CTRD_IMAGE_STORE_ROLLOUT",
        "DEMO_PERCENTAGE_ROLLOUT",
        "DISABLE_OAUTH_ACCESS_TOKENS",
        "FOCUSED_PR_ENVIRONMENTS",
        "INLINE_NOTIFICATION_PROCESSING",
        "IN_DASHBOARD_SUPPORT",
        "KAFKA_DEPLOYMENT_STATUS_CHANGES",
        "NEW_STRIPE_WEBHOOK_VERSION_ROLLOUT",
        "OAUTH_DCR_KILLSWITCH",
        "OAUTH_DEVICE_FLOW_KILLSWITCH",
        "RADAR_AUTO_EVALUATE",
        "REGION_REGISTRY_FROM_ORCHESTRATOR",
        "SERVICEINSTANCE_DATALOADER_FOR_STATIC_URL",
        "SPLIT_USAGE_QUERIES",
        "STRIPE_METERS_NEW_ACCOUNTS",
        "STRIPE_METERS_SHADOW_ENABLED",
        "UNIFIED_SNAPSHOT_AND_BUILD",
        "UNIFIED_SNAPSHOT_AND_BUILD_HOBBY",
        "UPDATED_VM_QUERIES",
        "USE_CLICKHOUSE_METRICS",
        "USE_GH_WEBHOOKS_FOR_CHANGE_DETECTION",
        "VM_TIME_RANGE_QUERY",
      ]),
    ),
    profile: Schema.NullOr(
      Schema.Struct({
        bio: Schema.NullOr(Schema.String),
        isPublic: Schema.Boolean,
        website: Schema.NullOr(Schema.String),
      }),
    ),
    registrationStatus: Schema.Literals([
      "ONBOARDED",
      "REGISTERED",
      "WAITLISTED",
    ]),
    riskLevel: Schema.NullOr(Schema.Number),
    termsAgreedOn: Schema.NullOr(Schema.String),
    username: Schema.NullOr(Schema.String),
    workspace: Schema.NullOr(
      Schema.Struct({
        adoptionHistory: Schema.Array(
          Schema.Struct({
            adoptionLevel: Schema.NullOr(Schema.Number),
            createdAt: Schema.String,
            deltaLevel: Schema.NullOr(Schema.Number),
            id: Schema.String,
            matchedIcpEmail: Schema.NullOr(Schema.String),
            monthlyEstimatedUsage: Schema.NullOr(Schema.Number),
            numConfigFile: Schema.Number,
            numCronSchedule: Schema.Number,
            numDeploys: Schema.Number,
            numEnvs: Schema.Number,
            numFailedDeploys: Schema.Number,
            numHealthcheck: Schema.Number,
            numIconConfig: Schema.Number,
            numRegion: Schema.Number,
            numReplicas: Schema.Number,
            numRootDirectory: Schema.Number,
            numSeats: Schema.Number,
            numServices: Schema.Number,
            numVariables: Schema.Number,
            numWatchPatterns: Schema.Number,
            totalCores: Schema.NullOr(Schema.Number),
            totalDisk: Schema.NullOr(Schema.Number),
            totalNetwork: Schema.NullOr(Schema.Number),
            updatedAt: Schema.String,
          }),
        ),
        adoptionLevel: Schema.Number,
        allowDeprecatedRegions: Schema.NullOr(Schema.Boolean),
        apiTokenRateLimit: Schema.NullOr(
          Schema.Struct({
            remainingPoints: Schema.Number,
            resetsAt: Schema.String,
          }),
        ),
        avatar: Schema.NullOr(Schema.String),
        banReason: Schema.NullOr(Schema.String),
        createdAt: Schema.String,
        customer: Schema.Struct({
          appliedCredits: Schema.Number,
          billingEmail: Schema.NullOr(Schema.String),
          creditBalance: Schema.Number,
          currentUsage: Schema.Number,
          defaultPaymentMethodId: Schema.NullOr(Schema.String),
          hasExhaustedFreePlan: Schema.Boolean,
          id: Schema.String,
          isPrepaying: Schema.Boolean,
          isTrialing: Schema.Boolean,
          isUsageSubscriber: Schema.Boolean,
          isWithdrawingToCredits: Schema.Boolean,
          remainingUsageCreditBalance: Schema.Number,
          state: Schema.Literals([
            "ACTIVE",
            "CANCELLED",
            "INACTIVE",
            "PAST_DUE",
            "UNPAID",
          ]),
          stripeCustomerId: Schema.String,
          supportedWithdrawalPlatforms: Schema.Array(
            Schema.Literals(["BMAC", "GITHUB", "PAYPAL", "STRIPE_CONNECT"]),
          ),
          trialDaysRemaining: Schema.Number,
        }),
        discordRole: Schema.NullOr(Schema.String),
        has2FAEnforcement: Schema.Boolean,
        hasAutomaticDiagnosis: Schema.Boolean,
        hasGuardrailsAccess: Schema.Boolean,
        hasSAML: Schema.Boolean,
        id: Schema.String,
        members: Schema.Array(
          Schema.Struct({
            avatar: Schema.NullOr(Schema.String),
            email: Schema.String,
            featureFlags: Schema.NullOr(
              Schema.Array(
                Schema.Literals([
                  "AUDIT_LOGS",
                  "BUCKET_FILE_BROWSER",
                  "DEBUG_SMART_DIAGNOSIS",
                  "IN_DASHBOARD_SUPPORT",
                  "MAGIC_CONFIG",
                  "POSTGRES_PGBOUNCER",
                  "PRIORITY_BOARDING",
                ]),
              ),
            ),
            id: Schema.String,
            name: Schema.NullOr(Schema.String),
            role: Schema.Literals(["ADMIN", "MEMBER", "VIEWER"]),
            twoFactorAuthEnabled: Schema.NullOr(Schema.Boolean),
          }),
        ),
        name: Schema.String,
        partnerProfile: Schema.NullOr(
          Schema.Struct({
            category: Schema.String,
            description: Schema.String,
            slug: Schema.String,
            type: Schema.Literals([
              "BASIC_PARTNER",
              "LIMITED_PARTNER",
              "TEMPLATE_MAINTAINER",
            ]),
            website: Schema.String,
          }),
        ),
        plan: Schema.Literals(["FREE", "HOBBY", "PRO"]),
        preferredRegion: Schema.NullOr(Schema.String),
        redactedDueTo2FAPending: Schema.Boolean,
        referredUsers: Schema.Array(
          Schema.Struct({
            code: Schema.String,
            id: Schema.String,
            status: Schema.Literals([
              "REFEREE_CREDITED",
              "REFERRER_CREDITED",
              "REGISTERED",
            ]),
          }),
        ),
        slackChannelId: Schema.NullOr(Schema.String),
        subscriptionModel: Schema.Literals(["FREE", "TEAM", "USER"]),
        subscriptionPlanLimit: Schema.NullOr(Schema.Unknown),
        supportTierOverride: Schema.NullOr(
          Schema.Literals(["BUSINESS_CLASS", "BUSINESS_CLASS_TRIAL"]),
        ),
        team: Schema.NullOr(
          Schema.Struct({
            adoptionLevel: Schema.Number,
            avatar: Schema.NullOr(Schema.String),
            createdAt: Schema.String,
            id: Schema.String,
            name: Schema.String,
            preferredRegion: Schema.NullOr(Schema.String),
            slackChannelId: Schema.NullOr(Schema.String),
            supportTierOverride: Schema.NullOr(
              Schema.Literals(["BUSINESS_CLASS", "BUSINESS_CLASS_TRIAL"]),
            ),
            updatedAt: Schema.String,
          }),
        ),
        updatedAt: Schema.String,
        usersWithout2FA: Schema.Array(Schema.String),
      }),
    ),
    workspaces: Schema.Array(
      Schema.Struct({
        adoptionHistory: Schema.Array(
          Schema.Struct({
            adoptionLevel: Schema.NullOr(Schema.Number),
            createdAt: Schema.String,
            deltaLevel: Schema.NullOr(Schema.Number),
            id: Schema.String,
            matchedIcpEmail: Schema.NullOr(Schema.String),
            monthlyEstimatedUsage: Schema.NullOr(Schema.Number),
            numConfigFile: Schema.Number,
            numCronSchedule: Schema.Number,
            numDeploys: Schema.Number,
            numEnvs: Schema.Number,
            numFailedDeploys: Schema.Number,
            numHealthcheck: Schema.Number,
            numIconConfig: Schema.Number,
            numRegion: Schema.Number,
            numReplicas: Schema.Number,
            numRootDirectory: Schema.Number,
            numSeats: Schema.Number,
            numServices: Schema.Number,
            numVariables: Schema.Number,
            numWatchPatterns: Schema.Number,
            totalCores: Schema.NullOr(Schema.Number),
            totalDisk: Schema.NullOr(Schema.Number),
            totalNetwork: Schema.NullOr(Schema.Number),
            updatedAt: Schema.String,
          }),
        ),
        adoptionLevel: Schema.Number,
        allowDeprecatedRegions: Schema.NullOr(Schema.Boolean),
        apiTokenRateLimit: Schema.NullOr(
          Schema.Struct({
            remainingPoints: Schema.Number,
            resetsAt: Schema.String,
          }),
        ),
        avatar: Schema.NullOr(Schema.String),
        banReason: Schema.NullOr(Schema.String),
        createdAt: Schema.String,
        customer: Schema.Struct({
          appliedCredits: Schema.Number,
          billingEmail: Schema.NullOr(Schema.String),
          creditBalance: Schema.Number,
          currentUsage: Schema.Number,
          defaultPaymentMethodId: Schema.NullOr(Schema.String),
          hasExhaustedFreePlan: Schema.Boolean,
          id: Schema.String,
          isPrepaying: Schema.Boolean,
          isTrialing: Schema.Boolean,
          isUsageSubscriber: Schema.Boolean,
          isWithdrawingToCredits: Schema.Boolean,
          remainingUsageCreditBalance: Schema.Number,
          state: Schema.Literals([
            "ACTIVE",
            "CANCELLED",
            "INACTIVE",
            "PAST_DUE",
            "UNPAID",
          ]),
          stripeCustomerId: Schema.String,
          supportedWithdrawalPlatforms: Schema.Array(
            Schema.Literals(["BMAC", "GITHUB", "PAYPAL", "STRIPE_CONNECT"]),
          ),
          trialDaysRemaining: Schema.Number,
        }),
        discordRole: Schema.NullOr(Schema.String),
        has2FAEnforcement: Schema.Boolean,
        hasAutomaticDiagnosis: Schema.Boolean,
        hasGuardrailsAccess: Schema.Boolean,
        hasSAML: Schema.Boolean,
        id: Schema.String,
        members: Schema.Array(
          Schema.Struct({
            avatar: Schema.NullOr(Schema.String),
            email: Schema.String,
            featureFlags: Schema.NullOr(
              Schema.Array(
                Schema.Literals([
                  "AUDIT_LOGS",
                  "BUCKET_FILE_BROWSER",
                  "DEBUG_SMART_DIAGNOSIS",
                  "IN_DASHBOARD_SUPPORT",
                  "MAGIC_CONFIG",
                  "POSTGRES_PGBOUNCER",
                  "PRIORITY_BOARDING",
                ]),
              ),
            ),
            id: Schema.String,
            name: Schema.NullOr(Schema.String),
            role: Schema.Literals(["ADMIN", "MEMBER", "VIEWER"]),
            twoFactorAuthEnabled: Schema.NullOr(Schema.Boolean),
          }),
        ),
        name: Schema.String,
        partnerProfile: Schema.NullOr(
          Schema.Struct({
            category: Schema.String,
            description: Schema.String,
            slug: Schema.String,
            type: Schema.Literals([
              "BASIC_PARTNER",
              "LIMITED_PARTNER",
              "TEMPLATE_MAINTAINER",
            ]),
            website: Schema.String,
          }),
        ),
        plan: Schema.Literals(["FREE", "HOBBY", "PRO"]),
        preferredRegion: Schema.NullOr(Schema.String),
        redactedDueTo2FAPending: Schema.Boolean,
        referredUsers: Schema.Array(
          Schema.Struct({
            code: Schema.String,
            id: Schema.String,
            status: Schema.Literals([
              "REFEREE_CREDITED",
              "REFERRER_CREDITED",
              "REGISTERED",
            ]),
          }),
        ),
        slackChannelId: Schema.NullOr(Schema.String),
        subscriptionModel: Schema.Literals(["FREE", "TEAM", "USER"]),
        subscriptionPlanLimit: Schema.NullOr(Schema.Unknown),
        supportTierOverride: Schema.NullOr(
          Schema.Literals(["BUSINESS_CLASS", "BUSINESS_CLASS_TRIAL"]),
        ),
        team: Schema.NullOr(
          Schema.Struct({
            adoptionLevel: Schema.Number,
            avatar: Schema.NullOr(Schema.String),
            createdAt: Schema.String,
            id: Schema.String,
            name: Schema.String,
            preferredRegion: Schema.NullOr(Schema.String),
            slackChannelId: Schema.NullOr(Schema.String),
            supportTierOverride: Schema.NullOr(
              Schema.Literals(["BUSINESS_CLASS", "BUSINESS_CLASS_TRIAL"]),
            ),
            updatedAt: Schema.String,
          }),
        ),
        updatedAt: Schema.String,
        usersWithout2FA: Schema.Array(Schema.String),
      }),
    ),
  }),
).pipe(T.ResponsePath("userTermsUpdate"));
export type UserTermsUpdateOutput = typeof UserTermsUpdateOutput.Type;

/**
 * Update date of TermsAgreedOn
 */
export const userTermsUpdate = API.make(() => ({
  inputSchema: UserTermsUpdateInput,
  outputSchema: UserTermsUpdateOutput,
}));
