import * as Schema from "effect/Schema";
import { API } from "../client.ts";
import * as T from "../traits.ts";
import {
  BadRequest,
  Forbidden,
  NotFound,
  UnprocessableEntity,
} from "../errors.ts";
import { SensitiveString } from "../sensitive.ts";

// Input Schema
export const CheckoutsclientConfirmInput =
  /*@__PURE__*/ /*#__PURE__*/ Schema.Struct({
    client_secret: Schema.String.pipe(T.PathParam()),
    custom_field_data: Schema.optional(
      Schema.Record(Schema.String, Schema.Unknown),
    ),
    product_id: Schema.optional(Schema.NullOr(Schema.String)),
    product_price_id: Schema.optional(Schema.NullOr(Schema.String)),
    amount: Schema.optional(Schema.NullOr(Schema.Number)),
    seats: Schema.optional(Schema.NullOr(Schema.Number)),
    is_business_customer: Schema.optional(Schema.NullOr(Schema.Boolean)),
    customer_name: Schema.optional(Schema.NullOr(Schema.String)),
    customer_email: Schema.optional(Schema.NullOr(Schema.String)),
    customer_billing_name: Schema.optional(Schema.NullOr(Schema.String)),
    customer_billing_address: Schema.optional(
      Schema.NullOr(
        Schema.Struct({
          line1: Schema.optional(Schema.NullOr(Schema.String)),
          line2: Schema.optional(Schema.NullOr(Schema.String)),
          postal_code: Schema.optional(Schema.NullOr(Schema.String)),
          city: Schema.optional(Schema.NullOr(Schema.String)),
          state: Schema.optional(Schema.NullOr(Schema.String)),
          country: Schema.Literals([
            "AD",
            "AE",
            "AF",
            "AG",
            "AI",
            "AL",
            "AM",
            "AO",
            "AQ",
            "AR",
            "AS",
            "AT",
            "AU",
            "AW",
            "AX",
            "AZ",
            "BA",
            "BB",
            "BD",
            "BE",
            "BF",
            "BG",
            "BH",
            "BI",
            "BJ",
            "BL",
            "BM",
            "BN",
            "BO",
            "BQ",
            "BR",
            "BS",
            "BT",
            "BV",
            "BW",
            "BY",
            "BZ",
            "CA",
            "CC",
            "CD",
            "CF",
            "CG",
            "CH",
            "CI",
            "CK",
            "CL",
            "CM",
            "CN",
            "CO",
            "CR",
            "CV",
            "CW",
            "CX",
            "CY",
            "CZ",
            "DE",
            "DJ",
            "DK",
            "DM",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "EH",
            "ER",
            "ES",
            "ET",
            "FI",
            "FJ",
            "FK",
            "FM",
            "FO",
            "FR",
            "GA",
            "GB",
            "GD",
            "GE",
            "GF",
            "GG",
            "GH",
            "GI",
            "GL",
            "GM",
            "GN",
            "GP",
            "GQ",
            "GR",
            "GS",
            "GT",
            "GU",
            "GW",
            "GY",
            "HK",
            "HM",
            "HN",
            "HR",
            "HT",
            "HU",
            "ID",
            "IE",
            "IL",
            "IM",
            "IN",
            "IO",
            "IQ",
            "IS",
            "IT",
            "JE",
            "JM",
            "JO",
            "JP",
            "KE",
            "KG",
            "KH",
            "KI",
            "KM",
            "KN",
            "KR",
            "KW",
            "KY",
            "KZ",
            "LA",
            "LB",
            "LC",
            "LI",
            "LK",
            "LR",
            "LS",
            "LT",
            "LU",
            "LV",
            "LY",
            "MA",
            "MC",
            "MD",
            "ME",
            "MF",
            "MG",
            "MH",
            "MK",
            "ML",
            "MM",
            "MN",
            "MO",
            "MP",
            "MQ",
            "MR",
            "MS",
            "MT",
            "MU",
            "MV",
            "MW",
            "MX",
            "MY",
            "MZ",
            "NA",
            "NC",
            "NE",
            "NF",
            "NG",
            "NI",
            "NL",
            "NO",
            "NP",
            "NR",
            "NU",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PF",
            "PG",
            "PH",
            "PK",
            "PL",
            "PM",
            "PN",
            "PR",
            "PS",
            "PT",
            "PW",
            "PY",
            "QA",
            "RE",
            "RO",
            "RS",
            "RW",
            "SA",
            "SB",
            "SC",
            "SD",
            "SE",
            "SG",
            "SH",
            "SI",
            "SJ",
            "SK",
            "SL",
            "SM",
            "SN",
            "SO",
            "SR",
            "SS",
            "ST",
            "SV",
            "SX",
            "SZ",
            "TC",
            "TD",
            "TF",
            "TG",
            "TH",
            "TJ",
            "TK",
            "TL",
            "TM",
            "TN",
            "TO",
            "TR",
            "TT",
            "TV",
            "TW",
            "TZ",
            "UA",
            "UG",
            "UM",
            "US",
            "UY",
            "UZ",
            "VA",
            "VC",
            "VE",
            "VG",
            "VI",
            "VN",
            "VU",
            "WF",
            "WS",
            "YE",
            "YT",
            "ZA",
            "ZM",
            "ZW",
          ]),
        }),
      ),
    ),
    customer_tax_id: Schema.optional(Schema.NullOr(Schema.String)),
    locale: Schema.optional(Schema.NullOr(Schema.String)),
    discount_code: Schema.optional(Schema.NullOr(Schema.String)),
    allow_trial: Schema.optional(Schema.NullOr(Schema.Literal(false))),
    confirmation_token_id: Schema.optional(Schema.NullOr(Schema.String)),
  }).pipe(
    T.Http({
      method: "POST",
      path: "/v1/checkouts/client/{client_secret}/confirm",
    }),
  );
export type CheckoutsclientConfirmInput =
  typeof CheckoutsclientConfirmInput.Type;

// Output Schema
export const CheckoutsclientConfirmOutput =
  /*@__PURE__*/ /*#__PURE__*/ Schema.Struct({
    id: Schema.String,
    created_at: Schema.String,
    modified_at: Schema.NullOr(Schema.String),
    custom_field_data: Schema.optional(
      Schema.Record(Schema.String, Schema.Unknown),
    ),
    payment_processor: Schema.Literals(["stripe"]),
    status: Schema.Literal("confirmed"),
    client_secret: SensitiveString,
    url: Schema.String,
    expires_at: Schema.String,
    success_url: Schema.String,
    return_url: Schema.NullOr(Schema.String),
    embed_origin: Schema.NullOr(Schema.String),
    amount: Schema.Number,
    seats: Schema.optional(Schema.NullOr(Schema.Number)),
    min_seats: Schema.optional(Schema.NullOr(Schema.Number)),
    max_seats: Schema.optional(Schema.NullOr(Schema.Number)),
    discount_amount: Schema.Number,
    net_amount: Schema.Number,
    tax_amount: Schema.NullOr(Schema.Number),
    tax_behavior: Schema.NullOr(Schema.Literals(["inclusive", "exclusive"])),
    total_amount: Schema.Number,
    currency: Schema.String,
    allow_trial: Schema.NullOr(Schema.Boolean),
    active_trial_interval: Schema.NullOr(
      Schema.Literals(["day", "week", "month", "year"]),
    ),
    active_trial_interval_count: Schema.NullOr(Schema.Number),
    trial_end: Schema.NullOr(Schema.String),
    organization_id: Schema.String,
    product_id: Schema.NullOr(Schema.String),
    product_price_id: Schema.NullOr(Schema.String),
    discount_id: Schema.NullOr(Schema.String),
    allow_discount_codes: Schema.Boolean,
    require_billing_address: Schema.Boolean,
    is_discount_applicable: Schema.Boolean,
    is_free_product_price: Schema.Boolean,
    is_payment_required: Schema.Boolean,
    is_payment_setup_required: Schema.Boolean,
    is_payment_form_required: Schema.Boolean,
    customer_id: Schema.NullOr(Schema.String),
    is_business_customer: Schema.Boolean,
    customer_name: Schema.NullOr(Schema.String),
    customer_email: Schema.NullOr(Schema.String),
    customer_ip_address: Schema.NullOr(Schema.String),
    customer_billing_name: Schema.NullOr(Schema.String),
    customer_billing_address: Schema.NullOr(
      Schema.Struct({
        line1: Schema.optional(Schema.NullOr(Schema.String)),
        line2: Schema.optional(Schema.NullOr(Schema.String)),
        postal_code: Schema.optional(Schema.NullOr(Schema.String)),
        city: Schema.optional(Schema.NullOr(Schema.String)),
        state: Schema.optional(Schema.NullOr(Schema.String)),
        country: Schema.Literals([
          "AD",
          "AE",
          "AF",
          "AG",
          "AI",
          "AL",
          "AM",
          "AO",
          "AQ",
          "AR",
          "AS",
          "AT",
          "AU",
          "AW",
          "AX",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BL",
          "BM",
          "BN",
          "BO",
          "BQ",
          "BR",
          "BS",
          "BT",
          "BV",
          "BW",
          "BY",
          "BZ",
          "CA",
          "CC",
          "CD",
          "CF",
          "CG",
          "CH",
          "CI",
          "CK",
          "CL",
          "CM",
          "CN",
          "CO",
          "CR",
          "CU",
          "CV",
          "CW",
          "CX",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "EH",
          "ER",
          "ES",
          "ET",
          "FI",
          "FJ",
          "FK",
          "FM",
          "FO",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GF",
          "GG",
          "GH",
          "GI",
          "GL",
          "GM",
          "GN",
          "GP",
          "GQ",
          "GR",
          "GS",
          "GT",
          "GU",
          "GW",
          "GY",
          "HK",
          "HM",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IM",
          "IN",
          "IO",
          "IQ",
          "IR",
          "IS",
          "IT",
          "JE",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KP",
          "KR",
          "KW",
          "KY",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "LY",
          "MA",
          "MC",
          "MD",
          "ME",
          "MF",
          "MG",
          "MH",
          "MK",
          "ML",
          "MM",
          "MN",
          "MO",
          "MP",
          "MQ",
          "MR",
          "MS",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NC",
          "NE",
          "NF",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NU",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PF",
          "PG",
          "PH",
          "PK",
          "PL",
          "PM",
          "PN",
          "PR",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RE",
          "RO",
          "RS",
          "RU",
          "RW",
          "SA",
          "SB",
          "SC",
          "SD",
          "SE",
          "SG",
          "SH",
          "SI",
          "SJ",
          "SK",
          "SL",
          "SM",
          "SN",
          "SO",
          "SR",
          "SS",
          "ST",
          "SV",
          "SX",
          "SY",
          "SZ",
          "TC",
          "TD",
          "TF",
          "TG",
          "TH",
          "TJ",
          "TK",
          "TL",
          "TM",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "UM",
          "US",
          "UY",
          "UZ",
          "VA",
          "VC",
          "VE",
          "VG",
          "VI",
          "VN",
          "VU",
          "WF",
          "WS",
          "YE",
          "YT",
          "ZA",
          "ZM",
          "ZW",
        ]),
      }),
    ),
    customer_tax_id: Schema.NullOr(Schema.String),
    locale: Schema.optional(Schema.NullOr(Schema.String)),
    payment_processor_metadata: Schema.Record(Schema.String, Schema.String),
    billing_address_fields: Schema.Struct({
      country: Schema.Literals(["required", "optional", "disabled"]),
      state: Schema.Literals(["required", "optional", "disabled"]),
      city: Schema.Literals(["required", "optional", "disabled"]),
      postal_code: Schema.Literals(["required", "optional", "disabled"]),
      line1: Schema.Literals(["required", "optional", "disabled"]),
      line2: Schema.Literals(["required", "optional", "disabled"]),
    }),
    products: Schema.Array(
      Schema.Struct({
        id: Schema.String,
        created_at: Schema.String,
        modified_at: Schema.NullOr(Schema.String),
        trial_interval: Schema.NullOr(
          Schema.Literals(["day", "week", "month", "year"]),
        ),
        trial_interval_count: Schema.NullOr(Schema.Number),
        name: Schema.String,
        description: Schema.NullOr(Schema.String),
        visibility: Schema.Literals(["draft", "private", "public"]),
        recurring_interval: Schema.NullOr(
          Schema.Literals(["day", "week", "month", "year"]),
        ),
        recurring_interval_count: Schema.NullOr(Schema.Number),
        is_recurring: Schema.Boolean,
        is_archived: Schema.Boolean,
        organization_id: Schema.String,
        prices: Schema.Array(Schema.Unknown),
        benefits: Schema.Array(
          Schema.Struct({
            id: Schema.String,
            created_at: Schema.String,
            modified_at: Schema.NullOr(Schema.String),
            type: Schema.Literals([
              "custom",
              "discord",
              "github_repository",
              "downloadables",
              "license_keys",
              "meter_credit",
              "feature_flag",
            ]),
            description: Schema.String,
            selectable: Schema.Boolean,
            deletable: Schema.Boolean,
            is_deleted: Schema.Boolean,
            organization_id: Schema.String,
          }),
        ),
        medias: Schema.Array(
          Schema.Struct({
            id: Schema.String,
            organization_id: Schema.String,
            name: Schema.String,
            path: Schema.String,
            mime_type: Schema.String,
            size: Schema.Number,
            storage_version: Schema.NullOr(Schema.String),
            checksum_etag: Schema.NullOr(Schema.String),
            checksum_sha256_base64: Schema.NullOr(Schema.String),
            checksum_sha256_hex: Schema.NullOr(Schema.String),
            last_modified_at: Schema.NullOr(Schema.String),
            version: Schema.NullOr(Schema.String),
            service: Schema.Literal("product_media"),
            is_uploaded: Schema.Boolean,
            created_at: Schema.String,
            size_readable: Schema.String,
            public_url: Schema.String,
          }),
        ),
      }),
    ),
    product: Schema.NullOr(
      Schema.Struct({
        id: Schema.String,
        created_at: Schema.String,
        modified_at: Schema.NullOr(Schema.String),
        trial_interval: Schema.NullOr(
          Schema.Literals(["day", "week", "month", "year"]),
        ),
        trial_interval_count: Schema.NullOr(Schema.Number),
        name: Schema.String,
        description: Schema.NullOr(Schema.String),
        visibility: Schema.Literals(["draft", "private", "public"]),
        recurring_interval: Schema.NullOr(
          Schema.Literals(["day", "week", "month", "year"]),
        ),
        recurring_interval_count: Schema.NullOr(Schema.Number),
        is_recurring: Schema.Boolean,
        is_archived: Schema.Boolean,
        organization_id: Schema.String,
        prices: Schema.Array(Schema.Unknown),
        benefits: Schema.Array(
          Schema.Struct({
            id: Schema.String,
            created_at: Schema.String,
            modified_at: Schema.NullOr(Schema.String),
            type: Schema.Literals([
              "custom",
              "discord",
              "github_repository",
              "downloadables",
              "license_keys",
              "meter_credit",
              "feature_flag",
            ]),
            description: Schema.String,
            selectable: Schema.Boolean,
            deletable: Schema.Boolean,
            is_deleted: Schema.Boolean,
            organization_id: Schema.String,
          }),
        ),
        medias: Schema.Array(
          Schema.Struct({
            id: Schema.String,
            organization_id: Schema.String,
            name: Schema.String,
            path: Schema.String,
            mime_type: Schema.String,
            size: Schema.Number,
            storage_version: Schema.NullOr(Schema.String),
            checksum_etag: Schema.NullOr(Schema.String),
            checksum_sha256_base64: Schema.NullOr(Schema.String),
            checksum_sha256_hex: Schema.NullOr(Schema.String),
            last_modified_at: Schema.NullOr(Schema.String),
            version: Schema.NullOr(Schema.String),
            service: Schema.Literal("product_media"),
            is_uploaded: Schema.Boolean,
            created_at: Schema.String,
            size_readable: Schema.String,
            public_url: Schema.String,
          }),
        ),
      }),
    ),
    product_price: Schema.NullOr(Schema.Unknown),
    prices: Schema.NullOr(
      Schema.Record(Schema.String, Schema.Array(Schema.Unknown)),
    ),
    discount: Schema.NullOr(Schema.Unknown),
    organization: Schema.Struct({
      created_at: Schema.String,
      modified_at: Schema.NullOr(Schema.String),
      id: Schema.String,
      name: Schema.String,
      slug: Schema.String,
      avatar_url: Schema.NullOr(Schema.String),
      proration_behavior: Schema.Literals([
        "invoice",
        "prorate",
        "next_period",
        "reset",
      ]),
      allow_customer_updates: Schema.Boolean,
    }),
    attached_custom_fields: Schema.NullOr(
      Schema.Array(
        Schema.Struct({
          custom_field_id: Schema.String,
          custom_field: Schema.Unknown,
          order: Schema.Number,
          required: Schema.Boolean,
        }),
      ),
    ),
    customer_session_token: Schema.NullOr(Schema.String),
  });
export type CheckoutsclientConfirmOutput =
  typeof CheckoutsclientConfirmOutput.Type;

// The operation
/**
 * Confirm Checkout Session from Client
 *
 * Confirm a checkout session by client secret.
 * Orders and subscriptions will be processed.
 *
 * @param client_secret - The checkout session client secret.
 */
export const checkoutsclientConfirm = /*@__PURE__*/ /*#__PURE__*/ API.make(
  () => ({
    inputSchema: CheckoutsclientConfirmInput,
    outputSchema: CheckoutsclientConfirmOutput,
    errors: [BadRequest, Forbidden, NotFound, UnprocessableEntity] as const,
  }),
);
