import * as Schema from "effect/Schema";
import { API } from "../client.ts";
import * as T from "../traits.ts";
import { NotFound, UnprocessableEntity } from "../errors.ts";

// Input Schema
export const CustomerPortallicenseKeyslistInput =
  /*@__PURE__*/ /*#__PURE__*/ Schema.Struct({
    benefit_id: Schema.optional(Schema.String).pipe(T.QueryParam()),
    page: Schema.optional(Schema.Number).pipe(T.QueryParam()),
    limit: Schema.optional(Schema.Number).pipe(T.QueryParam()),
  }).pipe(T.Http({ method: "GET", path: "/v1/customer-portal/license-keys/" }));
export type CustomerPortallicenseKeyslistInput =
  typeof CustomerPortallicenseKeyslistInput.Type;

// Output Schema
export const CustomerPortallicenseKeyslistOutput =
  /*@__PURE__*/ /*#__PURE__*/ Schema.Struct({
    items: Schema.Array(
      Schema.Struct({
        id: Schema.String,
        created_at: Schema.String,
        modified_at: Schema.NullOr(Schema.String),
        organization_id: Schema.String,
        customer_id: Schema.String,
        customer: Schema.Struct({
          id: Schema.String,
          created_at: Schema.String,
          modified_at: Schema.NullOr(Schema.String),
          metadata: Schema.Record(Schema.String, Schema.Unknown),
          external_id: Schema.optional(Schema.NullOr(Schema.String)),
          email: Schema.optional(Schema.NullOr(Schema.String)),
          email_verified: Schema.Boolean,
          type: Schema.Literals(["individual", "team"]),
          name: Schema.NullOr(Schema.String),
          billing_address: Schema.NullOr(
            Schema.Struct({
              line1: Schema.optional(Schema.NullOr(Schema.String)),
              line2: Schema.optional(Schema.NullOr(Schema.String)),
              postal_code: Schema.optional(Schema.NullOr(Schema.String)),
              city: Schema.optional(Schema.NullOr(Schema.String)),
              state: Schema.optional(Schema.NullOr(Schema.String)),
              country: Schema.Literals([
                "AD",
                "AE",
                "AF",
                "AG",
                "AI",
                "AL",
                "AM",
                "AO",
                "AQ",
                "AR",
                "AS",
                "AT",
                "AU",
                "AW",
                "AX",
                "AZ",
                "BA",
                "BB",
                "BD",
                "BE",
                "BF",
                "BG",
                "BH",
                "BI",
                "BJ",
                "BL",
                "BM",
                "BN",
                "BO",
                "BQ",
                "BR",
                "BS",
                "BT",
                "BV",
                "BW",
                "BY",
                "BZ",
                "CA",
                "CC",
                "CD",
                "CF",
                "CG",
                "CH",
                "CI",
                "CK",
                "CL",
                "CM",
                "CN",
                "CO",
                "CR",
                "CU",
                "CV",
                "CW",
                "CX",
                "CY",
                "CZ",
                "DE",
                "DJ",
                "DK",
                "DM",
                "DO",
                "DZ",
                "EC",
                "EE",
                "EG",
                "EH",
                "ER",
                "ES",
                "ET",
                "FI",
                "FJ",
                "FK",
                "FM",
                "FO",
                "FR",
                "GA",
                "GB",
                "GD",
                "GE",
                "GF",
                "GG",
                "GH",
                "GI",
                "GL",
                "GM",
                "GN",
                "GP",
                "GQ",
                "GR",
                "GS",
                "GT",
                "GU",
                "GW",
                "GY",
                "HK",
                "HM",
                "HN",
                "HR",
                "HT",
                "HU",
                "ID",
                "IE",
                "IL",
                "IM",
                "IN",
                "IO",
                "IQ",
                "IR",
                "IS",
                "IT",
                "JE",
                "JM",
                "JO",
                "JP",
                "KE",
                "KG",
                "KH",
                "KI",
                "KM",
                "KN",
                "KP",
                "KR",
                "KW",
                "KY",
                "KZ",
                "LA",
                "LB",
                "LC",
                "LI",
                "LK",
                "LR",
                "LS",
                "LT",
                "LU",
                "LV",
                "LY",
                "MA",
                "MC",
                "MD",
                "ME",
                "MF",
                "MG",
                "MH",
                "MK",
                "ML",
                "MM",
                "MN",
                "MO",
                "MP",
                "MQ",
                "MR",
                "MS",
                "MT",
                "MU",
                "MV",
                "MW",
                "MX",
                "MY",
                "MZ",
                "NA",
                "NC",
                "NE",
                "NF",
                "NG",
                "NI",
                "NL",
                "NO",
                "NP",
                "NR",
                "NU",
                "NZ",
                "OM",
                "PA",
                "PE",
                "PF",
                "PG",
                "PH",
                "PK",
                "PL",
                "PM",
                "PN",
                "PR",
                "PS",
                "PT",
                "PW",
                "PY",
                "QA",
                "RE",
                "RO",
                "RS",
                "RU",
                "RW",
                "SA",
                "SB",
                "SC",
                "SD",
                "SE",
                "SG",
                "SH",
                "SI",
                "SJ",
                "SK",
                "SL",
                "SM",
                "SN",
                "SO",
                "SR",
                "SS",
                "ST",
                "SV",
                "SX",
                "SY",
                "SZ",
                "TC",
                "TD",
                "TF",
                "TG",
                "TH",
                "TJ",
                "TK",
                "TL",
                "TM",
                "TN",
                "TO",
                "TR",
                "TT",
                "TV",
                "TW",
                "TZ",
                "UA",
                "UG",
                "UM",
                "US",
                "UY",
                "UZ",
                "VA",
                "VC",
                "VE",
                "VG",
                "VI",
                "VN",
                "VU",
                "WF",
                "WS",
                "YE",
                "YT",
                "ZA",
                "ZM",
                "ZW",
              ]),
            }),
          ),
          tax_id: Schema.NullOr(Schema.Array(Schema.Unknown)),
          locale: Schema.optional(Schema.NullOr(Schema.String)),
          organization_id: Schema.String,
          deleted_at: Schema.NullOr(Schema.String),
          avatar_url: Schema.String,
        }),
        benefit_id: Schema.String,
        key: Schema.String,
        display_key: Schema.String,
        status: Schema.Literals(["granted", "revoked", "disabled"]),
        limit_activations: Schema.NullOr(Schema.Number),
        usage: Schema.Number,
        limit_usage: Schema.NullOr(Schema.Number),
        validations: Schema.Number,
        last_validated_at: Schema.NullOr(Schema.String),
        expires_at: Schema.NullOr(Schema.String),
      }),
    ),
    pagination: Schema.Struct({
      total_count: Schema.Number,
      max_page: Schema.Number,
    }),
  });
export type CustomerPortallicenseKeyslistOutput =
  typeof CustomerPortallicenseKeyslistOutput.Type;

// The operation
/**
 * List License Keys
 *
 * **Scopes**: `customer_portal:read` `customer_portal:write`
 *
 * @param benefit_id - Filter by a specific benefit
 * @param page - Page number, defaults to 1.
 * @param limit - Size of a page, defaults to 10. Maximum is 100.
 */
export const customerPortallicenseKeyslist =
  /*@__PURE__*/ /*#__PURE__*/ API.make(() => ({
    inputSchema: CustomerPortallicenseKeyslistInput,
    outputSchema: CustomerPortallicenseKeyslistOutput,
    errors: [NotFound, UnprocessableEntity] as const,
  }));
