import * as Schema from "effect/Schema";
import { API } from "../client.ts";
import * as T from "../traits.ts";
import { UnprocessableEntity } from "../errors.ts";

// Input Schema
export const MetricsgetInput = /*@__PURE__*/ /*#__PURE__*/ Schema.Struct({
  start_date: Schema.String,
  end_date: Schema.String,
  timezone: Schema.optional(
    Schema.Literals([
      "Africa/Abidjan",
      "Africa/Accra",
      "Africa/Addis_Ababa",
      "Africa/Algiers",
      "Africa/Asmara",
      "Africa/Asmera",
      "Africa/Bamako",
      "Africa/Bangui",
      "Africa/Banjul",
      "Africa/Bissau",
      "Africa/Blantyre",
      "Africa/Brazzaville",
      "Africa/Bujumbura",
      "Africa/Cairo",
      "Africa/Casablanca",
      "Africa/Ceuta",
      "Africa/Conakry",
      "Africa/Dakar",
      "Africa/Dar_es_Salaam",
      "Africa/Djibouti",
      "Africa/Douala",
      "Africa/El_Aaiun",
      "Africa/Freetown",
      "Africa/Gaborone",
      "Africa/Harare",
      "Africa/Johannesburg",
      "Africa/Juba",
      "Africa/Kampala",
      "Africa/Khartoum",
      "Africa/Kigali",
      "Africa/Kinshasa",
      "Africa/Lagos",
      "Africa/Libreville",
      "Africa/Lome",
      "Africa/Luanda",
      "Africa/Lubumbashi",
      "Africa/Lusaka",
      "Africa/Malabo",
      "Africa/Maputo",
      "Africa/Maseru",
      "Africa/Mbabane",
      "Africa/Mogadishu",
      "Africa/Monrovia",
      "Africa/Nairobi",
      "Africa/Ndjamena",
      "Africa/Niamey",
      "Africa/Nouakchott",
      "Africa/Ouagadougou",
      "Africa/Porto-Novo",
      "Africa/Sao_Tome",
      "Africa/Timbuktu",
      "Africa/Tripoli",
      "Africa/Tunis",
      "Africa/Windhoek",
      "America/Adak",
      "America/Anchorage",
      "America/Anguilla",
      "America/Antigua",
      "America/Araguaina",
      "America/Argentina/Buenos_Aires",
      "America/Argentina/Catamarca",
      "America/Argentina/ComodRivadavia",
      "America/Argentina/Cordoba",
      "America/Argentina/Jujuy",
      "America/Argentina/La_Rioja",
      "America/Argentina/Mendoza",
      "America/Argentina/Rio_Gallegos",
      "America/Argentina/Salta",
      "America/Argentina/San_Juan",
      "America/Argentina/San_Luis",
      "America/Argentina/Tucuman",
      "America/Argentina/Ushuaia",
      "America/Aruba",
      "America/Asuncion",
      "America/Atikokan",
      "America/Atka",
      "America/Bahia",
      "America/Bahia_Banderas",
      "America/Barbados",
      "America/Belem",
      "America/Belize",
      "America/Blanc-Sablon",
      "America/Boa_Vista",
      "America/Bogota",
      "America/Boise",
      "America/Buenos_Aires",
      "America/Cambridge_Bay",
      "America/Campo_Grande",
      "America/Cancun",
      "America/Caracas",
      "America/Catamarca",
      "America/Cayenne",
      "America/Cayman",
      "America/Chicago",
      "America/Chihuahua",
      "America/Ciudad_Juarez",
      "America/Coral_Harbour",
      "America/Cordoba",
      "America/Costa_Rica",
      "America/Coyhaique",
      "America/Creston",
      "America/Cuiaba",
      "America/Curacao",
      "America/Danmarkshavn",
      "America/Dawson",
      "America/Dawson_Creek",
      "America/Denver",
      "America/Detroit",
      "America/Dominica",
      "America/Edmonton",
      "America/Eirunepe",
      "America/El_Salvador",
      "America/Ensenada",
      "America/Fort_Nelson",
      "America/Fort_Wayne",
      "America/Fortaleza",
      "America/Glace_Bay",
      "America/Godthab",
      "America/Goose_Bay",
      "America/Grand_Turk",
      "America/Grenada",
      "America/Guadeloupe",
      "America/Guatemala",
      "America/Guayaquil",
      "America/Guyana",
      "America/Halifax",
      "America/Havana",
      "America/Hermosillo",
      "America/Indiana/Indianapolis",
      "America/Indiana/Knox",
      "America/Indiana/Marengo",
      "America/Indiana/Petersburg",
      "America/Indiana/Tell_City",
      "America/Indiana/Vevay",
      "America/Indiana/Vincennes",
      "America/Indiana/Winamac",
      "America/Indianapolis",
      "America/Inuvik",
      "America/Iqaluit",
      "America/Jamaica",
      "America/Jujuy",
      "America/Juneau",
      "America/Kentucky/Louisville",
      "America/Kentucky/Monticello",
      "America/Knox_IN",
      "America/Kralendijk",
      "America/La_Paz",
      "America/Lima",
      "America/Los_Angeles",
      "America/Louisville",
      "America/Lower_Princes",
      "America/Maceio",
      "America/Managua",
      "America/Manaus",
      "America/Marigot",
      "America/Martinique",
      "America/Matamoros",
      "America/Mazatlan",
      "America/Mendoza",
      "America/Menominee",
      "America/Merida",
      "America/Metlakatla",
      "America/Mexico_City",
      "America/Miquelon",
      "America/Moncton",
      "America/Monterrey",
      "America/Montevideo",
      "America/Montreal",
      "America/Montserrat",
      "America/Nassau",
      "America/New_York",
      "America/Nipigon",
      "America/Nome",
      "America/Noronha",
      "America/North_Dakota/Beulah",
      "America/North_Dakota/Center",
      "America/North_Dakota/New_Salem",
      "America/Nuuk",
      "America/Ojinaga",
      "America/Panama",
      "America/Pangnirtung",
      "America/Paramaribo",
      "America/Phoenix",
      "America/Port-au-Prince",
      "America/Port_of_Spain",
      "America/Porto_Acre",
      "America/Porto_Velho",
      "America/Puerto_Rico",
      "America/Punta_Arenas",
      "America/Rainy_River",
      "America/Rankin_Inlet",
      "America/Recife",
      "America/Regina",
      "America/Resolute",
      "America/Rio_Branco",
      "America/Rosario",
      "America/Santa_Isabel",
      "America/Santarem",
      "America/Santiago",
      "America/Santo_Domingo",
      "America/Sao_Paulo",
      "America/Scoresbysund",
      "America/Shiprock",
      "America/Sitka",
      "America/St_Barthelemy",
      "America/St_Johns",
      "America/St_Kitts",
      "America/St_Lucia",
      "America/St_Thomas",
      "America/St_Vincent",
      "America/Swift_Current",
      "America/Tegucigalpa",
      "America/Thule",
      "America/Thunder_Bay",
      "America/Tijuana",
      "America/Toronto",
      "America/Tortola",
      "America/Vancouver",
      "America/Virgin",
      "America/Whitehorse",
      "America/Winnipeg",
      "America/Yakutat",
      "America/Yellowknife",
      "Antarctica/Casey",
      "Antarctica/Davis",
      "Antarctica/DumontDUrville",
      "Antarctica/Macquarie",
      "Antarctica/Mawson",
      "Antarctica/McMurdo",
      "Antarctica/Palmer",
      "Antarctica/Rothera",
      "Antarctica/South_Pole",
      "Antarctica/Syowa",
      "Antarctica/Troll",
      "Antarctica/Vostok",
      "Arctic/Longyearbyen",
      "Asia/Aden",
      "Asia/Almaty",
      "Asia/Amman",
      "Asia/Anadyr",
      "Asia/Aqtau",
      "Asia/Aqtobe",
      "Asia/Ashgabat",
      "Asia/Ashkhabad",
      "Asia/Atyrau",
      "Asia/Baghdad",
      "Asia/Bahrain",
      "Asia/Baku",
      "Asia/Bangkok",
      "Asia/Barnaul",
      "Asia/Beirut",
      "Asia/Bishkek",
      "Asia/Brunei",
      "Asia/Calcutta",
      "Asia/Chita",
      "Asia/Choibalsan",
      "Asia/Chongqing",
      "Asia/Chungking",
      "Asia/Colombo",
      "Asia/Dacca",
      "Asia/Damascus",
      "Asia/Dhaka",
      "Asia/Dili",
      "Asia/Dubai",
      "Asia/Dushanbe",
      "Asia/Famagusta",
      "Asia/Gaza",
      "Asia/Harbin",
      "Asia/Hebron",
      "Asia/Ho_Chi_Minh",
      "Asia/Hong_Kong",
      "Asia/Hovd",
      "Asia/Irkutsk",
      "Asia/Istanbul",
      "Asia/Jakarta",
      "Asia/Jayapura",
      "Asia/Jerusalem",
      "Asia/Kabul",
      "Asia/Kamchatka",
      "Asia/Karachi",
      "Asia/Kashgar",
      "Asia/Kathmandu",
      "Asia/Katmandu",
      "Asia/Khandyga",
      "Asia/Kolkata",
      "Asia/Krasnoyarsk",
      "Asia/Kuala_Lumpur",
      "Asia/Kuching",
      "Asia/Kuwait",
      "Asia/Macao",
      "Asia/Macau",
      "Asia/Magadan",
      "Asia/Makassar",
      "Asia/Manila",
      "Asia/Muscat",
      "Asia/Nicosia",
      "Asia/Novokuznetsk",
      "Asia/Novosibirsk",
      "Asia/Omsk",
      "Asia/Oral",
      "Asia/Phnom_Penh",
      "Asia/Pontianak",
      "Asia/Pyongyang",
      "Asia/Qatar",
      "Asia/Qostanay",
      "Asia/Qyzylorda",
      "Asia/Rangoon",
      "Asia/Riyadh",
      "Asia/Saigon",
      "Asia/Sakhalin",
      "Asia/Samarkand",
      "Asia/Seoul",
      "Asia/Shanghai",
      "Asia/Singapore",
      "Asia/Srednekolymsk",
      "Asia/Taipei",
      "Asia/Tashkent",
      "Asia/Tbilisi",
      "Asia/Tehran",
      "Asia/Tel_Aviv",
      "Asia/Thimbu",
      "Asia/Thimphu",
      "Asia/Tokyo",
      "Asia/Tomsk",
      "Asia/Ujung_Pandang",
      "Asia/Ulaanbaatar",
      "Asia/Ulan_Bator",
      "Asia/Urumqi",
      "Asia/Ust-Nera",
      "Asia/Vientiane",
      "Asia/Vladivostok",
      "Asia/Yakutsk",
      "Asia/Yangon",
      "Asia/Yekaterinburg",
      "Asia/Yerevan",
      "Atlantic/Azores",
      "Atlantic/Bermuda",
      "Atlantic/Canary",
      "Atlantic/Cape_Verde",
      "Atlantic/Faeroe",
      "Atlantic/Faroe",
      "Atlantic/Jan_Mayen",
      "Atlantic/Madeira",
      "Atlantic/Reykjavik",
      "Atlantic/South_Georgia",
      "Atlantic/St_Helena",
      "Atlantic/Stanley",
      "Australia/ACT",
      "Australia/Adelaide",
      "Australia/Brisbane",
      "Australia/Broken_Hill",
      "Australia/Canberra",
      "Australia/Currie",
      "Australia/Darwin",
      "Australia/Eucla",
      "Australia/Hobart",
      "Australia/LHI",
      "Australia/Lindeman",
      "Australia/Lord_Howe",
      "Australia/Melbourne",
      "Australia/NSW",
      "Australia/North",
      "Australia/Perth",
      "Australia/Queensland",
      "Australia/South",
      "Australia/Sydney",
      "Australia/Tasmania",
      "Australia/Victoria",
      "Australia/West",
      "Australia/Yancowinna",
      "Brazil/Acre",
      "Brazil/DeNoronha",
      "Brazil/East",
      "Brazil/West",
      "CET",
      "CST6CDT",
      "Canada/Atlantic",
      "Canada/Central",
      "Canada/Eastern",
      "Canada/Mountain",
      "Canada/Newfoundland",
      "Canada/Pacific",
      "Canada/Saskatchewan",
      "Canada/Yukon",
      "Chile/Continental",
      "Chile/EasterIsland",
      "Cuba",
      "EET",
      "EST",
      "EST5EDT",
      "Egypt",
      "Eire",
      "Etc/GMT",
      "Etc/GMT+0",
      "Etc/GMT+1",
      "Etc/GMT+10",
      "Etc/GMT+11",
      "Etc/GMT+12",
      "Etc/GMT+2",
      "Etc/GMT+3",
      "Etc/GMT+4",
      "Etc/GMT+5",
      "Etc/GMT+6",
      "Etc/GMT+7",
      "Etc/GMT+8",
      "Etc/GMT+9",
      "Etc/GMT-0",
      "Etc/GMT-1",
      "Etc/GMT-10",
      "Etc/GMT-11",
      "Etc/GMT-12",
      "Etc/GMT-13",
      "Etc/GMT-14",
      "Etc/GMT-2",
      "Etc/GMT-3",
      "Etc/GMT-4",
      "Etc/GMT-5",
      "Etc/GMT-6",
      "Etc/GMT-7",
      "Etc/GMT-8",
      "Etc/GMT-9",
      "Etc/GMT0",
      "Etc/Greenwich",
      "Etc/UCT",
      "Etc/UTC",
      "Etc/Universal",
      "Etc/Zulu",
      "Europe/Amsterdam",
      "Europe/Andorra",
      "Europe/Astrakhan",
      "Europe/Athens",
      "Europe/Belfast",
      "Europe/Belgrade",
      "Europe/Berlin",
      "Europe/Bratislava",
      "Europe/Brussels",
      "Europe/Bucharest",
      "Europe/Budapest",
      "Europe/Busingen",
      "Europe/Chisinau",
      "Europe/Copenhagen",
      "Europe/Dublin",
      "Europe/Gibraltar",
      "Europe/Guernsey",
      "Europe/Helsinki",
      "Europe/Isle_of_Man",
      "Europe/Istanbul",
      "Europe/Jersey",
      "Europe/Kaliningrad",
      "Europe/Kiev",
      "Europe/Kirov",
      "Europe/Kyiv",
      "Europe/Lisbon",
      "Europe/Ljubljana",
      "Europe/London",
      "Europe/Luxembourg",
      "Europe/Madrid",
      "Europe/Malta",
      "Europe/Mariehamn",
      "Europe/Minsk",
      "Europe/Monaco",
      "Europe/Moscow",
      "Europe/Nicosia",
      "Europe/Oslo",
      "Europe/Paris",
      "Europe/Podgorica",
      "Europe/Prague",
      "Europe/Riga",
      "Europe/Rome",
      "Europe/Samara",
      "Europe/San_Marino",
      "Europe/Sarajevo",
      "Europe/Saratov",
      "Europe/Simferopol",
      "Europe/Skopje",
      "Europe/Sofia",
      "Europe/Stockholm",
      "Europe/Tallinn",
      "Europe/Tirane",
      "Europe/Tiraspol",
      "Europe/Ulyanovsk",
      "Europe/Uzhgorod",
      "Europe/Vaduz",
      "Europe/Vatican",
      "Europe/Vienna",
      "Europe/Vilnius",
      "Europe/Volgograd",
      "Europe/Warsaw",
      "Europe/Zagreb",
      "Europe/Zaporozhye",
      "Europe/Zurich",
      "Factory",
      "GB",
      "GB-Eire",
      "GMT",
      "GMT+0",
      "GMT-0",
      "GMT0",
      "Greenwich",
      "HST",
      "Hongkong",
      "Iceland",
      "Indian/Antananarivo",
      "Indian/Chagos",
      "Indian/Christmas",
      "Indian/Cocos",
      "Indian/Comoro",
      "Indian/Kerguelen",
      "Indian/Mahe",
      "Indian/Maldives",
      "Indian/Mauritius",
      "Indian/Mayotte",
      "Indian/Reunion",
      "Iran",
      "Israel",
      "Jamaica",
      "Japan",
      "Kwajalein",
      "Libya",
      "MET",
      "MST",
      "MST7MDT",
      "Mexico/BajaNorte",
      "Mexico/BajaSur",
      "Mexico/General",
      "NZ",
      "NZ-CHAT",
      "Navajo",
      "PRC",
      "PST8PDT",
      "Pacific/Apia",
      "Pacific/Auckland",
      "Pacific/Bougainville",
      "Pacific/Chatham",
      "Pacific/Chuuk",
      "Pacific/Easter",
      "Pacific/Efate",
      "Pacific/Enderbury",
      "Pacific/Fakaofo",
      "Pacific/Fiji",
      "Pacific/Funafuti",
      "Pacific/Galapagos",
      "Pacific/Gambier",
      "Pacific/Guadalcanal",
      "Pacific/Guam",
      "Pacific/Honolulu",
      "Pacific/Johnston",
      "Pacific/Kanton",
      "Pacific/Kiritimati",
      "Pacific/Kosrae",
      "Pacific/Kwajalein",
      "Pacific/Majuro",
      "Pacific/Marquesas",
      "Pacific/Midway",
      "Pacific/Nauru",
      "Pacific/Niue",
      "Pacific/Norfolk",
      "Pacific/Noumea",
      "Pacific/Pago_Pago",
      "Pacific/Palau",
      "Pacific/Pitcairn",
      "Pacific/Pohnpei",
      "Pacific/Ponape",
      "Pacific/Port_Moresby",
      "Pacific/Rarotonga",
      "Pacific/Saipan",
      "Pacific/Samoa",
      "Pacific/Tahiti",
      "Pacific/Tarawa",
      "Pacific/Tongatapu",
      "Pacific/Truk",
      "Pacific/Wake",
      "Pacific/Wallis",
      "Pacific/Yap",
      "Poland",
      "Portugal",
      "ROC",
      "ROK",
      "Singapore",
      "Turkey",
      "UCT",
      "US/Alaska",
      "US/Aleutian",
      "US/Arizona",
      "US/Central",
      "US/East-Indiana",
      "US/Eastern",
      "US/Hawaii",
      "US/Indiana-Starke",
      "US/Michigan",
      "US/Mountain",
      "US/Pacific",
      "US/Samoa",
      "UTC",
      "Universal",
      "W-SU",
      "WET",
      "Zulu",
      "localtime",
    ]),
  ),
  interval: Schema.String,
  organization_id: Schema.optional(Schema.String),
  product_id: Schema.optional(Schema.String),
  billing_type: Schema.optional(Schema.String),
  customer_id: Schema.optional(Schema.String),
  metrics: Schema.optional(Schema.String),
}).pipe(T.Http({ method: "GET", path: "/v1/metrics/" }));
export type MetricsgetInput = typeof MetricsgetInput.Type;

// Output Schema
export const MetricsgetOutput = /*@__PURE__*/ /*#__PURE__*/ Schema.Struct({
  periods: Schema.Array(
    Schema.Struct({
      timestamp: Schema.String,
      active_subscriptions: Schema.optional(Schema.Unknown),
      committed_subscriptions: Schema.optional(Schema.Unknown),
      monthly_recurring_revenue: Schema.optional(Schema.Unknown),
      trial_monthly_recurring_revenue: Schema.optional(Schema.Unknown),
      committed_monthly_recurring_revenue: Schema.optional(Schema.Unknown),
      trial_committed_monthly_recurring_revenue: Schema.optional(
        Schema.Unknown,
      ),
      average_revenue_per_user: Schema.optional(Schema.Unknown),
      checkouts: Schema.optional(Schema.Unknown),
      succeeded_checkouts: Schema.optional(Schema.Unknown),
      churned_subscriptions: Schema.optional(Schema.Unknown),
      churn_rate: Schema.optional(Schema.Unknown),
      seats_total: Schema.optional(Schema.Unknown),
      seats_claimed: Schema.optional(Schema.Unknown),
      seats_pending: Schema.optional(Schema.Unknown),
      seat_customers: Schema.optional(Schema.Unknown),
      new_seat_customers: Schema.optional(Schema.Unknown),
      churned_seat_customers: Schema.optional(Schema.Unknown),
      orders: Schema.optional(Schema.Unknown),
      revenue: Schema.optional(Schema.Unknown),
      net_revenue: Schema.optional(Schema.Unknown),
      cumulative_revenue: Schema.optional(Schema.Unknown),
      net_cumulative_revenue: Schema.optional(Schema.Unknown),
      costs: Schema.optional(Schema.Unknown),
      cumulative_costs: Schema.optional(Schema.Unknown),
      average_order_value: Schema.optional(Schema.Unknown),
      net_average_order_value: Schema.optional(Schema.Unknown),
      cost_per_user: Schema.optional(Schema.Unknown),
      active_user_by_event: Schema.optional(Schema.Unknown),
      one_time_products: Schema.optional(Schema.Unknown),
      one_time_products_revenue: Schema.optional(Schema.Unknown),
      one_time_products_net_revenue: Schema.optional(Schema.Unknown),
      new_subscriptions: Schema.optional(Schema.Unknown),
      new_subscriptions_revenue: Schema.optional(Schema.Unknown),
      new_subscriptions_net_revenue: Schema.optional(Schema.Unknown),
      renewed_subscriptions: Schema.optional(Schema.Unknown),
      renewed_subscriptions_revenue: Schema.optional(Schema.Unknown),
      renewed_subscriptions_net_revenue: Schema.optional(Schema.Unknown),
      canceled_subscriptions: Schema.optional(Schema.Unknown),
      canceled_subscriptions_customer_service: Schema.optional(Schema.Unknown),
      canceled_subscriptions_low_quality: Schema.optional(Schema.Unknown),
      canceled_subscriptions_missing_features: Schema.optional(Schema.Unknown),
      canceled_subscriptions_switched_service: Schema.optional(Schema.Unknown),
      canceled_subscriptions_too_complex: Schema.optional(Schema.Unknown),
      canceled_subscriptions_too_expensive: Schema.optional(Schema.Unknown),
      canceled_subscriptions_unused: Schema.optional(Schema.Unknown),
      canceled_subscriptions_other: Schema.optional(Schema.Unknown),
      annual_recurring_revenue: Schema.optional(Schema.Unknown),
      committed_annual_recurring_revenue: Schema.optional(Schema.Unknown),
      checkouts_conversion: Schema.optional(Schema.Unknown),
      ltv: Schema.optional(Schema.Unknown),
      gross_margin: Schema.optional(Schema.Unknown),
      gross_margin_percentage: Schema.optional(Schema.Unknown),
      cashflow: Schema.optional(Schema.Unknown),
      average_seats_per_customer: Schema.optional(Schema.Unknown),
      seat_utilization_rate: Schema.optional(Schema.Unknown),
    }),
  ),
  totals: Schema.Struct({
    active_subscriptions: Schema.optional(Schema.Unknown),
    committed_subscriptions: Schema.optional(Schema.Unknown),
    monthly_recurring_revenue: Schema.optional(Schema.Unknown),
    trial_monthly_recurring_revenue: Schema.optional(Schema.Unknown),
    committed_monthly_recurring_revenue: Schema.optional(Schema.Unknown),
    trial_committed_monthly_recurring_revenue: Schema.optional(Schema.Unknown),
    average_revenue_per_user: Schema.optional(Schema.Unknown),
    checkouts: Schema.optional(Schema.Unknown),
    succeeded_checkouts: Schema.optional(Schema.Unknown),
    churned_subscriptions: Schema.optional(Schema.Unknown),
    churn_rate: Schema.optional(Schema.Unknown),
    seats_total: Schema.optional(Schema.Unknown),
    seats_claimed: Schema.optional(Schema.Unknown),
    seats_pending: Schema.optional(Schema.Unknown),
    seat_customers: Schema.optional(Schema.Unknown),
    new_seat_customers: Schema.optional(Schema.Unknown),
    churned_seat_customers: Schema.optional(Schema.Unknown),
    orders: Schema.optional(Schema.Unknown),
    revenue: Schema.optional(Schema.Unknown),
    net_revenue: Schema.optional(Schema.Unknown),
    cumulative_revenue: Schema.optional(Schema.Unknown),
    net_cumulative_revenue: Schema.optional(Schema.Unknown),
    costs: Schema.optional(Schema.Unknown),
    cumulative_costs: Schema.optional(Schema.Unknown),
    average_order_value: Schema.optional(Schema.Unknown),
    net_average_order_value: Schema.optional(Schema.Unknown),
    cost_per_user: Schema.optional(Schema.Unknown),
    active_user_by_event: Schema.optional(Schema.Unknown),
    one_time_products: Schema.optional(Schema.Unknown),
    one_time_products_revenue: Schema.optional(Schema.Unknown),
    one_time_products_net_revenue: Schema.optional(Schema.Unknown),
    new_subscriptions: Schema.optional(Schema.Unknown),
    new_subscriptions_revenue: Schema.optional(Schema.Unknown),
    new_subscriptions_net_revenue: Schema.optional(Schema.Unknown),
    renewed_subscriptions: Schema.optional(Schema.Unknown),
    renewed_subscriptions_revenue: Schema.optional(Schema.Unknown),
    renewed_subscriptions_net_revenue: Schema.optional(Schema.Unknown),
    canceled_subscriptions: Schema.optional(Schema.Unknown),
    canceled_subscriptions_customer_service: Schema.optional(Schema.Unknown),
    canceled_subscriptions_low_quality: Schema.optional(Schema.Unknown),
    canceled_subscriptions_missing_features: Schema.optional(Schema.Unknown),
    canceled_subscriptions_switched_service: Schema.optional(Schema.Unknown),
    canceled_subscriptions_too_complex: Schema.optional(Schema.Unknown),
    canceled_subscriptions_too_expensive: Schema.optional(Schema.Unknown),
    canceled_subscriptions_unused: Schema.optional(Schema.Unknown),
    canceled_subscriptions_other: Schema.optional(Schema.Unknown),
    annual_recurring_revenue: Schema.optional(Schema.Unknown),
    committed_annual_recurring_revenue: Schema.optional(Schema.Unknown),
    checkouts_conversion: Schema.optional(Schema.Unknown),
    ltv: Schema.optional(Schema.Unknown),
    gross_margin: Schema.optional(Schema.Unknown),
    gross_margin_percentage: Schema.optional(Schema.Unknown),
    cashflow: Schema.optional(Schema.Unknown),
    average_seats_per_customer: Schema.optional(Schema.Unknown),
    seat_utilization_rate: Schema.optional(Schema.Unknown),
  }),
  metrics: Schema.Struct({
    active_subscriptions: Schema.optional(
      Schema.NullOr(
        Schema.Struct({
          slug: Schema.String,
          display_name: Schema.String,
          type: Schema.Literals([
            "scalar",
            "currency",
            "currency_sub_cent",
            "percentage",
          ]),
        }),
      ),
    ),
    committed_subscriptions: Schema.optional(
      Schema.NullOr(
        Schema.Struct({
          slug: Schema.String,
          display_name: Schema.String,
          type: Schema.Literals([
            "scalar",
            "currency",
            "currency_sub_cent",
            "percentage",
          ]),
        }),
      ),
    ),
    monthly_recurring_revenue: Schema.optional(
      Schema.NullOr(
        Schema.Struct({
          slug: Schema.String,
          display_name: Schema.String,
          type: Schema.Literals([
            "scalar",
            "currency",
            "currency_sub_cent",
            "percentage",
          ]),
        }),
      ),
    ),
    trial_monthly_recurring_revenue: Schema.optional(
      Schema.NullOr(
        Schema.Struct({
          slug: Schema.String,
          display_name: Schema.String,
          type: Schema.Literals([
            "scalar",
            "currency",
            "currency_sub_cent",
            "percentage",
          ]),
        }),
      ),
    ),
    committed_monthly_recurring_revenue: Schema.optional(
      Schema.NullOr(
        Schema.Struct({
          slug: Schema.String,
          display_name: Schema.String,
          type: Schema.Literals([
            "scalar",
            "currency",
            "currency_sub_cent",
            "percentage",
          ]),
        }),
      ),
    ),
    trial_committed_monthly_recurring_revenue: Schema.optional(
      Schema.NullOr(
        Schema.Struct({
          slug: Schema.String,
          display_name: Schema.String,
          type: Schema.Literals([
            "scalar",
            "currency",
            "currency_sub_cent",
            "percentage",
          ]),
        }),
      ),
    ),
    average_revenue_per_user: Schema.optional(
      Schema.NullOr(
        Schema.Struct({
          slug: Schema.String,
          display_name: Schema.String,
          type: Schema.Literals([
            "scalar",
            "currency",
            "currency_sub_cent",
            "percentage",
          ]),
        }),
      ),
    ),
    checkouts: Schema.optional(
      Schema.NullOr(
        Schema.Struct({
          slug: Schema.String,
          display_name: Schema.String,
          type: Schema.Literals([
            "scalar",
            "currency",
            "currency_sub_cent",
            "percentage",
          ]),
        }),
      ),
    ),
    succeeded_checkouts: Schema.optional(
      Schema.NullOr(
        Schema.Struct({
          slug: Schema.String,
          display_name: Schema.String,
          type: Schema.Literals([
            "scalar",
            "currency",
            "currency_sub_cent",
            "percentage",
          ]),
        }),
      ),
    ),
    churned_subscriptions: Schema.optional(
      Schema.NullOr(
        Schema.Struct({
          slug: Schema.String,
          display_name: Schema.String,
          type: Schema.Literals([
            "scalar",
            "currency",
            "currency_sub_cent",
            "percentage",
          ]),
        }),
      ),
    ),
    churn_rate: Schema.optional(
      Schema.NullOr(
        Schema.Struct({
          slug: Schema.String,
          display_name: Schema.String,
          type: Schema.Literals([
            "scalar",
            "currency",
            "currency_sub_cent",
            "percentage",
          ]),
        }),
      ),
    ),
    seats_total: Schema.optional(
      Schema.NullOr(
        Schema.Struct({
          slug: Schema.String,
          display_name: Schema.String,
          type: Schema.Literals([
            "scalar",
            "currency",
            "currency_sub_cent",
            "percentage",
          ]),
        }),
      ),
    ),
    seats_claimed: Schema.optional(
      Schema.NullOr(
        Schema.Struct({
          slug: Schema.String,
          display_name: Schema.String,
          type: Schema.Literals([
            "scalar",
            "currency",
            "currency_sub_cent",
            "percentage",
          ]),
        }),
      ),
    ),
    seats_pending: Schema.optional(
      Schema.NullOr(
        Schema.Struct({
          slug: Schema.String,
          display_name: Schema.String,
          type: Schema.Literals([
            "scalar",
            "currency",
            "currency_sub_cent",
            "percentage",
          ]),
        }),
      ),
    ),
    seat_customers: Schema.optional(
      Schema.NullOr(
        Schema.Struct({
          slug: Schema.String,
          display_name: Schema.String,
          type: Schema.Literals([
            "scalar",
            "currency",
            "currency_sub_cent",
            "percentage",
          ]),
        }),
      ),
    ),
    new_seat_customers: Schema.optional(
      Schema.NullOr(
        Schema.Struct({
          slug: Schema.String,
          display_name: Schema.String,
          type: Schema.Literals([
            "scalar",
            "currency",
            "currency_sub_cent",
            "percentage",
          ]),
        }),
      ),
    ),
    churned_seat_customers: Schema.optional(
      Schema.NullOr(
        Schema.Struct({
          slug: Schema.String,
          display_name: Schema.String,
          type: Schema.Literals([
            "scalar",
            "currency",
            "currency_sub_cent",
            "percentage",
          ]),
        }),
      ),
    ),
    orders: Schema.optional(
      Schema.NullOr(
        Schema.Struct({
          slug: Schema.String,
          display_name: Schema.String,
          type: Schema.Literals([
            "scalar",
            "currency",
            "currency_sub_cent",
            "percentage",
          ]),
        }),
      ),
    ),
    revenue: Schema.optional(
      Schema.NullOr(
        Schema.Struct({
          slug: Schema.String,
          display_name: Schema.String,
          type: Schema.Literals([
            "scalar",
            "currency",
            "currency_sub_cent",
            "percentage",
          ]),
        }),
      ),
    ),
    net_revenue: Schema.optional(
      Schema.NullOr(
        Schema.Struct({
          slug: Schema.String,
          display_name: Schema.String,
          type: Schema.Literals([
            "scalar",
            "currency",
            "currency_sub_cent",
            "percentage",
          ]),
        }),
      ),
    ),
    cumulative_revenue: Schema.optional(
      Schema.NullOr(
        Schema.Struct({
          slug: Schema.String,
          display_name: Schema.String,
          type: Schema.Literals([
            "scalar",
            "currency",
            "currency_sub_cent",
            "percentage",
          ]),
        }),
      ),
    ),
    net_cumulative_revenue: Schema.optional(
      Schema.NullOr(
        Schema.Struct({
          slug: Schema.String,
          display_name: Schema.String,
          type: Schema.Literals([
            "scalar",
            "currency",
            "currency_sub_cent",
            "percentage",
          ]),
        }),
      ),
    ),
    costs: Schema.optional(
      Schema.NullOr(
        Schema.Struct({
          slug: Schema.String,
          display_name: Schema.String,
          type: Schema.Literals([
            "scalar",
            "currency",
            "currency_sub_cent",
            "percentage",
          ]),
        }),
      ),
    ),
    cumulative_costs: Schema.optional(
      Schema.NullOr(
        Schema.Struct({
          slug: Schema.String,
          display_name: Schema.String,
          type: Schema.Literals([
            "scalar",
            "currency",
            "currency_sub_cent",
            "percentage",
          ]),
        }),
      ),
    ),
    average_order_value: Schema.optional(
      Schema.NullOr(
        Schema.Struct({
          slug: Schema.String,
          display_name: Schema.String,
          type: Schema.Literals([
            "scalar",
            "currency",
            "currency_sub_cent",
            "percentage",
          ]),
        }),
      ),
    ),
    net_average_order_value: Schema.optional(
      Schema.NullOr(
        Schema.Struct({
          slug: Schema.String,
          display_name: Schema.String,
          type: Schema.Literals([
            "scalar",
            "currency",
            "currency_sub_cent",
            "percentage",
          ]),
        }),
      ),
    ),
    cost_per_user: Schema.optional(
      Schema.NullOr(
        Schema.Struct({
          slug: Schema.String,
          display_name: Schema.String,
          type: Schema.Literals([
            "scalar",
            "currency",
            "currency_sub_cent",
            "percentage",
          ]),
        }),
      ),
    ),
    active_user_by_event: Schema.optional(
      Schema.NullOr(
        Schema.Struct({
          slug: Schema.String,
          display_name: Schema.String,
          type: Schema.Literals([
            "scalar",
            "currency",
            "currency_sub_cent",
            "percentage",
          ]),
        }),
      ),
    ),
    one_time_products: Schema.optional(
      Schema.NullOr(
        Schema.Struct({
          slug: Schema.String,
          display_name: Schema.String,
          type: Schema.Literals([
            "scalar",
            "currency",
            "currency_sub_cent",
            "percentage",
          ]),
        }),
      ),
    ),
    one_time_products_revenue: Schema.optional(
      Schema.NullOr(
        Schema.Struct({
          slug: Schema.String,
          display_name: Schema.String,
          type: Schema.Literals([
            "scalar",
            "currency",
            "currency_sub_cent",
            "percentage",
          ]),
        }),
      ),
    ),
    one_time_products_net_revenue: Schema.optional(
      Schema.NullOr(
        Schema.Struct({
          slug: Schema.String,
          display_name: Schema.String,
          type: Schema.Literals([
            "scalar",
            "currency",
            "currency_sub_cent",
            "percentage",
          ]),
        }),
      ),
    ),
    new_subscriptions: Schema.optional(
      Schema.NullOr(
        Schema.Struct({
          slug: Schema.String,
          display_name: Schema.String,
          type: Schema.Literals([
            "scalar",
            "currency",
            "currency_sub_cent",
            "percentage",
          ]),
        }),
      ),
    ),
    new_subscriptions_revenue: Schema.optional(
      Schema.NullOr(
        Schema.Struct({
          slug: Schema.String,
          display_name: Schema.String,
          type: Schema.Literals([
            "scalar",
            "currency",
            "currency_sub_cent",
            "percentage",
          ]),
        }),
      ),
    ),
    new_subscriptions_net_revenue: Schema.optional(
      Schema.NullOr(
        Schema.Struct({
          slug: Schema.String,
          display_name: Schema.String,
          type: Schema.Literals([
            "scalar",
            "currency",
            "currency_sub_cent",
            "percentage",
          ]),
        }),
      ),
    ),
    renewed_subscriptions: Schema.optional(
      Schema.NullOr(
        Schema.Struct({
          slug: Schema.String,
          display_name: Schema.String,
          type: Schema.Literals([
            "scalar",
            "currency",
            "currency_sub_cent",
            "percentage",
          ]),
        }),
      ),
    ),
    renewed_subscriptions_revenue: Schema.optional(
      Schema.NullOr(
        Schema.Struct({
          slug: Schema.String,
          display_name: Schema.String,
          type: Schema.Literals([
            "scalar",
            "currency",
            "currency_sub_cent",
            "percentage",
          ]),
        }),
      ),
    ),
    renewed_subscriptions_net_revenue: Schema.optional(
      Schema.NullOr(
        Schema.Struct({
          slug: Schema.String,
          display_name: Schema.String,
          type: Schema.Literals([
            "scalar",
            "currency",
            "currency_sub_cent",
            "percentage",
          ]),
        }),
      ),
    ),
    canceled_subscriptions: Schema.optional(
      Schema.NullOr(
        Schema.Struct({
          slug: Schema.String,
          display_name: Schema.String,
          type: Schema.Literals([
            "scalar",
            "currency",
            "currency_sub_cent",
            "percentage",
          ]),
        }),
      ),
    ),
    canceled_subscriptions_customer_service: Schema.optional(
      Schema.NullOr(
        Schema.Struct({
          slug: Schema.String,
          display_name: Schema.String,
          type: Schema.Literals([
            "scalar",
            "currency",
            "currency_sub_cent",
            "percentage",
          ]),
        }),
      ),
    ),
    canceled_subscriptions_low_quality: Schema.optional(
      Schema.NullOr(
        Schema.Struct({
          slug: Schema.String,
          display_name: Schema.String,
          type: Schema.Literals([
            "scalar",
            "currency",
            "currency_sub_cent",
            "percentage",
          ]),
        }),
      ),
    ),
    canceled_subscriptions_missing_features: Schema.optional(
      Schema.NullOr(
        Schema.Struct({
          slug: Schema.String,
          display_name: Schema.String,
          type: Schema.Literals([
            "scalar",
            "currency",
            "currency_sub_cent",
            "percentage",
          ]),
        }),
      ),
    ),
    canceled_subscriptions_switched_service: Schema.optional(
      Schema.NullOr(
        Schema.Struct({
          slug: Schema.String,
          display_name: Schema.String,
          type: Schema.Literals([
            "scalar",
            "currency",
            "currency_sub_cent",
            "percentage",
          ]),
        }),
      ),
    ),
    canceled_subscriptions_too_complex: Schema.optional(
      Schema.NullOr(
        Schema.Struct({
          slug: Schema.String,
          display_name: Schema.String,
          type: Schema.Literals([
            "scalar",
            "currency",
            "currency_sub_cent",
            "percentage",
          ]),
        }),
      ),
    ),
    canceled_subscriptions_too_expensive: Schema.optional(
      Schema.NullOr(
        Schema.Struct({
          slug: Schema.String,
          display_name: Schema.String,
          type: Schema.Literals([
            "scalar",
            "currency",
            "currency_sub_cent",
            "percentage",
          ]),
        }),
      ),
    ),
    canceled_subscriptions_unused: Schema.optional(
      Schema.NullOr(
        Schema.Struct({
          slug: Schema.String,
          display_name: Schema.String,
          type: Schema.Literals([
            "scalar",
            "currency",
            "currency_sub_cent",
            "percentage",
          ]),
        }),
      ),
    ),
    canceled_subscriptions_other: Schema.optional(
      Schema.NullOr(
        Schema.Struct({
          slug: Schema.String,
          display_name: Schema.String,
          type: Schema.Literals([
            "scalar",
            "currency",
            "currency_sub_cent",
            "percentage",
          ]),
        }),
      ),
    ),
    annual_recurring_revenue: Schema.optional(
      Schema.NullOr(
        Schema.Struct({
          slug: Schema.String,
          display_name: Schema.String,
          type: Schema.Literals([
            "scalar",
            "currency",
            "currency_sub_cent",
            "percentage",
          ]),
        }),
      ),
    ),
    committed_annual_recurring_revenue: Schema.optional(
      Schema.NullOr(
        Schema.Struct({
          slug: Schema.String,
          display_name: Schema.String,
          type: Schema.Literals([
            "scalar",
            "currency",
            "currency_sub_cent",
            "percentage",
          ]),
        }),
      ),
    ),
    checkouts_conversion: Schema.optional(
      Schema.NullOr(
        Schema.Struct({
          slug: Schema.String,
          display_name: Schema.String,
          type: Schema.Literals([
            "scalar",
            "currency",
            "currency_sub_cent",
            "percentage",
          ]),
        }),
      ),
    ),
    ltv: Schema.optional(
      Schema.NullOr(
        Schema.Struct({
          slug: Schema.String,
          display_name: Schema.String,
          type: Schema.Literals([
            "scalar",
            "currency",
            "currency_sub_cent",
            "percentage",
          ]),
        }),
      ),
    ),
    gross_margin: Schema.optional(
      Schema.NullOr(
        Schema.Struct({
          slug: Schema.String,
          display_name: Schema.String,
          type: Schema.Literals([
            "scalar",
            "currency",
            "currency_sub_cent",
            "percentage",
          ]),
        }),
      ),
    ),
    gross_margin_percentage: Schema.optional(
      Schema.NullOr(
        Schema.Struct({
          slug: Schema.String,
          display_name: Schema.String,
          type: Schema.Literals([
            "scalar",
            "currency",
            "currency_sub_cent",
            "percentage",
          ]),
        }),
      ),
    ),
    cashflow: Schema.optional(
      Schema.NullOr(
        Schema.Struct({
          slug: Schema.String,
          display_name: Schema.String,
          type: Schema.Literals([
            "scalar",
            "currency",
            "currency_sub_cent",
            "percentage",
          ]),
        }),
      ),
    ),
    average_seats_per_customer: Schema.optional(
      Schema.NullOr(
        Schema.Struct({
          slug: Schema.String,
          display_name: Schema.String,
          type: Schema.Literals([
            "scalar",
            "currency",
            "currency_sub_cent",
            "percentage",
          ]),
        }),
      ),
    ),
    seat_utilization_rate: Schema.optional(
      Schema.NullOr(
        Schema.Struct({
          slug: Schema.String,
          display_name: Schema.String,
          type: Schema.Literals([
            "scalar",
            "currency",
            "currency_sub_cent",
            "percentage",
          ]),
        }),
      ),
    ),
  }),
});
export type MetricsgetOutput = typeof MetricsgetOutput.Type;

// The operation
/**
 * Get Metrics
 *
 * Get metrics about your orders and subscriptions.
 * Currency values are output in cents.
 * **Scopes**: `metrics:read`
 *
 * @param start_date - Start date.
 * @param end_date - End date.
 * @param timezone - Timezone to use for the timestamps. Default is UTC.
 * @param interval - Interval between two timestamps.
 * @param organization_id - Filter by organization ID.
 * @param product_id - Filter by product ID.
 * @param billing_type - Filter by billing type. `recurring` will filter data corresponding to subscriptions creations or renewals. `one_time` will filter data corresponding to one-time purchases.
 * @param customer_id - Filter by customer ID.
 * @param metrics - List of metric slugs to focus on. When provided, only the queries needed for these metrics will be executed, improving performance. If not provided, all metrics are returned.
 */
export const metricsget = /*@__PURE__*/ /*#__PURE__*/ API.make(() => ({
  inputSchema: MetricsgetInput,
  outputSchema: MetricsgetOutput,
  errors: [UnprocessableEntity] as const,
}));
