import * as Schema from "effect/Schema";
import { API } from "../client.ts";
import * as T from "../traits.ts";
import { UnprocessableEntity } from "../errors.ts";

// Input Schema
export const OrganizationslistInput = /*@__PURE__*/ /*#__PURE__*/ Schema.Struct(
  {
    slug: Schema.optional(Schema.String).pipe(T.QueryParam()),
    page: Schema.optional(Schema.Number).pipe(T.QueryParam()),
    limit: Schema.optional(Schema.Number).pipe(T.QueryParam()),
    sorting: Schema.optional(Schema.String).pipe(T.QueryParam()),
  },
).pipe(T.Http({ method: "GET", path: "/v1/organizations/" }));
export type OrganizationslistInput = typeof OrganizationslistInput.Type;

// Output Schema
export const OrganizationslistOutput =
  /*@__PURE__*/ /*#__PURE__*/ Schema.Struct({
    items: Schema.Array(
      Schema.Struct({
        created_at: Schema.String,
        modified_at: Schema.NullOr(Schema.String),
        id: Schema.String,
        name: Schema.String,
        slug: Schema.String,
        avatar_url: Schema.NullOr(Schema.String),
        proration_behavior: Schema.Literals([
          "invoice",
          "prorate",
          "next_period",
          "reset",
        ]),
        allow_customer_updates: Schema.Boolean,
        email: Schema.NullOr(Schema.String),
        website: Schema.NullOr(Schema.String),
        socials: Schema.Array(
          Schema.Struct({
            platform: Schema.Literals([
              "x",
              "github",
              "facebook",
              "instagram",
              "youtube",
              "tiktok",
              "linkedin",
              "threads",
              "discord",
              "other",
            ]),
            url: Schema.String,
          }),
        ),
        status: Schema.Literals([
          "created",
          "review",
          "snoozed",
          "denied",
          "active",
          "blocked",
          "offboarding",
        ]),
        details_submitted_at: Schema.NullOr(Schema.String),
        default_presentment_currency: Schema.String,
        default_tax_behavior: Schema.Literals([
          "location",
          "inclusive",
          "exclusive",
        ]),
        feature_settings: Schema.NullOr(
          Schema.Struct({
            issue_funding_enabled: Schema.optional(Schema.Boolean),
            seat_based_pricing_enabled: Schema.optional(Schema.Boolean),
            wallets_enabled: Schema.optional(Schema.Boolean),
            member_model_enabled: Schema.optional(Schema.Boolean),
            checkout_localization_enabled: Schema.optional(Schema.Boolean),
            overview_metrics: Schema.optional(
              Schema.NullOr(Schema.Array(Schema.String)),
            ),
            reset_proration_behavior_enabled: Schema.optional(Schema.Boolean),
          }),
        ),
        subscription_settings: Schema.Struct({
          allow_multiple_subscriptions: Schema.Boolean,
          proration_behavior: Schema.Literals([
            "invoice",
            "prorate",
            "next_period",
          ]),
          benefit_revocation_grace_period: Schema.Number,
          prevent_trial_abuse: Schema.Boolean,
          allow_customer_updates: Schema.Boolean,
        }),
        notification_settings: Schema.Struct({
          new_order: Schema.Boolean,
          new_subscription: Schema.Boolean,
        }),
        customer_email_settings: Schema.Struct({
          order_confirmation: Schema.Boolean,
          subscription_cancellation: Schema.Boolean,
          subscription_confirmation: Schema.Boolean,
          subscription_cycled: Schema.Boolean,
          subscription_cycled_after_trial: Schema.Boolean,
          subscription_past_due: Schema.Boolean,
          subscription_renewal_reminder: Schema.Boolean,
          subscription_revoked: Schema.Boolean,
          subscription_trial_conversion_reminder: Schema.Boolean,
          subscription_uncanceled: Schema.Boolean,
          subscription_updated: Schema.Boolean,
        }),
        customer_portal_settings: Schema.Struct({
          usage: Schema.Struct({
            show: Schema.Boolean,
          }),
          subscription: Schema.Struct({
            update_seats: Schema.Boolean,
            update_plan: Schema.Boolean,
          }),
          customer: Schema.optional(
            Schema.Struct({
              allow_email_change: Schema.optional(Schema.Boolean),
            }),
          ),
        }),
        country: Schema.optional(
          Schema.NullOr(
            Schema.Literals([
              "AD",
              "AE",
              "AF",
              "AG",
              "AI",
              "AL",
              "AM",
              "AO",
              "AQ",
              "AR",
              "AS",
              "AT",
              "AU",
              "AW",
              "AX",
              "AZ",
              "BA",
              "BB",
              "BD",
              "BE",
              "BF",
              "BG",
              "BH",
              "BI",
              "BJ",
              "BL",
              "BM",
              "BN",
              "BO",
              "BQ",
              "BR",
              "BS",
              "BT",
              "BV",
              "BW",
              "BY",
              "BZ",
              "CA",
              "CC",
              "CD",
              "CF",
              "CG",
              "CH",
              "CI",
              "CK",
              "CL",
              "CM",
              "CN",
              "CO",
              "CR",
              "CU",
              "CV",
              "CW",
              "CX",
              "CY",
              "CZ",
              "DE",
              "DJ",
              "DK",
              "DM",
              "DO",
              "DZ",
              "EC",
              "EE",
              "EG",
              "EH",
              "ER",
              "ES",
              "ET",
              "FI",
              "FJ",
              "FK",
              "FM",
              "FO",
              "FR",
              "GA",
              "GB",
              "GD",
              "GE",
              "GF",
              "GG",
              "GH",
              "GI",
              "GL",
              "GM",
              "GN",
              "GP",
              "GQ",
              "GR",
              "GS",
              "GT",
              "GU",
              "GW",
              "GY",
              "HK",
              "HM",
              "HN",
              "HR",
              "HT",
              "HU",
              "ID",
              "IE",
              "IL",
              "IM",
              "IN",
              "IO",
              "IQ",
              "IR",
              "IS",
              "IT",
              "JE",
              "JM",
              "JO",
              "JP",
              "KE",
              "KG",
              "KH",
              "KI",
              "KM",
              "KN",
              "KP",
              "KR",
              "KW",
              "KY",
              "KZ",
              "LA",
              "LB",
              "LC",
              "LI",
              "LK",
              "LR",
              "LS",
              "LT",
              "LU",
              "LV",
              "LY",
              "MA",
              "MC",
              "MD",
              "ME",
              "MF",
              "MG",
              "MH",
              "MK",
              "ML",
              "MM",
              "MN",
              "MO",
              "MP",
              "MQ",
              "MR",
              "MS",
              "MT",
              "MU",
              "MV",
              "MW",
              "MX",
              "MY",
              "MZ",
              "NA",
              "NC",
              "NE",
              "NF",
              "NG",
              "NI",
              "NL",
              "NO",
              "NP",
              "NR",
              "NU",
              "NZ",
              "OM",
              "PA",
              "PE",
              "PF",
              "PG",
              "PH",
              "PK",
              "PL",
              "PM",
              "PN",
              "PR",
              "PS",
              "PT",
              "PW",
              "PY",
              "QA",
              "RE",
              "RO",
              "RS",
              "RU",
              "RW",
              "SA",
              "SB",
              "SC",
              "SD",
              "SE",
              "SG",
              "SH",
              "SI",
              "SJ",
              "SK",
              "SL",
              "SM",
              "SN",
              "SO",
              "SR",
              "SS",
              "ST",
              "SV",
              "SX",
              "SY",
              "SZ",
              "TC",
              "TD",
              "TF",
              "TG",
              "TH",
              "TJ",
              "TK",
              "TL",
              "TM",
              "TN",
              "TO",
              "TR",
              "TT",
              "TV",
              "TW",
              "TZ",
              "UA",
              "UG",
              "UM",
              "US",
              "UY",
              "UZ",
              "VA",
              "VC",
              "VE",
              "VG",
              "VI",
              "VN",
              "VU",
              "WF",
              "WS",
              "YE",
              "YT",
              "ZA",
              "ZM",
              "ZW",
            ]),
          ),
        ),
        account_id: Schema.NullOr(Schema.String),
        payout_account_id: Schema.NullOr(Schema.String),
        capabilities: Schema.Struct({
          checkout_payments: Schema.Boolean,
          subscription_renewals: Schema.Boolean,
          payouts: Schema.Boolean,
          refunds: Schema.Boolean,
          api_access: Schema.Boolean,
          dashboard_access: Schema.Boolean,
        }),
      }),
    ),
    pagination: Schema.Struct({
      total_count: Schema.Number,
      max_page: Schema.Number,
    }),
  });
export type OrganizationslistOutput = typeof OrganizationslistOutput.Type;

// The operation
/**
 * List Organizations
 *
 * List organizations.
 * **Scopes**: `organizations:read` `organizations:write`
 *
 * @param slug - Filter by slug.
 * @param page - Page number, defaults to 1.
 * @param limit - Size of a page, defaults to 10. Maximum is 100.
 * @param sorting - Sorting criterion. Several criteria can be used simultaneously and will be applied in order. Add a minus sign `-` before the criteria name to sort by descending order.
 */
export const organizationslist = /*@__PURE__*/ /*#__PURE__*/ API.make(() => ({
  inputSchema: OrganizationslistInput,
  outputSchema: OrganizationslistOutput,
  errors: [UnprocessableEntity] as const,
}));
