import * as Schema from "effect/Schema";
import { API } from "../client.ts";
import * as T from "../traits.ts";
import {
  Forbidden,
  NotFound,
  Conflict,
  UnprocessableEntity,
} from "../errors.ts";

// Input Schema
export const SubscriptionsrevokeInput =
  /*@__PURE__*/ /*#__PURE__*/ Schema.Struct({
    id: Schema.String.pipe(T.PathParam()),
  }).pipe(T.Http({ method: "DELETE", path: "/v1/subscriptions/{id}" }));
export type SubscriptionsrevokeInput = typeof SubscriptionsrevokeInput.Type;

// Output Schema
export const SubscriptionsrevokeOutput =
  /*@__PURE__*/ /*#__PURE__*/ Schema.Struct({
    created_at: Schema.String,
    modified_at: Schema.NullOr(Schema.String),
    id: Schema.String,
    amount: Schema.Number,
    currency: Schema.String,
    recurring_interval: Schema.Literals(["day", "week", "month", "year"]),
    recurring_interval_count: Schema.Number,
    status: Schema.Literals([
      "incomplete",
      "incomplete_expired",
      "trialing",
      "active",
      "past_due",
      "canceled",
      "unpaid",
    ]),
    current_period_start: Schema.String,
    current_period_end: Schema.String,
    trial_start: Schema.NullOr(Schema.String),
    trial_end: Schema.NullOr(Schema.String),
    cancel_at_period_end: Schema.Boolean,
    canceled_at: Schema.NullOr(Schema.String),
    started_at: Schema.NullOr(Schema.String),
    ends_at: Schema.NullOr(Schema.String),
    ended_at: Schema.NullOr(Schema.String),
    customer_id: Schema.String,
    product_id: Schema.String,
    discount_id: Schema.NullOr(Schema.String),
    checkout_id: Schema.NullOr(Schema.String),
    seats: Schema.optional(Schema.NullOr(Schema.Number)),
    customer_cancellation_reason: Schema.NullOr(
      Schema.Literals([
        "customer_service",
        "low_quality",
        "missing_features",
        "switched_service",
        "too_complex",
        "too_expensive",
        "unused",
        "other",
      ]),
    ),
    customer_cancellation_comment: Schema.NullOr(Schema.String),
    metadata: Schema.Record(Schema.String, Schema.Unknown),
    custom_field_data: Schema.optional(
      Schema.Record(Schema.String, Schema.Unknown),
    ),
    customer: Schema.Struct({
      id: Schema.String,
      created_at: Schema.String,
      modified_at: Schema.NullOr(Schema.String),
      metadata: Schema.Record(Schema.String, Schema.Unknown),
      external_id: Schema.optional(Schema.NullOr(Schema.String)),
      email: Schema.optional(Schema.NullOr(Schema.String)),
      email_verified: Schema.Boolean,
      type: Schema.Literals(["individual", "team"]),
      name: Schema.NullOr(Schema.String),
      billing_address: Schema.NullOr(
        Schema.Struct({
          line1: Schema.optional(Schema.NullOr(Schema.String)),
          line2: Schema.optional(Schema.NullOr(Schema.String)),
          postal_code: Schema.optional(Schema.NullOr(Schema.String)),
          city: Schema.optional(Schema.NullOr(Schema.String)),
          state: Schema.optional(Schema.NullOr(Schema.String)),
          country: Schema.Literals([
            "AD",
            "AE",
            "AF",
            "AG",
            "AI",
            "AL",
            "AM",
            "AO",
            "AQ",
            "AR",
            "AS",
            "AT",
            "AU",
            "AW",
            "AX",
            "AZ",
            "BA",
            "BB",
            "BD",
            "BE",
            "BF",
            "BG",
            "BH",
            "BI",
            "BJ",
            "BL",
            "BM",
            "BN",
            "BO",
            "BQ",
            "BR",
            "BS",
            "BT",
            "BV",
            "BW",
            "BY",
            "BZ",
            "CA",
            "CC",
            "CD",
            "CF",
            "CG",
            "CH",
            "CI",
            "CK",
            "CL",
            "CM",
            "CN",
            "CO",
            "CR",
            "CU",
            "CV",
            "CW",
            "CX",
            "CY",
            "CZ",
            "DE",
            "DJ",
            "DK",
            "DM",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "EH",
            "ER",
            "ES",
            "ET",
            "FI",
            "FJ",
            "FK",
            "FM",
            "FO",
            "FR",
            "GA",
            "GB",
            "GD",
            "GE",
            "GF",
            "GG",
            "GH",
            "GI",
            "GL",
            "GM",
            "GN",
            "GP",
            "GQ",
            "GR",
            "GS",
            "GT",
            "GU",
            "GW",
            "GY",
            "HK",
            "HM",
            "HN",
            "HR",
            "HT",
            "HU",
            "ID",
            "IE",
            "IL",
            "IM",
            "IN",
            "IO",
            "IQ",
            "IR",
            "IS",
            "IT",
            "JE",
            "JM",
            "JO",
            "JP",
            "KE",
            "KG",
            "KH",
            "KI",
            "KM",
            "KN",
            "KP",
            "KR",
            "KW",
            "KY",
            "KZ",
            "LA",
            "LB",
            "LC",
            "LI",
            "LK",
            "LR",
            "LS",
            "LT",
            "LU",
            "LV",
            "LY",
            "MA",
            "MC",
            "MD",
            "ME",
            "MF",
            "MG",
            "MH",
            "MK",
            "ML",
            "MM",
            "MN",
            "MO",
            "MP",
            "MQ",
            "MR",
            "MS",
            "MT",
            "MU",
            "MV",
            "MW",
            "MX",
            "MY",
            "MZ",
            "NA",
            "NC",
            "NE",
            "NF",
            "NG",
            "NI",
            "NL",
            "NO",
            "NP",
            "NR",
            "NU",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PF",
            "PG",
            "PH",
            "PK",
            "PL",
            "PM",
            "PN",
            "PR",
            "PS",
            "PT",
            "PW",
            "PY",
            "QA",
            "RE",
            "RO",
            "RS",
            "RU",
            "RW",
            "SA",
            "SB",
            "SC",
            "SD",
            "SE",
            "SG",
            "SH",
            "SI",
            "SJ",
            "SK",
            "SL",
            "SM",
            "SN",
            "SO",
            "SR",
            "SS",
            "ST",
            "SV",
            "SX",
            "SY",
            "SZ",
            "TC",
            "TD",
            "TF",
            "TG",
            "TH",
            "TJ",
            "TK",
            "TL",
            "TM",
            "TN",
            "TO",
            "TR",
            "TT",
            "TV",
            "TW",
            "TZ",
            "UA",
            "UG",
            "UM",
            "US",
            "UY",
            "UZ",
            "VA",
            "VC",
            "VE",
            "VG",
            "VI",
            "VN",
            "VU",
            "WF",
            "WS",
            "YE",
            "YT",
            "ZA",
            "ZM",
            "ZW",
          ]),
        }),
      ),
      tax_id: Schema.NullOr(Schema.Array(Schema.Unknown)),
      locale: Schema.optional(Schema.NullOr(Schema.String)),
      organization_id: Schema.String,
      deleted_at: Schema.NullOr(Schema.String),
      avatar_url: Schema.String,
    }),
    product: Schema.Struct({
      id: Schema.String,
      created_at: Schema.String,
      modified_at: Schema.NullOr(Schema.String),
      trial_interval: Schema.NullOr(
        Schema.Literals(["day", "week", "month", "year"]),
      ),
      trial_interval_count: Schema.NullOr(Schema.Number),
      name: Schema.String,
      description: Schema.NullOr(Schema.String),
      visibility: Schema.Literals(["draft", "private", "public"]),
      recurring_interval: Schema.NullOr(
        Schema.Literals(["day", "week", "month", "year"]),
      ),
      recurring_interval_count: Schema.NullOr(Schema.Number),
      is_recurring: Schema.Boolean,
      is_archived: Schema.Boolean,
      organization_id: Schema.String,
      metadata: Schema.Record(Schema.String, Schema.Unknown),
      prices: Schema.Array(Schema.Unknown),
      benefits: Schema.Array(
        Schema.Struct({
          id: Schema.String,
          created_at: Schema.String,
          modified_at: Schema.NullOr(Schema.String),
          type: Schema.Literals([
            "custom",
            "discord",
            "github_repository",
            "downloadables",
            "license_keys",
            "meter_credit",
            "feature_flag",
          ]),
          description: Schema.String,
          selectable: Schema.Boolean,
          deletable: Schema.Boolean,
          is_deleted: Schema.Boolean,
          organization_id: Schema.String,
          metadata: Schema.Record(Schema.String, Schema.Unknown),
          properties: Schema.Record(Schema.String, Schema.Unknown),
        }),
      ),
      medias: Schema.Array(
        Schema.Struct({
          id: Schema.String,
          organization_id: Schema.String,
          name: Schema.String,
          path: Schema.String,
          mime_type: Schema.String,
          size: Schema.Number,
          storage_version: Schema.NullOr(Schema.String),
          checksum_etag: Schema.NullOr(Schema.String),
          checksum_sha256_base64: Schema.NullOr(Schema.String),
          checksum_sha256_hex: Schema.NullOr(Schema.String),
          last_modified_at: Schema.NullOr(Schema.String),
          version: Schema.NullOr(Schema.String),
          service: Schema.Literal("product_media"),
          is_uploaded: Schema.Boolean,
          created_at: Schema.String,
          size_readable: Schema.String,
          public_url: Schema.String,
        }),
      ),
      attached_custom_fields: Schema.Array(
        Schema.Struct({
          custom_field_id: Schema.String,
          custom_field: Schema.Struct({
            id: Schema.String,
            created_at: Schema.String,
            modified_at: Schema.NullOr(Schema.String),
            metadata: Schema.Record(Schema.String, Schema.Unknown),
            type: Schema.Literals([
              "text",
              "number",
              "date",
              "checkbox",
              "select",
            ]),
            slug: Schema.String,
            name: Schema.String,
            organization_id: Schema.String,
            properties: Schema.Record(Schema.String, Schema.Unknown),
          }),
          order: Schema.Number,
          required: Schema.Boolean,
        }),
      ),
    }),
    discount: Schema.NullOr(Schema.Unknown),
    prices: Schema.Array(Schema.Unknown),
    meters: Schema.Array(
      Schema.Struct({
        created_at: Schema.String,
        modified_at: Schema.NullOr(Schema.String),
        id: Schema.String,
        consumed_units: Schema.Number,
        credited_units: Schema.Number,
        amount: Schema.Number,
        meter_id: Schema.String,
        meter: Schema.Struct({
          metadata: Schema.Record(Schema.String, Schema.Unknown),
          created_at: Schema.String,
          modified_at: Schema.NullOr(Schema.String),
          id: Schema.String,
          name: Schema.String,
          unit: Schema.Literals(["scalar", "token", "custom"]),
          custom_label: Schema.optional(Schema.NullOr(Schema.String)),
          custom_multiplier: Schema.optional(Schema.NullOr(Schema.Number)),
          filter: Schema.Struct({
            conjunction: Schema.Literals(["and", "or"]),
            clauses: Schema.Array(Schema.Unknown),
          }),
          aggregation: Schema.Struct({
            func: Schema.Literals([
              "count",
              "sum",
              "max",
              "min",
              "avg",
              "unique",
            ]),
            property: Schema.optional(Schema.String),
          }),
          organization_id: Schema.String,
          archived_at: Schema.optional(Schema.NullOr(Schema.String)),
        }),
      }),
    ),
    pending_update: Schema.NullOr(
      Schema.Struct({
        created_at: Schema.String,
        modified_at: Schema.NullOr(Schema.String),
        id: Schema.String,
        applies_at: Schema.String,
        product_id: Schema.NullOr(Schema.String),
        seats: Schema.NullOr(Schema.Number),
      }),
    ),
  });
export type SubscriptionsrevokeOutput = typeof SubscriptionsrevokeOutput.Type;

// The operation
/**
 * Revoke Subscription
 *
 * Revoke a subscription, i.e cancel immediately.
 * **Scopes**: `subscriptions:write`
 *
 * @param id - The subscription ID.
 */
export const subscriptionsrevoke = /*@__PURE__*/ /*#__PURE__*/ API.make(() => ({
  inputSchema: SubscriptionsrevokeInput,
  outputSchema: SubscriptionsrevokeOutput,
  errors: [Forbidden, NotFound, Conflict, UnprocessableEntity] as const,
}));
