// AUTO-GENERATED by scripts/generate.ts from .generated-specs (specs/azure-rest-api-specs). Do not edit.
import * as S from "@distilled.cloud/core/schema";
import * as API from "@distilled.cloud/core/api";
import * as T from "../traits.ts";
import {
  AzureProtocol,
  type AzureOpError,
  type AzureOpContext,
} from "../protocol.ts";
import { UnknownAzureError } from "../errors.ts";
import * as Retry from "../retry.ts";

export type { AzureOpError, AzureOpContext };

/** Resource reference properties. */
export interface ResourceReferenceInput {}
export const ResourceReferenceInput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}),
).annotate({
  identifier: "ResourceReferenceInput",
}) as any as S.Schema<ResourceReferenceInput>;

/** Azure Traffic Collector resource properties. */
export interface AzureTrafficCollectorPropertiesFormatInput {
  /** The virtualHub to which the Azure Traffic Collector belongs. */
  virtualHub?: ResourceReferenceInput;
}
export const AzureTrafficCollectorPropertiesFormatInput =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      virtualHub: S.optional(ResourceReferenceInput),
    }),
  ).annotate({
    identifier: "AzureTrafficCollectorPropertiesFormatInput",
  }) as any as S.Schema<AzureTrafficCollectorPropertiesFormatInput>;

/** Resource tags. */
export type AzureTrafficCollectorsCreateOrUpdateRequestTagsMap = {
  [key: string]: string | undefined;
};
export const AzureTrafficCollectorsCreateOrUpdateRequestTagsMap =
  /*@__PURE__*/ S.Record(
    S.String,
    S.String,
  ) as any as S.Schema<AzureTrafficCollectorsCreateOrUpdateRequestTagsMap>;

export interface AzureTrafficCollectorsCreateOrUpdateRequest {
  /** The ID of the target subscription. */
  subscriptionId: string;
  /** The name of the resource group. The name is case insensitive. */
  resourceGroupName: string;
  /** Azure Traffic Collector name */
  azureTrafficCollectorName: string;
  /** Properties of the Azure Traffic Collector. */
  properties?: AzureTrafficCollectorPropertiesFormatInput;
  /** Resource location. */
  location: string;
  /** Resource tags. */
  tags?: AzureTrafficCollectorsCreateOrUpdateRequestTagsMap;
}
export const AzureTrafficCollectorsCreateOrUpdateRequest =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      subscriptionId: S.String.pipe(T.Label()),
      resourceGroupName: S.String.pipe(T.Label()),
      azureTrafficCollectorName: S.String.pipe(T.Label()),
      properties: S.optional(AzureTrafficCollectorPropertiesFormatInput),
      location: S.String,
      tags: S.optional(AzureTrafficCollectorsCreateOrUpdateRequestTagsMap),
    }).pipe(
      T.Http({
        method: "PUT",
        uri: "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.NetworkFunction/azureTrafficCollectors/{azureTrafficCollectorName}",
        code: 200,
        apiVersion: "2022-11-01",
      }),
    ),
  ).annotate({
    identifier: "AzureTrafficCollectorsCreateOrUpdateRequest",
  }) as any as S.Schema<AzureTrafficCollectorsCreateOrUpdateRequest>;

/** The type of identity that created the resource. */
export type SystemDataCreatedByType =
  | "User"
  | "Application"
  | "ManagedIdentity"
  | "Key";
export const SystemDataCreatedByType = /*@__PURE__*/ S.String;

/** The type of identity that last modified the resource. */
export type SystemDataLastModifiedByType =
  | "User"
  | "Application"
  | "ManagedIdentity"
  | "Key";
export const SystemDataLastModifiedByType = /*@__PURE__*/ S.String;

/** Metadata pertaining to creation and last modification of the resource. */
export interface SystemData {
  /** The identity that created the resource. */
  createdBy?: string;
  /** The type of identity that created the resource. */
  createdByType?: SystemDataCreatedByType;
  /** The timestamp of resource creation (UTC). */
  createdAt?: string;
  /** The identity that last modified the resource. */
  lastModifiedBy?: string;
  /** The type of identity that last modified the resource. */
  lastModifiedByType?: SystemDataLastModifiedByType;
  /** The timestamp of resource last modification (UTC) */
  lastModifiedAt?: string;
}
export const SystemData = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    createdBy: S.optional(S.String),
    createdByType: S.optional(SystemDataCreatedByType),
    createdAt: S.optional(S.String),
    lastModifiedBy: S.optional(S.String),
    lastModifiedByType: S.optional(SystemDataLastModifiedByType),
    lastModifiedAt: S.optional(S.String),
  }),
).annotate({ identifier: "SystemData" }) as any as S.Schema<SystemData>;

/** Resource reference properties. */
export interface ResourceReference {
  /** Resource ID. */
  id?: string;
}
export const ResourceReference = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.String),
  }),
).annotate({
  identifier: "ResourceReference",
}) as any as S.Schema<ResourceReference>;

/** Collector Policies for Azure Traffic Collector. */
export type AzureTrafficCollectorPropertiesFormatCollectorPoliciesList =
  Array<ResourceReference>;
export const AzureTrafficCollectorPropertiesFormatCollectorPoliciesList =
  /*@__PURE__*/ S.Array(
    ResourceReference,
  ) as any as S.Schema<AzureTrafficCollectorPropertiesFormatCollectorPoliciesList>;

/** The current provisioning state. */
export type ProvisioningState =
  | "Succeeded"
  | "Updating"
  | "Deleting"
  | "Failed";
export const ProvisioningState = /*@__PURE__*/ S.String;

/** Azure Traffic Collector resource properties. */
export interface AzureTrafficCollectorPropertiesFormat {
  /** Collector Policies for Azure Traffic Collector. */
  collectorPolicies?: AzureTrafficCollectorPropertiesFormatCollectorPoliciesList;
  /** The virtualHub to which the Azure Traffic Collector belongs. */
  virtualHub?: ResourceReference;
  /** The provisioning state of the application rule collection resource. */
  provisioningState?: ProvisioningState;
}
export const AzureTrafficCollectorPropertiesFormat = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      collectorPolicies: S.optional(
        AzureTrafficCollectorPropertiesFormatCollectorPoliciesList,
      ),
      virtualHub: S.optional(ResourceReference),
      provisioningState: S.optional(ProvisioningState),
    }),
).annotate({
  identifier: "AzureTrafficCollectorPropertiesFormat",
}) as any as S.Schema<AzureTrafficCollectorPropertiesFormat>;

/** Resource tags. */
export type AzureTrafficCollectorsCreateOrUpdateResponseTagsMap = {
  [key: string]: string | undefined;
};
export const AzureTrafficCollectorsCreateOrUpdateResponseTagsMap =
  /*@__PURE__*/ S.Record(
    S.String,
    S.String,
  ) as any as S.Schema<AzureTrafficCollectorsCreateOrUpdateResponseTagsMap>;

export interface AzureTrafficCollectorsCreateOrUpdateResponse {
  /** Fully qualified resource ID for the resource. Ex - /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{resourceType}/{resourceName} */
  id?: string;
  /** The name of the resource */
  name?: string;
  /** The type of the resource. E.g. "Microsoft.Compute/virtualMachines" or "Microsoft.Storage/storageAccounts" */
  type?: string;
  /** Azure Resource Manager metadata containing createdBy and modifiedBy information. */
  systemData?: SystemData;
  /** Properties of the Azure Traffic Collector. */
  properties?: AzureTrafficCollectorPropertiesFormat;
  /** Resource location. */
  location: string;
  /** Resource tags. */
  tags?: AzureTrafficCollectorsCreateOrUpdateResponseTagsMap;
  /** A unique read-only string that changes whenever the resource is updated. */
  etag?: string;
}
export const AzureTrafficCollectorsCreateOrUpdateResponse =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      id: S.optional(S.String),
      name: S.optional(S.String),
      type: S.optional(S.String),
      systemData: S.optional(SystemData),
      properties: S.optional(AzureTrafficCollectorPropertiesFormat),
      location: S.String,
      tags: S.optional(AzureTrafficCollectorsCreateOrUpdateResponseTagsMap),
      etag: S.optional(S.String),
    }),
  ).annotate({
    identifier: "AzureTrafficCollectorsCreateOrUpdateResponse",
  }) as any as S.Schema<AzureTrafficCollectorsCreateOrUpdateResponse>;

/** The ingestion type. */
export type IngestionType = "IPFIX";
export const IngestionType = /*@__PURE__*/ S.String;

/** Ingestion source type. */
export type SourceType = "Resource";
export const SourceType = /*@__PURE__*/ S.String;

/** Ingestion policy properties. */
export interface IngestionSourcesPropertiesFormat {
  /** Ingestion source type. */
  sourceType?: SourceType | (string & {});
  /** Resource ID. */
  resourceId?: string;
}
export const IngestionSourcesPropertiesFormat = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    sourceType: S.optional(SourceType),
    resourceId: S.optional(S.String),
  }),
).annotate({
  identifier: "IngestionSourcesPropertiesFormat",
}) as any as S.Schema<IngestionSourcesPropertiesFormat>;

/** Ingestion Sources. */
export type IngestionPolicyPropertiesFormatIngestionSourcesList =
  Array<IngestionSourcesPropertiesFormat>;
export const IngestionPolicyPropertiesFormatIngestionSourcesList =
  /*@__PURE__*/ S.Array(
    IngestionSourcesPropertiesFormat,
  ) as any as S.Schema<IngestionPolicyPropertiesFormatIngestionSourcesList>;

/** Ingestion Policy properties. */
export interface IngestionPolicyPropertiesFormat {
  /** The ingestion type. */
  ingestionType?: IngestionType | (string & {});
  /** Ingestion Sources. */
  ingestionSources?: IngestionPolicyPropertiesFormatIngestionSourcesList;
}
export const IngestionPolicyPropertiesFormat = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    ingestionType: S.optional(IngestionType),
    ingestionSources: S.optional(
      IngestionPolicyPropertiesFormatIngestionSourcesList,
    ),
  }),
).annotate({
  identifier: "IngestionPolicyPropertiesFormat",
}) as any as S.Schema<IngestionPolicyPropertiesFormat>;

/** Emission format type. */
export type EmissionType = "IPFIX";
export const EmissionType = /*@__PURE__*/ S.String;

/** Emission destination type. */
export type DestinationType = "AzureMonitor";
export const DestinationType = /*@__PURE__*/ S.String;

/** Emission policy destination properties. */
export interface EmissionPolicyDestination {
  /** Emission destination type. */
  destinationType?: DestinationType | (string & {});
}
export const EmissionPolicyDestination = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    destinationType: S.optional(DestinationType),
  }),
).annotate({
  identifier: "EmissionPolicyDestination",
}) as any as S.Schema<EmissionPolicyDestination>;

/** Emission policy destinations. */
export type EmissionPoliciesPropertiesFormatEmissionDestinationsList =
  Array<EmissionPolicyDestination>;
export const EmissionPoliciesPropertiesFormatEmissionDestinationsList =
  /*@__PURE__*/ S.Array(
    EmissionPolicyDestination,
  ) as any as S.Schema<EmissionPoliciesPropertiesFormatEmissionDestinationsList>;

/** Emission policy properties. */
export interface EmissionPoliciesPropertiesFormat {
  /** Emission format type. */
  emissionType?: EmissionType | (string & {});
  /** Emission policy destinations. */
  emissionDestinations?: EmissionPoliciesPropertiesFormatEmissionDestinationsList;
}
export const EmissionPoliciesPropertiesFormat = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    emissionType: S.optional(EmissionType),
    emissionDestinations: S.optional(
      EmissionPoliciesPropertiesFormatEmissionDestinationsList,
    ),
  }),
).annotate({
  identifier: "EmissionPoliciesPropertiesFormat",
}) as any as S.Schema<EmissionPoliciesPropertiesFormat>;

/** Emission policies. */
export type CollectorPolicyPropertiesFormatEmissionPoliciesList =
  Array<EmissionPoliciesPropertiesFormat>;
export const CollectorPolicyPropertiesFormatEmissionPoliciesList =
  /*@__PURE__*/ S.Array(
    EmissionPoliciesPropertiesFormat,
  ) as any as S.Schema<CollectorPolicyPropertiesFormatEmissionPoliciesList>;

/** Collection policy properties. */
export interface CollectorPolicyPropertiesFormat {
  /** Ingestion policies. */
  ingestionPolicy?: IngestionPolicyPropertiesFormat;
  /** Emission policies. */
  emissionPolicies?: CollectorPolicyPropertiesFormatEmissionPoliciesList;
  /** The provisioning state. */
  provisioningState?: ProvisioningState | (string & {});
}
export const CollectorPolicyPropertiesFormat = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    ingestionPolicy: S.optional(IngestionPolicyPropertiesFormat),
    emissionPolicies: S.optional(
      CollectorPolicyPropertiesFormatEmissionPoliciesList,
    ),
    provisioningState: S.optional(ProvisioningState),
  }),
).annotate({
  identifier: "CollectorPolicyPropertiesFormat",
}) as any as S.Schema<CollectorPolicyPropertiesFormat>;

/** Resource tags. */
export type CollectorPoliciesCreateOrUpdateRequestTagsMap = {
  [key: string]: string | undefined;
};
export const CollectorPoliciesCreateOrUpdateRequestTagsMap =
  /*@__PURE__*/ S.Record(
    S.String,
    S.String,
  ) as any as S.Schema<CollectorPoliciesCreateOrUpdateRequestTagsMap>;

export interface CollectorPoliciesCreateOrUpdateRequest {
  /** The ID of the target subscription. */
  subscriptionId: string;
  /** The name of the resource group. The name is case insensitive. */
  resourceGroupName: string;
  /** Azure Traffic Collector name */
  azureTrafficCollectorName: string;
  /** Collector Policy Name */
  collectorPolicyName: string;
  /** Properties of the Collector Policy. */
  properties?: CollectorPolicyPropertiesFormat;
  /** Resource location. */
  location: string;
  /** Resource tags. */
  tags?: CollectorPoliciesCreateOrUpdateRequestTagsMap;
}
export const CollectorPoliciesCreateOrUpdateRequest = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      subscriptionId: S.String.pipe(T.Label()),
      resourceGroupName: S.String.pipe(T.Label()),
      azureTrafficCollectorName: S.String.pipe(T.Label()),
      collectorPolicyName: S.String.pipe(T.Label()),
      properties: S.optional(CollectorPolicyPropertiesFormat),
      location: S.String,
      tags: S.optional(CollectorPoliciesCreateOrUpdateRequestTagsMap),
    }).pipe(
      T.Http({
        method: "PUT",
        uri: "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.NetworkFunction/azureTrafficCollectors/{azureTrafficCollectorName}/collectorPolicies/{collectorPolicyName}",
        code: 200,
        apiVersion: "2022-11-01",
      }),
    ),
).annotate({
  identifier: "CollectorPoliciesCreateOrUpdateRequest",
}) as any as S.Schema<CollectorPoliciesCreateOrUpdateRequest>;

/** Resource tags. */
export type CollectorPoliciesCreateOrUpdateResponseTagsMap = {
  [key: string]: string | undefined;
};
export const CollectorPoliciesCreateOrUpdateResponseTagsMap =
  /*@__PURE__*/ S.Record(
    S.String,
    S.String,
  ) as any as S.Schema<CollectorPoliciesCreateOrUpdateResponseTagsMap>;

export interface CollectorPoliciesCreateOrUpdateResponse {
  /** Fully qualified resource ID for the resource. Ex - /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{resourceType}/{resourceName} */
  id?: string;
  /** The name of the resource */
  name?: string;
  /** The type of the resource. E.g. "Microsoft.Compute/virtualMachines" or "Microsoft.Storage/storageAccounts" */
  type?: string;
  /** Azure Resource Manager metadata containing createdBy and modifiedBy information. */
  systemData?: SystemData;
  /** Properties of the Collector Policy. */
  properties?: CollectorPolicyPropertiesFormat;
  /** Resource location. */
  location: string;
  /** Resource tags. */
  tags?: CollectorPoliciesCreateOrUpdateResponseTagsMap;
  /** A unique read-only string that changes whenever the resource is updated. */
  etag?: string;
}
export const CollectorPoliciesCreateOrUpdateResponse = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      id: S.optional(S.String),
      name: S.optional(S.String),
      type: S.optional(S.String),
      systemData: S.optional(SystemData),
      properties: S.optional(CollectorPolicyPropertiesFormat),
      location: S.String,
      tags: S.optional(CollectorPoliciesCreateOrUpdateResponseTagsMap),
      etag: S.optional(S.String),
    }),
).annotate({
  identifier: "CollectorPoliciesCreateOrUpdateResponse",
}) as any as S.Schema<CollectorPoliciesCreateOrUpdateResponse>;

export interface DeleteAzureTrafficCollectorRequest {
  /** The ID of the target subscription. */
  subscriptionId: string;
  /** The name of the resource group. The name is case insensitive. */
  resourceGroupName: string;
  /** Azure Traffic Collector name */
  azureTrafficCollectorName: string;
}
export const DeleteAzureTrafficCollectorRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    subscriptionId: S.String.pipe(T.Label()),
    resourceGroupName: S.String.pipe(T.Label()),
    azureTrafficCollectorName: S.String.pipe(T.Label()),
  }).pipe(
    T.Http({
      method: "DELETE",
      uri: "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.NetworkFunction/azureTrafficCollectors/{azureTrafficCollectorName}",
      code: 200,
      apiVersion: "2022-11-01",
    }),
  ),
).annotate({
  identifier: "DeleteAzureTrafficCollectorRequest",
}) as any as S.Schema<DeleteAzureTrafficCollectorRequest>;

export interface DeleteAzureTrafficCollectorResponse {}
export const DeleteAzureTrafficCollectorResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}),
).annotate({
  identifier: "DeleteAzureTrafficCollectorResponse",
}) as any as S.Schema<DeleteAzureTrafficCollectorResponse>;

export interface DeleteCollectorPolicyRequest {
  /** The ID of the target subscription. */
  subscriptionId: string;
  /** The name of the resource group. The name is case insensitive. */
  resourceGroupName: string;
  /** Azure Traffic Collector name */
  azureTrafficCollectorName: string;
  /** Collector Policy Name */
  collectorPolicyName: string;
}
export const DeleteCollectorPolicyRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    subscriptionId: S.String.pipe(T.Label()),
    resourceGroupName: S.String.pipe(T.Label()),
    azureTrafficCollectorName: S.String.pipe(T.Label()),
    collectorPolicyName: S.String.pipe(T.Label()),
  }).pipe(
    T.Http({
      method: "DELETE",
      uri: "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.NetworkFunction/azureTrafficCollectors/{azureTrafficCollectorName}/collectorPolicies/{collectorPolicyName}",
      code: 200,
      apiVersion: "2022-11-01",
    }),
  ),
).annotate({
  identifier: "DeleteCollectorPolicyRequest",
}) as any as S.Schema<DeleteCollectorPolicyRequest>;

export interface DeleteCollectorPolicyResponse {}
export const DeleteCollectorPolicyResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}),
).annotate({
  identifier: "DeleteCollectorPolicyResponse",
}) as any as S.Schema<DeleteCollectorPolicyResponse>;

export interface GetAzureTrafficCollectorRequest {
  /** The ID of the target subscription. */
  subscriptionId: string;
  /** The name of the resource group. The name is case insensitive. */
  resourceGroupName: string;
  /** Azure Traffic Collector name */
  azureTrafficCollectorName: string;
}
export const GetAzureTrafficCollectorRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    subscriptionId: S.String.pipe(T.Label()),
    resourceGroupName: S.String.pipe(T.Label()),
    azureTrafficCollectorName: S.String.pipe(T.Label()),
  }).pipe(
    T.Http({
      method: "GET",
      uri: "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.NetworkFunction/azureTrafficCollectors/{azureTrafficCollectorName}",
      code: 200,
      apiVersion: "2022-11-01",
    }),
  ),
).annotate({
  identifier: "GetAzureTrafficCollectorRequest",
}) as any as S.Schema<GetAzureTrafficCollectorRequest>;

/** Resource tags. */
export type AzureTrafficCollectorsGetResponseTagsMap = {
  [key: string]: string | undefined;
};
export const AzureTrafficCollectorsGetResponseTagsMap = /*@__PURE__*/ S.Record(
  S.String,
  S.String,
) as any as S.Schema<AzureTrafficCollectorsGetResponseTagsMap>;

export interface GetAzureTrafficCollectorResponse {
  /** Fully qualified resource ID for the resource. Ex - /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{resourceType}/{resourceName} */
  id?: string;
  /** The name of the resource */
  name?: string;
  /** The type of the resource. E.g. "Microsoft.Compute/virtualMachines" or "Microsoft.Storage/storageAccounts" */
  type?: string;
  /** Azure Resource Manager metadata containing createdBy and modifiedBy information. */
  systemData?: SystemData;
  /** Properties of the Azure Traffic Collector. */
  properties?: AzureTrafficCollectorPropertiesFormat;
  /** Resource location. */
  location: string;
  /** Resource tags. */
  tags?: AzureTrafficCollectorsGetResponseTagsMap;
  /** A unique read-only string that changes whenever the resource is updated. */
  etag?: string;
}
export const GetAzureTrafficCollectorResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.String),
    name: S.optional(S.String),
    type: S.optional(S.String),
    systemData: S.optional(SystemData),
    properties: S.optional(AzureTrafficCollectorPropertiesFormat),
    location: S.String,
    tags: S.optional(AzureTrafficCollectorsGetResponseTagsMap),
    etag: S.optional(S.String),
  }),
).annotate({
  identifier: "GetAzureTrafficCollectorResponse",
}) as any as S.Schema<GetAzureTrafficCollectorResponse>;

export interface GetCollectorPolicyRequest {
  /** The ID of the target subscription. */
  subscriptionId: string;
  /** The name of the resource group. The name is case insensitive. */
  resourceGroupName: string;
  /** Azure Traffic Collector name */
  azureTrafficCollectorName: string;
  /** Collector Policy Name */
  collectorPolicyName: string;
}
export const GetCollectorPolicyRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    subscriptionId: S.String.pipe(T.Label()),
    resourceGroupName: S.String.pipe(T.Label()),
    azureTrafficCollectorName: S.String.pipe(T.Label()),
    collectorPolicyName: S.String.pipe(T.Label()),
  }).pipe(
    T.Http({
      method: "GET",
      uri: "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.NetworkFunction/azureTrafficCollectors/{azureTrafficCollectorName}/collectorPolicies/{collectorPolicyName}",
      code: 200,
      apiVersion: "2022-11-01",
    }),
  ),
).annotate({
  identifier: "GetCollectorPolicyRequest",
}) as any as S.Schema<GetCollectorPolicyRequest>;

/** Resource tags. */
export type CollectorPoliciesGetResponseTagsMap = {
  [key: string]: string | undefined;
};
export const CollectorPoliciesGetResponseTagsMap = /*@__PURE__*/ S.Record(
  S.String,
  S.String,
) as any as S.Schema<CollectorPoliciesGetResponseTagsMap>;

export interface GetCollectorPolicyResponse {
  /** Fully qualified resource ID for the resource. Ex - /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{resourceType}/{resourceName} */
  id?: string;
  /** The name of the resource */
  name?: string;
  /** The type of the resource. E.g. "Microsoft.Compute/virtualMachines" or "Microsoft.Storage/storageAccounts" */
  type?: string;
  /** Azure Resource Manager metadata containing createdBy and modifiedBy information. */
  systemData?: SystemData;
  /** Properties of the Collector Policy. */
  properties?: CollectorPolicyPropertiesFormat;
  /** Resource location. */
  location: string;
  /** Resource tags. */
  tags?: CollectorPoliciesGetResponseTagsMap;
  /** A unique read-only string that changes whenever the resource is updated. */
  etag?: string;
}
export const GetCollectorPolicyResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.String),
    name: S.optional(S.String),
    type: S.optional(S.String),
    systemData: S.optional(SystemData),
    properties: S.optional(CollectorPolicyPropertiesFormat),
    location: S.String,
    tags: S.optional(CollectorPoliciesGetResponseTagsMap),
    etag: S.optional(S.String),
  }),
).annotate({
  identifier: "GetCollectorPolicyResponse",
}) as any as S.Schema<GetCollectorPolicyResponse>;

export interface ListAzureTrafficCollectorByResourceGroupRequest {
  /** The ID of the target subscription. */
  subscriptionId: string;
  /** The name of the resource group. The name is case insensitive. */
  resourceGroupName: string;
}
export const ListAzureTrafficCollectorByResourceGroupRequest =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      subscriptionId: S.String.pipe(T.Label()),
      resourceGroupName: S.String.pipe(T.Label()),
    }).pipe(
      T.Http({
        method: "GET",
        uri: "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.NetworkFunction/azureTrafficCollectors",
        code: 200,
        apiVersion: "2022-11-01",
      }),
    ),
  ).annotate({
    identifier: "ListAzureTrafficCollectorByResourceGroupRequest",
  }) as any as S.Schema<ListAzureTrafficCollectorByResourceGroupRequest>;

/** Resource tags. */
export type AzureTrafficCollectorTagsMap = {
  [key: string]: string | undefined;
};
export const AzureTrafficCollectorTagsMap = /*@__PURE__*/ S.Record(
  S.String,
  S.String,
) as any as S.Schema<AzureTrafficCollectorTagsMap>;

/** Azure Traffic Collector resource. */
export interface AzureTrafficCollector {
  /** Fully qualified resource ID for the resource. Ex - /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{resourceType}/{resourceName} */
  id?: string;
  /** The name of the resource */
  name?: string;
  /** The type of the resource. E.g. "Microsoft.Compute/virtualMachines" or "Microsoft.Storage/storageAccounts" */
  type?: string;
  /** Azure Resource Manager metadata containing createdBy and modifiedBy information. */
  systemData?: SystemData;
  /** Properties of the Azure Traffic Collector. */
  properties?: AzureTrafficCollectorPropertiesFormat;
  /** Resource location. */
  location: string;
  /** Resource tags. */
  tags?: AzureTrafficCollectorTagsMap;
  /** A unique read-only string that changes whenever the resource is updated. */
  etag?: string;
}
export const AzureTrafficCollector = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.String),
    name: S.optional(S.String),
    type: S.optional(S.String),
    systemData: S.optional(SystemData),
    properties: S.optional(AzureTrafficCollectorPropertiesFormat),
    location: S.String,
    tags: S.optional(AzureTrafficCollectorTagsMap),
    etag: S.optional(S.String),
  }),
).annotate({
  identifier: "AzureTrafficCollector",
}) as any as S.Schema<AzureTrafficCollector>;

/** The AzureTrafficCollector items on this page */
export type AzureTrafficCollectorListResultValueList =
  Array<AzureTrafficCollector>;
export const AzureTrafficCollectorListResultValueList = /*@__PURE__*/ S.Array(
  AzureTrafficCollector,
) as any as S.Schema<AzureTrafficCollectorListResultValueList>;

/** The response of a AzureTrafficCollector list operation. */
export interface AzureTrafficCollectorListResult {
  /** The AzureTrafficCollector items on this page */
  value: AzureTrafficCollectorListResultValueList;
  /** The link to the next page of items */
  nextLink?: string;
}
export const AzureTrafficCollectorListResult = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    value: AzureTrafficCollectorListResultValueList,
    nextLink: S.optional(S.String),
  }),
).annotate({
  identifier: "AzureTrafficCollectorListResult",
}) as any as S.Schema<AzureTrafficCollectorListResult>;

export interface ListAzureTrafficCollectorBySubscriptionRequest {
  /** The ID of the target subscription. */
  subscriptionId: string;
}
export const ListAzureTrafficCollectorBySubscriptionRequest =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      subscriptionId: S.String.pipe(T.Label()),
    }).pipe(
      T.Http({
        method: "GET",
        uri: "/subscriptions/{subscriptionId}/providers/Microsoft.NetworkFunction/azureTrafficCollectors",
        code: 200,
        apiVersion: "2022-11-01",
      }),
    ),
  ).annotate({
    identifier: "ListAzureTrafficCollectorBySubscriptionRequest",
  }) as any as S.Schema<ListAzureTrafficCollectorBySubscriptionRequest>;

export interface ListCollectorPoliciesRequest {
  /** The ID of the target subscription. */
  subscriptionId: string;
  /** The name of the resource group. The name is case insensitive. */
  resourceGroupName: string;
  /** Azure Traffic Collector name */
  azureTrafficCollectorName: string;
}
export const ListCollectorPoliciesRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    subscriptionId: S.String.pipe(T.Label()),
    resourceGroupName: S.String.pipe(T.Label()),
    azureTrafficCollectorName: S.String.pipe(T.Label()),
  }).pipe(
    T.Http({
      method: "GET",
      uri: "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.NetworkFunction/azureTrafficCollectors/{azureTrafficCollectorName}/collectorPolicies",
      code: 200,
      apiVersion: "2022-11-01",
    }),
  ),
).annotate({
  identifier: "ListCollectorPoliciesRequest",
}) as any as S.Schema<ListCollectorPoliciesRequest>;

/** Resource tags. */
export type CollectorPolicyTagsMap = { [key: string]: string | undefined };
export const CollectorPolicyTagsMap = /*@__PURE__*/ S.Record(
  S.String,
  S.String,
) as any as S.Schema<CollectorPolicyTagsMap>;

/** Collector policy resource. */
export interface CollectorPolicy {
  /** Fully qualified resource ID for the resource. Ex - /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{resourceType}/{resourceName} */
  id?: string;
  /** The name of the resource */
  name?: string;
  /** The type of the resource. E.g. "Microsoft.Compute/virtualMachines" or "Microsoft.Storage/storageAccounts" */
  type?: string;
  /** Azure Resource Manager metadata containing createdBy and modifiedBy information. */
  systemData?: SystemData;
  /** Properties of the Collector Policy. */
  properties?: CollectorPolicyPropertiesFormat;
  /** Resource location. */
  location: string;
  /** Resource tags. */
  tags?: CollectorPolicyTagsMap;
  /** A unique read-only string that changes whenever the resource is updated. */
  etag?: string;
}
export const CollectorPolicy = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.String),
    name: S.optional(S.String),
    type: S.optional(S.String),
    systemData: S.optional(SystemData),
    properties: S.optional(CollectorPolicyPropertiesFormat),
    location: S.String,
    tags: S.optional(CollectorPolicyTagsMap),
    etag: S.optional(S.String),
  }),
).annotate({
  identifier: "CollectorPolicy",
}) as any as S.Schema<CollectorPolicy>;

/** The CollectorPolicy items on this page */
export type CollectorPolicyListResultValueList = Array<CollectorPolicy>;
export const CollectorPolicyListResultValueList = /*@__PURE__*/ S.Array(
  CollectorPolicy,
) as any as S.Schema<CollectorPolicyListResultValueList>;

/** The response of a CollectorPolicy list operation. */
export interface CollectorPolicyListResult {
  /** The CollectorPolicy items on this page */
  value: CollectorPolicyListResultValueList;
  /** The link to the next page of items */
  nextLink?: string;
}
export const CollectorPolicyListResult = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    value: CollectorPolicyListResultValueList,
    nextLink: S.optional(S.String),
  }),
).annotate({
  identifier: "CollectorPolicyListResult",
}) as any as S.Schema<CollectorPolicyListResult>;

export interface ListNetworkFunctionOperationsRequest {}
export const ListNetworkFunctionOperationsRequest = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({}).pipe(
      T.Http({
        method: "GET",
        uri: "/providers/Microsoft.NetworkFunction/operations",
        code: 200,
        apiVersion: "2022-11-01",
      }),
    ),
).annotate({
  identifier: "ListNetworkFunctionOperationsRequest",
}) as any as S.Schema<ListNetworkFunctionOperationsRequest>;

/** Display metadata associated with the operation. */
export interface OperationDisplay {
  /** Service provider: Microsoft NetworkFunction. */
  provider?: string;
  /** Resource on which the operation is performed etc. */
  resource?: string;
  /** Type of operation: get, read, delete, etc. */
  operation?: string;
  /** Description of the operation. */
  description?: string;
}
export const OperationDisplay = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    provider: S.optional(S.String),
    resource: S.optional(S.String),
    operation: S.optional(S.String),
    description: S.optional(S.String),
  }),
).annotate({
  identifier: "OperationDisplay",
}) as any as S.Schema<OperationDisplay>;

/** Azure Traffic Collector REST API operation definition. */
export interface Operation {
  /** Operation name: {provider}/{resource}/{operation} */
  name?: string;
  /** Indicates whether the operation is a data action */
  isDataAction?: boolean;
  /** Display metadata associated with the operation. */
  display?: OperationDisplay;
  /** Origin of the operation */
  origin?: string;
}
export const Operation = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    name: S.optional(S.String),
    isDataAction: S.optional(S.Boolean),
    display: S.optional(OperationDisplay),
    origin: S.optional(S.String),
  }),
).annotate({ identifier: "Operation" }) as any as S.Schema<Operation>;

/** The Operation items on this page */
export type OperationListResultValueList = Array<Operation>;
export const OperationListResultValueList = /*@__PURE__*/ S.Array(
  Operation,
) as any as S.Schema<OperationListResultValueList>;

/** Paged collection of Operation items */
export interface OperationListResult {
  /** The Operation items on this page */
  value: OperationListResultValueList;
  /** The link to the next page of items */
  nextLink?: string;
}
export const OperationListResult = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    value: OperationListResultValueList,
    nextLink: S.optional(S.String),
  }),
).annotate({
  identifier: "OperationListResult",
}) as any as S.Schema<OperationListResult>;

/** Resource tags. */
export type AzureTrafficCollectorsUpdateTagsRequestTagsMap = {
  [key: string]: string | undefined;
};
export const AzureTrafficCollectorsUpdateTagsRequestTagsMap =
  /*@__PURE__*/ S.Record(
    S.String,
    S.String,
  ) as any as S.Schema<AzureTrafficCollectorsUpdateTagsRequestTagsMap>;

export interface UpdateAzureTrafficCollectorTagRequest {
  /** The ID of the target subscription. */
  subscriptionId: string;
  /** The name of the resource group. The name is case insensitive. */
  resourceGroupName: string;
  /** Azure Traffic Collector name */
  azureTrafficCollectorName: string;
  /** Resource tags. */
  tags?: AzureTrafficCollectorsUpdateTagsRequestTagsMap;
}
export const UpdateAzureTrafficCollectorTagRequest = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      subscriptionId: S.String.pipe(T.Label()),
      resourceGroupName: S.String.pipe(T.Label()),
      azureTrafficCollectorName: S.String.pipe(T.Label()),
      tags: S.optional(AzureTrafficCollectorsUpdateTagsRequestTagsMap),
    }).pipe(
      T.Http({
        method: "PATCH",
        uri: "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.NetworkFunction/azureTrafficCollectors/{azureTrafficCollectorName}",
        code: 200,
        apiVersion: "2022-11-01",
      }),
    ),
).annotate({
  identifier: "UpdateAzureTrafficCollectorTagRequest",
}) as any as S.Schema<UpdateAzureTrafficCollectorTagRequest>;

/** Resource tags. */
export type AzureTrafficCollectorsUpdateTagsResponseTagsMap = {
  [key: string]: string | undefined;
};
export const AzureTrafficCollectorsUpdateTagsResponseTagsMap =
  /*@__PURE__*/ S.Record(
    S.String,
    S.String,
  ) as any as S.Schema<AzureTrafficCollectorsUpdateTagsResponseTagsMap>;

export interface UpdateAzureTrafficCollectorTagResponse {
  /** Fully qualified resource ID for the resource. Ex - /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{resourceType}/{resourceName} */
  id?: string;
  /** The name of the resource */
  name?: string;
  /** The type of the resource. E.g. "Microsoft.Compute/virtualMachines" or "Microsoft.Storage/storageAccounts" */
  type?: string;
  /** Azure Resource Manager metadata containing createdBy and modifiedBy information. */
  systemData?: SystemData;
  /** Properties of the Azure Traffic Collector. */
  properties?: AzureTrafficCollectorPropertiesFormat;
  /** Resource location. */
  location: string;
  /** Resource tags. */
  tags?: AzureTrafficCollectorsUpdateTagsResponseTagsMap;
  /** A unique read-only string that changes whenever the resource is updated. */
  etag?: string;
}
export const UpdateAzureTrafficCollectorTagResponse = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      id: S.optional(S.String),
      name: S.optional(S.String),
      type: S.optional(S.String),
      systemData: S.optional(SystemData),
      properties: S.optional(AzureTrafficCollectorPropertiesFormat),
      location: S.String,
      tags: S.optional(AzureTrafficCollectorsUpdateTagsResponseTagsMap),
      etag: S.optional(S.String),
    }),
).annotate({
  identifier: "UpdateAzureTrafficCollectorTagResponse",
}) as any as S.Schema<UpdateAzureTrafficCollectorTagResponse>;

/** Resource tags. */
export type CollectorPoliciesUpdateTagsRequestTagsMap = {
  [key: string]: string | undefined;
};
export const CollectorPoliciesUpdateTagsRequestTagsMap = /*@__PURE__*/ S.Record(
  S.String,
  S.String,
) as any as S.Schema<CollectorPoliciesUpdateTagsRequestTagsMap>;

export interface UpdateCollectorPolicyTagRequest {
  /** The ID of the target subscription. */
  subscriptionId: string;
  /** The name of the resource group. The name is case insensitive. */
  resourceGroupName: string;
  /** Azure Traffic Collector name */
  azureTrafficCollectorName: string;
  /** Collector Policy Name */
  collectorPolicyName: string;
  /** Resource tags. */
  tags?: CollectorPoliciesUpdateTagsRequestTagsMap;
}
export const UpdateCollectorPolicyTagRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    subscriptionId: S.String.pipe(T.Label()),
    resourceGroupName: S.String.pipe(T.Label()),
    azureTrafficCollectorName: S.String.pipe(T.Label()),
    collectorPolicyName: S.String.pipe(T.Label()),
    tags: S.optional(CollectorPoliciesUpdateTagsRequestTagsMap),
  }).pipe(
    T.Http({
      method: "PATCH",
      uri: "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.NetworkFunction/azureTrafficCollectors/{azureTrafficCollectorName}/collectorPolicies/{collectorPolicyName}",
      code: 200,
      apiVersion: "2022-11-01",
    }),
  ),
).annotate({
  identifier: "UpdateCollectorPolicyTagRequest",
}) as any as S.Schema<UpdateCollectorPolicyTagRequest>;

/** Resource tags. */
export type CollectorPoliciesUpdateTagsResponseTagsMap = {
  [key: string]: string | undefined;
};
export const CollectorPoliciesUpdateTagsResponseTagsMap =
  /*@__PURE__*/ S.Record(
    S.String,
    S.String,
  ) as any as S.Schema<CollectorPoliciesUpdateTagsResponseTagsMap>;

export interface UpdateCollectorPolicyTagResponse {
  /** Fully qualified resource ID for the resource. Ex - /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{resourceType}/{resourceName} */
  id?: string;
  /** The name of the resource */
  name?: string;
  /** The type of the resource. E.g. "Microsoft.Compute/virtualMachines" or "Microsoft.Storage/storageAccounts" */
  type?: string;
  /** Azure Resource Manager metadata containing createdBy and modifiedBy information. */
  systemData?: SystemData;
  /** Properties of the Collector Policy. */
  properties?: CollectorPolicyPropertiesFormat;
  /** Resource location. */
  location: string;
  /** Resource tags. */
  tags?: CollectorPoliciesUpdateTagsResponseTagsMap;
  /** A unique read-only string that changes whenever the resource is updated. */
  etag?: string;
}
export const UpdateCollectorPolicyTagResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.String),
    name: S.optional(S.String),
    type: S.optional(S.String),
    systemData: S.optional(SystemData),
    properties: S.optional(CollectorPolicyPropertiesFormat),
    location: S.String,
    tags: S.optional(CollectorPoliciesUpdateTagsResponseTagsMap),
    etag: S.optional(S.String),
  }),
).annotate({
  identifier: "UpdateCollectorPolicyTagResponse",
}) as any as S.Schema<UpdateCollectorPolicyTagResponse>;

export type AzureTrafficCollectorsCreateOrUpdateError = AzureOpError;
/** Creates or updates a Azure Traffic Collector resource */
export const AzureTrafficCollectorsCreateOrUpdate: API.OperationMethod<
  AzureTrafficCollectorsCreateOrUpdateRequest,
  AzureTrafficCollectorsCreateOrUpdateResponse,
  AzureTrafficCollectorsCreateOrUpdateError,
  AzureOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: AzureTrafficCollectorsCreateOrUpdateRequest,
  output: AzureTrafficCollectorsCreateOrUpdateResponse,
  errors: [UnknownAzureError],
  protocol: AzureProtocol,
  retry: Retry.Retry,
}));

export type CollectorPoliciesCreateOrUpdateError = AzureOpError;
/** Creates or updates a Collector Policy resource */
export const CollectorPoliciesCreateOrUpdate: API.OperationMethod<
  CollectorPoliciesCreateOrUpdateRequest,
  CollectorPoliciesCreateOrUpdateResponse,
  CollectorPoliciesCreateOrUpdateError,
  AzureOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CollectorPoliciesCreateOrUpdateRequest,
  output: CollectorPoliciesCreateOrUpdateResponse,
  errors: [UnknownAzureError],
  protocol: AzureProtocol,
  retry: Retry.Retry,
}));

export type DeleteAzureTrafficCollectorError = AzureOpError;
/** Deletes a specified Azure Traffic Collector resource. */
export const DeleteAzureTrafficCollector: API.OperationMethod<
  DeleteAzureTrafficCollectorRequest,
  DeleteAzureTrafficCollectorResponse,
  DeleteAzureTrafficCollectorError,
  AzureOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: DeleteAzureTrafficCollectorRequest,
  output: DeleteAzureTrafficCollectorResponse,
  errors: [UnknownAzureError],
  protocol: AzureProtocol,
  retry: Retry.Retry,
}));

export type DeleteCollectorPolicyError = AzureOpError;
/** Deletes a specified Collector Policy resource. */
export const DeleteCollectorPolicy: API.OperationMethod<
  DeleteCollectorPolicyRequest,
  DeleteCollectorPolicyResponse,
  DeleteCollectorPolicyError,
  AzureOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: DeleteCollectorPolicyRequest,
  output: DeleteCollectorPolicyResponse,
  errors: [UnknownAzureError],
  protocol: AzureProtocol,
  retry: Retry.Retry,
}));

export type GetAzureTrafficCollectorError = AzureOpError;
/** Gets the specified Azure Traffic Collector in a specified resource group */
export const GetAzureTrafficCollector: API.OperationMethod<
  GetAzureTrafficCollectorRequest,
  GetAzureTrafficCollectorResponse,
  GetAzureTrafficCollectorError,
  AzureOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetAzureTrafficCollectorRequest,
  output: GetAzureTrafficCollectorResponse,
  errors: [UnknownAzureError],
  protocol: AzureProtocol,
  retry: Retry.Retry,
}));

export type GetCollectorPolicyError = AzureOpError;
/** Gets the collector policy in a specified Traffic Collector */
export const GetCollectorPolicy: API.OperationMethod<
  GetCollectorPolicyRequest,
  GetCollectorPolicyResponse,
  GetCollectorPolicyError,
  AzureOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetCollectorPolicyRequest,
  output: GetCollectorPolicyResponse,
  errors: [UnknownAzureError],
  protocol: AzureProtocol,
  retry: Retry.Retry,
}));

export type ListAzureTrafficCollectorByResourceGroupError = AzureOpError;
/** Return list of Azure Traffic Collectors in a Resource Group */
export const ListAzureTrafficCollectorByResourceGroup: API.OperationMethod<
  ListAzureTrafficCollectorByResourceGroupRequest,
  AzureTrafficCollectorListResult,
  ListAzureTrafficCollectorByResourceGroupError,
  AzureOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ListAzureTrafficCollectorByResourceGroupRequest,
  output: AzureTrafficCollectorListResult,
  errors: [UnknownAzureError],
  protocol: AzureProtocol,
  retry: Retry.Retry,
}));

export type ListAzureTrafficCollectorBySubscriptionError = AzureOpError;
/** Return list of Azure Traffic Collectors in a subscription */
export const ListAzureTrafficCollectorBySubscription: API.OperationMethod<
  ListAzureTrafficCollectorBySubscriptionRequest,
  AzureTrafficCollectorListResult,
  ListAzureTrafficCollectorBySubscriptionError,
  AzureOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ListAzureTrafficCollectorBySubscriptionRequest,
  output: AzureTrafficCollectorListResult,
  errors: [UnknownAzureError],
  protocol: AzureProtocol,
  retry: Retry.Retry,
}));

export type ListCollectorPoliciesError = AzureOpError;
/** Return list of Collector policies in a Azure Traffic Collector */
export const ListCollectorPolicies: API.OperationMethod<
  ListCollectorPoliciesRequest,
  CollectorPolicyListResult,
  ListCollectorPoliciesError,
  AzureOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ListCollectorPoliciesRequest,
  output: CollectorPolicyListResult,
  errors: [UnknownAzureError],
  protocol: AzureProtocol,
  retry: Retry.Retry,
}));

export type ListNetworkFunctionOperationsError = AzureOpError;
/** Lists all of the available NetworkFunction Rest API operations. */
export const ListNetworkFunctionOperations: API.OperationMethod<
  ListNetworkFunctionOperationsRequest,
  OperationListResult,
  ListNetworkFunctionOperationsError,
  AzureOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ListNetworkFunctionOperationsRequest,
  output: OperationListResult,
  errors: [UnknownAzureError],
  protocol: AzureProtocol,
  retry: Retry.Retry,
}));

export type UpdateAzureTrafficCollectorTagError = AzureOpError;
/** Updates the specified Azure Traffic Collector tags. */
export const UpdateAzureTrafficCollectorTag: API.OperationMethod<
  UpdateAzureTrafficCollectorTagRequest,
  UpdateAzureTrafficCollectorTagResponse,
  UpdateAzureTrafficCollectorTagError,
  AzureOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: UpdateAzureTrafficCollectorTagRequest,
  output: UpdateAzureTrafficCollectorTagResponse,
  errors: [UnknownAzureError],
  protocol: AzureProtocol,
  retry: Retry.Retry,
}));

export type UpdateCollectorPolicyTagError = AzureOpError;
/** Updates the specified Collector Policy tags. */
export const UpdateCollectorPolicyTag: API.OperationMethod<
  UpdateCollectorPolicyTagRequest,
  UpdateCollectorPolicyTagResponse,
  UpdateCollectorPolicyTagError,
  AzureOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: UpdateCollectorPolicyTagRequest,
  output: UpdateCollectorPolicyTagResponse,
  errors: [UnknownAzureError],
  protocol: AzureProtocol,
  retry: Retry.Retry,
}));
