import * as Schema from "effect/Schema";
import { API } from "../../client.ts";
import * as T from "../../traits.ts";
import { BadRequest, Forbidden, NotFound } from "../../errors.ts";
import { SensitiveString } from "../../sensitive.ts";

// Input Schema
export const WarehouseTablesFileCreateInput =
  /*@__PURE__*/ /*#__PURE__*/ Schema.Struct({
    project_id: Schema.String.pipe(T.PathParam()),
    id: Schema.String,
    deleted: Schema.optional(Schema.NullOr(Schema.Boolean)),
    name: Schema.String,
    format: Schema.Literals([
      "CSV",
      "CSVWithNames",
      "Parquet",
      "JSONEachRow",
      "Delta",
      "DeltaS3Wrapper",
    ]),
    created_by: Schema.Struct({
      id: Schema.Number,
      uuid: Schema.String,
      distinct_id: Schema.optional(Schema.NullOr(Schema.String)),
      first_name: Schema.optional(Schema.String),
      last_name: Schema.optional(Schema.String),
      email: Schema.String,
      is_email_verified: Schema.optional(Schema.NullOr(Schema.Boolean)),
      hedgehog_config: Schema.NullOr(
        Schema.Record(Schema.String, Schema.Unknown),
      ),
      role_at_organization: Schema.optional(Schema.Unknown),
    }),
    created_at: Schema.String,
    url_pattern: Schema.String,
    credential: Schema.Struct({
      id: Schema.String,
      created_by: Schema.Struct({
        id: Schema.Number,
        uuid: Schema.String,
        distinct_id: Schema.optional(Schema.NullOr(Schema.String)),
        first_name: Schema.optional(Schema.String),
        last_name: Schema.optional(Schema.String),
        email: Schema.String,
        is_email_verified: Schema.optional(Schema.NullOr(Schema.Boolean)),
        hedgehog_config: Schema.NullOr(
          Schema.Record(Schema.String, Schema.Unknown),
        ),
        role_at_organization: Schema.optional(Schema.Unknown),
      }),
      created_at: Schema.String,
      access_key: Schema.String,
      access_secret: SensitiveString,
    }),
    columns: Schema.Array(Schema.Record(Schema.String, Schema.Unknown)),
    external_data_source: Schema.Struct({
      id: Schema.String,
      created_at: Schema.String,
      created_by: Schema.NullOr(Schema.Number),
      status: Schema.String,
      source_type: Schema.Literals([
        "Ashby",
        "Supabase",
        "CustomerIO",
        "Github",
        "Stripe",
        "Hubspot",
        "Postgres",
        "Zendesk",
        "Snowflake",
        "Salesforce",
        "MySQL",
        "MongoDB",
        "MSSQL",
        "Vitally",
        "BigQuery",
        "Chargebee",
        "Clerk",
        "GoogleAds",
        "TemporalIO",
        "DoIt",
        "GoogleSheets",
        "MetaAds",
        "Klaviyo",
        "Mailchimp",
        "Braze",
        "Mailjet",
        "Redshift",
        "Polar",
        "RevenueCat",
        "LinkedinAds",
        "RedditAds",
        "TikTokAds",
        "BingAds",
        "Shopify",
        "Attio",
        "SnapchatAds",
        "Linear",
        "Intercom",
        "Amplitude",
        "Mixpanel",
        "Jira",
        "ActiveCampaign",
        "Marketo",
        "Adjust",
        "AppsFlyer",
        "Freshdesk",
        "GoogleAnalytics",
        "Pipedrive",
        "SendGrid",
        "Slack",
        "PagerDuty",
        "Asana",
        "Notion",
        "Airtable",
        "Greenhouse",
        "BambooHR",
        "Lever",
        "GitLab",
        "Datadog",
        "Sentry",
        "Pendo",
        "FullStory",
        "AmazonAds",
        "PinterestAds",
        "AppleSearchAds",
        "QuickBooks",
        "Xero",
        "NetSuite",
        "WooCommerce",
        "BigCommerce",
        "PayPal",
        "Square",
        "Zoom",
        "Trello",
        "Monday",
        "ClickUp",
        "Confluence",
        "Recurly",
        "SalesLoft",
        "Outreach",
        "Gong",
        "Calendly",
        "Typeform",
        "Iterable",
        "ZohoCRM",
        "Close",
        "Oracle",
        "DynamoDB",
        "Elasticsearch",
        "Kafka",
        "LaunchDarkly",
        "Braintree",
        "Recharge",
        "HelpScout",
        "Gorgias",
        "Instagram",
        "YouTubeAnalytics",
        "FacebookPages",
        "TwitterAds",
        "Workday",
        "ServiceNow",
        "Pardot",
        "Copper",
        "Front",
        "ChartMogul",
        "Zuora",
        "Paddle",
        "CircleCI",
        "CockroachDB",
        "Firebase",
        "AzureBlob",
        "GoogleDrive",
        "OneDrive",
        "SharePoint",
        "Box",
        "SFTP",
        "MicrosoftTeams",
        "Aircall",
        "Webflow",
        "Okta",
        "Auth0",
        "Productboard",
        "Smartsheet",
        "Wrike",
        "Plaid",
        "SurveyMonkey",
        "Eventbrite",
        "RingCentral",
        "Twilio",
        "Freshsales",
        "Shortcut",
        "ConvertKit",
        "Drip",
        "CampaignMonitor",
        "MailerLite",
        "Omnisend",
        "Brevo",
        "Postmark",
        "Granola",
        "BuildBetter",
        "Convex",
        "ClickHouse",
        "Plain",
      ]),
    }),
    external_schema: Schema.NullOr(
      Schema.Record(Schema.String, Schema.Unknown),
    ),
    options: Schema.optional(Schema.Record(Schema.String, Schema.Unknown)),
  }).pipe(
    T.Http({
      method: "POST",
      path: "/api/projects/{project_id}/warehouse_tables/file/",
      contentType: "form-urlencoded",
    }),
  );
export type WarehouseTablesFileCreateInput =
  typeof WarehouseTablesFileCreateInput.Type;

// Output Schema
export const WarehouseTablesFileCreateOutput =
  /*@__PURE__*/ /*#__PURE__*/ Schema.Void;
export type WarehouseTablesFileCreateOutput =
  typeof WarehouseTablesFileCreateOutput.Type;

// The operation
/**
 * Create, Read, Update and Delete Warehouse Tables.
 *
 * @param project_id - Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/.
 */
export const warehouseTablesFileCreate = /*@__PURE__*/ /*#__PURE__*/ API.make(
  () => ({
    inputSchema: WarehouseTablesFileCreateInput,
    outputSchema: WarehouseTablesFileCreateOutput,
    errors: [BadRequest, Forbidden, NotFound] as const,
  }),
);
